import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createRuntime, type Runtime } from "../src/runtime.js";
import { activateAsset, createDepreciationRun, disposeAsset, generateFixedAssetRegister, previewDepreciation } from "../src/features/fixed-assets/service.js";

const integration=process.env.DATABASE_URL?describe:describe.skip;
integration("fixed assets and depreciation",()=>{
 let runtime:Runtime;const org="org_fixed_assets_test";
 beforeAll(async()=>{runtime=await createRuntime();await runtime.db.query("TRUNCATE backend_outbox_events,audit_logs,users,organizations CASCADE");await runtime.db.query(`INSERT INTO organizations(id,name,base_currency,status) VALUES($1,'Fixed Assets Test','UGX','active')`,[org]);const accounts=[["asset","1500","Equipment","asset","fixed_asset","debit"],["accum","1590","Accumulated Depreciation","asset","contra_asset","credit"],["dep","6500","Depreciation Expense","expense","depreciation","debit"],["cash","1000","Cash","asset","cash","debit"],["gain","4700","Gain on Disposal","revenue","other","credit"],["loss","6700","Loss on Disposal","expense","other","debit"]];for(const row of accounts)await runtime.db.query(`INSERT INTO accounts(id,organization_id,code,name,type,subtype,normal_balance) VALUES($1,$2,$3,$4,$5,$6,$7)`,[row[0],org,...row.slice(1)]);await runtime.db.query(`INSERT INTO fixed_asset_categories(id,organization_id,code,name,asset_account_id,accumulated_depreciation_account_id,depreciation_expense_account_id,disposal_gain_account_id,disposal_loss_account_id,default_useful_life_months) VALUES('cat',$1,'EQUIP','Equipment','asset','accum','dep','gain','loss',12)`,[org]);await runtime.db.query(`INSERT INTO fixed_assets(id,organization_id,category_id,asset_number,name,acquisition_date,acquisition_cost_minor,residual_value_minor,useful_life_months,depreciation_method,created_by) VALUES('fa1',$1,'cat','FA-001','Laptop Fleet','2026-01-01',120000,0,12,'straight_line','tester')`,[org]);});
 afterAll(async()=>{await runtime?.close();});
 it("capitalizes and depreciates straight-line without passing residual value",async()=>{const activation=await activateAsset(runtime,org,"tester","fa1",{inServiceDate:"2026-01-01",creditAccountId:"cash"});expect(activation).toMatchObject({status:"active",accountingPosted:true});const preview=await previewDepreciation(runtime,org,"2026-01-31");expect(preview).toMatchObject({totalMinor:10000,assetCount:1});const run=await createDepreciationRun(runtime,org,"tester",{postingDate:"2026-01-31"},"dep-jan");expect(run).toMatchObject({status:"posted",totalMinor:10000});const asset=(await runtime.db.query(`SELECT accumulated_depreciation_minor::float8 AS accumulated,(acquisition_cost_minor-accumulated_depreciation_minor)::float8 AS book FROM fixed_assets WHERE id='fa1'`)).rows[0];expect(asset).toMatchObject({accumulated:10000,book:110000});});
 it("produces an as-of fixed asset register",async()=>{const report=await generateFixedAssetRegister(runtime,org,{asOf:"2026-01-31"});expect(report.totals).toMatchObject({acquisitionCostMinor:120000,accumulatedDepreciationMinor:10000,netBookValueMinor:110000});expect(report.rows[0]).toMatchObject({assetNumber:"FA-001",netBookValueMinor:110000});});
 it("posts balanced disposal gain accounting",async()=>{const disposal=await disposeAsset(runtime,org,"tester","fa1",{disposalDate:"2026-02-01",proceedsMinor:115000,proceedsAccountId:"cash",reason:"Asset sold"});expect(disposal).toMatchObject({status:"disposed",bookValueMinor:110000,gainMinor:5000,lossMinor:0});const totals=(await runtime.db.query(`SELECT SUM(debit_minor)::float8 AS debit,SUM(credit_minor)::float8 AS credit FROM journal_lines WHERE journal_entry_id=$1`,[disposal.journalEntryId])).rows[0];expect(totals).toMatchObject({debit:125000,credit:125000});});
});
