import { z } from "zod";
import { AppError } from "../../../src/lib/errors";
import type { MobileSyncMutation, MobileSyncMutationContext, PreparedMobileSyncMutation } from "../../mobile-sync/backend/contracts";
import { requireAcademicsWrite } from "./mobile-sync-permissions";
import { type R, guard, unguard, own, requireStableId } from "./mobile-sync-common";
const planShape = z.object({ academicYearId: z.string().optional(), termId: z.string().optional(), classId: z.string().optional(), streamId: z.string().nullable().optional(), subjectId: z.string().optional(), teacherUserId: z.string().optional(), timetableEntryId: z.string().nullable().optional(), schemeItemId: z.string().nullable().optional(), templateId: z.string().nullable().optional(), lessonDate: z.string().optional(), weekNo: z.number().int().positive().nullable().optional(), lessonNo: z.number().int().positive().nullable().optional(), topic: z.string().min(1).max(500).optional(), subtopic: z.string().max(500).nullable().optional(), lessonObjectives: z.string().max(20000).nullable().optional(), priorKnowledge: z.string().max(20000).nullable().optional(), introductionText: z.string().max(30000).nullable().optional(), lessonDevelopment: z.string().max(50000).nullable().optional(), teacherActivities: z.string().max(30000).nullable().optional(), learnerActivities: z.string().max(30000).nullable().optional(), teachingMethods: z.string().max(10000).nullable().optional(), requiredMaterials: z.string().max(10000).nullable().optional(), differentiatedInstruction: z.string().max(20000).nullable().optional(), specialNeedsAccommodations: z.string().max(20000).nullable().optional(), lessonAssessment: z.string().max(20000).nullable().optional(), lessonConclusion: z.string().max(20000).nullable().optional(), homework: z.string().max(20000).nullable().optional(), teacherReflection: z.string().max(20000).nullable().optional() }).strict();
export async function prepareLessonPlan(c: MobileSyncMutationContext, m: MobileSyncMutation): Promise<PreparedMobileSyncMutation> {
    await requireAcademicsWrite(c);
    if (m.kind === "delete") throw new AppError(409, "SERVER_MANAGED_LIFECYCLE", "Lesson plans cannot be deleted offline");
    requireStableId(m.recordId, "Lesson plan");
    const old = await c.db.prepare("SELECT * FROM acad_lesson_plans WHERE id=? AND organization_id=?").bind(m.recordId, c.organizationId).first<R>();
    const p = planShape.safeParse(m.payload);
    if (!p.success) throw new AppError(422, "VALIDATION_ERROR", "Invalid lesson plan", p.error.flatten());
    if (!old) {
        const d = p.data, teacher = d.teacherUserId ?? c.userId;
        await own(c, teacher);
        for (const k of ["academicYearId", "termId", "classId", "subjectId", "lessonDate", "topic"] as const) if (!d[k]) throw new AppError(422, "VALIDATION_ERROR", `${k} is required`);
        return { statements: [guard(c.db, "lesson-plans", m.recordId, c.organizationId), c.db.prepare(`INSERT INTO acad_lesson_plans(id,organization_id,academic_year_id,term_id,class_id,stream_id,subject_id,teacher_user_id,timetable_entry_id,scheme_item_id,template_id,lesson_date,week_no,lesson_no,topic,subtopic,lesson_objectives,prior_knowledge,introduction_text,lesson_development,teacher_activities,learner_activities,teaching_methods,required_materials,differentiated_instruction,special_needs_accommodations,lesson_assessment,lesson_conclusion,homework,teacher_reflection,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?,?)`).bind(m.recordId, c.organizationId, d.academicYearId, d.termId, d.classId, d.streamId ?? null, d.subjectId, teacher, d.timetableEntryId ?? null, d.schemeItemId ?? null, d.templateId ?? null, d.lessonDate, d.weekNo ?? null, d.lessonNo ?? null, d.topic, d.subtopic ?? null, d.lessonObjectives ?? null, d.priorKnowledge ?? null, d.introductionText ?? null, d.lessonDevelopment ?? null, d.teacherActivities ?? null, d.learnerActivities ?? null, d.teachingMethods ?? null, d.requiredMaterials ?? null, d.differentiatedInstruction ?? null, d.specialNeedsAccommodations ?? null, d.lessonAssessment ?? null, d.lessonConclusion ?? null, d.homework ?? null, d.teacherReflection ?? null, c.userId, m.clientTimestamp, m.clientTimestamp), unguard(c.db, "lesson-plans", m.recordId, c.organizationId)], serverPayload: { id: m.recordId, ...d, teacherUserId: teacher, status: "draft", createdBy: c.userId, createdAt: m.clientTimestamp, updatedAt: m.clientTimestamp } };
    }
    await own(c, String(old.teacher_user_id));
    if (!["draft", "rejected"].includes(String(old.status))) throw new AppError(409, "LESSON_PLAN_LOCKED", "Only draft or rejected lesson plans can be edited offline");
    const allowed: R = { topic: "topic", subtopic: "subtopic", lessonObjectives: "lesson_objectives", priorKnowledge: "prior_knowledge", introductionText: "introduction_text", lessonDevelopment: "lesson_development", teacherActivities: "teacher_activities", learnerActivities: "learner_activities", teachingMethods: "teaching_methods", requiredMaterials: "required_materials", differentiatedInstruction: "differentiated_instruction", specialNeedsAccommodations: "special_needs_accommodations", lessonAssessment: "lesson_assessment", lessonConclusion: "lesson_conclusion", homework: "homework", teacherReflection: "teacher_reflection" };
    const e = Object.entries(p.data).filter(([k]) => allowed[k]);
    if (!e.length) throw new AppError(422, "VALIDATION_ERROR", "No editable lesson plan fields supplied");
    return { statements: [guard(c.db, "lesson-plans", m.recordId, c.organizationId), c.db.prepare(`UPDATE acad_lesson_plans SET ${e.map(([k]) => `${allowed[k]}=?`).join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(...e.map(([, x]) => x ?? null), m.recordId, c.organizationId), unguard(c.db, "lesson-plans", m.recordId, c.organizationId)], serverPayload: { ...old, ...p.data, id: m.recordId } };
}
const deliveryShape = z.object({ lessonPlanId: z.string().nullable().optional(), attendanceSessionId: z.string().nullable().optional(), actualStartsAt: z.string().nullable().optional(), actualEndsAt: z.string().nullable().optional(), deliveryStatus: z.enum(["scheduled", "taught", "missed", "postponed", "recovery"]).optional(), actualTopic: z.string().max(500).nullable().optional(), actualSubtopic: z.string().max(500).nullable().optional(), studentAttendanceSummary: z.string().max(20000).nullable().optional(), lessonNotes: z.string().max(30000).nullable().optional(), missedReason: z.string().max(10000).nullable().optional(), recoveryDate: z.string().nullable().optional() }).strict();
export async function prepareDelivery(c: MobileSyncMutationContext, m: MobileSyncMutation): Promise<PreparedMobileSyncMutation> {
    await requireAcademicsWrite(c);
    if (m.kind === "delete") throw new AppError(409, "SERVER_MANAGED_LIFECYCLE", "Lesson deliveries cannot be deleted offline");
    const old = await c.db.prepare("SELECT * FROM acad_lesson_deliveries WHERE id=? AND organization_id=?").bind(m.recordId, c.organizationId).first<R>();
    if (!old) throw new AppError(404, "DELIVERY_NOT_FOUND", "Lesson delivery not found; synchronize the timetable first");
    await own(c, String(old.teacher_user_id));
    const p = deliveryShape.safeParse(m.payload);
    if (!p.success) throw new AppError(422, "VALIDATION_ERROR", "Invalid lesson delivery", p.error.flatten());
    let attendance = p.data.studentAttendanceSummary ?? null;
    if (p.data.attendanceSessionId) {
        const a = await c.db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status IN ('present','late') THEN 1 ELSE 0 END) present,SUM(CASE WHEN status='absent' THEN 1 ELSE 0 END) absent FROM att_records WHERE organization_id=? AND session_id=? AND person_type='student' AND official=1`).bind(c.organizationId, p.data.attendanceSessionId).first<R>();
        attendance = JSON.stringify({ total: Number(a?.total || 0), present: Number(a?.present || 0), absent: Number(a?.absent || 0) });
    }
    const st: D1PreparedStatement[] = [guard(c.db, "deliveries", m.recordId, c.organizationId), c.db.prepare(`UPDATE acad_lesson_deliveries SET lesson_plan_id=COALESCE(?,lesson_plan_id),canonical_attendance_session_id=COALESCE(?,canonical_attendance_session_id),actual_starts_at=?,actual_ends_at=?,delivery_status=COALESCE(?,delivery_status),actual_topic=?,actual_subtopic=?,student_attendance_summary=COALESCE(?,student_attendance_summary),lesson_notes=?,missed_reason=?,recovery_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(p.data.lessonPlanId ?? null, p.data.attendanceSessionId ?? null, p.data.actualStartsAt ?? null, p.data.actualEndsAt ?? null, p.data.deliveryStatus ?? null, p.data.actualTopic ?? null, p.data.actualSubtopic ?? null, attendance, p.data.lessonNotes ?? null, p.data.missedReason ?? null, p.data.recoveryDate ?? null, m.recordId, c.organizationId), unguard(c.db, "deliveries", m.recordId, c.organizationId)];
    if (p.data.deliveryStatus === "taught" && p.data.lessonPlanId) {
        st.push(c.db.prepare("UPDATE acad_lesson_plans SET status='delivered',updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND status='approved'").bind(p.data.lessonPlanId, c.organizationId), c.db.prepare(`UPDATE acad_scheme_items SET coverage_status='covered',covered_at=COALESCE(covered_at,CURRENT_TIMESTAMP),teacher_reflection=COALESCE(?,teacher_reflection),updated_at=CURRENT_TIMESTAMP WHERE id=(SELECT scheme_item_id FROM acad_lesson_plans WHERE id=? AND organization_id=?) AND organization_id=?`).bind(p.data.lessonNotes ?? null, p.data.lessonPlanId, c.organizationId, c.organizationId));
    }
    return { statements: st, serverPayload: { ...old, ...p.data, studentAttendanceSummary: attendance, id: m.recordId } };
}
