// AUTO-GENERATED by scripts/sync-modules.mjs. Do not edit by hand.
import { moduleDefinition as module0 } from "./academics/backend/module";
import { moduleDefinition as module1 } from "./attendance/backend/module";
import { moduleDefinition as module2 } from "./books/backend/module";
import { moduleDefinition as module3 } from "./communications/backend/module";
import { moduleDefinition as module4 } from "./contacts/backend/module";
import { moduleDefinition as module5 } from "./exams/backend/module";
import { moduleDefinition as module6 } from "./human-resources/backend/module";
import { moduleDefinition as module7 } from "./ledgerly/backend/module";
import { moduleDefinition as module8 } from "./mobile-sync/backend/module";
import { moduleDefinition as module9 } from "./payroll-payments/backend/module";
import { moduleDefinition as module10 } from "./printerly/backend/module";
import { moduleDefinition as module11 } from "./school/backend/module";
import { moduleDefinition as module12 } from "./security-camera/backend/module";
import { moduleDefinition as module13 } from "./tasks-work/backend/module";

export const backendModules = [module0, module1, module2, module3, module4, module5, module6, module7, module8, module9, module10, module11, module12, module13].sort((a,b)=>(a.order ?? 100)-(b.order ?? 100)||a.name.localeCompare(b.name));
