// AUTO-GENERATED by scripts/sync-modules.mjs. Do not edit by hand.
export const moduleCatalog = [
  {
    "key": "academics",
    "name": "Academics",
    "version": "2.1.0",
    "description": "Scheme-led teaching and learning with rule-driven lesson-aware timetables, term topics, competencies, lesson plans, delivery, lesson-level continuous assessment, supervision and academic operations.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "school-management"
      ],
      "requiresDataFrom": [
        "school-management"
      ],
      "sharedCore": [
        "school_academic_years",
        "school_terms",
        "school_departments",
        "school_classes",
        "school_streams",
        "school_subjects",
        "school_staff_profiles",
        "school_staff_teaching_assignments",
        "school_lesson_periods",
        "school_files",
        "att_sessions",
        "att_records",
        "school_students",
        "school_enrollments",
        "users"
      ],
      "features": [
        "scheme-first-learning-cycle",
        "term-topics",
        "scheme-lessons",
        "lesson-competencies",
        "competency-success-criteria",
        "lesson-plan-from-scheme",
        "lesson-plan-workflow",
        "lesson-delivery",
        "lesson-level-continuous-assessment",
        "learner-lesson-marks",
        "competency-levels",
        "marks-draft-submit-reopen",
        "curriculum-coverage",
        "professional-timetable-rule-engine",
        "hard-soft-timetable-rules",
        "ai-timetable-drafting",
        "period-timeframe-matrix",
        "lesson-aware-timetable-occurrences",
        "scheme-lesson-period-linking",
        "lesson-plan-period-context",
        "timetable-exceptions",
        "teacher-absence-recovery",
        "room-unavailability",
        "school-closure-handling",
        "recovery-lesson-queue",
        "class-teacher-department-timetables",
        "room-allocation",
        "single-double-lessons",
        "teacher-availability",
        "conflict-detection",
        "substitute-lessons",
        "temporary-timetable-changes",
        "timetable-approval-publishing",
        "printable-timetables",
        "workload-analysis",
        "schemes-of-work",
        "hod-dos-approval",
        "scheme-version-history",
        "lesson-plans",
        "lesson-plan-templates",
        "lesson-delivery-register",
        "coverage-tracking",
        "recovery-lessons",
        "teacher-supervision",
        "observations",
        "followups",
        "book-record-inspection",
        "evidence-attachments"
      ]
    }
  },
  {
    "key": "agentic-employees",
    "name": "AI Employees",
    "version": "2.8.0",
    "description": "Tenant-safe AI school employees with Chat Studio and a high-end Agentic Command Center featuring searchable slash commands, query criteria, composite multi-tool reports, guided evidence analysis and explanation, output selection, governed writes and professional exports.",
    "category": "automation",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "school-management"
      ],
      "requiresDataFrom": [
        "school-management",
        "academics",
        "communications",
        "human-resources",
        "books",
        "attendance",
        "exams",
        "payroll-payments",
        "tasks-work",
        "printerly"
      ],
      "sharedCore": [
        "organizations",
        "users",
        "school_students",
        "school_guardians",
        "school_student_guardians",
        "school_staff_profiles"
      ],
      "providers": [
        "openai",
        "google",
        "anthropic",
        "groq",
        "cloudflare",
        "openrouter",
        "ollama",
        "custom"
      ],
      "providerScope": "per-organization",
      "modelRouting": [
        "luna",
        "terra",
        "sol"
      ],
      "agents": [
        "secretary",
        "dos",
        "bursar",
        "headteacher",
        "hr",
        "librarian"
      ],
      "features": [
        "per-school-ai-provider",
        "encrypted-school-api-keys",
        "provider-model-catalog",
        "custom-model-ids",
        "provider-connection-test",
        "advanced-generation-controls",
        "agent-chat-studio",
        "live-agent-status",
        "verified-data-chat",
        "inline-editable-approvals",
        "inline-governed-execution",
        "professional-markdown-tables",
        "conversation-artifact-cards",
        "resumable-conversations",
        "role-specific-starter-prompts",
        "responsive-chat-ui",
        "conversation-memory",
        "working-memory",
        "institutional-memory",
        "memory-search",
        "memory-management-ui",
        "memory-provenance",
        "memory-due-dates",
        "bounded-tool-calling",
        "tenant-isolation",
        "human-approval-gates",
        "tool-audit-log",
        "task-execution",
        "model-tier-routing",
        "custom-agent-prompts",
        "academics-supervision-tools",
        "hr-leave-tools",
        "fees-collection-analysis",
        "books-stock-and-distribution-tools",
        "communications-health-tools",
        "approved-communications-execution",
        "proactive-schedules",
        "proactive-run-history",
        "school-timezone-scheduling",
        "controlled-agent-delegation",
        "headteacher-daily-brief",
        "guardian-family-resolution",
        "cumulative-family-reports",
        "published-results-readonly-analysis",
        "cumulative-attendance-analysis",
        "family-finance-analysis",
        "durable-event-inbox",
        "payment-posted-reactions",
        "absence-escalation",
        "approved-leave-reactions",
        "low-stock-reactions",
        "overdue-lesson-plan-reactions",
        "event-reaction-retries",
        "event-reaction-audit",
        "headteacher-exception-briefing",
        "event-to-action-proposals",
        "approved-work-task-execution",
        "idempotent-action-execution",
        "conversation-task-preparation",
        "postgresql-selfhost-runtime",
        "node-hono-runtime",
        "professional-pdf-generation",
        "docx-generation",
        "xlsx-generation",
        "pptx-generation",
        "professional-black-font-reports",
        "report-tables",
        "report-charts",
        "data-as-of-metadata",
        "saved-agent-documents",
        "printable-pdf-companions",
        "printerly-governed-printing",
        "printer-policy-and-quota-enforcement",
        "image-capture",
        "image-preview",
        "vision-ocr",
        "handwriting-and-table-extraction",
        "image-evidence-workflows",
        "role-scoped-system-catalog",
        "delegated-api-read-access",
        "governed-system-mutations",
        "short-lived-delegated-jwt",
        "agent-role-and-user-scope-intersection",
        "legacy-action-audit-route",
        "slash-quick-command-palette",
        "500-plus-command-alias-catalog",
        "schema-driven-command-forms",
        "searchable-reference-pickers",
        "deterministic-command-validation",
        "direct-read-quick-commands",
        "governed-write-quick-commands",
        "dedicated-agentic-command-center",
        "query-criteria-builder",
        "command-output-format-selector",
        "interactive-command-results",
        "command-csv-export",
        "command-xlsx-export",
        "command-pdf-export",
        "expanded-command-synonyms",
        "5000-route-node-capability-ceiling",
        "composite-report-planner",
        "multi-tool-read-plans",
        "cross-module-student-joins",
        "repeated-tool-period-comparisons",
        "composite-report-criteria-prompts",
        "composite-report-export",
        "guided-analysis-catalog",
        "guided-account-for",
        "cross-entity-analysis-resolution",
        "teacher-student-account-entity-detection",
        "evidence-family-guidance",
        "dynamic-analysis-planning",
        "counter-evidence-analysis",
        "non-template-analysis-synthesis",
        "analysis-suggested-follow-up",
        "43-domain-analysis-knowledge-base"
      ]
    }
  },
  {
    "key": "attendance",
    "name": "Attendance",
    "version": "1.3.0",
    "description": "Canonical student and staff attendance, devices, offline capture, biometrics, exceptions, corrections and reporting.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "school-management"
      ],
      "requiresDataFrom": [
        "school-management"
      ],
      "integratesWith": [
        "academics",
        "payroll-payments",
        "communications",
        "school-management"
      ],
      "captureMethods": [
        "FACE",
        "QR",
        "NFC",
        "MANUAL",
        "TEACHER_REGISTER",
        "ADMIN_OVERRIDE",
        "IMPORT",
        "API"
      ],
      "offline": true,
      "primaryKioskPlatform": "android",
      "features": [
        "daily-attendance",
        "class-and-lesson-registers",
        "staff-time",
        "in-out-events",
        "offline-sync",
        "deduplication",
        "biometric-profiles",
        "test-spoof-controls",
        "devices",
        "qr-kiosk-enrollment",
        "exceptions",
        "corrections",
        "reports",
        "notification-rules"
      ],
      "mobileClient": "react-native-android",
      "cameraSource": "device",
      "externalCameraSupport": false,
      "deviceCameraOnly": true,
      "faceEngine": "facenet-128-v1",
      "faceDetection": "mlkit-bundled",
      "faceMatching": "on-device-1-n",
      "activeLiveness": "blink-or-head-turn",
      "encryptedTemplateSync": true,
      "faceTestOverrides": [
        "screen-image",
        "printed-image"
      ]
    }
  },
  {
    "key": "books",
    "name": "Books",
    "version": "1.1.0",
    "description": "Standalone writing-book stock, learner issue tracking and reporting linked to School Management learner and academic data.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "school-management"
      ],
      "requiresDataFrom": [
        "school-management"
      ],
      "sharedCore": [
        "organizations",
        "users",
        "school_students",
        "school_classes",
        "school_streams",
        "school_academic_years",
        "school_terms"
      ],
      "bookTypes": [
        "small",
        "a4"
      ],
      "offline": true,
      "offlineModel": "immutable-operation-intents",
      "features": [
        "stock-receipts-and-adjustments",
        "individual-learner-issues",
        "bulk-class-and-stream-issues",
        "transaction-reversals",
        "learner-book-ledger",
        "class-and-stream-reports",
        "term-and-year-reports",
        "stock-balance-report",
        "unissued-learners-report",
        "csv-export",
        "audit-friendly-history",
        "offline-stock-operation-intents",
        "year-scale-mobile-change-feed"
      ]
    }
  },
  {
    "key": "communications",
    "name": "Messages & Notifications",
    "version": "1.0.0",
    "description": "Platform-wide SMS and approved-template WhatsApp campaigns for School, Exams, Finance, Attendance, Discipline, Tasks & Work and future modules.",
    "category": "platform",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "channels": [
        "sms",
        "whatsapp"
      ],
      "whatsappTemplate": {
        "name": "general_app_update",
        "language": "en_US",
        "category": "UTILITY"
      },
      "sharedCore": [
        "organizations",
        "users",
        "memberships",
        "contacts",
        "contact_people",
        "school_students",
        "school_guardians",
        "school_staff_profiles"
      ],
      "features": [
        "message-types",
        "audience-preview",
        "fee-reminders",
        "published-results",
        "student-parent-messaging",
        "teacher-staff-messaging",
        "attendance-notices",
        "discipline-notices",
        "task-work-updates",
        "scheduled-campaigns",
        "delivery-history",
        "retry-failed",
        "recipient-preferences",
        "audit-snapshots"
      ]
    }
  },
  {
    "key": "contacts",
    "name": "Contacts",
    "version": "1.0.0",
    "description": "Shared people and organizations directory assembled from the capabilities enabled for each organization.",
    "category": "platform",
    "core": true,
    "active": true,
    "manifest": {
      "standalone": true,
      "owns": [
        "contacts",
        "contact_people",
        "contact_addresses"
      ],
      "discoversEnabledModules": true,
      "contactSources": {
        "ledgerly-core": [
          "customer",
          "supplier",
          "employee",
          "other"
        ],
        "communications": [
          "sms",
          "whatsapp"
        ],
        "school-management": [
          "student",
          "guardian",
          "staff"
        ],
        "tasks-work": [
          "organization_user"
        ]
      }
    }
  },
  {
    "key": "exams",
    "name": "Examinations",
    "version": "1.0.0",
    "description": "Standalone examinations, marks, Uganda PLE grading, report cards, academic reports and audit workflows linked to School Management shared data.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresDataFrom": [
        "school-management"
      ],
      "sharedCore": [
        "organizations",
        "users",
        "school_students",
        "school_classes",
        "school_streams",
        "school_subjects",
        "school_academic_years",
        "school_terms",
        "att_records"
      ],
      "features": [
        "exam-crud",
        "class-enrolment",
        "subject-configuration",
        "bulk-marks-entry",
        "mark-audit",
        "ple-grading",
        "best-four-aggregate",
        "division-ranking",
        "comment-rules",
        "report-cards",
        "class-marksheets",
        "academic-reports",
        "publication"
      ],
      "reportStyle": "ported-from-attached-exams-project"
    }
  },
  {
    "key": "file-manager",
    "name": "Documents & Files",
    "version": "1.0.0",
    "description": "Unified organization document library for uploaded, scanned and Ledgerly-generated files with folders, versions and record links.",
    "category": "operations",
    "core": true,
    "active": true,
    "manifest": {
      "standalone": true,
      "sharedCore": [
        "organizations",
        "users",
        "files"
      ],
      "requiresDataFrom": [
        "agentic-employees",
        "school-management",
        "printerly"
      ],
      "features": [
        "folders",
        "multi-file-upload",
        "generated-document-catalog",
        "scanner-document-catalog",
        "school-file-catalog",
        "version-history",
        "entity-links",
        "pdf-image-preview",
        "download",
        "archive-trash",
        "source-traceability"
      ]
    }
  },
  {
    "key": "human-resources",
    "name": "Human Resources",
    "version": "1.0.0",
    "description": "Standalone workforce, employment, departments, onboarding and leave management using people from enabled modules.",
    "category": "people",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "discoversEnabledModules": true,
      "peopleSources": {
        "contacts": [
          "employee"
        ],
        "school-management": [
          "staff"
        ],
        "tasks-work": [
          "organization_user"
        ]
      },
      "features": [
        "workforce-directory",
        "departments",
        "employment-records",
        "onboarding",
        "leave-types",
        "leave-requests",
        "approvals",
        "audit"
      ]
    }
  },
  {
    "key": "ledgerly-core",
    "name": "Ledgerly Finance Core",
    "version": "1.0.0",
    "description": "Core accounting, finance operations and authoritative offline finance projections for Ledgerly.",
    "category": "finance",
    "core": true,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "contacts"
      ],
      "integratesWith": [
        "school-management",
        "payroll-payments",
        "human-resources"
      ],
      "offline": true,
      "mobileSourceOfTruth": "server",
      "offlineWritable": [
        "document-intents",
        "journal-intents"
      ],
      "offlineForbidden": [
        "posting",
        "reversals",
        "period-closing",
        "bank-reconciliation",
        "approvals"
      ],
      "features": [
        "chart-of-accounts",
        "journals",
        "documents",
        "banking",
        "budgets",
        "fiscal-periods",
        "inventory",
        "tax",
        "reports",
        "projects",
        "dimensions",
        "offline-draft-intents",
        "year-scale-mobile-change-feed"
      ]
    }
  },
  {
    "key": "mobile-sync",
    "name": "Mobile Sync Core",
    "version": "1.0.0",
    "description": "Offline-first mobile synchronization, device grants, idempotent mutation ordering, conflict/version controls, tombstones, resumable pull cursors and recovery.",
    "category": "platform",
    "core": true,
    "active": true,
    "manifest": {
      "standalone": true,
      "backendOnly": true,
      "protocolVersion": 1,
      "offlineGrantDays": 400,
      "features": [
        "offline-device-grants",
        "idempotent-batches",
        "stable-client-uuids",
        "record-versioning",
        "ordered-mutations",
        "duplicate-prevention",
        "tombstones",
        "dependency-aware-sync",
        "partial-sync-recovery",
        "retry-handling",
        "per-collection-pull-cursors",
        "schema-version-acknowledgements",
        "audit-events",
        "interrupted-sync-recovery"
      ]
    }
  },
  {
    "key": "payroll-payments",
    "name": "Payroll & Payments",
    "version": "1.0.0",
    "description": "Complete payroll calculation, statutory deductions, payslips, salary batches, receipts, supplier payments, allocations and reversals.",
    "category": "finance",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "discoversEnabledModules": true,
      "requiredData": [
        "contacts",
        "accounts",
        "journals"
      ],
      "optionalSources": [
        "human-resources",
        "school-management",
        "communications"
      ],
      "features": [
        "employees",
        "salary-components",
        "statutory-rules",
        "payroll-inputs",
        "calculation",
        "approval",
        "posting",
        "reversal",
        "payslips",
        "delivery",
        "payment-batches",
        "receipts",
        "supplier-payments",
        "allocations",
        "reversals",
        "webhooks"
      ]
    }
  },
  {
    "key": "printerly",
    "name": "Printerly",
    "version": "1.13.0",
    "description": "Secure remote printing and scanning with governance, privacy, supplies, procurement and SLA-backed service operations.",
    "category": "operations",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "sharedCore": [
        "organizations",
        "users",
        "permissions",
        "files",
        "projects",
        "dimensions",
        "journals",
        "notifications",
        "reports"
      ],
      "features": [
        "remote-printing",
        "global-print-with-printerly",
        "scannerly",
        "department-project-charging",
        "print-cost-accounting",
        "ledger-journal-posting",
        "printer-health",
        "multi-channel-alerts",
        "usage-reporting",
        "monthly-print-quotas",
        "automatic-print-rules",
        "approval-workflows",
        "scheduled-printing",
        "multi-document-batches",
        "audit-compliance-center",
        "printer-pools",
        "default-auto-pool",
        "load-aware-smart-routing",
        "capability-aware-routing",
        "pool-priority-routing",
        "automatic-printer-failover",
        "routing-audit-events",
        "secure-release",
        "single-use-release-pin",
        "high-entropy-qr-release-token",
        "lan-release-station",
        "release-attempt-throttling",
        "station-printer-pinning",
        "document-retention-policies",
        "automatic-r2-purge",
        "legal-holds",
        "retention-audit-events",
        "storage-inventory",
        "school-file-preservation",
        "priority-queue",
        "cups-node",
        "sane-scanner",
        "restart-safe-duplicate-prevention",
        "consumables-inventory",
        "stock-movement-ledger",
        "cups-marker-level-monitoring",
        "low-stock-alerts",
        "preventive-maintenance",
        "maintenance-service-log",
        "maintenance-due-alerts",
        "supplier-directory",
        "supplier-consumable-catalog",
        "replenishment-recommendations",
        "automatic-reorder-drafts",
        "purchase-request-approvals",
        "partial-receiving",
        "atomic-receipt-restock",
        "procurement-history",
        "service-desk",
        "sla-management",
        "automatic-incident-creation",
        "sla-breach-alerts",
        "service-ticket-timeline",
        "maintenance-window-planning",
        "service-history-linkage"
      ]
    }
  },
  {
    "key": "school-management",
    "name": "School Management",
    "version": "1.11.0",
    "description": "School administration, fees, promotion, discipline, students, staff, identity, mobile PIN access and academic setup",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "backendModules": [
        "setup",
        "iam",
        "mobile-pin-access",
        "student-management",
        "promotion-engine",
        "discipline-behaviour",
        "staff-teacher-management",
        "files",
        "fees-billing"
      ],
      "plannedModules": [
        "library",
        "boarding",
        "transport",
        "communications"
      ],
      "accountingIntegration": true,
      "integratesWith": [
        "academics",
        "attendance",
        "communications",
        "exams"
      ]
    }
  },
  {
    "key": "security-camera",
    "name": "Security Cameras",
    "version": "0.17.0",
    "description": "Local-first Ledgerly CCTV with Android camera appliances, immutable recording integrity, legal holds, forensic export manifests, chain-of-custody auditing, certified deployment readiness, automatic health remediation, failover and local/NAS archive protection.",
    "category": "operations",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "sharedCore": [
        "organizations",
        "users",
        "permissions",
        "mobile-sync",
        "communications"
      ],
      "securityScopes": [
        "security:read",
        "security:live",
        "security:export",
        "security:review",
        "security:manage"
      ],
      "features": [
        "qr-camera-pairing",
        "one-time-nvr-pairing",
        "whip-camera-publishing",
        "whep-live-view",
        "continuous-nvr-recording",
        "direct-lan-mp4-segment-fallback",
        "persistent-phone-segment-queue",
        "bounded-offline-spool",
        "appliance-diagnostics",
        "automatic-health-remediation",
        "fleet-health-scoring",
        "deployment-readiness-score",
        "commissioning-certificates",
        "sha256-recording-integrity",
        "immutable-recording-fingerprint-baselines",
        "chained-segment-integrity",
        "integrity-sidecar-manifests",
        "integrity-verification-history",
        "critical-recording-tamper-alerts",
        "incident-window-integrity-verification",
        "security-integrity-workspace",
        "legal-holds",
        "offline-legal-hold-enforcement",
        "chain-of-custody-log",
        "forensic-export-source-manifests",
        "forensic-export-sha256",
        "optional-hmac-evidence-signing",
        "security-forensics-workspace",
        "camera-focused-ci",
        "nvr-package-smoke-test",
        "android-foreground-appliance-service",
        "camera-and-nvr-heartbeats",
        "camera-server-assignment",
        "recording-policy-control",
        "recording-metadata-sync",
        "recording-timeline",
        "short-lived-playback-grants",
        "time-range-clip-export",
        "protected-clips",
        "multi-volume-storage",
        "storage-retention",
        "nvr-runtime-health",
        "operational-alerts",
        "motion-event-heuristic",
        "optional-person-object-detector",
        "evidence-snapshots",
        "incident-protection-windows",
        "visual-camera-zones",
        "camera-groups",
        "multi-camera-monitor-wall",
        "fleet-diagnostics",
        "camera-lifecycle-controls",
        "systemd-production-service",
        "camera-specific-permission-scopes",
        "security-audit-trail",
        "notification-escalation-policies",
        "communications-sms-whatsapp-delivery-bridge",
        "resend-email-alert-delivery",
        "signed-webhook-alert-delivery",
        "security-in-app-inbox",
        "automatic-primary-secondary-nvr-failover",
        "automatic-primary-failback",
        "nvr-self-validation",
        "local-nas-backup-replication",
        "backup-integrity-sidecars",
        "outbound-only-nvr-cloud-connectivity"
      ]
    }
  },
  {
    "key": "tasks-work",
    "name": "Tasks & Work",
    "version": "1.1.0",
    "description": "Projects, tasks and execution workflows blended with Ledgerly organizations, users, contacts, people and School staff.",
    "category": "operations",
    "core": false,
    "active": true,
    "manifest": {
      "backendModules": [
        "teams",
        "shared-contacts",
        "projects",
        "tasks",
        "subtasks",
        "assignees",
        "followers",
        "checklists",
        "comments",
        "time-tracking",
        "notifications",
        "reminders",
        "whatsapp-webhook"
      ],
      "communications": [
        "resend",
        "egosms",
        "ulib-whatsapp-hub"
      ],
      "source": "kawalyauma/tasks-work-backend",
      "sourceCommit": "19bda3eee6018bd2f5631a1353adcd71ad366da9",
      "sharedCore": [
        "organizations",
        "users",
        "memberships",
        "contacts",
        "contact_people",
        "school_staff_profiles"
      ]
    }
  }
] as const;
