import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";
import { createJournal, ensureFinanceProvisioned, postJournal, reversalPreview, reverseJournal } from "./service.js";

const accountInput=z.object({code:z.string().trim().min(1).max(30),name:z.string().trim().min(1).max(160),type:z.enum(["asset","liability","equity","revenue","expense"]),subtype:z.string().trim().max(80).optional(),normalBalance:z.enum(["debit","credit"]),currency:z.string().length(3).transform(v=>v.toUpperCase()).optional(),allowPosting:z.boolean().default(true),parentAccountId:z.string().nullable().optional(),accountGroupId:z.string().nullable().optional(),active:z.boolean().default(true)});
const groupInput=z.object({code:z.string().trim().min(1).max(30),name:z.string().trim().min(1).max(160),type:z.enum(["asset","liability","equity","revenue","expense"]),parentGroupId:z.string().nullable().optional(),active:z.boolean().default(true)});
const lineInput=z.object({accountId:z.string().min(1),description:z.string().max(500).optional(),debitMinor:z.number().int().nonnegative().optional(),creditMinor:z.number().int().nonnegative().optional(),contactId:z.string().optional(),projectId:z.string().optional(),classId:z.string().optional(),departmentId:z.string().optional(),locationId:z.string().optional(),taxCode:z.string().max(30).optional(),dimensions:z.record(z.string(),z.union([z.string(),z.number(),z.boolean(),z.null()])).optional()});
const journalInput=z.object({transactionDate:z.iso.date(),postingDate:z.iso.date(),description:z.string().min(1).max(500),reference:z.string().max(100).optional(),currency:z.string().length(3).transform(v=>v.toUpperCase()),exchangeRateMicros:z.number().int().positive().optional(),sourceType:z.string().max(50).optional(),sourceId:z.string().max(100).optional(),lines:z.array(lineInput).min(2).max(500)});
const reversalInput=z.object({postingDate:z.iso.date(),reason:z.string().trim().min(3).max(500)});

function pagination(c:{req:{query:(name:string)=>string|undefined}}){const rawLimit=Number(c.req.query("limit")??50),rawOffset=Number(c.req.query("offset")??0);return{limit:Number.isSafeInteger(rawLimit)?Math.min(200,Math.max(1,rawLimit)):50,offset:Number.isSafeInteger(rawOffset)?Math.max(0,rawOffset):0};}
async function assertParentAccount(runtime:Runtime,org:string,id:string|undefined|null,selfId?:string){if(!id)return;if(id===selfId)throw new AppError(422,"INVALID_PARENT","An account cannot be its own parent");const row=await runtime.db.query("SELECT 1 FROM accounts WHERE id=$1 AND organization_id=$2",[id,org]);if(!row.rowCount)throw new AppError(422,"INVALID_PARENT","Parent account not found");}
async function assertGroup(runtime:Runtime,org:string,id:string|undefined|null){if(!id)return;const row=await runtime.db.query("SELECT 1 FROM account_groups WHERE id=$1 AND organization_id=$2",[id,org]);if(!row.rowCount)throw new AppError(422,"INVALID_GROUP","Account group not found");}

export function createAccountsRoutes(runtime:Runtime){
  const router=new Hono<AppEnv>(); router.use("*",async(c,next)=>{await ensureFinanceProvisioned(runtime,c.get("principal").organizationId);await next();});
  router.get("/",requireScope("accounts:read"),async c=>{const p=c.get("principal"),{limit,offset}=pagination(c),r=await runtime.db.query(`SELECT id,code,name,type,subtype,normal_balance AS "normalBalance",currency,allow_posting AS "allowPosting",active,parent_account_id AS "parentAccountId",account_group_id AS "accountGroupId",created_at AS "createdAt" FROM accounts WHERE organization_id=$1 ORDER BY code LIMIT $2 OFFSET $3`,[p.organizationId,limit,offset]);return c.json({data:r.rows,pagination:{limit,offset}});});
  router.post("/",requireScope("accounts:write"),async c=>{const s=accountInput.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid account",s.error.flatten());const p=c.get("principal"),v=s.data,id=createId("acc");await assertParentAccount(runtime,p.organizationId,v.parentAccountId);await assertGroup(runtime,p.organizationId,v.accountGroupId);await runtime.db.query(`INSERT INTO accounts(id,organization_id,code,name,type,subtype,normal_balance,currency,allow_posting,parent_account_id,account_group_id,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[id,p.organizationId,v.code,v.name,v.type,v.subtype??null,v.normalBalance,v.currency??null,v.allowPosting,v.parentAccountId??null,v.accountGroupId??null,v.active]);return c.json({data:{id,...v}},201);});
  router.put("/:id",requireScope("accounts:write"),async c=>{const s=accountInput.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid account",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=s.data;await assertParentAccount(runtime,p.organizationId,v.parentAccountId,id);await assertGroup(runtime,p.organizationId,v.accountGroupId);const r=await runtime.db.query(`UPDATE accounts SET code=$1,name=$2,type=$3,subtype=$4,normal_balance=$5,currency=$6,allow_posting=$7,parent_account_id=$8,account_group_id=$9,active=$10,updated_at=CURRENT_TIMESTAMP WHERE id=$11 AND organization_id=$12`,[v.code,v.name,v.type,v.subtype??null,v.normalBalance,v.currency??null,v.allowPosting,v.parentAccountId??null,v.accountGroupId??null,v.active,id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Account not found");return c.json({data:{id,...v}});});
  router.patch("/:id/active",requireScope("accounts:write"),async c=>{const s=z.object({active:z.boolean()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid status");const p=c.get("principal"),id=c.req.param("id"),r=await runtime.db.query("UPDATE accounts SET active=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3",[s.data.active,id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Account not found");return c.json({data:{id,active:s.data.active}});});
  router.delete("/:id",requireScope("accounts:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),used=await runtime.db.query("SELECT 1 FROM journal_lines WHERE organization_id=$1 AND account_id=$2 LIMIT 1",[p.organizationId,id]);if(used.rowCount)throw new AppError(409,"ACCOUNT_IN_USE","An account with transactions can only be deactivated");const r=await runtime.db.query("DELETE FROM accounts WHERE id=$1 AND organization_id=$2",[id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Account not found");return c.body(null,204);});
  router.post("/:id/merge",requireScope("accounts:write"),async c=>{const s=z.object({targetAccountId:z.string()}).safeParse(await c.req.json().catch(()=>null)),p=c.get("principal"),source=c.req.param("id");if(!s.success||s.data.targetAccountId===source)throw new AppError(422,"VALIDATION_ERROR","Invalid merge target");const rows=await runtime.db.query<{id:string;type:string}>("SELECT id,type FROM accounts WHERE organization_id=$1 AND id=ANY($2::text[])",[p.organizationId,[source,s.data.targetAccountId]]);if(rows.rows.length!==2||rows.rows[0]!.type!==rows.rows[1]!.type)throw new AppError(422,"INCOMPATIBLE_ACCOUNTS","Accounts must exist and have the same type");await runtime.db.query("UPDATE journal_lines SET account_id=$1,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$2 AND account_id=$3",[s.data.targetAccountId,p.organizationId,source]);await runtime.db.query("UPDATE accounts SET active=false,allow_posting=false,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2",[source,p.organizationId]);return c.json({data:{sourceAccountId:source,targetAccountId:s.data.targetAccountId,status:"merged"}});});
  router.post("/groups",requireScope("accounts:write"),async c=>{const s=groupInput.omit({active:true}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid account group",s.error.flatten());const p=c.get("principal"),id=createId("acg"),v=s.data;if(v.parentGroupId){const parent=await runtime.db.query("SELECT 1 FROM account_groups WHERE id=$1 AND organization_id=$2",[v.parentGroupId,p.organizationId]);if(!parent.rowCount)throw new AppError(422,"INVALID_PARENT","Parent group not found");}await runtime.db.query("INSERT INTO account_groups(id,organization_id,code,name,type,parent_group_id) VALUES($1,$2,$3,$4,$5,$6)",[id,p.organizationId,v.code,v.name,v.type,v.parentGroupId??null]);return c.json({data:{id,...v}},201);});
  router.get("/groups",requireScope("accounts:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT id,code,name,type,parent_group_id AS "parentGroupId",active FROM account_groups WHERE organization_id=$1 ORDER BY code`,[p.organizationId]);return c.json({data:r.rows});});
  router.put("/groups/:id",requireScope("accounts:write"),async c=>{const s=groupInput.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid account group",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=s.data;if(v.parentGroupId===id)throw new AppError(422,"INVALID_PARENT","A group cannot be its own parent");let parent=v.parentGroupId??null;const seen=new Set<string>([id]);while(parent){if(seen.has(parent))throw new AppError(422,"INVALID_PARENT","Circular group hierarchy is not allowed");seen.add(parent);const row=(await runtime.db.query<{parentId:string|null}>(`SELECT parent_group_id AS "parentId" FROM account_groups WHERE id=$1 AND organization_id=$2`,[parent,p.organizationId])).rows[0];if(!row)throw new AppError(422,"INVALID_PARENT","Parent group not found");parent=row.parentId;}const r=await runtime.db.query("UPDATE account_groups SET code=$1,name=$2,type=$3,parent_group_id=$4,active=$5,updated_at=CURRENT_TIMESTAMP WHERE id=$6 AND organization_id=$7",[v.code,v.name,v.type,v.parentGroupId??null,v.active,id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Account group not found");return c.json({data:{id,...v}});});
  router.delete("/groups/:id",requireScope("accounts:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),used=await runtime.db.query(`SELECT 1 FROM accounts WHERE organization_id=$1 AND account_group_id=$2 UNION ALL SELECT 1 FROM account_groups WHERE organization_id=$1 AND parent_group_id=$2 LIMIT 1`,[p.organizationId,id]);if(used.rowCount)throw new AppError(409,"GROUP_IN_USE","Assigned or parent groups can only be deactivated");const r=await runtime.db.query("DELETE FROM account_groups WHERE id=$1 AND organization_id=$2",[id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Account group not found");return c.body(null,204);});
  router.post("/opening-balances",requireScope("accounts:write"),async c=>{const s=z.object({postingDate:z.iso.date(),currency:z.string().length(3).transform(v=>v.toUpperCase()),reference:z.string().max(100).optional(),lines:z.array(z.object({accountId:z.string(),debitMinor:z.number().int().nonnegative().default(0),creditMinor:z.number().int().nonnegative().default(0)})).min(2)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid opening balances",s.error.flatten());const debits=s.data.lines.reduce((n,l)=>n+l.debitMinor,0),credits=s.data.lines.reduce((n,l)=>n+l.creditMinor,0);if(debits!==credits)throw new AppError(422,"UNBALANCED_JOURNAL","Opening balances must balance",{debits,credits});const p=c.get("principal"),key=c.req.header("Idempotency-Key")??s.data.postingDate,j=await createJournal(runtime,p.organizationId,p.userId,{transactionDate:s.data.postingDate,postingDate:s.data.postingDate,description:"Opening balances",reference:s.data.reference,currency:s.data.currency,sourceType:"opening_balance",lines:s.data.lines},`opening-balances:${key}`);if(j.status==="draft")await postJournal(runtime,p.organizationId,p.userId,j.id);return c.json({data:{journalEntryId:j.id,status:"posted"}},201);});
  return router;
}

export function createJournalRoutes(runtime:Runtime){
  const router=new Hono<AppEnv>(); router.use("*",async(c,next)=>{await ensureFinanceProvisioned(runtime,c.get("principal").organizationId);await next();});
  router.get("/",requireScope("journals:read"),async c=>{const p=c.get("principal"),{limit,offset}=pagination(c),r=await runtime.db.query(`SELECT id,entry_number AS "entryNumber",transaction_date::text AS "transactionDate",posting_date::text AS "postingDate",description,reference,source_type AS "sourceType",status,currency,posted_at AS "postedAt",created_at AS "createdAt" FROM journal_entries WHERE organization_id=$1 ORDER BY posting_date DESC,entry_number DESC LIMIT $2 OFFSET $3`,[p.organizationId,limit,offset]);return c.json({data:r.rows,pagination:{limit,offset}});});
  router.get("/:id",requireScope("journals:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),entry=(await runtime.db.query(`SELECT id,organization_id,entry_number,transaction_date::text AS transaction_date,posting_date::text AS posting_date,description,reference,source_type,source_id,status,currency,exchange_rate_micros::float8 AS exchange_rate_micros,reversal_of_id,posted_at,posted_by,idempotency_key,metadata,created_at,updated_at FROM journal_entries WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!entry)throw new AppError(404,"NOT_FOUND","Journal not found");const lines=await runtime.db.query(`SELECT l.id,l.organization_id,l.journal_entry_id,l.account_id,l.description,l.debit_minor::float8 AS debit_minor,l.credit_minor::float8 AS credit_minor,l.base_debit_minor::float8 AS base_debit_minor,l.base_credit_minor::float8 AS base_credit_minor,l.contact_id,l.project_id,l.class_id,l.department_id,l.location_id,l.tax_code,l.dimensions_json,a.code AS account_code,a.name AS account_name,l.created_at,l.updated_at FROM journal_lines l JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE l.journal_entry_id=$1 AND l.organization_id=$2 ORDER BY l.id`,[id,p.organizationId]);return c.json({data:{...entry,lines:lines.rows.map(row=>({...row,dimensions:(row as {dimensions_json?:unknown}).dimensions_json??{},dimension_labels:[]}))}});});
  router.post("/",requireScope("journals:write"),async c=>{const key=c.req.header("Idempotency-Key");if(!key||key.length>200)throw new AppError(422,"IDEMPOTENCY_KEY_REQUIRED","A valid Idempotency-Key header is required");const s=journalInput.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid journal",s.error.flatten());const p=c.get("principal"),journal=await createJournal(runtime,p.organizationId,p.userId,s.data,key);return c.json({data:journal},201);});
  router.post("/:id/post",requireScope("journals:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await postJournal(runtime,p.organizationId,p.userId,id);return c.json({data:{id,status:"posted"}});});
  router.get("/:id/reversal-preview",requireScope("journals:read"),async c=>{const p=c.get("principal");return c.json({data:await reversalPreview(runtime,p.organizationId,c.req.param("id"))});});
  router.post("/:id/reverse",requireScope("journals:write"),async c=>{const s=reversalInput.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","A posting date and reason are required",s.error.flatten());const p=c.get("principal");return c.json({data:await reverseJournal(runtime,p.organizationId,p.userId,c.req.param("id"),s.data.postingDate,s.data.reason)});});
  router.delete("/:id",requireScope("journals:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),journal=(await runtime.db.query<{status:string}>("SELECT status FROM journal_entries WHERE id=$1 AND organization_id=$2",[id,p.organizationId])).rows[0];if(!journal)throw new AppError(404,"NOT_FOUND","Journal not found");if(journal.status!=="draft")throw new AppError(409,"IMMUTABLE_POSTED_TRANSACTION","Posted journals must be reversed, not deleted");await runtime.db.query("DELETE FROM journal_entries WHERE id=$1 AND organization_id=$2 AND status='draft'",[id,p.organizationId]);return c.body(null,204);});
  return router;
}
