import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../types";
import { requireScope } from "../lib/auth";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { randomToken, sha256 } from "../lib/crypto";
import { auditStatement } from "../services/audit";

export const adminRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
adminRoutes.get("/memberships",requireScope("admin:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare(`SELECT m.user_id AS userId,u.email,u.display_name AS displayName,m.role,m.scopes,m.created_at AS createdAt FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? ORDER BY u.display_name`).bind(p.organizationId).all<Record<string,unknown>>();return c.json({data:r.results.map(v=>({...v,scopes:JSON.parse(String(v.scopes))}))})});
const memberInput=z.object({email:z.email(),displayName:z.string().min(2).max(160),role:z.enum(["admin","accountant","manager","viewer","integration"]),scopes:z.array(z.string().max(80)).max(100).default([])});
adminRoutes.post("/memberships",requireScope("admin:write"),async c=>{const p=c.get("principal");if(!["owner","admin"].includes(p.role))throw new AppError(403,"FORBIDDEN","Only owners and administrators can add members");const s=memberInput.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid member",s.error.flatten());let user=await c.env.FINANCE_DB.prepare("SELECT id FROM users WHERE email=?").bind(s.data.email.toLowerCase()).first<{id:string}>();if(!user){user={id:createId("usr")};await c.env.FINANCE_DB.prepare("INSERT INTO users (id,email,display_name) VALUES (?,?,?)").bind(user.id,s.data.email.toLowerCase(),s.data.displayName).run()}await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare("INSERT INTO memberships (organization_id,user_id,role,scopes) VALUES (?,?,?,?)").bind(p.organizationId,user.id,s.data.role,JSON.stringify(s.data.scopes)),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"membership.created",entityType:"membership",entityId:user.id,after:{role:s.data.role,scopes:s.data.scopes}})]);return c.json({data:{userId:user.id,...s.data}},201)});
adminRoutes.put("/memberships/:userId",requireScope("admin:write"),async c=>{const p=c.get("principal"),s=memberInput.pick({displayName:true,role:true,scopes:true}).safeParse(await c.req.json()),userId=c.req.param("userId");if(!["owner","admin"].includes(p.role))throw new AppError(403,"FORBIDDEN","Only owners and administrators can edit members");if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid member",s.error.flatten());const existing=await c.env.FINANCE_DB.prepare("SELECT role FROM memberships WHERE organization_id=? AND user_id=?").bind(p.organizationId,userId).first<{role:string}>();if(!existing)throw new AppError(404,"NOT_FOUND","Member not found");if(existing.role==="owner")throw new AppError(409,"OWNER_PROTECTED","Ownership cannot be changed here");await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare("UPDATE memberships SET role=?,scopes=?,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND user_id=?").bind(s.data.role,JSON.stringify(s.data.scopes),p.organizationId,userId),c.env.FINANCE_DB.prepare("UPDATE users SET display_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(s.data.displayName,userId)]);return c.json({data:{userId,...s.data}})});
adminRoutes.delete("/memberships/:userId",requireScope("admin:write"),async c=>{const p=c.get("principal"),userId=c.req.param("userId");if(userId===p.userId)throw new AppError(409,"SELF_REMOVAL","You cannot remove your own membership");const r=await c.env.FINANCE_DB.prepare("DELETE FROM memberships WHERE organization_id=? AND user_id=? AND role<>'owner'").bind(p.organizationId,userId).run();if(!r.meta.changes)throw new AppError(409,"OWNER_PROTECTED","Owner membership cannot be removed");return c.body(null,204)});
adminRoutes.get("/api-keys",requireScope("admin:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare("SELECT id,name,prefix,scopes,expires_at AS expiresAt,last_used_at AS lastUsedAt,revoked_at AS revokedAt,created_at AS createdAt FROM api_keys WHERE organization_id=? ORDER BY created_at DESC").bind(p.organizationId).all<Record<string,unknown>>();return c.json({data:r.results.map(v=>({...v,scopes:JSON.parse(String(v.scopes))}))})});
const keyInput=z.object({name:z.string().min(1).max(120),scopes:z.array(z.string().max(80)).min(1).max(100),expiresAt:z.iso.datetime().optional()});
adminRoutes.post("/api-keys",requireScope("admin:write"),async c=>{const s=keyInput.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid API key",s.error.flatten());const p=c.get("principal"),id=createId("key"),secret=`yfp_${randomToken(32)}`,prefix=secret.slice(0,12);await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare("INSERT INTO api_keys (id,organization_id,name,prefix,key_hash,scopes,expires_at,created_by) VALUES (?,?,?,?,?,?,?,?)").bind(id,p.organizationId,s.data.name,prefix,await sha256(secret),JSON.stringify(s.data.scopes),s.data.expiresAt??null,p.userId),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"api_key.created",entityType:"api_key",entityId:id,after:{name:s.data.name,prefix,scopes:s.data.scopes}})]);return c.json({data:{id,name:s.data.name,prefix,secret,scopes:s.data.scopes,expiresAt:s.data.expiresAt},warning:"Copy the secret now; it cannot be retrieved again."},201)});
adminRoutes.delete("/api-keys/:id",requireScope("admin:write"),async c=>{const p=c.get("principal");await c.env.FINANCE_DB.prepare("UPDATE api_keys SET revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND revoked_at IS NULL").bind(c.req.param("id"),p.organizationId).run();return c.body(null,204)});
