import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../types";
import { requireScope } from "../lib/auth";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { auditStatement } from "../services/audit";
import { createJournal, postJournal } from "../services/ledger";

export const closingRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
const defaults=["bank_reconciled","receivables_reviewed","payables_reviewed","inventory_closed","payroll_posted","tax_reviewed","accruals_posted","management_review"];
closingRoutes.get("/:periodId/checklist",requireScope("periods:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare("SELECT id,code,name,required,status,evidence,completed_by AS completedBy,completed_at AS completedAt FROM close_checklist_items WHERE organization_id=? AND period_id=? ORDER BY created_at").bind(p.organizationId,c.req.param("periodId")).all();return c.json({data:r.results})});
closingRoutes.post("/:periodId/checklist/initialize",requireScope("periods:write"),async c=>{const p=c.get("principal"),periodId=c.req.param("periodId");const period=await c.env.FINANCE_DB.prepare("SELECT id FROM fiscal_periods WHERE id=? AND organization_id=?").bind(periodId,p.organizationId).first();if(!period)throw new AppError(404,"NOT_FOUND","Fiscal period not found");await c.env.FINANCE_DB.batch(defaults.map(code=>c.env.FINANCE_DB.prepare("INSERT OR IGNORE INTO close_checklist_items (id,organization_id,period_id,code,name) VALUES (?,?,?,?,?)").bind(createId("cli"),p.organizationId,periodId,code,code.replaceAll("_"," "))));return c.json({data:{periodId,itemCount:defaults.length}},201)});
const item=z.object({status:z.enum(["pending","completed","waived"]),evidence:z.string().max(2000).optional()});
closingRoutes.patch("/:periodId/checklist/:itemId",requireScope("periods:write"),async c=>{const s=item.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid checklist update",s.error.flatten());const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare("UPDATE close_checklist_items SET status=?,evidence=?,completed_by=CASE WHEN ?='completed' THEN ? ELSE NULL END,completed_at=CASE WHEN ?='completed' THEN CURRENT_TIMESTAMP ELSE NULL END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND period_id=? AND organization_id=?").bind(s.data.status,s.data.evidence??null,s.data.status,p.userId,s.data.status,c.req.param("itemId"),c.req.param("periodId"),p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Checklist item not found");return c.json({data:{id:c.req.param("itemId"),...s.data}})});
const schedule=z.object({type:z.enum(["accrual","deferral","prepayment","recurring_adjustment"]),name:z.string().min(1).max(160),startDate:z.iso.date(),endDate:z.iso.date().optional(),frequency:z.enum(["monthly","quarterly","yearly"]),amountMinor:z.number().int().positive(),debitAccountId:z.string(),creditAccountId:z.string(),nextPostingDate:z.iso.date()});
closingRoutes.post("/schedules",requireScope("journals:write"),async c=>{const s=schedule.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid adjustment schedule",s.error.flatten());const p=c.get("principal"),id=createId("sch"),v=s.data;await c.env.FINANCE_DB.prepare("INSERT INTO adjustment_schedules (id,organization_id,type,name,start_date,end_date,frequency,amount_minor,debit_account_id,credit_account_id,next_posting_date) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,p.organizationId,v.type,v.name,v.startDate,v.endDate??null,v.frequency,v.amountMinor,v.debitAccountId,v.creditAccountId,v.nextPostingDate).run();return c.json({data:{id,status:"active",...v}},201)});
closingRoutes.post("/schedules/:id/post",requireScope("journals:write"),async c=>{const p=c.get("principal");const s=await c.env.FINANCE_DB.prepare("SELECT name,next_posting_date AS date,amount_minor AS amount,debit_account_id AS debit,credit_account_id AS credit,frequency,status FROM adjustment_schedules WHERE id=? AND organization_id=?").bind(c.req.param("id"),p.organizationId).first<{name:string;date:string;amount:number;debit:string;credit:string;frequency:string;status:string}>();if(!s||s.status!=="active")throw new AppError(409,"INVALID_STATE","Active schedule not found");const org=await c.env.FINANCE_DB.prepare("SELECT base_currency AS currency FROM organizations WHERE id=?").bind(p.organizationId).first<{currency:string}>();const j=await createJournal(c.env.FINANCE_DB,p.organizationId,p.userId,{transactionDate:s.date,postingDate:s.date,description:s.name,currency:org?.currency??"UGX",sourceType:"period_adjustment",sourceId:c.req.param("id"),lines:[{accountId:s.debit,debitMinor:s.amount},{accountId:s.credit,creditMinor:s.amount}]},`schedule:${c.req.param("id")}:${s.date}`);await postJournal(c.env.FINANCE_DB,p.organizationId,p.userId,j.id);const mod=s.frequency==="monthly"?"+1 month":s.frequency==="quarterly"?"+3 months":"+1 year";await c.env.FINANCE_DB.prepare("UPDATE adjustment_schedules SET next_posting_date=date(next_posting_date,?),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(mod,c.req.param("id")).run();return c.json({data:{journalEntryId:j.id,postedOn:s.date}})});
const close=z.object({retainedEarningsAccountId:z.string().optional(),openNextYear:z.boolean().default(false),nextYearName:z.string().max(80).optional()});
closingRoutes.post("/:periodId/close",requireScope("periods:write"),async c=>{const s=close.safeParse(await c.req.json().catch(()=>({})));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid close request",s.error.flatten());const p=c.get("principal"),id=c.req.param("periodId");const period=await c.env.FINANCE_DB.prepare("SELECT name,starts_on AS startsOn,ends_on AS endsOn,status FROM fiscal_periods WHERE id=? AND organization_id=?").bind(id,p.organizationId).first<{name:string;startsOn:string;endsOn:string;status:string}>();if(!period||period.status==="locked")throw new AppError(409,"INVALID_STATE","Open fiscal period not found");const missing=await c.env.FINANCE_DB.prepare("SELECT COUNT(*) AS count FROM close_checklist_items WHERE organization_id=? AND period_id=? AND required=1 AND status NOT IN ('completed','waived')").bind(p.organizationId,id).first<{count:number}>();if(Number(missing?.count))throw new AppError(409,"CHECKLIST_INCOMPLETE","Required close checklist items remain",{count:Number(missing?.count)});let closingJournalId:string|undefined;if(s.data.retainedEarningsAccountId){const balances=await c.env.FINANCE_DB.prepare(`SELECT a.id,a.type,SUM(l.base_debit_minor-l.base_credit_minor) net FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id JOIN accounts a ON a.id=l.account_id WHERE l.organization_id=? AND j.status IN ('posted','reversed') AND j.posting_date BETWEEN ? AND ? AND a.type IN ('revenue','expense') GROUP BY a.id,a.type HAVING net<>0`).bind(p.organizationId,period.startsOn,period.endsOn).all<{id:string;type:string;net:number}>();const lines:{accountId:string;debitMinor?:number;creditMinor?:number}[]=balances.results.flatMap(x=>{const n=Number(x.net);return [{accountId:x.id,...(n>0?{creditMinor:n}:{debitMinor:-n})}]});const debit=lines.reduce((n,l)=>n+(l.debitMinor??0),0),credit=lines.reduce((n,l)=>n+(l.creditMinor??0),0);if(debit!==credit)lines.push({accountId:s.data.retainedEarningsAccountId,...(debit>credit?{creditMinor:debit-credit}:{debitMinor:credit-debit})});if(lines.length>=2){const org=await c.env.FINANCE_DB.prepare("SELECT base_currency currency FROM organizations WHERE id=?").bind(p.organizationId).first<{currency:string}>();const j=await createJournal(c.env.FINANCE_DB,p.organizationId,p.userId,{transactionDate:period.endsOn,postingDate:period.endsOn,description:`Year-end close ${period.name}`,currency:org?.currency??"UGX",sourceType:"year_end_close",sourceId:id,lines},`period:${id}:year-end-close`);await postJournal(c.env.FINANCE_DB,p.organizationId,p.userId,j.id);closingJournalId=j.id}}
  const statements=[c.env.FINANCE_DB.prepare("UPDATE fiscal_periods SET status='locked',locked_at=CURRENT_TIMESTAMP,locked_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(p.userId,id,p.organizationId),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"fiscal_period.closed",entityType:"fiscal_period",entityId:id,after:{closingJournalId}})];if(s.data.openNextYear){const start=new Date(period.endsOn+"T00:00:00Z");start.setUTCDate(start.getUTCDate()+1);const end=new Date(start);end.setUTCFullYear(end.getUTCFullYear()+1);end.setUTCDate(end.getUTCDate()-1);statements.push(c.env.FINANCE_DB.prepare("INSERT INTO fiscal_periods (id,organization_id,name,starts_on,ends_on,status) VALUES (?,?,?,?,?,'open')").bind(createId("fpd"),p.organizationId,s.data.nextYearName??`FY ${end.getUTCFullYear()}`,start.toISOString().slice(0,10),end.toISOString().slice(0,10)))}await c.env.FINANCE_DB.batch(statements);return c.json({data:{id,status:"locked",closingJournalId,nextYearOpened:s.data.openNextYear}})});
closingRoutes.post("/:periodId/post-close-adjustments",requireScope("journals:write"),async c=>{const p=c.get("principal"),id=createId("apr");await c.env.FINANCE_DB.prepare("INSERT INTO compliance_approvals (id,organization_id,entity_type,entity_id,action,requested_by,reason) VALUES (?,?,?,?,?,?,?)").bind(id,p.organizationId,"fiscal_period",c.req.param("periodId"),"post_close_adjustment",p.userId,String((await c.req.json().catch(()=>({}))).reason??"")).run();return c.json({data:{id,status:"pending"}},202)});
