import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../types";
import { requireScope } from "../lib/auth";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { auditStatement } from "../services/audit";
import { recordMovement, transferStock } from "../services/inventory";

export const inventoryRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
inventoryRoutes.get("/locations",requireScope("products:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare("SELECT id,code,name,active FROM inventory_locations WHERE organization_id=? ORDER BY code").bind(p.organizationId).all();return c.json({data:r.results})});
inventoryRoutes.post("/locations",requireScope("products:write"),async c=>{const s=z.object({code:z.string().min(1).max(30),name:z.string().min(1).max(160)}).safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid location",s.error.flatten());const p=c.get("principal"),id=createId("loc");await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare("INSERT INTO inventory_locations (id,organization_id,code,name) VALUES (?,?,?,?)").bind(id,p.organizationId,s.data.code,s.data.name),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"inventory.location_created",entityType:"inventory_location",entityId:id,after:s.data})]);return c.json({data:{id,...s.data}},201)});
inventoryRoutes.get("/balances",requireScope("products:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare(`SELECT b.product_id AS productId,p.sku,p.name,b.location_id AS locationId,l.code AS locationCode,b.quantity_micros AS quantityMicros,b.inventory_value_minor AS inventoryValueMinor FROM inventory_balances b JOIN products p ON p.id=b.product_id AND p.organization_id=b.organization_id JOIN inventory_locations l ON l.id=b.location_id AND l.organization_id=b.organization_id WHERE b.organization_id=? ORDER BY p.sku,l.code`).bind(p.organizationId).all();return c.json({data:r.results})});
const movement=z.object({productId:z.string(),locationId:z.string(),type:z.enum(["opening","receipt","issue","adjustment","sale_return","purchase_return"]),movementDate:z.iso.date(),quantityDeltaMicros:z.number().int(),unitCostMinor:z.number().int().nonnegative().optional(),offsetAccountId:z.string(),sourceType:z.string().max(50).optional(),sourceId:z.string().max(100).optional()});
inventoryRoutes.post("/movements",requireScope("products:write"),async c=>{const key=c.req.header("Idempotency-Key");if(!key)throw new AppError(422,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required");const s=movement.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid movement",s.error.flatten());const p=c.get("principal");return c.json({data:await recordMovement(c.env.FINANCE_DB,p.organizationId,p.userId,s.data,key)},201)});
const transfer=z.object({productId:z.string(),fromLocationId:z.string(),toLocationId:z.string(),movementDate:z.iso.date(),quantityMicros:z.number().int().positive()});
inventoryRoutes.post("/transfers",requireScope("products:write"),async c=>{const key=c.req.header("Idempotency-Key");if(!key)throw new AppError(422,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required");const s=transfer.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid transfer",s.error.flatten());const p=c.get("principal");return c.json({data:await transferStock(c.env.FINANCE_DB,p.organizationId,p.userId,s.data,key)},201)});
