import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../types";
import { requireScope } from "../lib/auth";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { auditStatement } from "../services/audit";
import { createDocument } from "../services/documents";

const line=z.object({productId:z.string().optional(),accountId:z.string(),taxAccountId:z.string().optional(),description:z.string().min(1).max(500),quantityMicros:z.number().int().positive().default(1_000_000),unitPriceMinor:z.number().int().nonnegative(),taxMinor:z.number().int().nonnegative().default(0),projectId:z.string().optional()});
const input=z.object({type:z.enum(["estimate","sales_order","purchase_order"]),number:z.string().min(1).max(60),contactId:z.string(),issueDate:z.iso.date(),expiryDate:z.iso.date().optional(),currency:z.string().length(3).toUpperCase(),customFields:z.record(z.string(),z.unknown()).optional(),lines:z.array(line).min(1).max(500)});
export const ordersRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
ordersRoutes.get("/",requireScope("documents:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare(`SELECT o.id,o.type,o.number,o.issue_date AS issueDate,o.expiry_date AS expiryDate,o.status,o.currency,o.total_minor AS totalMinor,c.name AS contact FROM orders o JOIN contacts c ON c.id=o.contact_id AND c.organization_id=o.organization_id WHERE o.organization_id=? ORDER BY o.issue_date DESC,o.number DESC`).bind(p.organizationId).all();return c.json({data:r.results})});
ordersRoutes.post("/",requireScope("documents:write"),async c=>{const s=input.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid order",s.error.flatten());const p=c.get("principal"),v=s.data,id=createId("ord");const expected=(v.type==="estimate"||v.type==="sales_order")?"customer":"supplier";const contact=await c.env.FINANCE_DB.prepare("SELECT id FROM contacts WHERE id=? AND organization_id=? AND type=? AND active=1").bind(v.contactId,p.organizationId,expected).first();if(!contact)throw new AppError(422,"INVALID_CONTACT",`A ${expected} is required`);const calculated=v.lines.map(l=>({...l,subtotalMinor:Math.round(l.quantityMicros*l.unitPriceMinor/1_000_000),totalMinor:Math.round(l.quantityMicros*l.unitPriceMinor/1_000_000)+l.taxMinor}));const subtotal=calculated.reduce((n,l)=>n+l.subtotalMinor,0),tax=calculated.reduce((n,l)=>n+l.taxMinor,0);await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare(`INSERT INTO orders (id,organization_id,type,number,contact_id,issue_date,expiry_date,currency,subtotal_minor,tax_minor,total_minor,custom_fields) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,p.organizationId,v.type,v.number,v.contactId,v.issueDate,v.expiryDate??null,v.currency,subtotal,tax,subtotal+tax,JSON.stringify(v.customFields??{})),...calculated.map(l=>c.env.FINANCE_DB.prepare(`INSERT INTO order_lines (id,organization_id,order_id,product_id,account_id,tax_account_id,description,quantity_micros,unit_price_minor,subtotal_minor,tax_minor,total_minor,project_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(createId("oln"),p.organizationId,id,l.productId??null,l.accountId,l.taxAccountId??null,l.description,l.quantityMicros,l.unitPriceMinor,l.subtotalMinor,l.taxMinor,l.totalMinor,l.projectId??null)),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"order.created",entityType:"order",entityId:id,after:{type:v.type,number:v.number,totalMinor:subtotal+tax}})]);return c.json({data:{id,status:"draft",subtotalMinor:subtotal,taxMinor:tax,totalMinor:subtotal+tax}},201)});
ordersRoutes.post("/:id/approve",requireScope("documents:write"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare("UPDATE orders SET status='approved',updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND status='draft'").bind(c.req.param("id"),p.organizationId).run();if(!r.meta.changes)throw new AppError(409,"INVALID_STATE","Draft order not found");return c.json({data:{id:c.req.param("id"),status:"approved"}})});
const conversion=z.object({documentNumber:z.string().min(1).max(60),issueDate:z.iso.date(),dueDate:z.iso.date().optional()});
ordersRoutes.post("/:id/convert",requireScope("documents:write"),async c=>{const s=conversion.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid conversion",s.error.flatten());const p=c.get("principal");const order=await c.env.FINANCE_DB.prepare("SELECT type,contact_id AS contactId,currency,status,custom_fields AS customFields FROM orders WHERE id=? AND organization_id=?").bind(c.req.param("id"),p.organizationId).first<{type:"estimate"|"sales_order"|"purchase_order";contactId:string;currency:string;status:string;customFields:string}>();if(!order||order.status!=="approved")throw new AppError(409,"INVALID_STATE","Approved order not found");const raw=await c.env.FINANCE_DB.prepare(`SELECT product_id AS productId,account_id AS accountId,tax_account_id AS taxAccountId,description,quantity_micros AS quantityMicros,unit_price_minor AS unitPriceMinor,tax_minor AS taxMinor,project_id AS projectId FROM order_lines WHERE order_id=? AND organization_id=?`).bind(c.req.param("id"),p.organizationId).all<any>();const doc=await createDocument(c.env.FINANCE_DB,p.organizationId,p.userId,{type:(order.type==="estimate"||order.type==="sales_order")?"invoice":"bill",number:s.data.documentNumber,contactId:order.contactId,issueDate:s.data.issueDate,dueDate:s.data.dueDate,currency:order.currency,customFields:JSON.parse(order.customFields),lines:raw.results.map(l=>({...l,taxAccountId:l.taxAccountId??undefined,productId:l.productId??undefined,projectId:l.projectId??undefined}))});await c.env.FINANCE_DB.prepare("UPDATE orders SET status='converted',converted_document_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(doc.id,c.req.param("id"),p.organizationId).run();return c.json({data:{orderId:c.req.param("id"),status:"converted",documentId:doc.id}},201)});
