import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../types";
import { requireScope } from "../lib/auth";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { auditStatement } from "../services/audit";
import { SignJWT } from "jose";
import { randomToken, sha256 } from "../lib/crypto";

export const organizationsRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
organizationsRoutes.post("/switch",async c=>{const p=c.get("principal"),body=await c.req.json<{organizationId?:string}>();if(!body.organizationId)throw new AppError(422,"VALIDATION_ERROR","Organization is required");const m=await c.env.FINANCE_DB.prepare("SELECT role,scopes FROM memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=? AND m.organization_id=? AND o.status='active'").bind(p.userId,body.organizationId).first<{role:string;scopes:string}>();if(!m)throw new AppError(403,"NO_MEMBERSHIP","No active organization membership found");const now=Math.floor(Date.now()/1000),accessToken=await new SignJWT({org:body.organizationId,role:m.role,scopes:JSON.parse(m.scopes)}).setProtectedHeader({alg:"HS256"}).setSubject(p.userId).setIssuer(c.env.JWT_ISSUER).setAudience(c.env.JWT_AUDIENCE).setIssuedAt(now).setExpirationTime(now+900).sign(new TextEncoder().encode(c.env.JWT_SECRET)),refreshToken=randomToken(48),sessionId=createId("ses");await c.env.FINANCE_DB.prepare("INSERT INTO sessions(id,user_id,organization_id,refresh_token_hash,expires_at,ip_address,user_agent) VALUES(?,?,?,?,datetime('now','+30 days'),?,?)").bind(sessionId,p.userId,body.organizationId,await sha256(refreshToken),c.req.header("CF-Connecting-IP")??null,c.req.header("User-Agent")??null).run();return c.json({data:{accessToken,refreshToken,expiresIn:900,sessionId}})});
const settings=z.object({name:z.string().min(2).max(160),legalName:z.string().max(160).nullable().optional(),baseCurrency:z.string().length(3).toUpperCase(),timezone:z.string().min(1).max(100),fiscalYearStartMonth:z.number().int().min(1).max(12),address:z.record(z.string(),z.unknown()).default({}),taxRegistrationNumber:z.string().max(100).nullable().optional(),documentNumbering:z.record(z.string(),z.unknown()).default({}),branding:z.object({logoDataUrl:z.string().max(400000).optional(),email:z.string().max(160).optional(),phone:z.string().max(60).optional(),website:z.string().max(200).optional(),footer:z.string().max(500).optional(),primaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/).optional()}).default({})});
organizationsRoutes.get("/",async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare(`SELECT o.id,o.name,o.legal_name AS legalName,o.base_currency AS baseCurrency,o.timezone,o.fiscal_year_start_month AS fiscalYearStartMonth,o.address_json AS address,o.tax_registration_number AS taxRegistrationNumber,o.document_numbering_json AS documentNumbering,o.status,m.role,m.scopes FROM memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=? ORDER BY o.name`).bind(p.userId).all<Record<string,unknown>>();return c.json({data:r.results.map(v=>({...v,address:JSON.parse(String(v.address)),documentNumbering:JSON.parse(String(v.documentNumbering)),scopes:JSON.parse(String(v.scopes))}))})});
organizationsRoutes.get("/current",requireScope("accounts:read"),async c=>{const p=c.get("principal");const v=await c.env.FINANCE_DB.prepare(`SELECT id,name,legal_name AS legalName,base_currency AS baseCurrency,timezone,fiscal_year_start_month AS fiscalYearStartMonth,address_json AS address,tax_registration_number AS taxRegistrationNumber,document_numbering_json AS documentNumbering,branding_json AS branding,status,created_at AS createdAt,updated_at AS updatedAt FROM organizations WHERE id=?`).bind(p.organizationId).first<Record<string,unknown>>();if(!v)throw new AppError(404,"NOT_FOUND","Organization not found");return c.json({data:{...v,address:JSON.parse(String(v.address)),documentNumbering:JSON.parse(String(v.documentNumbering)),branding:JSON.parse(String(v.branding))}})});
organizationsRoutes.put("/current",requireScope("admin:write"),async c=>{const s=settings.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid organization settings",s.error.flatten());const p=c.get("principal"),v=s.data;await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare(`UPDATE organizations SET name=?,legal_name=?,base_currency=?,timezone=?,fiscal_year_start_month=?,address_json=?,tax_registration_number=?,document_numbering_json=?,branding_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(v.name,v.legalName??null,v.baseCurrency,v.timezone,v.fiscalYearStartMonth,JSON.stringify(v.address),v.taxRegistrationNumber??null,JSON.stringify(v.documentNumbering),JSON.stringify(v.branding),p.organizationId),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"organization.updated",entityType:"organization",entityId:p.organizationId,after:v})]);return c.json({data:{id:p.organizationId,...v}})});
const createOrg=settings.pick({name:true,legalName:true,baseCurrency:true,timezone:true,fiscalYearStartMonth:true,address:true,taxRegistrationNumber:true,documentNumbering:true});
const defaults=[["1000","Cash and Bank","asset","cash","debit"],["1100","Accounts Receivable","asset","receivable","debit"],["1200","Inventory","asset","inventory","debit"],["2000","Accounts Payable","liability","payable","credit"],["2100","Tax Payable","liability","tax","credit"],["2200","Payroll Payable","liability","payroll","credit"],["3000","Owner's Equity","equity","equity","credit"],["4000","Sales Revenue","revenue","sales","credit"],["5000","Cost of Goods Sold","expense","cogs","debit"],["6000","Operating Expenses","expense","operating","debit"]] as const;
organizationsRoutes.post("/",requireScope("admin:write"),async c=>{const s=createOrg.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid organization",s.error.flatten());const p=c.get("principal");if(p.userId.startsWith("apikey:"))throw new AppError(403,"FORBIDDEN","API keys cannot create organizations");const id=createId("org"),v=s.data;await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare(`INSERT INTO organizations(id,name,legal_name,base_currency,timezone,fiscal_year_start_month,address_json,tax_registration_number,document_numbering_json) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,v.name,v.legalName??null,v.baseCurrency,v.timezone,v.fiscalYearStartMonth,JSON.stringify(v.address),v.taxRegistrationNumber??null,JSON.stringify(v.documentNumbering)),c.env.FINANCE_DB.prepare("INSERT INTO memberships(organization_id,user_id,role,scopes) VALUES(?,?,'owner','[]')").bind(id,p.userId),...defaults.map(([code,name,type,subtype,normal])=>c.env.FINANCE_DB.prepare("INSERT INTO accounts(id,organization_id,code,name,type,subtype,normal_balance) VALUES(?,?,?,?,?,?,?)").bind(createId("acc"),id,code,name,type,subtype,normal))]);return c.json({data:{id,...v}},201)});
