import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../types";
import { requireScope } from "../lib/auth";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { auditStatement } from "../services/audit";

export const projectsRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
const projectInput=z.object({customerId:z.string().optional(),code:z.string().min(1).max(40),name:z.string().min(1).max(160),budgetAmountMinor:z.number().int().nonnegative().default(0)});
projectsRoutes.get("/",requireScope("documents:read"),async c=>{const p=c.get("principal");const r=await c.env.FINANCE_DB.prepare(`SELECT p.id,p.code,p.name,p.status,p.budget_amount_minor AS budgetAmountMinor,c.name AS customer FROM projects p LEFT JOIN contacts c ON c.id=p.customer_id AND c.organization_id=p.organization_id WHERE p.organization_id=? ORDER BY p.code`).bind(p.organizationId).all();return c.json({data:r.results})});
projectsRoutes.post("/",requireScope("documents:write"),async c=>{const s=projectInput.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid project",s.error.flatten());const p=c.get("principal"),id=createId("prj");if(s.data.customerId){const customer=await c.env.FINANCE_DB.prepare("SELECT id FROM contacts WHERE id=? AND organization_id=? AND type='customer'").bind(s.data.customerId,p.organizationId).first();if(!customer)throw new AppError(422,"INVALID_CUSTOMER","Project customer is invalid")}await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare("INSERT INTO projects (id,organization_id,customer_id,code,name,budget_amount_minor) VALUES (?,?,?,?,?,?)").bind(id,p.organizationId,s.data.customerId??null,s.data.code,s.data.name,s.data.budgetAmountMinor),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"project.created",entityType:"project",entityId:id,after:s.data})]);return c.json({data:{id,status:"active",...s.data}},201)});
const timeInput=z.object({entryDate:z.iso.date(),minutes:z.number().int().positive().max(1440),description:z.string().max(500).optional(),billable:z.boolean().default(false),costRateMinor:z.number().int().nonnegative().default(0),billingRateMinor:z.number().int().nonnegative().default(0)});
projectsRoutes.post("/:id/time-entries",requireScope("documents:write"),async c=>{const s=timeInput.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid time entry",s.error.flatten());const p=c.get("principal"),id=createId("tim");const project=await c.env.FINANCE_DB.prepare("SELECT id FROM projects WHERE id=? AND organization_id=? AND status='active'").bind(c.req.param("id"),p.organizationId).first();if(!project)throw new AppError(404,"NOT_FOUND","Active project not found");await c.env.FINANCE_DB.prepare(`INSERT INTO time_entries (id,organization_id,user_id,project_id,entry_date,minutes,description,billable,cost_rate_minor,billing_rate_minor)
  VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(id,p.organizationId,p.userId,c.req.param("id"),s.data.entryDate,s.data.minutes,s.data.description??null,s.data.billable,s.data.costRateMinor,s.data.billingRateMinor).run();return c.json({data:{id,status:"draft",...s.data}},201)});
projectsRoutes.patch("/:projectId/time-entries/:id/approve",requireScope("documents:write"),async c=>{const p=c.get("principal");const result=await c.env.FINANCE_DB.prepare("UPDATE time_entries SET status='approved',updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND organization_id=? AND status='draft'").bind(c.req.param("id"),c.req.param("projectId"),p.organizationId).run();if(!result.meta.changes)throw new AppError(409,"INVALID_STATE","Draft time entry not found");return c.json({data:{id:c.req.param("id"),status:"approved"}})});
