import{MobileSyncStore}from"../../native";import{localMobileRecord,localMobileRecords,queueMobileMutation}from"../syncEngine";type R=Record<string,any>;const M="tasks-work",uid=(p:string)=>`${p}_${Date.now().toString(36)}${Math.random().toString(36).slice(2)}${Math.random().toString(36).slice(2)}`;export const workNetworkError=(e:any)=>e?.code==="NETWORK_ERROR"||e?.status===0;export async function workOfflineFallback<T>(online:()=>Promise<T>,offline:()=>Promise<T>){try{return await online()}catch(e){if(workNetworkError(e))return offline();throw e}}const rows=async(c:string)=>((await localMobileRecords<R>(M,c,1000,0)).map(x=>({...(x.payload||{}),id:x.id})));const pending=async(c:string)=>(await MobileSyncStore.pendingOperations(250)).filter(x=>x.moduleKey===M&&x.collectionKey===c);async function overlay(c:string){const map=new Map((await rows(c)).map(x=>[x.id,x]));for(const op of await pending(c)){if(op.kind==="delete"){map.delete(op.recordId);continue}let p:R={};try{p=op.payloadJson?JSON.parse(op.payloadJson):{}}catch{}map.set(op.recordId,{...(map.get(op.recordId)||{id:op.recordId}),...p,id:op.recordId})}return[...map.values()]}
export const offlineProjects=()=>rows("projects");export async function offlineTasks(f:any={}){let x=await overlay("tasks");if(f.status)x=x.filter(r=>r.status===f.status);if(f.projectId)x=x.filter(r=>r.projectId===f.projectId);if(f.parentTaskId!==undefined)x=x.filter(r=>r.parentTaskId===f.parentTaskId);if(f.search){const q=String(f.search).toLowerCase();x=x.filter(r=>`${r.taskNumber||""} ${r.title||""} ${r.description||""}`.toLowerCase().includes(q))}return x}
export async function offlineTask(id:string){const t=(await overlay("tasks")).find(x=>x.id===id);if(!t)throw new Error("Task is not available offline");const[checklist,comments,timeEntries,subtasks]=await Promise.all([rows("checklist-items"),overlay("comments"),overlay("time-entries"),offlineTasks({parentTaskId:id})]);return{...t,assignees:[],followers:[],checklist:checklist.filter(x=>x.taskId===id),comments:comments.filter(x=>x.taskId===id),timeEntries:timeEntries.filter(x=>x.taskId===id),subtasks,checklistTotal:checklist.filter(x=>x.taskId===id).length,checklistCompleted:checklist.filter(x=>x.taskId===id&&x.isCompleted).length,commentCount:comments.filter(x=>x.taskId===id).length}}
export async function offlineProject(id:string){const p=(await offlineProjects()).find(x=>x.id===id);if(!p)throw new Error("Project is not available offline");return{...p,tasks:await offlineTasks({projectId:id})}}
export async function offlineDashboard(){const[p,t]=await Promise.all([offlineProjects(),offlineTasks()]),done=t.filter(x=>x.status==="completed"),inProgress=t.filter(x=>x.status==="in_progress"),blocked=t.filter(x=>x.status==="blocked"),now=Date.now(),overdue=t.filter(x=>x.dueAt&&new Date(x.dueAt).getTime()<now&&!['completed','cancelled'].includes(x.status));return{tasks:{total:t.length,completed:done.length,inProgress:inProgress.length,blocked:blocked.length,overdue:overdue.length},projects:{total:p.length,active:p.filter(x=>x.status==="active").length,completed:p.filter(x=>x.status==="completed").length},myDue:t.filter(x=>!['completed','cancelled'].includes(x.status)).slice(0,20),recent:t.slice(0,20),unreadNotifications:0,myMinutesLast7Days:(await rows("time-entries")).reduce((n,x)=>n+Number(x.minutes||0),0)}}
export async function queueTaskPatch(id:string,body:R){const allowed:R={};for(const k of['status','progress','actualMinutes'])if(body[k]!==undefined)allowed[k]=body[k];await queueMobileMutation({moduleKey:M,collectionKey:"tasks",recordId:id,payload:allowed});return{...(await offlineTask(id)),...allowed}}
export async function queueComment(taskId:string,body:string,mentionUserIds:string[]=[]){const id=uid("wcm");await queueMobileMutation({moduleKey:M,collectionKey:"comments",recordId:id,payload:{taskId,body,mentions:mentionUserIds},baseVersion:0});return{id,taskId,body,mentions:mentionUserIds,createdAt:new Date().toISOString()}}
export async function queueTime(taskId:string,body:R){const id=uid("wte"),payload={taskId,...body};await queueMobileMutation({moduleKey:M,collectionKey:"time-entries",recordId:id,payload,baseVersion:0});return{id,...payload}}
export async function queueChecklistCompletion(itemId:string){const id=uid("wcc"),completedAt=new Date().toISOString();await queueMobileMutation({moduleKey:M,collectionKey:"checklist-completions",recordId:id,payload:{itemId,completedAt},baseVersion:0});return{id,itemId,isCompleted:true,completedAt}}
