import {useEffect,useState} from "react";
import {RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {Card,ErrorNotice,Metric,Pill,SectionTitle} from "../school/ui";
import {workApi} from "./api";
import type {WorkDashboard} from "./types";
import {err,tone} from "./context";
export function OverviewTab({session,onSession}:{session:MobileSession;onSession:SessionUpdater}){const c={session,onSession};const[data,setData]=useState<WorkDashboard|null>(null),[org,setOrg]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const[d,o]=await Promise.all([workApi.dashboard(c),workApi.organization(c)]);setData(d);setOrg(o)}catch(e){setError(err(e))}finally{setLoading(false)}}useEffect(()=>{void load()},[session.accessToken]);return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.scroll}><View style={s.hero}><Text style={s.eyebrow}>PROJECTS · TASKS · EXECUTION</Text><Text style={s.title}>Tasks & Work</Text><Text style={s.copy}>Plan projects, assign work, follow checklists, discuss tasks, track time, manage teams and keep execution connected to Ledgerly people and communications.</Text>{org?.name?<Text style={s.org}>{org.name}</Text>:null}</View>{error?<ErrorNotice message={error} onRetry={load}/>:null}<View style={s.metrics}><Metric label="Tasks" value={data?.tasks.total||0} sub={`${data?.tasks.completed||0} completed`}/><Metric label="In progress" value={data?.tasks.inProgress||0} sub={`${data?.tasks.blocked||0} blocked`} tone={(data?.tasks.blocked||0)>0?"warn":"good"}/><Metric label="Overdue" value={data?.tasks.overdue||0} sub="needs attention" tone={(data?.tasks.overdue||0)>0?"bad":"good"}/><Metric label="Projects" value={data?.projects.total||0} sub={`${data?.projects.active||0} active`}/><Metric label="Unread" value={data?.unreadNotifications||0} sub="notifications" tone={(data?.unreadNotifications||0)>0?"warn":"good"}/><Metric label="My time" value={`${Math.round((data?.myMinutesLast7Days||0)/60*10)/10}h`} sub="last 7 days"/></View><SectionTitle title="My upcoming work" subtitle="Open tasks assigned to your user"/><Card>{data?.myDue?.length?data.myDue.map(x=><View key={x.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{x.taskNumber} · {x.title}</Text><Text style={s.meta}>{[x.projectName,x.dueAt?`due ${x.dueAt}`:null,x.priority].filter(Boolean).join(" · ")}</Text></View><Pill text={x.status} tone={tone(x.status)}/></View>):<Text style={s.empty}>No assigned open tasks are due.</Text>}</Card><SectionTitle title="Recent activity"/><Card>{data?.recent?.length?data.recent.map(x=><View key={x.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{x.taskNumber} · {x.title}</Text><Text style={s.meta}>{[x.projectName,x.priority].filter(Boolean).join(" · ")}</Text></View><Pill text={x.status} tone={tone(x.status)}/></View>):<Text style={s.empty}>No recent task activity.</Text>}</Card></ScrollView>}
const s=StyleSheet.create({scroll:{padding:16,paddingBottom:40,gap:12},hero:{backgroundColor:"#24354f",borderRadius:24,padding:20},eyebrow:{fontSize:8,fontWeight:"900",letterSpacing:1.1,color:"#8ab9ff"},title:{fontSize:28,fontWeight:"900",color:"white",marginTop:7},copy:{fontSize:11,lineHeight:17,color:"#c7d3e3",marginTop:6},org:{fontSize:9,fontWeight:"900",color:"#8fb2df",marginTop:12},metrics:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",gap:10},row:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#edf1ef"},name:{fontSize:11,fontWeight:"900",color:"#263d33"},meta:{fontSize:9,color:"#819087",marginTop:3},empty:{fontSize:10,color:"#819087"}});
