import {createHash} from "node:crypto";
import {Hono} from "hono";
import {AppError} from "../../http/errors.js";
import type {AppEnv} from "../../http/types.js";
import type {Runtime} from "../../runtime.js";
import {createId,requireScope} from "../core-identity/security.js";

const MAX_FILE_BYTES=50*1024*1024;
const safeName=(value:string)=>(value.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"file").slice(0,180);
const normalizeName=(value:string)=>value.trim().replace(/\s+/g," ").toLocaleLowerCase();
const sourceLabel=(source:string)=>({upload:"Uploaded",ai_generated:"AI generated",school_file:"School file",scannerly:"Scanned",report_export:"Report",system_generated:"System generated",finance_attachment:"Finance attachment",printerly:"Printerly"} as Record<string,string>)[source]||source;
function json(value:unknown,fallback:unknown){if(value&&typeof value==="object")return value;try{return typeof value==="string"?JSON.parse(value):fallback}catch{return fallback}}
function mapItem(row:Record<string,any>){return{id:String(row.id),folderId:row.folderId??null,folderName:row.folderName??null,title:String(row.title),filename:String(row.filename),mimeType:String(row.mimeType),sizeBytes:Number(row.sizeBytes||0),checksumSha256:row.checksumSha256??null,sourceType:String(row.sourceType),sourceLabel:sourceLabel(String(row.sourceType)),sourceModule:row.sourceModule??null,sourceEntityType:row.sourceEntityType??null,sourceEntityId:row.sourceEntityId??null,status:row.status,currentVersion:Number(row.currentVersion||1),hasPreview:Boolean(row.previewObjectKey),previewMimeType:row.previewMimeType??null,tags:json(row.tags,[]),metadata:json(row.metadata,{}),createdBy:row.createdBy??null,createdAt:String(row.createdAt),updatedAt:String(row.updatedAt),contentUrl:`/api/v1/files/items/${row.id}/content`,previewUrl:row.previewObjectKey?`/api/v1/files/items/${row.id}/content?preview=1`:null};}
const selectItem=`SELECT i.id,i.folder_id AS "folderId",f.name AS "folderName",i.title,i.filename,i.mime_type AS "mimeType",i.size_bytes::float8 AS "sizeBytes",i.checksum_sha256 AS "checksumSha256",i.storage_bucket AS "storageBucket",i.object_key AS "objectKey",i.preview_object_key AS "previewObjectKey",i.preview_mime_type AS "previewMimeType",i.source_type AS "sourceType",i.source_module AS "sourceModule",i.source_entity_type AS "sourceEntityType",i.source_entity_id AS "sourceEntityId",i.status,i.current_version AS "currentVersion",i.tags_json AS tags,i.metadata_json AS metadata,i.created_by AS "createdBy",i.created_at AS "createdAt",i.updated_at AS "updatedAt" FROM file_items i LEFT JOIN file_folders f ON f.id=i.folder_id AND f.organization_id=i.organization_id`;

async function ownedItem(runtime:Runtime,org:string,id:string){const row=(await runtime.db.query<Record<string,any>>(`${selectItem} WHERE i.id=$1 AND i.organization_id=$2 AND i.deleted_at IS NULL`,[id,org])).rows[0];if(!row)throw new AppError(404,"FILE_NOT_FOUND","Document or file not found");return row;}
async function ownedFolder(runtime:Runtime,org:string,id:string|null|undefined){if(!id)return null;const row=(await runtime.db.query<Record<string,any>>(`SELECT id,parent_id AS "parentId",name FROM file_folders WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[id,org])).rows[0];if(!row)throw new AppError(422,"INVALID_FOLDER","Choose a valid document folder");return row;}

export function createFileManagerRoutes(runtime:Runtime){
  const r=new Hono<AppEnv>();r.use("*",requireScope("documents:read"));
  r.get("/manifest",c=>c.json({data:{key:"file-manager",name:"Documents & Files",version:"1.0.0",features:["folders","uploads","versions","preview","archive"]}}));
  r.get("/summary",async c=>{const p=c.get("principal"),row=(await runtime.db.query<Record<string,any>>(`SELECT COUNT(*)::int AS "totalFiles",COUNT(*) FILTER(WHERE source_type='upload')::int AS "uploadedFiles",COUNT(*) FILTER(WHERE source_type<>'upload')::int AS "generatedFiles",COUNT(*) FILTER(WHERE status='archived')::int AS "archivedFiles",COUNT(*) FILTER(WHERE status='trashed')::int AS "trashedFiles",COALESCE(SUM(size_bytes) FILTER(WHERE status<>'trashed'),0)::float8 AS "storageBytes" FROM file_items WHERE organization_id=$1 AND deleted_at IS NULL`,[p.organizationId])).rows[0]??{};return c.json({data:row});});
  r.get("/folders",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT f.id,f.parent_id AS "parentId",f.name,f.created_at AS "createdAt",f.updated_at AS "updatedAt",(SELECT COUNT(*)::int FROM file_items i WHERE i.organization_id=f.organization_id AND i.folder_id=f.id AND i.status<>'trashed' AND i.deleted_at IS NULL) AS "fileCount" FROM file_folders f WHERE f.organization_id=$1 AND f.deleted_at IS NULL ORDER BY lower(f.name)`,[p.organizationId]);return c.json({data:q.rows});});
  r.post("/folders",requireScope("documents:write"),async c=>{const p=c.get("principal"),body=await c.req.json<Record<string,unknown>>().catch(()=>({})),name=String(body.name||"").trim().replace(/\s+/g," ").slice(0,120),parentId=body.parentId?String(body.parentId):null;if(!name)throw new AppError(422,"FOLDER_NAME_REQUIRED","Folder name is required");await ownedFolder(runtime,p.organizationId,parentId);const id=createId("fld");try{await runtime.db.query(`INSERT INTO file_folders(id,organization_id,parent_id,name,name_normalized,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$6)`,[id,p.organizationId,parentId,name,normalizeName(name),p.userId]);}catch{throw new AppError(409,"FOLDER_EXISTS","A folder with this name already exists here");}return c.json({data:{id,parentId,name,fileCount:0}},201);});
  r.patch("/folders/:id",requireScope("documents:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),current=await ownedFolder(runtime,p.organizationId,id),body=await c.req.json<Record<string,unknown>>().catch(()=>({})),name=body.name===undefined?String(current!.name):String(body.name||"").trim().replace(/\s+/g," ").slice(0,120),parentId=body.parentId===undefined?(current!.parentId??null):(body.parentId?String(body.parentId):null);if(!name)throw new AppError(422,"FOLDER_NAME_REQUIRED","Folder name is required");if(parentId===id)throw new AppError(422,"INVALID_FOLDER_PARENT","A folder cannot contain itself");let cursor=parentId;while(cursor){if(cursor===id)throw new AppError(422,"INVALID_FOLDER_PARENT","A folder cannot be moved into its descendant");cursor=(await ownedFolder(runtime,p.organizationId,cursor))?.parentId??null;}await runtime.db.query(`UPDATE file_folders SET parent_id=$1,name=$2,name_normalized=$3,updated_by=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$5 AND organization_id=$6`,[parentId,name,normalizeName(name),p.userId,id,p.organizationId]);return c.json({data:{id,parentId,name}});});
  r.delete("/folders/:id",requireScope("documents:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await ownedFolder(runtime,p.organizationId,id);const used=(await runtime.db.query(`SELECT EXISTS(SELECT 1 FROM file_folders WHERE organization_id=$1 AND parent_id=$2 AND deleted_at IS NULL) OR EXISTS(SELECT 1 FROM file_items WHERE organization_id=$1 AND folder_id=$2 AND status<>'trashed' AND deleted_at IS NULL) AS used`,[p.organizationId,id])).rows[0]?.used;if(used)throw new AppError(409,"FOLDER_NOT_EMPTY","Move or archive this folder's contents before deleting it");await runtime.db.query(`UPDATE file_folders SET deleted_at=CURRENT_TIMESTAMP,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[p.userId,id,p.organizationId]);return c.body(null,204);});
  r.get("/items",async c=>{const p=c.get("principal"),params:any[]=[p.organizationId],where=["i.organization_id=$1","i.deleted_at IS NULL"],status=c.req.query("status")||"active",source=c.req.query("source"),folderId=c.req.query("folderId"),query=String(c.req.query("q")||"").trim();if(status!=="all"){params.push(status);where.push(`i.status=$${params.length}`);}if(folderId!==undefined){if(folderId){params.push(folderId);where.push(`i.folder_id=$${params.length}`);}else where.push("i.folder_id IS NULL");}if(source&&source!=="all"){params.push(source);where.push(`i.source_type=$${params.length}`);}if(query){params.push(`%${query}%`);where.push(`(i.title ILIKE $${params.length} OR i.filename ILIKE $${params.length} OR COALESCE(i.source_module,'') ILIKE $${params.length})`);}params.push(Math.min(250,Math.max(1,Number(c.req.query("limit")||100))),Math.max(0,Number(c.req.query("offset")||0)));const q=await runtime.db.query<Record<string,any>>(`${selectItem} WHERE ${where.join(" AND ")} ORDER BY i.updated_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);return c.json({data:q.rows.map(mapItem)});});
  r.get("/items/:id",async c=>{const p=c.get("principal"),item=await ownedItem(runtime,p.organizationId,c.req.param("id")),[versions,links]=await Promise.all([runtime.db.query(`SELECT id,version_number AS "versionNumber",filename,mime_type AS "mimeType",size_bytes::float8 AS "sizeBytes",checksum_sha256 AS "checksumSha256",created_by AS "createdBy",created_at AS "createdAt" FROM file_versions WHERE organization_id=$1 AND file_item_id=$2 ORDER BY version_number DESC`,[p.organizationId,item.id]),runtime.db.query(`SELECT id,module_key AS "moduleKey",entity_type AS "entityType",entity_id AS "entityId",label,created_by AS "createdBy",created_at AS "createdAt" FROM file_links WHERE organization_id=$1 AND file_item_id=$2 ORDER BY created_at DESC`,[p.organizationId,item.id])]);return c.json({data:{...mapItem(item),versions:versions.rows,links:links.rows}});});
  r.post("/upload",requireScope("documents:write"),async c=>{const p=c.get("principal"),form=await c.req.formData(),part=form.get("file");if(!(part instanceof File))throw new AppError(422,"FILE_REQUIRED","Choose a file to upload");if(part.size<=0||part.size>MAX_FILE_BYTES)throw new AppError(part.size>MAX_FILE_BYTES?413:422,"INVALID_FILE_SIZE","Files must be between 1 byte and 50 MB");const id=createId("fil"),versionId=createId("fver"),bytes=new Uint8Array(await part.arrayBuffer()),checksum=createHash("sha256").update(bytes).digest("hex"),mime=(part.type||"application/octet-stream").toLowerCase(),filename=part.name||"file",title=String(form.get("title")||filename.replace(/\.[^.]+$/,"")).trim().slice(0,240)||filename,key=`files/${p.organizationId}/${id}/v1/${safeName(filename)}`;await runtime.storage.put(key,bytes,mime);const client=await runtime.db.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO file_items(id,organization_id,title,filename,mime_type,size_bytes,checksum_sha256,object_key,source_type,source_module,source_entity_type,source_entity_id,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'upload','file-manager','file_item',$1,$9,$9)`,[id,p.organizationId,title,filename,mime,bytes.byteLength,checksum,key,p.userId]);await client.query(`INSERT INTO file_versions(id,organization_id,file_item_id,version_number,filename,mime_type,size_bytes,checksum_sha256,object_key,created_by) VALUES($1,$2,$3,1,$4,$5,$6,$7,$8,$9)`,[versionId,p.organizationId,id,filename,mime,bytes.byteLength,checksum,key,p.userId]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK").catch(()=>{});await runtime.storage.delete(key).catch(()=>{});throw error;}finally{client.release();}return c.json({data:mapItem({id,title,filename,mimeType:mime,sizeBytes:bytes.byteLength,checksumSha256:checksum,sourceType:"upload",sourceModule:"file-manager",sourceEntityType:"file_item",sourceEntityId:id,status:"active",currentVersion:1,tags:[],metadata:{},createdBy:p.userId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})},201);});
  r.post("/items/:id/versions",requireScope("documents:write"),async c=>{const p=c.get("principal"),current=await ownedItem(runtime,p.organizationId,c.req.param("id"));if(current.sourceType!=="upload")throw new AppError(409,"VERSION_NOT_ALLOWED","New versions can only be uploaded for files owned by this library");const form=await c.req.formData(),part=form.get("file");if(!(part instanceof File)||part.size<=0||part.size>MAX_FILE_BYTES)throw new AppError(422,"INVALID_FILE_SIZE","Choose a replacement file below 50 MB");const next=Number(current.currentVersion)+1,bytes=new Uint8Array(await part.arrayBuffer()),checksum=createHash("sha256").update(bytes).digest("hex"),mime=(part.type||"application/octet-stream").toLowerCase(),key=`files/${p.organizationId}/${current.id}/v${next}/${safeName(part.name)}`;await runtime.storage.put(key,bytes,mime);await runtime.db.query(`INSERT INTO file_versions(id,organization_id,file_item_id,version_number,filename,mime_type,size_bytes,checksum_sha256,object_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[createId("fver"),p.organizationId,current.id,next,part.name,mime,bytes.byteLength,checksum,key,p.userId]);await runtime.db.query(`UPDATE file_items SET filename=$1,mime_type=$2,size_bytes=$3,checksum_sha256=$4,object_key=$5,preview_object_key=NULL,preview_mime_type=NULL,current_version=$6,updated_by=$7,updated_at=CURRENT_TIMESTAMP WHERE id=$8 AND organization_id=$9`,[part.name,mime,bytes.byteLength,checksum,key,next,p.userId,current.id,p.organizationId]);return c.json({data:{id:current.id,currentVersion:next,filename:part.name,mimeType:mime,sizeBytes:bytes.byteLength,checksumSha256:checksum}},201);});
  r.patch("/items/:id",requireScope("documents:write"),async c=>{const p=c.get("principal"),current=await ownedItem(runtime,p.organizationId,c.req.param("id")),body=await c.req.json<Record<string,unknown>>().catch(()=>({})),title=body.title===undefined?current.title:String(body.title||"").trim().slice(0,240),folderId=body.folderId===undefined?(current.folderId??null):(body.folderId?String(body.folderId):null),status=body.status===undefined?current.status:String(body.status),tags=body.tags===undefined?json(current.tags,[]):Array.isArray(body.tags)?body.tags.map(String).map(x=>x.trim()).filter(Boolean).slice(0,30):[];if(!title)throw new AppError(422,"TITLE_REQUIRED","Document title is required");if(!["active","archived","trashed"].includes(status))throw new AppError(422,"INVALID_STATUS","Invalid document status");await ownedFolder(runtime,p.organizationId,folderId);await runtime.db.query(`UPDATE file_items SET title=$1,folder_id=$2,status=$3,tags_json=$4::jsonb,updated_by=$5,updated_at=CURRENT_TIMESTAMP WHERE id=$6 AND organization_id=$7`,[title,folderId,status,JSON.stringify(tags),p.userId,current.id,p.organizationId]);return c.json({data:{id:current.id,title,folderId,status,tags}});});
  r.delete("/items/:id",requireScope("documents:write"),async c=>{const p=c.get("principal"),item=await ownedItem(runtime,p.organizationId,c.req.param("id"));await runtime.db.query(`UPDATE file_items SET status='trashed',updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[p.userId,item.id,p.organizationId]);return c.body(null,204);});
  r.post("/items/:id/restore",requireScope("documents:write"),async c=>{const p=c.get("principal"),item=await ownedItem(runtime,p.organizationId,c.req.param("id"));await runtime.db.query(`UPDATE file_items SET status='active',updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[p.userId,item.id,p.organizationId]);return c.json({data:{id:item.id,status:"active"}});});
  r.get("/items/:id/content",async c=>{const p=c.get("principal"),item=await ownedItem(runtime,p.organizationId,c.req.param("id")),preview=c.req.query("preview")==="1",key=preview&&item.previewObjectKey?item.previewObjectKey:item.objectKey,mime=preview&&item.previewObjectKey?(item.previewMimeType||"application/pdf"):item.mimeType;if(!key)throw new AppError(404,"FILE_OBJECT_MISSING","This catalog entry does not have a stored file object");const bytes=await runtime.storage.get(String(key));if(!bytes)throw new AppError(404,"FILE_OBJECT_MISSING","The stored file object is unavailable");const filename=preview&&item.previewObjectKey?`${item.title}.pdf`:item.filename;c.header("Content-Type",String(mime));c.header("Content-Length",String(bytes.byteLength));c.header("Content-Disposition",`${c.req.query("download")==="1"?"attachment":"inline"}; filename="${safeName(String(filename))}"`);return c.body(bytes);});
  r.get("/items/:id/versions/:version/content",async c=>{const p=c.get("principal"),id=c.req.param("id"),version=Number(c.req.param("version"));await ownedItem(runtime,p.organizationId,id);const row=(await runtime.db.query<Record<string,any>>(`SELECT filename,mime_type AS "mimeType",object_key AS "objectKey" FROM file_versions WHERE organization_id=$1 AND file_item_id=$2 AND version_number=$3`,[p.organizationId,id,version])).rows[0];if(!row)throw new AppError(404,"VERSION_NOT_FOUND","File version not found");const bytes=await runtime.storage.get(row.objectKey);if(!bytes)throw new AppError(404,"FILE_OBJECT_MISSING","The stored file version is unavailable");c.header("Content-Type",row.mimeType);c.header("Content-Disposition",`attachment; filename="${safeName(row.filename)}"`);return c.body(bytes);});
  r.post("/sync-system",requireScope("documents:write"),async c=>{const p=c.get("principal");let schoolFiles=0;try{const result=await runtime.db.query(`INSERT INTO file_items(id,organization_id,title,filename,mime_type,size_bytes,checksum_sha256,storage_bucket,object_key,source_type,source_module,source_entity_type,source_entity_id,status,current_version,metadata_json,created_by,updated_by,created_at,updated_at) SELECT 'fil_school_'||f.id,f.organization_id,f.original_name,f.original_name,f.mime_type,f.size_bytes,f.checksum_sha256,'reports',f.object_key,'school_file','school-management','school_file',f.id,'active',1,jsonb_build_object('purpose',f.purpose),f.uploaded_by,f.uploaded_by,f.created_at,f.updated_at FROM school_files f WHERE f.organization_id=$1 AND f.deleted_at IS NULL ON CONFLICT DO NOTHING`,[p.organizationId]);schoolFiles=result.rowCount??0;}catch{}return c.json({data:{imported:schoolFiles,aiGenerated:0,schoolFiles,scannerFiles:0}});});
  return r;
}
