import { useEffect,useState,type FormEvent,type ReactNode } from "react";
import { MonitorSmartphone,Plus,RefreshCw,ScanQrCode } from "lucide-react";
import { del,errorText,get,post } from "../../../web/api";
import { Badge,Button,Card,EmptyState,Field,Modal,Notice,Spinner } from "../../../web/components/ui";
import { EnrollmentQr } from "./EnrollmentQr";
import "./devices.css";

type R=Record<string,any>;
const base="/attendance";
const words=(x:any)=>String(x??"—").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function Status({value}:{value:any}){const v=String(value||"unknown");return <Badge tone={(v==="active"?"success":v==="pending"?"warning":["revoked","suspended"].includes(v)?"danger":"neutral") as any}>{words(v)}</Badge>}
function useDevices(){const[data,setData]=useState<R[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);try{setData(await get<R[]>(`${base}/devices`));setError("")}catch(e){setError(errorText(e))}finally{setLoading(false)}};useEffect(()=>{void load()},[]);return{data,setData,loading,error,load}}
function newExitPin(){return String(crypto.getRandomValues(new Uint32Array(1))[0]%1_000_000).padStart(6,"0")}
function FormModal({title,children,close,submit}:{title:string;children:ReactNode;close:()=>void;submit:(f:FormData)=>Promise<void>}){const[busy,setBusy]=useState(false),[error,setError]=useState("");return <Modal title={title} onClose={close} locked={busy}><form className="att-modal" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");try{await submit(new FormData(e.currentTarget))}catch(x){setError(errorText(x))}finally{setBusy(false)}}}>{children}{error&&<Notice tone="danger">{error}</Notice>}<div className="att-modal-actions"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?"Saving…":"Create kiosk"}</Button></div></form></Modal>}

export function DevicesPage(){
  const devices=useDevices(),[createOpen,setCreateOpen]=useState(false),[enrollment,setEnrollment]=useState<R|null>(null),[testDevice,setTestDevice]=useState<R|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  const showEnrollment=(r:R)=>{const exitPin=newExitPin();setEnrollment({...r,exitPin,qrPayload:`LEDGERLY-ATTENDANCE:1:${r.enrollmentToken}:${exitPin}`})};
  const newQr=async(d:R)=>{setError("");try{showEnrollment(await post<R>(`${base}/kiosk-enrollment/${d.id}/refresh`,{}))}catch(e){setError(errorText(e))}};
  const revokeTest=async(d:R)=>{setError("");try{await del(`${base}/devices/${d.id}/test-mode`);setMessage(`Face test mode disabled for ${d.name}.`);await devices.load()}catch(e){setError(errorText(e))}};

  useEffect(()=>{if(!enrollment?.id)return;const timer=setInterval(async()=>{try{const rows=await get<R[]>(`${base}/devices`);devices.setData(rows);const found=rows.find(d=>d.id===enrollment.id);if(found?.status==="active"){setMessage(`${found.name} registered successfully by QR scan.`);setEnrollment(null)}}catch{/* keep the QR visible while polling fails */}},2500);return()=>clearInterval(timer)},[enrollment?.id]);

  return <div className="att-page">
    <div className="att-head"><div><small>LEDGERLY ATTENDANCE</small><h1>Devices & kiosks</h1><p>Create an Android attendance kiosk, then register the phone or tablet by scanning its one-time QR code.</p></div><div className="att-actions"><Button onClick={()=>setCreateOpen(true)}><Plus/> Create kiosk</Button></div></div>
    <Notice tone="info"><b>QR registration:</b> the QR is single-use and expires after 10 minutes. It contains only a temporary enrollment token and the kiosk exit PIN—not the permanent device credential.</Notice>
    {enrollment&&<Card className="att-device-setup att-qr-setup"><div className="att-device-setup-head"><div><small>KIOSK QR ENROLLMENT</small><h2>Scan this QR on {enrollment.name}</h2><p>Open Ledgerly Attendance on the Android device and point its rear camera at this code. The kiosk will activate automatically.</p></div><Status value="pending"/></div><div className="att-qr-layout"><div className="att-qr-frame"><EnrollmentQr value={enrollment.qrPayload}/></div><div className="att-qr-details"><div><span>Kiosk code</span><strong>{enrollment.deviceCode}</strong></div><div><span>Administrator exit PIN</span><strong className="att-pin">{enrollment.exitPin}</strong><small>Keep this PIN for exiting kiosk mode later.</small></div><div><span>QR expires</span><strong>{new Date(enrollment.enrollmentExpiresAt).toLocaleTimeString()}</strong><small>{new Date(enrollment.enrollmentExpiresAt).toLocaleDateString()}</small></div><Notice tone="warning">This QR can register only this pending kiosk and becomes unusable immediately after a successful scan.</Notice><div className="att-inline"><Button variant="secondary" onClick={async()=>{const d=devices.data.find(x=>x.id===enrollment.id)||enrollment;await newQr(d)}}><RefreshCw/> Generate new QR</Button><Button onClick={()=>setEnrollment(null)}>Close</Button></div></div></div></Card>}
    {message&&<Notice tone="success">{message}</Notice>}{error&&<Notice tone="danger">{error}</Notice>}
    <Card>{devices.loading?<Spinner/>:devices.error?<Notice tone="danger">{devices.error}</Notice>:!devices.data.length?<EmptyState title="No kiosks created" description="Create a kiosk and scan its QR code with the Android Attendance app."/>:<div className="att-device-grid">{devices.data.map(d=>{const test=!!(d.testModeExpiresAt&&new Date(d.testModeExpiresAt)>new Date());return <article key={d.id}><MonitorSmartphone/><div><b>{d.name}</b><small>{d.deviceCode} · {d.locationName||"No location"}</small><span>{d.population} · {d.direction} · device camera</span>{d.status==="pending"&&<small className="att-pending-device">Waiting for QR scan</small>}{test&&<small className="att-test-active">⚠ Test mode until {new Date(d.testModeExpiresAt).toLocaleTimeString()}</small>}</div><div className="att-device-actions"><Status value={d.status}/>{d.status==="pending"?<button onClick={()=>void newQr(d)}><ScanQrCode/> Show QR</button>:test?<button onClick={()=>void revokeTest(d)}>Disable test</button>:d.status==="active"?<button onClick={()=>setTestDevice(d)}>Face test mode</button>:null}</div></article>})}</div>}</Card>
    {createOpen&&<FormModal title="Create attendance kiosk" close={()=>setCreateOpen(false)} submit={async f=>{const r=await post<R>(`${base}/kiosk-enrollment`,{name:f.get("name"),locationName:f.get("location"),population:f.get("population"),direction:f.get("direction")});showEnrollment(r);setCreateOpen(false);await devices.load()}}><Notice tone="info">After creation, Ledgerly will display a QR code. Scan it from the Android Attendance app to finish registration.</Notice><Field label="Kiosk name"><input name="name" required placeholder="Main Gate Tablet"/></Field><Field label="Location"><input name="location" placeholder="Main Gate"/></Field><div className="att-form-grid"><Field label="Population"><select name="population"><option value="mixed">Students + staff</option><option value="students">Students</option><option value="staff">Staff</option></select></Field><Field label="Direction"><select name="direction"><option value="BOTH">IN and OUT</option><option value="IN">IN only</option><option value="OUT">OUT only</option></select></Field></div></FormModal>}
    {testDevice&&<FormModal title={`Face test mode · ${testDevice.name}`} close={()=>setTestDevice(null)} submit={async f=>{await post(`${base}/devices/${testDevice.id}/test-mode`,{allowScreenImage:!!f.get("screen"),allowPrintedImage:!!f.get("print"),minutes:Number(f.get("minutes")||30),reason:String(f.get("reason")||"")});setTestDevice(null);setMessage(`Temporary face test mode enabled for ${testDevice.name}.`);await devices.load()}}><Notice tone="warning">Testing only. Liveness is bypassed for the selected spoof types and resulting face captures are stored as unofficial test events.</Notice><label className="att-check"><input name="screen" type="checkbox"/> Allow a face displayed on another phone/screen</label><label className="att-check"><input name="print" type="checkbox"/> Allow a printed photograph</label><Field label="Expires after"><select name="minutes" defaultValue="30"><option value="10">10 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option></select></Field><Field label="Reason"><textarea name="reason" required placeholder="Testing face recognition before rollout"/></Field></FormModal>}
  </div>;
}
