import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const hhmm=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const schemeSchema=z.object({academicYearId:z.string(),termId:z.string(),classId:z.string(),streamId:z.string().nullable().optional(),subjectId:z.string(),teacherStaffId:z.string().nullable().optional(),curriculumId:z.string().nullable().optional(),title:z.string().min(2)});
const availabilitySchema=z.object({teacherStaffId:z.string(),weekday:z.number().int().min(1).max(7),startsAt:hhmm,endsAt:hhmm,available:z.boolean().default(true),notes:z.string().max(1000).nullable().optional()});
const timetableSchema=z.object({academicYearId:z.string(),termId:z.string(),name:z.string().min(2).max(180),notes:z.string().max(2000).nullable().optional()});
const entrySchema=z.object({classId:z.string(),streamId:z.string().nullable().optional(),subjectId:z.string(),teacherStaffId:z.string(),roomId:z.string().nullable().optional(),weekday:z.number().int().min(1).max(7),startsAt:hhmm,endsAt:hhmm,lessonPeriodId:z.string().nullable().optional(),notes:z.string().max(1000).nullable().optional()});

async function activeTeacher(runtime:Runtime,org:string,id:string){const q=await runtime.db.query(`SELECT 1 FROM school_staff_profiles WHERE id=$1 AND organization_id=$2 AND employment_status='active' AND deleted_at IS NULL`,[id,org]);if(!q.rowCount)throw new AppError(422,"INVALID_TEACHER","Teacher must be an active staff member in this school");}
async function hierarchy(runtime:Runtime,org:string,yearId:string,termId:string,classId?:string|null,streamId?:string|null){const term=await runtime.db.query(`SELECT 1 FROM school_terms WHERE id=$1 AND organization_id=$2 AND academic_year_id=$3`,[termId,org,yearId]);if(!term.rowCount)throw new AppError(422,"TERM_YEAR_MISMATCH","Term does not belong to the selected academic year");if(classId){const cls=await runtime.db.query(`SELECT 1 FROM school_classes WHERE id=$1 AND organization_id=$2 AND academic_year_id=$3`,[classId,org,yearId]);if(!cls.rowCount)throw new AppError(422,"CLASS_YEAR_MISMATCH","Class does not belong to the selected academic year");}if(streamId){const st=await runtime.db.query(`SELECT 1 FROM school_streams WHERE id=$1 AND organization_id=$2 AND class_id=$3`,[streamId,org,classId]);if(!st.rowCount)throw new AppError(422,"STREAM_CLASS_MISMATCH","Stream does not belong to the selected class");}}

export function createAcademicReferenceIntegrityRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.post("/schemes",requireScope("school:write"),async c=>{const s=schemeSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid scheme",s.error.flatten());const p=c.get("principal"),v=s.data;await hierarchy(runtime,p.organizationId,v.academicYearId,v.termId,v.classId,v.streamId);const subject=await runtime.db.query(`SELECT 1 FROM school_subjects WHERE id=$1 AND organization_id=$2`,[v.subjectId,p.organizationId]);if(!subject.rowCount)throw new AppError(422,"INVALID_SUBJECT","Subject does not belong to this school");if(v.teacherStaffId)await activeTeacher(runtime,p.organizationId,v.teacherStaffId);if(v.curriculumId&&! (await runtime.db.query(`SELECT 1 FROM school_curricula WHERE id=$1 AND organization_id=$2 AND active=true`,[v.curriculumId,p.organizationId])).rowCount)throw new AppError(422,"INVALID_CURRICULUM","Curriculum is not active in this school");const id=createId("sch");await runtime.db.query(`INSERT INTO school_schemes_of_work(id,organization_id,academic_year_id,term_id,class_id,stream_id,subject_id,teacher_staff_id,curriculum_id,title,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,p.organizationId,v.academicYearId,v.termId,v.classId,v.streamId??null,v.subjectId,v.teacherStaffId??null,v.curriculumId??null,v.title,p.userId]);return c.json({data:{id,status:"draft",...v}},201);});
 r.post("/teacher-availability",requireScope("school:write"),async c=>{const s=availabilitySchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid teacher availability",s.error.flatten());const p=c.get("principal"),v=s.data;if(v.endsAt<=v.startsAt)throw new AppError(422,"VALIDATION_ERROR","endsAt must be after startsAt");await activeTeacher(runtime,p.organizationId,v.teacherStaffId);const id=createId("ava");await runtime.db.query(`INSERT INTO school_teacher_availability(id,organization_id,teacher_staff_id,weekday,starts_at,ends_at,available,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.teacherStaffId,v.weekday,v.startsAt,v.endsAt,v.available,v.notes??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.post("/timetables",requireScope("school:write"),async c=>{const s=timetableSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid timetable",s.error.flatten());const p=c.get("principal"),v=s.data;await hierarchy(runtime,p.organizationId,v.academicYearId,v.termId);const id=createId("ttb");await runtime.db.query(`INSERT INTO school_academic_timetables(id,organization_id,academic_year_id,term_id,name,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,v.academicYearId,v.termId,v.name,v.notes??null,p.userId]);return c.json({data:{id,status:"draft",...v}},201);});
 r.post("/timetables/:id/entries",requireScope("school:write"),async c=>{const s=entrySchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid timetable entry",s.error.flatten());const p=c.get("principal"),tid=c.req.param("id"),v=s.data;if(v.endsAt<=v.startsAt)throw new AppError(422,"VALIDATION_ERROR","endsAt must be after startsAt");const tt=(await runtime.db.query(`SELECT academic_year_id,term_id,status FROM school_academic_timetables WHERE id=$1 AND organization_id=$2`,[tid,p.organizationId])).rows[0] as any;if(!tt)throw new AppError(404,"NOT_FOUND","Timetable not found");if(!["draft","submitted"].includes(String(tt.status)))throw new AppError(409,"TIMETABLE_LOCKED","Approved, published or archived timetables cannot be edited");await hierarchy(runtime,p.organizationId,String(tt.academic_year_id),String(tt.term_id),v.classId,v.streamId);await activeTeacher(runtime,p.organizationId,v.teacherStaffId);if(! (await runtime.db.query(`SELECT 1 FROM school_subjects WHERE id=$1 AND organization_id=$2`,[v.subjectId,p.organizationId])).rowCount)throw new AppError(422,"INVALID_SUBJECT","Subject does not belong to this school");if(v.roomId&&! (await runtime.db.query(`SELECT 1 FROM school_academic_rooms WHERE id=$1 AND organization_id=$2 AND active=true`,[v.roomId,p.organizationId])).rowCount)throw new AppError(422,"INVALID_ROOM","Room is not active in this school");const conflict=await runtime.db.query(`SELECT 1 FROM school_academic_timetable_entries WHERE organization_id=$1 AND timetable_id=$2 AND weekday=$3 AND starts_at<$5::time AND ends_at>$4::time AND (teacher_staff_id=$6 OR class_id=$7 OR ($8::text IS NOT NULL AND room_id=$8)) LIMIT 1`,[p.organizationId,tid,v.weekday,v.startsAt,v.endsAt,v.teacherStaffId,v.classId,v.roomId??null]);if(conflict.rowCount)throw new AppError(409,"TIMETABLE_CONFLICT","Teacher, class or room already has an overlapping lesson");const unavailable=await runtime.db.query(`SELECT 1 FROM school_teacher_availability WHERE organization_id=$1 AND teacher_staff_id=$2 AND weekday=$3 AND available=false AND starts_at<$5::time AND ends_at>$4::time LIMIT 1`,[p.organizationId,v.teacherStaffId,v.weekday,v.startsAt,v.endsAt]);if(unavailable.rowCount)throw new AppError(409,"TEACHER_UNAVAILABLE","Teacher is unavailable during this period");const id=createId("tte");await runtime.db.query(`INSERT INTO school_academic_timetable_entries(id,organization_id,timetable_id,class_id,stream_id,subject_id,teacher_staff_id,room_id,weekday,starts_at,ends_at,lesson_period_id,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[id,p.organizationId,tid,v.classId,v.streamId??null,v.subjectId,v.teacherStaffId,v.roomId??null,v.weekday,v.startsAt,v.endsAt,v.lessonPeriodId??null,v.notes??null,p.userId]);return c.json({data:{id,timetableId:tid,...v}},201);});
 return r;}
