import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const curriculumSchema=z.object({code:z.string().min(1),name:z.string().min(2),authority:z.string().nullable().optional(),version:z.string().nullable().optional(),startsOn:date.nullable().optional(),endsOn:date.nullable().optional()});
const schemeSchema=z.object({academicYearId:z.string(),termId:z.string(),classId:z.string(),streamId:z.string().nullable().optional(),subjectId:z.string(),teacherStaffId:z.string().nullable().optional(),curriculumId:z.string().nullable().optional(),title:z.string().min(2)});
const itemSchema=z.object({syllabusTopicId:z.string().nullable().optional(),weekNumber:z.number().int().positive(),sequence:z.number().int().positive().default(1),topic:z.string().min(1),subtopic:z.string().nullable().optional(),learningOutcomes:z.string().nullable().optional(),teachingMethods:z.string().nullable().optional(),learningResources:z.string().nullable().optional(),assessmentStrategy:z.string().nullable().optional(),plannedPeriods:z.number().int().positive().default(1)});
function camel(row:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(row))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
async function owned(runtime:Runtime,org:string,table:string,id?:string|null){if(!id)return;const q=await runtime.db.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(422,"INVALID_REFERENCE",`${table} record does not belong to this school`);}

export function createAcademicsRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/manifest",c=>c.json({data:{key:"academics",version:"1.0.0",features:["curriculum","syllabus","schemes-of-work"]}}));
 r.get("/curricula",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT * FROM school_curricula WHERE organization_id=$1 ORDER BY active DESC,name`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/curricula",requireScope("school:write"),async c=>{const s=curriculumSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid curriculum",s.error.flatten());const p=c.get("principal"),v=s.data,id=createId("cur");await runtime.db.query(`INSERT INTO school_curricula(id,organization_id,code,name,authority,version,starts_on,ends_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.code.toUpperCase(),v.name,v.authority??null,v.version??null,v.startsOn??null,v.endsOn??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.get("/syllabus",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT u.*,s.name subject_name,cl.name class_level_name,c.name curriculum_name FROM school_syllabus_units u JOIN school_subjects s ON s.id=u.subject_id LEFT JOIN school_class_levels cl ON cl.id=u.class_level_id JOIN school_curricula c ON c.id=u.curriculum_id WHERE u.organization_id=$1 ORDER BY s.name,u.sequence`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/syllabus",requireScope("school:write"),async c=>{const p=c.get("principal"),b=await c.req.json().catch(()=>({})) as any;for(const [t,id] of [["school_curricula",b.curriculumId],["school_subjects",b.subjectId],["school_class_levels",b.classLevelId]] as const)await owned(runtime,p.organizationId,t,id);if(!b.code||!b.title)throw new AppError(422,"VALIDATION_ERROR","code and title are required");const id=createId("syl");await runtime.db.query(`INSERT INTO school_syllabus_units(id,organization_id,curriculum_id,class_level_id,subject_id,code,title,sequence,competencies,learning_outcomes,suggested_periods) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,p.organizationId,b.curriculumId,b.classLevelId??null,b.subjectId,String(b.code),String(b.title),Number(b.sequence??1),b.competencies??null,b.learningOutcomes??null,b.suggestedPeriods??null]);return c.json({data:{id,...b}},201);});
 r.post("/syllabus/:unitId/topics",requireScope("school:write"),async c=>{const p=c.get("principal"),unitId=c.req.param("unitId"),b=await c.req.json().catch(()=>({})) as any;await owned(runtime,p.organizationId,"school_syllabus_units",unitId);if(!b.title)throw new AppError(422,"VALIDATION_ERROR","title is required");const id=createId("top");await runtime.db.query(`INSERT INTO school_syllabus_topics(id,organization_id,unit_id,code,title,sequence,learning_outcomes,content_notes,suggested_periods) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,unitId,b.code??null,b.title,Number(b.sequence??1),b.learningOutcomes??null,b.contentNotes??null,b.suggestedPeriods??null]);return c.json({data:{id,unitId,...b}},201);});
 r.get("/schemes",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT w.*,s.name subject_name,c.name class_name,st.name stream_name FROM school_schemes_of_work w JOIN school_subjects s ON s.id=w.subject_id JOIN school_classes c ON c.id=w.class_id LEFT JOIN school_streams st ON st.id=w.stream_id WHERE w.organization_id=$1 ORDER BY w.created_at DESC`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/schemes",requireScope("school:write"),async c=>{const s=schemeSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid scheme",s.error.flatten());const p=c.get("principal"),v=s.data;for(const [t,id] of [["school_academic_years",v.academicYearId],["school_terms",v.termId],["school_classes",v.classId],["school_streams",v.streamId],["school_subjects",v.subjectId],["school_staff_profiles",v.teacherStaffId],["school_curricula",v.curriculumId]] as const)await owned(runtime,p.organizationId,t,id);const id=createId("sch");await runtime.db.query(`INSERT INTO school_schemes_of_work(id,organization_id,academic_year_id,term_id,class_id,stream_id,subject_id,teacher_staff_id,curriculum_id,title,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,p.organizationId,v.academicYearId,v.termId,v.classId,v.streamId??null,v.subjectId,v.teacherStaffId??null,v.curriculumId??null,v.title,p.userId]);return c.json({data:{id,status:"draft",...v}},201);});
 r.post("/schemes/:id/items",requireScope("school:write"),async c=>{const s=itemSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid scheme item",s.error.flatten());const p=c.get("principal"),schemeId=c.req.param("id"),v=s.data;await owned(runtime,p.organizationId,"school_schemes_of_work",schemeId);await owned(runtime,p.organizationId,"school_syllabus_topics",v.syllabusTopicId);const id=createId("sci");await runtime.db.query(`INSERT INTO school_scheme_items(id,organization_id,scheme_id,syllabus_topic_id,week_number,sequence,topic,subtopic,learning_outcomes,teaching_methods,learning_resources,assessment_strategy,planned_periods) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[id,p.organizationId,schemeId,v.syllabusTopicId??null,v.weekNumber,v.sequence,v.topic,v.subtopic??null,v.learningOutcomes??null,v.teachingMethods??null,v.learningResources??null,v.assessmentStrategy??null,v.plannedPeriods]);return c.json({data:{id,...v}},201);});
 r.post("/schemes/:id/workflow",requireScope("school:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),b=await c.req.json().catch(()=>({})) as any,action=String(b.action??"");const q=await runtime.db.query(`SELECT status FROM school_schemes_of_work WHERE id=$1 AND organization_id=$2`,[id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Scheme not found");const current=String(q.rows[0].status);let next:string;if(action==="submit"&&["draft","rejected"].includes(current))next="submitted";else if(action==="approve"&&current==="submitted")next="approved";else if(action==="reject"&&current==="submitted")next="rejected";else throw new AppError(409,"INVALID_WORKFLOW","Invalid scheme workflow action");await runtime.db.query(`UPDATE school_schemes_of_work SET status=$1,submitted_at=CASE WHEN $1='submitted' THEN CURRENT_TIMESTAMP ELSE submitted_at END,submitted_by=CASE WHEN $1='submitted' THEN $2 ELSE submitted_by END,reviewed_at=CASE WHEN $1 IN ('approved','rejected') THEN CURRENT_TIMESTAMP ELSE reviewed_at END,reviewed_by=CASE WHEN $1 IN ('approved','rejected') THEN $2 ELSE reviewed_by END,review_notes=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$4`,[next,p.userId,b.notes??null,id]);return c.json({data:{id,status:next}});});
 return r;}
