import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const curriculumSchema=z.object({code:z.string().min(1),name:z.string().min(2),authority:z.string().nullable().optional(),version:z.string().nullable().optional(),startsOn:date.nullable().optional(),endsOn:date.nullable().optional()});
function camel(row:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(row))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
async function owned(runtime:Runtime,org:string,table:string,id?:string|null){if(!id)return;const q=await runtime.db.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(422,"INVALID_REFERENCE",`${table} record does not belong to this school`);}

export function createAcademicsRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/manifest",c=>c.json({data:{key:"academics",version:"1.0.0",features:["curriculum","syllabus","schemes-of-work"]}}));
 r.get("/setup",async c=>{const p=c.get("principal"),org=p.organizationId;const[years,terms,classes,streams,subjects,teachers,students,teacherAllocations]=await Promise.all([
  runtime.db.query(`SELECT id,code,name,is_current AS "isCurrent",status FROM school_academic_years WHERE organization_id=$1 ORDER BY starts_on DESC`,[org]),
  runtime.db.query(`SELECT id,academic_year_id AS "academicYearId",code,name,sequence_no AS "sequenceNo",is_current AS "isCurrent",status FROM school_terms WHERE organization_id=$1 ORDER BY starts_on DESC,sequence_no`,[org]),
  runtime.db.query(`SELECT id,academic_year_id AS "academicYearId",class_level_id AS "classLevelId",code,name FROM school_classes WHERE organization_id=$1 AND active=true ORDER BY name`,[org]),
  runtime.db.query(`SELECT id,class_id AS "classId",code,name FROM school_streams WHERE organization_id=$1 AND active=true ORDER BY name`,[org]),
  runtime.db.query(`SELECT id,department_id AS "departmentId",code,name,short_name AS "shortName" FROM school_subjects WHERE organization_id=$1 AND active=true ORDER BY name`,[org]),
  runtime.db.query(`SELECT id,staff_number AS "staffNumber",first_name||' '||last_name AS name FROM school_staff_profiles WHERE organization_id=$1 AND is_teacher=true AND employment_status='active' ORDER BY first_name,last_name`,[org]),
  runtime.db.query(`SELECT id,admission_number AS "admissionNumber",student_number AS "studentNumber",current_class_id AS "classId",current_stream_id AS "streamId",concat_ws(' ',first_name,middle_name,last_name) AS name FROM school_students WHERE organization_id=$1 AND deleted_at IS NULL AND status IN ('active','suspended') ORDER BY last_name,first_name`,[org]),
  runtime.db.query(`SELECT id,academic_year_id AS "academicYearId",term_id AS "termId",class_id AS "classId",stream_id AS "streamId",subject_id AS "subjectId",staff_id AS "teacherStaffId" FROM school_staff_teaching_assignments WHERE organization_id=$1 AND active=true`,[org]),
 ]);return c.json({data:{years:years.rows,terms:terms.rows,classes:classes.rows,streams:streams.rows,subjects:subjects.rows,teachers:teachers.rows,students:students.rows,teacherAllocations:teacherAllocations.rows}});});
 r.get("/curricula",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT * FROM school_curricula WHERE organization_id=$1 ORDER BY active DESC,name`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/curricula",requireScope("school:write"),async c=>{const s=curriculumSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid curriculum",s.error.flatten());const p=c.get("principal"),v=s.data,id=createId("cur");await runtime.db.query(`INSERT INTO school_curricula(id,organization_id,code,name,authority,version,starts_on,ends_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.code.toUpperCase(),v.name,v.authority??null,v.version??null,v.startsOn??null,v.endsOn??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.get("/syllabus",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT u.*,s.name subject_name,cl.name class_level_name,c.name curriculum_name FROM school_syllabus_units u JOIN school_subjects s ON s.id=u.subject_id LEFT JOIN school_class_levels cl ON cl.id=u.class_level_id JOIN school_curricula c ON c.id=u.curriculum_id WHERE u.organization_id=$1 ORDER BY s.name,u.sequence`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/syllabus",requireScope("school:write"),async c=>{const p=c.get("principal"),b=await c.req.json().catch(()=>({})) as any;for(const [t,id] of [["school_curricula",b.curriculumId],["school_subjects",b.subjectId],["school_class_levels",b.classLevelId]] as const)await owned(runtime,p.organizationId,t,id);if(!b.code||!b.title)throw new AppError(422,"VALIDATION_ERROR","code and title are required");const id=createId("syl");await runtime.db.query(`INSERT INTO school_syllabus_units(id,organization_id,curriculum_id,class_level_id,subject_id,code,title,sequence,competencies,learning_outcomes,suggested_periods) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,p.organizationId,b.curriculumId,b.classLevelId??null,b.subjectId,String(b.code),String(b.title),Number(b.sequence??1),b.competencies??null,b.learningOutcomes??null,b.suggestedPeriods??null]);return c.json({data:{id,...b}},201);});
 r.post("/syllabus/:unitId/topics",requireScope("school:write"),async c=>{const p=c.get("principal"),unitId=c.req.param("unitId"),b=await c.req.json().catch(()=>({})) as any;await owned(runtime,p.organizationId,"school_syllabus_units",unitId);if(!b.title)throw new AppError(422,"VALIDATION_ERROR","title is required");const id=createId("top");await runtime.db.query(`INSERT INTO school_syllabus_topics(id,organization_id,unit_id,code,title,sequence,learning_outcomes,content_notes,suggested_periods) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,unitId,b.code??null,b.title,Number(b.sequence??1),b.learningOutcomes??null,b.contentNotes??null,b.suggestedPeriods??null]);return c.json({data:{id,unitId,...b}},201);});
 return r;}
