import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function camel(r:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(r))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
async function owned(rt:Runtime,org:string,t:string,id?:string|null){if(!id)return;const q=await rt.db.query(`SELECT 1 FROM ${t} WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(422,"INVALID_REFERENCE",`${t} record does not belong to this school`);}
const hhmm=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const roomSchema=z.object({code:z.string().min(1).max(40),name:z.string().min(1).max(120),campusId:z.string().nullable().optional(),capacity:z.number().int().positive().nullable().optional(),notes:z.string().max(1000).nullable().optional()});
const availabilitySchema=z.object({teacherStaffId:z.string(),weekday:z.number().int().min(1).max(7),startsAt:hhmm,endsAt:hhmm,available:z.boolean().default(true),notes:z.string().max(1000).nullable().optional()});
const timetableSchema=z.object({academicYearId:z.string(),termId:z.string(),name:z.string().min(2).max(180),notes:z.string().max(2000).nullable().optional()});
const entrySchema=z.object({classId:z.string(),streamId:z.string().nullable().optional(),subjectId:z.string(),teacherStaffId:z.string(),roomId:z.string().nullable().optional(),weekday:z.number().int().min(1).max(7),startsAt:hhmm,endsAt:hhmm,lessonPeriodId:z.string().nullable().optional(),notes:z.string().max(1000).nullable().optional()});
function overlapWhere(alias:string){return `${alias}.weekday=$4 AND ${alias}.starts_at < $6::time AND ${alias}.ends_at > $5::time`;}

export function createAcademicTimetableRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/rooms",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT * FROM school_academic_rooms WHERE organization_id=$1 ORDER BY active DESC,name`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/rooms",requireScope("school:write"),async c=>{const s=roomSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid academic room",s.error.flatten());const p=c.get("principal"),v=s.data;await owned(runtime,p.organizationId,"school_branches",v.campusId);const id=createId("arm");await runtime.db.query(`INSERT INTO school_academic_rooms(id,organization_id,code,name,campus_id,capacity,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,p.organizationId,v.code.trim().toUpperCase(),v.name,v.campusId??null,v.capacity??null,v.notes??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.get("/teacher-availability",async c=>{const p=c.get("principal"),teacher=c.req.query("teacherStaffId"),q=await runtime.db.query(`SELECT a.*,concat_ws(' ',s.first_name,s.last_name) teacher_name FROM school_teacher_availability a JOIN school_staff_profiles s ON s.id=a.teacher_staff_id WHERE a.organization_id=$1 AND ($2::text IS NULL OR a.teacher_staff_id=$2) ORDER BY a.teacher_staff_id,a.weekday,a.starts_at`,[p.organizationId,teacher??null]);return c.json({data:q.rows.map(camel)});});
 r.post("/teacher-availability",requireScope("school:write"),async c=>{const s=availabilitySchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid teacher availability",s.error.flatten());const p=c.get("principal"),v=s.data;if(v.endsAt<=v.startsAt)throw new AppError(422,"VALIDATION_ERROR","endsAt must be after startsAt");await owned(runtime,p.organizationId,"school_staff_profiles",v.teacherStaffId);const id=createId("ava");await runtime.db.query(`INSERT INTO school_teacher_availability(id,organization_id,teacher_staff_id,weekday,starts_at,ends_at,available,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.teacherStaffId,v.weekday,v.startsAt,v.endsAt,v.available,v.notes??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.delete("/teacher-availability/:id",requireScope("school:write"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`DELETE FROM school_teacher_availability WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Availability record not found");return c.body(null,204);});
 r.get("/timetables",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT t.*,ay.name academic_year_name,tr.name term_name,(SELECT COUNT(*)::int FROM school_academic_timetable_entries e WHERE e.timetable_id=t.id) entry_count FROM school_academic_timetables t JOIN school_academic_years ay ON ay.id=t.academic_year_id JOIN school_terms tr ON tr.id=t.term_id WHERE t.organization_id=$1 ORDER BY t.created_at DESC`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/timetables",requireScope("school:write"),async c=>{const s=timetableSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid timetable",s.error.flatten());const p=c.get("principal"),v=s.data;await owned(runtime,p.organizationId,"school_academic_years",v.academicYearId);await owned(runtime,p.organizationId,"school_terms",v.termId);const id=createId("ttb");await runtime.db.query(`INSERT INTO school_academic_timetables(id,organization_id,academic_year_id,term_id,name,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,v.academicYearId,v.termId,v.name,v.notes??null,p.userId]);return c.json({data:{id,status:"draft",...v}},201);});
 r.get("/timetables/:id/entries",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT e.*,cl.name class_name,st.name stream_name,su.name subject_name,concat_ws(' ',sp.first_name,sp.last_name) teacher_name,rm.name room_name FROM school_academic_timetable_entries e JOIN school_classes cl ON cl.id=e.class_id LEFT JOIN school_streams st ON st.id=e.stream_id JOIN school_subjects su ON su.id=e.subject_id JOIN school_staff_profiles sp ON sp.id=e.teacher_staff_id LEFT JOIN school_academic_rooms rm ON rm.id=e.room_id WHERE e.organization_id=$1 AND e.timetable_id=$2 ORDER BY e.weekday,e.starts_at,cl.name,st.name`,[p.organizationId,c.req.param("id")]);return c.json({data:q.rows.map(camel)});});
 r.post("/timetables/:id/conflicts",requireScope("school:write"),async c=>{const s=entrySchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid timetable entry",s.error.flatten());const p=c.get("principal"),v=s.data,tid=c.req.param("id");const q=await runtime.db.query(`SELECT id,class_id,stream_id,subject_id,teacher_staff_id,room_id,weekday,starts_at,ends_at FROM school_academic_timetable_entries e WHERE e.organization_id=$1 AND e.timetable_id=$2 AND ${overlapWhere("e")} AND (e.teacher_staff_id=$3 OR e.class_id=$7 OR ($8::text IS NOT NULL AND e.room_id=$8))`,[p.organizationId,tid,v.teacherStaffId,v.weekday,v.startsAt,v.endsAt,v.classId,v.roomId??null]);return c.json({data:{conflicts:q.rows.map(camel)}});});
 r.post("/timetables/:id/entries",requireScope("school:write"),async c=>{const s=entrySchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid timetable entry",s.error.flatten());const p=c.get("principal"),v=s.data,tid=c.req.param("id");if(v.endsAt<=v.startsAt)throw new AppError(422,"VALIDATION_ERROR","endsAt must be after startsAt");for(const[t,id]of [["school_academic_timetables",tid],["school_classes",v.classId],["school_streams",v.streamId],["school_subjects",v.subjectId],["school_staff_profiles",v.teacherStaffId],["school_academic_rooms",v.roomId]] as const)await owned(runtime,p.organizationId,t,id);const conflicts=await runtime.db.query(`SELECT id FROM school_academic_timetable_entries e WHERE e.organization_id=$1 AND e.timetable_id=$2 AND ${overlapWhere("e")} AND (e.teacher_staff_id=$3 OR e.class_id=$7 OR ($8::text IS NOT NULL AND e.room_id=$8)) LIMIT 1`,[p.organizationId,tid,v.teacherStaffId,v.weekday,v.startsAt,v.endsAt,v.classId,v.roomId??null]);if(conflicts.rowCount)throw new AppError(409,"TIMETABLE_CONFLICT","Teacher, class or room already has an overlapping lesson");const unavailable=await runtime.db.query(`SELECT 1 FROM school_teacher_availability a WHERE a.organization_id=$1 AND a.teacher_staff_id=$2 AND a.weekday=$3 AND a.available=false AND a.starts_at < $5::time AND a.ends_at > $4::time LIMIT 1`,[p.organizationId,v.teacherStaffId,v.weekday,v.startsAt,v.endsAt]);if(unavailable.rowCount)throw new AppError(409,"TEACHER_UNAVAILABLE","Teacher is unavailable during this period");const id=createId("tte");await runtime.db.query(`INSERT INTO school_academic_timetable_entries(id,organization_id,timetable_id,class_id,stream_id,subject_id,teacher_staff_id,room_id,weekday,starts_at,ends_at,lesson_period_id,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[id,p.organizationId,tid,v.classId,v.streamId??null,v.subjectId,v.teacherStaffId,v.roomId??null,v.weekday,v.startsAt,v.endsAt,v.lessonPeriodId??null,v.notes??null,p.userId]);return c.json({data:{id,timetableId:tid,...v}},201);});
 r.delete("/timetable-entries/:id",requireScope("school:write"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`DELETE FROM school_academic_timetable_entries WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Timetable entry not found");return c.body(null,204);});
 r.post("/timetables/:id/workflow",requireScope("school:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),b=await c.req.json().catch(()=>({})) as any,action=String(b.action??"");const q=await runtime.db.query(`SELECT status FROM school_academic_timetables WHERE id=$1 AND organization_id=$2`,[id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Timetable not found");const cur=String(q.rows[0].status);let next="";if(action==="submit"&&cur==="draft")next="submitted";if(action==="approve"&&cur==="submitted")next="approved";if(action==="publish"&&cur==="approved")next="published";if(action==="archive"&&["approved","published"].includes(cur))next="archived";if(!next)throw new AppError(409,"INVALID_WORKFLOW","Invalid timetable workflow action");await runtime.db.query(`UPDATE school_academic_timetables SET status=$1,submitted_at=CASE WHEN $1='submitted' THEN CURRENT_TIMESTAMP ELSE submitted_at END,submitted_by=CASE WHEN $1='submitted' THEN $2 ELSE submitted_by END,approved_at=CASE WHEN $1='approved' THEN CURRENT_TIMESTAMP ELSE approved_at END,approved_by=CASE WHEN $1='approved' THEN $2 ELSE approved_by END,published_at=CASE WHEN $1='published' THEN CURRENT_TIMESTAMP ELSE published_at END,published_by=CASE WHEN $1='published' THEN $2 ELSE published_by END,updated_at=CURRENT_TIMESTAMP WHERE id=$3`,[next,p.userId,id]);return c.json({data:{id,status:next}});});
 return r;}
