import { createCipheriv, createHash, randomBytes } from "node:crypto";
import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";
import { completeStockCount, recordMovement } from "../inventory/service.js";

function encryptAccountNumber(value:string,secret:string){const key=createHash("sha256").update(`supplier-bank:${secret}`).digest(),iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,iv),encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]),tag=cipher.getAuthTag();return `v1.${iv.toString("base64url")}.${tag.toString("base64url")}.${encrypted.toString("base64url")}`;}

const supplierBank=z.object({bankName:z.string().min(1).max(160),accountName:z.string().min(1).max(160),accountNumber:z.string().min(4).max(120),branchCode:z.string().max(80).optional(),swiftBic:z.string().max(30).optional(),currency:z.string().length(3).transform(v=>v.toUpperCase())});
const cheque=z.object({bankAccountId:z.string(),chequeNumber:z.string().min(1).max(80),payeeContactId:z.string().optional(),issueDate:z.iso.date(),amountMinor:z.number().int().positive(),paymentId:z.string().optional()});
const lot=z.object({productId:z.string(),locationId:z.string(),lotNumber:z.string().min(1).max(120),serialNumber:z.string().max(120).optional(),expiryDate:z.iso.date().optional(),quantityMicros:z.number().int().positive(),unitCostMinor:z.number().int().nonnegative(),receivedAt:z.iso.date(),offsetAccountId:z.string()});

export function createFinanceMaintenanceRoutes(runtime:Runtime){const r=new Hono<AppEnv>();
 r.get("/contacts/:id/bank-accounts",requireScope("contacts:read"),async c=>{const p=c.get("principal"),rows=await runtime.db.query(`SELECT id,bank_name AS "bankName",account_name AS "accountName",account_number_masked AS "accountNumberMasked",branch_code AS "branchCode",swift_bic AS "swiftBic",currency,active FROM supplier_bank_accounts WHERE organization_id=$1 AND contact_id=$2 ORDER BY created_at DESC`,[p.organizationId,c.req.param("id")]);return c.json({data:rows.rows});});
 r.post("/contacts/:id/bank-accounts",requireScope("contacts:write"),async c=>{const s=supplierBank.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid supplier bank account",s.error.flatten());const p=c.get("principal"),contactId=c.req.param("id"),supplier=await runtime.db.query(`SELECT 1 FROM contacts WHERE id=$1 AND organization_id=$2 AND type='supplier' AND active=true AND archived_at IS NULL`,[contactId,p.organizationId]);if(!supplier.rowCount)throw new AppError(422,"INVALID_SUPPLIER","Supplier contact required");const id=createId("sba"),masked=`****${s.data.accountNumber.slice(-4)}`,encrypted=encryptAccountNumber(s.data.accountNumber,runtime.config.JWT_SECRET);await runtime.db.query(`INSERT INTO supplier_bank_accounts(id,organization_id,contact_id,bank_name,account_name,account_number_masked,account_number_encrypted,branch_code,swift_bic,currency) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,p.organizationId,contactId,s.data.bankName,s.data.accountName,masked,encrypted,s.data.branchCode??null,s.data.swiftBic??null,s.data.currency]);return c.json({data:{id,bankName:s.data.bankName,accountName:s.data.accountName,accountNumberMasked:masked,branchCode:s.data.branchCode,swiftBic:s.data.swiftBic,currency:s.data.currency,active:true}},201);});

 r.get("/cheques",requireScope("payments:read"),async c=>{const p=c.get("principal"),rows=await runtime.db.query(`SELECT id,bank_account_id AS "bankAccountId",cheque_number AS "chequeNumber",payee_contact_id AS "payeeContactId",issue_date::text AS "issueDate",amount_minor::float8 AS "amountMinor",status,payment_id AS "paymentId",cleared_at AS "clearedAt",voided_at AS "voidedAt",stopped_at AS "stoppedAt" FROM cheques WHERE organization_id=$1 ORDER BY issue_date DESC,created_at DESC`,[p.organizationId]);return c.json({data:rows.rows});});
 r.post("/cheques",requireScope("payments:write"),async c=>{const s=cheque.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid cheque",s.error.flatten());const p=c.get("principal"),bank=await runtime.db.query(`SELECT 1 FROM bank_accounts WHERE id=$1 AND organization_id=$2 AND active=true`,[s.data.bankAccountId,p.organizationId]);if(!bank.rowCount)throw new AppError(422,"INVALID_BANK_ACCOUNT","Active bank account required");if(s.data.payeeContactId){const contact=await runtime.db.query(`SELECT 1 FROM contacts WHERE id=$1 AND organization_id=$2 AND active=true`,[s.data.payeeContactId,p.organizationId]);if(!contact.rowCount)throw new AppError(422,"INVALID_CONTACT","Payee contact is invalid");}if(s.data.paymentId){const payment=await runtime.db.query(`SELECT 1 FROM payments WHERE id=$1 AND organization_id=$2`,[s.data.paymentId,p.organizationId]);if(!payment.rowCount)throw new AppError(422,"INVALID_PAYMENT","Payment is invalid");}const id=createId("chq");await runtime.db.query(`INSERT INTO cheques(id,organization_id,bank_account_id,cheque_number,payee_contact_id,issue_date,amount_minor,payment_id,created_by) VALUES($1,$2,$3,$4,$5,$6::date,$7,$8,$9)`,[id,p.organizationId,s.data.bankAccountId,s.data.chequeNumber,s.data.payeeContactId??null,s.data.issueDate,s.data.amountMinor,s.data.paymentId??null,p.userId]);return c.json({data:{id,status:"issued",...s.data}},201);});
 r.post("/cheques/:id/:action",requireScope("payments:write"),async c=>{const action=c.req.param("action");if(!["clear","void","stop"].includes(action))throw new AppError(404,"NOT_FOUND","Unknown cheque action");const p=c.get("principal"),status=action==="clear"?"cleared":action==="void"?"void":"stopped",result=await runtime.db.query(`UPDATE cheques SET status=$1,cleared_at=CASE WHEN $1='cleared' THEN CURRENT_TIMESTAMP ELSE cleared_at END,voided_at=CASE WHEN $1='void' THEN CURRENT_TIMESTAMP ELSE voided_at END,stopped_at=CASE WHEN $1='stopped' THEN CURRENT_TIMESTAMP ELSE stopped_at END,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status='issued' RETURNING id`,[status,c.req.param("id"),p.organizationId]);if(!result.rowCount)throw new AppError(409,"INVALID_STATE","Issued cheque not found");return c.json({data:{id:c.req.param("id"),status}});});

 r.get("/inventory/lots",requireScope("products:read"),async c=>{const p=c.get("principal"),rows=await runtime.db.query(`SELECT id,product_id AS "productId",location_id AS "locationId",lot_number AS "lotNumber",serial_number AS "serialNumber",expiry_date::text AS "expiryDate",quantity_micros::float8 AS "quantityMicros",unit_cost_minor::float8 AS "unitCostMinor",received_at::text AS "receivedAt",receipt_movement_id AS "movementId" FROM inventory_lots WHERE organization_id=$1 ORDER BY expiry_date NULLS LAST,lot_number`,[p.organizationId]);return c.json({data:rows.rows});});
 r.post("/inventory/lots",requireScope("products:write"),async c=>{const s=lot.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid inventory lot",s.error.flatten());const p=c.get("principal"),existing=(await runtime.db.query<any>(`SELECT id,receipt_movement_id AS "movementId",quantity_micros::float8 AS "quantityMicros",unit_cost_minor::float8 AS "unitCostMinor",received_at::text AS "receivedAt" FROM inventory_lots WHERE organization_id=$1 AND product_id=$2 AND location_id=$3 AND lot_number=$4 AND COALESCE(serial_number,'')=COALESCE($5,'')`,[p.organizationId,s.data.productId,s.data.locationId,s.data.lotNumber,s.data.serialNumber??null])).rows[0];if(existing){if(existing.quantityMicros!==s.data.quantityMicros||existing.unitCostMinor!==s.data.unitCostMinor||existing.receivedAt!==s.data.receivedAt)throw new AppError(409,"LOT_ALREADY_EXISTS","The lot or serial already exists with different receipt details");return c.json({data:{id:existing.id,movementId:existing.movementId,...s.data,replayed:true}});}const id=createId("lot"),movement=await recordMovement(runtime,p.organizationId,p.userId,{productId:s.data.productId,locationId:s.data.locationId,type:"receipt",movementDate:s.data.receivedAt,quantityDeltaMicros:s.data.quantityMicros,unitCostMinor:s.data.unitCostMinor,offsetAccountId:s.data.offsetAccountId,sourceType:"inventory_lot",sourceId:id},`lot:${p.organizationId}:${s.data.productId}:${s.data.locationId}:${s.data.lotNumber}:${s.data.serialNumber??""}`);await runtime.db.query(`INSERT INTO inventory_lots(id,organization_id,product_id,location_id,lot_number,serial_number,expiry_date,quantity_micros,unit_cost_minor,received_at,receipt_movement_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::date,$8,$9,$10::date,$11,$12)`,[id,p.organizationId,s.data.productId,s.data.locationId,s.data.lotNumber,s.data.serialNumber??null,s.data.expiryDate??null,s.data.quantityMicros,s.data.unitCostMinor,s.data.receivedAt,movement.id,p.userId]);return c.json({data:{id,movementId:movement.id,...s.data}},201);});
 r.post("/inventory/stock-counts/:id/approve",requireScope("products:write"),async c=>{const s=z.object({offsetAccountId:z.string()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Offset account required");const p=c.get("principal"),id=c.req.param("id"),account=await runtime.db.query(`SELECT 1 FROM accounts WHERE id=$1 AND organization_id=$2 AND active=true AND allow_posting=true`,[s.data.offsetAccountId,p.organizationId]);if(!account.rowCount)throw new AppError(422,"INVALID_ACCOUNT","Stock-count offset account is invalid");const current=await runtime.db.query(`UPDATE inventory_stock_counts SET offset_account_id=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status IN ('draft','in_progress') RETURNING id`,[s.data.offsetAccountId,id,p.organizationId]);if(!current.rowCount){const completed=(await runtime.db.query<{status:string}>(`SELECT status FROM inventory_stock_counts WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(completed?.status==="completed")return c.json({data:{id,status:"approved",replayed:true}});throw new AppError(409,"INVALID_STATE","Draft stock count required");}const result=await completeStockCount(runtime,p.organizationId,p.userId,id);return c.json({data:{...result,status:"approved"}});});
 return r;}
