-- Academics authoring and supervision mobile stream triggers. Requires 0033.
CREATE TRIGGER IF NOT EXISTS academics_ms_schemes_ai AFTER INSERT ON acad_schemes WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':schemes:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'schemes',NEW.id,'upsert',json_object('id',NEW.id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'teacherUserId',NEW.teacher_user_id,'title',NEW.title,'status',NEW.status,'versionNo',NEW.version_no,'coveragePercent',NEW.coverage_percent,'teacherReflection',NEW.teacher_reflection,'hodFeedback',NEW.hod_feedback,'dosFeedback',NEW.dos_feedback,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_schemes_au AFTER UPDATE ON acad_schemes WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':schemes:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'schemes',NEW.id,'upsert',json_object('id',NEW.id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'teacherUserId',NEW.teacher_user_id,'title',NEW.title,'status',NEW.status,'versionNo',NEW.version_no,'coveragePercent',NEW.coverage_percent,'teacherReflection',NEW.teacher_reflection,'hodFeedback',NEW.hod_feedback,'dosFeedback',NEW.dos_feedback,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_schemes_ad AFTER DELETE ON acad_schemes WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=OLD.organization_id||':schemes:'||OLD.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'schemes',OLD.id,'delete',NULL,OLD.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_scheme_items_ai AFTER INSERT ON acad_scheme_items WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':scheme-items:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'scheme-items',NEW.id,'upsert',json_object('id',NEW.id,'schemeId',NEW.scheme_id,'sequenceNo',NEW.sequence_no,'weekNo',NEW.week_no,'lessonNo',NEW.lesson_no,'topic',NEW.topic,'subtopic',NEW.subtopic,'learningObjectives',NEW.learning_objectives,'competencies',NEW.competencies,'teachingMethods',NEW.teaching_methods,'learningMaterials',NEW.learning_materials,'referencesText',NEW.references_text,'plannedActivities',NEW.planned_activities,'assessmentActivities',NEW.assessment_activities,'plannedDate',NEW.planned_date,'coverageStatus',NEW.coverage_status,'teacherReflection',NEW.teacher_reflection,'coveredAt',NEW.covered_at,'updatedAt',NEW.updated_at),NULL); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_scheme_items_au AFTER UPDATE ON acad_scheme_items WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':scheme-items:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'scheme-items',NEW.id,'upsert',json_object('id',NEW.id,'schemeId',NEW.scheme_id,'sequenceNo',NEW.sequence_no,'weekNo',NEW.week_no,'lessonNo',NEW.lesson_no,'topic',NEW.topic,'subtopic',NEW.subtopic,'learningObjectives',NEW.learning_objectives,'competencies',NEW.competencies,'teachingMethods',NEW.teaching_methods,'learningMaterials',NEW.learning_materials,'referencesText',NEW.references_text,'plannedActivities',NEW.planned_activities,'assessmentActivities',NEW.assessment_activities,'plannedDate',NEW.planned_date,'coverageStatus',NEW.coverage_status,'teacherReflection',NEW.teacher_reflection,'coveredAt',NEW.covered_at,'updatedAt',NEW.updated_at),NULL); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_scheme_items_ad AFTER DELETE ON acad_scheme_items WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=OLD.organization_id||':scheme-items:'||OLD.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'scheme-items',OLD.id,'delete',NULL,NULL); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_plan_templates_ai AFTER INSERT ON acad_lesson_plan_templates  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'templates',NEW.id,'upsert',json_object('id',NEW.id,'name',NEW.name,'description',NEW.description,'templateJson',NEW.template_json,'active',NEW.active,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_plan_templates_au AFTER UPDATE ON acad_lesson_plan_templates  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'templates',NEW.id,'upsert',json_object('id',NEW.id,'name',NEW.name,'description',NEW.description,'templateJson',NEW.template_json,'active',NEW.active,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_plan_templates_ad AFTER DELETE ON acad_lesson_plan_templates  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'templates',OLD.id,'delete',NULL,OLD.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_plans_ai AFTER INSERT ON acad_lesson_plans WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':lesson-plans:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'lesson-plans',NEW.id,'upsert',json_object('id',NEW.id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'teacherUserId',NEW.teacher_user_id,'timetableEntryId',NEW.timetable_entry_id,'schemeItemId',NEW.scheme_item_id,'templateId',NEW.template_id,'lessonDate',NEW.lesson_date,'weekNo',NEW.week_no,'lessonNo',NEW.lesson_no,'topic',NEW.topic,'subtopic',NEW.subtopic,'lessonObjectives',NEW.lesson_objectives,'priorKnowledge',NEW.prior_knowledge,'introductionText',NEW.introduction_text,'lessonDevelopment',NEW.lesson_development,'teacherActivities',NEW.teacher_activities,'learnerActivities',NEW.learner_activities,'teachingMethods',NEW.teaching_methods,'requiredMaterials',NEW.required_materials,'differentiatedInstruction',NEW.differentiated_instruction,'specialNeedsAccommodations',NEW.special_needs_accommodations,'lessonAssessment',NEW.lesson_assessment,'lessonConclusion',NEW.lesson_conclusion,'homework',NEW.homework,'teacherReflection',NEW.teacher_reflection,'hodFeedback',NEW.hod_feedback,'status',NEW.status,'approvedBy',NEW.approved_by,'approvedAt',NEW.approved_at,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_plans_au AFTER UPDATE ON acad_lesson_plans WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':lesson-plans:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'lesson-plans',NEW.id,'upsert',json_object('id',NEW.id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'teacherUserId',NEW.teacher_user_id,'timetableEntryId',NEW.timetable_entry_id,'schemeItemId',NEW.scheme_item_id,'templateId',NEW.template_id,'lessonDate',NEW.lesson_date,'weekNo',NEW.week_no,'lessonNo',NEW.lesson_no,'topic',NEW.topic,'subtopic',NEW.subtopic,'lessonObjectives',NEW.lesson_objectives,'priorKnowledge',NEW.prior_knowledge,'introductionText',NEW.introduction_text,'lessonDevelopment',NEW.lesson_development,'teacherActivities',NEW.teacher_activities,'learnerActivities',NEW.learner_activities,'teachingMethods',NEW.teaching_methods,'requiredMaterials',NEW.required_materials,'differentiatedInstruction',NEW.differentiated_instruction,'specialNeedsAccommodations',NEW.special_needs_accommodations,'lessonAssessment',NEW.lesson_assessment,'lessonConclusion',NEW.lesson_conclusion,'homework',NEW.homework,'teacherReflection',NEW.teacher_reflection,'hodFeedback',NEW.hod_feedback,'status',NEW.status,'approvedBy',NEW.approved_by,'approvedAt',NEW.approved_at,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_plans_ad AFTER DELETE ON acad_lesson_plans WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=OLD.organization_id||':lesson-plans:'||OLD.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'lesson-plans',OLD.id,'delete',NULL,OLD.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_deliveries_ai AFTER INSERT ON acad_lesson_deliveries WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':deliveries:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'deliveries',NEW.id,'upsert',json_object('id',NEW.id,'timetableEntryId',NEW.timetable_entry_id,'lessonPlanId',NEW.lesson_plan_id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'teacherUserId',NEW.teacher_user_id,'substituteTeacherUserId',NEW.substitute_teacher_user_id,'attendanceSessionId',NEW.canonical_attendance_session_id,'scheduledDate',NEW.scheduled_date,'scheduledStartsAt',NEW.scheduled_starts_at,'scheduledEndsAt',NEW.scheduled_ends_at,'actualStartsAt',NEW.actual_starts_at,'actualEndsAt',NEW.actual_ends_at,'deliveryStatus',NEW.delivery_status,'actualTopic',NEW.actual_topic,'actualSubtopic',NEW.actual_subtopic,'studentAttendanceSummary',NEW.student_attendance_summary,'lessonNotes',NEW.lesson_notes,'missedReason',NEW.missed_reason,'recoveryDate',NEW.recovery_date,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_deliveries_au AFTER UPDATE ON acad_lesson_deliveries WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=NEW.organization_id||':deliveries:'||NEW.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'deliveries',NEW.id,'upsert',json_object('id',NEW.id,'timetableEntryId',NEW.timetable_entry_id,'lessonPlanId',NEW.lesson_plan_id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'teacherUserId',NEW.teacher_user_id,'substituteTeacherUserId',NEW.substitute_teacher_user_id,'attendanceSessionId',NEW.canonical_attendance_session_id,'scheduledDate',NEW.scheduled_date,'scheduledStartsAt',NEW.scheduled_starts_at,'scheduledEndsAt',NEW.scheduled_ends_at,'actualStartsAt',NEW.actual_starts_at,'actualEndsAt',NEW.actual_ends_at,'deliveryStatus',NEW.delivery_status,'actualTopic',NEW.actual_topic,'actualSubtopic',NEW.actual_subtopic,'studentAttendanceSummary',NEW.student_attendance_summary,'lessonNotes',NEW.lesson_notes,'missedReason',NEW.missed_reason,'recoveryDate',NEW.recovery_date,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_lesson_deliveries_ad AFTER DELETE ON acad_lesson_deliveries WHEN NOT EXISTS(SELECT 1 FROM academics_mobile_sync_suppression WHERE record_key=OLD.organization_id||':deliveries:'||OLD.id) BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'deliveries',OLD.id,'delete',NULL,OLD.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_observations_ai AFTER INSERT ON acad_observations  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'supervision','observation:'||NEW.id,'upsert',json_object('entityType','observation','id',NEW.id,'observationType',NEW.observation_type,'scheduledFor',NEW.scheduled_for,'observedAt',NEW.observed_at,'teacherUserId',NEW.teacher_user_id,'observerUserId',NEW.observer_user_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'lessonPlanId',NEW.lesson_plan_id,'status',NEW.status,'rubricJson',NEW.rubric_json,'preparationScore',NEW.preparation_score,'teachingMethodsScore',NEW.teaching_methods_score,'classroomManagementScore',NEW.classroom_management_score,'learnerParticipationScore',NEW.learner_participation_score,'materialsUseScore',NEW.materials_use_score,'timeManagementScore',NEW.time_management_score,'strengths',NEW.strengths,'areasForImprovement',NEW.areas_for_improvement,'recommendations',NEW.recommendations,'teacherAcknowledgedAt',NEW.teacher_acknowledged_at,'teacherResponse',NEW.teacher_response,'followupDate',NEW.followup_date,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_observations_au AFTER UPDATE ON acad_observations  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'supervision','observation:'||NEW.id,'upsert',json_object('entityType','observation','id',NEW.id,'observationType',NEW.observation_type,'scheduledFor',NEW.scheduled_for,'observedAt',NEW.observed_at,'teacherUserId',NEW.teacher_user_id,'observerUserId',NEW.observer_user_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'lessonPlanId',NEW.lesson_plan_id,'status',NEW.status,'rubricJson',NEW.rubric_json,'preparationScore',NEW.preparation_score,'teachingMethodsScore',NEW.teaching_methods_score,'classroomManagementScore',NEW.classroom_management_score,'learnerParticipationScore',NEW.learner_participation_score,'materialsUseScore',NEW.materials_use_score,'timeManagementScore',NEW.time_management_score,'strengths',NEW.strengths,'areasForImprovement',NEW.areas_for_improvement,'recommendations',NEW.recommendations,'teacherAcknowledgedAt',NEW.teacher_acknowledged_at,'teacherResponse',NEW.teacher_response,'followupDate',NEW.followup_date,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_observations_ad AFTER DELETE ON acad_observations  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'supervision','observation:'||OLD.id,'delete',NULL,OLD.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_inspections_ai AFTER INSERT ON acad_inspections  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'supervision','inspection:'||NEW.id,'upsert',json_object('entityType','inspection','id',NEW.id,'inspectionType',NEW.inspection_type,'inspectedOn',NEW.inspected_on,'inspectorUserId',NEW.inspector_user_id,'teacherUserId',NEW.teacher_user_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'sampleSize',NEW.sample_size,'quantityOfWork',NEW.quantity_of_work,'qualityOfMarking',NEW.quality_of_marking,'correctionFeedbackChecks',NEW.correction_feedback_checks,'dateOfLastMarking',NEW.date_of_last_marking,'findings',NEW.findings,'recommendations',NEW.recommendations,'teacherResponse',NEW.teacher_response,'followupDate',NEW.followup_date,'status',NEW.status,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_inspections_au AFTER UPDATE ON acad_inspections  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(NEW.organization_id,'supervision','inspection:'||NEW.id,'upsert',json_object('entityType','inspection','id',NEW.id,'inspectionType',NEW.inspection_type,'inspectedOn',NEW.inspected_on,'inspectorUserId',NEW.inspector_user_id,'teacherUserId',NEW.teacher_user_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'subjectId',NEW.subject_id,'sampleSize',NEW.sample_size,'quantityOfWork',NEW.quantity_of_work,'qualityOfMarking',NEW.quality_of_marking,'correctionFeedbackChecks',NEW.correction_feedback_checks,'dateOfLastMarking',NEW.date_of_last_marking,'findings',NEW.findings,'recommendations',NEW.recommendations,'teacherResponse',NEW.teacher_response,'followupDate',NEW.followup_date,'status',NEW.status,'updatedAt',NEW.updated_at),NEW.created_by); END;
CREATE TRIGGER IF NOT EXISTS academics_ms_inspections_ad AFTER DELETE ON acad_inspections  BEGIN
 INSERT INTO academics_mobile_sync_emit(organization_id,collection_key,record_id,operation,payload_json,changed_by) VALUES(OLD.organization_id,'supervision','inspection:'||OLD.id,'delete',NULL,OLD.created_by); END;
