-- Ledgerly Finance Core offline mobile sync. Official accounting stays server-authoritative.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS ledgerly_mobile_document_intents(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id TEXT REFERENCES mobile_sync_devices(id) ON DELETE SET NULL,intent_type TEXT NOT NULL CHECK(intent_type IN ('invoice','bill')),payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','retry','applied','rejected')),server_document_id TEXT REFERENCES documents(id) ON DELETE SET NULL,error_code TEXT,error_message TEXT,attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts>=0),next_attempt_at TEXT,created_by TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,client_created_at TEXT NOT NULL,applied_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS ledgerly_mobile_document_intents_pending_idx ON ledgerly_mobile_document_intents(status,next_attempt_at,created_at);
CREATE INDEX IF NOT EXISTS ledgerly_mobile_document_intents_user_idx ON ledgerly_mobile_document_intents(organization_id,created_by,created_at DESC);
CREATE TABLE IF NOT EXISTS ledgerly_mobile_journal_intents(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id TEXT REFERENCES mobile_sync_devices(id) ON DELETE SET NULL,payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','retry','applied','rejected')),server_journal_id TEXT REFERENCES journal_entries(id) ON DELETE SET NULL,error_code TEXT,error_message TEXT,attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts>=0),next_attempt_at TEXT,created_by TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,client_created_at TEXT NOT NULL,applied_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS ledgerly_mobile_journal_intents_pending_idx ON ledgerly_mobile_journal_intents(status,next_attempt_at,created_at);
CREATE INDEX IF NOT EXISTS ledgerly_mobile_journal_intents_user_idx ON ledgerly_mobile_journal_intents(organization_id,created_by,created_at DESC);

-- Source-table triggers emit a normalized event. One trigger below owns versioning, tombstones and pull changes.
CREATE TABLE IF NOT EXISTS ledgerly_mobile_change_events(id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id TEXT NOT NULL,collection_key TEXT NOT NULL,record_id TEXT NOT NULL,operation TEXT NOT NULL CHECK(operation IN ('upsert','delete')),payload_json TEXT);
CREATE TRIGGER IF NOT EXISTS ledgerly_mobile_change_apply AFTER INSERT ON ledgerly_mobile_change_events BEGIN
 INSERT INTO mobile_sync_record_versions(organization_id,module_key,collection_key,record_id,version,deleted,server_updated_at,last_device_id) VALUES(NEW.organization_id,'ledgerly-core',NEW.collection_key,NEW.record_id,1,CASE WHEN NEW.operation='delete' THEN 1 ELSE 0 END,CURRENT_TIMESTAMP,NULL) ON CONFLICT(organization_id,module_key,collection_key,record_id) DO UPDATE SET version=mobile_sync_record_versions.version+1,deleted=excluded.deleted,server_updated_at=CURRENT_TIMESTAMP,last_device_id=NULL;
 DELETE FROM mobile_sync_tombstones WHERE NEW.operation='upsert' AND organization_id=NEW.organization_id AND module_key='ledgerly-core' AND collection_key=NEW.collection_key AND record_id=NEW.record_id;
 INSERT INTO mobile_sync_tombstones(organization_id,module_key,collection_key,record_id,version,deleted_at,device_id) SELECT NEW.organization_id,'ledgerly-core',NEW.collection_key,NEW.record_id,v.version,CURRENT_TIMESTAMP,NULL FROM mobile_sync_record_versions v WHERE NEW.operation='delete' AND v.organization_id=NEW.organization_id AND v.module_key='ledgerly-core' AND v.collection_key=NEW.collection_key AND v.record_id=NEW.record_id ON CONFLICT(organization_id,module_key,collection_key,record_id) DO UPDATE SET version=excluded.version,deleted_at=CURRENT_TIMESTAMP,device_id=NULL;
 INSERT INTO mobile_sync_changes(organization_id,module_key,collection_key,record_id,version,operation,payload_json,changed_by,device_id,changed_at) SELECT NEW.organization_id,'ledgerly-core',NEW.collection_key,NEW.record_id,v.version,NEW.operation,NEW.payload_json,NULL,NULL,CURRENT_TIMESTAMP FROM mobile_sync_record_versions v WHERE v.organization_id=NEW.organization_id AND v.module_key='ledgerly-core' AND v.collection_key=NEW.collection_key AND v.record_id=NEW.record_id;
 DELETE FROM ledgerly_mobile_change_events WHERE id=NEW.id;
END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_accounts_insert AFTER INSERT ON accounts BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'accounts',NEW.id,'upsert',json_object('id',NEW.id,'code',NEW.code,'name',NEW.name,'type',NEW.type,'subtype',NEW.subtype,'normalBalance',NEW.normal_balance,'currency',NEW.currency,'allowPosting',NEW.allow_posting,'active',NEW.active,'parentAccountId',NEW.parent_account_id,'accountGroupId',NEW.account_group_id,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_accounts_update AFTER UPDATE ON accounts BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'accounts',NEW.id,'upsert',json_object('id',NEW.id,'code',NEW.code,'name',NEW.name,'type',NEW.type,'subtype',NEW.subtype,'normalBalance',NEW.normal_balance,'currency',NEW.currency,'allowPosting',NEW.allow_posting,'active',NEW.active,'parentAccountId',NEW.parent_account_id,'accountGroupId',NEW.account_group_id,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_accounts_delete AFTER DELETE ON accounts BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'accounts',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_dimensions_insert AFTER INSERT ON dimensions BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'dimensions',NEW.id,'upsert',json_object('id',NEW.id,'type',NEW.type,'code',NEW.code,'name',NEW.name,'active',NEW.active,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_dimensions_update AFTER UPDATE ON dimensions BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'dimensions',NEW.id,'upsert',json_object('id',NEW.id,'type',NEW.type,'code',NEW.code,'name',NEW.name,'active',NEW.active,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_dimensions_delete AFTER DELETE ON dimensions BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'dimensions',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_products_insert AFTER INSERT ON products BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'products',NEW.id,'upsert',json_object('id',NEW.id,'sku',NEW.sku,'name',NEW.name,'type',NEW.type,'incomeAccountId',NEW.income_account_id,'expenseAccountId',NEW.expense_account_id,'inventoryAccountId',NEW.inventory_account_id,'quantityOnHandMicros',NEW.quantity_on_hand_micros,'averageCostMinor',NEW.average_cost_minor,'reorderPointMicros',NEW.reorder_point_micros,'active',NEW.active,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_products_update AFTER UPDATE ON products BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'products',NEW.id,'upsert',json_object('id',NEW.id,'sku',NEW.sku,'name',NEW.name,'type',NEW.type,'incomeAccountId',NEW.income_account_id,'expenseAccountId',NEW.expense_account_id,'inventoryAccountId',NEW.inventory_account_id,'quantityOnHandMicros',NEW.quantity_on_hand_micros,'averageCostMinor',NEW.average_cost_minor,'reorderPointMicros',NEW.reorder_point_micros,'active',NEW.active,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_products_delete AFTER DELETE ON products BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'products',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_projects_insert AFTER INSERT ON projects BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'projects',NEW.id,'upsert',json_object('id',NEW.id,'customerId',NEW.customer_id,'code',NEW.code,'name',NEW.name,'status',NEW.status,'budgetAmountMinor',NEW.budget_amount_minor,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_projects_update AFTER UPDATE ON projects BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'projects',NEW.id,'upsert',json_object('id',NEW.id,'customerId',NEW.customer_id,'code',NEW.code,'name',NEW.name,'status',NEW.status,'budgetAmountMinor',NEW.budget_amount_minor,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_projects_delete AFTER DELETE ON projects BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'projects',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_fiscal_periods_insert AFTER INSERT ON fiscal_periods BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'fiscal-periods',NEW.id,'upsert',json_object('id',NEW.id,'name',NEW.name,'startsOn',NEW.starts_on,'endsOn',NEW.ends_on,'status',NEW.status,'lockedAt',NEW.locked_at,'lockedBy',NEW.locked_by,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_fiscal_periods_update AFTER UPDATE ON fiscal_periods BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'fiscal-periods',NEW.id,'upsert',json_object('id',NEW.id,'name',NEW.name,'startsOn',NEW.starts_on,'endsOn',NEW.ends_on,'status',NEW.status,'lockedAt',NEW.locked_at,'lockedBy',NEW.locked_by,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_fiscal_periods_delete AFTER DELETE ON fiscal_periods BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'fiscal-periods',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_bank_accounts_insert AFTER INSERT ON bank_accounts BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'bank-accounts',NEW.id,'upsert',json_object('id',NEW.id,'ledgerAccountId',NEW.ledger_account_id,'name',NEW.name,'bankName',NEW.bank_name,'accountNumberMasked',NEW.account_number_masked,'currency',NEW.currency,'openingBalanceMinor',NEW.opening_balance_minor,'active',NEW.active,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_bank_accounts_update AFTER UPDATE ON bank_accounts BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'bank-accounts',NEW.id,'upsert',json_object('id',NEW.id,'ledgerAccountId',NEW.ledger_account_id,'name',NEW.name,'bankName',NEW.bank_name,'accountNumberMasked',NEW.account_number_masked,'currency',NEW.currency,'openingBalanceMinor',NEW.opening_balance_minor,'active',NEW.active,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_bank_accounts_delete AFTER DELETE ON bank_accounts BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'bank-accounts',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_documents_insert AFTER INSERT ON documents BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'documents',NEW.id,'upsert',json_object('id',NEW.id,'type',NEW.type,'number',NEW.number,'contactId',NEW.contact_id,'issueDate',NEW.issue_date,'dueDate',NEW.due_date,'status',NEW.status,'currency',NEW.currency,'subtotalMinor',NEW.subtotal_minor,'taxMinor',NEW.tax_minor,'totalMinor',NEW.total_minor,'paidMinor',NEW.paid_minor,'journalEntryId',NEW.journal_entry_id,'approvalStatus',NEW.approval_status,'customFields',NEW.custom_fields,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_documents_update AFTER UPDATE ON documents BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'documents',NEW.id,'upsert',json_object('id',NEW.id,'type',NEW.type,'number',NEW.number,'contactId',NEW.contact_id,'issueDate',NEW.issue_date,'dueDate',NEW.due_date,'status',NEW.status,'currency',NEW.currency,'subtotalMinor',NEW.subtotal_minor,'taxMinor',NEW.tax_minor,'totalMinor',NEW.total_minor,'paidMinor',NEW.paid_minor,'journalEntryId',NEW.journal_entry_id,'approvalStatus',NEW.approval_status,'customFields',NEW.custom_fields,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_documents_delete AFTER DELETE ON documents BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'documents',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_document_lines_insert AFTER INSERT ON document_lines BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'document-lines',NEW.id,'upsert',json_object('id',NEW.id,'documentId',NEW.document_id,'productId',NEW.product_id,'accountId',NEW.account_id,'taxAccountId',NEW.tax_account_id,'description',NEW.description,'quantityMicros',NEW.quantity_micros,'unitPriceMinor',NEW.unit_price_minor,'subtotalMinor',NEW.subtotal_minor,'taxMinor',NEW.tax_minor,'totalMinor',NEW.total_minor,'projectId',NEW.project_id,'classId',NEW.class_id,'departmentId',NEW.department_id,'locationId',NEW.location_id,'dimensionsJson',NEW.dimensions_json,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_document_lines_update AFTER UPDATE ON document_lines BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'document-lines',NEW.id,'upsert',json_object('id',NEW.id,'documentId',NEW.document_id,'productId',NEW.product_id,'accountId',NEW.account_id,'taxAccountId',NEW.tax_account_id,'description',NEW.description,'quantityMicros',NEW.quantity_micros,'unitPriceMinor',NEW.unit_price_minor,'subtotalMinor',NEW.subtotal_minor,'taxMinor',NEW.tax_minor,'totalMinor',NEW.total_minor,'projectId',NEW.project_id,'classId',NEW.class_id,'departmentId',NEW.department_id,'locationId',NEW.location_id,'dimensionsJson',NEW.dimensions_json,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_document_lines_delete AFTER DELETE ON document_lines BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'document-lines',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_journal_entries_insert AFTER INSERT ON journal_entries BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'journals',NEW.id,'upsert',json_object('id',NEW.id,'entryNumber',NEW.entry_number,'transactionDate',NEW.transaction_date,'postingDate',NEW.posting_date,'description',NEW.description,'reference',NEW.reference,'sourceType',NEW.source_type,'sourceId',NEW.source_id,'status',NEW.status,'currency',NEW.currency,'exchangeRateMicros',NEW.exchange_rate_micros,'reversalOfId',NEW.reversal_of_id,'postedAt',NEW.posted_at,'postedBy',NEW.posted_by,'metadata',NEW.metadata,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_journal_entries_update AFTER UPDATE ON journal_entries BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'journals',NEW.id,'upsert',json_object('id',NEW.id,'entryNumber',NEW.entry_number,'transactionDate',NEW.transaction_date,'postingDate',NEW.posting_date,'description',NEW.description,'reference',NEW.reference,'sourceType',NEW.source_type,'sourceId',NEW.source_id,'status',NEW.status,'currency',NEW.currency,'exchangeRateMicros',NEW.exchange_rate_micros,'reversalOfId',NEW.reversal_of_id,'postedAt',NEW.posted_at,'postedBy',NEW.posted_by,'metadata',NEW.metadata,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_journal_entries_delete AFTER DELETE ON journal_entries BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'journals',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_journal_lines_insert AFTER INSERT ON journal_lines BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'journal-lines',NEW.id,'upsert',json_object('id',NEW.id,'journalEntryId',NEW.journal_entry_id,'accountId',NEW.account_id,'description',NEW.description,'debitMinor',NEW.debit_minor,'creditMinor',NEW.credit_minor,'baseDebitMinor',NEW.base_debit_minor,'baseCreditMinor',NEW.base_credit_minor,'contactId',NEW.contact_id,'projectId',NEW.project_id,'classId',NEW.class_id,'departmentId',NEW.department_id,'locationId',NEW.location_id,'taxCode',NEW.tax_code,'dimensionsJson',NEW.dimensions_json,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_journal_lines_update AFTER UPDATE ON journal_lines BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'journal-lines',NEW.id,'upsert',json_object('id',NEW.id,'journalEntryId',NEW.journal_entry_id,'accountId',NEW.account_id,'description',NEW.description,'debitMinor',NEW.debit_minor,'creditMinor',NEW.credit_minor,'baseDebitMinor',NEW.base_debit_minor,'baseCreditMinor',NEW.base_credit_minor,'contactId',NEW.contact_id,'projectId',NEW.project_id,'classId',NEW.class_id,'departmentId',NEW.department_id,'locationId',NEW.location_id,'taxCode',NEW.tax_code,'dimensionsJson',NEW.dimensions_json,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS ledgerly_sync_journal_lines_delete AFTER DELETE ON journal_lines BEGIN INSERT INTO ledgerly_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'journal-lines',OLD.id,'delete',NULL); END;
