-- Offline Books operations are immutable intents; official stock/distribution rows stay server-authoritative.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS bks_mobile_operation_intents(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id TEXT REFERENCES mobile_sync_devices(id) ON DELETE SET NULL,operation_type TEXT NOT NULL CHECK(operation_type IN ('stock_movement','individual_issue','bulk_issue')),payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','retry','applied','rejected')),server_entity_type TEXT,server_entity_id TEXT,result_json TEXT,error_code TEXT,error_message TEXT,attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts>=0),next_attempt_at TEXT,created_by TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,client_created_at TEXT NOT NULL,applied_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS bks_mobile_intents_pending_idx ON bks_mobile_operation_intents(status,next_attempt_at,created_at);
CREATE INDEX IF NOT EXISTS bks_mobile_intents_user_idx ON bks_mobile_operation_intents(organization_id,created_by,created_at DESC);
CREATE TABLE IF NOT EXISTS bks_mobile_change_events(id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id TEXT NOT NULL,collection_key TEXT NOT NULL,record_id TEXT NOT NULL,operation TEXT NOT NULL CHECK(operation IN ('upsert','delete')),payload_json TEXT);
CREATE TRIGGER IF NOT EXISTS bks_mobile_change_apply AFTER INSERT ON bks_mobile_change_events BEGIN
 INSERT INTO mobile_sync_record_versions(organization_id,module_key,collection_key,record_id,version,deleted,server_updated_at,last_device_id) VALUES(NEW.organization_id,'books',NEW.collection_key,NEW.record_id,1,CASE WHEN NEW.operation='delete' THEN 1 ELSE 0 END,CURRENT_TIMESTAMP,NULL) ON CONFLICT(organization_id,module_key,collection_key,record_id) DO UPDATE SET version=mobile_sync_record_versions.version+1,deleted=excluded.deleted,server_updated_at=CURRENT_TIMESTAMP,last_device_id=NULL;
 DELETE FROM mobile_sync_tombstones WHERE NEW.operation='upsert' AND organization_id=NEW.organization_id AND module_key='books' AND collection_key=NEW.collection_key AND record_id=NEW.record_id;
 INSERT INTO mobile_sync_tombstones(organization_id,module_key,collection_key,record_id,version,deleted_at,device_id) SELECT NEW.organization_id,'books',NEW.collection_key,NEW.record_id,v.version,CURRENT_TIMESTAMP,NULL FROM mobile_sync_record_versions v WHERE NEW.operation='delete' AND v.organization_id=NEW.organization_id AND v.module_key='books' AND v.collection_key=NEW.collection_key AND v.record_id=NEW.record_id ON CONFLICT(organization_id,module_key,collection_key,record_id) DO UPDATE SET version=excluded.version,deleted_at=CURRENT_TIMESTAMP,device_id=NULL;
 INSERT INTO mobile_sync_changes(organization_id,module_key,collection_key,record_id,version,operation,payload_json,changed_by,device_id,changed_at) SELECT NEW.organization_id,'books',NEW.collection_key,NEW.record_id,v.version,NEW.operation,NEW.payload_json,NULL,NULL,CURRENT_TIMESTAMP FROM mobile_sync_record_versions v WHERE v.organization_id=NEW.organization_id AND v.module_key='books' AND v.collection_key=NEW.collection_key AND v.record_id=NEW.record_id;
 DELETE FROM bks_mobile_change_events WHERE id=NEW.id;
END;
CREATE TRIGGER IF NOT EXISTS bks_sync_stock_insert AFTER INSERT ON bks_stock_movements BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'stock-movements',NEW.id,'upsert',json_object('id',NEW.id,'bookType',NEW.book_type,'movementType',NEW.movement_type,'quantityDelta',NEW.quantity_delta,'movementOn',NEW.movement_on,'referenceText',NEW.reference_text,'notes',NEW.notes,'recordedBy',NEW.recorded_by,'reversedAt',NEW.reversed_at,'reversedBy',NEW.reversed_by,'reversalReason',NEW.reversal_reason,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_stock_update AFTER UPDATE ON bks_stock_movements BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'stock-movements',NEW.id,'upsert',json_object('id',NEW.id,'bookType',NEW.book_type,'movementType',NEW.movement_type,'quantityDelta',NEW.quantity_delta,'movementOn',NEW.movement_on,'referenceText',NEW.reference_text,'notes',NEW.notes,'recordedBy',NEW.recorded_by,'reversedAt',NEW.reversed_at,'reversedBy',NEW.reversed_by,'reversalReason',NEW.reversal_reason,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_stock_delete AFTER DELETE ON bks_stock_movements BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'stock-movements',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_distribution_insert AFTER INSERT ON bks_distributions BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'distributions',NEW.id,'upsert',json_object('id',NEW.id,'studentId',NEW.student_id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'batchId',NEW.batch_id,'bookType',NEW.book_type,'quantity',NEW.quantity,'distributedOn',NEW.distributed_on,'source',NEW.source,'notes',NEW.notes,'distributedBy',NEW.distributed_by,'reversedAt',NEW.reversed_at,'reversedBy',NEW.reversed_by,'reversalReason',NEW.reversal_reason,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_distribution_update AFTER UPDATE ON bks_distributions BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'distributions',NEW.id,'upsert',json_object('id',NEW.id,'studentId',NEW.student_id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'batchId',NEW.batch_id,'bookType',NEW.book_type,'quantity',NEW.quantity,'distributedOn',NEW.distributed_on,'source',NEW.source,'notes',NEW.notes,'distributedBy',NEW.distributed_by,'reversedAt',NEW.reversed_at,'reversedBy',NEW.reversed_by,'reversalReason',NEW.reversal_reason,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_distribution_delete AFTER DELETE ON bks_distributions BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'distributions',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_batch_insert AFTER INSERT ON bks_distribution_batches BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'distribution-batches',NEW.id,'upsert',json_object('id',NEW.id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'bookType',NEW.book_type,'quantityPerLearner',NEW.quantity_per_learner,'learnerCount',NEW.learner_count,'totalQuantity',NEW.total_quantity,'distributedOn',NEW.distributed_on,'notes',NEW.notes,'createdBy',NEW.created_by,'reversedAt',NEW.reversed_at,'reversedBy',NEW.reversed_by,'reversalReason',NEW.reversal_reason,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_batch_update AFTER UPDATE ON bks_distribution_batches BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(NEW.organization_id,'distribution-batches',NEW.id,'upsert',json_object('id',NEW.id,'academicYearId',NEW.academic_year_id,'termId',NEW.term_id,'classId',NEW.class_id,'streamId',NEW.stream_id,'bookType',NEW.book_type,'quantityPerLearner',NEW.quantity_per_learner,'learnerCount',NEW.learner_count,'totalQuantity',NEW.total_quantity,'distributedOn',NEW.distributed_on,'notes',NEW.notes,'createdBy',NEW.created_by,'reversedAt',NEW.reversed_at,'reversedBy',NEW.reversed_by,'reversalReason',NEW.reversal_reason,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS bks_sync_batch_delete AFTER DELETE ON bks_distribution_batches BEGIN INSERT INTO bks_mobile_change_events(organization_id,collection_key,record_id,operation,payload_json) VALUES(OLD.organization_id,'distribution-batches',OLD.id,'delete',NULL); END;
