PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS contacts_mobile_sync_suppression(record_key TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS contacts_mobile_change_events(id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id TEXT NOT NULL,collection_key TEXT NOT NULL,record_id TEXT NOT NULL,operation TEXT NOT NULL CHECK(operation IN('upsert','delete')),payload_json TEXT);
CREATE TRIGGER IF NOT EXISTS contacts_mobile_change_apply AFTER INSERT ON contacts_mobile_change_events BEGIN
 INSERT INTO mobile_sync_record_versions(organization_id,module_key,collection_key,record_id,version,deleted,server_updated_at,last_device_id) VALUES(NEW.organization_id,'contacts',NEW.collection_key,NEW.record_id,1,CASE WHEN NEW.operation='delete' THEN 1 ELSE 0 END,CURRENT_TIMESTAMP,NULL) ON CONFLICT(organization_id,module_key,collection_key,record_id) DO UPDATE SET version=mobile_sync_record_versions.version+1,deleted=excluded.deleted,server_updated_at=CURRENT_TIMESTAMP,last_device_id=NULL;
 DELETE FROM mobile_sync_tombstones WHERE NEW.operation='upsert' AND organization_id=NEW.organization_id AND module_key='contacts' AND collection_key=NEW.collection_key AND record_id=NEW.record_id;
 INSERT INTO mobile_sync_tombstones(organization_id,module_key,collection_key,record_id,version,deleted_at,device_id) SELECT NEW.organization_id,'contacts',NEW.collection_key,NEW.record_id,v.version,CURRENT_TIMESTAMP,NULL FROM mobile_sync_record_versions v WHERE NEW.operation='delete' AND v.organization_id=NEW.organization_id AND v.module_key='contacts' AND v.collection_key=NEW.collection_key AND v.record_id=NEW.record_id ON CONFLICT(organization_id,module_key,collection_key,record_id) DO UPDATE SET version=excluded.version,deleted_at=CURRENT_TIMESTAMP,device_id=NULL;
 INSERT INTO mobile_sync_changes(organization_id,module_key,collection_key,record_id,version,operation,payload_json,changed_by,device_id,changed_at) SELECT NEW.organization_id,'contacts',NEW.collection_key,NEW.record_id,v.version,NEW.operation,NEW.payload_json,NULL,NULL,CURRENT_TIMESTAMP FROM mobile_sync_record_versions v WHERE v.organization_id=NEW.organization_id AND v.module_key='contacts' AND v.collection_key=NEW.collection_key AND v.record_id=NEW.record_id;
 DELETE FROM contacts_mobile_change_events WHERE id=NEW.id;
END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_contact_i AFTER INSERT ON contacts WHEN NOT EXISTS(SELECT 1 FROM contacts_mobile_sync_suppression WHERE record_key=NEW.organization_id||':contacts:'||NEW.id) BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,NEW.organization_id,'contacts',NEW.id,CASE WHEN NEW.archived_at IS NULL THEN 'upsert' ELSE 'delete' END,CASE WHEN NEW.archived_at IS NULL THEN json_object('id',NEW.id,'type',NEW.type,'code',NEW.code,'name',NEW.name,'email',NEW.email,'taxNumber',NEW.tax_number,'paymentTermsDays',NEW.payment_terms_days,'creditLimitMinor',NEW.credit_limit_minor,'pricingTier',NEW.pricing_tier,'active',NEW.active,'customFields',json(NEW.custom_fields)) ELSE NULL END); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_contact_u AFTER UPDATE ON contacts WHEN NOT EXISTS(SELECT 1 FROM contacts_mobile_sync_suppression WHERE record_key=NEW.organization_id||':contacts:'||NEW.id) BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,NEW.organization_id,'contacts',NEW.id,CASE WHEN NEW.archived_at IS NULL THEN 'upsert' ELSE 'delete' END,CASE WHEN NEW.archived_at IS NULL THEN json_object('id',NEW.id,'type',NEW.type,'code',NEW.code,'name',NEW.name,'email',NEW.email,'taxNumber',NEW.tax_number,'paymentTermsDays',NEW.payment_terms_days,'creditLimitMinor',NEW.credit_limit_minor,'pricingTier',NEW.pricing_tier,'active',NEW.active,'customFields',json(NEW.custom_fields)) ELSE NULL END); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_contact_d AFTER DELETE ON contacts BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,OLD.organization_id,'contacts',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_person_i AFTER INSERT ON contact_people WHEN NOT EXISTS(SELECT 1 FROM contacts_mobile_sync_suppression WHERE record_key=NEW.organization_id||':contact-people:'||NEW.id) BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,NEW.organization_id,'contact-people',NEW.id,'upsert',json_object('id',NEW.id,'contactId',NEW.contact_id,'name',NEW.name,'email',NEW.email,'phone',NEW.phone,'role',NEW.role,'isPrimary',NEW.is_primary,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_person_u AFTER UPDATE ON contact_people WHEN NOT EXISTS(SELECT 1 FROM contacts_mobile_sync_suppression WHERE record_key=NEW.organization_id||':contact-people:'||NEW.id) BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,NEW.organization_id,'contact-people',NEW.id,'upsert',json_object('id',NEW.id,'contactId',NEW.contact_id,'name',NEW.name,'email',NEW.email,'phone',NEW.phone,'role',NEW.role,'isPrimary',NEW.is_primary,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_person_d AFTER DELETE ON contact_people BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,OLD.organization_id,'contact-people',OLD.id,'delete',NULL); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_address_i AFTER INSERT ON contact_addresses WHEN NOT EXISTS(SELECT 1 FROM contacts_mobile_sync_suppression WHERE record_key=NEW.organization_id||':contact-addresses:'||NEW.id) BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,NEW.organization_id,'contact-addresses',NEW.id,'upsert',json_object('id',NEW.id,'contactId',NEW.contact_id,'type',NEW.type,'line1',NEW.line1,'line2',NEW.line2,'city',NEW.city,'state',NEW.state,'postalCode',NEW.postal_code,'country',NEW.country,'isDefault',NEW.is_default,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_address_u AFTER UPDATE ON contact_addresses WHEN NOT EXISTS(SELECT 1 FROM contacts_mobile_sync_suppression WHERE record_key=NEW.organization_id||':contact-addresses:'||NEW.id) BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,NEW.organization_id,'contact-addresses',NEW.id,'upsert',json_object('id',NEW.id,'contactId',NEW.contact_id,'type',NEW.type,'line1',NEW.line1,'line2',NEW.line2,'city',NEW.city,'state',NEW.state,'postalCode',NEW.postal_code,'country',NEW.country,'isDefault',NEW.is_default,'createdAt',NEW.created_at,'updatedAt',NEW.updated_at)); END;
CREATE TRIGGER IF NOT EXISTS contacts_sync_address_d AFTER DELETE ON contact_addresses BEGIN INSERT INTO contacts_mobile_change_events VALUES(NULL,OLD.organization_id,'contact-addresses',OLD.id,'delete',NULL); END;
