import {useState} from "react";
import {SafeAreaView,StatusBar,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {OverviewTab} from "./OverviewTab";
import {ComposeTab} from "./ComposeTab";
import {CampaignsTab} from "./CampaignsTab";
import {DeliveriesTab} from "./DeliveriesTab";
import {SetupTab} from "./SetupTab";
type Tab="overview"|"compose"|"campaigns"|"deliveries"|"setup";
export function CommunicationsWorkspaceScreen({session,onSession,onBack}:{session:MobileSession;onSession:SessionUpdater;onBack:()=>void}){const[tab,setTab]=useState<Tab>("overview");const tabs:[Tab,string,string][]=[["overview","Overview","⌂"],["compose","Compose","+"],["campaigns","Campaigns","C"],["deliveries","Delivery","D"],["setup","Setup","⚙"]];const content=tab==="overview"?<OverviewTab session={session} onSession={onSession}/>:tab==="compose"?<ComposeTab session={session} onSession={onSession}/>:tab==="campaigns"?<CampaignsTab session={session} onSession={onSession}/>:tab==="deliveries"?<DeliveriesTab session={session} onSession={onSession}/>:<SetupTab session={session} onSession={onSession}/>;return <SafeAreaView style={s.root}><StatusBar barStyle="light-content" backgroundColor="#382951"/><View style={s.head}><TouchableOpacity style={s.back} onPress={onBack}><Text style={s.backText}>←</Text></TouchableOpacity><View><Text style={s.eyebrow}>LEDGERLY MOBILE · MODULE 09</Text><Text style={s.title}>Messages & Notifications</Text></View><View style={s.badge}><Text style={s.badgeText}>COMMS</Text></View></View><View style={s.body}>{content}</View><View style={s.nav}>{tabs.map(([id,label,icon])=><TouchableOpacity key={id} onPress={()=>setTab(id)} style={s.navItem}><View style={[s.navIcon,tab===id&&s.navIconOn]}><Text style={[s.navGlyph,tab===id&&s.navGlyphOn]}>{icon}</Text></View><Text style={[s.navText,tab===id&&s.navTextOn]}>{label}</Text></TouchableOpacity>)}</View></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f5f3f7"},head:{height:74,backgroundColor:"#382951",flexDirection:"row",alignItems:"center",paddingHorizontal:14},back:{width:38,height:38,borderRadius:13,backgroundColor:"#52406e",alignItems:"center",justifyContent:"center",marginRight:12},backText:{fontSize:21,color:"white"},eyebrow:{fontSize:7,fontWeight:"900",letterSpacing:1.1,color:"#c9a9f5"},title:{fontSize:18,fontWeight:"900",color:"white",marginTop:2},badge:{marginLeft:"auto",borderRadius:14,backgroundColor:"#eee7f7",paddingHorizontal:10,paddingVertical:7},badgeText:{fontSize:8,fontWeight:"900",color:"#6a518c"},body:{flex:1},nav:{height:72,backgroundColor:"white",borderTopWidth:1,borderTopColor:"#e5e0ea",flexDirection:"row",paddingHorizontal:5,paddingTop:7},navItem:{flex:1,alignItems:"center"},navIcon:{width:31,height:28,borderRadius:10,alignItems:"center",justifyContent:"center"},navIconOn:{backgroundColor:"#eee8f5"},navGlyph:{fontSize:12,fontWeight:"900",color:"#97919e"},navGlyphOn:{color:"#705595"},navText:{fontSize:7.5,fontWeight:"900",color:"#97919e",marginTop:3},navTextOn:{color:"#705595"}});
