import {MobileApiError} from "../auth";
import type {CommunicationContext,MessageType} from "./types";
export function err(e:unknown){return e instanceof MobileApiError?e.message:e instanceof Error?e.message:"Something went wrong."}
export function today(){const d=new Date(),p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
export function localScheduleIso(value:string){const raw=value.trim();if(!raw||/[zZ]$|[+-]\d{2}:\d{2}$/.test(raw))return raw;const m=raw.match(/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})(?::\d{2})?$/);if(!m)return raw;const local=new Date(`${m[1]}:00`),offset=-local.getTimezoneOffset(),sign=offset>=0?"+":"-",abs=Math.abs(offset),p=(n:number)=>String(n).padStart(2,"0");return `${m[1]}:00${sign}${p(Math.floor(abs/60))}:${p(abs%60)}`}
export function tone(status:string){const v=String(status).toLowerCase();if(["sent","delivered","completed","approved","configured","active"].includes(v))return "good" as const;if(["scheduled","queued","draft","sending","partial"].includes(v))return "warn" as const;if(["failed","cancelled","suppressed","inactive","not configured"].includes(v))return "bad" as const;return "neutral" as const}
export const opts=(rows:any[],label=(x:any)=>x.name||x.title||x.code||x.id)=>rows.map(x=>({label:String(label(x)),value:String(x.id),detail:[x.code,x.status,x.taskNumber].filter(Boolean).join(" · ")}));
export const years=(c:CommunicationContext)=>opts(c.years||[],x=>x.name||x.code),terms=(c:CommunicationContext,yearId:string)=>opts((c.terms||[]).filter(x=>!yearId||x.academicYearId===yearId)),classes=(c:CommunicationContext,yearId:string)=>opts((c.classes||[]).filter(x=>!yearId||x.academicYearId===yearId)),streams=(c:CommunicationContext,classId:string)=>opts((c.streams||[]).filter(x=>!classId||x.classId===classId));
export function messageTypeOptions(rows:MessageType[]){return rows.filter(x=>x.active!==false).map(x=>({label:x.name,value:x.typeKey,detail:[x.moduleKey,x.category,x.audienceKind].filter(Boolean).join(" · ")}))}
export function recipientModeOptions(){return [{label:"All guardians",value:"all_guardians"},{label:"Primary guardian",value:"primary_guardian"},{label:"Student direct",value:"student_direct"},{label:"Guardians + student",value:"guardians_and_student"}]}
