import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { decryptMfaSecret, hashRecoveryCode, verifyTotp } from "./mfa.js";
import { createId, hashPassword, issueTokens, passwordNeedsRehash, randomToken, requestIp, requireScope, sha256, verifyPassword } from "./security.js";

const registerSchema = z.object({ organizationName:z.string().min(2).max(160), baseCurrency:z.string().length(3).transform(v=>v.toUpperCase()).default("UGX"), name:z.string().min(2).max(160), email:z.string().email(), password:z.string().min(12).max(200) });
const loginSchema = z.object({ identifier:z.string().min(1).max(320).optional(), email:z.string().email().optional(), password:z.string(), organizationId:z.string().optional(), mfaCode:z.string().min(6).max(40).optional() }).refine(v=>Boolean(v.identifier||v.email),{message:"Email, username or phone is required"});
const settingsSchema = z.object({ name:z.string().min(2).max(160), legalName:z.string().max(160).nullable().optional(), baseCurrency:z.string().length(3).transform(v=>v.toUpperCase()), timezone:z.string().min(1).max(100), fiscalYearStartMonth:z.number().int().min(1).max(12), address:z.record(z.string(),z.unknown()).default({}), taxRegistrationNumber:z.string().max(100).nullable().optional(), documentNumbering:z.record(z.string(),z.unknown()).default({}), branding:z.object({logoDataUrl:z.string().max(400000).optional(),email:z.string().max(160).optional(),phone:z.string().max(60).optional(),website:z.string().max(200).optional(),footer:z.string().max(500).optional(),primaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/).optional()}).default({}) });
const memberSchema = z.object({ email:z.string().email(), displayName:z.string().min(2).max(160), role:z.enum(["admin","accountant","manager","viewer","integration"]), scopes:z.array(z.string().max(80)).max(100).default([]) });
const keySchema = z.object({ name:z.string().min(1).max(120), scopes:z.array(z.string().max(80)).min(1).max(100), expiresAt:z.string().datetime().optional() });

async function audit(runtime:Runtime, organizationId:string, actorId:string, action:string, entityType:string, entityId:string, after?:unknown, requestId?:string) {
  await runtime.db.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,request_id,after_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[createId("aud"),organizationId,actorId,action,entityType,entityId,requestId??null,after===undefined?null:JSON.stringify(after)]);
}
async function outbox(runtime:Runtime, topic:string, aggregateType:string, aggregateId:string, payload:unknown, client=runtime.db) {
  await client.query(`INSERT INTO backend_outbox_events(id,topic,aggregate_type,aggregate_id,payload) VALUES($1,$2,$3,$4,$5::jsonb)`,[createId("evt"),topic,aggregateType,aggregateId,JSON.stringify(payload)]);
}
async function loginEvent(runtime:Runtime,data:{organizationId?:string;userId?:string;identifier:string;eventType:"success"|"failure";ip?:string;userAgent?:string;reason?:string}) {
  try { await runtime.db.query(`INSERT INTO identity_login_events(id,organization_id,user_id,identifier,event_type,ip_address,user_agent,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[createId("ile"),data.organizationId??null,data.userId??null,data.identifier,data.eventType,data.ip??null,data.userAgent??null,data.reason??null]); } catch { /* login must not fail because event logging failed */ }
}

export function createAuthRoutes(runtime:Runtime) {
  const router=new Hono<AppEnv>();
  router.post("/register",async c=>{
    const parsed=registerSchema.safeParse(await c.req.json().catch(()=>null)); if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid registration",parsed.error.flatten());
    const email=parsed.data.email.toLowerCase(); if((await runtime.db.query("SELECT 1 FROM users WHERE lower(email)=lower($1)",[email])).rowCount)throw new AppError(409,"EMAIL_EXISTS","Email is already registered");
    const organizationId=createId("org"),userId=createId("usr"),passwordHash=await hashPassword(parsed.data.password),client=await runtime.db.connect();
    try { await client.query("BEGIN");
      await client.query("INSERT INTO organizations(id,name,base_currency) VALUES($1,$2,$3)",[organizationId,parsed.data.organizationName,parsed.data.baseCurrency]);
      await client.query("INSERT INTO users(id,email,display_name,password_hash,email_verified_at) VALUES($1,$2,$3,$4,CURRENT_TIMESTAMP)",[userId,email,parsed.data.name,passwordHash]);
      await client.query("INSERT INTO memberships(organization_id,user_id,role,scopes) VALUES($1,$2,'owner','[]'::jsonb)",[organizationId,userId]);
      await outbox(runtime,"organization.created","organization",organizationId,{organizationId,userId,source:"registration"},client); await client.query("COMMIT");
    } catch(error){await client.query("ROLLBACK");throw error;} finally{client.release();}
    return c.json({data:{organizationId,userId}},201);
  });
  router.post("/login",async c=>{
    const parsed=loginSchema.safeParse(await c.req.json().catch(()=>null)); if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid login",parsed.error.flatten());
    const identifier=(parsed.data.identifier||parsed.data.email||"").trim(),ip=requestIp(c.req.header.bind(c.req)),userAgent=c.req.header("User-Agent");
    let user:{id:string;passwordHash:string|null;status:string}|undefined;
    if(identifier.includes("@")){user=(await runtime.db.query<{id:string;passwordHash:string|null;status:string}>(`SELECT id,password_hash AS "passwordHash",status FROM users WHERE lower(email)=lower($1)`,[identifier])).rows[0];}
    else if(parsed.data.organizationId){const normalized=identifier.replace(/\s+/g,"").toLowerCase();user=(await runtime.db.query<{id:string;passwordHash:string|null;status:string}>(`SELECT u.id,u.password_hash AS "passwordHash",u.status FROM identity_aliases a JOIN users u ON u.id=a.user_id WHERE a.organization_id=$1 AND a.alias_normalized=$2 LIMIT 1`,[parsed.data.organizationId,normalized])).rows[0];}
    else throw new AppError(422,"ORGANIZATION_REQUIRED","Organization is required when signing in with username or phone number");
    if(!user?.passwordHash||user.status!=="active"||!await verifyPassword(parsed.data.password,user.passwordHash)){await loginEvent(runtime,{organizationId:parsed.data.organizationId,userId:user?.id,identifier,eventType:"failure",ip,userAgent,reason:"Invalid credentials"});throw new AppError(401,"INVALID_CREDENTIALS","Invalid credentials");}
    if(passwordNeedsRehash(user.passwordHash))await runtime.db.query("UPDATE users SET password_hash=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2",[await hashPassword(parsed.data.password),user.id]);
    const membership=parsed.data.organizationId?(await runtime.db.query<{organizationId:string;role:string;scopes:string[]}>(`SELECT m.organization_id AS "organizationId",m.role,m.scopes FROM memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 AND m.organization_id=$2 AND o.status='active' LIMIT 1`,[user.id,parsed.data.organizationId])).rows[0]:(await runtime.db.query<{organizationId:string;role:string;scopes:string[]}>(`SELECT m.organization_id AS "organizationId",m.role,m.scopes FROM memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 AND o.status='active' ORDER BY m.created_at LIMIT 1`,[user.id])).rows[0];
    if(!membership)throw new AppError(403,"NO_MEMBERSHIP","No organization membership found");
    const mfa=(await runtime.db.query<{secretEncrypted:string;recoveryHashes:string[]}>(`SELECT secret_encrypted AS "secretEncrypted",recovery_code_hashes AS "recoveryHashes" FROM identity_mfa WHERE organization_id=$1 AND user_id=$2 AND method='totp' AND enabled=true`,[membership.organizationId,user.id])).rows[0];
    if(mfa){if(!parsed.data.mfaCode)throw new AppError(401,"MFA_REQUIRED","Two-factor authentication code required",{method:"totp"});const secret=await decryptMfaSecret(runtime.config.JWT_SECRET,mfa.secretEncrypted);let valid=verifyTotp(secret,parsed.data.mfaCode);if(!valid){const recoveryHash=hashRecoveryCode(parsed.data.mfaCode),index=mfa.recoveryHashes.indexOf(recoveryHash);if(index>=0){valid=true;const next=[...mfa.recoveryHashes];next.splice(index,1);await runtime.db.query("UPDATE identity_mfa SET recovery_code_hashes=$1::jsonb,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$2 AND user_id=$3 AND method='totp'",[JSON.stringify(next),membership.organizationId,user.id]);}}if(!valid)throw new AppError(401,"INVALID_MFA_CODE","Two-factor authentication code is invalid");}
    await loginEvent(runtime,{organizationId:membership.organizationId,userId:user.id,identifier,eventType:"success",ip,userAgent});
    return c.json({data:await issueTokens(runtime,runtime.db,user.id,membership.organizationId,membership.role,membership.scopes,{ip,userAgent})});
  });
  router.post("/refresh",async c=>{
    const body=await c.req.json<{refreshToken?:string}>().catch(()=>({}));if(!body.refreshToken)throw new AppError(422,"REFRESH_TOKEN_REQUIRED","Refresh token required");const client=await runtime.db.connect();
    try{await client.query("BEGIN");const session=(await client.query<{id:string;userId:string;organizationId:string;role:string;scopes:string[]}>(`SELECT s.id,s.user_id AS "userId",s.organization_id AS "organizationId",m.role,m.scopes FROM sessions s JOIN memberships m ON m.user_id=s.user_id AND m.organization_id=s.organization_id JOIN users u ON u.id=s.user_id JOIN organizations o ON o.id=s.organization_id WHERE s.refresh_token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP AND u.status='active' AND o.status='active' FOR UPDATE OF s`,[sha256(body.refreshToken)])).rows[0];if(!session)throw new AppError(401,"INVALID_REFRESH_TOKEN","Refresh token is invalid or expired");await client.query("UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[session.id]);const data=await issueTokens(runtime,client,session.userId,session.organizationId,session.role,session.scopes,{ip:requestIp(c.req.header.bind(c.req)),userAgent:c.req.header("User-Agent")});await client.query("COMMIT");return c.json({data});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  });
  router.post("/logout",async c=>{const body=await c.req.json<{refreshToken?:string}>().catch(()=>({}));if(body.refreshToken)await runtime.db.query("UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE refresh_token_hash=$1 AND revoked_at IS NULL",[sha256(body.refreshToken)]);return c.body(null,204);});
  return router;
}

export function createOrganizationRoutes(runtime:Runtime){
  const router=new Hono<AppEnv>();
  router.post("/switch",async c=>{const p=c.get("principal"),body=await c.req.json<{organizationId?:string}>().catch(()=>({}));if(!body.organizationId)throw new AppError(422,"VALIDATION_ERROR","Organization is required");const membership=(await runtime.db.query<{role:string;scopes:string[]}>(`SELECT m.role,m.scopes FROM memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 AND m.organization_id=$2 AND o.status='active'`,[p.userId,body.organizationId])).rows[0];if(!membership)throw new AppError(403,"NO_MEMBERSHIP","No active organization membership found");return c.json({data:await issueTokens(runtime,runtime.db,p.userId,body.organizationId,membership.role,membership.scopes,{ip:requestIp(c.req.header.bind(c.req)),userAgent:c.req.header("User-Agent")})});});
  router.get("/",async c=>{const p=c.get("principal");const result=await runtime.db.query(`SELECT o.id,o.name,o.legal_name AS "legalName",o.base_currency AS "baseCurrency",o.timezone,o.fiscal_year_start_month AS "fiscalYearStartMonth",o.address,o.tax_registration_number AS "taxRegistrationNumber",o.document_numbering AS "documentNumbering",o.status,m.role,m.scopes FROM memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 ORDER BY o.name`,[p.userId]);return c.json({data:result.rows});});
  router.get("/current",requireScope("accounts:read"),async c=>{const p=c.get("principal"),row=(await runtime.db.query(`SELECT id,name,legal_name AS "legalName",base_currency AS "baseCurrency",timezone,fiscal_year_start_month AS "fiscalYearStartMonth",address,tax_registration_number AS "taxRegistrationNumber",document_numbering AS "documentNumbering",branding,status,created_at AS "createdAt",updated_at AS "updatedAt" FROM organizations WHERE id=$1`,[p.organizationId])).rows[0];if(!row)throw new AppError(404,"NOT_FOUND","Organization not found");return c.json({data:row});});
  router.put("/current",requireScope("admin:write"),async c=>{const parsed=settingsSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid organization settings",parsed.error.flatten());const p=c.get("principal"),v=parsed.data;await runtime.db.query(`UPDATE organizations SET name=$1,legal_name=$2,base_currency=$3,timezone=$4,fiscal_year_start_month=$5,address=$6::jsonb,tax_registration_number=$7,document_numbering=$8::jsonb,branding=$9::jsonb,updated_at=CURRENT_TIMESTAMP WHERE id=$10`,[v.name,v.legalName??null,v.baseCurrency,v.timezone,v.fiscalYearStartMonth,JSON.stringify(v.address),v.taxRegistrationNumber??null,JSON.stringify(v.documentNumbering),JSON.stringify(v.branding),p.organizationId]);await audit(runtime,p.organizationId,p.userId,"organization.updated","organization",p.organizationId,v,c.get("requestId"));return c.json({data:{id:p.organizationId,...v}});});
  const createSchema=settingsSchema.pick({name:true,legalName:true,baseCurrency:true,timezone:true,fiscalYearStartMonth:true,address:true,taxRegistrationNumber:true,documentNumbering:true});
  router.post("/",requireScope("admin:write"),async c=>{const parsed=createSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid organization",parsed.error.flatten());const p=c.get("principal");if(p.userId.startsWith("apikey:"))throw new AppError(403,"FORBIDDEN","API keys cannot create organizations");const id=createId("org"),v=parsed.data,client=await runtime.db.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO organizations(id,name,legal_name,base_currency,timezone,fiscal_year_start_month,address,tax_registration_number,document_numbering) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9::jsonb)`,[id,v.name,v.legalName??null,v.baseCurrency,v.timezone,v.fiscalYearStartMonth,JSON.stringify(v.address),v.taxRegistrationNumber??null,JSON.stringify(v.documentNumbering)]);await client.query("INSERT INTO memberships(organization_id,user_id,role,scopes) VALUES($1,$2,'owner','[]'::jsonb)",[id,p.userId]);await outbox(runtime,"organization.created","organization",id,{organizationId:id,userId:p.userId,source:"organization.create"},client);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}return c.json({data:{id,...v}},201);});
  return router;
}

export function createAdminRoutes(runtime:Runtime){
  const router=new Hono<AppEnv>();
  router.get("/memberships",requireScope("admin:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT m.user_id AS "userId",u.email,u.display_name AS "displayName",m.role,m.scopes,m.created_at AS "createdAt" FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 ORDER BY u.display_name`,[p.organizationId]);return c.json({data:r.rows});});
  router.post("/memberships",requireScope("admin:write"),async c=>{const p=c.get("principal");if(!["owner","admin"].includes(p.role))throw new AppError(403,"FORBIDDEN","Only owners and administrators can add members");const parsed=memberSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid member",parsed.error.flatten());const v=parsed.data,client=await runtime.db.connect();let userId:string;try{await client.query("BEGIN");const existing=(await client.query<{id:string}>("SELECT id FROM users WHERE lower(email)=lower($1)",[v.email])).rows[0];userId=existing?.id??createId("usr");if(!existing)await client.query("INSERT INTO users(id,email,display_name) VALUES($1,$2,$3)",[userId,v.email.toLowerCase(),v.displayName]);if((await client.query("SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$2",[p.organizationId,userId])).rowCount)throw new AppError(409,"DUPLICATE_RECORD","User is already a member of this organization");await client.query("INSERT INTO memberships(organization_id,user_id,role,scopes) VALUES($1,$2,$3,$4::jsonb)",[p.organizationId,userId,v.role,JSON.stringify(v.scopes)]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}await audit(runtime,p.organizationId,p.userId,"membership.created","membership",userId!,{role:v.role,scopes:v.scopes},c.get("requestId"));return c.json({data:{userId:userId!,...v}},201);});
  router.put("/memberships/:userId",requireScope("admin:write"),async c=>{const p=c.get("principal"),userId=c.req.param("userId"),parsed=memberSchema.pick({displayName:true,role:true,scopes:true}).safeParse(await c.req.json().catch(()=>null));if(!["owner","admin"].includes(p.role))throw new AppError(403,"FORBIDDEN","Only owners and administrators can edit members");if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid member",parsed.error.flatten());const existing=(await runtime.db.query<{role:string}>("SELECT role FROM memberships WHERE organization_id=$1 AND user_id=$2",[p.organizationId,userId])).rows[0];if(!existing)throw new AppError(404,"NOT_FOUND","Member not found");if(existing.role==="owner")throw new AppError(409,"OWNER_PROTECTED","Ownership cannot be changed here");await runtime.db.query("UPDATE memberships SET role=$1,scopes=$2::jsonb,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$3 AND user_id=$4",[parsed.data.role,JSON.stringify(parsed.data.scopes),p.organizationId,userId]);await runtime.db.query("UPDATE users SET display_name=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2",[parsed.data.displayName,userId]);return c.json({data:{userId,...parsed.data}});});
  router.delete("/memberships/:userId",requireScope("admin:write"),async c=>{const p=c.get("principal"),userId=c.req.param("userId");if(userId===p.userId)throw new AppError(409,"SELF_REMOVAL","You cannot remove your own membership");const result=await runtime.db.query("DELETE FROM memberships WHERE organization_id=$1 AND user_id=$2 AND role<>'owner'",[p.organizationId,userId]);if(!result.rowCount)throw new AppError(409,"OWNER_PROTECTED","Owner membership cannot be removed");return c.body(null,204);});
  router.get("/api-keys",requireScope("admin:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT id,name,prefix,scopes,expires_at AS "expiresAt",last_used_at AS "lastUsedAt",revoked_at AS "revokedAt",created_at AS "createdAt" FROM api_keys WHERE organization_id=$1 ORDER BY created_at DESC`,[p.organizationId]);return c.json({data:r.rows});});
  router.post("/api-keys",requireScope("admin:write"),async c=>{const parsed=keySchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid API key",parsed.error.flatten());const p=c.get("principal"),id=createId("key"),secret=`yfp_${randomToken(32)}`,prefix=secret.slice(0,12),v=parsed.data;await runtime.db.query("INSERT INTO api_keys(id,organization_id,name,prefix,key_hash,scopes,expires_at,created_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8)",[id,p.organizationId,v.name,prefix,sha256(secret),JSON.stringify(v.scopes),v.expiresAt??null,p.userId]);await audit(runtime,p.organizationId,p.userId,"api_key.created","api_key",id,{name:v.name,prefix,scopes:v.scopes},c.get("requestId"));return c.json({data:{id,name:v.name,prefix,secret,scopes:v.scopes,expiresAt:v.expiresAt},warning:"Copy the secret now; it cannot be retrieved again."},201);});
  router.delete("/api-keys/:id",requireScope("admin:write"),async c=>{const p=c.get("principal");await runtime.db.query("UPDATE api_keys SET revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND revoked_at IS NULL",[c.req.param("id"),p.organizationId]);return c.body(null,204);});
  return router;
}
