import {useEffect,useState} from "react";
import {RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {Card,ErrorNotice,Metric,Pill,SectionTitle} from "../school/ui";
import {humanResourcesApi} from "./api";
import type {HrAuditEntry,HrDashboard,HrManifest} from "./types";
import {err} from "./context";

export function OverviewTab({session,onSession}:{session:MobileSession;onSession:SessionUpdater}){const c={session,onSession};const[data,setData]=useState<HrDashboard|null>(null),[manifest,setManifest]=useState<HrManifest|null>(null),[audit,setAudit]=useState<HrAuditEntry[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const[d,m,a]=await Promise.all([humanResourcesApi.dashboard(c),humanResourcesApi.manifest(c),humanResourcesApi.audit(c,12)]);setData(d);setManifest(m);setAudit(a)}catch(e){setError(err(e))}finally{setLoading(false)}}useEffect(()=>{void load()},[session.accessToken]);return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.scroll}><View style={s.hero}><Text style={s.eyebrow}>PEOPLE · WORKFORCE OPERATIONS</Text><Text style={s.title}>Human Resources</Text><Text style={s.copy}>Manage employment records, departments, onboarding and leave while reusing people already defined in Ledgerly modules.</Text></View>{error?<ErrorNotice message={error} onRetry={load}/>:null}<View style={s.metrics}><Metric label="Employees" value={data?.employees||0} sub="HR records"/><Metric label="Active" value={data?.activeEmployees||0} sub="currently active" tone="good"/><Metric label="Departments" value={data?.departments||0} sub="active departments"/><Metric label="Leave approvals" value={data?.pendingLeave||0} sub="pending" tone={(data?.pendingLeave||0)>0?"warn":"good"}/><Metric label="Onboarding" value={data?.pendingOnboarding||0} sub="pending tasks" tone={(data?.pendingOnboarding||0)>0?"warn":"good"}/></View><SectionTitle title="Connected people sources" subtitle="HR discovers people from enabled Ledgerly modules"/><Card>{manifest?.enabledModules?.length?manifest.enabledModules.map(x=><View key={x.key} style={s.row}><View style={{flex:1}}><Text style={s.name}>{x.name}</Text><Text style={s.meta}>{x.key}</Text></View><Pill text="ENABLED" tone="good"/></View>):<Text style={s.empty}>No enabled people-source modules were reported.</Text>}</Card><SectionTitle title="Recent HR audit" subtitle="Recorded workforce and approval changes"/><Card>{audit.length?audit.slice(0,8).map(x=><View key={x.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{x.action.replace(/^hr\./,"").replaceAll("."," · ").replaceAll("_"," ")}</Text><Text style={s.meta}>{x.actorName||"Ledgerly user"} · {String(x.createdAt||"").replace("T"," ").slice(0,16)}</Text></View></View>):<Text style={s.empty}>No HR audit activity has been recorded yet.</Text>}</Card><SectionTitle title="Operational scope"/><Card><Text style={s.scope}>Workforce directory · employment records · departments · onboarding · leave types · leave requests · approvals · audit</Text></Card></ScrollView>}
const s=StyleSheet.create({scroll:{padding:16,paddingBottom:40,gap:12},hero:{backgroundColor:"#30283f",borderRadius:24,padding:20},eyebrow:{fontSize:8,fontWeight:"900",letterSpacing:1.1,color:"#bfa9ec"},title:{fontSize:27,fontWeight:"900",color:"white",marginTop:7},copy:{fontSize:11,lineHeight:17,color:"#d6cce8",marginTop:6},metrics:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",gap:10},row:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:9,borderBottomWidth:1,borderBottomColor:"#edf1ef"},name:{fontSize:11,fontWeight:"900",color:"#2f3d36",textTransform:"capitalize"},meta:{fontSize:9,color:"#7f8c86",marginTop:3},empty:{fontSize:10,color:"#7e8d86"},scope:{fontSize:10,lineHeight:17,color:"#65756d"}});
