import {useEffect,useMemo,useState} from "react";
import {ActivityIndicator,Alert,KeyboardAvoidingView,Platform,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from "react-native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {agenticEmployeesApi,type AgentApproval,type AgentConversation,type AgenticEmployee,type AgenticSettings,type AgentMessage,type AgentTask,type EventReaction,type EventSettings} from "./agenticEmployeesApi";

type Tab="employees"|"workspace"|"tasks"|"approvals"|"events";
type Profile={icon:string;domain:string;short:string;accent:string;skills:string[];prompts:string[]};
const TABS:Array<{key:Tab;label:string;hint:string}>=[
 {key:"employees",label:"Workforce",hint:"Choose the right digital employee"},
 {key:"workspace",label:"Workspace",hint:"Continue a saved conversation"},
 {key:"tasks",label:"Tasks",hint:"Assigned AI work"},
 {key:"approvals",label:"Actions",hint:"Human review queue"},
 {key:"events",label:"Reactions",hint:"Automatic school alerts"},
];
const PROFILES:Record<string,Profile>={
 secretary:{icon:"AM",domain:"OFFICE",short:"Front office & communications",accent:"#168c5a",skills:["Admissions","Parents","Letters","Communications"],prompts:["Show front-office work that needs attention","Draft a parent communication for…","Help me prepare student or guardian records"]},
 dos:{icon:"DD",domain:"ACADEMICS",short:"Academic supervision",accent:"#4477d6",skills:["Lesson plans","Schemes","Timetables","Supervision"],prompts:["Check lesson-plan compliance this week","Show teachers who need academic follow-up","Prepare a lesson plan for…"]},
 bursar:{icon:"GG",domain:"FINANCE",short:"Fees & finance operations",accent:"#c78320",skills:["Fees","Payments","Banking","Journals"],prompts:["Review today's fee collections","Show students with the largest balances","Prepare these payment records for posting"]},
 headteacher:{icon:"MM",domain:"MANAGEMENT",short:"Executive school coordination",accent:"#7657c7",skills:["Briefings","Exceptions","Delegation","Decisions"],prompts:["Give me today's executive school brief","What needs my attention across the school?","Prepare a management briefing for…"]},
 hr:{icon:"SS",domain:"HR",short:"Staff & people operations",accent:"#c45772",skills:["Staff","Leave","Payroll","HR documents"],prompts:["Show staff matters that need follow-up","Review approved leave and staffing impact","Prepare an HR handover brief"]},
 librarian:{icon:"PP",domain:"BOOKS",short:"Books & learning inventory",accent:"#198c8f",skills:["Stock","Issues","Returns","Inventory"],prompts:["Show books that need restocking","Review learner book distributions","Prepare a writing-book stock report"]},
};
const FALLBACK:Profile={icon:"AI",domain:"GENERAL",short:"Ledgerly AI employee",accent:"#667785",skills:["School work"],prompts:["What needs my attention today?"]};
const INTENTS=[
 {label:"Fees & payments",agent:"bursar",prompt:"Help me with fees, payments or finance records"},
 {label:"Lesson plans",agent:"dos",prompt:"Help me review or create lesson-plan work"},
 {label:"Staff & leave",agent:"hr",prompt:"Help me with staff, leave or HR work"},
 {label:"Books & stock",agent:"librarian",prompt:"Help me with books and stock work"},
 {label:"Parents & office",agent:"secretary",prompt:"Help me with front-office, parent or student work"},
 {label:"Executive brief",agent:"headteacher",prompt:"Give me an executive school briefing"},
];

export function AgenticEmployeesWorkspaceScreen({session,onSession,onBack}:{session:MobileSession;onSession:SessionUpdater;onBack:()=>void}){
 const[tab,setTab]=useState<Tab>("employees"),[agents,setAgents]=useState<AgenticEmployee[]>([]),[settings,setSettings]=useState<AgenticSettings|null>(null),[eventSettings,setEventSettings]=useState<EventSettings|null>(null);
 const[selectedKey,setSelectedKey]=useState("secretary"),[conversation,setConversation]=useState<AgentConversation|null>(null),[conversations,setConversations]=useState<AgentConversation[]>([]),[messages,setMessages]=useState<AgentMessage[]>([]),[message,setMessage]=useState("");
 const[tasks,setTasks]=useState<AgentTask[]>([]),[approvals,setApprovals]=useState<AgentApproval[]>([]),[reactions,setReactions]=useState<EventReaction[]>([]),[taskTitle,setTaskTitle]=useState(""),[taskInstructions,setTaskInstructions]=useState("");
 const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState("");
 const activeMeta=TABS.find(x=>x.key===tab)||TABS[0],agent=useMemo(()=>agents.find(x=>x.key===selectedKey)||agents[0],[agents,selectedKey]),profile=agent?(PROFILES[agent.key]||FALLBACK):FALLBACK;
 const pending=approvals.filter(x=>x.status==="pending").length,urgent=reactions.filter(x=>!x.acknowledgedAt&&x.severity==="urgent").length;
 const visibleAgents=useMemo(()=>{const q=search.trim().toLowerCase();return agents.filter(item=>{const p=PROFILES[item.key]||FALLBACK;return !q||[item.name,item.title,item.description,p.short,...p.skills,...item.configuredTools].join(" ").toLowerCase().includes(q)})},[agents,search]);

 function errorText(e:unknown){return e instanceof Error?e.message:String(e)}
 function latestConversation(key:string){return conversations.filter(x=>x.agentKey===key).sort((a,b)=>String(b.lastMessageAt||b.createdAt||"").localeCompare(String(a.lastMessageAt||a.createdAt||"")))[0]}
 function workload(key:string){return {tasks:tasks.filter(x=>x.agentKey===key&&!["completed","failed","cancelled"].includes(x.status)).length,actions:approvals.filter(x=>x.agentKey===key&&["pending","approved"].includes(x.status)).length}}
 async function load(showSpinner=true){if(showSpinner)setLoading(true);else setRefreshing(true);setError("");try{
   const[a,st,ta,cv,pendingApprovals,approvedApprovals,rx,es]=await Promise.all([
    agenticEmployeesApi.agents(session,onSession),agenticEmployeesApi.settings(session,onSession),agenticEmployeesApi.tasks(session,onSession),agenticEmployeesApi.conversations(session,onSession),
    agenticEmployeesApi.approvals(session,onSession,"pending"),agenticEmployeesApi.approvals(session,onSession,"approved"),agenticEmployeesApi.reactions(session,onSession),agenticEmployeesApi.eventSettings(session,onSession),
   ]);
   setAgents(a);setSettings(st);setTasks(ta);setConversations(cv);setApprovals([...pendingApprovals,...approvedApprovals]);setReactions(rx);setEventSettings(es);
   if(a.length&&!a.some(x=>x.key===selectedKey))setSelectedKey(a[0].key);
  }catch(e){setError(errorText(e))}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[session.accessToken,session.apiUrl,session.organizationId]);

 async function resumeConversation(next:AgentConversation){setBusy(true);setError("");setSelectedKey(next.agentKey);try{const history=await agenticEmployeesApi.messages(session,onSession,next.id);setConversation(next);setMessages(history);setTab("workspace")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function openEmployee(next:AgenticEmployee,forceNew=false,initial=""){if(!next.enabled)return;setSelectedKey(next.key);const recent=!forceNew?latestConversation(next.key):undefined;if(recent){setMessage(initial);await resumeConversation(recent);return}setBusy(true);setError("");try{const c=await agenticEmployeesApi.createConversation(session,onSession,next.key,next.title);setConversation(c);setConversations(x=>[c,...x]);setMessages([]);setMessage(initial);setTab("workspace")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function launchIntent(item:typeof INTENTS[number]){const target=agents.find(x=>x.key===item.agent)||agents.find(x=>x.enabled);if(target)await openEmployee(target,false,item.prompt)}
 async function send(){const content=message.trim();if(!conversation||!content||busy)return;setMessage("");setMessages(x=>[...x,{id:`local-${Date.now()}`,role:"user",content}]);setBusy(true);setError("");try{const reply=await agenticEmployeesApi.sendMessage(session,onSession,conversation.id,content);setMessages(x=>[...x,reply]);const cv=await agenticEmployeesApi.conversations(session,onSession);setConversations(cv)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function createTask(){if(!agent||!taskTitle.trim()||!taskInstructions.trim())return;setBusy(true);setError("");try{await agenticEmployeesApi.createTask(session,onSession,{agentKey:agent.key,title:taskTitle.trim(),instructions:taskInstructions.trim()});setTaskTitle("");setTaskInstructions("");setTasks(await agenticEmployeesApi.tasks(session,onSession));setTab("tasks")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function approvalAction(item:AgentApproval,action:"approve"|"reject"|"execute"){setBusy(true);setError("");try{if(action==="execute")await agenticEmployeesApi.executeApproval(session,onSession,item.id);else await agenticEmployeesApi.decideApproval(session,onSession,item.id,action);const[p,a]=await Promise.all([agenticEmployeesApi.approvals(session,onSession,"pending"),agenticEmployeesApi.approvals(session,onSession,"approved")]);setApprovals([...p,...a])}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 function confirmApproval(item:AgentApproval,action:"approve"|"reject"|"execute"){const verb=action==="execute"?"Execute":action==="approve"?"Approve":"Reject";Alert.alert(`${verb} this action?`,`${friendlyAction(item.actionType)}\n\nThe employee cannot complete this sensitive action without your human step.`,[{text:"Cancel",style:"cancel"},{text:verb,style:action==="reject"?"destructive":"default",onPress:()=>void approvalAction(item,action)}])}
 async function acknowledge(item:EventReaction){setBusy(true);setError("");try{await agenticEmployeesApi.acknowledgeReaction(session,onSession,item.id);setReactions(await agenticEmployeesApi.reactions(session,onSession))}catch(e){setError(errorText(e))}finally{setBusy(false)}}

 const EmployeeCard=({item}:{item:AgenticEmployee})=>{const p=PROFILES[item.key]||FALLBACK,w=workload(item.key),recent=latestConversation(item.key);return <TouchableOpacity accessibilityRole="button" activeOpacity={.9} disabled={!item.enabled||busy} style={[s.employeeCard,item.key===selectedKey&&{borderColor:p.accent},!item.enabled&&s.disabledCard]} onPress={()=>setSelectedKey(item.key)}>
  <View style={s.employeeTop}><View style={[s.avatar,{backgroundColor:hexSoft(p.accent)}]}><Text style={[s.avatarText,{color:p.accent}]}>{p.icon}</Text><View style={[s.liveDot,item.enabled&&s.liveDotOn]}/></View><View style={{flex:1}}><Text style={[s.domain,{color:p.accent}]}>{p.domain}</Text><View style={s.nameRow}><Text style={s.employeeName}>{item.name}</Text><View style={[s.status,item.enabled?s.statusOn:s.statusOff]}><Text style={[s.statusText,item.enabled?s.statusTextOn:s.statusTextOff]}>{item.enabled?"READY":"OFF"}</Text></View></View><Text style={s.employeeTitle}>{item.title}</Text></View></View>
  <Text style={s.employeeCopy}>{p.short}. {item.description}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.skillRow}>{p.skills.map(skill=><Text key={skill} style={s.skill}>{skill}</Text>)}</ScrollView>
  <View style={s.metrics}><Metric value={w.tasks} label="tasks"/><Metric value={w.actions} label="actions"/><Metric value={item.configuredTools.length} label="tools"/><Metric value={item.modelTier.toUpperCase()} label="model"/></View>
  <View style={s.cardActions}><TouchableOpacity style={s.secondaryAction} onPress={()=>{setSelectedKey(item.key);setTab("tasks")}}><Text style={s.secondaryActionText}>Assign</Text></TouchableOpacity><TouchableOpacity style={[s.primaryAction,{backgroundColor:p.accent}]} onPress={()=>void openEmployee(item)}><Text style={s.primaryActionText}>{recent?"Resume":"Chat"}  ›</Text></TouchableOpacity></View>
 </TouchableOpacity>};

 if(loading)return <SafeAreaView style={s.root}><View style={s.loading}><ActivityIndicator size="large" color="#178c5b"/><Text style={s.loadingTitle}>Loading AI workforce</Text><Text style={s.loadingCopy}>Connecting to your organisation’s digital employees.</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.root}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}>
  <View style={s.header}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Back to home" style={s.back} onPress={onBack}><Text style={s.backText}>‹</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.eyebrow}>LEDGERLY AI WORKFORCE</Text><Text style={s.headerTitle}>{activeMeta.label}</Text><Text style={s.headerHint}>{activeMeta.hint}</Text></View><View style={[s.provider,settings?.configured?s.providerOn:s.providerWarn]}><View style={[s.providerDot,settings?.configured?s.dotOn:s.dotWarn]}/><Text style={s.providerText}>{settings?.configured?"AI LIVE":"SETUP"}</Text></View></View>
  <View style={s.navWrap}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.nav}>{TABS.map(item=><TouchableOpacity key={item.key} accessibilityRole="tab" accessibilityState={{selected:tab===item.key}} style={[s.navItem,tab===item.key&&s.navActive]} onPress={()=>setTab(item.key)}><Text style={[s.navText,tab===item.key&&s.navTextActive]}>{item.label}</Text>{item.key==="approvals"&&pending>0?<View style={s.badge}><Text style={s.badgeText}>{pending}</Text></View>:null}{item.key==="events"&&urgent>0?<View style={[s.badge,s.urgentBadge]}><Text style={s.badgeText}>{urgent}</Text></View>:null}</TouchableOpacity>)}</ScrollView></View>
  <ScrollView keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(false)}/>} contentContainerStyle={s.content}>
   {error?<View style={s.error}><View style={{flex:1}}><Text style={s.errorTitle}>Something needs attention</Text><Text style={s.errorText}>{error}</Text></View><TouchableOpacity style={s.retry} onPress={()=>void load(false)}><Text style={s.retryText}>Retry</Text></TouchableOpacity></View>:null}
   {!settings?.configured?<View style={s.notice}><Text style={s.noticeTitle}>AI provider is not connected</Text><Text style={s.noticeText}>An administrator must configure the OpenAI API key before employees can answer or run tasks.</Text></View>:null}

   {tab==="employees"?<><View style={s.summaryRow}><Summary value={agents.filter(x=>x.enabled).length} label="employees"/><Summary value={tasks.filter(x=>!["completed","failed","cancelled"].includes(x.status)).length} label="open tasks"/><Summary value={approvals.length} label="actions"/><Summary value={conversations.length} label="threads"/></View>
    <View style={s.heroCard}><Text style={s.heroEyebrow}>START WITH THE JOB</Text><Text style={s.heroTitle}>What do you want done?</Text><Text style={s.heroCopy}>Choose a job and Ledgerly takes you to the right specialist.</Text><View style={s.intentGrid}>{INTENTS.map(item=><TouchableOpacity key={item.label} style={s.intentCard} onPress={()=>void launchIntent(item)}><Text style={s.intentTitle}>{item.label}</Text><Text style={s.intentAgent}>{agents.find(x=>x.key===item.agent)?.name||"AI employee"}  ›</Text></TouchableOpacity>)}</View></View>
    <TextInput value={search} onChangeText={setSearch} placeholder="Search by job, employee or capability…" placeholderTextColor="#87958e" style={s.search}/><Text style={s.sectionTitle}>Your digital school team</Text><Text style={s.sectionCopy}>Each employee works inside its department and your Ledgerly permissions. Sensitive writes still require human review.</Text><View style={s.stack}>{visibleAgents.map(item=><EmployeeCard key={item.key} item={item}/>)}{!visibleAgents.length?<Empty title="No employee found" copy="Try fees, lesson plans, staff, books or communications."/>:null}</View>
    {agent?<View style={s.selectedPanel}><Text style={s.selectedEyebrow}>SELECTED SPECIALIST</Text><Text style={s.selectedTitle}>{agent.name} · {agent.title}</Text><Text style={s.selectedCopy}>{profile.short}</Text><View style={s.quickPromptRow}>{profile.prompts.slice(0,2).map(p=><TouchableOpacity key={p} style={s.quickPrompt} onPress={()=>void openEmployee(agent,false,p)}><Text style={s.quickPromptText}>{p}</Text></TouchableOpacity>)}</View></View>:null}
   </>:null}

   {tab==="workspace"?<><View style={s.workspaceHero}><View style={[s.workspaceAvatar,{backgroundColor:hexSoft(profile.accent)}]}><Text style={[s.workspaceAvatarText,{color:profile.accent}]}>{profile.icon}</Text></View><View style={{flex:1}}><Text style={[s.domain,{color:profile.accent}]}>{profile.domain} SPECIALIST</Text><Text style={s.workspaceName}>{agent?.name||"Choose an employee"}</Text><Text style={s.workspaceRole}>{agent?.title} · {agent?.modelTier.toUpperCase()} · {agent?.configuredTools.length||0} tools</Text></View>{agent?<TouchableOpacity style={s.newChat} onPress={()=>void openEmployee(agent,true)}><Text style={s.newChatText}>＋ New</Text></TouchableOpacity>:null}</View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.pickerRow}>{agents.map(item=>{const p=PROFILES[item.key]||FALLBACK;return <TouchableOpacity key={item.key} disabled={!item.enabled||busy} style={[s.agentChip,item.key===selectedKey&&{backgroundColor:p.accent,borderColor:p.accent}]} onPress={()=>void openEmployee(item)}><Text style={[s.agentChipText,item.key===selectedKey&&s.agentChipTextActive]}>{item.name}</Text></TouchableOpacity>})}</ScrollView>
    {conversations.length?<><Text style={s.miniHeading}>RECENT CONVERSATIONS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.threadRow}>{conversations.slice(0,8).map(item=><TouchableOpacity key={item.id} style={[s.threadCard,conversation?.id===item.id&&s.threadCardActive]} onPress={()=>void resumeConversation(item)}><Text numberOfLines={1} style={s.threadTitle}>{item.title}</Text><Text style={s.threadMeta}>{agentName(agents,item.agentKey)} · {when(item.lastMessageAt||item.createdAt)}</Text></TouchableOpacity>)}</ScrollView></>:null}
    {!conversation?<View style={s.empty}><Text style={s.emptyIcon}>AI</Text><Text style={s.emptyTitle}>Choose an employee</Text><Text style={s.emptyCopy}>Select an employee above to start or resume a secure school conversation.</Text></View>:<View style={s.chatCard}><View style={s.contextRow}><Text style={s.contextPill}>✓ Role scoped</Text><Text style={s.contextPill}>◉ Memory</Text><Text style={s.contextPill}>▣ Governed actions</Text></View><View style={s.messages}>{messages.length===0?<View style={s.chatWelcome}><Text style={s.chatWelcomeTitle}>What should {agent?.name} do?</Text><Text style={s.chatWelcomeCopy}>Speak naturally. {agent?.name} can use permitted Ledgerly data, tools and memory.</Text><View style={s.promptStack}>{profile.prompts.map(p=><TouchableOpacity key={p} style={s.promptButton} onPress={()=>setMessage(p)}><Text style={s.promptText}>{p}</Text><Text style={s.promptArrow}>›</Text></TouchableOpacity>)}</View></View>:null}{messages.map(item=><View key={item.id} style={[s.messageBubble,item.role==="user"?s.userBubble:s.aiBubble]}><Text style={[s.messageWho,item.role==="user"&&{color:"#cfe6dc"}]}>{item.role==="user"?"YOU":agent?.name?.toUpperCase()}</Text><Text style={[s.messageText,item.role==="user"&&{color:"white"}]}>{item.content}</Text>{item.model?<Text style={[s.messageModel,item.role==="user"&&{color:"#cfe6dc"}]}>{item.model}</Text>:null}</View>)}{busy?<View style={[s.messageBubble,s.aiBubble]}><Text style={s.messageWho}>{agent?.name?.toUpperCase()}</Text><Text style={s.messageText}>Working with Ledgerly…</Text></View>:null}</View><View style={s.quickTools}><TouchableOpacity onPress={()=>setMessage("Create a document for ")}><Text style={s.quickToolText}>＋ Document</Text></TouchableOpacity><TouchableOpacity onPress={()=>setMessage("What do you remember about ")}><Text style={s.quickToolText}>◉ Memory</Text></TouchableOpacity><TouchableOpacity onPress={()=>setTab("approvals")}><Text style={s.quickToolText}>✓ Actions {approvals.length?`(${approvals.length})`:""}</Text></TouchableOpacity></View><View style={s.composer}><TextInput accessibilityLabel="Message AI employee" multiline value={message} onChangeText={setMessage} placeholder={`Message ${agent?.name||"employee"}…`} placeholderTextColor="#85938c" style={s.composerInput}/><TouchableOpacity accessibilityRole="button" disabled={busy||!message.trim()} style={[s.sendButton,{backgroundColor:profile.accent},(busy||!message.trim())&&s.buttonDisabled]} onPress={()=>void send()}><Text style={s.sendText}>Send</Text></TouchableOpacity></View></View>}
   </>:null}

   {tab==="tasks"?<><Text style={s.sectionTitle}>Assign real work</Text><Text style={s.sectionCopy}>Tasks use the selected employee’s tools, memory and role boundaries.</Text><View style={s.formCard}><Text style={s.fieldLabel}>EMPLOYEE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.pickerRow}>{agents.filter(x=>x.enabled).map(item=><TouchableOpacity key={item.key} style={[s.agentChip,item.key===selectedKey&&{backgroundColor:(PROFILES[item.key]||FALLBACK).accent,borderColor:(PROFILES[item.key]||FALLBACK).accent}]} onPress={()=>setSelectedKey(item.key)}><Text style={[s.agentChipText,item.key===selectedKey&&s.agentChipTextActive]}>{item.name}</Text></TouchableOpacity>)}</ScrollView><Text style={s.fieldLabel}>TASK TITLE</Text><TextInput value={taskTitle} onChangeText={setTaskTitle} placeholder="e.g. Review this week’s fee arrears" placeholderTextColor="#87958e" style={s.input}/><Text style={s.fieldLabel}>INSTRUCTIONS</Text><TextInput value={taskInstructions} onChangeText={setTaskInstructions} multiline placeholder="Describe the outcome you need and any limits." placeholderTextColor="#87958e" style={[s.input,s.textarea]}/><TouchableOpacity accessibilityRole="button" disabled={busy||!agent||!taskTitle.trim()||!taskInstructions.trim()} style={[s.primary,{backgroundColor:profile.accent},(busy||!taskTitle.trim()||!taskInstructions.trim())&&s.buttonDisabled]} onPress={()=>void createTask()}><Text style={s.primaryText}>{busy?"Assigning…":"Assign task"}</Text></TouchableOpacity></View><Text style={[s.sectionTitle,{marginTop:24}]}>Recent tasks</Text><View style={s.stack}>{tasks.map(item=><View key={item.id} style={s.listCard}><View style={s.listTop}><Text style={s.listTitle}>{item.title}</Text><StatePill text={item.status}/></View><Text style={s.listMeta}>{agentName(agents,item.agentKey)} · {when(item.createdAt)}</Text>{item.resultText?<Text style={s.result}>{item.resultText}</Text>:null}{item.errorText?<Text style={s.failure}>{item.errorText}</Text>:null}</View>)}{!tasks.length?<Empty title="No tasks yet" copy="Assigned AI work will appear here."/>:null}</View></>:null}

   {tab==="approvals"?<><Text style={s.sectionTitle}>Human action queue</Text><Text style={s.sectionCopy}>Review exactly what an employee wants to change before Ledgerly executes it.</Text><View style={s.safety}><Text style={s.safetyTitle}>Two-step control remains active</Text><Text style={s.safetyText}>Approval confirms the proposal. Execution is a separate action through Ledgerly’s permission-controlled backend.</Text></View><View style={s.stack}>{approvals.map(item=><View key={item.id} style={s.listCard}><View style={s.listTop}><Text style={s.listTitle}>{friendlyAction(item.actionType)}</Text><StatePill text={item.status}/></View><Text style={s.listMeta}>{agentName(agents,item.agentKey)} · requires {item.requiredScope}</Text><Text style={s.payload}>{payloadSummary(item.payload)}</Text><View style={s.actions}>{item.status==="pending"?<><TouchableOpacity disabled={busy} style={s.smallPrimary} onPress={()=>confirmApproval(item,"approve")}><Text style={s.smallPrimaryText}>Approve</Text></TouchableOpacity><TouchableOpacity disabled={busy} style={s.smallSecondary} onPress={()=>confirmApproval(item,"reject")}><Text style={s.smallSecondaryText}>Reject</Text></TouchableOpacity></>:null}{item.status==="approved"?<TouchableOpacity disabled={busy} style={s.smallPrimary} onPress={()=>confirmApproval(item,"execute")}><Text style={s.smallPrimaryText}>Execute approved action</Text></TouchableOpacity>:null}</View></View>)}{!approvals.length?<Empty title="Action queue is clear" copy="No sensitive employee actions are waiting for review."/>:null}</View></>:null}

   {tab==="events"?<><View style={s.eventStatus}><View><Text style={s.eventStatusTitle}>Proactive workforce</Text><Text style={s.eventStatusCopy}>{eventSettings?.enabled?"Listening for verified Ledgerly events":"Event reactions are disabled"}</Text></View><View style={[s.eventSwitch,eventSettings?.enabled?s.eventSwitchOn:s.eventSwitchOff]}><Text style={s.eventSwitchText}>{eventSettings?.enabled?"ON":"OFF"}</Text></View></View><Text style={s.sectionTitle}>School event reactions</Text><Text style={s.sectionCopy}>Payments, attendance, approved leave, book stock and academic follow-up can surface here automatically.</Text><View style={s.stack}>{reactions.map(item=><View key={item.id} style={[s.reactionCard,item.severity==="urgent"&&s.reactionUrgent,item.severity==="attention"&&s.reactionAttention]}><View style={s.listTop}><View style={[s.severityDot,item.severity==="urgent"?s.severityUrgent:item.severity==="attention"?s.severityAttention:s.severityInfo]}/><Text style={[s.listTitle,{flex:1}]}>{item.title}</Text><Text style={s.severityLabel}>{item.severity.toUpperCase()}</Text></View><Text style={s.listMeta}>{agentName(agents,item.agentKey)} · {item.sourceModule} · {when(item.occurredAt)}</Text><Text style={s.result}>{item.summary}</Text>{item.recommendedAction?<View style={s.recommend}><Text style={s.recommendLabel}>RECOMMENDED FOLLOW-UP</Text><Text style={s.recommendText}>{item.recommendedAction}</Text></View>:null}{!item.acknowledgedAt?<TouchableOpacity disabled={busy} style={s.ackButton} onPress={()=>void acknowledge(item)}><Text style={s.ackText}>Acknowledge</Text></TouchableOpacity>:<Text style={s.acknowledged}>✓ Acknowledged</Text>}</View>)}{!reactions.length?<Empty title="No event reactions yet" copy="Verified school events and AI follow-up will appear here."/>:null}</View></>:null}
  </ScrollView>
 </KeyboardAvoidingView></SafeAreaView>
}

function Summary({value,label}:{value:number;label:string}){return <View style={s.summary}><Text style={s.summaryValue}>{value}</Text><Text style={s.summaryLabel}>{label}</Text></View>}
function Metric({value,label}:{value:string|number;label:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Empty({title,copy}:{title:string;copy:string}){return <View style={s.emptySmall}><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyCopy}>{copy}</Text></View>}
function StatePill({text}:{text:string}){const good=["completed","approved","executed"].includes(text);return <View style={[s.statePill,good?s.stateGood:text==="failed"?s.stateBad:s.stateNeutral]}><Text style={s.stateText}>{text.toUpperCase()}</Text></View>}
function agentName(agents:AgenticEmployee[],key:string){const a=agents.find(x=>x.key===key);return a?`${a.name} · ${a.title}`:key}
function friendlyAction(value:string){return value.replace(/[._-]+/g," ").replace(/\b\w/g,x=>x.toUpperCase())}
function payloadSummary(value:Record<string,unknown>){const entries=Object.entries(value||{}).slice(0,4);return entries.length?entries.map(([k,v])=>`${friendlyAction(k)}: ${typeof v==="object"?JSON.stringify(v):String(v)}`).join("\n"):"No additional action details."}
function when(value?:string){if(!value)return"recent";const d=new Date(value),ms=Date.now()-d.getTime();if(Number.isNaN(d.getTime()))return value;if(ms<60000)return"now";if(ms<3600000)return`${Math.max(1,Math.floor(ms/60000))}m ago`;if(ms<86400000)return`${Math.floor(ms/3600000)}h ago`;return d.toLocaleDateString()}
function hexSoft(hex:string){return `${hex}18`}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:"#f3f7f5"},header:{minHeight:94,backgroundColor:"#071c16",paddingHorizontal:14,paddingVertical:12,flexDirection:"row",alignItems:"center",gap:12},back:{width:48,height:48,borderRadius:15,borderWidth:1,borderColor:"#2b5143",alignItems:"center",justifyContent:"center"},backText:{color:"#fff",fontSize:34,lineHeight:38,fontWeight:"400",marginTop:-3},eyebrow:{color:"#67d8a2",fontSize:10,lineHeight:14,fontWeight:"900",letterSpacing:1},headerTitle:{color:"white",fontSize:22,lineHeight:27,fontWeight:"900",marginTop:2},headerHint:{color:"#a9c1b7",fontSize:12,lineHeight:16,marginTop:1},provider:{minHeight:40,borderRadius:14,paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:6,borderWidth:1},providerOn:{backgroundColor:"#103d2e",borderColor:"#2b7053"},providerWarn:{backgroundColor:"#46391e",borderColor:"#745f30"},providerDot:{width:7,height:7,borderRadius:4},dotOn:{backgroundColor:"#4bd394"},dotWarn:{backgroundColor:"#e5b94f"},providerText:{color:"#e5f1ec",fontSize:10,fontWeight:"900"},
 navWrap:{backgroundColor:"#0c2b21",borderBottomWidth:1,borderBottomColor:"#173d30"},nav:{paddingHorizontal:10,paddingVertical:8,gap:7},navItem:{minWidth:92,minHeight:46,borderRadius:14,paddingHorizontal:12,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},navActive:{backgroundColor:"#fff"},navText:{fontSize:12,fontWeight:"900",color:"#a8beb5"},navTextActive:{color:"#173b2e"},badge:{minWidth:20,height:20,borderRadius:10,backgroundColor:"#168c59",alignItems:"center",justifyContent:"center",paddingHorizontal:5},urgentBadge:{backgroundColor:"#b9493e"},badgeText:{color:"white",fontSize:10,fontWeight:"900"},
 content:{padding:16,paddingBottom:46},loading:{flex:1,alignItems:"center",justifyContent:"center",padding:30},loadingTitle:{fontSize:18,fontWeight:"900",color:"#1b352a",marginTop:15},loadingCopy:{fontSize:13,lineHeight:19,color:"#73837b",textAlign:"center",marginTop:5},error:{backgroundColor:"#fff0ed",borderWidth:1,borderColor:"#ebccc7",padding:14,borderRadius:16,flexDirection:"row",alignItems:"center",gap:10,marginBottom:14},errorTitle:{fontSize:14,fontWeight:"900",color:"#8b3e37"},errorText:{fontSize:12.5,lineHeight:18,color:"#8b5d58",marginTop:3},retry:{minWidth:62,minHeight:44,borderRadius:12,backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},retryText:{fontSize:12,fontWeight:"900",color:"#8b3e37"},notice:{backgroundColor:"#fff8e8",borderWidth:1,borderColor:"#eadcb7",borderRadius:17,padding:15,marginBottom:16},noticeTitle:{fontSize:15,fontWeight:"900",color:"#634d18"},noticeText:{fontSize:12.5,lineHeight:19,color:"#75653d",marginTop:5},
 summaryRow:{flexDirection:"row",gap:7,marginBottom:14},summary:{flex:1,backgroundColor:"#e5eee9",borderRadius:15,padding:10,minHeight:74},summaryValue:{fontSize:22,lineHeight:26,fontWeight:"900",color:"#14392b"},summaryLabel:{fontSize:9.5,lineHeight:13,fontWeight:"800",color:"#62776c",marginTop:4},heroCard:{backgroundColor:"#102f25",borderRadius:21,padding:17,marginBottom:14},heroEyebrow:{color:"#68d5a1",fontSize:10,fontWeight:"900",letterSpacing:1},heroTitle:{color:"#fff",fontSize:22,fontWeight:"900",marginTop:3},heroCopy:{color:"#abc1b7",fontSize:12.5,lineHeight:18,marginTop:4},intentGrid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:14},intentCard:{width:"48%",minHeight:62,borderRadius:14,backgroundColor:"#173f31",borderWidth:1,borderColor:"#285442",padding:11,justifyContent:"center"},intentTitle:{color:"#fff",fontSize:12.5,fontWeight:"900"},intentAgent:{color:"#87c8aa",fontSize:10.5,fontWeight:"800",marginTop:4},search:{minHeight:50,borderWidth:1,borderColor:"#d7e2dc",borderRadius:15,paddingHorizontal:14,fontSize:13.5,color:"#20382e",backgroundColor:"#fff",marginBottom:18},sectionTitle:{fontSize:21,lineHeight:27,fontWeight:"900",color:"#173328"},sectionCopy:{fontSize:13,lineHeight:20,color:"#6c7c74",marginTop:5,marginBottom:14},stack:{gap:11},
 employeeCard:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dce6e1",borderRadius:21,padding:16},disabledCard:{opacity:.6},employeeTop:{flexDirection:"row",alignItems:"center",gap:12},avatar:{width:52,height:52,borderRadius:17,alignItems:"center",justifyContent:"center",position:"relative"},avatarText:{fontSize:15,fontWeight:"900"},liveDot:{position:"absolute",right:-1,bottom:-1,width:12,height:12,borderRadius:6,backgroundColor:"#9ea9a4",borderWidth:2,borderColor:"#fff"},liveDotOn:{backgroundColor:"#29aa71"},domain:{fontSize:9.5,fontWeight:"900",letterSpacing:.9},nameRow:{flexDirection:"row",alignItems:"center",gap:8},employeeName:{fontSize:18,lineHeight:22,fontWeight:"900",color:"#153328"},employeeTitle:{fontSize:12.5,lineHeight:17,fontWeight:"700",color:"#6a7b72",marginTop:2},status:{borderRadius:999,paddingHorizontal:8,paddingVertical:4},statusOn:{backgroundColor:"#e1f3e9"},statusOff:{backgroundColor:"#ecefed"},statusText:{fontSize:9,fontWeight:"900"},statusTextOn:{color:"#21714d"},statusTextOff:{color:"#7b837f"},employeeCopy:{fontSize:13,lineHeight:19,color:"#5f7268",marginTop:13},skillRow:{gap:6,marginTop:11},skill:{backgroundColor:"#f2f6f4",borderWidth:1,borderColor:"#e3eae6",borderRadius:999,paddingHorizontal:9,paddingVertical:5,fontSize:9.5,fontWeight:"800",color:"#587066"},metrics:{flexDirection:"row",gap:6,marginTop:13},metric:{flex:1,backgroundColor:"#f4f7f5",borderRadius:11,padding:8},metricValue:{fontSize:13,fontWeight:"900",color:"#1d382d"},metricLabel:{fontSize:8.5,fontWeight:"800",color:"#74857c",marginTop:2},cardActions:{flexDirection:"row",gap:8,marginTop:13,paddingTop:12,borderTopWidth:1,borderTopColor:"#edf1ef"},secondaryAction:{flex:1,minHeight:44,borderRadius:12,backgroundColor:"#edf2ef",alignItems:"center",justifyContent:"center"},secondaryActionText:{fontSize:12,fontWeight:"900",color:"#52685e"},primaryAction:{flex:1,minHeight:44,borderRadius:12,alignItems:"center",justifyContent:"center"},primaryActionText:{fontSize:12,fontWeight:"900",color:"#fff"},selectedPanel:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe5df",borderRadius:18,padding:15,marginTop:14},selectedEyebrow:{fontSize:9,fontWeight:"900",letterSpacing:1,color:"#6a8377"},selectedTitle:{fontSize:16,fontWeight:"900",color:"#18372a",marginTop:4},selectedCopy:{fontSize:12,color:"#6e7f76",marginTop:3},quickPromptRow:{gap:7,marginTop:12},quickPrompt:{backgroundColor:"#f1f6f3",borderRadius:12,padding:11},quickPromptText:{fontSize:11.5,lineHeight:17,fontWeight:"700",color:"#4d675b"},
 workspaceHero:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dae5df",borderRadius:18,padding:13,flexDirection:"row",alignItems:"center",gap:10,marginBottom:10},workspaceAvatar:{width:48,height:48,borderRadius:15,alignItems:"center",justifyContent:"center"},workspaceAvatarText:{fontSize:14,fontWeight:"900"},workspaceName:{fontSize:17,fontWeight:"900",color:"#18372a",marginTop:2},workspaceRole:{fontSize:10.5,color:"#74847c",marginTop:2},newChat:{minHeight:38,borderRadius:11,backgroundColor:"#edf3f0",paddingHorizontal:10,alignItems:"center",justifyContent:"center"},newChatText:{fontSize:11,fontWeight:"900",color:"#416154"},pickerRow:{gap:8,paddingRight:10,marginBottom:10},agentChip:{minHeight:42,borderRadius:13,borderWidth:1,borderColor:"#d4e0da",backgroundColor:"#fff",paddingHorizontal:14,alignItems:"center",justifyContent:"center"},agentChipText:{fontSize:12,fontWeight:"900",color:"#536b5f"},agentChipTextActive:{color:"white"},miniHeading:{fontSize:9.5,fontWeight:"900",letterSpacing:.9,color:"#75857d",marginTop:3,marginBottom:7},threadRow:{gap:8,paddingRight:10,marginBottom:12},threadCard:{width:190,backgroundColor:"#fff",borderWidth:1,borderColor:"#dfe7e3",borderRadius:13,padding:10},threadCardActive:{borderColor:"#72b495",backgroundColor:"#f4faf7"},threadTitle:{fontSize:11.5,fontWeight:"900",color:"#2b463a"},threadMeta:{fontSize:9.5,color:"#7a8982",marginTop:4},empty:{backgroundColor:"#fff",borderRadius:20,padding:28,alignItems:"center",borderWidth:1,borderColor:"#dce6e1"},emptyIcon:{width:54,height:54,borderRadius:17,textAlign:"center",textAlignVertical:"center",paddingTop:16,backgroundColor:"#e2f2e9",color:"#168b5b",fontWeight:"900",overflow:"hidden"},emptyTitle:{fontSize:17,lineHeight:22,fontWeight:"900",color:"#1d392e",marginTop:10},emptyCopy:{fontSize:13,lineHeight:19,color:"#74837c",textAlign:"center",marginTop:5},emptySmall:{backgroundColor:"#fff",borderRadius:18,padding:20,alignItems:"center",borderWidth:1,borderColor:"#e0e8e4"},
 chatCard:{backgroundColor:"#fff",borderRadius:20,borderWidth:1,borderColor:"#dbe5e0",overflow:"hidden"},contextRow:{flexDirection:"row",gap:6,flexWrap:"wrap",padding:10,borderBottomWidth:1,borderBottomColor:"#edf1ef",backgroundColor:"#f7faf8"},contextPill:{fontSize:9.5,fontWeight:"800",color:"#567165",backgroundColor:"#eaf2ee",paddingHorizontal:8,paddingVertical:5,borderRadius:999},messages:{padding:14,gap:10,minHeight:300},chatWelcome:{padding:18,alignItems:"center"},chatWelcomeTitle:{fontSize:18,fontWeight:"900",color:"#244034",textAlign:"center"},chatWelcomeCopy:{fontSize:12.5,lineHeight:19,color:"#74837c",textAlign:"center",marginTop:6},promptStack:{width:"100%",gap:7,marginTop:14},promptButton:{minHeight:48,borderRadius:12,borderWidth:1,borderColor:"#dce6e1",backgroundColor:"#f8faf9",padding:11,flexDirection:"row",alignItems:"center"},promptText:{flex:1,fontSize:11.5,lineHeight:16,fontWeight:"700",color:"#4d675b"},promptArrow:{fontSize:20,color:"#168c5a"},messageBubble:{maxWidth:"90%",borderRadius:16,padding:12},userBubble:{backgroundColor:"#173d2f",alignSelf:"flex-end"},aiBubble:{backgroundColor:"#eef4f1",alignSelf:"flex-start"},messageWho:{fontSize:9,fontWeight:"900",letterSpacing:.6,color:"#6d8177",marginBottom:4},messageText:{fontSize:13.5,lineHeight:20,color:"#263c32"},messageModel:{fontSize:9.5,color:"#778980",marginTop:6},quickTools:{flexDirection:"row",gap:6,flexWrap:"wrap",paddingHorizontal:11,paddingTop:10,borderTopWidth:1,borderTopColor:"#edf1ef"},quickToolsButton:{},quickToolText:{backgroundColor:"#edf3f0",borderRadius:9,paddingHorizontal:9,paddingVertical:7,fontSize:10.5,fontWeight:"900",color:"#4d675b"},composer:{padding:11,flexDirection:"row",alignItems:"flex-end",gap:9},composerInput:{flex:1,minHeight:50,maxHeight:120,borderWidth:1,borderColor:"#d5dfda",backgroundColor:"#fafcfb",borderRadius:14,paddingHorizontal:12,paddingVertical:11,fontSize:14,lineHeight:20,color:"#1f342b"},sendButton:{minHeight:50,minWidth:66,borderRadius:14,alignItems:"center",justifyContent:"center"},sendText:{color:"white",fontSize:13,fontWeight:"900"},
 formCard:{backgroundColor:"#fff",borderRadius:19,borderWidth:1,borderColor:"#dce6e1",padding:15},fieldLabel:{fontSize:10.5,lineHeight:14,fontWeight:"900",letterSpacing:.8,color:"#687b71",marginBottom:7,marginTop:12},input:{minHeight:50,borderWidth:1,borderColor:"#d5dfda",borderRadius:13,paddingHorizontal:13,fontSize:14,color:"#1f342b",backgroundColor:"#fbfcfc"},textarea:{minHeight:112,textAlignVertical:"top",paddingTop:12},primary:{minHeight:52,borderRadius:14,alignItems:"center",justifyContent:"center",marginTop:14},primaryText:{color:"white",fontSize:14,fontWeight:"900"},buttonDisabled:{opacity:.45},listCard:{backgroundColor:"#fff",borderRadius:18,borderWidth:1,borderColor:"#dde6e2",padding:15},listTop:{flexDirection:"row",alignItems:"center",gap:8},listTitle:{fontSize:15,lineHeight:20,fontWeight:"900",color:"#1d392e",flex:1},listMeta:{fontSize:11.5,lineHeight:17,color:"#718178",marginTop:5},result:{fontSize:13,lineHeight:19,color:"#445b50",marginTop:10},failure:{fontSize:12.5,lineHeight:18,color:"#a3453c",marginTop:8},statePill:{borderRadius:999,paddingHorizontal:8,paddingVertical:5},stateGood:{backgroundColor:"#dff2e8"},stateBad:{backgroundColor:"#fae3df"},stateNeutral:{backgroundColor:"#edf0ef"},stateText:{fontSize:9,fontWeight:"900",color:"#52655c"},safety:{backgroundColor:"#e9f3ee",borderRadius:16,padding:14,marginBottom:14},safetyTitle:{fontSize:14,fontWeight:"900",color:"#214838"},safetyText:{fontSize:12.5,lineHeight:18,color:"#557064",marginTop:4},payload:{fontSize:12,lineHeight:18,color:"#566c61",marginTop:9},actions:{flexDirection:"row",gap:8,marginTop:13,flexWrap:"wrap"},smallPrimary:{minHeight:44,borderRadius:12,backgroundColor:"#168c5a",paddingHorizontal:15,alignItems:"center",justifyContent:"center"},smallPrimaryText:{color:"white",fontSize:12,fontWeight:"900"},smallSecondary:{minHeight:44,borderRadius:12,backgroundColor:"#edf1ef",paddingHorizontal:15,alignItems:"center",justifyContent:"center"},smallSecondaryText:{color:"#5f6e67",fontSize:12,fontWeight:"900"},
 eventStatus:{backgroundColor:"#102f25",borderRadius:18,padding:15,marginBottom:18,flexDirection:"row",alignItems:"center"},eventStatusTitle:{color:"#fff",fontSize:15,fontWeight:"900"},eventStatusCopy:{color:"#abc1b7",fontSize:11.5,marginTop:4},eventSwitch:{marginLeft:"auto",borderRadius:999,paddingHorizontal:10,paddingVertical:7},eventSwitchOn:{backgroundColor:"#1a8d5c"},eventSwitchOff:{backgroundColor:"#5b6762"},eventSwitchText:{color:"white",fontSize:10,fontWeight:"900"},reactionCard:{backgroundColor:"#fff",borderRadius:18,borderWidth:1,borderColor:"#dfe7e3",padding:15},reactionUrgent:{borderLeftWidth:4,borderLeftColor:"#b7483f"},reactionAttention:{borderLeftWidth:4,borderLeftColor:"#d49832"},severityDot:{width:9,height:9,borderRadius:5},severityUrgent:{backgroundColor:"#bf463d"},severityAttention:{backgroundColor:"#d89b35"},severityInfo:{backgroundColor:"#3e8e6b"},severityLabel:{fontSize:9,fontWeight:"900",color:"#6b7a73"},recommend:{backgroundColor:"#f2f6f4",borderRadius:13,padding:11,marginTop:11},recommendLabel:{fontSize:9,fontWeight:"900",color:"#648073",letterSpacing:.6},recommendText:{fontSize:12.5,lineHeight:18,color:"#465f53",marginTop:4},ackButton:{alignSelf:"flex-start",minHeight:44,borderRadius:12,backgroundColor:"#edf7f2",paddingHorizontal:14,alignItems:"center",justifyContent:"center",marginTop:12},ackText:{fontSize:12,fontWeight:"900",color:"#168c5a"},acknowledged:{fontSize:11.5,fontWeight:"800",color:"#668078",marginTop:12}
});
