import { Hono } from "hono";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function camel(r:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(r))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
async function bands(runtime:Runtime,org:string,examId:string){const q=await runtime.db.query(`SELECT gb.* FROM exm_exams e JOIN exm_grade_bands gb ON gb.grading_scale_id=e.grading_scale_id AND gb.organization_id=e.organization_id WHERE e.id=$1 AND e.organization_id=$2 ORDER BY gb.sort_order`,[examId,org]);return q.rows;}
function grade(mark:number|null,max:number,bs:any[]){if(mark==null)return{percentage:null,grade:null,points:null};const pct=Math.round((mark/max)*1000)/10;const fallback=[{grade:"D1",min_mark:90,max_mark:100,points:1},{grade:"D2",min_mark:80,max_mark:89,points:2},{grade:"C3",min_mark:70,max_mark:79,points:3},{grade:"C4",min_mark:60,max_mark:69,points:4},{grade:"C5",min_mark:55,max_mark:59,points:5},{grade:"C6",min_mark:50,max_mark:54,points:6},{grade:"P7",min_mark:45,max_mark:49,points:7},{grade:"P8",min_mark:40,max_mark:44,points:8},{grade:"F9",min_mark:0,max_mark:39,points:9}];const all=bs.length?bs:fallback;const b=all.find((x:any)=>pct>=Number(x.min_mark)&&pct<=Number(x.max_mark))??all[all.length-1];return{percentage:pct,grade:String((b as any).grade),points:Number((b as any).points)};}

export function createExamMarkRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/:examId/marksheet",async c=>{const p=c.get("principal"),classId=c.req.query("classId");if(!classId)throw new AppError(422,"VALIDATION_ERROR","classId is required");const students=await runtime.db.query(`SELECT id,admission_number,student_number,first_name,last_name,current_stream_id FROM school_students WHERE organization_id=$1 AND current_class_id=$2 AND deleted_at IS NULL AND status='active' ORDER BY last_name,first_name`,[p.organizationId,classId]);const subjects=await runtime.db.query(`SELECT es.*,s.code,s.name FROM exm_exam_subjects es JOIN school_subjects s ON s.id=es.subject_id WHERE es.organization_id=$1 AND es.exam_id=$2 AND es.class_id=$3 ORDER BY s.name`,[p.organizationId,c.req.param("examId"),classId]);const marks=await runtime.db.query(`SELECT * FROM exm_marks WHERE organization_id=$1 AND exam_id=$2 AND class_id=$3`,[p.organizationId,c.req.param("examId"),classId]);return c.json({data:{students:students.rows.map(camel),subjects:subjects.rows.map(camel),marks:marks.rows.map(camel)}});});
 r.post("/:examId/marks",requireScope("school:write"),async c=>{const p=c.get("principal"),examId=c.req.param("examId"),b=await c.req.json().catch(()=>({})) as any;if(!b.studentId||!b.subjectId)throw new AppError(422,"VALIDATION_ERROR","studentId and subjectId are required");const es=(await runtime.db.query(`SELECT es.class_id,es.max_mark FROM exm_exam_subjects es JOIN school_students st ON st.current_class_id=es.class_id WHERE es.organization_id=$1 AND es.exam_id=$2 AND es.subject_id=$3 AND st.id=$4 AND st.organization_id=$1`,[p.organizationId,examId,b.subjectId,b.studentId])).rows[0] as any;if(!es)throw new AppError(422,"INVALID_EXAM_SUBJECT","Student is not configured for this exam subject");const raw=b.absent===true?null:Number(b.rawMark);if(raw!=null&&(raw<0||raw>Number(es.max_mark)))throw new AppError(422,"INVALID_MARK","Mark is outside the allowed range");const g=grade(raw,Number(es.max_mark),await bands(runtime,p.organizationId,examId)),previous=(await runtime.db.query(`SELECT raw_mark FROM exm_marks WHERE organization_id=$1 AND exam_id=$2 AND student_id=$3 AND subject_id=$4`,[p.organizationId,examId,b.studentId,b.subjectId])).rows[0] as any;await runtime.db.query(`INSERT INTO exm_marks(id,organization_id,exam_id,student_id,subject_id,class_id,raw_mark,max_mark,percentage,grade,grade_points,absent,exempt,remarks,entered_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(organization_id,exam_id,student_id,subject_id) DO UPDATE SET raw_mark=EXCLUDED.raw_mark,max_mark=EXCLUDED.max_mark,percentage=EXCLUDED.percentage,grade=EXCLUDED.grade,grade_points=EXCLUDED.grade_points,absent=EXCLUDED.absent,exempt=EXCLUDED.exempt,remarks=EXCLUDED.remarks,entered_by=EXCLUDED.entered_by,updated_at=CURRENT_TIMESTAMP`,[createId("mrk"),p.organizationId,examId,b.studentId,b.subjectId,es.class_id,raw,es.max_mark,g.percentage,g.grade,g.points,b.absent===true,b.exempt===true,b.remarks??null,p.userId]);await runtime.db.query(`INSERT INTO exm_mark_audit(id,organization_id,exam_id,student_id,subject_id,old_mark,new_mark,actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[createId("mau"),p.organizationId,examId,b.studentId,b.subjectId,previous?.raw_mark??null,raw,p.userId]);return c.json({data:{studentId:b.studentId,subjectId:b.subjectId,rawMark:raw,...g}});});
 return r;}
