import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function camel(r:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(r))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
const bandSchema=z.object({grade:z.string().min(1).max(12),label:z.string().max(80).nullable().optional(),minMark:z.number().min(0).max(100),maxMark:z.number().min(0).max(100),points:z.number().int().nullable().optional(),colorHex:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#64748B"),sortOrder:z.number().int().min(0).default(0)}).refine(v=>v.minMark<=v.maxMark,{message:"minMark must not exceed maxMark"});

const DEFAULT_CT=[
 {min:4,max:12,text:"Excellent performance! This student has demonstrated outstanding academic ability — Division 1. Keep up the great work."},
 {min:13,max:24,text:"Very good performance — Division 2. This student is performing above average. Consistent effort will lead to even better results."},
 {min:24,max:29,text:"Good performance — Division 3. The student is progressing well. With more effort, higher results are attainable."},
 {min:30,max:34,text:"Fair performance — Division 4. The student needs to work harder, especially in weak subjects. Regular revision is highly encouraged."},
 {min:35,max:99,text:"Below average performance. The student did not meet the minimum standard. Immediate intervention and parental support are needed."},
];
const DEFAULT_HT=[
 {min:4,max:12,text:"Exceptional results — Division 1. We are very proud of this student's achievement. Continue to soar high."},
 {min:13,max:24,text:"Commendable performance — Division 2. This student shows real promise. We encourage continued dedication to studies."},
 {min:24,max:29,text:"Satisfactory performance — Division 3. The school believes this student can achieve much more with sustained commitment."},
 {min:30,max:34,text:"Average performance — Division 4. We urge the student to take studies more seriously and participate actively in class."},
 {min:35,max:99,text:"Ungraded (U). The school calls upon parents and the student to seek immediate academic support and remediation."},
];

export function createExamParityRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.patch("/grade-bands/:id",requireScope("school:write"),async c=>{const s=bandSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid grade band",s.error.flatten());const p=c.get("principal"),v=s.data,id=c.req.param("id");const q=await runtime.db.query(`UPDATE exm_grade_bands SET grade=$1,label=$2,min_mark=$3,max_mark=$4,points=$5,color_hex=$6,sort_order=$7,updated_at=CURRENT_TIMESTAMP WHERE id=$8 AND organization_id=$9 RETURNING *`,[v.grade,v.label??null,v.minMark,v.maxMark,v.points??null,v.colorHex,v.sortOrder,id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"GRADE_BAND_NOT_FOUND","Grade band not found");return c.json({data:camel(q.rows[0] as any)});});
 r.post("/comment-rules/seed-defaults",requireScope("school:write"),async c=>{const p=c.get("principal"),count=await runtime.db.query(`SELECT COUNT(*)::int n FROM exm_comment_rules WHERE organization_id=$1`,[p.organizationId]);if(Number((count.rows[0] as any)?.n??0)>0)return c.json({data:{skipped:true}});const client=await runtime.db.connect();try{await client.query("BEGIN");for(const [type,rows] of [["class_teacher",DEFAULT_CT],["head_teacher",DEFAULT_HT]] as const)for(const x of rows)await client.query(`INSERT INTO exm_comment_rules(id,organization_id,comment_type,min_agg,max_agg,comment_text,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[createId("ecr"),p.organizationId,type,x.min,x.max,x.text,p.userId]);await client.query("COMMIT");return c.json({data:{seeded:true}});}catch(e){await client.query("ROLLBACK");throw e}finally{client.release();}});
 r.delete("/comment-rules/:id",requireScope("school:write"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`UPDATE exm_comment_rules SET active=false,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND active=true RETURNING id`,[c.req.param("id"),p.organizationId]);if(!q.rowCount)throw new AppError(404,"COMMENT_RULE_NOT_FOUND","Comment rule not found");return c.json({data:{deleted:true}});});
 r.post("/:examId/finalize",requireScope("school:write"),async c=>{const p=c.get("principal"),examId=c.req.param("examId"),client=await runtime.db.connect();try{await client.query("BEGIN");const exam=(await client.query(`SELECT status FROM exm_exams WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[examId,p.organizationId])).rows[0] as any;if(!exam)throw new AppError(404,"EXAM_NOT_FOUND","Exam not found");if(exam.status==="published"){await client.query("ROLLBACK");return c.json({data:{id:examId,status:"published",alreadyPublished:true}});}if(exam.status!=="marking")throw new AppError(409,"INVALID_STATUS","Move the examination to marking before final publication.");const rows=await client.query(`SELECT ec.class_id,c.name class_name,COUNT(rc.id)::int cards,COUNT(rc.published_at)::int published_cards FROM exm_exam_classes ec JOIN school_classes c ON c.id=ec.class_id LEFT JOIN exm_report_cards rc ON rc.organization_id=ec.organization_id AND rc.exam_id=ec.exam_id AND rc.class_id=ec.class_id WHERE ec.organization_id=$1 AND ec.exam_id=$2 GROUP BY ec.class_id,c.name ORDER BY c.name`,[p.organizationId,examId]);if(!rows.rowCount)throw new AppError(409,"EXAM_HAS_NO_CLASSES","Enroll at least one class before finalizing this examination.");const pending=(rows.rows as any[]).filter(x=>Number(x.cards)===0||Number(x.cards)!==Number(x.published_cards));if(pending.length)throw new AppError(409,"UNPUBLISHED_CLASS_RESULTS",`Publish the computed report cards for every enrolled class first. Pending: ${pending.map(x=>x.class_name).join(", ")}.`);await client.query(`UPDATE exm_exams SET status='published',updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[p.userId,examId,p.organizationId]);await client.query(`INSERT INTO exm_finalization_events(id,organization_id,exam_id,action,actor_user_id) VALUES($1,$2,$3,'finalized',$4)`,[createId("efe"),p.organizationId,examId,p.userId]);await client.query("COMMIT");return c.json({data:{id:examId,status:"published",classes:rows.rowCount,reportCards:(rows.rows as any[]).reduce((n,x)=>n+Number(x.cards||0),0)}});}catch(e){try{await client.query("ROLLBACK");}catch{}throw e}finally{client.release();}});
 r.post("/:examId/reopen",requireScope("school:write"),async c=>{const p=c.get("principal"),examId=c.req.param("examId"),body=await c.req.json().catch(()=>({})) as any,client=await runtime.db.connect();try{await client.query("BEGIN");const q=await client.query(`UPDATE exm_exams SET status='marking',updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status='published' RETURNING id`,[p.userId,examId,p.organizationId]);if(!q.rowCount)throw new AppError(409,"INVALID_STATUS","Only a published examination can be reopened");await client.query(`INSERT INTO exm_finalization_events(id,organization_id,exam_id,action,actor_user_id,notes) VALUES($1,$2,$3,'reopened',$4,$5)`,[createId("efe"),p.organizationId,examId,p.userId,body.notes??null]);await client.query("COMMIT");return c.json({data:{id:examId,status:"marking"}});}catch(e){await client.query("ROLLBACK");throw e}finally{client.release();}});
 r.get("/:examId/reports/summary",async c=>{const p=c.get("principal"),examId=c.req.param("examId"),classId=c.req.query("classId"),params:any[]=[p.organizationId,examId],where=["organization_id=$1","exam_id=$2"];if(classId){params.push(classId);where.push(`class_id=$${params.length}`);}const q=await runtime.db.query(`SELECT COUNT(*)::int students,ROUND(AVG(total_marks),2)::float8 average_total,ROUND(AVG(aggregate),2)::float8 average_aggregate,COUNT(*) FILTER(WHERE division='1')::int division_1,COUNT(*) FILTER(WHERE division='2')::int division_2,COUNT(*) FILTER(WHERE division='3')::int division_3,COUNT(*) FILTER(WHERE division='4')::int division_4,COUNT(*) FILTER(WHERE division='U')::int ungraded FROM exm_report_cards WHERE ${where.join(" AND ")}`,params);return c.json({data:{...camel(q.rows[0] as any),classId:classId??null}});});
 return r;}
