import { Hono } from "hono";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function camel(r:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(r))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
async function owned(rt:Runtime,org:string,t:string,id?:string|null){if(!id)return;const q=await rt.db.query(`SELECT 1 FROM ${t} WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(422,"INVALID_REFERENCE","Referenced record does not belong to this school");}

export function createExamSetupRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/grading-scales",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT * FROM exm_grading_scales WHERE organization_id=$1 AND active=true ORDER BY is_default DESC,name`,[p.organizationId]);const data=[];for(const row of q.rows){const bands=await runtime.db.query(`SELECT * FROM exm_grade_bands WHERE organization_id=$1 AND grading_scale_id=$2 ORDER BY sort_order,min_mark DESC`,[p.organizationId,(row as any).id]);data.push({...camel(row),bands:bands.rows.map(camel)});}return c.json({data});});
 r.post("/grading-scales/seed-ple",requireScope("school:write"),async c=>{const p=c.get("principal");let row=(await runtime.db.query(`SELECT id FROM exm_grading_scales WHERE organization_id=$1 AND code='PLE'`,[p.organizationId])).rows[0] as any;if(!row){const id=createId("egs");await runtime.db.query(`INSERT INTO exm_grading_scales(id,organization_id,code,name,is_default,created_by) VALUES($1,$2,'PLE','Uganda PLE Scale',true,$3)`,[id,p.organizationId,p.userId]);row={id};const bands:[[string,number,number,number]]|any=[["D1",90,100,1],["D2",80,89,2],["C3",70,79,3],["C4",60,69,4],["C5",55,59,5],["C6",50,54,6],["P7",45,49,7],["P8",40,44,8],["F9",0,39,9]];for(let i=0;i<bands.length;i++){const b=bands[i];await runtime.db.query(`INSERT INTO exm_grade_bands(id,organization_id,grading_scale_id,grade,min_mark,max_mark,points,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[createId("egb"),p.organizationId,id,b[0],b[1],b[2],b[3],i+1]);}}return c.json({data:{id:row.id}},201);});
 r.get("/:examId/classes",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT ec.*,cl.name class_name,st.name stream_name FROM exm_exam_classes ec JOIN school_classes cl ON cl.id=ec.class_id LEFT JOIN school_streams st ON st.id=ec.stream_id WHERE ec.organization_id=$1 AND ec.exam_id=$2 ORDER BY cl.name,st.name`,[p.organizationId,c.req.param("examId")]);return c.json({data:q.rows.map(camel)});});
 r.post("/:examId/classes",requireScope("school:write"),async c=>{const p=c.get("principal"),examId=c.req.param("examId"),b=await c.req.json().catch(()=>({})) as any;if(!b.classId)throw new AppError(422,"VALIDATION_ERROR","classId is required");await owned(runtime,p.organizationId,"exm_exams",examId);await owned(runtime,p.organizationId,"school_classes",b.classId);await owned(runtime,p.organizationId,"school_streams",b.streamId);const id=createId("exc");await runtime.db.query(`INSERT INTO exm_exam_classes(id,organization_id,exam_id,class_id,stream_id,created_by) VALUES($1,$2,$3,$4,$5,$6)`,[id,p.organizationId,examId,b.classId,b.streamId??null,p.userId]);return c.json({data:{id,examId,...b}},201);});
 r.get("/:examId/subjects",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT es.*,s.code subject_code,s.name subject_name FROM exm_exam_subjects es JOIN school_subjects s ON s.id=es.subject_id WHERE es.organization_id=$1 AND es.exam_id=$2 ORDER BY s.name`,[p.organizationId,c.req.param("examId")]);return c.json({data:q.rows.map(camel)});});
 r.post("/:examId/subjects",requireScope("school:write"),async c=>{const p=c.get("principal"),examId=c.req.param("examId"),b=await c.req.json().catch(()=>({})) as any;if(!b.classId||!b.subjectId)throw new AppError(422,"VALIDATION_ERROR","classId and subjectId are required");await owned(runtime,p.organizationId,"exm_exams",examId);await owned(runtime,p.organizationId,"school_classes",b.classId);await owned(runtime,p.organizationId,"school_subjects",b.subjectId);const id=createId("exs");await runtime.db.query(`INSERT INTO exm_exam_subjects(id,organization_id,exam_id,class_id,subject_id,max_mark,compulsory,aggregate_subject,weight) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,examId,b.classId,b.subjectId,Number(b.maxMark??100),b.compulsory!==false,b.aggregateSubject!==false,Number(b.weight??1)]);return c.json({data:{id,examId,...b}},201);});
 return r;}
