import { createHash } from "node:crypto";
import { Document,Packer,Paragraph,HeadingLevel } from "docx";
import PptxGenJS from "pptxgenjs";
import * as XLSX from "xlsx";
import { PDFDocument,StandardFonts,rgb } from "pdf-lib";
import type { AgentDocumentGenerateInput,AgentDocumentArtifact,AgentDocumentService } from "../src/types";

const MIME={docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",xlsx:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",pptx:"application/vnd.openxmlformats-officedocument.presentationml.presentation"} as const;
function safe(value:string){return value.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,140)||"document";}
function textLines(value:unknown,depth=0):string[]{if(depth>5)return[String(value??"")];if(value==null)return[];if(["string","number","boolean"].includes(typeof value))return[String(value)];if(Array.isArray(value))return value.flatMap(v=>textLines(v,depth+1).map(x=>`• ${x}`));return Object.entries(value as Record<string,unknown>).flatMap(([k,v])=>{const child=textLines(v,depth+1);return child.length?[k.replace(/[_-]+/g," "),...child.map(x=>`  ${x}`)]:[];});}
async function renderPdf(title:string,spec:Record<string,unknown>){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([595.28,841.89]),y=790;const draw=(line:string,isBold=false)=>{const f=isBold?bold:font,size=isBold?14:10,max=88;for(let i=0;i<line.length||i===0;i+=max){if(y<60){page=pdf.addPage([595.28,841.89]);y=790;}page.drawText(line.slice(i,i+max)||" ",{x:54,y,font:f,size,color:rgb(.08,.08,.08)});y-=isBold?20:14;}};draw(title,true);y-=6;for(const line of textLines(spec))draw(line);return Buffer.from(await pdf.save());}
function docxBuffer(title:string,spec:any){const children=[new Paragraph({text:title,heading:HeadingLevel.TITLE})];const sections=Array.isArray(spec.sections)?spec.sections:null;if(sections){for(const section of sections){if(section.heading)children.push(new Paragraph({text:String(section.heading),heading:HeadingLevel.HEADING_1}));for(const p of section.paragraphs||[])children.push(new Paragraph(String(p)));for(const b of section.bullets||[])children.push(new Paragraph({text:String(b),bullet:{level:0}}));}}else for(const line of textLines(spec))children.push(new Paragraph(line));return Packer.toBuffer(new Document({sections:[{children}]}));}
function xlsxBuffer(spec:any){const wb=XLSX.utils.book_new(),sheets=Array.isArray(spec.sheets)&&spec.sheets.length?spec.sheets:[{name:"Sheet1",rows:Array.isArray(spec.rows)?spec.rows:[["Value"],[JSON.stringify(spec)]]}];for(const item of sheets.slice(0,30)){const rows=Array.isArray(item.rows)?item.rows:[["Value"]],ws=XLSX.utils.aoa_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,String(item.name||`Sheet${wb.SheetNames.length+1}`).slice(0,31));}return Buffer.from(XLSX.write(wb,{type:"buffer",bookType:"xlsx"}) as any);}
async function pptxBuffer(title:string,spec:any){const pptx=new PptxGenJS();pptx.layout="LAYOUT_WIDE";const slides=Array.isArray(spec.slides)&&spec.slides.length?spec.slides:[{title,bullets:textLines(spec)}];for(const item of slides.slice(0,60)){const slide=pptx.addSlide();slide.addText(String(item.title||title),{x:.6,y:.4,w:12,h:.6,fontSize:24,bold:true});const bullets=Array.isArray(item.bullets)?item.bullets:(item.body?[String(item.body)]:[]);if(bullets.length)slide.addText(bullets.map((t:string)=>({text:String(t),options:{bullet:{indent:18}}})),{x:.8,y:1.3,w:11.6,h:5.5,fontSize:18,breakLine:true});}const out=await pptx.write({outputType:"nodebuffer"} as any);return Buffer.from(out as any);}
export function createAgentDocumentService(bucket:any):AgentDocumentService{return{async generate(input:AgentDocumentGenerateInput):Promise<AgentDocumentArtifact>{const spec=input.spec||{},title=String(input.title||"Ledgerly document").trim();let source:Buffer;if(input.format==="docx")source=await docxBuffer(title,spec);else if(input.format==="xlsx")source=xlsxBuffer(spec);else source=await pptxBuffer(title,spec);const pdf=await renderPdf(title,spec),base=`agentic-documents/${input.organizationId}/${input.documentId}/v1`,sourceKey=`${base}/${safe(title)}.${input.format}`,pdfKey=`${base}/${safe(title)}.pdf`,checksum=createHash("sha256").update(source).digest("hex");await bucket.put(sourceKey,source,{httpMetadata:{contentType:MIME[input.format],contentDisposition:`attachment; filename=\"${safe(title)}.${input.format}\"`},customMetadata:{organizationId:input.organizationId,documentId:input.documentId,agentKey:input.agentKey,checksum}});await bucket.put(pdfKey,pdf,{httpMetadata:{contentType:"application/pdf",contentDisposition:`inline; filename=\"${safe(title)}.pdf\"`},customMetadata:{organizationId:input.organizationId,documentId:input.documentId,agentKey:input.agentKey}});return{sourceObjectKey:sourceKey,pdfObjectKey:pdfKey,sourceMimeType:MIME[input.format],sourceSizeBytes:source.length,pdfSizeBytes:pdf.length,checksumSha256:checksum};}};}
