import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const projectSchema=z.object({code:z.string().min(1).max(40),name:z.string().min(2).max(160),description:z.string().max(2000).nullable().optional(),ownerUserId:z.string().nullable().optional(),status:z.enum(['planned','active','on_hold','completed','cancelled']).default('active'),startDate:z.string().nullable().optional(),dueDate:z.string().nullable().optional()});
const taskSchema=z.object({projectId:z.string().nullable().optional(),taskNumber:z.string().min(1).max(60),title:z.string().min(2).max(220),description:z.string().max(5000).nullable().optional(),priority:z.enum(['low','normal','high','urgent']).default('normal'),dueAt:z.string().nullable().optional(),assigneeUserIds:z.array(z.string()).max(100).default([])});

async function validateUsers(runtime:Runtime,org:string,userIds:string[]){if(!userIds.length)return;const q=await runtime.db.query(`SELECT DISTINCT m.user_id FROM memberships m WHERE m.organization_id=$1 AND m.user_id=ANY($2::text[])`,[org,[...new Set(userIds)]]);if(q.rowCount!==new Set(userIds).size)throw new AppError(422,'INVALID_ASSIGNEE','Every assignee must belong to this organization');}

export function createWorkRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('work:read'));
 r.get('/manifest',c=>c.json({data:{key:'tasks-work',version:'1.0.0',features:['projects','tasks','assignees','comments','dashboard']}}));
 r.get('/dashboard',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT COUNT(*) FILTER(WHERE archived_at IS NULL)::int total,COUNT(*) FILTER(WHERE archived_at IS NULL AND status='done')::int done,COUNT(*) FILTER(WHERE archived_at IS NULL AND status='blocked')::int blocked,COUNT(*) FILTER(WHERE archived_at IS NULL AND due_at<CURRENT_TIMESTAMP AND status NOT IN ('done','cancelled'))::int overdue FROM work_tasks WHERE organization_id=$1`,[p.organizationId]);return c.json({data:q.rows[0]});});
 r.get('/projects',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT p.*,u.display_name AS owner_name FROM work_projects p LEFT JOIN users u ON u.id=p.owner_user_id WHERE p.organization_id=$1 ORDER BY p.created_at DESC`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/projects',requireScope('work:write'),async c=>{const s=projectSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid project',s.error.flatten());const p=c.get('principal'),v=s.data;if(v.ownerUserId)await validateUsers(runtime,p.organizationId,[v.ownerUserId]);const id=createId('wpr');await runtime.db.query(`INSERT INTO work_projects(id,organization_id,code,name,description,owner_user_id,status,start_date,due_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,p.organizationId,v.code.toUpperCase(),v.name,v.description??null,v.ownerUserId??null,v.status,v.startDate??null,v.dueDate??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.get('/tasks',async c=>{const p=c.get('principal'),status=c.req.query('status')??null,projectId=c.req.query('projectId')??null,mine=c.req.query('mine')==='true';const q=await runtime.db.query(`SELECT t.*,p.name AS project_name,COALESCE(jsonb_agg(jsonb_build_object('userId',a.user_id,'name',u.display_name)) FILTER(WHERE a.user_id IS NOT NULL),'[]'::jsonb) assignees FROM work_tasks t LEFT JOIN work_projects p ON p.id=t.project_id LEFT JOIN work_task_assignees a ON a.task_id=t.id AND a.organization_id=t.organization_id LEFT JOIN users u ON u.id=a.user_id WHERE t.organization_id=$1 AND t.archived_at IS NULL AND ($2::text IS NULL OR t.status=$2) AND ($3::text IS NULL OR t.project_id=$3) AND ($4::boolean=false OR EXISTS(SELECT 1 FROM work_task_assignees ma WHERE ma.organization_id=t.organization_id AND ma.task_id=t.id AND ma.user_id=$5)) GROUP BY t.id,p.name ORDER BY t.updated_at DESC LIMIT 500`,[p.organizationId,status,projectId,mine,p.userId]);return c.json({data:q.rows});});
 r.post('/tasks',requireScope('work:write'),async c=>{const s=taskSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid task',s.error.flatten());const p=c.get('principal'),v=s.data;if(v.projectId){const q=await runtime.db.query(`SELECT 1 FROM work_projects WHERE id=$1 AND organization_id=$2`,[v.projectId,p.organizationId]);if(!q.rowCount)throw new AppError(422,'INVALID_PROJECT','Project does not belong to this organization');}await validateUsers(runtime,p.organizationId,v.assigneeUserIds);const id=createId('wts'),client=await runtime.db.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO work_tasks(id,organization_id,project_id,task_number,title,description,priority,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.projectId??null,v.taskNumber,v.title,v.description??null,v.priority,v.dueAt??null,p.userId]);for(const uid of new Set(v.assigneeUserIds))await client.query(`INSERT INTO work_task_assignees(organization_id,task_id,user_id,assigned_by) VALUES($1,$2,$3,$4)`,[p.organizationId,id,uid,p.userId]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}return c.json({data:{id,status:'todo',...v}},201);});
 r.patch('/tasks/:id',requireScope('work:write'),async c=>{const s=z.object({status:z.enum(['todo','in_progress','blocked','review','done','cancelled']).optional(),priority:z.enum(['low','normal','high','urgent']).optional(),title:z.string().min(2).max(220).optional(),description:z.string().max(5000).nullable().optional(),dueAt:z.string().nullable().optional()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid task update',s.error.flatten());const p=c.get('principal'),v=s.data,q=await runtime.db.query(`UPDATE work_tasks SET title=COALESCE($1,title),description=CASE WHEN $2::boolean THEN $3 ELSE description END,status=COALESCE($4,status),priority=COALESCE($5,priority),due_at=CASE WHEN $6::boolean THEN $7::timestamptz ELSE due_at END,completed_at=CASE WHEN $4='done' THEN COALESCE(completed_at,CURRENT_TIMESTAMP) WHEN $4 IS NOT NULL AND $4<>'done' THEN NULL ELSE completed_at END,updated_at=CURRENT_TIMESTAMP WHERE id=$8 AND organization_id=$9 AND archived_at IS NULL RETURNING *`,[v.title??null,Object.hasOwn(v,'description'),v.description??null,v.status??null,v.priority??null,Object.hasOwn(v,'dueAt'),v.dueAt??null,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'NOT_FOUND','Task not found');return c.json({data:q.rows[0]});});
 r.post('/tasks/:id/assignees',requireScope('work:write'),async c=>{const s=z.object({userIds:z.array(z.string()).min(1).max(100)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid assignees',s.error.flatten());const p=c.get('principal'),taskId=c.req.param('id'),exists=await runtime.db.query(`SELECT 1 FROM work_tasks WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL`,[taskId,p.organizationId]);if(!exists.rowCount)throw new AppError(404,'NOT_FOUND','Task not found');await validateUsers(runtime,p.organizationId,s.data.userIds);for(const uid of new Set(s.data.userIds))await runtime.db.query(`INSERT INTO work_task_assignees(organization_id,task_id,user_id,assigned_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[p.organizationId,taskId,uid,p.userId]);return c.json({data:{taskId,userIds:[...new Set(s.data.userIds)]}});});
 r.get('/tasks/:id/comments',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT c.*,u.display_name AS user_name FROM work_task_comments c LEFT JOIN users u ON u.id=c.user_id WHERE c.organization_id=$1 AND c.task_id=$2 ORDER BY c.created_at`,[p.organizationId,c.req.param('id')]);return c.json({data:q.rows});});
 r.post('/tasks/:id/comments',requireScope('work:write'),async c=>{const s=z.object({body:z.string().min(1).max(5000)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid comment',s.error.flatten());const p=c.get('principal'),taskId=c.req.param('id'),exists=await runtime.db.query(`SELECT 1 FROM work_tasks WHERE id=$1 AND organization_id=$2`,[taskId,p.organizationId]);if(!exists.rowCount)throw new AppError(404,'NOT_FOUND','Task not found');const id=createId('wtc');await runtime.db.query(`INSERT INTO work_task_comments(id,organization_id,task_id,user_id,body) VALUES($1,$2,$3,$4,$5)`,[id,p.organizationId,taskId,p.userId,s.data.body]);return c.json({data:{id,taskId,body:s.data.body}},201);});
 return r;}
