import { createId } from "../../../src/lib/ids";
import type { Env } from "../../../src/types";
import { executeTool as baseExecute,openAiTools as baseTools } from "./system-tools-v16";
import type { ToolContext } from "./tools-v14";
import { compileSafeQuery,intelligenceCatalog,type SafeQueryPlan } from "./intelligence-registry";

const NAMES=["discover_data_capabilities","safe_data_query","school_intelligence_snapshot","prepare_fee_payment","pending_action_status"] as const;
type IntelligenceTool=typeof NAMES[number];

const SPECS:Record<IntelligenceTool,any>={
 discover_data_capabilities:{type:"function",name:"discover_data_capabilities",strict:false,description:"Discover the Ledgerly semantic data entities, fields, metrics and governed actions available to this AI employee. Use this when a requested summary/query is unfamiliar instead of guessing table or field names.",parameters:{type:"object",properties:{query:{type:"string",description:"Optional concept such as lesson plans, attendance, arrears or finance"}},additionalProperties:false}},
 safe_data_query:{type:"function",name:"safe_data_query",strict:false,description:"Run a read-only structured query through Ledgerly's safe query planner. You choose semantic entities/fields/metrics/filters; Ledgerly validates them, injects the school tenant, binds values and generates SQL. Never provide SQL text.",parameters:{type:"object",properties:{entity:{type:"string"},fields:{type:"array",items:{type:"string"}},filters:{type:"array",items:{type:"object",properties:{field:{type:"string"},operator:{type:"string",enum:["eq","neq","contains","starts_with","gt","gte","lt","lte","in","between","is_null"]},value:{}},required:["field","operator"],additionalProperties:false}},metrics:{type:"array",items:{type:"string"}},groupBy:{type:"array",items:{type:"string"}},orderBy:{type:"array",items:{type:"object",properties:{field:{type:"string"},direction:{type:"string",enum:["asc","desc"]}},required:["field"],additionalProperties:false}},limit:{type:"integer",minimum:1,maximum:150}},required:["entity"],additionalProperties:false}},
 school_intelligence_snapshot:{type:"function",name:"school_intelligence_snapshot",strict:false,description:"Build a compact server-calculated school intelligence snapshot. PostgreSQL/D1 performs counts, sums and rates locally; use the result for analysis instead of pulling thousands of raw rows into the model.",parameters:{type:"object",properties:{days:{type:"integer",minimum:1,maximum:365,description:"Trend window for dated sections; default 30"},sections:{type:"array",items:{type:"string",enum:["students","fees","attendance","finance","academics","hr"]}}},additionalProperties:false}},
 prepare_fee_payment:{type:"function",name:"prepare_fee_payment",strict:false,description:"Safely prepare a school-fee receipt. Resolves learner and payment method, collects all missing/ambiguous details in a pending intent, and only when exact prepares a previewed Action Center proposal. It never records money itself.",parameters:{type:"object",properties:{pendingIntentId:{type:"string"},studentId:{type:"string"},studentQuery:{type:"string",description:"Name, admission number or student number"},amountMinor:{type:"integer",minimum:1,description:"Amount in the currency's smallest unit; for UGX this is the UGX amount"},paymentMethodId:{type:"string"},paymentMethodQuery:{type:"string",description:"For example cash, bank, mobile money or method name"},paymentDate:{type:"string",description:"YYYY-MM-DD; if omitted Ledgerly uses the school's local current date"},reference:{type:"string"},notes:{type:"string"}},additionalProperties:false}},
 pending_action_status:{type:"function",name:"pending_action_status",strict:false,description:"List unresolved clarification intents for this conversation so a follow-up answer can continue the same action instead of starting over.",parameters:{type:"object",properties:{intentType:{type:"string"}},additionalProperties:false}}
};

function allowed(agent:any,name:IntelligenceTool,requested?:string[]|null){if(!agent.tools.includes(name))return false;if(!requested)return true;return requested.includes(name);}
export function openAiTools(agent:any,requested?:string[]|null){return[...baseTools(agent,requested),...NAMES.filter(name=>allowed(agent,name,requested)).map(name=>SPECS[name])];}
function obj(raw:unknown){return(raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:{}) as Record<string,any>;}
function safeJson(value:string|null|undefined,fallback:any){try{return value?JSON.parse(value):fallback;}catch{return fallback;}}
function isoDate(date:Date){return date.toISOString().slice(0,10);}
async function orgContext(db:D1Database,org:string){return await db.prepare("SELECT base_currency AS baseCurrency,timezone FROM organizations WHERE id=?").bind(org).first<{baseCurrency:string;timezone:string}>()||{baseCurrency:"UGX",timezone:"Africa/Kampala"};}
function localDate(timezone:string){try{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),get=(type:string)=>parts.find(p=>p.type===type)?.value||"";return`${get("year")}-${get("month")}-${get("day")}`;}catch{return isoDate(new Date());}}
function startDate(days:number){const d=new Date();d.setUTCDate(d.getUTCDate()-Math.max(0,days-1));return isoDate(d);}

async function runPlan(ctx:ToolContext,plan:SafeQueryPlan,audit=true){
 const compiled=compileSafeQuery(ctx.agent.key,ctx.principal.organizationId,plan),auditId=createId("aiq");
 if(audit)await ctx.db.prepare("INSERT INTO ae_query_audit(id,organization_id,conversation_id,agent_key,entity_key,plan_json,status,created_by) VALUES(?,?,?,?,?,?,'running',?)").bind(auditId,ctx.principal.organizationId,ctx.conversationId,ctx.agent.key,compiled.entity,JSON.stringify(plan),ctx.principal.userId).run();
 try{const rows=await ctx.db.prepare(compiled.sql).bind(...compiled.bindings).all<Record<string,unknown>>();if(audit)await ctx.db.prepare("UPDATE ae_query_audit SET status='succeeded',row_count=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(rows.results.length,auditId,ctx.principal.organizationId).run();return{entity:compiled.entity,rowCount:rows.results.length,rows:rows.results,limit:compiled.limit};}
 catch(error){const message=error instanceof Error?error.message:String(error);if(audit)await ctx.db.prepare("UPDATE ae_query_audit SET status='failed',error_text=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(message.slice(0,2000),auditId,ctx.principal.organizationId).run().catch(()=>undefined);throw error;}
}

async function snapshot(ctx:ToolContext,args:Record<string,any>){
 const requested=Array.isArray(args.sections)?args.sections.map(String):["students","fees","attendance","finance","academics","hr"],days=Math.max(1,Math.min(Number(args.days||30),365)),from=startDate(days),out:Record<string,unknown>={window:{days,from,to:isoDate(new Date())}};
 const can=(entity:string)=>intelligenceCatalog(ctx.agent.key).some(e=>e.key===entity);
 if(requested.includes("students")&&can("students"))out.students=(await runPlan(ctx,{entity:"students",metrics:["count"],limit:1},false)).rows[0]||{};
 if(requested.includes("fees")&&can("fee_balances"))out.fees=(await runPlan(ctx,{entity:"fee_balances",metrics:["studentCount","billedTotalMinor","paidTotalMinor","outstandingTotalMinor"],limit:1},false)).rows[0]||{};
 if(requested.includes("attendance")&&can("student_attendance"))out.attendance=(await runPlan(ctx,{entity:"student_attendance",filters:[{field:"attendanceDate",operator:"gte",value:from}],metrics:["count","presentCount","absentCount","lateCount","attendanceRate"],limit:1},false)).rows[0]||{};
 if(requested.includes("finance")&&can("finance_activity"))out.finance=(await runPlan(ctx,{entity:"finance_activity",filters:[{field:"postingDate",operator:"gte",value:from}],groupBy:["accountType"],metrics:["lineCount","debitTotalMinor","creditTotalMinor"],orderBy:[{field:"accountType",direction:"asc"}],limit:30},false)).rows;
 if(requested.includes("academics")&&can("lesson_plans"))out.academics={lessonPlansByStatus:(await runPlan(ctx,{entity:"lesson_plans",filters:[{field:"lessonDate",operator:"gte",value:from}],groupBy:["status"],metrics:["count"],orderBy:[{field:"status",direction:"asc"}],limit:30},false)).rows};
 if(requested.includes("hr")&&can("staff")){const staff=(await runPlan(ctx,{entity:"staff",metrics:["count"],limit:1},false)).rows[0]||{},attendance=can("staff_attendance")?(await runPlan(ctx,{entity:"staff_attendance",filters:[{field:"attendanceDate",operator:"gte",value:from}],metrics:["count","presentCount","absentCount","lateCount","avgMinutesLate"],limit:1},false)).rows[0]||{}:{};out.hr={staff,attendance};}
 await ctx.db.prepare("INSERT INTO ae_query_audit(id,organization_id,conversation_id,agent_key,entity_key,plan_json,row_count,status,created_by,completed_at) VALUES(?,?,?,?,?,?,?,'succeeded',?,CURRENT_TIMESTAMP)").bind(createId("aiq"),ctx.principal.organizationId,ctx.conversationId,ctx.agent.key,"school_intelligence_snapshot",JSON.stringify({days,sections:requested}),Object.keys(out).length,ctx.principal.userId).run();
 return{calculatedBy:"ledgerly_server",aiDidNotCalculateFigures:true,...out};
}

async function latestPending(ctx:ToolContext,id?:string){if(id)return await ctx.db.prepare("SELECT * FROM ae_pending_intents WHERE id=? AND organization_id=? AND conversation_id=? AND agent_key=?").bind(id,ctx.principal.organizationId,ctx.conversationId,ctx.agent.key).first<any>();return await ctx.db.prepare("SELECT * FROM ae_pending_intents WHERE organization_id=? AND conversation_id=? AND agent_key=? AND intent_type='finance.fee_payment' AND status='awaiting_information' ORDER BY updated_at DESC LIMIT 1").bind(ctx.principal.organizationId,ctx.conversationId,ctx.agent.key).first<any>();}
function studentTokens(q:string){return q.trim().toLowerCase().split(/\s+/).filter(Boolean).slice(0,6);}
async function studentCandidates(db:D1Database,org:string,query:string){
 const tokens=studentTokens(query);if(!tokens.length)return[];const name=`LOWER(COALESCE(s.first_name,'')||' '||COALESCE(s.middle_name,'')||' '||COALESCE(s.last_name,''))`,where:string[]=[],bind:unknown[]=[org];for(const token of tokens){where.push(`(${name} LIKE ? OR LOWER(COALESCE(s.admission_number,'')) LIKE ? OR LOWER(COALESCE(s.student_number,'')) LIKE ?)`);bind.push(`%${token}%`,`%${token}%`,`%${token}%`);}const rows=await db.prepare(`SELECT s.id,s.admission_number AS "admissionNumber",s.student_number AS "studentNumber",TRIM(COALESCE(s.first_name,'')||' '||COALESCE(s.middle_name||' ','')||COALESCE(s.last_name,'')) AS "studentName",c.name AS "className",st.name AS "streamName" FROM school_students s LEFT JOIN school_classes c ON c.id=s.current_class_id AND c.organization_id=s.organization_id LEFT JOIN school_streams st ON st.id=s.current_stream_id AND st.organization_id=s.organization_id WHERE s.organization_id=? AND s.deleted_at IS NULL AND s.status='active' AND ${where.join(" AND ")} ORDER BY s.admission_number LIMIT 12`).bind(...bind).all<any>();return rows.results;
}
async function exactStudent(db:D1Database,org:string,id:string){return await db.prepare(`SELECT s.id,s.admission_number AS "admissionNumber",s.student_number AS "studentNumber",TRIM(COALESCE(s.first_name,'')||' '||COALESCE(s.middle_name||' ','')||COALESCE(s.last_name,'')) AS "studentName",c.name AS "className",st.name AS "streamName" FROM school_students s LEFT JOIN school_classes c ON c.id=s.current_class_id AND c.organization_id=s.organization_id LEFT JOIN school_streams st ON st.id=s.current_stream_id AND st.organization_id=s.organization_id WHERE s.id=? AND s.organization_id=? AND s.deleted_at IS NULL AND s.status='active'`).bind(id,org).first<any>();}
async function methodCandidates(db:D1Database,org:string,query:string){const q=`%${query.trim().toLowerCase()}%`;return(await db.prepare("SELECT id,name,method_type AS \"methodType\" FROM school_payment_methods WHERE organization_id=? AND active=1 AND (LOWER(name) LIKE ? OR LOWER(method_type) LIKE ?) ORDER BY name LIMIT 12").bind(org,q,q).all<any>()).results;}
async function exactMethod(db:D1Database,org:string,id:string){return await db.prepare("SELECT id,name,method_type AS \"methodType\" FROM school_payment_methods WHERE id=? AND organization_id=? AND active=1").bind(id,org).first<any>();}

async function savePending(ctx:ToolContext,current:any,draft:Record<string,unknown>,missing:string[],candidates:Record<string,unknown>,prompt:string){
 const id=current?.id||createId("api");if(current)await ctx.db.prepare("UPDATE ae_pending_intents SET draft_json=?,missing_fields_json=?,candidates_json=?,clarification_prompt=?,status='awaiting_information',updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(JSON.stringify(draft),JSON.stringify(missing),JSON.stringify(candidates),prompt,id,ctx.principal.organizationId).run();else await ctx.db.prepare("INSERT INTO ae_pending_intents(id,organization_id,conversation_id,agent_key,intent_type,status,draft_json,missing_fields_json,candidates_json,clarification_prompt,created_by) VALUES(?,?,?,?,?,'awaiting_information',?,?,?,?,?)").bind(id,ctx.principal.organizationId,ctx.conversationId,ctx.agent.key,"finance.fee_payment",JSON.stringify(draft),JSON.stringify(missing),JSON.stringify(candidates),prompt,ctx.principal.userId).run();return id;
}

async function prepareFeePayment(ctx:ToolContext & {env?:Env},raw:unknown){
 if(ctx.agent.key!=="bursar"&&ctx.agent.key!=="headteacher")throw new Error("Only the Bursar or Head Teacher AI may prepare fee payments");const args=obj(raw),current=await latestPending(ctx,args.pendingIntentId),draft:Record<string,any>={...safeJson(current?.draft_json,{})};for(const key of ["studentId","studentQuery","amountMinor","paymentMethodId","paymentMethodQuery","paymentDate","reference","notes"])if(Object.prototype.hasOwnProperty.call(args,key)&&args[key]!==undefined&&args[key]!==null&&args[key]!=="")draft[key]=args[key];
 const candidates:Record<string,unknown>={},missing:string[]=[],questions:string[]=[];let student:any=null,method:any=null;
 if(draft.studentId){student=await exactStudent(ctx.db,ctx.principal.organizationId,String(draft.studentId));if(!student){delete draft.studentId;missing.push("studentId");questions.push("The selected learner no longer exists or is inactive. Which student should receive this fee payment?");}}
 if(!student&&draft.studentQuery){const found=await studentCandidates(ctx.db,ctx.principal.organizationId,String(draft.studentQuery));candidates.students=found;if(found.length===1){student=found[0];draft.studentId=student.id;}else{missing.push("studentId");questions.push(found.length?`I found ${found.length} active students matching '${draft.studentQuery}'. Which one do you mean?`:`I could not find an active student matching '${draft.studentQuery}'. Give an admission/student number or a more specific name.`);}}
 if(!student&&!draft.studentQuery){missing.push("studentId");questions.push("Which student paid? Give the name, admission number or student number.");}
 const amount=Number(draft.amountMinor||0);if(!Number.isInteger(amount)||amount<=0){missing.push("amountMinor");questions.push("How much was paid?");}
 if(draft.paymentMethodId){method=await exactMethod(ctx.db,ctx.principal.organizationId,String(draft.paymentMethodId));if(!method){delete draft.paymentMethodId;missing.push("paymentMethodId");questions.push("That payment method is unavailable. Which active method was used?");}}
 if(!method&&draft.paymentMethodQuery){const found=await methodCandidates(ctx.db,ctx.principal.organizationId,String(draft.paymentMethodQuery));candidates.paymentMethods=found;if(found.length===1){method=found[0];draft.paymentMethodId=method.id;}else{missing.push("paymentMethodId");questions.push(found.length?`I found ${found.length} payment methods matching '${draft.paymentMethodQuery}'. Which one was used?`:`I could not find an active payment method matching '${draft.paymentMethodQuery}'. Which configured payment method was used?`);}}
 if(!method&&!draft.paymentMethodQuery){missing.push("paymentMethodId");questions.push("How was the payment received (for example cash, bank or mobile money)?");}
 const uniqueMissing=[...new Set(missing)];if(uniqueMissing.length){const prompt=questions.join(" "),id=await savePending(ctx,current,draft,uniqueMissing,candidates,prompt);return{needsClarification:true,pendingIntentId:id,missingFields:uniqueMissing,questions,candidates,known:{student,amountMinor:amount>0?amount:null,paymentMethod:method},executed:false,message:"No Ledgerly data has been changed. Ask the user all listed clarification questions together."};}
 const org=await orgContext(ctx.db,ctx.principal.organizationId),paymentDate=String(draft.paymentDate||localDate(org.timezone)),pendingId=current?.id||await savePending(ctx,null,draft,[],{},""),preview={action:"Record and post school fee receipt",student:{id:student.id,name:student.studentName,admissionNumber:student.admissionNumber,className:student.className,streamName:student.streamName},amountMinor:amount,currency:org.baseCurrency,paymentMethod:{id:method.id,name:method.name,type:method.methodType},paymentDate,reference:draft.reference||null,effects:["Create a school fee receipt through the normal fee service","Post the Ledgerly payment and accounting entries","Auto-allocate against the student's oldest open school-fee invoices","Update the student's fee balance and installment allocations","Create/finalize the receipt archive and audit trail"]};
 const body={studentId:student.id,paymentMethodId:method.id,paymentDate,amountMinor:amount,reference:draft.reference||null,notes:draft.notes||null,allocations:[],autoAllocate:true,autoPost:true,idempotencyKey:`ai-fee-${pendingId}`};
 const prepared:any=await baseExecute(ctx,"prepare_system_action",{method:"POST",path:"/api/v1/school/fees/receipts",bodyJson:JSON.stringify(body),title:`Fee payment · ${student.studentName}`,summary:`Proposed ${org.baseCurrency} ${amount.toLocaleString()} fee receipt for ${student.studentName} (${student.admissionNumber||student.studentNumber||student.id}) via ${method.name} on ${paymentDate}. Nothing has been changed yet.`,changePreviewJson:JSON.stringify(preview)});
 const actionId=prepared?.action?.id||null;await ctx.db.prepare("UPDATE ae_pending_intents SET status='action_prepared',draft_json=?,missing_fields_json='[]',candidates_json='{}',clarification_prompt=NULL,action_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(JSON.stringify({...draft,paymentDate}),actionId,pendingId,ctx.principal.organizationId).run();return{needsClarification:false,pendingIntentId:pendingId,executed:false,nothingChangedYet:true,preview,action:prepared?.action||null,message:"Tell the user this exact preview before any change. The proposal must still be reviewed, approved and explicitly executed in the AI Action Center."};
}

export async function executeTool(ctx:ToolContext & {env?:Env},name:string,raw:unknown){
 if(!NAMES.includes(name as IntelligenceTool))return baseExecute(ctx,name,raw);if(!allowed(ctx.agent,name as IntelligenceTool,ctx.requestedTools))throw new Error(`${name} is not enabled for this employee`);const args=obj(raw);
 if(name==="discover_data_capabilities")return{role:ctx.agent.key,entities:intelligenceCatalog(ctx.agent.key,String(args.query||"")),governedActions:[...(ctx.agent.tools.includes("prepare_fee_payment")?[{key:"fee_payment",requiredWhenExact:["unique active student","positive amount","active payment method"],defaults:["school-local current payment date if omitted"],endpoint:"POST /api/v1/school/fees/receipts",sideEffects:["receipt","payment","accounting posting","fee allocation","balance","audit"],safeguards:["never guess ambiguous students","ask all missing fields together","preview before mutation","human approval plus explicit execution"]}]:[]),...(ctx.agent.tools.includes("prepare_system_action")?[{key:"system_action",description:"Other mutations are prepared as Action Center proposals using registered Ledgerly API routes; the AI cannot execute them directly."}]:[])],mutationPolicy:"Read tools may execute immediately. Any write must be exact, previewed, proposed in the Action Center, human-approved, and explicitly executed through Ledgerly's normal API/service."};
 if(name==="safe_data_query")return runPlan(ctx,args as SafeQueryPlan,true);
 if(name==="school_intelligence_snapshot")return snapshot(ctx,args);
 if(name==="prepare_fee_payment")return prepareFeePayment(ctx,raw);
 const type=String(args.intentType||"").trim(),sql=`SELECT id,intent_type AS "intentType",status,draft_json AS "draftJson",missing_fields_json AS "missingFieldsJson",candidates_json AS "candidatesJson",clarification_prompt AS "clarificationPrompt",action_id AS "actionId",updated_at AS "updatedAt" FROM ae_pending_intents WHERE organization_id=? AND conversation_id=? AND agent_key=?${type?" AND intent_type=?":""} AND status IN ('awaiting_information','ready','action_prepared') ORDER BY updated_at DESC LIMIT 20`,rows=await ctx.db.prepare(sql).bind(ctx.principal.organizationId,ctx.conversationId,ctx.agent.key,...(type?[type]:[])).all<any>();return{pending:rows.results.map(r=>({...r,draft:safeJson(r.draftJson,{}),missingFields:safeJson(r.missingFieldsJson,[]),candidates:safeJson(r.candidatesJson,{})}))};
}
