import { AppError } from "../../../src/lib/errors";
import { createId } from "../../../src/lib/ids";
import type { AuthPrincipal, Env } from "../../../src/types";
import type { AgentDefinition } from "./policy";
import { resolveRuntimeProvider } from "./provider-config";
import { executeTool } from "./memory-tools-v17";
import { buildLightToolRegistry, toolsForGroups, toolsForKind, toolsForModules, type LightTaskKind, type LightToolDescriptor } from "./light-tool-registry";
import { resolveLightReferences } from "./light-reference-resolver";

type ChatMessage={role:"user"|"assistant";content:string};
type LightRunInput={db:D1Database;env:Env&{AI_PROVIDER_ENCRYPTION_KEY?:string};principal:AuthPrincipal;agent:AgentDefinition;conversationId:string;messages:ChatMessage[]};
type Runtime=Awaited<ReturnType<typeof resolveRuntimeProvider>>;
type RouteArguments={pathParams?:Record<string,string|number>;query?:Record<string,string|number|boolean|null>;body?:Record<string,unknown>;title?:string;summary?:string};
type ToolExecution={tool:LightToolDescriptor;result:unknown};
type LightResult={text:string;model:string;provider:string;providerResponseId:string|null;usage:unknown;toolEvents:Array<Record<string,unknown>>;routing:Record<string,unknown>};

const KINDS:LightTaskKind[]=["query","report","create","update","delete","action","communication","document","analysis"];

function latestUser(input:LightRunInput){return[...input.messages].reverse().find(message=>message.role==="user")?.content.trim()||"";}
function stripFence(value:string){const text=value.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");const start=text.indexOf("{"),end=text.lastIndexOf("}");return start>=0&&end>start?text.slice(start,end+1):text;}
function parseObject<T extends Record<string,unknown>>(value:string,fallback:T):T{try{const parsed=JSON.parse(stripFence(value));return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as T:fallback;}catch{return fallback;}}

async function fetchJson<T>(url:string,init:RequestInit,timeoutMs:number){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...init,signal:controller.signal}),payload=await response.json().catch(()=>({})) as T;return{response,payload};}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new AppError(504,"AI_PROVIDER_TIMEOUT",`Light AI request timed out after ${timeoutMs} ms.`);throw error;}finally{clearTimeout(timer);}}
function openAiText(payload:any){if(typeof payload?.output_text==="string"&&payload.output_text.trim())return payload.output_text.trim();const chunks:string[]=[];for(const item of payload?.output||[])if(item?.type==="message")for(const part of item.content||[])if(part?.type==="output_text"&&part.text)chunks.push(part.text);return chunks.join("\n").trim();}
function anthropicText(payload:any){return(payload?.content||[]).filter((part:any)=>part?.type==="text"&&part.text).map((part:any)=>part.text).join("\n").trim();}

async function cheapText(runtime:Runtime,prompt:string,maxTokens=320){
 const timeout=Math.min(runtime.config.timeoutMs,45000);
 if(runtime.provider==="openai"){
  const{response,payload}=await fetchJson<any>(`${runtime.baseUrl}/responses`,{method:"POST",headers:{Authorization:`Bearer ${runtime.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:runtime.model,instructions:"Be concise. Follow the requested output format exactly. Do not invent Ledgerly data or IDs.",input:prompt,max_output_tokens:maxTokens})},timeout);
  if(!response.ok)throw new AppError(502,"AI_PROVIDER_ERROR",payload?.error?.message||`Light AI request failed (${response.status})`);return{text:openAiText(payload),id:payload?.id||null,usage:payload?.usage||null};
 }
 if(runtime.provider==="google"){
  const{response,payload}=await fetchJson<any>(`${runtime.baseUrl}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${runtime.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:runtime.model,messages:[{role:"system",content:"Be concise. Follow the requested output format exactly. Do not invent Ledgerly data or IDs."},{role:"user",content:prompt}],max_tokens:maxTokens,temperature:0})},timeout);
  if(!response.ok)throw new AppError(502,"AI_PROVIDER_ERROR",payload?.error?.message||`Light AI request failed (${response.status})`);return{text:String(payload?.choices?.[0]?.message?.content||"").trim(),id:payload?.id||null,usage:payload?.usage||null};
 }
 const{response,payload}=await fetchJson<any>(`${runtime.baseUrl}/messages`,{method:"POST",headers:{"x-api-key":runtime.apiKey,"anthropic-version":"2023-06-01","Content-Type":"application/json"},body:JSON.stringify({model:runtime.model,system:"Be concise. Follow the requested output format exactly. Do not invent Ledgerly data or IDs.",messages:[{role:"user",content:prompt}],max_tokens:maxTokens,temperature:0})},timeout);
 if(!response.ok)throw new AppError(502,"AI_PROVIDER_ERROR",payload?.error?.message||`Light AI request failed (${response.status})`);return{text:anthropicText(payload),id:payload?.id||null,usage:payload?.usage||null};
}
async function cheapJson<T extends Record<string,unknown>>(runtime:Runtime,prompt:string,fallback:T,maxTokens=260){const result=await cheapText(runtime,`${prompt}\n\nReturn JSON only. No markdown.`,maxTokens);return{value:parseObject(result.text,fallback),id:result.id,usage:result.usage};}
async function stage<T>(input:LightRunInput,name:string,work:()=>Promise<T>){const id=createId("aat");await input.db.prepare(`INSERT INTO ae_tool_calls(id,organization_id,conversation_id,agent_key,user_id,tool_name,arguments_json,status) VALUES (?,?,?,?,?,?,?,'running')`).bind(id,input.principal.organizationId,input.conversationId,input.agent.key,input.principal.userId,name,"{}").run();try{const result=await work();await input.db.prepare("UPDATE ae_tool_calls SET status='succeeded',result_json=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(JSON.stringify(result).slice(0,12000),id,input.principal.organizationId).run();return result;}catch(error){const message=error instanceof Error?error.message:String(error);await input.db.prepare("UPDATE ae_tool_calls SET status='failed',error_text=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(message,id,input.principal.organizationId).run();throw error;}}

function words(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g," ").split(/\s+/).filter(Boolean);}
function lexicalScore(query:string,tool:LightToolDescriptor){const q=new Set(words(query)),hay=words(`${tool.name} ${tool.description} ${tool.aliases.join(" ")} ${tool.module} ${tool.group}`);let score=0;for(const token of hay)if(q.has(token))score+=token.length>4?3:1;return score;}
function shortlist(query:string,tools:LightToolDescriptor[],limit=36){return[...tools].map(tool=>({tool,score:lexicalScore(query,tool)})).sort((a,b)=>b.score-a.score||a.tool.name.localeCompare(b.tool.name)).slice(0,limit).map(item=>item.tool);}
function inferKinds(prompt:string):LightTaskKind[]{const v=prompt.toLowerCase(),result:LightTaskKind[]=[];if(/\b(create|add|register|open|new|make)\b/.test(v))result.push("create");if(/\b(update|edit|change|rename|modify|move)\b/.test(v))result.push("update");if(/\b(delete|remove)\b/.test(v))result.push("delete");if(/\b(report|statement|summary|analytics)\b/.test(v))result.push("report");if(/\b(pdf|excel|xlsx|presentation|powerpoint|pptx|word|docx|print)\b/.test(v))result.push("document");if(/\b(send|message|sms|whatsapp|notify)\b/.test(v))result.push("communication");if(/\b(analy[sz]e|compare|why|trend|relationship)\b/.test(v))result.push("analysis");if(!result.length||/\b(check|show|find|get|list|what|who|how much|balance)\b/.test(v))result.unshift("query");return[...new Set(result)].slice(0,4);}
function validKinds(value:unknown,fallback:LightTaskKind[]){const raw=Array.isArray(value)?value.map(String):[],picked=raw.filter((kind):kind is LightTaskKind=>KINDS.includes(kind as LightTaskKind));return picked.length?[...new Set(picked)].slice(0,5):fallback;}
function enrichKinds(kinds:LightTaskKind[],format:"pdf"|"xlsx"|"pptx"|"docx"|null,prompt:string){const result=[...kinds];if(result.includes("analysis")){result.push("query","report");}if(result.includes("report"))result.push("query");if(result.includes("communication"))result.push("query");if(format&&documentNeedsLedgerlyData(prompt))result.push("query","report");return[...new Set(result)].slice(0,6);}
function validSelections(value:unknown,allowed:string[],max=6){const set=new Set(allowed),raw=Array.isArray(value)?value.map(String):[];return[...new Set(raw.filter(item=>set.has(item)))].slice(0,max);}
function formatTools(tools:LightToolDescriptor[]){return tools.map(tool=>({name:tool.name,kind:tool.kind,module:tool.module,group:tool.group,source:tool.source,description:tool.description.slice(0,220),aliases:tool.aliases.slice(0,5)}));}
function requestedFormat(prompt:string):"pdf"|"xlsx"|"pptx"|"docx"|null{const v=prompt.toLowerCase();if(/\bpdf\b/.test(v))return"pdf";if(/\b(excel|xlsx|spreadsheet|workbook)\b/.test(v))return"xlsx";if(/\b(powerpoint|pptx|presentation|slides?)\b/.test(v))return"pptx";if(/\b(word|docx)\b/.test(v))return"docx";return null;}
function documentNeedsLedgerlyData(prompt:string){return/\b(report|statement|summary|balance|arrears|attendance|student|learner|staff|teacher|fees?|finance|academic|inventory|stock|payroll|class|exam|collection|performance|budget|bank|journal)\b/i.test(prompt);}

function routeInputHint(path:string,method:string){const key=`${method.toUpperCase()} ${path}`,exact:Record<string,string>={
 "POST /api/v1/school/setup/classLevels":"Body: code, name, sequenceNo; optional educationLevel, promotionLevelId, terminal, active.",
 "POST /api/v1/school/setup/classes":"Body: classLevelId, code, name; optional academicYearId, campusId, departmentId, capacity, classTeacherUserId, active. Put a human class-level name in classLevelId when only the name is known.",
 "POST /api/v1/school/setup/streams":"Body: classId, code, name; optional campusId, capacity, classTeacherUserId, active. Put a human class name in classId when only the name is known.",
 "POST /api/v1/school/setup/subjects":"Body: code, name; optional departmentId, shortName, subjectType, curriculumCode, passMark, maxMark, active, metadata.",
 "POST /api/v1/school/setup/academicYears":"Body: code, name, startsOn, endsOn; optional status, isCurrent.",
 "POST /api/v1/school/setup/terms":"Body: academicYearId, code, name, sequenceNo, startsOn, endsOn; optional status, isCurrent.",
 "POST /api/v1/school/setup/departments":"Body: code, name; optional campusId, description, headUserId, parentId, active.",
 "POST /api/v1/school/setup/feeCategories":"Body: code, name; optional description, incomeAccountId, receivableAccountId, productId, taxable, taxCode, refundable, mandatory, active, metadata.",
 "POST /api/v1/school/setup/paymentMethods":"Body: code, name, methodType; optional accountId, configuration, active.",
 "POST /api/v1/school/student-management/students":"Body requires firstName, lastName and admissionDate. Optional middleName, preferredName, gender, dateOfBirth, nationality, phone, email, physicalAddress, admissionClassLevelId, currentAcademicYearId, currentClassId, currentStreamId, admissionNumber, studentNumber, guardian, residencyStatus and status. Human class/stream/year names may be put in corresponding *Id fields for Ledgerly to resolve.",
 "POST /api/v1/school/staff-management/staff":"Body requires firstName, lastName and hireDate. Optional staffNumber, gender, phone, email, departmentId, positionId, campusId, employmentType, employmentStatus, isTeacher, payType, basePayMinor, currency, userId, notes and emergencyContact. Human department/position/campus names may be supplied in the corresponding *Id fields.",
};if(exact[key])return exact[key];if(method==="GET")return"Use path parameters and query filters only when supplied or implied. Never invent IDs.";return"Build the smallest request body needed. Never invent an ID. If a required foreign key is known only by human name, put that name in the corresponding *Id field for deterministic resolution.";}
function codeFromName(value:string,fallback:string){return value.replace(/[^A-Za-z0-9]+/g,"").toUpperCase().slice(0,40)||fallback;}
function applyCommonDefaults(tool:LightToolDescriptor,body:Record<string,unknown>){const path=tool.pathTemplate||"";if(tool.method==="POST"&&path==="/api/v1/school/setup/classes"){if(typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"CLASS");if(typeof body.name==="string"&&!body.classLevelId)body.classLevelId=body.name;}if(tool.method==="POST"&&path==="/api/v1/school/setup/classLevels"&&typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"LEVEL");if(tool.method==="POST"&&path==="/api/v1/school/setup/streams"&&typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"STREAM");if(tool.method==="POST"&&path==="/api/v1/school/setup/subjects"&&typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"SUBJECT");if(tool.method==="POST"&&path==="/api/v1/school/setup/departments"&&typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"DEPT");if(tool.method==="POST"&&path==="/api/v1/school/setup/feeCategories"&&typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"FEE");if(tool.method==="POST"&&path==="/api/v1/school/setup/paymentMethods"&&typeof body.name==="string"&&!body.code)body.code=codeFromName(body.name,"PAY");if(tool.method==="POST"&&path==="/api/v1/school/student-management/students"&&!body.admissionDate)body.admissionDate=new Date().toISOString().slice(0,10);if(tool.method==="POST"&&path==="/api/v1/school/staff-management/staff"&&!body.hireDate)body.hireDate=new Date().toISOString().slice(0,10);return body;}
const REQUIRED_BODY:Record<string,Array<[string,string]>>={
 "POST /api/v1/school/setup/classLevels":[["name","class-level name"],["code","class-level code"],["sequenceNo","sequence number"]],
 "POST /api/v1/school/setup/classes":[["name","class name"],["code","class code"],["classLevelId","class level"]],
 "POST /api/v1/school/setup/streams":[["name","stream name"],["code","stream code"],["classId","class"]],
 "POST /api/v1/school/setup/subjects":[["name","subject name"],["code","subject code"]],
 "POST /api/v1/school/setup/academicYears":[["name","academic-year name"],["code","academic-year code"],["startsOn","start date"],["endsOn","end date"]],
 "POST /api/v1/school/setup/terms":[["name","term name"],["code","term code"],["academicYearId","academic year"],["sequenceNo","term sequence"],["startsOn","start date"],["endsOn","end date"]],
 "POST /api/v1/school/setup/departments":[["name","department name"],["code","department code"]],
 "POST /api/v1/school/setup/feeCategories":[["name","fee-category name"],["code","fee-category code"]],
 "POST /api/v1/school/setup/paymentMethods":[["name","payment-method name"],["code","payment-method code"],["methodType","payment method type"]],
 "POST /api/v1/school/student-management/students":[["firstName","student first name"],["lastName","student last name"],["admissionDate","admission date"]],
 "POST /api/v1/school/staff-management/staff":[["firstName","staff first name"],["lastName","staff last name"],["hireDate","hire date"]],
};
function missingRouteRequirements(tool:LightToolDescriptor,body:Record<string,unknown>){const requirements=REQUIRED_BODY[`${tool.method} ${tool.pathTemplate}`]||[];return requirements.filter(([field])=>body[field]===undefined||body[field]===null||String(body[field]).trim()==="").map(([,label])=>label);}

function genericReferenceKey(pathTemplate:string,param:string){if(param!=="id")return param;const segments=pathTemplate.split("/").filter(Boolean),index=segments.findIndex(segment=>segment===`:${param}`),resource=index>0?segments[index-1].toLowerCase():"";const map:Record<string,string>={students:"studentId",guardians:"guardianId",classes:"classId",classlevels:"classLevelId",streams:"streamId",subjects:"subjectId",terms:"termId",academicyears:"academicYearId",departments:"departmentId",staff:"staffId",employees:"staffId",accounts:"accountId",contacts:"contactId",products:"productId",feecategories:"feeCategoryId",paymentmethods:"paymentMethodId"};return map[resource]||param;}
async function resolvePathParams(input:LightRunInput,tool:LightToolDescriptor,params:Record<string,string|number>){const out:Record<string,string|number>={},issues:string[]=[];for(const[key,raw]of Object.entries(params)){if(typeof raw!=="string"){out[key]=raw;continue;}const referenceKey=genericReferenceKey(tool.pathTemplate||"",key);const resolved=await resolveLightReferences(input.db,input.principal.organizationId,{[referenceKey]:raw});const value=(resolved.value as Record<string,unknown>)[referenceKey];out[key]=typeof value==="string"||typeof value==="number"?value:raw;issues.push(...resolved.issues);}return{value:out,issues};}
function fillPath(template:string,params:Record<string,string|number>){const missing:string[]=[];const path=template.replace(/:([A-Za-z0-9_]+)/g,(_all,key)=>{const value=params[key];if(value===undefined||value===null||String(value).trim()===""){missing.push(key);return`:${key}`;}return encodeURIComponent(String(value));});return{path,missing};}
function appendQuery(path:string,query:Record<string,string|number|boolean|null>){const entries=Object.entries(query).filter(([,value])=>value!==null&&value!==undefined&&String(value)!=="");if(!entries.length)return path;return`${path}${path.includes("?")?"&":"?"}${entries.map(([key,value])=>`${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`).join("&")}`;}
function scopeFor(path:string){const p=path.toLowerCase();if(p.includes("/accounts"))return"accounts:write";if(p.includes("/journals"))return"journals:write";if(p.includes("/reports"))return"reports:write";if(p.includes("/contacts"))return"contacts:write";if(p.includes("/documents")||p.includes("/files"))return"documents:write";if(p.includes("/payments")||p.includes("/banking"))return"payments:write";if(p.includes("/payroll"))return"payroll:write";if(p.includes("/communications"))return"communications:write";if(p.includes("/products")||p.includes("/inventory"))return"products:write";return"school:write";}
function tinyHash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
async function prepareRouteAction(input:LightRunInput,tool:LightToolDescriptor,path:string,body:unknown,title:string,summary:string){const method=tool.method||"POST",payload={agentKey:input.agent.key,method,path,body},key=`conversation:${input.conversationId}:light:${method}:${path}:${tinyHash(JSON.stringify(body))}`,id=createId("aea");await input.db.prepare(`INSERT INTO ae_actions(id,organization_id,agent_key,action_type,title,summary,required_scope,payload_json,idempotency_key,status) VALUES(?,?,?,?,?,?,?,?,?,'suggested') ON CONFLICT(organization_id,idempotency_key) DO NOTHING`).bind(id,input.principal.organizationId,input.agent.key,"system.api.request",title.slice(0,240),summary.slice(0,600),scopeFor(path),JSON.stringify(payload),key).run();const action=await input.db.prepare("SELECT id,status,title,action_type AS actionType,required_scope AS requiredScope FROM ae_actions WHERE organization_id=? AND idempotency_key=?").bind(input.principal.organizationId,key).first();return{prepared:true,executed:false,requiresHumanApproval:true,approvalSurface:"chat",action};}

async function extractNativeArguments(runtime:Runtime,tool:LightToolDescriptor,prompt:string){const schema=JSON.stringify(tool.parameters||{type:"object",properties:{}}).slice(0,7000);const result=await cheapJson<Record<string,unknown>>(runtime,`Extract arguments for the Ledgerly tool ${tool.name}. Description: ${tool.description}\nJSON schema: ${schema}\nUser request: ${prompt}\nReturn exactly the argument object expected by the tool.`,{},600);return result.value;}
async function extractRouteArguments(runtime:Runtime,tool:LightToolDescriptor,prompt:string){const result=await cheapJson<RouteArguments>(runtime,`Extract arguments for this exact Ledgerly operation. Method/path: ${tool.method} ${tool.pathTemplate}. ${routeInputHint(tool.pathTemplate||"",tool.method||"GET")}\nUser request: ${prompt}\nReturn {"pathParams":{},"query":{},"body":{},"title":"short approval title","summary":"what will happen"}. Keep omitted fields omitted.`,{},650);return result.value;}

async function executeSelected(input:LightRunInput,runtime:Runtime,tool:LightToolDescriptor,prompt:string,events:Array<Record<string,unknown>>):Promise<ToolExecution>{
 const extracted=await stage(input,`light_extract_${tool.module.replace(/[^a-z0-9]+/gi,"_").toLowerCase()}`,()=>tool.source==="native"?extractNativeArguments(runtime,tool,prompt):extractRouteArguments(runtime,tool,prompt));
 const logId=createId("aat");await input.db.prepare(`INSERT INTO ae_tool_calls(id,organization_id,conversation_id,agent_key,user_id,tool_name,arguments_json,status) VALUES(?,?,?,?,?,?,?,'running')`).bind(logId,input.principal.organizationId,input.conversationId,input.agent.key,input.principal.userId,tool.name,JSON.stringify(extracted)).run();
 try{
  let result:unknown;
  if(tool.source==="native")result=await executeTool({db:input.db,env:input.env,principal:input.principal,agent:input.agent,conversationId:input.conversationId,requestedTools:null},tool.nativeName||tool.name,extracted);
  else{
   if(!input.env.AGENT_SYSTEM_GATEWAY)throw new Error("Ledgerly Light requires the self-hosted system gateway");
   const args=extracted as RouteArguments,pathResolution=await resolvePathParams(input,tool,args.pathParams||{});if(pathResolution.issues.length)result={needsClarification:true,issues:pathResolution.issues};
   else{const filled=fillPath(tool.pathTemplate||"",pathResolution.value);if(filled.missing.length)result={needsClarification:true,issues:[`The request needs ${filled.missing.join(", ")} before it can run.`]};else{const path=appendQuery(filled.path,args.query||{}),body=applyCommonDefaults(tool,{...(args.body||{})}),missing=missingRouteRequirements(tool,body);if(missing.length)result={needsClarification:true,issues:[`Please provide ${missing.join(", ")}.`]};else{const resolved=await resolveLightReferences(input.db,input.principal.organizationId,body);if(resolved.issues.length)result={needsClarification:true,issues:resolved.issues};else if(tool.readOnly){const response=await input.env.AGENT_SYSTEM_GATEWAY.request({agentKey:input.agent.key,principal:input.principal,method:tool.method||"GET",path,body:tool.method==="GET"?undefined:resolved.value});if(!response.ok)throw new Error(`Ledgerly API ${response.status}: ${JSON.stringify(response.data).slice(0,1800)}`);result=response.data;}else result=await prepareRouteAction(input,tool,path,resolved.value,args.title||`${tool.kind} ${tool.group}`,args.summary||`Prepared from: ${prompt}`);}}}
  }
  await input.db.prepare("UPDATE ae_tool_calls SET status='succeeded',result_json=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(JSON.stringify(result).slice(0,20000),logId,input.principal.organizationId).run();events.push({id:logId,tool:tool.name,status:"succeeded"});return{tool,result};
 }catch(error){const message=error instanceof Error?error.message:String(error);await input.db.prepare("UPDATE ae_tool_calls SET status='failed',error_text=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(message,logId,input.principal.organizationId).run();events.push({id:logId,tool:tool.name,status:"failed",error:message});return{tool,result:{error:message}};}
}

async function prepareDocumentFromResults(input:LightRunInput,runtime:Runtime,prompt:string,format:"pdf"|"xlsx"|"pptx"|"docx",results:unknown[],events:Array<Record<string,unknown>>){const verified=JSON.stringify(results).slice(0,20000),spec=await stage(input,"light_build_document",()=>cheapJson<Record<string,unknown>>(runtime,`Build a professional ${format.toUpperCase()} document specification using ONLY these verified Ledgerly results. Never invent a figure. User request: ${prompt}\nVerified data: ${verified}\nReturn a JSON report structure using subtitle, summary, dataAsOf, sources, sections, tables, charts, sheets and slides where useful. Tables carry exact figures. Charts only use verified numeric comparisons. Default to white background and black/dark text.`,{},1600)),title=await cheapJson<{title?:string}>(runtime,`Create a short professional file title for: ${prompt}\nReturn {"title":"..."}.`,{title:"Ledgerly Report"},100),args={title:String(title.value.title||"Ledgerly Report").slice(0,180),format,contentJson:JSON.stringify(spec.value)},logId=createId("aat");await input.db.prepare(`INSERT INTO ae_tool_calls(id,organization_id,conversation_id,agent_key,user_id,tool_name,arguments_json,status) VALUES(?,?,?,?,?,?,?,'running')`).bind(logId,input.principal.organizationId,input.conversationId,input.agent.key,input.principal.userId,"prepare_document",JSON.stringify({title:args.title,format})).run();try{const result=await executeTool({db:input.db,env:input.env,principal:input.principal,agent:input.agent,conversationId:input.conversationId,requestedTools:null},"prepare_document",args);await input.db.prepare("UPDATE ae_tool_calls SET status='succeeded',result_json=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(JSON.stringify(result),logId,input.principal.organizationId).run();events.push({id:logId,tool:"prepare_document",status:"succeeded"});return result;}catch(error){const message=error instanceof Error?error.message:String(error);await input.db.prepare("UPDATE ae_tool_calls SET status='failed',error_text=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(message,logId,input.principal.organizationId).run();events.push({id:logId,tool:"prepare_document",status:"failed",error:message});throw error;}}

export async function runLightAgent(input:LightRunInput):Promise<LightResult>{
 const prompt=latestUser(input);if(!prompt)throw new AppError(422,"VALIDATION_ERROR","A user message is required");
 const runtime=await resolveRuntimeProvider(input.db,input.env,input.principal.organizationId,"luna"),registry=await stage(input,"light_build_registry",()=>buildLightToolRegistry(input.env,input.principal,input.agent)),fallbackKinds=inferKinds(prompt),format=requestedFormat(prompt);
 const kindStage=await stage(input,"light_route_type",()=>cheapJson<{types?:unknown}>(runtime,`Classify this Ledgerly request into the necessary task types from: ${KINDS.join(", ")}. Request: ${prompt}\nReturn {"types":[...]}.`,{types:fallbackKinds},180));
 let kinds=enrichKinds(validKinds(kindStage.value.types,fallbackKinds),format,prompt);
 let candidates=toolsForKind(registry,kinds);if(!candidates.length)candidates=registry.tools;
 const availableModules=[...new Set(candidates.map(tool=>tool.module))].sort(),moduleStage=await stage(input,"light_route_module",()=>cheapJson<{modules?:unknown}>(runtime,`Choose the Ledgerly modules needed for this request. Available: ${availableModules.join(", ")}. Request: ${prompt}\nReturn {"modules":[...]}, maximum 6.`,{modules:availableModules.slice(0,1)},220));
 let modules=validSelections(moduleStage.value.modules,availableModules,6);if(!modules.length)modules=availableModules.slice(0,1);candidates=toolsForModules(candidates,modules);if(!candidates.length)candidates=toolsForModules(registry.tools,modules);
 if(candidates.length>42){const groups=[...new Set(candidates.map(tool=>tool.group))].sort(),groupStage=await stage(input,"light_route_group",()=>cheapJson<{groups?:unknown}>(runtime,`Choose the relevant Ledgerly subgroups for: ${prompt}\nAvailable: ${groups.join(", ")}\nReturn {"groups":[...]}, maximum 5.`,{groups:groups.slice(0,2)},220)),picked=validSelections(groupStage.value.groups,groups,5),grouped=toolsForGroups(candidates,picked);if(grouped.length)candidates=grouped;}
 candidates=shortlist(prompt,candidates,36);
 if(format&&documentNeedsLedgerlyData(prompt)){const dataCandidates=candidates.filter(tool=>!(tool.source==="native"&&["prepare_document","prepare_print_document","list_saved_documents"].includes(tool.name)));if(dataCandidates.length)candidates=dataCandidates;}
 const selectStage=await stage(input,"light_route_tool",()=>cheapJson<{tools?:unknown}>(runtime,`Choose the exact tools needed to fully complete this request. Prefer the fewest tools. Writes become approval cards and must never execute directly. Request: ${prompt}\nCandidates: ${JSON.stringify(formatTools(candidates))}\nReturn {"tools":["exact_name",...]}, maximum 6.`,{tools:candidates.slice(0,1).map(tool=>tool.name)},650)),selectedNames=validSelections(selectStage.value.tools,candidates.map(tool=>tool.name),6),selected=(selectedNames.length?selectedNames:[candidates[0]?.name]).filter(Boolean).map(name=>candidates.find(tool=>tool.name===name)!).filter(Boolean);
 if(!selected.length)throw new AppError(409,"LIGHT_TOOL_NOT_FOUND","Light Mode could not find a permitted Ledgerly capability for this request. Advanced Mode can still use system discovery.");
 const events:Array<Record<string,unknown>>=[],executed:ToolExecution[]=[];for(const tool of selected)executed.push(await executeSelected(input,runtime,tool,prompt,events));
 const results=executed.map(item=>({tool:item.tool.name,module:item.tool.module,kind:item.tool.kind,result:item.result})),issues=results.flatMap(item=>{const value=item.result as any;return value?.needsClarification&&Array.isArray(value.issues)?value.issues:[]});
 const routing={mode:"light",kinds,modules,selected:selected.map(tool=>tool.name),registry:registry.stats};
 if(issues.length)return{text:`I need one detail before I can safely continue: ${[...new Set(issues)].join(" ")}`,model:runtime.model,provider:runtime.provider,providerResponseId:null,usage:null,toolEvents:events,routing};
 const alreadyPreparedDocument=results.some(item=>item.tool==="prepare_document"&&(item.result as any)?.prepared);
 if(format&&!alreadyPreparedDocument){await prepareDocumentFromResults(input,runtime,prompt,format,results,events);return{text:`I prepared the ${format.toUpperCase()} output from verified Ledgerly data. Review or edit the document approval below, then approve it to generate the file.`,model:runtime.model,provider:runtime.provider,providerResponseId:null,usage:null,toolEvents:events,routing};}
 const prepared=results.filter(item=>(item.result as any)?.prepared&&(item.result as any)?.requiresHumanApproval);if(prepared.length)return{text:prepared.length===1?"I prepared the requested Ledgerly action. Review or edit the approval card below, then approve it when ready.":`I prepared ${prepared.length} Ledgerly actions. Review or edit the approval cards below before approving them.`,model:runtime.model,provider:runtime.provider,providerResponseId:null,usage:null,toolEvents:events,routing};
 const answer=await stage(input,"light_write_answer",()=>cheapText(runtime,`Answer using ONLY the verified Ledgerly results. Be concise but complete. Use a markdown table for exact comparisons when useful. Never invent missing values.\nUser request: ${prompt}\nVerified results: ${JSON.stringify(results).slice(0,22000)}`,900));return{text:answer.text||"I completed the Ledgerly lookup but could not format the final answer.",model:runtime.model,provider:runtime.provider,providerResponseId:answer.id,usage:answer.usage,toolEvents:events,routing};
}
