import { executeTool as baseExecute,openAiTools as baseTools } from "./intelligence-tools-v20";
import { intelligenceCatalog } from "./intelligence-registry";
import type { ToolContext } from "./tools-v14";

const NAME="inspect_data_schema";
const SPEC={type:"function",name:NAME,strict:false,description:"Inspect the live columns and datatypes of Ledgerly tables behind registered semantic entities. Only registered tables for this employee role can be inspected; arbitrary table names are not accepted. Use when technical schema certainty is needed.",parameters:{type:"object",properties:{query:{type:"string",description:"Semantic entity/topic such as lesson plans, fees or attendance"},entity:{type:"string",description:"Optional exact registered entity key"}},additionalProperties:false}};

function allowed(agent:any,requested?:string[]|null){if(!agent.tools.includes(NAME))return false;if(!requested)return true;return requested.includes(NAME);}
function tablesFromSource(source:string){return source.split("+").map(x=>x.trim()).filter(x=>/^[A-Za-z_][A-Za-z0-9_]*$/.test(x));}
export function openAiTools(agent:any,requested?:string[]|null){const base=baseTools(agent,requested);return allowed(agent,requested)?[...base,SPEC]:base;}
export async function executeTool(ctx:ToolContext,name:string,raw:unknown){if(name!==NAME)return baseExecute(ctx,name,raw);if(!allowed(ctx.agent,ctx.requestedTools))throw new Error(`${NAME} is not enabled for this employee`);const args=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,entity=String(args.entity||"").trim(),query=String(args.query||"").trim(),catalog=intelligenceCatalog(ctx.agent.key,entity||query),selected=entity?catalog.filter(x=>x.key===entity):catalog.slice(0,8);if(entity&&!selected.length)throw new Error(`Registered intelligence entity '${entity}' is unavailable to this employee`);const output=[] as Array<Record<string,unknown>>;for(const item of selected){const tables=tablesFromSource(item.source),schemas=[] as Array<Record<string,unknown>>;for(const table of tables){const rows=await ctx.db.prepare(`PRAGMA table_info('${table}')`).all<any>();schemas.push({table,columns:rows.results.map(r=>({name:r.name,type:r.type,notNull:Boolean(r.notnull),default:r.dflt_value??null}))});}output.push({entity:item.key,semanticDescription:item.description,registeredFields:item.fields,sourceTables:schemas});}return{live:true,tenantSafety:"Only registered entity tables were inspected; no arbitrary table name was accepted.",entities:output};}
