import { createId } from "../../../src/lib/ids";
import type { Env } from "../../../src/types";
import { executeTool as baseExecute,openAiTools as baseTools } from "./tools-v15";
import type { ToolContext } from "./tools-v14";

const NAMES=["system_catalog","system_read","prepare_system_action"] as const;
type SystemTool=typeof NAMES[number];
const SPECS:Record<SystemTool,any>={
 system_catalog:{type:"function",name:"system_catalog",strict:false,description:"List Ledgerly API operations available to this employee role on the self-hosted runtime. Use this before unfamiliar system work.",parameters:{type:"object",properties:{query:{type:"string"}},additionalProperties:false}},
 system_read:{type:"function",name:"system_read",strict:false,description:"Perform a read-only GET against an allowed Ledgerly API route using the current user's exact tenant, role and scopes.",parameters:{type:"object",properties:{path:{type:"string",description:"Absolute Ledgerly API path beginning /api/v1/"}},required:["path"],additionalProperties:false}},
 prepare_system_action:{type:"function",name:"prepare_system_action",strict:false,description:"Prepare a role-scoped Ledgerly API mutation in the AI Action Center. It NEVER executes the change. Supply a human-readable change preview whenever possible, then tell the user exactly what will change and that nothing has changed yet. Human approval and explicit execution are mandatory.",parameters:{type:"object",properties:{method:{type:"string",enum:["POST","PUT","PATCH","DELETE"]},path:{type:"string"},bodyJson:{type:"string",description:"JSON request body. Use {} for DELETE or requests without fields."},title:{type:"string"},summary:{type:"string"},changePreviewJson:{type:"string",description:"Optional JSON describing the exact records/fields/effects the user should see before approval. Sensitive values are redacted before storage/display."}},required:["method","path","bodyJson","title","summary"],additionalProperties:false}}
};
function sameSet(a:readonly string[],b:readonly string[]){return a.length===b.length&&a.every(x=>b.includes(x));}
function allowed(agent:any,name:SystemTool,requested?:string[]|null){if(!agent.tools.includes(name))return false;if(!requested)return true;if(requested.includes(name))return true;const legacy=agent.tools.filter((x:string)=>!NAMES.includes(x as SystemTool));return sameSet(requested,legacy);}
function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
function scopeFor(path:string){const p=path.toLowerCase();if(p.includes("/accounts"))return"accounts:write";if(p.includes("/journals"))return"journals:write";if(p.includes("/reports"))return"reports:write";if(p.includes("/contacts"))return"contacts:write";if(p.includes("/documents"))return"documents:write";if(p.includes("/payments")||p.includes("/banking"))return"payments:write";if(p.includes("/payroll"))return"payroll:write";if(p.includes("/communications"))return"communications:write";if(p.includes("/products")||p.includes("/inventory"))return"products:write";return"school:write";}
function redact(value:unknown,key=""):unknown{if(/password|secret|token|api[_-]?key|authorization|credential/i.test(key))return"[REDACTED]";if(Array.isArray(value))return value.map(v=>redact(v));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,redact(v,k)]));return value;}
function previewOf(method:string,path:string,body:unknown,raw?:unknown){if(typeof raw==="string"&&raw.trim()){try{return redact(JSON.parse(raw));}catch{throw new Error("changePreviewJson must be valid JSON");}}return{operation:`${method} ${path}`,request:redact(body),notice:"This is a proposal only. No Ledgerly data has been changed."};}
export function openAiTools(agent:any,requested?:string[]|null){return[...baseTools(agent,requested),...NAMES.filter(name=>allowed(agent,name,requested)).map(name=>SPECS[name])];}
export async function executeTool(ctx:ToolContext & {env?:Env},name:string,raw:unknown){if(!NAMES.includes(name as SystemTool))return baseExecute(ctx,name,raw);if(!allowed(ctx.agent,name as SystemTool,ctx.requestedTools))throw new Error(`${name} is not enabled for this employee`);const env=ctx.env as Env|undefined;if(!env?.AGENT_SYSTEM_GATEWAY)throw new Error("The self-hosted delegated system gateway is not available");const args=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>;
 if(name==="system_catalog"){const routes=await env.AGENT_SYSTEM_GATEWAY.catalog(ctx.agent.key,ctx.principal),q=String(args.query||"").trim().toLowerCase();return{role:ctx.agent.key,routes:(q?routes.filter(r=>`${r.method} ${r.path}`.toLowerCase().includes(q)):routes).slice(0,250)};}
 if(name==="system_read"){const path=String(args.path||"").trim();const result=await env.AGENT_SYSTEM_GATEWAY.request({agentKey:ctx.agent.key,principal:ctx.principal,method:"GET",path});if(!result.ok)throw new Error(`Ledgerly API ${result.status}: ${JSON.stringify(result.data).slice(0,1200)}`);return result.data;}
 const method=String(args.method||"").toUpperCase() as "POST"|"PUT"|"PATCH"|"DELETE",path=String(args.path||"").trim(),title=String(args.title||"Ledgerly action").trim().slice(0,200),summary=String(args.summary||"").trim().slice(0,600);if(!["POST","PUT","PATCH","DELETE"].includes(method)||!path.startsWith("/api/v1/"))throw new Error("A valid Ledgerly API method and /api/v1/ path are required");let body:unknown={};try{body=JSON.parse(String(args.bodyJson||"{}"));}catch{throw new Error("bodyJson must be valid JSON");}const changePreview=previewOf(method,path,body,args.changePreviewJson),payload={agentKey:ctx.agent.key,method,path,body,changePreview},key=`conversation:${ctx.conversationId}:system:${method}:${path}:${hash(JSON.stringify(body))}`,id=createId("aea");await ctx.db.prepare(`INSERT INTO ae_actions(id,organization_id,agent_key,action_type,title,summary,required_scope,payload_json,idempotency_key,status) VALUES(?,?,?,?,?,?,?,?,?,'suggested') ON CONFLICT(organization_id,idempotency_key) DO NOTHING`).bind(id,ctx.principal.organizationId,ctx.agent.key,"system.api.request",title,summary||`${method} ${path}`,scopeFor(path),JSON.stringify(payload),key).run();const action=await ctx.db.prepare("SELECT id,status,title,summary,action_type AS actionType,required_scope AS requiredScope FROM ae_actions WHERE organization_id=? AND idempotency_key=?").bind(ctx.principal.organizationId,key).first();return{prepared:true,executed:false,nothingChangedYet:true,requiresHumanApproval:true,requiresExplicitExecution:true,changePreview,action,message:"Present the change preview to the user now. No Ledgerly data has been changed; the Action Center must approve and explicitly execute it."};}
