import { createId } from "../../../src/lib/ids";
import type { Env } from "../../../src/types";
import { executeTool as baseExecute,openAiTools as baseTools } from "./tools-v15";
import type { ToolContext } from "./tools-v14";

const NAMES=["system_catalog","system_read","prepare_system_action","prepare_system_workflow"] as const;
type SystemTool=typeof NAMES[number];
const SPECS:Record<SystemTool,any>={
 system_catalog:{type:"function",name:"system_catalog",strict:false,description:"List the REAL Ledgerly API operations available to this employee role. Use this before unfamiliar reads or writes. Never invent API routes.",parameters:{type:"object",properties:{query:{type:"string"}},additionalProperties:false}},
 system_read:{type:"function",name:"system_read",strict:false,description:"Perform a read-only GET against a real permitted Ledgerly API route. The path is checked against the live route catalog before execution.",parameters:{type:"object",properties:{path:{type:"string",description:"Absolute Ledgerly API path beginning /api/v1/. Use system_catalog rather than guessing."}},required:["path"],additionalProperties:false}},
 prepare_system_action:{type:"function",name:"prepare_system_action",strict:false,description:"Prepare ONE governed Ledgerly mutation for human confirmation. Method and path are validated against the live route catalog. Never invent routes or required school data.",parameters:{type:"object",properties:{method:{type:"string",enum:["POST","PUT","PATCH","DELETE"]},path:{type:"string"},bodyJson:{type:"string",description:"JSON request body. Use {} when there is no body."},title:{type:"string"},summary:{type:"string"}},required:["method","path","bodyJson","title","summary"],additionalProperties:false}},
 prepare_system_workflow:{type:"function",name:"prepare_system_workflow",strict:false,description:"Prepare one governed compound Ledgerly workflow made of 2-12 dependent API mutations. All routes are validated before the user sees the confirmation. Later steps may reference earlier responses with {{stepId.data.id}} placeholders in paths or bodies. Execution is sequential, stops on the first failure and never silently retries or invents rollback.",parameters:{type:"object",properties:{title:{type:"string"},summary:{type:"string"},stepsJson:{type:"string",description:"JSON array of steps. Each step: {id,title,method,path,body}. IDs must be unique. A later step can use placeholders such as {{staff.data.id}} from an earlier step response."}},required:["title","summary","stepsJson"],additionalProperties:false}}
};
function sameSet(a:readonly string[],b:readonly string[]){return a.length===b.length&&a.every(x=>b.includes(x));}
function allowed(agent:any,name:SystemTool,requested?:string[]|null){if(!agent.tools.includes(name))return false;if(!requested)return true;if(requested.includes(name))return true;const legacy=agent.tools.filter((x:string)=>!NAMES.includes(x as SystemTool));return sameSet(requested,legacy);}
function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
function scopeFor(path:string){const p=path.toLowerCase();if(p.includes("/accounts"))return"accounts:write";if(p.includes("/journals"))return"journals:write";if(p.includes("/reports"))return"reports:write";if(p.includes("/contacts"))return"contacts:write";if(p.includes("/documents")||p.includes("/files"))return"documents:write";if(p.includes("/payments")||p.includes("/banking"))return"payments:write";if(p.includes("/payroll"))return"payroll:write";if(p.includes("/communications"))return"communications:write";if(p.includes("/products")||p.includes("/inventory"))return"products:write";return"school:write";}
function cleanPath(value:string){const path=String(value||"").trim().split("?")[0].replace(/\/+$/,"");return path||"/";}
function normalizeKnownAlias(method:string,raw:string){const path=cleanPath(raw);if((method==="POST"||method==="GET")&&path==="/api/v1/staff")return"/api/v1/school/staff-management/staff";if(path.startsWith("/api/v1/staff/"))return`/api/v1/school/staff-management/staff/${path.slice("/api/v1/staff/".length)}`;return path;}
function routeMatches(templatePath:string,requestedPath:string){const expected=cleanPath(templatePath).split("/").filter(Boolean),actual=cleanPath(requestedPath).split("/").filter(Boolean);if(expected.length!==actual.length)return false;return expected.every((part,index)=>part===actual[index]||part.startsWith(":")||/^\{\{.+\}\}$/.test(actual[index]||""));}
function relatedRoutes(routes:any[],method:string,path:string){const words=cleanPath(path).toLowerCase().split("/").filter(x=>x&&!['api','v1'].includes(x)&&!x.startsWith("{{"));return routes.filter(r=>String(r.method||"").toUpperCase()===method).map(r=>{const candidate=String(r.path||""),lower=candidate.toLowerCase(),score=words.reduce((n,w)=>n+(lower.includes(w)?1:0),0);return{...r,score};}).filter(r=>r.score>0).sort((a,b)=>b.score-a.score).slice(0,8);}
async function validateCatalogRoute(env:Env,agentKey:string,principal:any,method:string,rawPath:string){if(!env.AGENT_SYSTEM_GATEWAY)throw new Error("The self-hosted delegated system gateway is not available");const path=normalizeKnownAlias(method,rawPath);const routes=await env.AGENT_SYSTEM_GATEWAY.catalog(agentKey,principal);const found=routes.find((route:any)=>String(route.method||"").toUpperCase()===method&&routeMatches(String(route.path||""),path));if(found)return{path,catalogPath:String((found as any).path),corrected:cleanPath(rawPath)!==path};const related=relatedRoutes(routes,method,path);throw new Error(`Ledgerly route ${method} ${path} does not exist in this employee's permitted live route catalog. Use system_catalog and retry with a real route.${related.length?` Related routes: ${related.map((r:any)=>`${r.method} ${r.path}`).join("; ")}`:""}`);}
function parseBody(value:unknown){if(value&&typeof value==="object")return value;try{return JSON.parse(String(value||"{}"));}catch{throw new Error("Request body must be valid JSON");}}
function placeholderRefs(value:unknown){const text=JSON.stringify(value),refs:string[]=[];for(const match of text.matchAll(/\{\{([A-Za-z][A-Za-z0-9_-]*)\.[^}]+\}\}/g))refs.push(match[1]!);return[...new Set(refs)];}

export function openAiTools(agent:any,requested?:string[]|null){return[...baseTools(agent,requested),...NAMES.filter(name=>allowed(agent,name,requested)).map(name=>SPECS[name])];}

export async function executeTool(ctx:ToolContext & {env?:Env},name:string,raw:unknown){
 if(!NAMES.includes(name as SystemTool))return baseExecute(ctx,name,raw);
 if(!allowed(ctx.agent,name as SystemTool,ctx.requestedTools))throw new Error(`${name} is not enabled for this employee`);
 const env=ctx.env as Env|undefined;if(!env?.AGENT_SYSTEM_GATEWAY)throw new Error("The self-hosted delegated system gateway is not available");
 const args=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>;
 if(name==="system_catalog"){const routes=await env.AGENT_SYSTEM_GATEWAY.catalog(ctx.agent.key,ctx.principal),q=String(args.query||"").trim().toLowerCase();return{role:ctx.agent.key,routes:(q?routes.filter(r=>`${r.method} ${r.path}`.toLowerCase().includes(q)):routes).slice(0,250)};}
 if(name==="system_read"){const rawPath=String(args.path||"").trim();if(!rawPath.startsWith("/api/v1/"))throw new Error("A valid /api/v1/ Ledgerly path is required");const validated=await validateCatalogRoute(env,ctx.agent.key,ctx.principal,"GET",rawPath);const result=await env.AGENT_SYSTEM_GATEWAY.request({agentKey:ctx.agent.key,principal:ctx.principal,method:"GET",path:validated.path});if(!result.ok)throw new Error(`Ledgerly API ${result.status}: ${JSON.stringify(result.data).slice(0,1200)}`);return result.data;}
 if(name==="prepare_system_workflow"){
  const title=String(args.title||"Ledgerly workflow").trim().slice(0,200),summary=String(args.summary||"").trim().slice(0,1200);let source:any;
  try{source=JSON.parse(String(args.stepsJson||"[]"));}catch{throw new Error("stepsJson must be valid JSON");}
  if(!Array.isArray(source)||source.length<2||source.length>12)throw new Error("A compound workflow requires 2 to 12 steps");
  const seen=new Set<string>(),steps:any[]=[],requiredScopes=new Set<string>();
  for(let index=0;index<source.length;index++){
   const item=source[index]&&typeof source[index]==="object"?source[index]:{},id=String(item.id||"").trim(),method=String(item.method||"").toUpperCase(),rawPath=String(item.path||"").trim();
   if(!/^[A-Za-z][A-Za-z0-9_-]{0,39}$/.test(id)||seen.has(id))throw new Error(`Workflow step ${index+1} needs a unique simple id`);
   if(!["POST","PUT","PATCH","DELETE"].includes(method)||!rawPath.startsWith("/api/v1/"))throw new Error(`Workflow step ${id} has an invalid method or path`);
   const body=parseBody(item.body??{}),refs=[...placeholderRefs(rawPath),...placeholderRefs(body)];for(const ref of refs)if(!seen.has(ref))throw new Error(`Workflow step ${id} references ${ref} before that step has executed`);
   const validated=await validateCatalogRoute(env,ctx.agent.key,ctx.principal,method,rawPath),requiredScope=scopeFor(validated.path);requiredScopes.add(requiredScope);
   steps.push({id,title:String(item.title||`${method} ${validated.path}`).trim().slice(0,180),method,path:validated.path,body,requiredScope,catalogPath:validated.catalogPath});seen.add(id);
  }
  const payload={agentKey:ctx.agent.key,steps,requiredScopes:[...requiredScopes],executionPolicy:{mode:"sequential",stopOnFailure:true,automaticRetry:false,automaticRollback:false}},key=`conversation:${ctx.conversationId}:workflow:${hash(JSON.stringify(payload))}`,id=createId("aea"),primaryScope=[...requiredScopes][0]||"school:write";
  await ctx.db.prepare(`INSERT INTO ae_actions(id,organization_id,agent_key,action_type,title,summary,required_scope,payload_json,idempotency_key,status) VALUES(?,?,?,?,?,?,?,?,?,'suggested') ON CONFLICT(organization_id,idempotency_key) DO NOTHING`).bind(id,ctx.principal.organizationId,ctx.agent.key,"system.api.workflow",title,summary||`${steps.length}-step Ledgerly workflow`,primaryScope,JSON.stringify(payload),key).run();
  const action=await ctx.db.prepare("SELECT id,status,title,action_type AS actionType,required_scope AS requiredScope FROM ae_actions WHERE organization_id=? AND idempotency_key=?").bind(ctx.principal.organizationId,key).first();
  return{prepared:true,executed:false,requiresHumanApproval:true,compound:true,stepCount:steps.length,requiredScopes:[...requiredScopes],steps:steps.map(x=>({id:x.id,title:x.title,method:x.method,path:x.path,requiredScope:x.requiredScope})),action};
 }
 const method=String(args.method||"").toUpperCase() as "POST"|"PUT"|"PATCH"|"DELETE",rawPath=String(args.path||"").trim(),title=String(args.title||"Ledgerly action").trim().slice(0,200),summary=String(args.summary||"").trim().slice(0,1000);if(!["POST","PUT","PATCH","DELETE"].includes(method)||!rawPath.startsWith("/api/v1/"))throw new Error("A valid Ledgerly API method and /api/v1/ path are required");const validated=await validateCatalogRoute(env,ctx.agent.key,ctx.principal,method,rawPath),body=parseBody(args.bodyJson),payload={agentKey:ctx.agent.key,method,path:validated.path,body},key=`conversation:${ctx.conversationId}:system:${method}:${validated.path}:${hash(JSON.stringify(body))}`,id=createId("aea");await ctx.db.prepare(`INSERT INTO ae_actions(id,organization_id,agent_key,action_type,title,summary,required_scope,payload_json,idempotency_key,status) VALUES(?,?,?,?,?,?,?,?,?,'suggested') ON CONFLICT(organization_id,idempotency_key) DO NOTHING`).bind(id,ctx.principal.organizationId,ctx.agent.key,"system.api.request",title,summary||`${method} ${validated.path}`,scopeFor(validated.path),JSON.stringify(payload),key).run();const action=await ctx.db.prepare("SELECT id,status,title,action_type AS actionType,required_scope AS requiredScope FROM ae_actions WHERE organization_id=? AND idempotency_key=?").bind(ctx.principal.organizationId,key).first();return{prepared:true,executed:false,requiresHumanApproval:true,routeValidated:true,correctedLegacyPath:validated.corrected,path:validated.path,action};
}
