import { Hono } from "hono";
import type { AppVariables,Env } from "../../../src/types";
import { requireScope } from "../../../src/lib/auth";
import { AppError } from "../../../src/lib/errors";
import { createId } from "../../../src/lib/ids";
import { resolveModel } from "./policy";

export const agenticVisionRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
const MAX_IMAGE_BYTES=10*1024*1024;
const MIMES=new Set(["image/jpeg","image/png","image/webp"]);
function safeName(value:string){return String(value||"image").normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,160)||"image";}
async function sha256(bytes:ArrayBuffer){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");}
function base64(bytes:Uint8Array){let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(binary);}
function responseText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text.trim();const parts:string[]=[];for(const item of payload?.output||[])for(const part of item?.content||[])if(part?.type==="output_text"&&part?.text)parts.push(part.text);return parts.join("\n").trim();}
async function inspectImage(env:Env,mime:string,bytes:ArrayBuffer){if(!env.OPENAI_API_KEY)throw new AppError(503,"AI_NOT_CONFIGURED","OpenAI is required for image OCR and visual extraction");const model=resolveModel("terra",env as any),url=String(env.OPENAI_BASE_URL||"https://api.openai.com/v1").replace(/\/$/,"")+"/responses";const prompt=`Read this school/business image carefully. Perform OCR on ALL visible text, including handwriting where legible. Preserve names, dates, amounts, table rows, headings and labels exactly. Then describe the visual structure (tables, columns, form fields, signatures, ticks, stamps, lesson-plan fields, fee/payment fields). Do not invent unreadable values. Return plain text with two sections exactly: OCR TEXT: and VISUAL STRUCTURE:`;const r=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,reasoning:{effort:"low"},input:[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:`data:${mime};base64,${base64(new Uint8Array(bytes))}`}]}]})});const payload=await r.json().catch(()=>({}));if(!r.ok)throw new AppError(502,"VISION_PROVIDER_ERROR",(payload as any)?.error?.message||`Vision request failed (${r.status})`);const text=responseText(payload);const marker="VISUAL STRUCTURE:";const idx=text.indexOf(marker);return{ocrText:(idx>=0?text.slice(0,idx):text).replace(/^OCR TEXT:\s*/i,"").trim(),visionSummary:(idx>=0?text.slice(idx+marker.length):"").trim(),model};}

agenticVisionRoutes.post("/vision/images",requireScope("school:read"),async c=>{const p=c.get("principal"),form=await c.req.formData(),part=form.get("file");if(!(part instanceof File))throw new AppError(422,"FILE_REQUIRED","Take a photo or choose an image");if(part.size<=0)throw new AppError(422,"EMPTY_FILE","The image is empty");if(part.size>MAX_IMAGE_BYTES)throw new AppError(413,"IMAGE_TOO_LARGE","Images are limited to 10 MB");const mime=String(part.type||"").toLowerCase();if(!MIMES.has(mime))throw new AppError(415,"UNSUPPORTED_IMAGE","Use JPEG, PNG or WebP images");const id=createId("aeimg"),bytes=await part.arrayBuffer(),checksum=await sha256(bytes),key=`agentic-images/${p.organizationId}/${new Date().toISOString().slice(0,7)}/${id}/${safeName(part.name)}`;await c.env.WORK_FILES_BUCKET.put(key,bytes,{httpMetadata:{contentType:mime,contentDisposition:`inline; filename=\"${safeName(part.name)}\"`},customMetadata:{organizationId:p.organizationId,imageId:id,checksum}});await c.env.FINANCE_DB.prepare(`INSERT INTO ae_image_attachments(id,organization_id,uploaded_by,object_key,original_name,mime_type,size_bytes,checksum_sha256,status) VALUES(?,?,?,?,?,?,?,?,'processing')`).bind(id,p.organizationId,p.userId,key,part.name,mime,part.size,checksum).run();try{const vision=await inspectImage(c.env,mime,bytes);await c.env.FINANCE_DB.prepare("UPDATE ae_image_attachments SET status='ready',ocr_text=?,vision_summary=?,error_text=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(vision.ocrText,vision.visionSummary,id,p.organizationId).run();return c.json({data:{id,originalName:part.name,mimeType:mime,sizeBytes:part.size,ocrText:vision.ocrText,visionSummary:vision.visionSummary,model:vision.model}},201);}catch(error){const text=error instanceof Error?error.message:String(error);await c.env.FINANCE_DB.prepare("UPDATE ae_image_attachments SET status='failed',error_text=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(text.slice(0,1000),id,p.organizationId).run();throw error;}});
agenticVisionRoutes.get("/vision/images/:id",requireScope("school:read"),async c=>{const p=c.get("principal"),row=await c.env.FINANCE_DB.prepare("SELECT object_key AS objectKey,mime_type AS mimeType,original_name AS originalName,status FROM ae_image_attachments WHERE id=? AND organization_id=? AND status<>'deleted'").bind(c.req.param("id"),p.organizationId).first<any>();if(!row)throw new AppError(404,"IMAGE_NOT_FOUND","Image not found");const obj=await c.env.WORK_FILES_BUCKET.get(row.objectKey);if(!obj)throw new AppError(404,"IMAGE_FILE_MISSING","Stored image is missing");c.header("Content-Type",row.mimeType);c.header("Content-Disposition",`inline; filename=\"${safeName(row.originalName)}\"`);return c.body(new Uint8Array(await obj.arrayBuffer()));});
