import {useEffect,useState} from "react";
import {Activity,ArrowLeftRight,CheckCircle2,DatabaseBackup,RefreshCw,Server,ShieldCheck,TriangleAlert} from "lucide-react";
import {get,post,errorText} from "../../../web/api";
type Camera={id:string;name:string;server_id?:string};type ServerRow={id:string;name:string;status:string;last_seen_at?:string};
type Redundancy={camera_id:string;camera_name:string;primary_server_id:string;secondary_server_id:string;primary_server_name:string;secondary_server_name:string;primary_status:string;secondary_status:string;state:string;failover_after_seconds:number;failback_enabled:number;failback_after_seconds:number;last_reason?:string;state_changed_at:string};
type FailEvent={id:string;camera_name:string;from_server_name?:string;to_server_name?:string;reason:string;state:string;automatic:number;created_at:string};type Validation={id:string;server_id?:string;camera_id?:string;check_type:string;status:string;message?:string;created_at:string};type Backup={server_id:string;server_name:string;enabled:number;target_label?:string;status:string;pending_files:number;pending_bytes:number;replicated_files:number;replicated_bytes:number;lag_seconds?:number;last_success_at?:string;last_error?:string;updated_at:string};
type Gate={key:string;label:string;status:"passed"|"warning"|"failed";detail:string;required:boolean};type Readiness={score:number;status:"ready"|"caution"|"not_ready";gates:Gate[];generatedAt:string;certificate?:Commissioning};type Drill={generatedAt:string;protectedCameras:number;readyCameras:number;score?:number;status?:string;certificate?:Commissioning;results:Array<{cameraId:string;cameraName:string;primaryServerName:string;secondaryServerName:string;primaryHealthy:boolean;secondaryHealthy:boolean;ready:boolean;predictedRtoSeconds:number;message:string}>};type Commissioning={id:string;run_type?:string;runType?:string;status:string;score:number;passed:boolean;actor_id?:string;summary?:string;created_at?:string;createdAt?:string};
export function SecurityCameraResilience(){const[cameras,setCameras]=useState<Camera[]>([]),[servers,setServers]=useState<ServerRow[]>([]),[data,setData]=useState<any>({configs:[],events:[],validation:{runs:[],summary:{}},backups:[],readiness:null}),[history,setHistory]=useState<Commissioning[]>([]),[drill,setDrill]=useState<Drill|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");async function load(){setBusy(true);setError("");try{const[c,s,r,h]=await Promise.all([get<Camera[]>("/security-camera/cameras"),get<ServerRow[]>("/security-camera/servers"),get<any>("/security-camera/redundancy"),get<Commissioning[]>("/security-camera/commissioning-history?limit=100")]);setCameras(c);setServers(s);setData(r);setHistory(h)}catch(e){setError(errorText(e))}finally{setBusy(false)}}useEffect(()=>{void load();const t=setInterval(()=>void load(),20000);return()=>clearInterval(t)},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),cameraId=String(f.get("cameraId")||"");try{await post(`/security-camera/cameras/${cameraId}/redundancy`,{primaryServerId:f.get("primaryServerId"),secondaryServerId:f.get("secondaryServerId"),failoverAfterSeconds:Number(f.get("failoverAfterSeconds")||90),failbackEnabled:f.get("failbackEnabled")==="on",failbackAfterSeconds:Number(f.get("failbackAfterSeconds")||300),enabled:true});await load()}catch(x){setError(errorText(x))}}
 async function switchTo(cameraId:string,target:"primary"|"secondary"){const reason=window.prompt(`Reason for switching to ${target} NVR`,target==="secondary"?"Manual disaster-recovery test":"Restore primary NVR")||undefined;try{await post(`/security-camera/cameras/${cameraId}/failover`,{target,reason});await load()}catch(x){setError(errorText(x))}}
 async function runDrill(){setBusy(true);setError("");try{setDrill(await post<Drill>("/security-camera/recovery-drill",{}));await load()}catch(x){setError(errorText(x))}finally{setBusy(false)}}
 async function certify(){setBusy(true);setError("");try{await post<Readiness>("/security-camera/readiness/certify",{});await load()}catch(x){setError(errorText(x))}finally{setBusy(false)}}
 const configs:Redundancy[]=data.configs||[],events:FailEvent[]=data.events||[],runs:Validation[]=data.validation?.runs||[],summary=data.validation?.summary||{},backups:Backup[]=data.backups||[],readiness:Readiness|null=data.readiness||null;
 return <div className="sec-res"><header className="sec-res-hero"><div><div className="sec-res-kicker"><ShieldCheck size={15}/> CAMERA RESILIENCE</div><h1>NVR failover, backup & certified deployment readiness</h1><p>Keep capture running through failure, verify local/NAS recovery and retain auditable commissioning evidence before a school depends on the system.</p></div><div className="actions"><button onClick={()=>void certify()}><CheckCircle2 size={15}/>Certify current state</button><button onClick={()=>void runDrill()}><ShieldCheck size={15}/>Recovery drill</button><button onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></div></header>{error&&<div className="sec-error">{error}</div>}
 {readiness?<section className="sec-res-card"><h2><ShieldCheck size={18}/> Deployment readiness</h2><div className="sec-res-stats"><Stat label="Readiness score" value={`${readiness.score}/100`}/><Stat label="Deployment state" value={readiness.status.replace("_"," ")}/><Stat label="Required gates failed" value={readiness.gates.filter(g=>g.required&&g.status==="failed").length}/><Stat label="Advisories" value={readiness.gates.filter(g=>!g.required&&g.status!=="passed").length}/></div><div className="sec-val-grid">{readiness.gates.map(g=><article key={g.key} className={g.status}>{g.status==="passed"?<CheckCircle2 size={16}/>:<TriangleAlert size={16}/>}<div><b>{g.label}{g.required?"":" · advisory"}</b><small>{g.detail}</small></div><time>{g.status}</time></article>)}</div></section>:null}
 {drill?<section className="sec-res-card"><h2><ArrowLeftRight size={18}/> Latest recovery drill · no assignments changed</h2><p className="hint">This dry run checks whether each configured secondary NVR is currently healthy and estimates failover detection time.</p><div className="sec-val-grid">{drill.results.map(r=><article key={r.cameraId} className={r.ready?"passed":"failed"}>{r.ready?<CheckCircle2 size={16}/>:<TriangleAlert size={16}/>}<div><b>{r.cameraName}</b><small>{r.primaryServerName} → {r.secondaryServerName}</small><small>{r.message} · predicted RTO ~{r.predictedRtoSeconds}s</small></div></article>)}</div></section>:null}
 <section className="sec-res-card"><h2><CheckCircle2 size={18}/> Commissioning history</h2><p className="hint">Historical records are immutable snapshots. Live readiness may later improve or degrade without rewriting a prior certification.</p><div className="sec-val-grid">{history.length?history.map(h=><article key={h.id} className={h.status}><span>{h.status==="passed"?<CheckCircle2 size={16}/>:<TriangleAlert size={16}/>}</span><div><b>{String(h.run_type||h.runType||"commissioning").replace(/_/g," ")}</b><small>{h.summary||"No summary"}</small><small>Score {h.score}/100 · operator {h.actor_id||"system"}</small></div><time>{new Date(h.created_at||h.createdAt||Date.now()).toLocaleString()}</time></article>):<div className="sec-empty">No commissioning certificates have been recorded yet.</div>}</div></section>
 <section className="sec-res-stats"><Stat label="Failover-protected cameras" value={configs.length}/><Stat label="On secondary NVR" value={configs.filter(x=>x.state==="secondary").length}/><Stat label="Backup targets unhealthy" value={backups.filter(x=>x.enabled&&x.status!=="healthy").length}/><Stat label="Validation failures · 24h" value={summary.failed||0}/></section>
 <div className="sec-res-grid"><section className="sec-res-card"><h2><ArrowLeftRight size={18}/> Configure automatic failover</h2><form className="sec-res-form" onSubmit={save}><label>Camera<select name="cameraId" required>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Primary NVR<select name="primaryServerId" required>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Secondary NVR<select name="secondaryServerId" required>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Fail over after seconds<input name="failoverAfterSeconds" type="number" min="30" max="900" defaultValue="90"/></label><label>Fail back after stable seconds<input name="failbackAfterSeconds" type="number" min="60" max="3600" defaultValue="300"/></label><label className="check"><input name="failbackEnabled" type="checkbox" defaultChecked/> Automatically return to primary</label><button>Save redundancy</button></form><p className="hint">Failover changes the camera's real NVR assignment. The phone reconnects through its existing configuration polling, with no new QR pairing.</p></section>
 <section className="sec-res-card"><h2><Server size={18}/> Current protection state</h2><div className="sec-res-list">{configs.length?configs.map(r=><article key={r.camera_id} className={r.state}><div><b>{r.camera_name}</b><small>{r.primary_server_name} → {r.secondary_server_name}</small><small>{r.last_reason||"Primary recorder selected"}</small></div><span>{r.state}</span><div className="actions"><button onClick={()=>void switchTo(r.camera_id,"primary")}>Use primary</button><button onClick={()=>void switchTo(r.camera_id,"secondary")}>Use secondary</button></div></article>):<div className="sec-empty">No camera redundancy configured yet.</div>}</div></section></div>
 <section className="sec-res-card"><h2><DatabaseBackup size={18}/> Local / NAS archive replication</h2><p className="hint">Configured on each NVR with <code>CAMERA_BACKUP_ROOT</code>. This creates a second local/NAS copy; footage is never backed up to Ledgerly cloud.</p><div className="sec-val-grid">{backups.length?backups.map(b=><article key={b.server_id} className={b.status==="healthy"?"passed":b.status==="failed"?"failed":"warning"}><DatabaseBackup size={16}/><div><b>{b.server_name}</b><small>{b.enabled?`${b.target_label||"backup target"} · ${b.status}`:"Backup disabled"}</small><small>{b.pending_files||0} pending · {fmtBytes(b.pending_bytes||0)} · lag {b.lag_seconds==null?"—":fmtAge(b.lag_seconds)}</small>{b.last_error?<small>{b.last_error}</small>:null}</div><time>{b.last_success_at?`Last copy ${new Date(b.last_success_at).toLocaleString()}`:"No completed copy yet"}</time></article>):<div className="sec-empty">No NVR has reported backup status yet.</div>}</div></section>
 <section className="sec-res-card"><h2><Activity size={18}/> Appliance validation</h2><div className="sec-val-grid">{runs.slice(0,100).map(v=><article key={v.id} className={v.status}>{v.status==="passed"?<CheckCircle2 size={16}/>:<TriangleAlert size={16}/>}<div><b>{v.check_type.replace(/_/g," ")}</b><small>{v.message||"No details"}</small></div><time>{new Date(v.created_at).toLocaleString()}</time></article>)}</div></section>
 <section className="sec-res-card"><h2><ArrowLeftRight size={18}/> Failover history</h2><div className="sec-fail-table"><div className="head"><span>Camera</span><span>Move</span><span>Reason</span><span>Time</span></div>{events.map(e=><div key={e.id}><span><b>{e.camera_name}</b><small>{e.automatic?"automatic":"manual"}</small></span><span>{e.from_server_name||"—"} → {e.to_server_name||"—"}</span><span>{e.reason}</span><span>{new Date(e.created_at).toLocaleString()}</span></div>)}</div></section>{busy&&<div className="sec-sync">Refreshing resilience status…</div>}</div>}
function Stat({label,value}:{label:string;value:any}){return <div className="sec-res-stat"><span>{label}</span><b>{value}</b></div>}
function fmtBytes(v:number){if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;if(v<1073741824)return`${(v/1048576).toFixed(1)} MB`;return`${(v/1073741824).toFixed(1)} GB`}
function fmtAge(v:number){if(v<60)return`${v}s`;if(v<3600)return`${Math.round(v/60)}m`;return`${(v/3600).toFixed(1)}h`}
