import {useEffect,useMemo,useRef,useState} from "react";
import {Grid2X2,MonitorPlay,Play,RefreshCw,Save,Square} from "lucide-react";
import {get,post,errorText} from "../../../web/api";
import {WhepPlayer} from "./WhepPlayer";
type CameraRow={id:string;name:string;location?:string;status:string;server_id?:string;stream_status?:string;lifecycle_status?:string};
type Group={id:string;name:string;cameras:Array<{camera_id:string;camera_name:string}>};
type Wall={id:string;name:string;group_id?:string;columns:number;muted:number;cameras:Array<{camera_id:string;camera_name:string}>};
type Fleet={groups:Group[];views:Wall[]};
type Session={id:string;cameraId:string;cameraName:string;status:string;expiresAt:string;whepUrl:string;viewerToken:string};
export function SecurityCameraWall(){
 const[cameras,setCameras]=useState<CameraRow[]>([]),[fleet,setFleet]=useState<Fleet>({groups:[],views:[]}),[selected,setSelected]=useState<string[]>([]),[columns,setColumns]=useState(2),[viewId,setViewId]=useState(""),[sessions,setSessions]=useState<Record<string,Session>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),sessionsRef=useRef<Record<string,Session>>({});
 useEffect(()=>{sessionsRef.current=sessions},[sessions]);
 async function load(){setBusy(true);setError("");try{const[c,f]=await Promise.all([get<CameraRow[]>("/security-camera/cameras"),get<Fleet>("/security-camera/fleet")]);setCameras(c);setFleet(f);setSelected(s=>s.length?s:c.filter(x=>x.status==="online"&&x.stream_status==="online"&&x.lifecycle_status!=="disabled"&&x.lifecycle_status!=="decommissioned").slice(0,4).map(x=>x.id))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 useEffect(()=>{void load();return()=>{for(const s of Object.values(sessionsRef.current))void post(`/security-camera/live/${s.id}/end`,{}).catch(()=>{})}},[]);
 function chooseView(id:string){setViewId(id);const v=fleet.views.find(x=>x.id===id);if(!v)return;setColumns(Number(v.columns)||2);setSelected(v.cameras.map(x=>x.camera_id).slice(0,9))}
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length>=9?s:[...s,id])}
 async function start(){await stop();setBusy(true);setError("");const next:Record<string,Session>={};for(const id of selected){const c=cameras.find(x=>x.id===id);if(!c||c.status!=="online"||c.stream_status!=="online"||!c.server_id)continue;try{next[id]=await post<Session>(`/security-camera/cameras/${id}/live`,{})}catch(e){setError(prev=>prev||`${c.name}: ${errorText(e)}`)}}sessionsRef.current=next;setSessions(next);setBusy(false)}
 async function stop(){const old=sessionsRef.current;sessionsRef.current={};setSessions({});await Promise.allSettled(Object.values(old).map(s=>post(`/security-camera/live/${s.id}/end`,{})))}
 async function saveView(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post("/security-camera/wall-views",{name:f.get("name"),groupId:f.get("groupId")||null,columns,cameraIds:selected,muted:true});e.currentTarget.reset();await load()}catch(x){setError(errorText(x))}}
 const tiles=useMemo(()=>selected.map(id=>cameras.find(c=>c.id===id)).filter(Boolean) as CameraRow[],[selected,cameras]);
 return <div className="sec-wall"><header className="sec-wall-hero"><div><div className="sec-event-kicker"><MonitorPlay size={15}/> SECURITY MONITOR WALL</div><h1>Live camera wall</h1><p>Open up to nine authenticated NVR viewers at once. Each tile fans out from the existing NVR stream; phones continue one capture and local recording remains uninterrupted.</p></div><div className="sec-wall-actions"><button onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button>{Object.keys(sessions).length?<button className="danger" onClick={()=>void stop()}><Square size={14}/>Stop wall</button>:<button className="primary" onClick={()=>void start()}><Play size={14}/>Start wall</button>}</div></header>{error&&<div className="sec-error">{error}</div>}
 <section className="sec-wall-controls"><label>Saved view<select value={viewId} onChange={e=>chooseView(e.target.value)}><option value="">Custom selection</option>{fleet.views.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Columns<select value={columns} onChange={e=>setColumns(Number(e.target.value))}><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option><option value={4}>4</option></select></label><form onSubmit={saveView}><input name="name" required placeholder="Night security wall"/><select name="groupId"><option value="">No group</option>{fleet.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button><Save size={14}/>Save current view</button></form></section>
 <div className="sec-wall-picks">{cameras.map(c=><button key={c.id} className={selected.includes(c.id)?"active":""} disabled={c.lifecycle_status==="disabled"||c.lifecycle_status==="decommissioned"} onClick={()=>toggle(c.id)}><span className={`sec-status ${c.status}`}>{c.status}</span><b>{c.name}</b><small>{c.location||"No location"} · {c.stream_status||"stream offline"}</small></button>)}</div>
 <section className="sec-wall-grid" style={{gridTemplateColumns:`repeat(${Math.max(1,Math.min(4,columns))},minmax(0,1fr))`}}>{tiles.length?tiles.map(c=><article className="sec-wall-tile" key={c.id}><div className="sec-wall-label"><div><b>{c.name}</b><small>{c.location||"Security camera"}</small></div><span className={`sec-status ${c.status}`}>{c.status}</span></div>{sessions[c.id]?<WhepPlayer url={sessions[c.id].whepUrl} token={sessions[c.id].viewerToken} cameraName={c.name}/>:<div className="sec-wall-placeholder"><Grid2X2 size={30}/><b>{c.stream_status==="online"?"Ready for live wall":"NVR stream unavailable"}</b><small>{c.stream_status==="online"?"Start wall to request a short-lived viewer session.":"The camera can remain selected; it will become watchable when its NVR stream recovers."}</small></div>}</article>):<div className="sec-empty">Select cameras for this monitoring wall.</div>}</section>{busy?<div className="sec-sync">Updating monitoring wall…</div>:null}</div>
}
