import {useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,Bell,CheckCircle2,Clock3,History,RefreshCw,Server,ShieldCheck,UsersRound} from "lucide-react";
import {get,post,errorText} from "../../../web/api";

type Camera={id:string;name:string;location?:string;lifecycle_status?:string;recording_enabled?:number};
type Audit={id:string;actor_id:string;action:string;resource_type:string;resource_id?:string;camera_id?:string;server_id?:string;ip_address?:string;details:any;created_at:string};
type Policy={id:string;name:string;enabled:number;minimum_severity:string;eventTypes:string[];channels:string[];recipients:string[];escalation_minutes:number;cooldown_minutes:number};
type Queue={id:string;policy_name:string;alert_id:string;channel:string;recipient:string;status:string;attempts:number;not_before:string;last_error?:string;created_at:string};
type UpdatePolicy={server_id:string;name:string;app_version?:string;status:string;desired_version?:string;update_channel?:string;auto_update_enabled?:number;maintenance_start?:string;maintenance_end?:string};
export function SecurityCameraGovernance(){
 const[data,setData]=useState<any>(null),[audit,setAudit]=useState<Audit[]>([]),[cameras,setCameras]=useState<Camera[]>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const[g,a,c]=await Promise.all([get<any>("/security-camera/governance"),get<Audit[]>("/security-camera/audit?limit=300"),get<Camera[]>("/security-camera/cameras")]);setData(g);setAudit(a);setCameras(c)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),20000);return()=>clearInterval(t)},[]);
 async function savePolicy(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post("/security-camera/notification-policies",{name:f.get("name"),minimumSeverity:f.get("minimumSeverity"),eventTypes:String(f.get("eventTypes")||"").split(",").map(x=>x.trim()).filter(Boolean),channels:Array.from(f.getAll("channels")),recipients:String(f.get("recipients")||"").split(/[\n,;]/).map(x=>x.trim()).filter(Boolean),escalationMinutes:Number(f.get("escalationMinutes")||0),cooldownMinutes:Number(f.get("cooldownMinutes")||10),enabled:true});e.currentTarget.reset();await load()}catch(x){setError(errorText(x))}}
 async function bulk(action:string){if(!selected.length)return;const reason=action==="maintenance"?window.prompt("Reason for maintenance","")||"Bulk maintenance":null;try{await post("/security-camera/fleet/bulk",{cameraIds:selected,action,reason});setSelected([]);await load()}catch(x){setError(errorText(x))}}
 async function saveUpdate(serverId:string,e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post(`/security-camera/servers/${serverId}/update-policy`,{desiredVersion:f.get("desiredVersion")||null,updateChannel:f.get("updateChannel"),autoUpdateEnabled:f.get("autoUpdateEnabled")==="on",maintenanceStart:f.get("maintenanceStart")||null,maintenanceEnd:f.get("maintenanceEnd")||null});await load()}catch(x){setError(errorText(x))}}
 const overview=data?.overview||{},policies:Policy[]=data?.policies||[],queue:Queue[]=data?.queue||[],updates:UpdatePolicy[]=data?.updates||[];
 const stats=useMemo(()=>({criticalQueue:queue.filter(q=>q.status==="queued").length,failedQueue:queue.filter(q=>q.status==="failed").length}),[queue]);
 return <div className="sec-gov"><header className="sec-gov-hero"><div><div className="sec-gov-kicker"><ShieldCheck size={15}/> SECURITY GOVERNANCE</div><h1>Permissions, audit & escalation</h1><p>Control sensitive CCTV actions, track who accessed footage, route alerts through durable delivery jobs and manage NVR update policy.</p></div><button onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></header>{error&&<div className="sec-error">{error}</div>}
 <section className="sec-gov-stats"><Stat icon={<History/>} label="Audit events · 24h" value={overview.audit?.total||0}/><Stat icon={<Bell/>} label="Queued notifications" value={stats.criticalQueue}/><Stat icon={<AlertTriangle/>} label="Failed notifications" value={stats.failedQueue}/><Stat icon={<Server/>} label="NVR upgrades needed" value={overview.servers?.upgrade_needed||0}/></section>
 <div className="sec-gov-grid"><section className="sec-gov-card"><h2><Bell size={18}/> Escalation policies</h2><p>Jobs are provider-neutral. Communications workers can consume email, SMS, WhatsApp, in-app or webhook deliveries.</p><form className="sec-gov-policy" onSubmit={savePolicy}><input name="name" required placeholder="Critical after-hours security"/><select name="minimumSeverity"><option value="critical">Critical+</option><option value="warning">Warning+</option><option value="info">All severities</option></select><input name="eventTypes" placeholder="person,intrusion,camera_offline"/><input name="recipients" required placeholder="guard@example.com, +256..."/><div className="sec-channel-row"><label><input type="checkbox" name="channels" value="in_app" defaultChecked/> In-app</label><label><input type="checkbox" name="channels" value="email"/> Email</label><label><input type="checkbox" name="channels" value="sms"/> SMS</label><label><input type="checkbox" name="channels" value="whatsapp"/> WhatsApp</label><label><input type="checkbox" name="channels" value="webhook"/> Webhook</label></div><label>Escalate after minutes<input name="escalationMinutes" type="number" min="0" max="1440" defaultValue="0"/></label><label>Cooldown minutes<input name="cooldownMinutes" type="number" min="0" max="1440" defaultValue="10"/></label><button type="submit">Create policy</button></form><div className="sec-gov-list">{policies.map(p=><article key={p.id}><div><b>{p.name}</b><small>{p.minimum_severity} · {p.channels.join(", ")} · {p.recipients.length} recipient(s)</small></div><span>{p.enabled?"enabled":"disabled"}</span></article>)}</div></section>
 <section className="sec-gov-card"><h2><UsersRound size={18}/> Bulk fleet control</h2><p>Select cameras and apply an operational change as one audited batch.</p><div className="sec-bulk-actions"><button disabled={!selected.length} onClick={()=>void bulk("pause_recording")}>Pause recording</button><button disabled={!selected.length} onClick={()=>void bulk("resume_recording")}>Resume recording</button><button disabled={!selected.length} onClick={()=>void bulk("maintenance")}>Maintenance</button><button disabled={!selected.length} onClick={()=>void bulk("activate")}>Activate</button></div><div className="sec-camera-checks">{cameras.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(x=>e.target.checked?[...x,c.id]:x.filter(id=>id!==c.id))}/><span><b>{c.name}</b><small>{c.location||"No location"} · {c.lifecycle_status||"active"} · {c.recording_enabled===0?"recording paused":"recording enabled"}</small></span></label>)}</div></section></div>
 <section className="sec-gov-card"><h2><Server size={18}/> NVR update policy</h2><div className="sec-update-grid">{updates.map(s=><form key={s.server_id} onSubmit={e=>void saveUpdate(s.server_id,e)}><div><b>{s.name}</b><small>Installed {s.app_version||"unknown"} · {s.status}</small></div><label>Desired version<input name="desiredVersion" defaultValue={s.desired_version||""} placeholder="0.9.0"/></label><label>Channel<select name="updateChannel" defaultValue={s.update_channel||"stable"}><option value="stable">Stable</option><option value="candidate">Candidate</option><option value="pinned">Pinned</option></select></label><label>Maintenance start<input name="maintenanceStart" type="time" defaultValue={s.maintenance_start||"02:00"}/></label><label>Maintenance end<input name="maintenanceEnd" type="time" defaultValue={s.maintenance_end||"04:00"}/></label><label className="sec-auto"><input name="autoUpdateEnabled" type="checkbox" defaultChecked={Boolean(s.auto_update_enabled)}/> Permit safe auto-update</label><button>Save NVR policy</button></form>)}</div></section>
 <div className="sec-gov-grid"><section className="sec-gov-card"><h2><Activity size={18}/> Notification queue</h2><div className="sec-gov-table"><div className="head"><span>Policy</span><span>Destination</span><span>Status</span><span>When</span></div>{queue.slice(0,100).map(q=><div key={q.id}><span><b>{q.policy_name}</b><small>{q.channel}</small></span><span>{q.recipient}</span><span className={`state ${q.status}`}>{q.status}{q.attempts?` · ${q.attempts} attempt(s)`:""}</span><span>{new Date(q.not_before).toLocaleString()}</span></div>)}</div></section>
 <section className="sec-gov-card"><h2><Clock3 size={18}/> Recent security audit</h2><div className="sec-audit-list">{audit.slice(0,120).map(a=><article key={a.id}><div><b>{label(a.action)}</b><small>{a.actor_id} · {a.resource_type}{a.resource_id?` · ${a.resource_id}`:""}</small></div><time>{new Date(a.created_at).toLocaleString()}</time>{a.ip_address?<small>IP {a.ip_address}</small>:null}</article>)}</div></section></div>
 <section className="sec-gov-card sec-scope-card"><h2><CheckCircle2 size={18}/> Security scopes</h2><div className="sec-scope-grid"><Scope n="security:read" t="See cameras, health, timelines and governance metadata"/><Scope n="security:live" t="Open and close live viewer sessions"/><Scope n="security:export" t="Create downloadable footage exports"/><Scope n="security:review" t="Review events, evidence, incidents and alerts"/><Scope n="security:manage" t="Pair/revoke devices, configure cameras, NVRs and policies"/></div><p>Owner/admin roles bypass explicit scopes. Legacy <code>school:read/write</code> remains accepted temporarily for compatibility while existing roles are migrated.</p></section>{busy&&<div className="sec-sync">Refreshing security governance…</div>}</div>
}
function Stat({icon,label,value}:{icon:any;label:string;value:any}){return <div className="sec-gov-stat"><i>{icon}</i><span>{label}</span><b>{value}</b></div>}
function Scope({n,t}:{n:string;t:string}){return <div><code>{n}</code><span>{t}</span></div>}
function label(v:string){return String(v||"").replace(/[._]/g," ").replace(/\b\w/g,m=>m.toUpperCase())}
