import {useEffect,useMemo,useState} from "react";
import {Crosshair,Image as ImageIcon,RotateCcw,Save,Undo2} from "lucide-react";
import {post,errorText} from "../../../web/api";

type CameraRow={id:string;name:string;location?:string};
type Zone={id:string;camera_id:string;name:string;zone_type:string;polygon:Array<[number,number]>;enabled:number};
export function ZoneEditor({cameras,zones,onSaved}:{cameras:CameraRow[];zones:Zone[];onSaved:()=>Promise<void>|void}){
 const[cameraId,setCameraId]=useState(cameras[0]?.id||""),[zoneId,setZoneId]=useState(""),[name,setName]=useState("Detection zone"),[zoneType,setZoneType]=useState("motion"),[points,setPoints]=useState<Array<[number,number]>>([]),[snapshot,setSnapshot]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!cameraId&&cameras[0])setCameraId(cameras[0].id)},[cameras.length]);
 useEffect(()=>{setSnapshot("");setError("");if(!cameraId)return;void post<any>(`/security-camera/cameras/${cameraId}/snapshot`,{}).then(x=>setSnapshot(x.url)).catch(()=>{})},[cameraId]);
 const cameraZones=useMemo(()=>zones.filter(z=>z.camera_id===cameraId),[zones,cameraId]);
 function edit(id:string){const z=zones.find(x=>x.id===id);if(!z)return;setCameraId(z.camera_id);setZoneId(z.id);setName(z.name);setZoneType(z.zone_type);setPoints(Array.isArray(z.polygon)?z.polygon:[])}
 function click(e:React.MouseEvent<SVGSVGElement>){if(points.length>=16)return;const r=e.currentTarget.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));setPoints(p=>[...p,[Number(x.toFixed(4)),Number(y.toFixed(4))]])}
 async function save(){if(!cameraId)return setError("Choose a camera first");if(points.length<3)return setError("Draw at least three points around the detection area");setBusy(true);setError("");try{const result=await post<any>(`/security-camera/cameras/${cameraId}/zones`,{id:zoneId||undefined,name,zoneType,polygon:points,enabled:true});setZoneId(result.id);await onSaved()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 function fresh(){setZoneId("");setName("Detection zone");setZoneType("motion");setPoints([])}
 const polygon=points.map(([x,y])=>`${x*1000},${y*562}`).join(" ");
 return <div className="sec-zone-editor"><div className="sec-zone-toolbar"><label>Camera<select value={cameraId} onChange={e=>{setCameraId(e.target.value);fresh()}}>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Zone<select value={zoneId} onChange={e=>e.target.value?edit(e.target.value):fresh()}><option value="">New zone</option>{cameraZones.map(z=><option value={z.id} key={z.id}>{z.name}</option>)}</select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Type<select value={zoneType} onChange={e=>setZoneType(e.target.value)}><option value="motion">Motion</option><option value="person">Person/object</option><option value="line">Line crossing</option><option value="exclude">Exclusion</option></select></label></div><div className="sec-zone-canvas"><svg viewBox="0 0 1000 562" preserveAspectRatio="none" onClick={click}>{snapshot?<image href={snapshot} x="0" y="0" width="1000" height="562" preserveAspectRatio="xMidYMid slice"/>:<><rect width="1000" height="562" fill="#071c16"/><text x="500" y="270" textAnchor="middle" fill="#a7bfb4" fontSize="28">No recent snapshot available</text><text x="500" y="310" textAnchor="middle" fill="#729285" fontSize="18">You can still draw normalized zones</text></>}{points.length>1&&<polyline points={polygon} fill={points.length>2?"rgba(31,157,101,.22)":"none"} stroke="#58dda0" strokeWidth="5" vectorEffect="non-scaling-stroke"/>}{points.length>2&&<line x1={points.at(-1)![0]*1000} y1={points.at(-1)![1]*562} x2={points[0][0]*1000} y2={points[0][1]*562} stroke="#58dda0" strokeWidth="5" vectorEffect="non-scaling-stroke"/>}{points.map((p,i)=><g key={i}><circle cx={p[0]*1000} cy={p[1]*562} r="11" fill="#fff" stroke="#16835f" strokeWidth="5" vectorEffect="non-scaling-stroke"/><text x={p[0]*1000+15} y={p[1]*562-15} fill="#fff" fontSize="19" paintOrder="stroke" stroke="#071c16" strokeWidth="6">{i+1}</text></g>)}</svg><div className="sec-zone-hint"><Crosshair size={14}/> Click around the real camera image to define the polygon. Up to 16 points.</div></div>{error&&<div className="sec-error">{error}</div>}<div className="sec-zone-actions"><button onClick={()=>setPoints(p=>p.slice(0,-1))} disabled={!points.length}><Undo2 size={14}/>Undo point</button><button onClick={()=>setPoints([[0,0],[1,0],[1,1],[0,1]])}><ImageIcon size={14}/>Full frame</button><button onClick={fresh}><RotateCcw size={14}/>New</button><button className="primary" disabled={busy} onClick={()=>void save()}><Save size={14}/>{busy?"Saving…":"Save zone"}</button></div></div>
}
