import {useEffect,useMemo,useState} from "react";
import {RefreshControl,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import type {MobileSession} from "./auth";
import type {SessionUpdater} from "./apiClient";
import {enabledMobileModules,type ModuleAvailability} from "./moduleAvailability";

type GroupKey="school"|"people"|"finance";
type ModuleItem={key:string;group:GroupKey;icon:string;title:string;copy:string;onPress:()=>void};

export function HomeScreen({session,onSession,onAttendance,onSchool,onAcademics,onExams,onBooks,onHumanResources,onPayrollPayments,onContacts,onCommunications,onTasksWork,onFinanceCore,onPrinterly,onSecurityCameras,onLogout}:{session:MobileSession;onSession:SessionUpdater;onAttendance:()=>void;onSchool:()=>void;onAcademics:()=>void;onExams:()=>void;onBooks:()=>void;onHumanResources:()=>void;onPayrollPayments:()=>void;onContacts:()=>void;onCommunications:()=>void;onTasksWork:()=>void;onFinanceCore:()=>void;onPrinterly:()=>void;onSecurityCameras:()=>void;onLogout:()=>void}){
 const name=session.identifier.includes("@")?session.identifier.split("@")[0]:session.identifier;
 const[enabledKeys,setEnabledKeys]=useState<Set<string>|null>(null),[source,setSource]=useState<ModuleAvailability["source"]>("unverified"),[refreshing,setRefreshing]=useState(false),[moduleError,setModuleError]=useState("");
 async function load(){setRefreshing(true);setModuleError("");try{const result=await enabledMobileModules(session,onSession);setSource(result.source);setEnabledKeys(result.modules?new Set(result.modules.map(x=>x.moduleKey)):null)}catch(e){setModuleError(e instanceof Error?e.message:String(e))}finally{setRefreshing(false)}}
 useEffect(()=>{void load()},[session.accessToken,session.organizationId,session.apiUrl]);
 const all:ModuleItem[]=[
  {key:"attendance",group:"school",icon:"✓",title:"Attendance",copy:"Capture and review student and staff attendance, including offline-ready kiosk workflows.",onPress:onAttendance},
  {key:"school-management",group:"school",icon:"S",title:"School Management",copy:"Learners, staff, fees, discipline, promotions, school setup and access control.",onPress:onSchool},
  {key:"academics",group:"school",icon:"A",title:"Academics",copy:"Timetables, schemes of work, lesson planning, supervision and teaching resources.",onPress:onAcademics},
  {key:"exams",group:"school",icon:"E",title:"Examinations",copy:"Exam setup, marks entry, Uganda PLE grading, report cards and results audit.",onPress:onExams},
  {key:"books",group:"school",icon:"B",title:"Books",copy:"Manage writing-book stock, learner issues, reversals and class coverage reports.",onPress:onBooks},
  {key:"human-resources",group:"people",icon:"H",title:"Human Resources",copy:"Staff records, employment, onboarding, leave, requests and approvals.",onPress:onHumanResources},
  {key:"contacts",group:"people",icon:"C",title:"Contacts",copy:"Shared people directory for school, communications and operational workflows.",onPress:onContacts},
  {key:"communications",group:"people",icon:"M",title:"Messages & Notifications",copy:"SMS, approved WhatsApp templates, campaigns, schedules and delivery history.",onPress:onCommunications},
  {key:"tasks-work",group:"people",icon:"W",title:"Tasks & Work",copy:"Projects, assignments, checklists, comments, time tracking and work chat.",onPress:onTasksWork},
  {key:"payroll-payments",group:"finance",icon:"$",title:"Payroll & Payments",copy:"Payroll, payslips, salary batches, supplier payments, receipts and reversals.",onPress:onPayrollPayments},
  {key:"ledgerly-core",group:"finance",icon:"₵",title:"Ledgerly Finance Core",copy:"Accounts, journals, banking, budgets, inventory, tax and finance reports.",onPress:onFinanceCore},
  {key:"printerly",group:"finance",icon:"P",title:"Printerly",copy:"Remote printing, secure release, printer health, costing and usage reporting.",onPress:onPrinterly},
  {key:"security-camera",group:"finance",icon:"V",title:"Security Cameras",copy:"Camera pairing, live view, local NVR archive, events, health and recovery.",onPress:onSecurityCameras},
 ];
 const modules=enabledKeys?all.filter(x=>enabledKeys.has(x.key)):all;
 const groups=useMemo(()=>[
  {key:"school" as GroupKey,title:"School & learning",copy:"Daily academic and school operations"},
  {key:"people" as GroupKey,title:"People & communication",copy:"Staff, contacts, messaging and teamwork"},
  {key:"finance" as GroupKey,title:"Finance & services",copy:"Money, printing and physical operations"},
 ].map(g=>({...g,items:modules.filter(x=>x.group===g.key)})).filter(g=>g.items.length),[modules]);
 const Module=({item}:{item:ModuleItem})=><TouchableOpacity accessibilityRole="button" activeOpacity={.88} style={s.module} onPress={item.onPress}><View style={s.moduleTop}><View style={s.icon}><Text style={s.iconText}>{item.icon}</Text></View><View style={s.moduleText}><Text style={s.moduleTitle}>{item.title}</Text><Text style={s.moduleCopy}>{item.copy}</Text></View><Text style={s.moduleArrow}>›</Text></View></TouchableOpacity>;
 return <SafeAreaView style={s.root}><StatusBar barStyle="light-content" backgroundColor="#071c16"/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load}/>} contentContainerStyle={s.scroll}>
  <View style={s.header}><View><Text style={s.brand}>ledgerly</Text><Text style={s.mobile}>MOBILE WORKSPACE</Text></View><View style={s.avatar}><Text style={s.avatarText}>{(name[0]||"L").toUpperCase()}</Text></View></View>
  <View style={s.hero}><View style={s.heroGlow}/><Text style={s.hello}>WELCOME BACK</Text><Text style={s.title}>{name||"Ledgerly user"}</Text><Text style={s.heroCopy}>Choose a work area below. Only modules enabled for your organisation are shown.</Text><View style={s.sessionRow}><View style={s.onlineDot}/><Text style={s.sessionText}>Signed in securely</Text></View></View>
  <View style={s.workspaceHead}><View style={{flex:1}}><Text style={s.sectionEyebrow}>YOUR WORKSPACE</Text><Text style={s.sectionTitle}>What do you need to do?</Text><Text style={s.availability}>{source==="server"?"Live organisation access":source==="cache"?"Offline · showing last verified access":"Offline · access not yet verified"}</Text></View><View style={s.count}><Text style={s.countText}>{modules.length}</Text><Text style={s.countLabel}>modules</Text></View></View>
  {moduleError?<View style={s.error}><View style={{flex:1}}><Text style={s.errorTitle}>Couldn’t refresh module access</Text><Text style={s.errorText}>{moduleError}</Text></View><TouchableOpacity accessibilityRole="button" style={s.retryButton} onPress={()=>void load()}><Text style={s.retry}>Retry</Text></TouchableOpacity></View>:null}
  {groups.map(group=><View key={group.key} style={s.group}><View style={s.groupHead}><Text style={s.groupTitle}>{group.title}</Text><Text style={s.groupCopy}>{group.copy}</Text></View><View style={s.groupList}>{group.items.map(item=><Module key={item.key} item={item}/>)}</View></View>)}
  {!modules.length?<View style={s.none}><Text style={s.noneTitle}>No mobile modules are enabled</Text><Text style={s.noneCopy}>Ask an organisation administrator to enable the modules needed for your work.</Text></View>:null}
  <View style={s.roadmap}><Text style={s.roadmapTitle}>Works with your organisation settings</Text><Text style={s.roadmapText}>Ledgerly Mobile keeps the last verified module list available when the network is down.</Text></View>
  <TouchableOpacity accessibilityRole="button" style={s.logout} onPress={onLogout}><Text style={s.logoutText}>Sign out of Ledgerly</Text></TouchableOpacity>
 </ScrollView></SafeAreaView>
}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:"#f3f6f4"},scroll:{paddingBottom:34},header:{height:74,backgroundColor:"#071c16",paddingHorizontal:20,flexDirection:"row",alignItems:"center"},brand:{color:"white",fontSize:21,lineHeight:25,fontWeight:"900",letterSpacing:-.4},mobile:{color:"#83a394",fontSize:11,lineHeight:14,fontWeight:"900",letterSpacing:1,marginTop:2},avatar:{marginLeft:"auto",width:44,height:44,borderRadius:14,backgroundColor:"#174335",borderWidth:1,borderColor:"#2d604c",alignItems:"center",justifyContent:"center"},avatarText:{color:"#d6f4e4",fontSize:16,fontWeight:"900"},
 hero:{backgroundColor:"#071c16",paddingHorizontal:20,paddingTop:22,paddingBottom:28,overflow:"hidden"},heroGlow:{position:"absolute",width:190,height:190,borderRadius:95,backgroundColor:"#0b5138",right:-70,top:-80,opacity:.55},hello:{color:"#62d39d",fontSize:12,lineHeight:16,fontWeight:"900",letterSpacing:1},title:{color:"white",fontSize:32,lineHeight:38,fontWeight:"900",letterSpacing:-.8,marginTop:7,textTransform:"capitalize"},heroCopy:{color:"#b6ccc2",fontSize:14,lineHeight:21,maxWidth:340,marginTop:8},sessionRow:{marginTop:17,flexDirection:"row",alignItems:"center"},onlineDot:{width:8,height:8,borderRadius:4,backgroundColor:"#45c98a",marginRight:8},sessionText:{color:"#c4d7cf",fontSize:12,lineHeight:16,fontWeight:"800"},
 workspaceHead:{paddingHorizontal:20,paddingTop:22,paddingBottom:12,flexDirection:"row",alignItems:"center"},sectionEyebrow:{fontSize:11,lineHeight:14,fontWeight:"900",color:"#178c5b",letterSpacing:.8},sectionTitle:{fontSize:23,lineHeight:29,fontWeight:"900",color:"#14271f",marginTop:4,letterSpacing:-.4},availability:{fontSize:12,lineHeight:17,color:"#708078",fontWeight:"700",marginTop:5},count:{marginLeft:12,minWidth:62,backgroundColor:"#e1ebe6",borderRadius:18,paddingHorizontal:10,paddingVertical:8,alignItems:"center"},countText:{fontSize:18,lineHeight:21,fontWeight:"900",color:"#365347"},countLabel:{fontSize:10,lineHeight:13,fontWeight:"800",color:"#6d8177",marginTop:1},
 error:{marginHorizontal:20,marginBottom:14,backgroundColor:"#fff3f1",borderRadius:17,padding:14,flexDirection:"row",alignItems:"center",gap:10,borderWidth:1,borderColor:"#f0d4d0"},errorTitle:{fontSize:14,lineHeight:18,fontWeight:"900",color:"#8a423d"},errorText:{fontSize:12,lineHeight:18,color:"#8e5b56",marginTop:3},retryButton:{minHeight:44,minWidth:64,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:"#edf8f2"},retry:{fontSize:13,fontWeight:"900",color:"#138c5a"},
 group:{marginTop:8},groupHead:{paddingHorizontal:20,paddingTop:8,paddingBottom:8},groupTitle:{fontSize:18,lineHeight:23,fontWeight:"900",color:"#203a2f"},groupCopy:{fontSize:12,lineHeight:17,color:"#74847c",marginTop:3},groupList:{gap:10},
 module:{marginHorizontal:20,backgroundColor:"white",borderRadius:18,padding:16,borderWidth:1,borderColor:"#dce5e0",shadowColor:"#163226",shadowOpacity:.04,shadowRadius:8,shadowOffset:{width:0,height:4},elevation:1},moduleTop:{flexDirection:"row",alignItems:"center"},icon:{width:48,height:48,borderRadius:14,backgroundColor:"#dff3e9",alignItems:"center",justifyContent:"center",marginRight:13},iconText:{fontSize:20,fontWeight:"900",color:"#138c5a"},moduleText:{flex:1},moduleTitle:{fontSize:16,lineHeight:21,fontWeight:"900",color:"#13271f"},moduleCopy:{fontSize:12.5,lineHeight:18,color:"#687a71",marginTop:3},moduleArrow:{fontSize:27,lineHeight:30,color:"#3d9d72",marginLeft:9},
 none:{marginHorizontal:20,backgroundColor:"white",borderRadius:20,padding:20,borderWidth:1,borderColor:"#dce5e0"},noneTitle:{fontSize:17,lineHeight:22,fontWeight:"900",color:"#293d34"},noneCopy:{fontSize:13,lineHeight:19,color:"#74847c",marginTop:6},roadmap:{marginHorizontal:20,marginTop:18,borderRadius:18,backgroundColor:"#e9efec",padding:18},roadmapTitle:{fontSize:16,lineHeight:21,fontWeight:"900",color:"#293d34"},roadmapText:{fontSize:13,lineHeight:19,color:"#6f8178",marginTop:5},logout:{alignSelf:"center",minHeight:52,justifyContent:"center",paddingHorizontal:18,marginTop:8},logoutText:{color:"#687a71",fontSize:13,lineHeight:17,fontWeight:"800"}
});
