import fs from "node:fs";
import path from "node:path";

const VIDEO=/^(\d{4}-\d{2}-\d{2})_(\d{2})-(\d{2})-(\d{2})(?:-(\d+))?\.mp4$/;
function writable(root){try{fs.mkdirSync(root,{recursive:true});const f=path.join(root,`.ledgerly-backup-health-${process.pid}`);fs.writeFileSync(f,"ok");fs.rmSync(f);return true}catch{return false}}
function signature(row){let integrity="none";try{const st=fs.statSync(`${row.path}.integrity.json`);integrity=`${st.size}:${st.mtimeMs}`}catch{}return`${row.sizeBytes}:${row.modifiedAt}:${row.protected?1:0}:${integrity}`}
function segmentTime(name,fallback){const m=VIDEO.exec(name);if(!m)return fallback;const[,date,h,mn,s]=m,d=new Date(`${date}T${h}:${mn}:${s}`);return Number.isNaN(d.getTime())?fallback:d.getTime()}
function videoFiles(root){const out=[];if(!root||!fs.existsSync(root))return out;for(const c of fs.readdirSync(root,{withFileTypes:true})){if(!c.isDirectory())continue;const dir=path.join(root,c.name);for(const f of fs.readdirSync(dir,{withFileTypes:true}))if(f.isFile()&&f.name.endsWith(".mp4")){const full=path.join(dir,f.name),st=fs.statSync(full);out.push({path:full,cameraId:c.name,startedMs:segmentTime(f.name,st.mtimeMs),protected:fs.existsSync(`${full}.protected`),mtimeMs:st.mtimeMs,sizeBytes:st.size})}}return out}
function activeHolds(){try{const serverState=path.resolve(process.env.CAMERA_SERVER_STATE||"./camera-server-state.json"),file=path.resolve(process.env.CAMERA_FORENSICS_STATE||path.join(path.dirname(serverState),"camera-forensics-state.json")),data=JSON.parse(fs.readFileSync(file,"utf8"));return Array.isArray(data?.holds)?data.holds:[]}catch{return[]}}
function held(file,holds){return(holds||[]).some(h=>h.camera_id===file.cameraId&&file.mtimeMs>=Date.parse(h.from_at)&&file.startedMs<=Date.parse(h.to_at))}
export class BackupReplicator{
 constructor({catalog,root,stateFile,maxPerRun=20,retentionDays=90}){this.catalog=catalog;this.root=String(root||"").trim()?path.resolve(root):"";this.stateFile=path.resolve(stateFile||"./camera-backup-state.json");this.maxPerRun=Math.max(1,Math.min(200,Number(maxPerRun)||20));this.retentionDays=Math.max(1,Number(retentionDays)||90);this.state={completed:{},replicatedFiles:0,replicatedBytes:0,lastSuccessAt:null,lastAttemptAt:null,lastError:null};this.running=false;this.snapshot={enabled:Boolean(this.root),status:this.root?"starting":"disabled",targetLabel:this.root?(path.basename(this.root)||"backup"):null,pendingFiles:0,pendingBytes:0,replicatedFiles:0,replicatedBytes:0,lagSeconds:null,lastSuccessAt:null,lastAttemptAt:null,lastError:null,details:{writable:false,retentionDays:this.retentionDays}};this.load()}
 load(){try{this.state={...this.state,...JSON.parse(fs.readFileSync(this.stateFile,"utf8"))}}catch{}}
 save(){try{fs.mkdirSync(path.dirname(this.stateFile),{recursive:true});fs.writeFileSync(this.stateFile,JSON.stringify(this.state,null,2),{mode:0o600})}catch{}}
 enabled(){return Boolean(this.root)}
 destination(row){return path.join(this.root,row.cameraId,row.name)}
 pending(){if(!this.enabled())return[];const out=[];for(const cameraId of this.catalog.cameras())for(const row of this.catalog.all(cameraId)){const done=this.state.completed?.[row.id],dest=this.destination(row);if(done===signature(row)&&fs.existsSync(dest))continue;out.push(row)}return out.sort((a,b)=>Number(b.protected)-Number(a.protected)||a.startedAt.localeCompare(b.startedAt))}
 refresh(){if(!this.enabled()){this.snapshot={...this.snapshot,enabled:false,status:"disabled"};return this.snapshot}const pending=this.pending(),oldest=pending[0],lag=oldest?Math.max(0,Math.round((Date.now()-Date.parse(oldest.startedAt))/1000)):0,ok=writable(this.root),status=!ok?"failed":this.state.lastError?"warning":lag>3600?"lagging":"healthy";this.snapshot={enabled:true,status,targetLabel:path.basename(this.root)||"backup",pendingFiles:pending.length,pendingBytes:pending.reduce((n,x)=>n+x.sizeBytes,0),replicatedFiles:Number(this.state.replicatedFiles||0),replicatedBytes:Number(this.state.replicatedBytes||0),lagSeconds:lag,lastSuccessAt:this.state.lastSuccessAt||null,lastAttemptAt:this.state.lastAttemptAt||null,lastError:this.state.lastError||null,details:{writable:ok,retentionDays:this.retentionDays,integritySidecars:true,legalHoldAware:true}};return this.snapshot}
 health(){return this.snapshot}
 cleanup(){if(!this.enabled())return{deleted:0,freedBytes:0,heldFiles:0};const cutoff=Date.now()-this.retentionDays*86400000,holds=activeHolds();let deleted=0,freedBytes=0,heldFiles=0;for(const f of videoFiles(this.root)){if(f.protected){continue}if(held(f,holds)){heldFiles++;continue}if(f.mtimeMs>=cutoff)continue;try{fs.rmSync(f.path);fs.rmSync(`${f.path}.protected`,{force:true});fs.rmSync(`${f.path}.integrity.json`,{force:true});deleted++;freedBytes+=f.sizeBytes}catch{}}return{deleted,freedBytes,heldFiles,retentionDays:this.retentionDays}}
 async run(){if(!this.enabled()||this.running)return this.health();this.running=true;this.state.lastAttemptAt=new Date().toISOString();try{if(!writable(this.root))throw new Error("Backup target is not writable");const rows=this.pending().slice(0,this.maxPerRun);for(const row of rows){const dest=this.destination(row);fs.mkdirSync(path.dirname(dest),{recursive:true});const tmp=`${dest}.partial-${process.pid}`;await fs.promises.copyFile(row.path,tmp);const src=await fs.promises.stat(row.path),dst=await fs.promises.stat(tmp);if(src.size!==dst.size){await fs.promises.rm(tmp,{force:true});throw new Error(`Backup size verification failed for ${row.cameraId}/${row.name}`)}await fs.promises.rename(tmp,dest);if(row.protected)await fs.promises.writeFile(`${dest}.protected`,JSON.stringify({replicatedAt:new Date().toISOString(),source:`${row.cameraId}/${row.name}`}));else await fs.promises.rm(`${dest}.protected`,{force:true});const integrity=`${row.path}.integrity.json`;if(fs.existsSync(integrity))await fs.promises.copyFile(integrity,`${dest}.integrity.json`);else await fs.promises.rm(`${dest}.integrity.json`,{force:true});this.state.completed[row.id]=signature(row);this.state.replicatedFiles=Number(this.state.replicatedFiles||0)+1;this.state.replicatedBytes=Number(this.state.replicatedBytes||0)+row.sizeBytes;this.state.lastSuccessAt=new Date().toISOString()}this.state.lastError=null;this.cleanup();if(Object.keys(this.state.completed).length>100000){const active=new Set();for(const c of this.catalog.cameras())for(const r of this.catalog.all(c))active.add(r.id);for(const k of Object.keys(this.state.completed))if(!active.has(k))delete this.state.completed[k]}this.save();return this.refresh()}catch(error){this.state.lastError=error instanceof Error?error.message:String(error);this.save();return this.refresh()}finally{this.running=false}}
}
