import fs from "node:fs";
import path from "node:path";

const VIDEO=/^(\d{4}-\d{2}-\d{2})_(\d{2})-(\d{2})-(\d{2})(?:-(\d+))?\.mp4$/;
function safeId(value){if(!/^[A-Za-z0-9_-]{3,100}$/.test(value))throw new Error("Invalid camera id");return value}
function segmentTime(name){const m=VIDEO.exec(name);if(!m)return null;const[,date,h,mn,s]=m,d=new Date(`${date}T${h}:${mn}:${s}Z`);return Number.isNaN(d.getTime())?null:d}
function walkRoot(root,cameraId,key){const dir=path.join(root,safeId(cameraId));if(!fs.existsSync(dir))return[];return fs.readdirSync(dir,{withFileTypes:true}).filter(x=>x.isFile()&&VIDEO.test(x.name)).map(x=>{const file=path.join(dir,x.name),st=fs.statSync(file),started=segmentTime(x.name);return{id:`${key}:${cameraId}:${x.name}`,cameraId,name:x.name,path:file,root,volumeKey:key,relativePath:`${key}:${path.relative(root,file)}`,startedAt:(started||st.birthtime).toISOString(),modifiedAt:st.mtime.toISOString(),sizeBytes:st.size,protected:fs.existsSync(`${file}.protected`)}})}
function held(row,holds){const start=Date.parse(row.startedAt),end=Date.parse(row.modifiedAt||row.startedAt);return(holds||[]).some(h=>h.camera_id===row.cameraId&&end>=Date.parse(h.from_at)&&start<=Date.parse(h.to_at))}
export class RecordingCatalog{
 constructor({storageRoot,storageRoots,retentionDays=30,maxStoragePercent=90}){this.storageRoots=(storageRoots&&storageRoots.length?storageRoots:[storageRoot]).map(x=>path.resolve(x));this.retentionDays=Math.max(1,Number(retentionDays)||30);this.maxStoragePercent=Math.min(99,Math.max(50,Number(maxStoragePercent)||90));const serverState=path.resolve(process.env.CAMERA_SERVER_STATE||"./camera-server-state.json");this.forensicsStateFile=path.resolve(process.env.CAMERA_FORENSICS_STATE||path.join(path.dirname(serverState),"camera-forensics-state.json"));for(const r of this.storageRoots)try{fs.mkdirSync(r,{recursive:true})}catch{}}
 key(i){return`v${i}`}
 cameras(){const set=new Set();for(const root of this.storageRoots){if(!fs.existsSync(root))continue;for(const x of fs.readdirSync(root,{withFileTypes:true}))if(x.isDirectory()&&/^[A-Za-z0-9_-]{3,100}$/.test(x.name))set.add(x.name)}return[...set].sort()}
 all(cameraId){return this.storageRoots.flatMap((root,i)=>walkRoot(root,cameraId,this.key(i))).sort((a,b)=>a.startedAt.localeCompare(b.startedAt)||a.name.localeCompare(b.name))}
 list(cameraId,{from,to,limit=500}={}){let rows=this.all(cameraId);if(from){const t=new Date(from).getTime();if(!Number.isNaN(t))rows=rows.filter(x=>new Date(x.modifiedAt).getTime()>=t)}if(to){const t=new Date(to).getTime();if(!Number.isNaN(t))rows=rows.filter(x=>new Date(x.startedAt).getTime()<=t)}return rows.slice(-Math.min(5000,Math.max(1,Number(limit)||500)))}
 summary(cameraId){const rows=this.all(cameraId),bytes=rows.reduce((n,x)=>n+x.sizeBytes,0);return{cameraId,segments:rows.length,sizeBytes:bytes,oldestAt:rows[0]?.startedAt||null,newestAt:rows.at(-1)?.startedAt||null,protectedSegments:rows.filter(x=>x.protected).length,volumes:[...new Set(rows.map(x=>x.volumeKey))].length}}
 resolve(localPath){const raw=String(localPath||"");const m=/^(v\d+):(.*)$/.exec(raw);if(m){const i=Number(m[1].slice(1)),root=this.storageRoots[i],rel=m[2];if(root){const full=path.resolve(root,rel);if(full.startsWith(root+path.sep)&&fs.existsSync(full))return full}}for(const root of this.storageRoots){const full=path.resolve(root,raw);if(full.startsWith(root+path.sep)&&fs.existsSync(full))return full}return null}
 protect(cameraId,name,enabled=true){safeId(cameraId);if(!VIDEO.test(name))throw new Error("Invalid segment name");const row=this.all(cameraId).find(x=>x.name===name);if(!row)throw new Error("Recording segment not found");const marker=`${row.path}.protected`;if(enabled)fs.writeFileSync(marker,JSON.stringify({protectedAt:new Date().toISOString()}));else if(fs.existsSync(marker))fs.rmSync(marker);return{cameraId,name,protected:enabled}}
 activeHolds(){try{const data=JSON.parse(fs.readFileSync(this.forensicsStateFile,"utf8"));return Array.isArray(data?.holds)?data.holds:[]}catch{return[]}}
 cleanup(retentionByCamera={},holds=this.activeHolds()){const candidates=[];for(const cameraId of this.cameras())for(const row of this.all(cameraId))if(!row.protected&&!held(row,holds))candidates.push(row);candidates.sort((a,b)=>a.startedAt.localeCompare(b.startedAt)||a.name.localeCompare(b.name));let deleted=0,freedBytes=0,heldSegments=0;for(const cameraId of this.cameras())for(const row of this.all(cameraId))if(!row.protected&&held(row,holds))heldSegments++;for(const row of candidates){const days=Math.max(1,Number(retentionByCamera[row.cameraId])||this.retentionDays),cutoff=Date.now()-days*86400000;if(new Date(row.startedAt).getTime()<cutoff){try{fs.rmSync(row.path);fs.rmSync(`${row.path}.integrity.json`,{force:true});deleted++;freedBytes+=row.sizeBytes}catch{}}}for(const root of this.storageRoots){let st;try{st=fs.statfsSync(root)}catch{continue}let usedPercent=100-(Number(st.bavail)*100/Number(st.blocks));for(const row of candidates.filter(x=>x.root===root)){if(usedPercent<=this.maxStoragePercent)break;if(!fs.existsSync(row.path))continue;try{fs.rmSync(row.path);fs.rmSync(`${row.path}.integrity.json`,{force:true});deleted++;freedBytes+=row.sizeBytes;st=fs.statfsSync(root);usedPercent=100-(Number(st.bavail)*100/Number(st.blocks))}catch{}}}return{deleted,freedBytes,heldSegments,defaultRetentionDays:this.retentionDays,maxStoragePercent:this.maxStoragePercent,completedAt:new Date().toISOString()}}
}
