import fs from "node:fs";
import path from "node:path";
import {spawn} from "node:child_process";
function safe(v){return String(v||"").replace(/[^A-Za-z0-9_-]/g,"_").slice(0,120)}
function run(ffmpeg,args){return new Promise((resolve,reject)=>{const p=spawn(ffmpeg,args,{stdio:["ignore","ignore","pipe"]});let err="";p.stderr.on("data",d=>err=(err+String(d)).slice(-4000));p.on("error",reject);p.on("close",c=>c===0?resolve():reject(new Error(err||`ffmpeg exited ${c}`)))})}
function activeSchedule(config,id,at){if(!id)return true;const s=(config.schedules||[]).find(x=>x.id===id&&x.enabled!==0);if(!s)return false;const d=new Date(at),tz=s.timezone||"Africa/Kampala";if(Number.isNaN(d.getTime()))return false;const p=new Intl.DateTimeFormat("en-GB",{timeZone:tz,weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(d),map={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6},day=map[p.find(x=>x.type==="weekday")?.value||"Mon"],days=Array.isArray(s.days)?s.days:[0,1,2,3,4,5,6],t=`${p.find(x=>x.type==="hour")?.value||"00"}:${p.find(x=>x.type==="minute")?.value||"00"}`;if(!days.includes(day))return false;return s.start_time<=s.end_time?(t>=s.start_time&&t<=s.end_time):(t>=s.start_time||t<=s.end_time)}
function scoreRules(config,cameraId,type,zoneId,confidence,at){return(config.rules||[]).filter(r=>r.enabled!==0&&r.event_type===type&&(!r.camera_id||r.camera_id===cameraId)&&(!r.zone_id||r.zone_id===zoneId)&&(confidence==null||confidence>=Number(r.min_confidence||0))&&activeSchedule(config,r.schedule_id,at))}
function cropFor(zone){const pts=Array.isArray(zone?.polygon)?zone.polygon:[];if(pts.length<3)return null;const xs=pts.map(p=>Number(p?.[0])).filter(Number.isFinite),ys=pts.map(p=>Number(p?.[1])).filter(Number.isFinite);if(xs.length<3||ys.length<3)return null;const x=Math.max(0,Math.min(1,Math.min(...xs))),y=Math.max(0,Math.min(1,Math.min(...ys))),x2=Math.max(x+.02,Math.min(1,Math.max(...xs))),y2=Math.max(y+.02,Math.min(1,Math.max(...ys))),w=x2-x,h=y2-y;return`crop=iw*${w.toFixed(4)}:ih*${h.toFixed(4)}:iw*${x.toFixed(4)}:ih*${y.toFixed(4)}`}
export class EventEngine{
 constructor({catalog,cloud,ffmpeg="ffmpeg",evidenceRoot="./camera-evidence",motionThreshold=.18}){this.catalog=catalog;this.cloud=cloud;this.ffmpeg=ffmpeg;this.evidenceRoot=path.resolve(evidenceRoot);this.motionThreshold=Math.min(.9,Math.max(.02,Number(motionThreshold)||.18));this.seen=new Set();this.protectedIncidents=new Set();fs.mkdirSync(this.evidenceRoot,{recursive:true})}
 closest(cameraId,at){const t=Date.parse(at||new Date().toISOString()),rows=this.catalog.all(cameraId);let best=null,bestD=Infinity;for(const r of rows){const a=Date.parse(r.startedAt),b=Date.parse(r.modifiedAt),d=t<a?a-t:t>b?t-b:0;if(d<bestD){best=r;bestD=d}}return bestD<=10*60*1000?best:null}
 async snapshot(cameraId,row,eventId,provided){const dir=path.join(this.evidenceRoot,safe(cameraId));fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`${safe(eventId)}.jpg`);if(provided){const raw=String(provided).replace(/^data:image\/\w+;base64,/,"");fs.writeFileSync(file,Buffer.from(raw,"base64"));return file}if(!row)return null;await run(this.ffmpeg,["-hide_banner","-loglevel","error","-ss","1","-i",row.path,"-frames:v","1","-q:v","3","-y",file]);return fs.existsSync(file)&&fs.statSync(file).size>512?file:null}
 async ingest(input){const cameraId=String(input?.cameraId||""),type=String(input?.eventType||"motion"),camera=this.cloud.camera(cameraId);if(!camera)throw new Error("Unknown or unassigned camera");if(!["motion","person","object","line_crossing","intrusion","tamper","manual"].includes(type))throw new Error("Unsupported event type");const startedAt=input?.startedAt||new Date().toISOString(),confidence=Number.isFinite(Number(input?.confidence))?Number(input.confidence):null,zoneId=input?.zoneId||null,id=String(input?.id||`evt_${cameraId}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`),row=this.closest(cameraId,startedAt),rules=scoreRules(this.cloud.eventConfig||{},cameraId,type,zoneId,confidence,startedAt),protect=Boolean(input?.protected)||rules.some(r=>r.protect_clip!==0);if(protect&&row)try{this.catalog.protect(cameraId,row.name,true)}catch{}let shot=null;try{shot=await this.snapshot(cameraId,row,id,input?.snapshotBase64)}catch(error){console.error("[camera-events] snapshot",error.message)}const relative=shot?`evidence:${path.relative(this.evidenceRoot,shot)}`:null,event={id,cameraId,eventType:type,severity:input?.severity||rules.sort((a,b)=>({critical:3,warning:2,info:1}[b.severity]-({critical:3,warning:2,info:1}[a.severity])))[0]?.severity||"info",confidence,source:input?.source||"nvr",startedAt,endedAt:input?.endedAt||null,zoneId,recordingId:row?.id||null,snapshotPath:relative,protected:protect,metadata:{...(input?.metadata||{}),localRecordingPath:row?.relativePath||null},message:input?.message||`${type.replace(/_/g," ")} detected`};this.cloud.enqueueEvent(event);return event}
 async applyIncidentProtection(){for(const i of this.cloud.eventConfig?.incidents||[]){if(this.protectedIncidents.has(i.id))continue;const from=Date.parse(i.from_at),to=Date.parse(i.to_at);for(const row of this.catalog.all(i.camera_id)){const a=Date.parse(row.startedAt),b=Date.parse(row.modifiedAt);if(b>=from&&a<=to)try{this.catalog.protect(i.camera_id,row.name,true)}catch{}}this.protectedIncidents.add(i.id)}if(this.protectedIncidents.size>5000)this.protectedIncidents=new Set([...this.protectedIncidents].slice(-2500))}
 async motionScan(){await this.applyIncidentProtection();for(const camera of this.cloud.config.cameras||[]){const row=this.catalog.all(camera.id).at(-1);if(!row)continue;const zones=(this.cloud.eventConfig?.zones||[]).filter(z=>z.camera_id===camera.id&&z.enabled!==0&&z.zone_type==="motion"),targets=[null,...zones];for(const zone of targets){const rules=scoreRules(this.cloud.eventConfig||{},camera.id,"motion",zone?.id||null,null,row.startedAt);if(!rules.length)continue;const key=`${row.id}:${zone?.id||"full"}`;if(this.seen.has(key))continue;this.seen.add(key);const temp=path.join(this.evidenceRoot,`.motion-${safe(camera.id)}-${safe(zone?.id||"full")}-${Date.now()}.jpg`),crop=cropFor(zone),vf=`${crop?crop+",":""}select='gt(scene,${this.motionThreshold})'`;try{await run(this.ffmpeg,["-hide_banner","-loglevel","error","-i",row.path,"-vf",vf,"-frames:v","1","-q:v","4","-y",temp]);if(fs.existsSync(temp)&&fs.statSync(temp).size>512){const raw=fs.readFileSync(temp).toString("base64");await this.ingest({cameraId:camera.id,eventType:"motion",zoneId:zone?.id||null,startedAt:row.startedAt,source:"ffmpeg-scene",snapshotBase64:raw,metadata:{sceneThreshold:this.motionThreshold,zone:zone?.name||"full-frame"}})}}catch{}finally{try{fs.rmSync(temp)}catch{}}}}if(this.seen.size>10000)this.seen=new Set([...this.seen].slice(-5000))}
 resolveEvidence(localPath){const m=/^evidence:(.*)$/.exec(String(localPath||""));if(!m)return null;const full=path.resolve(this.evidenceRoot,m[1]);return full.startsWith(this.evidenceRoot+path.sep)&&fs.existsSync(full)?full:null}
}
