import fs from "node:fs";
import path from "node:path";

function safeId(value){if(!/^[A-Za-z0-9_-]{3,100}$/.test(value))throw new Error("Invalid camera id");return value}
function stamp(value){const d=value?new Date(value):new Date();if(Number.isNaN(d.getTime()))return stamp();return d.toISOString().replace(/T/,"_").replace(/:/g,"-").replace(/\.\d{3}Z$/,".mp4")}
function volumeKeyForRoot(root){const primary=path.resolve(process.env.CAMERA_STORAGE_ROOT||"./camera-storage"),roots=[primary,...String(process.env.CAMERA_STORAGE_VOLUMES||"").split(";").map(x=>x.trim()).filter(Boolean).map(x=>path.resolve(x))],unique=[...new Set(roots)],i=unique.indexOf(path.resolve(root));return`v${Math.max(0,i)}`}
async function bodyBuffer(req,max=64*1024*1024){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw new Error("Camera segment exceeds 64 MB");chunks.push(chunk)}return Buffer.concat(chunks)}
function multipartFile(buffer,contentType){const m=/boundary=(?:"([^"]+)"|([^;]+))/i.exec(contentType||"");if(!m)throw new Error("Multipart boundary missing");const boundary=Buffer.from(`--${m[1]||m[2]}`),headerEnd=Buffer.from("\r\n\r\n"),start=buffer.indexOf(boundary);if(start<0)throw new Error("Multipart payload invalid");const headersAt=buffer.indexOf(headerEnd,start);if(headersAt<0)throw new Error("Multipart headers invalid");const dataStart=headersAt+headerEnd.length,endMarker=Buffer.from(`\r\n--${m[1]||m[2]}`),dataEnd=buffer.indexOf(endMarker,dataStart);if(dataEnd<0)throw new Error("Multipart payload incomplete");return buffer.subarray(dataStart,dataEnd)}
export async function ingestSegment(req,{storageRoot,cloud,cameraId}){safeId(cameraId);const auth=String(req.headers.authorization||""),m=/^Device\s+([^\.\s]+)\.([^\s]+)$/.exec(auth);if(!m||m[1]!==cameraId||!cloud.authorizeCamera(cameraId,m[2])){const error=new Error("Camera is not assigned to this NVR or its credential is invalid");error.status=401;throw error}const raw=await bodyBuffer(req),contentType=String(req.headers["content-type"]||""),video=contentType.startsWith("multipart/form-data")?multipartFile(raw,contentType):raw;if(video.length<1024)throw new Error("Camera segment is empty");const startedAt=String(req.headers["x-ledgerly-segment-start"]||new Date().toISOString()),endedAt=String(req.headers["x-ledgerly-segment-end"]||new Date().toISOString()),dir=path.join(storageRoot,cameraId);fs.mkdirSync(dir,{recursive:true});let name=stamp(startedAt),file=path.join(dir,name),n=1;while(fs.existsSync(file)){name=name.replace(/(?:-\d+)?\.mp4$/,`-${n++}.mp4`);file=path.join(dir,name)}const temp=`${file}.part`;fs.writeFileSync(temp,video);fs.renameSync(temp,file);const volumeKey=volumeKeyForRoot(storageRoot),relative=path.relative(storageRoot,file),row={id:`${volumeKey}:${cameraId}:${name}`,cameraId,startedAt,endedAt,localPath:`${volumeKey}:${relative}`,sizeBytes:video.length,protected:false,status:"complete"};cloud.enqueueRecording(row);return row}
