// @ts-nocheck
import { AppError } from "../../../src/lib/errors";
import { raiseAlert } from "./health";
const makeId=(p:string)=>`${p}_${crypto.randomUUID().replaceAll("-","")}`;
const now=()=>new Date().toISOString();
const safeJson=(v:any,f:any)=>{try{return v?JSON.parse(String(v)):f}catch{return f}};
const TYPES=new Set(["toner","ink","drum","paper","waste","other"]),MOVES=new Set(["opening","restock","usage","adjustment","writeoff"]),EVENTS=new Set(["service","repair","cleaning","inspection","parts"]);
async function printer(db:any,org:string,id:any){if(!id)return null;const p=await db.prepare("SELECT id,name FROM prn_printers WHERE id=? AND organization_id=?").bind(String(id),org).first<any>();if(!p)throw new AppError(422,"INVALID_PRINTER","Selected printer does not belong to this organization");return p}
async function meter(db:any,org:string,printerId:string){const r=await db.prepare("SELECT COALESCE(SUM(actual_impressions),0) value FROM prn_jobs WHERE organization_id=? AND printer_id=? AND status='completed'").bind(org,printerId).first<any>();return Math.max(0,Number(r?.value||0))}
async function orgCurrency(db:any,org:string){const r=await db.prepare("SELECT currency FROM prn_cost_profiles WHERE organization_id=?").bind(org).first<any>().catch(()=>null);return String(r?.currency||"UGX").trim().toUpperCase().slice(0,8)||"UGX"}
function markerMap(v:any){const m=new Map<string,number>();for(const x of safeJson(v,[])){const name=String(x?.name||"").trim().toLowerCase(),level=Number(x?.levelPercent);if(name&&Number.isFinite(level))m.set(name,Math.max(0,Math.min(100,level)))}return m}
async function resolve(db:any,org:string,fingerprint:string){await db.prepare("UPDATE prn_alerts SET resolved_at=COALESCE(resolved_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND fingerprint=? AND resolved_at IS NULL").bind(org,fingerprint).run()}

export async function dashboard(db:any,organizationId:string){
 const [items,moves,printers,events,currency]=await Promise.all([
  db.prepare(`SELECT c.*,p.name printerName,p.marker_levels_json markerLevelsJson FROM prn_consumables c LEFT JOIN prn_printers p ON p.id=c.printer_id AND p.organization_id=c.organization_id WHERE c.organization_id=? AND c.active=1 ORDER BY CASE c.type WHEN 'toner' THEN 0 WHEN 'ink' THEN 1 WHEN 'paper' THEN 2 ELSE 3 END,c.name`).bind(organizationId).all<any>(),
  db.prepare(`SELECT m.*,c.name consumableName,u.display_name actorName FROM prn_consumable_movements m JOIN prn_consumables c ON c.id=m.consumable_id AND c.organization_id=m.organization_id LEFT JOIN users u ON u.id=m.actor_id WHERE m.organization_id=? ORDER BY m.created_at DESC LIMIT 120`).bind(organizationId).all<any>(),
  db.prepare(`SELECT p.id,p.name,p.location,p.health_status healthStatus,p.marker_levels_json markerLevelsJson,mp.service_interval_impressions serviceIntervalImpressions,mp.service_interval_days serviceIntervalDays,mp.warning_impressions warningImpressions,mp.warning_days warningDays,mp.last_service_at lastServiceAt,mp.last_service_impressions lastServiceImpressions,mp.next_due_at nextDueAt,(SELECT COALESCE(SUM(j.actual_impressions),0) FROM prn_jobs j WHERE j.organization_id=p.organization_id AND j.printer_id=p.id AND j.status='completed') lifetimeImpressions FROM prn_printers p LEFT JOIN prn_maintenance_profiles mp ON mp.organization_id=p.organization_id AND mp.printer_id=p.id WHERE p.organization_id=? ORDER BY p.name`).bind(organizationId).all<any>(),
  db.prepare(`SELECT e.*,p.name printerName,u.display_name createdByName FROM prn_maintenance_events e JOIN prn_printers p ON p.id=e.printer_id AND p.organization_id=e.organization_id LEFT JOIN users u ON u.id=e.created_by WHERE e.organization_id=? ORDER BY e.performed_at DESC LIMIT 120`).bind(organizationId).all<any>(),
  orgCurrency(db,organizationId),
 ]);
 const itemRows=(items.results||[]).map((x:any)=>({...x,markerLevels:safeJson(x.markerLevelsJson,[]),lowStock:Number(x.on_hand)<=Number(x.reorder_level),lowMarker:x.last_marker_percent!=null&&Number(x.last_marker_percent)<=Number(x.marker_low_percent)}));
 const printerRows=(printers.results||[]).map((x:any)=>{const life=Number(x.lifetimeImpressions||0),last=Number(x.lastServiceImpressions||0),interval=Number(x.serviceIntervalImpressions||0),warn=Number(x.warningImpressions||0),nextImp=interval?last+interval:null,remaining=nextImp==null?null:nextImp-life,timeDue=x.nextDueAt?new Date(x.nextDueAt).getTime()-Date.now():null;const due=(nextImp!=null&&life>=nextImp)||(timeDue!=null&&timeDue<=0),warning=!due&&((remaining!=null&&remaining<=warn)||(timeDue!=null&&timeDue<=Number(x.warningDays||14)*86400000));return {...x,markerLevels:safeJson(x.markerLevelsJson,[]),nextDueImpressions:nextImp,remainingImpressions:remaining,maintenanceState:due?"due":warning?"warning":"ok"}});
 const lowStock=itemRows.filter((x:any)=>x.lowStock).length,lowMarker=itemRows.filter((x:any)=>x.lowMarker).length,dueMaintenance=printerRows.filter((x:any)=>x.maintenanceState==="due").length,inventoryValue=itemRows.reduce((s:number,x:any)=>s+Number(x.on_hand||0)*Number(x.unit_cost_minor||0),0);
 return {currency,summary:{items:itemRows.length,lowStock,lowMarker,dueMaintenance,inventoryValue},items:itemRows,movements:moves.results||[],printers:printerRows,maintenanceEvents:events.results||[]};
}

export async function saveItem(db:any,organizationId:string,userId:string,id:string|null,data:any){
 const type=TYPES.has(String(data.type))?String(data.type):"other",name=String(data.name||"").trim().slice(0,160);if(!name)throw new AppError(422,"NAME_REQUIRED","Consumable name is required");
 const p=await printer(db,organizationId,data.printerId||null),sku=String(data.sku||"").trim().slice(0,100)||null,markerName=String(data.markerName||"").trim().slice(0,160)||null,color=String(data.color||"").trim().slice(0,50)||null,unit=String(data.unit||"unit").trim().slice(0,30)||"unit",reorder=Math.max(0,Math.round(Number(data.reorderLevel)||0)),target=Math.max(reorder,Math.round(Number(data.targetStock)||0)),cost=Math.max(0,Math.round(Number(data.unitCostMinor)||0)),currency=await orgCurrency(db,organizationId),low=Math.max(1,Math.min(99,Math.round(Number(data.markerLowPercent)||15)));
 if(id){const r=await db.prepare(`UPDATE prn_consumables SET printer_id=?,type=?,name=?,sku=?,marker_name=?,color=?,unit=?,reorder_level=?,target_stock=?,unit_cost_minor=?,currency=?,marker_low_percent=?,active=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(p?.id||null,type,name,sku,markerName,color,unit,reorder,target,cost,currency,low,data.active===false?0:1,userId,id,organizationId).run();if(!r.meta?.changes)throw new AppError(404,"CONSUMABLE_NOT_FOUND","Consumable not found");return {id,updated:true}}
 const itemId=makeId("prnsupply"),opening=Math.max(0,Math.round(Number(data.onHand)||0));const statements=[db.prepare(`INSERT INTO prn_consumables(id,organization_id,printer_id,type,name,sku,marker_name,color,unit,on_hand,reorder_level,target_stock,unit_cost_minor,currency,marker_low_percent,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(itemId,organizationId,p?.id||null,type,name,sku,markerName,color,unit,opening,reorder,target,cost,currency,low,userId,userId)];if(opening>0)statements.push(db.prepare(`INSERT INTO prn_consumable_movements(id,organization_id,consumable_id,movement_type,quantity_delta,balance_after,unit_cost_minor,reference,notes,actor_id) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(makeId("prnmove"),organizationId,itemId,"opening",opening,opening,cost,"opening-balance","Initial stock",userId));await db.batch(statements);return {id:itemId,created:true};
}
export async function deactivateItem(db:any,organizationId:string,userId:string,itemId:string){const r=await db.prepare("UPDATE prn_consumables SET active=0,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND active=1").bind(userId,itemId,organizationId).run();if(!r.meta?.changes)throw new AppError(404,"CONSUMABLE_NOT_FOUND","Consumable not found");await Promise.all([resolve(db,organizationId,`consumable-marker:${itemId}`),resolve(db,organizationId,`consumable-stock:${itemId}`)]);return {id:itemId,active:false}}
export async function addMovement(db:any,organizationId:string,userId:string,itemId:string,data:any){
 const item=await db.prepare("SELECT * FROM prn_consumables WHERE id=? AND organization_id=? AND active=1").bind(itemId,organizationId).first<any>();if(!item)throw new AppError(404,"CONSUMABLE_NOT_FOUND","Consumable not found");
 const movementType=MOVES.has(String(data.movementType))?String(data.movementType):"adjustment",delta=Math.round(Number(data.quantityDelta)||0);if(!delta)throw new AppError(422,"QUANTITY_REQUIRED","Quantity change cannot be zero");
 const cost=Math.max(0,Math.round(Number(data.unitCostMinor??item.unit_cost_minor)||0)),movementId=makeId("prnmove");
 const results=await db.batch([
  db.prepare(`INSERT INTO prn_consumable_movements(id,organization_id,consumable_id,movement_type,quantity_delta,balance_after,unit_cost_minor,reference,notes,actor_id)
    SELECT ?,organization_id,id,?,?,on_hand+?,?,?, ?, ? FROM prn_consumables WHERE id=? AND organization_id=? AND active=1 AND on_hand+?>=0`).bind(movementId,movementType,delta,delta,cost,String(data.reference||"").slice(0,120)||null,String(data.notes||"").slice(0,500)||null,userId,itemId,organizationId,delta),
  db.prepare(`UPDATE prn_consumables SET on_hand=(SELECT balance_after FROM prn_consumable_movements WHERE id=? AND organization_id=?),unit_cost_minor=CASE WHEN ?>0 THEN ? ELSE unit_cost_minor END,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND EXISTS(SELECT 1 FROM prn_consumable_movements WHERE id=? AND organization_id=?)`).bind(movementId,organizationId,cost,cost,userId,itemId,organizationId,movementId,organizationId),
 ]);
 if(!results?.[0]?.meta?.changes)throw new AppError(409,"INSUFFICIENT_STOCK","This movement would make consumable stock negative");const row=await db.prepare("SELECT balance_after balance FROM prn_consumable_movements WHERE id=? AND organization_id=?").bind(movementId,organizationId).first<any>();return {id:itemId,movementId,balance:Number(row?.balance||0)};
}
export async function saveMaintenanceProfile(db:any,organizationId:string,userId:string,printerId:string,data:any){
 await printer(db,organizationId,printerId);const intervalImp=Math.max(0,Math.min(1000000000,Math.round(Number(data.serviceIntervalImpressions)||0))),intervalDays=Math.max(0,Math.min(3650,Math.round(Number(data.serviceIntervalDays)||0))),warningImp=Math.max(0,Math.min(100000000,Math.round(Number(data.warningImpressions)||0))),warningDays=Math.max(0,Math.min(365,Math.round(Number(data.warningDays)||0)));if(!intervalImp&&!intervalDays)throw new AppError(422,"MAINTENANCE_INTERVAL_REQUIRED","Set an impressions or day service interval");
 const existing=await db.prepare("SELECT last_service_at lastServiceAt,last_service_impressions lastServiceImpressions FROM prn_maintenance_profiles WHERE organization_id=? AND printer_id=?").bind(organizationId,printerId).first<any>(),baselineAt=existing?.lastServiceAt||now(),baselineImp=existing?Number(existing.lastServiceImpressions||0):await meter(db,organizationId,printerId),nextDue=intervalDays?new Date(new Date(baselineAt).getTime()+intervalDays*86400000).toISOString():null;
 await db.prepare(`INSERT INTO prn_maintenance_profiles(organization_id,printer_id,service_interval_impressions,service_interval_days,warning_impressions,warning_days,last_service_at,last_service_impressions,next_due_at,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(organization_id,printer_id) DO UPDATE SET service_interval_impressions=excluded.service_interval_impressions,service_interval_days=excluded.service_interval_days,warning_impressions=excluded.warning_impressions,warning_days=excluded.warning_days,next_due_at=excluded.next_due_at,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(organizationId,printerId,intervalImp,intervalDays,warningImp,warningDays,baselineAt,baselineImp,nextDue,userId).run();return {printerId,updated:true};
}
export async function recordMaintenance(db:any,organizationId:string,userId:string,printerId:string,data:any){
 const p=await printer(db,organizationId,printerId),eventType=EVENTS.has(String(data.eventType))?String(data.eventType):"service",performedAt=data.performedAt?new Date(String(data.performedAt)).toISOString():now(),current=await meter(db,organizationId,printerId),cost=Math.max(0,Math.round(Number(data.costMinor)||0)),currency=await orgCurrency(db,organizationId),id=makeId("prnmaint");
 await db.prepare(`INSERT INTO prn_maintenance_events(id,organization_id,printer_id,event_type,notes,technician,cost_minor,currency,impressions_at_event,performed_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(id,organizationId,printerId,eventType,String(data.notes||"").slice(0,1000),String(data.technician||"").slice(0,160)||null,cost,currency,current,performedAt,userId).run();
 if(data.resetServiceClock!==false&&(eventType==="service"||eventType==="cleaning")){const profile=await db.prepare("SELECT service_interval_days serviceIntervalDays FROM prn_maintenance_profiles WHERE organization_id=? AND printer_id=?").bind(organizationId,printerId).first<any>();const days=Number(profile?.serviceIntervalDays||0),next=days?new Date(new Date(performedAt).getTime()+days*86400000).toISOString():null;await db.prepare(`INSERT INTO prn_maintenance_profiles(organization_id,printer_id,last_service_at,last_service_impressions,next_due_at,updated_by) VALUES(?,?,?,?,?,?) ON CONFLICT(organization_id,printer_id) DO UPDATE SET last_service_at=excluded.last_service_at,last_service_impressions=excluded.last_service_impressions,next_due_at=excluded.next_due_at,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(organizationId,printerId,performedAt,current,next,userId).run()}
 await resolve(db,organizationId,`maintenance:${printerId}`);return {id,printerId,printerName:p.name,impressionsAtEvent:current,currency};
}

export async function sweepOrganization(env:any,organizationId:string){
 const db=env.FINANCE_DB,items=(await db.prepare(`SELECT c.*,p.name printerName,p.marker_levels_json markerLevelsJson FROM prn_consumables c LEFT JOIN prn_printers p ON p.id=c.printer_id AND p.organization_id=c.organization_id WHERE c.organization_id=? AND c.active=1`).bind(organizationId).all<any>()).results||[];let updatedMarkers=0,alerts=0;
 for(const item of items){const markers=markerMap(item.markerLevelsJson),markerName=String(item.marker_name||"").trim().toLowerCase(),level=markerName?markers.get(markerName):undefined;if(level!==undefined){await db.prepare("UPDATE prn_consumables SET last_marker_percent=?,last_marker_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(level,item.id,organizationId).run();updatedMarkers++;if(level<=Number(item.marker_low_percent||15)){const severity=level<=5?"critical":"warning";await raiseAlert(env,{organizationId,fingerprint:`consumable-marker:${item.id}`,eventType:"printerly.printer_fault",severity,title:`${item.name} is ${level}%`,body:`${item.printerName||"Printer"}: ${item.name} has reached ${level}%.`,entityType:"consumable",entityId:item.id,details:{printerId:item.printer_id,markerName:item.marker_name,levelPercent:level}});alerts++}else await resolve(db,organizationId,`consumable-marker:${item.id}`)}
  if(Number(item.on_hand)<=Number(item.reorder_level)){await raiseAlert(env,{organizationId,fingerprint:`consumable-stock:${item.id}`,eventType:"printerly.printer_fault",severity:Number(item.on_hand)===0?"critical":"warning",title:`Reorder ${item.name}`,body:`${item.on_hand} ${item.unit}${Number(item.on_hand)===1?"":"s"} remain${item.printerName?` for ${item.printerName}`:""}. Target stock is ${item.target_stock}.`,entityType:"consumable",entityId:item.id,details:{printerId:item.printer_id,onHand:item.on_hand,reorderLevel:item.reorder_level,targetStock:item.target_stock}});alerts++}else await resolve(db,organizationId,`consumable-stock:${item.id}`)
 }
 const profiles=(await db.prepare(`SELECT mp.*,p.name printerName,(SELECT COALESCE(SUM(j.actual_impressions),0) FROM prn_jobs j WHERE j.organization_id=mp.organization_id AND j.printer_id=mp.printer_id AND j.status='completed') lifetimeImpressions FROM prn_maintenance_profiles mp JOIN prn_printers p ON p.id=mp.printer_id AND p.organization_id=mp.organization_id WHERE mp.organization_id=?`).bind(organizationId).all<any>()).results||[];
 for(const x of profiles){const life=Number(x.lifetimeImpressions||0),nextImp=Number(x.service_interval_impressions||0)?Number(x.last_service_impressions||0)+Number(x.service_interval_impressions):null,remaining=nextImp==null?null:nextImp-life,timeMs=x.next_due_at?new Date(x.next_due_at).getTime()-Date.now():null,due=(nextImp!=null&&remaining<=0)||(timeMs!=null&&timeMs<=0),warning=!due&&((remaining!=null&&remaining<=Number(x.warning_impressions||0))||(timeMs!=null&&timeMs<=Number(x.warning_days||0)*86400000));if(due||warning){await raiseAlert(env,{organizationId,fingerprint:`maintenance:${x.printer_id}`,eventType:"printerly.printer_fault",severity:due?"critical":"warning",title:`Printer maintenance ${due?"due":"approaching"} · ${x.printerName}`,body:due?`${x.printerName} has reached its maintenance interval.`:`${x.printerName} is approaching its maintenance interval.`,entityType:"maintenance",entityId:x.printer_id,details:{printerId:x.printer_id,lifetimeImpressions:life,nextDueImpressions:nextImp,nextDueAt:x.next_due_at}});alerts++}else await resolve(db,organizationId,`maintenance:${x.printer_id}`)}
 return {organizationId,items:items.length,updatedMarkers,alerts};
}
export async function runConsumablesSweep(env:any){const orgs=await env.FINANCE_DB.prepare("SELECT organization_id FROM organization_modules WHERE module_key='printerly' AND enabled=1").all<any>();const out=[];for(const x of orgs.results||[])out.push(await sweepOrganization(env,x.organization_id));return out}
