// @ts-nocheck
import{Hono}from"hono";import type{MiddlewareHandler}from"hono";import type{AppVariables,Env}from"../../../src/types";import{requireModuleEnabled}from"../../../src/lib/modules";import{AppError}from"../../../src/lib/errors";import*as S from"./service-desk";
export const printerlyServiceDeskRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();const json=async(c:any)=>c.req.json().catch(()=>({}));
const access=(write=false):MiddlewareHandler<{Bindings:Env;Variables:AppVariables}>=>async(c,next)=>{const p=c.get("principal");if(["owner","admin","manager","accountant"].includes(p.role)||(!write&&p.role==="viewer"))return next();const scopes=write?["school:write","documents:write","reports:write"]:["school:read","documents:read","reports:read"];if(p.scopes.some((s:string)=>scopes.includes(s)))return next();throw new AppError(403,"FORBIDDEN","You do not have permission to use Printerly service desk")};
const admin:MiddlewareHandler<{Bindings:Env;Variables:AppVariables}>=async(c,next)=>{const p=c.get("principal");if(["owner","admin"].includes(p.role)||p.scopes.includes("admin:write"))return next();throw new AppError(403,"SERVICE_DESK_ADMIN_REQUIRED","Only organization owners and administrators can configure Printerly SLA policy")};const read=[requireModuleEnabled("printerly"),access(false)],write=[requireModuleEnabled("printerly"),access(true)];
printerlyServiceDeskRoutes.get("/service-desk",...read,async c=>c.json({data:await S.dashboard(c.env.FINANCE_DB,c.get("principal").organizationId)}));
printerlyServiceDeskRoutes.get("/service-desk/tickets/:id",...read,async c=>c.json({data:await S.detail(c.env.FINANCE_DB,c.get("principal").organizationId,c.req.param("id"))}));
printerlyServiceDeskRoutes.put("/service-desk/settings",...write,admin,async c=>{const p=c.get("principal");return c.json({data:await S.updateSettings(c.env.FINANCE_DB,p.organizationId,p.userId,await json(c))})});
printerlyServiceDeskRoutes.post("/service-desk/tickets",...write,async c=>{const p=c.get("principal");return c.json({data:await S.createTicket(c.env.FINANCE_DB,p.organizationId,p.userId,await json(c))},201)});
printerlyServiceDeskRoutes.post("/service-desk/tickets/:id/assign",...write,async c=>{const p=c.get("principal"),b=await json(c);return c.json({data:await S.assign(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"),String(b.assigneeId||""))})});
printerlyServiceDeskRoutes.post("/service-desk/tickets/:id/acknowledge",...write,async c=>{const p=c.get("principal");return c.json({data:await S.acknowledge(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"))})});
printerlyServiceDeskRoutes.post("/service-desk/tickets/:id/status",...write,async c=>{const p=c.get("principal"),b=await json(c);return c.json({data:await S.setStatus(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"),String(b.status||""),b.notes)})});
printerlyServiceDeskRoutes.post("/service-desk/tickets/:id/comments",...write,async c=>{const p=c.get("principal"),b=await json(c);return c.json({data:await S.comment(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"),String(b.notes||""))},201)});
printerlyServiceDeskRoutes.post("/service-desk/tickets/:id/resolve",...write,async c=>{const p=c.get("principal");return c.json({data:await S.resolve(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"),await json(c))})});
printerlyServiceDeskRoutes.post("/service-desk/sweep",...write,admin,async c=>c.json({data:await S.sweepOrganization(c.env,c.get("principal").organizationId)}));
