import {localMobileRecords,queueMobileMutation} from "../syncEngine";
import type {BookReference,BookStudent,BooksOverview,BookType,ClassReport,Distribution,DistributionBatch,LearnerReport,Paged,PeriodReport,StockMovement,StockRow,UnissuedReport} from "./types";
type R=Record<string,any>;const M="books",S="school-management";const uid=(p:string)=>`${p}_${Date.now().toString(36)}${Math.random().toString(36).slice(2)}${Math.random().toString(36).slice(2)}`;export const booksNetworkError=(e:any)=>e?.code==="NETWORK_ERROR"||e?.status===0;export async function booksOfflineFallback<T>(online:()=>Promise<T>,offline:()=>Promise<T>){try{return await online()}catch(e){if(booksNetworkError(e))return offline();throw e}}
const rows=async<T=R>(m:string,c:string)=>((await localMobileRecords<T>(m,c,1000,0)).map(x=>({...(x.payload as any),id:x.id})) as T[]);
async function studentsRaw(){return rows<R>(S,"students")}async function context(){return rows<R>(S,"academic-context")}
export async function offlineStudents(filters:{classId?:string;streamId?:string;q?:string;limit?:number}={}):Promise<BookStudent[]>{let x=(await studentsRaw()).map(s=>({id:s.id,admissionNumber:s.admissionNumber,studentNumber:s.studentNumber,name:[s.firstName,s.middleName,s.lastName].filter(Boolean).join(" "),academicYearId:s.currentAcademicYearId,classId:s.currentClassId,streamId:s.currentStreamId,className:s.className,streamName:s.streamName}));if(filters.classId)x=x.filter(s=>s.classId===filters.classId);if(filters.streamId)x=x.filter(s=>s.streamId===filters.streamId);if(filters.q){const q=filters.q.toLowerCase();x=x.filter(s=>`${s.name} ${s.admissionNumber||""} ${s.studentNumber||""}`.toLowerCase().includes(q))}return x.slice(0,filters.limit||200)}
export async function offlineReference():Promise<BookReference>{const c=await context(),by=(t:string)=>c.filter(x=>x.entityType===t).map(({entityType,...x})=>x),years=by("academic-year"),terms=by("term"),classes=by("class"),streams=by("stream"),year=years.find((x:any)=>x.isCurrent)||years[0]||null,term=terms.find((x:any)=>x.isCurrent)||terms.find((x:any)=>!year||x.academicYearId===year.id)||null;return{bookTypes:["small","a4"],years,terms,classes,streams,current:{year,term}}}
export const offlineMovements=async()=>rows<StockMovement>(M,"stock-movements");export const offlineDistributions=async()=>rows<Distribution>(M,"distributions");export const offlineBatches=async()=>rows<DistributionBatch>(M,"distribution-batches");
export async function offlineStock():Promise<StockRow[]>{const[m,d]=await Promise.all([offlineMovements(),offlineDistributions()]);return(["small","a4"]as BookType[]).map(bookType=>{const stockIn=m.filter(x=>x.bookType===bookType&&!x.reversedAt).reduce((n,x)=>n+Number(x.quantityDelta||0),0),issued=d.filter(x=>x.bookType===bookType&&!x.reversedAt).reduce((n,x)=>n+Number(x.quantity||0),0);return{bookType,stockIn,issued,available:stockIn-issued}})}
function filterDist(rows:Distribution[],f:any){return rows.filter(x=>(!f.bookType||x.bookType===f.bookType)&&(!f.studentId||x.studentId===f.studentId)&&(!f.classId||x.classId===f.classId)&&(!f.streamId||x.streamId===f.streamId)&&(!f.academicYearId||x.academicYearId===f.academicYearId)&&(!f.termId||x.termId===f.termId)&&(!f.from||x.distributedOn>=f.from)&&(!f.to||x.distributedOn<=f.to))}
function filterMov(rows:StockMovement[],f:any){return rows.filter(x=>(!f.bookType||x.bookType===f.bookType)&&(!f.from||x.movementOn>=f.from)&&(!f.to||x.movementOn<=f.to))}
export async function offlinePagedDistributions(f:any={}):Promise<Paged<Distribution>>{const all=filterDist(await offlineDistributions(),f),offset=Number(f.offset||0),limit=Number(f.limit||200);return{rows:all.slice(offset,offset+limit),total:all.length,offset,limit}}
export async function offlinePagedMovements(f:any={}):Promise<Paged<StockMovement>>{const all=filterMov(await offlineMovements(),f),offset=Number(f.offset||0),limit=Number(f.limit||200);return{rows:all.slice(offset,offset+limit),total:all.length,offset,limit}}
export async function offlineOverview():Promise<BooksOverview>{const[stock,d,ref]=await Promise.all([offlineStock(),offlineDistributions(),offlineReference()]),active=d.filter(x=>!x.reversedAt),current=ref.current.term?.id?active.filter(x=>x.termId===ref.current.term?.id):active;return{stock,totalIssued:active.reduce((n,x)=>n+Number(x.quantity||0),0),transactions:active.length,learnersServed:new Set(active.map(x=>x.studentId)).size,currentTermIssued:current.reduce((n,x)=>n+Number(x.quantity||0),0),currentTermLearners:new Set(current.map(x=>x.studentId)).size,current:ref.current,recent:active.slice(0,20)}}
export async function offlineLearnerReport(studentId:string,f:any={}):Promise<LearnerReport>{const s=(await offlineStudents({limit:1000})).find(x=>x.id===studentId),tx=filterDist(await offlineDistributions(),{...f,studentId}).filter(x=>!x.reversedAt);if(!s)throw new Error("Learner is not available offline");const small=tx.filter(x=>x.bookType==="small").reduce((n,x)=>n+Number(x.quantity||0),0),a4=tx.filter(x=>x.bookType==="a4").reduce((n,x)=>n+Number(x.quantity||0),0);return{student:{id:s.id,admissionNumber:s.admissionNumber,studentNumber:s.studentNumber,name:s.name,currentClassName:s.className,currentStreamName:s.streamName},totals:{small,a4,total:small+a4},transactions:tx}}
export async function offlineClassReport(classId:string,f:any={}):Promise<ClassReport>{const ss=await offlineStudents({classId,streamId:f.streamId,limit:1000}),d=filterDist(await offlineDistributions(),{...f,classId}).filter(x=>!x.reversedAt),rows=ss.map(s=>{const tx=d.filter(x=>x.studentId===s.id),small=tx.filter(x=>x.bookType==="small").reduce((n,x)=>n+Number(x.quantity||0),0),a4=tx.filter(x=>x.bookType==="a4").reduce((n,x)=>n+Number(x.quantity||0),0);return{studentId:s.id,admissionNumber:s.admissionNumber,studentNumber:s.studentNumber,studentName:s.name,className:s.className||"",streamName:s.streamName,small,a4,total:small+a4,lastIssuedOn:tx.map(x=>x.distributedOn).sort().pop()||null}});return{rows,totals:{learners:rows.length,learnersServed:rows.filter(x=>x.total>0).length,small:rows.reduce((n,x)=>n+x.small,0),a4:rows.reduce((n,x)=>n+x.a4,0),total:rows.reduce((n,x)=>n+x.total,0)}}}
export async function offlineUnissued(classId:string,f:any={}):Promise<UnissuedReport>{const r=await offlineClassReport(classId,f),rows=r.rows.filter(x=>x.total===0);return{rows,total:rows.length,classLearners:r.totals.learners,served:r.totals.learnersServed}}
export async function offlinePeriod(f:any={}):Promise<PeriodReport>{const d=filterDist(await offlineDistributions(),f).filter(x=>!x.reversedAt),types=(['small','a4']as BookType[]).map(bookType=>{const x=d.filter(r=>r.bookType===bookType);return{bookType,quantity:x.reduce((n,r)=>n+Number(r.quantity||0),0),transactions:x.length,learners:new Set(x.map(r=>r.studentId)).size}}),groups=new Map<string,any>();for(const x of d){const k=`${x.classId||""}:${x.streamId||""}`,g=groups.get(k)||{classId:x.classId||"",className:x.className,streamId:x.streamId,streamName:x.streamName,quantity:0,learners:new Set<string>()};g.quantity+=Number(x.quantity||0);g.learners.add(x.studentId);groups.set(k,g)}const byClass=[...groups.values()].map(g=>({...g,learners:g.learners.size})),days=new Map<string,Distribution[]>();for(const x of d){const a=days.get(x.distributedOn)||[];a.push(x);days.set(x.distributedOn,a)}const byDay=[...days.entries()].map(([date,x])=>({date,quantity:x.reduce((n,r)=>n+Number(r.quantity||0),0),transactions:x.length,learners:new Set(x.map(r=>r.studentId)).size}));return{byType:types,byClass,byDay}}
export async function queueBookIntent(payload:R){const id=uid("bki");await queueMobileMutation({moduleKey:M,collectionKey:"operation-intents",recordId:id,payload,baseVersion:0});return{id,status:"queued",offlineQueued:true,...payload}}
