import {useEffect,useMemo,useState} from "react";
import {Alert,Modal,RefreshControl,ScrollView,StyleSheet,Switch,Text,TouchableOpacity,View} from "react-native";
import {FilePicker} from "../../native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {schoolApi} from "./api";
import type {SchoolFile,SchoolProfile,SchoolRole,SchoolUser,SetupBundle,SetupKey} from "./types";
import {Card,Empty,ErrorNotice,Field,Pill,PrimaryButton,SecondaryButton,SectionTitle,SelectField} from "./ui";

type Props={session:MobileSession;onSession:SessionUpdater};
type Area="setup"|"identity"|"files";
const setupKeys:SetupKey[]=["branches","academicYears","terms","departments","classLevels","classes","streams","subjects","classSubjects","gradingScales","gradeBoundaries","divisions","assessmentTypes","promotionRules","calendar","lessonPeriods","feeCategories","paymentMethods","templates"];
const labels:Record<SetupKey,string>={branches:"Campuses",academicYears:"Academic years",terms:"Terms",departments:"Departments",classLevels:"Class levels",classes:"Classes",streams:"Streams",subjects:"Subjects",classSubjects:"Class subjects",gradingScales:"Grading scales",gradeBoundaries:"Grade boundaries",divisions:"Divisions",assessmentTypes:"Assessment types",promotionRules:"Promotion rules",calendar:"Calendar",lessonPeriods:"Lesson periods",feeCategories:"Fee categories",paymentMethods:"Payment methods",templates:"Templates"};
const yesNo=[{label:"Yes",value:"true"},{label:"No",value:"false"}];
const statusOptions=["planned","active","closed","archived"].map(x=>({label:x.replace("_"," "),value:x}));
const bool=(v:string|undefined,def=false)=>v===undefined?def:v==="true";
const num=(v:string|undefined,def=0)=>v===undefined||v===""?def:Number(v);

function setupPayload(key:SetupKey,f:Record<string,string>){
 const base={active:bool(f.active,true)};
 switch(key){
  case"branches":return{code:f.code,name:f.name,registrationNumber:f.registrationNumber||null,phone:f.phone||null,email:f.email||null,physicalAddress:f.physicalAddress||null,districtRegion:f.districtRegion||null,principalName:f.principalName||null,isMain:bool(f.isMain),...base};
  case"academicYears":return{code:f.code,name:f.name,startsOn:f.startsOn,endsOn:f.endsOn,status:f.status||"planned",isCurrent:bool(f.isCurrent)};
  case"terms":return{academicYearId:f.academicYearId,code:f.code,name:f.name,sequenceNo:num(f.sequenceNo,1),startsOn:f.startsOn,endsOn:f.endsOn,status:f.status||"planned",isCurrent:bool(f.isCurrent)};
  case"departments":return{campusId:f.campusId||null,code:f.code,name:f.name,description:f.description||null,parentId:f.parentId||null,...base};
  case"classLevels":return{code:f.code,name:f.name,sequenceNo:num(f.sequenceNo,1),educationLevel:f.educationLevel||null,promotionLevelId:f.promotionLevelId||null,terminal:bool(f.terminal),...base};
  case"classes":return{academicYearId:f.academicYearId||null,campusId:f.campusId||null,classLevelId:f.classLevelId,departmentId:f.departmentId||null,code:f.code,name:f.name,capacity:f.capacity?num(f.capacity):null,...base};
  case"streams":return{classId:f.classId,campusId:f.campusId||null,code:f.code,name:f.name,capacity:f.capacity?num(f.capacity):null,...base};
  case"subjects":return{departmentId:f.departmentId||null,code:f.code,name:f.name,shortName:f.shortName||null,subjectType:f.subjectType||"compulsory",curriculumCode:f.curriculumCode||null,passMark:f.passMark?num(f.passMark):null,maxMark:num(f.maxMark,100),metadata:{},...base};
  case"classSubjects":return{classLevelId:f.classLevelId,subjectId:f.subjectId,academicYearId:f.academicYearId||null,compulsory:bool(f.compulsory,true),periodsPerWeek:f.periodsPerWeek?num(f.periodsPerWeek):null,active:bool(f.active,true)};
  case"gradingScales":return{code:f.code,name:f.name,curriculum:f.curriculum||null,isDefault:bool(f.isDefault),...base};
  case"gradeBoundaries":return{gradingScaleId:f.gradingScaleId,grade:f.grade,minScore:num(f.minScore),maxScore:num(f.maxScore),points:f.points?num(f.points):null,aggregatePoints:f.aggregatePoints?num(f.aggregatePoints):null,remark:f.remark||null,sequenceNo:num(f.sequenceNo)};
  case"divisions":return{gradingScaleId:f.gradingScaleId||null,code:f.code,name:f.name,minAggregate:f.minAggregate?num(f.minAggregate):null,maxAggregate:f.maxAggregate?num(f.maxAggregate):null,minSubjects:f.minSubjects?num(f.minSubjects):null,sequenceNo:num(f.sequenceNo),rule:{},...base};
  case"assessmentTypes":return{code:f.code,name:f.name,weightPercent:num(f.weightPercent,100),maxScore:num(f.maxScore,100),sequenceNo:num(f.sequenceNo),...base};
  case"promotionRules":return{classLevelId:f.classLevelId||null,name:f.name,minimumAverage:f.minimumAverage?num(f.minimumAverage):null,maximumFailedSubjects:f.maximumFailedSubjects?num(f.maximumFailedSubjects):null,minimumAttendancePercent:f.minimumAttendancePercent?num(f.minimumAttendancePercent):null,targetClassLevelId:f.targetClassLevelId||null,allowManualOverride:bool(f.allowManualOverride,true),rule:{},...base};
  case"calendar":return{campusId:f.campusId||null,academicYearId:f.academicYearId||null,termId:f.termId||null,eventType:f.eventType||"school_event",title:f.title,description:f.description||null,startsAt:f.startsAt,endsAt:f.endsAt,allDay:bool(f.allDay,true),teachingDay:bool(f.teachingDay)};
  case"lessonPeriods":return{campusId:f.campusId||null,code:f.code,name:f.name,sequenceNo:num(f.sequenceNo,1),startsAt:f.startsAt,endsAt:f.endsAt,periodType:f.periodType||"lesson",teachingPeriod:bool(f.teachingPeriod,true),...base};
  case"feeCategories":return{code:f.code,name:f.name,description:f.description||null,taxable:bool(f.taxable),refundable:bool(f.refundable),mandatory:bool(f.mandatory),metadata:{},...base};
  case"paymentMethods":return{code:f.code,name:f.name,methodType:f.methodType||"cash",configuration:{},...base};
  case"templates":return{campusId:f.campusId||null,templateType:f.templateType||"other",name:f.name,fileId:f.fileId||null,version:num(f.version,1),content:{},isDefault:bool(f.isDefault),...base};
 }
}
function recordTitle(row:any){return row.name||row.title||row.grade||row.code||row.id}
function errText(e:any){return e?.message||"Request failed"}

export function AdminTab({session,onSession}:Props){
 const c={session,onSession};
 const[area,setArea]=useState<Area>("setup"),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
 const[profile,setProfile]=useState<SchoolProfile|null>(null),[bundle,setBundle]=useState<SetupBundle|null>(null),[key,setKey]=useState<SetupKey>("academicYears"),[rows,setRows]=useState<any[]>([]),[roles,setRoles]=useState<SchoolRole[]>([]),[users,setUsers]=useState<SchoolUser[]>([]),[files,setFiles]=useState<SchoolFile[]>([]),[security,setSecurity]=useState<any>(null);
 const[modal,setModal]=useState<"profile"|"setup"|"user"|"role"|"security"|null>(null),[form,setForm]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false);
 const options=(items:any[]=[])=>items.map(x=>({label:x.name||x.code||x.id,value:x.id,detail:x.code||undefined}));
 async function load(silent=false){if(!silent)setLoading(true);setError("");try{const[p,b,r,u,f,sec]=await Promise.all([schoolApi.profile(c),schoolApi.setupBundle(c),schoolApi.roles(c),schoolApi.users(c),schoolApi.files(c),schoolApi.securityPolicy(c)]);setProfile(p);setBundle(b);setRoles(r);setUsers(u);setFiles(f);setSecurity(sec);setRows(await schoolApi.setupList(c,key));}catch(e:any){setError(errText(e))}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!loading)schoolApi.setupList(c,key).then(setRows).catch(e=>setError(errText(e)))},[key]);
 const currentYear=bundle?.academicYears.find((x:any)=>Boolean(x.isCurrent));
 function openProfile(){const p=profile||{};setForm({schoolCode:String(p.schoolCode||""),registrationNumber:String(p.registrationNumber||""),motto:String(p.motto||""),schoolType:String(p.schoolType||"day"),ownershipType:String(p.ownershipType||""),educationLevel:String(p.educationLevel||""),curriculum:String(p.curriculum||""),phone:String(p.phoneNumbers?.[0]||""),email:String(p.emailAddresses?.[0]||""),website:String(p.website||""),physicalAddress:String(p.physicalAddress||""),country:String(p.country||"Uganda"),districtRegion:String(p.districtRegion||""),headTeacherName:String(p.headTeacherName||""),headTeacherPhone:String(p.headTeacherPhone||""),headTeacherEmail:String(p.headTeacherEmail||""),timezone:String(p.timezone||"Africa/Kampala"),defaultCurrency:String(p.defaultCurrency||"UGX")});setModal("profile")}
 function openSetup(){setForm({active:"true",status:"planned",isCurrent:"false",isMain:"false",sequenceNo:"1",maxMark:"100",weightPercent:"100",compulsory:"true",allowManualOverride:"true",allDay:"true",teachingPeriod:"true",version:"1",academicYearId:currentYear?.id||""});setModal("setup")}
 async function save(){setSaving(true);try{
  if(modal==="profile"){await schoolApi.saveProfile(c,{schoolCode:form.schoolCode,registrationNumber:form.registrationNumber||null,motto:form.motto||null,schoolType:form.schoolType||"day",ownershipType:form.ownershipType||null,educationLevel:form.educationLevel||null,curriculum:form.curriculum||null,phoneNumbers:form.phone?[form.phone]:[],emailAddresses:form.email?[form.email]:[],website:form.website||null,physicalAddress:form.physicalAddress||null,postalAddress:null,country:form.country||"Uganda",districtRegion:form.districtRegion||null,locationText:null,headTeacherName:form.headTeacherName||null,headTeacherPhone:form.headTeacherPhone||null,headTeacherEmail:form.headTeacherEmail||null,language:"en",timezone:form.timezone||"Africa/Kampala",dateFormat:"DD/MM/YYYY",timeFormat:"24h",defaultCurrency:(form.defaultCurrency||"UGX").toUpperCase(),multiCampusEnabled:false,branding:{},systemPreferences:{}})}
  else if(modal==="setup")await schoolApi.setupCreate(c,key,setupPayload(key,form));
  else if(modal==="user")await schoolApi.createUser(c,{email:form.email,displayName:form.displayName,password:form.password||undefined,username:form.username||null,phone:form.phone||null,status:form.status||"active",forcePasswordChange:bool(form.forcePasswordChange,true),coreRole:form.coreRole||"viewer",scopes:["school:read"],roleIds:form.roleId?[form.roleId]:[],notificationPreferences:{}});
  else if(modal==="role")await schoolApi.createRole(c,{code:form.code,name:form.name,description:form.description||null,roleCategory:form.roleCategory||"custom",active:true,permissions:(form.permissions||"").split(/[,\n]/).map(x=>x.trim()).filter(Boolean)});
  else if(modal==="security")await schoolApi.saveSecurityPolicy(c,{minimumPasswordLength:num(form.minimumPasswordLength,12),requireUppercase:bool(form.requireUppercase,true),requireLowercase:bool(form.requireLowercase,true),requireNumber:bool(form.requireNumber,true),requireSymbol:bool(form.requireSymbol),passwordExpiryDays:form.passwordExpiryDays?num(form.passwordExpiryDays):null,passwordHistoryCount:num(form.passwordHistoryCount,5),maxFailedLogins:num(form.maxFailedLogins,5),lockoutMinutes:num(form.lockoutMinutes,15),sessionTimeoutMinutes:num(form.sessionTimeoutMinutes,480),require2faForAdmins:bool(form.require2faForAdmins,true),allowImpersonation:bool(form.allowImpersonation)});
  setModal(null);await load(true);Alert.alert("Saved","School Management has been updated.")
 }catch(e:any){Alert.alert("Couldn’t save",errText(e))}finally{setSaving(false)}}
 function openSecurity(){const x=security||{};setForm({minimumPasswordLength:String(x.minimumPasswordLength??12),requireUppercase:String(Boolean(x.requireUppercase??true)),requireLowercase:String(Boolean(x.requireLowercase??true)),requireNumber:String(Boolean(x.requireNumber??true)),requireSymbol:String(Boolean(x.requireSymbol??false)),passwordExpiryDays:String(x.passwordExpiryDays??""),passwordHistoryCount:String(x.passwordHistoryCount??5),maxFailedLogins:String(x.maxFailedLogins??5),lockoutMinutes:String(x.lockoutMinutes??15),sessionTimeoutMinutes:String(x.sessionTimeoutMinutes??480),require2faForAdmins:String(Boolean(x.require2faForAdmins??true)),allowImpersonation:String(Boolean(x.allowImpersonation??false))});setModal("security")}
 async function upload(){try{const picked=await FilePicker.pick();if(!picked)return;if(picked.size>15*1024*1024){Alert.alert("File too large","School uploads are limited to 15 MB.");return}const created=await schoolApi.uploadFile(c,picked,"mobile_upload");setFiles(x=>[created,...x]);Alert.alert("Uploaded",picked.name)}catch(e:any){Alert.alert("Upload failed",errText(e))}}
 function removeFile(file:SchoolFile){Alert.alert("Delete file?",file.originalName,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>void schoolApi.deleteFile(c,file.id).then(()=>setFiles(x=>x.filter(y=>y.id!==file.id))).catch(e=>Alert.alert("Can’t delete",errText(e)))}])}
 function removeSetup(row:any){Alert.alert("Delete configuration?",String(recordTitle(row)),[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>void schoolApi.setupDelete(c,key,row.id).then(()=>setRows(x=>x.filter(y=>y.id!==row.id))).catch(e=>Alert.alert("Can’t delete",errText(e)))}])}
 const setupFields=useMemo(()=>{
  const f:(string|[string,string])[]=[];const add=(...x:(string|[string,string])[])=>f.push(...x);
  if(["branches","academicYears","terms","departments","classLevels","classes","streams","subjects","gradingScales","divisions","assessmentTypes","lessonPeriods","feeCategories","paymentMethods"].includes(key))add("code","name");
  if(key==="calendar")add("title");if(key==="templates")add("name");if(key==="gradeBoundaries")add("grade");if(key==="promotionRules")add("name");
  return f;
 },[key]);
 function textField(name:string,label=name.replace(/([A-Z])/g," $1")){return <Field key={name} label={label} value={form[name]||""} onChangeText={v=>setForm(x=>({...x,[name]:v}))}/>}
 function select(name:string,label:string,opts:{label:string;value:string}[]){return <SelectField key={name} label={label} value={form[name]} onChange={v=>setForm(x=>({...x,[name]:v}))} options={opts}/>}
 function dynamicSetupFields(){const out:any[]=[];setupFields.forEach(x=>out.push(textField(x as string)));switch(key){
  case"branches":out.push(textField("registrationNumber"),textField("phone"),textField("email"),textField("physicalAddress"),textField("districtRegion"),textField("principalName"),select("isMain","Main campus",yesNo));break;
  case"academicYears":out.push(textField("startsOn","Starts on (YYYY-MM-DD)"),textField("endsOn","Ends on"),select("status","Status",statusOptions),select("isCurrent","Current year",yesNo));break;
  case"terms":out.push(select("academicYearId","Academic year",options(bundle?.academicYears)),textField("sequenceNo"),textField("startsOn"),textField("endsOn"),select("status","Status",statusOptions),select("isCurrent","Current term",yesNo));break;
  case"departments":out.push(select("campusId","Campus",options(bundle?.branches)),textField("description"));break;
  case"classLevels":out.push(textField("sequenceNo"),textField("educationLevel"),select("promotionLevelId","Next class level",options(bundle?.classLevels)),select("terminal","Terminal class",yesNo));break;
  case"classes":out.push(select("academicYearId","Academic year",options(bundle?.academicYears)),select("campusId","Campus",options(bundle?.branches)),select("classLevelId","Class level",options(bundle?.classLevels)),select("departmentId","Department",options(bundle?.departments)),textField("capacity"));break;
  case"streams":out.push(select("classId","Class",options(bundle?.classes)),select("campusId","Campus",options(bundle?.branches)),textField("capacity"));break;
  case"subjects":out.push(select("departmentId","Department",options(bundle?.departments)),textField("shortName"),select("subjectType","Subject type",["compulsory","optional","elective"].map(x=>({label:x,value:x}))),textField("curriculumCode"),textField("passMark"),textField("maxMark"));break;
  case"classSubjects":out.push(select("classLevelId","Class level",options(bundle?.classLevels)),select("subjectId","Subject",options(bundle?.subjects)),select("academicYearId","Academic year",options(bundle?.academicYears)),textField("periodsPerWeek"),select("compulsory","Compulsory",yesNo));break;
  case"gradingScales":out.push(textField("curriculum"),select("isDefault","Default scale",yesNo));break;
  case"gradeBoundaries":out.push(textField("gradingScaleId","Grading scale ID"),textField("minScore"),textField("maxScore"),textField("points"),textField("aggregatePoints"),textField("remark"),textField("sequenceNo"));break;
  case"divisions":out.push(textField("gradingScaleId","Grading scale ID"),textField("minAggregate"),textField("maxAggregate"),textField("minSubjects"),textField("sequenceNo"));break;
  case"assessmentTypes":out.push(textField("weightPercent"),textField("maxScore"),textField("sequenceNo"));break;
  case"promotionRules":out.push(select("classLevelId","Class level",options(bundle?.classLevels)),textField("minimumAverage"),textField("maximumFailedSubjects"),textField("minimumAttendancePercent"),select("targetClassLevelId","Target level",options(bundle?.classLevels)),select("allowManualOverride","Allow manual override",yesNo));break;
  case"calendar":out.push(select("campusId","Campus",options(bundle?.branches)),select("academicYearId","Academic year",options(bundle?.academicYears)),select("termId","Term",options(bundle?.terms)),select("eventType","Event type",["holiday","weekend","school_event","teaching_day_override","closure","other"].map(x=>({label:x.replaceAll("_"," "),value:x}))),textField("startsAt"),textField("endsAt"),textField("description"),select("allDay","All day",yesNo),select("teachingDay","Teaching day",yesNo));break;
  case"lessonPeriods":out.push(select("campusId","Campus",options(bundle?.branches)),textField("sequenceNo"),textField("startsAt","Starts at (HH:MM)"),textField("endsAt","Ends at (HH:MM)"),select("periodType","Period type",["lesson","break","lunch","assembly","other"].map(x=>({label:x,value:x}))),select("teachingPeriod","Teaching period",yesNo));break;
  case"feeCategories":out.push(textField("description"),select("taxable","Taxable",yesNo),select("refundable","Refundable",yesNo),select("mandatory","Mandatory",yesNo));break;
  case"paymentMethods":out.push(select("methodType","Method",["cash","bank","mobile_money","card","cheque","online","other"].map(x=>({label:x.replace("_"," "),value:x}))));break;
  case"templates":out.push(select("campusId","Campus",options(bundle?.branches)),select("templateType","Template type",["letterhead","receipt","invoice","report_card","id_card","admission","transfer","other"].map(x=>({label:x.replaceAll("_"," "),value:x}))),textField("fileId","Uploaded file ID"),textField("version"),select("isDefault","Default template",yesNo));break;
 }
 if(!["academicYears","terms","gradeBoundaries","calendar"].includes(key))out.push(select("active","Active",yesNo));return out}
 if(loading)return <View style={s.center}><Text style={s.muted}>Loading School Administration…</Text></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load(true)}}/>} contentContainerStyle={s.scroll}>
  <View style={s.areaRow}>{(["setup","identity","files"] as Area[]).map(x=><TouchableOpacity key={x} onPress={()=>setArea(x)} style={[s.area,area===x&&s.areaActive]}><Text style={[s.areaText,area===x&&s.areaTextActive]}>{x==="identity"?"Users & security":x==="files"?"Files":"School setup"}</Text></TouchableOpacity>)}</View>
  {error?<ErrorNotice message={error} onRetry={()=>void load()}/>:null}
  {area==="setup"?<>
   <SectionTitle title="School identity" subtitle="Core profile and localization" action="Edit" onAction={openProfile}/><Card><Text style={s.school}>{profile?.schoolName||"School profile"}</Text><Text style={s.code}>{profile?.schoolCode||"No school code"} · {profile?.defaultCurrency||"UGX"} · {profile?.timezone||"Africa/Kampala"}</Text><Text style={s.copy}>{profile?.physicalAddress||profile?.districtRegion||"Add the school address and district."}</Text></Card>
   <SectionTitle title="Configuration" subtitle="Academic structure, grading, fees and operational setup" action="Add" onAction={openSetup}/><SelectField label="Configuration area" value={key} onChange={v=>setKey(v as SetupKey)} options={setupKeys.map(x=>({label:labels[x],value:x}))}/>
   {rows.length?rows.map(row=><Card key={row.id} style={s.rowCard}><View style={s.rowTop}><View style={{flex:1}}><Text style={s.rowTitle}>{recordTitle(row)}</Text><Text style={s.rowSub}>{row.code||row.id}</Text></View>{"active" in row?<Pill text={row.active?"Active":"Inactive"} tone={row.active?"good":"warn"}/>:null}</View><View style={s.actions}><SecondaryButton compact title="View" onPress={()=>Alert.alert(labels[key],JSON.stringify(row,null,2))}/><PrimaryButton compact danger title="Delete" onPress={()=>removeSetup(row)}/></View></Card>):<Empty title={`No ${labels[key].toLowerCase()}`} copy="Create the first configuration record from mobile."/>}
   <SectionTitle title="Smart defaults" subtitle="Restore safe school defaults without replacing valid records"/><PrimaryButton title="Restore smart defaults" onPress={()=>Alert.alert("Restore defaults?","Ledgerly will recreate missing safe defaults.",[{text:"Cancel",style:"cancel"},{text:"Restore",onPress:()=>void schoolApi.restoreDefaults(c).then(()=>load(true)).catch(e=>Alert.alert("Failed",errText(e)))}])}/>
  </>:area==="identity"?<>
   <SectionTitle title="School users" subtitle="Accounts, access and login identities" action="Add user" onAction={()=>{setForm({status:"active",coreRole:"viewer",forcePasswordChange:"true"});setModal("user")}}/>
   {users.map(u=><Card key={u.userId||u.id||u.email} style={s.rowCard}><View style={s.rowTop}><View style={{flex:1}}><Text style={s.rowTitle}>{u.displayName}</Text><Text style={s.rowSub}>{u.email}{u.username?` · @${u.username}`:""}</Text></View><Pill text={u.status||"active"} tone={u.status==="active"?"good":"warn"}/></View><Text style={s.small}>{u.staffNumber||"No staff number"} · {u.coreRole||"viewer"}</Text><View style={s.actions}><SecondaryButton compact title="Activate" onPress={()=>void schoolApi.updateUser(c,String(u.userId||u.id),{status:"active"}).then(()=>load(true)).catch(e=>Alert.alert("Failed",errText(e)))}/><PrimaryButton compact danger title="Suspend" onPress={()=>void schoolApi.updateUser(c,String(u.userId||u.id),{status:"suspended"}).then(()=>load(true)).catch(e=>Alert.alert("Failed",errText(e)))}/></View></Card>)}
   <SectionTitle title="Roles" subtitle="System and custom role permission bundles" action="Add role" onAction={()=>{setForm({roleCategory:"custom"});setModal("role")}}/>
   {roles.map(r=><Card key={r.id} style={s.rowCard}><View style={s.rowTop}><View style={{flex:1}}><Text style={s.rowTitle}>{r.name}</Text><Text style={s.rowSub}>{r.code} · {r.permissions?.length||0} permissions</Text></View><Pill text={r.systemRole?"System":"Custom"} tone={r.systemRole?"neutral":"good"}/></View></Card>)}
   <SectionTitle title="Security policy" subtitle="Password, lockout, session and 2FA requirements" action="Edit" onAction={openSecurity}/><Card><Text style={s.rowTitle}>Minimum password: {security?.minimumPasswordLength||12} characters</Text><Text style={s.copy}>Failed-login lockout: {security?.maxFailedLogins||5} attempts · Session timeout: {security?.sessionTimeoutMinutes||480} minutes</Text><View style={s.securityLine}><Text style={s.small}>Administrator 2FA</Text><Pill text={security?.require2faForAdmins?"Required":"Optional"} tone={security?.require2faForAdmins?"good":"warn"}/></View></Card>
   <View style={{height:10}}/><SecondaryButton title="Restore built-in roles" onPress={()=>void schoolApi.bootstrapIam(c).then(()=>load(true)).catch(e=>Alert.alert("Failed",errText(e)))}/>
  </>:<>
   <SectionTitle title="School files" subtitle="R2-backed documents, evidence, photos and templates" action="Upload" onAction={()=>void upload()}/>
   <Card><Text style={s.rowTitle}>{files.length} active files</Text><Text style={s.copy}>Choose files directly from Android. Maximum upload size is 15 MB and the backend validates supported document, media and office formats.</Text></Card>
   {files.length?files.map(f=><Card key={f.id} style={s.rowCard}><View style={s.rowTop}><View style={{flex:1}}><Text numberOfLines={1} style={s.rowTitle}>{f.originalName}</Text><Text style={s.rowSub}>{f.mimeType} · {(Number(f.sizeBytes||0)/1024).toFixed(0)} KB</Text></View><Pill text={f.purpose||"document"}/></View><View style={s.actions}><SecondaryButton compact title="ID" onPress={()=>Alert.alert("File ID",f.id)}/><PrimaryButton compact danger title="Delete" onPress={()=>removeFile(f)}/></View></Card>):<Empty title="No school files" copy="Upload the first document, image, evidence file or template from this device."/>}
  </>}
  <Modal visible={modal!==null} transparent animationType="slide" onRequestClose={()=>setModal(null)}><View style={s.overlay}><View style={s.sheet}><View style={s.sheetHead}><Text style={s.sheetTitle}>{modal==="profile"?"School profile":modal==="setup"?`New ${labels[key]}`:modal==="user"?"New school user":modal==="role"?"New role":"Security policy"}</Text><TouchableOpacity onPress={()=>setModal(null)}><Text style={s.close}>×</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{paddingBottom:25}}>
   {modal==="profile"?<>{textField("schoolCode","School code")}{textField("registrationNumber")}{textField("motto")}{textField("schoolType")}{textField("ownershipType")}{textField("educationLevel")}{textField("curriculum")}{textField("phone")}{textField("email")}{textField("website")}{textField("physicalAddress")}{textField("country")}{textField("districtRegion")}{textField("headTeacherName")}{textField("headTeacherPhone")}{textField("headTeacherEmail")}{textField("timezone")}{textField("defaultCurrency")}</>:modal==="setup"?<>{dynamicSetupFields()}</>:modal==="user"?<>{textField("displayName","Display name")}{textField("email")}{textField("username")}{textField("phone")}{textField("password","Temporary password")}{select("roleId","School role",roles.map(r=>({label:r.name,value:r.id})))}{select("coreRole","Core Ledgerly role",["viewer","manager","accountant","admin"].map(x=>({label:x,value:x})))}{select("status","Status",["active","inactive","suspended","locked"].map(x=>({label:x,value:x})))}{select("forcePasswordChange","Force password change",yesNo)}</>:modal==="role"?<>{textField("code")}{textField("name")}{textField("description")}{textField("roleCategory","Role category")}<Field label="Permissions (comma or new line separated)" multiline value={form.permissions||""} onChangeText={v=>setForm(x=>({...x,permissions:v}))}/></>:modal==="security"?<>{textField("minimumPasswordLength")}{select("requireUppercase","Require uppercase",yesNo)}{select("requireLowercase","Require lowercase",yesNo)}{select("requireNumber","Require number",yesNo)}{select("requireSymbol","Require symbol",yesNo)}{textField("passwordExpiryDays")}{textField("passwordHistoryCount")}{textField("maxFailedLogins")}{textField("lockoutMinutes")}{textField("sessionTimeoutMinutes")}{select("require2faForAdmins","Require admin 2FA",yesNo)}{select("allowImpersonation","Allow impersonation",yesNo)}</>:null}
   <PrimaryButton title={saving?"Saving…":"Save"} disabled={saving} onPress={()=>void save()}/>
  </ScrollView></View></View></Modal>
 </ScrollView>
}
const s=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center"},muted:{color:"#708078",fontWeight:"800"},scroll:{padding:16,paddingBottom:36,gap:10},areaRow:{flexDirection:"row",gap:7,marginBottom:3},area:{flex:1,minHeight:42,borderRadius:13,borderWidth:1,borderColor:"#dce5e0",backgroundColor:"#fff",alignItems:"center",justifyContent:"center",paddingHorizontal:5},areaActive:{backgroundColor:"#163d30",borderColor:"#163d30"},areaText:{fontSize:9,fontWeight:"900",color:"#63776d",textAlign:"center"},areaTextActive:{color:"#d7f4e6"},school:{fontSize:20,fontWeight:"900",color:"#173126"},code:{fontSize:10,fontWeight:"900",color:"#148e5b",marginTop:4},copy:{fontSize:10,lineHeight:16,color:"#778980",marginTop:7},rowCard:{marginTop:0},rowTop:{flexDirection:"row",alignItems:"center",gap:8},rowTitle:{fontSize:13,fontWeight:"900",color:"#253d32"},rowSub:{fontSize:9,color:"#84938b",marginTop:3},small:{fontSize:9,color:"#71847a",marginTop:8},actions:{flexDirection:"row",justifyContent:"flex-end",gap:8,marginTop:12},securityLine:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:"#edf1ef",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},overlay:{flex:1,backgroundColor:"rgba(4,18,13,.5)",justifyContent:"flex-end"},sheet:{backgroundColor:"white",borderTopLeftRadius:26,borderTopRightRadius:26,maxHeight:"88%",padding:18},sheetHead:{flexDirection:"row",alignItems:"center",marginBottom:14},sheetTitle:{fontSize:19,fontWeight:"900",color:"#173126",flex:1},close:{fontSize:30,color:"#819087",paddingHorizontal:7}});
