import {Modal,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View,type TextInputProps,type ViewStyle} from "react-native";
import {useState} from "react";

export function Card({children,style}:{children:any;style?:ViewStyle}){return <View style={[s.card,style]}>{children}</View>}
export function SectionTitle({title,subtitle,action,onAction}:{title:string;subtitle?:string;action?:string;onAction?:()=>void}){return <View style={s.section}><View style={{flex:1,paddingRight:12}}><Text style={s.sectionTitle}>{title}</Text>{subtitle?<Text style={s.sectionSub}>{subtitle}</Text>:null}</View>{action&&onAction?<TouchableOpacity accessibilityRole="button" hitSlop={8} style={s.sectionActionButton} onPress={onAction}><Text style={s.sectionAction}>{action}</Text></TouchableOpacity>:null}</View>}
export function Field({label,...props}:TextInputProps&{label:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#84968d" {...props} style={[s.input,props.multiline&&s.multi,props.style]}/></View>}
export function SelectField({label,value,onChange,options,placeholder="Choose"}:{label:string;value?:string|null;onChange:(v:string)=>void;options:{label:string;value:string;detail?:string|null}[];placeholder?:string}){const[open,setOpen]=useState(false),selected=options.find(x=>x.value===value);return <View style={s.field}><Text style={s.label}>{label}</Text><TouchableOpacity accessibilityRole="button" style={s.select} onPress={()=>setOpen(true)}><Text style={[s.selectText,!selected&&s.placeholder]} numberOfLines={2}>{selected?.label||placeholder}</Text><Text style={s.chev}>⌄</Text></TouchableOpacity><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><TouchableOpacity activeOpacity={1} style={s.overlay} onPress={()=>setOpen(false)}><View style={s.sheet}><View style={s.sheetHandle}/><Text style={s.sheetTitle}>{label}</Text><ScrollView contentContainerStyle={s.options}>{options.length?options.map(x=><TouchableOpacity accessibilityRole="button" key={x.value} style={[s.option,x.value===value&&s.optionActive]} onPress={()=>{onChange(x.value);setOpen(false)}}><Text style={s.optionText}>{x.label}</Text>{x.detail?<Text style={s.optionDetail}>{x.detail}</Text>:null}</TouchableOpacity>):<Text style={s.emptyText}>No options available.</Text>}</ScrollView></View></TouchableOpacity></Modal></View>}
export function PrimaryButton({title,onPress,disabled,compact,danger}:{title:string;onPress:()=>void;disabled?:boolean;compact?:boolean;danger?:boolean}){return <TouchableOpacity accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.primary,compact&&s.compact,danger&&s.danger,disabled&&s.disabled]}><Text style={s.primaryText}>{title}</Text></TouchableOpacity>}
export function SecondaryButton({title,onPress,compact}:{title:string;onPress:()=>void;compact?:boolean}){return <TouchableOpacity accessibilityRole="button" onPress={onPress} style={[s.secondary,compact&&s.compact]}><Text style={s.secondaryText}>{title}</Text></TouchableOpacity>}
export function Pill({text,tone="neutral"}:{text:string;tone?:"neutral"|"good"|"warn"|"bad"}){return <View style={[s.pill,tone==="good"&&s.good,tone==="warn"&&s.warn,tone==="bad"&&s.bad]}><Text style={[s.pillText,tone==="good"&&s.goodText,tone==="warn"&&s.warnText,tone==="bad"&&s.badText]} numberOfLines={1}>{String(text||"—").toUpperCase()}</Text></View>}
export function Empty({title,copy}:{title:string;copy:string}){return <View style={s.empty}><Text style={s.emptyIcon}>◇</Text><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyText}>{copy}</Text></View>}
export function ErrorNotice({message,onRetry}:{message:string;onRetry?:()=>void}){return <View style={s.error}><Text style={s.errorTitle}>Couldn’t load this section</Text><Text style={s.errorText}>{message}</Text>{onRetry?<TouchableOpacity accessibilityRole="button" style={s.retryButton} onPress={onRetry}><Text style={s.retry}>Try again</Text></TouchableOpacity>:null}</View>}
export function Money({minor,currency="UGX",large=false}:{minor?:number|null;currency?:string;large?:boolean}){const value=Number(minor||0)/100;return <Text style={large?s.moneyLarge:s.money}>{currency} {value.toLocaleString(undefined,{maximumFractionDigits:0})}</Text>}
export function Metric({label,value,sub,tone="plain"}:{label:string;value:string|number;sub?:string;tone?:"plain"|"good"|"warn"|"bad"}){return <View style={[s.metric,tone==="good"&&s.metricGood,tone==="warn"&&s.metricWarn,tone==="bad"&&s.metricBad]}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text>{sub?<Text style={s.metricSub}>{sub}</Text>:null}</View>}

const s=StyleSheet.create({
 card:{backgroundColor:"#fff",borderRadius:20,borderWidth:1,borderColor:"#d9e3de",padding:18,shadowColor:"#132d22",shadowOpacity:.04,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:1},
 section:{flexDirection:"row",alignItems:"center",paddingTop:12,paddingBottom:6,minHeight:58},sectionTitle:{fontSize:20,lineHeight:25,fontWeight:"900",color:"#173126"},sectionSub:{fontSize:13,lineHeight:19,color:"#667b70",marginTop:4},sectionActionButton:{minHeight:44,minWidth:64,borderRadius:12,alignItems:"center",justifyContent:"center",paddingHorizontal:12,backgroundColor:"#e9f6ef"},sectionAction:{fontSize:13,fontWeight:"900",color:"#138c5a"},
 field:{marginBottom:16},label:{fontSize:12,lineHeight:16,fontWeight:"900",letterSpacing:.35,color:"#4f675b",marginBottom:8},input:{minHeight:54,borderRadius:14,borderWidth:1,borderColor:"#cfdcd5",backgroundColor:"#fbfcfb",paddingHorizontal:15,paddingVertical:12,color:"#20362c",fontSize:15,lineHeight:21},multi:{minHeight:112,textAlignVertical:"top",paddingTop:14},select:{minHeight:54,borderRadius:14,borderWidth:1,borderColor:"#cfdcd5",backgroundColor:"#fbfcfb",paddingHorizontal:15,paddingVertical:10,flexDirection:"row",alignItems:"center"},selectText:{fontSize:15,lineHeight:20,fontWeight:"700",color:"#263d33",flex:1},placeholder:{color:"#84968d",fontWeight:"600"},chev:{color:"#526e61",fontSize:21,marginLeft:8},
 overlay:{flex:1,backgroundColor:"rgba(4,18,13,.58)",justifyContent:"flex-end"},sheet:{backgroundColor:"white",borderTopLeftRadius:28,borderTopRightRadius:28,paddingHorizontal:18,paddingTop:10,paddingBottom:22,maxHeight:"78%"},sheetHandle:{alignSelf:"center",width:42,height:5,borderRadius:3,backgroundColor:"#d7e0dc",marginBottom:12},sheetTitle:{fontSize:21,lineHeight:26,fontWeight:"900",color:"#173126",marginBottom:12},options:{paddingBottom:8},option:{minHeight:58,paddingHorizontal:14,paddingVertical:12,borderRadius:14,borderBottomWidth:1,borderBottomColor:"#edf1ef",justifyContent:"center"},optionActive:{backgroundColor:"#eaf7f0"},optionText:{fontSize:15,lineHeight:20,fontWeight:"800",color:"#2c4338"},optionDetail:{fontSize:12,lineHeight:17,color:"#6f8178",marginTop:3},
 primary:{minHeight:54,borderRadius:14,backgroundColor:"#148e5b",alignItems:"center",justifyContent:"center",paddingHorizontal:18,paddingVertical:10},compact:{minHeight:44,minWidth:96},danger:{backgroundColor:"#b94d49"},disabled:{opacity:.45},primaryText:{color:"white",fontSize:14,lineHeight:18,fontWeight:"900"},secondary:{minHeight:54,borderRadius:14,borderWidth:1,borderColor:"#bdcec5",alignItems:"center",justifyContent:"center",paddingHorizontal:18,paddingVertical:10,backgroundColor:"#fff"},secondaryText:{fontSize:14,lineHeight:18,fontWeight:"900",color:"#365347"},
 pill:{maxWidth:160,minHeight:30,borderRadius:20,backgroundColor:"#edf1ef",paddingHorizontal:11,paddingVertical:7,alignItems:"center",justifyContent:"center"},pillText:{fontSize:10,lineHeight:13,fontWeight:"900",color:"#64766d",letterSpacing:.35},good:{backgroundColor:"#e3f6ec"},goodText:{color:"#148459"},warn:{backgroundColor:"#fff3dc"},warnText:{color:"#8b5b09"},bad:{backgroundColor:"#fae8e7"},badText:{color:"#9d3d39"},
 empty:{backgroundColor:"#eef3f0",borderRadius:20,padding:26,alignItems:"center"},emptyIcon:{fontSize:28,color:"#789187"},emptyTitle:{fontSize:16,lineHeight:21,fontWeight:"900",color:"#3b5549",marginTop:9,textAlign:"center"},emptyText:{fontSize:13,lineHeight:19,color:"#6f8178",textAlign:"center",marginTop:6,maxWidth:320},
 error:{backgroundColor:"#fff1ef",borderRadius:18,padding:16,borderWidth:1,borderColor:"#efcecb"},errorTitle:{fontSize:14,lineHeight:18,fontWeight:"900",color:"#8e3734"},errorText:{fontSize:13,lineHeight:19,color:"#89534f",marginTop:5},retryButton:{alignSelf:"flex-start",minHeight:42,justifyContent:"center",paddingHorizontal:4,marginTop:6},retry:{fontSize:13,fontWeight:"900",color:"#138c5a"},
 money:{fontSize:14,lineHeight:19,fontWeight:"900",color:"#1d3a2e"},moneyLarge:{fontSize:25,lineHeight:31,fontWeight:"900",color:"#152f24"},metric:{width:"48%",minHeight:110,borderRadius:18,backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe5e0",padding:15},metricGood:{backgroundColor:"#edf9f3"},metricWarn:{backgroundColor:"#fff8e9"},metricBad:{backgroundColor:"#fff0ef"},metricLabel:{fontSize:11,lineHeight:15,fontWeight:"900",letterSpacing:.25,color:"#61766b"},metricValue:{fontSize:24,lineHeight:30,fontWeight:"900",color:"#19372a",marginTop:8},metricSub:{fontSize:12,lineHeight:17,color:"#6f8178",marginTop:4}
});
