// @ts-nocheck
import {Hono} from "hono";
import {z} from "zod";
import type{AppVariables,Env}from"../../../src/types";
import{requireScope}from"../../../src/lib/auth";
import{AppError}from"../../../src/lib/errors";
import{auditStatement}from"../../../src/services/audit";

export const financeMobileOperationsRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();

financeMobileOperationsRoutes.get("/budgets/:id",requireScope("reports:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),budget=await c.env.FINANCE_DB.prepare(`SELECT id,name,fiscal_year AS fiscalYear,version,scenario,kind,parent_id AS parentId,status,locked_at AS lockedAt,created_at AS createdAt,updated_at AS updatedAt FROM budgets WHERE id=? AND organization_id=?`).bind(id,p.organizationId).first<any>();if(!budget)throw new AppError(404,"NOT_FOUND","Budget not found");const lines=await c.env.FINANCE_DB.prepare(`SELECT l.id,l.account_id AS accountId,a.code AS accountCode,a.name AS accountName,l.period,l.amount_minor AS amountMinor,l.class_id AS classId,cl.name AS className,l.department_id AS departmentId,d.name AS departmentName,l.location_id AS locationId,loc.name AS locationName FROM budget_lines l JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id LEFT JOIN dimensions cl ON cl.id=l.class_id AND cl.organization_id=l.organization_id LEFT JOIN dimensions d ON d.id=l.department_id AND d.organization_id=l.organization_id LEFT JOIN dimensions loc ON loc.id=l.location_id AND loc.organization_id=l.organization_id WHERE l.organization_id=? AND l.budget_id=? ORDER BY l.period,a.code`).bind(p.organizationId,id).all();return c.json({data:{...budget,lines:lines.results}})});

financeMobileOperationsRoutes.get("/banking/transactions/:id/match-candidates",requireScope("payments:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),tx=await c.env.FINANCE_DB.prepare(`SELECT t.id,t.bank_account_id AS bankAccountId,t.transaction_date AS transactionDate,t.amount_minor AS amountMinor,t.status,b.ledger_account_id AS ledgerAccountId FROM bank_transactions t JOIN bank_accounts b ON b.id=t.bank_account_id AND b.organization_id=t.organization_id WHERE t.id=? AND t.organization_id=?`).bind(id,p.organizationId).first<any>();if(!tx)throw new AppError(404,"NOT_FOUND","Bank transaction not found");const rows=await c.env.FINANCE_DB.prepare(`SELECT l.id AS journalLineId,j.id AS journalId,j.entry_number AS entryNumber,j.posting_date AS postingDate,j.description,j.reference,j.status,l.debit_minor AS debitMinor,l.credit_minor AS creditMinor,(l.debit_minor-l.credit_minor) AS netMinor FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.organization_id=l.organization_id WHERE l.organization_id=? AND l.account_id=? AND j.status IN ('posted','reversed') AND (l.debit_minor-l.credit_minor)=? AND ABS(julianday(j.posting_date)-julianday(?))<=14 AND NOT EXISTS(SELECT 1 FROM bank_transactions x WHERE x.organization_id=l.organization_id AND x.matched_journal_line_id=l.id AND x.id<>?) ORDER BY ABS(julianday(j.posting_date)-julianday(?)),j.posting_date DESC,j.entry_number DESC LIMIT 100`).bind(p.organizationId,tx.ledgerAccountId,tx.amountMinor,tx.transactionDate,id,tx.transactionDate).all();return c.json({data:{transaction:tx,candidates:rows.results}})});

financeMobileOperationsRoutes.get("/inventory/movements",requireScope("products:read"),async c=>{const p=c.get("principal"),productId=c.req.query("productId")||null,locationId=c.req.query("locationId")||null,limit=Math.max(1,Math.min(500,Number(c.req.query("limit")||200))),r=await c.env.FINANCE_DB.prepare(`SELECT m.id,m.product_id AS productId,p.sku,p.name AS productName,m.location_id AS locationId,l.code AS locationCode,l.name AS locationName,m.movement_type AS type,m.movement_date AS movementDate,m.quantity_delta_micros AS quantityDeltaMicros,m.unit_cost_minor AS unitCostMinor,m.value_delta_minor AS valueDeltaMinor,m.source_type AS sourceType,m.source_id AS sourceId,m.journal_entry_id AS journalEntryId,m.created_at AS createdAt FROM inventory_movements m JOIN products p ON p.id=m.product_id AND p.organization_id=m.organization_id JOIN inventory_locations l ON l.id=m.location_id AND l.organization_id=m.organization_id WHERE m.organization_id=? AND (? IS NULL OR m.product_id=?) AND (? IS NULL OR m.location_id=?) ORDER BY m.movement_date DESC,m.created_at DESC LIMIT ?`).bind(p.organizationId,productId,productId,locationId,locationId,limit).all();return c.json({data:r.results})});

financeMobileOperationsRoutes.get("/projects/:id",requireScope("documents:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),project=await c.env.FINANCE_DB.prepare(`SELECT p.id,p.customer_id AS customerId,c.name AS customer,p.code,p.name,p.status,p.budget_amount_minor AS budgetAmountMinor,p.created_at AS createdAt,p.updated_at AS updatedAt FROM projects p LEFT JOIN contacts c ON c.id=p.customer_id AND c.organization_id=p.organization_id WHERE p.id=? AND p.organization_id=?`).bind(id,p.organizationId).first<any>();if(!project)throw new AppError(404,"NOT_FOUND","Finance project not found");const time=await c.env.FINANCE_DB.prepare(`SELECT t.id,t.user_id AS userId,u.display_name AS userName,t.entry_date AS entryDate,t.minutes,t.description,t.billable,t.cost_rate_minor AS costRateMinor,t.billing_rate_minor AS billingRateMinor,t.status,t.created_at AS createdAt,t.updated_at AS updatedAt FROM time_entries t JOIN users u ON u.id=t.user_id WHERE t.organization_id=? AND t.project_id=? ORDER BY t.entry_date DESC,t.created_at DESC`).bind(p.organizationId,id).all();return c.json({data:{...project,timeEntries:time.results}})});

financeMobileOperationsRoutes.get("/tax/exemptions",requireScope("accounts:read"),async c=>{const p=c.get("principal"),r=await c.env.FINANCE_DB.prepare(`SELECT e.id,e.contact_id AS contactId,c.name AS contactName,e.tax_code_id AS taxCodeId,t.code AS taxCode,e.certificate_number AS certificateNumber,e.reason,e.starts_on AS startsOn,e.ends_on AS endsOn,e.created_at AS createdAt FROM tax_exemptions e LEFT JOIN contacts c ON c.id=e.contact_id AND c.organization_id=e.organization_id LEFT JOIN tax_codes t ON t.id=e.tax_code_id AND t.organization_id=e.organization_id WHERE e.organization_id=? ORDER BY COALESCE(e.ends_on,'9999-12-31') DESC,e.created_at DESC`).bind(p.organizationId).all();return c.json({data:r.results})});

const product=z.object({sku:z.string().trim().min(1).max(60),name:z.string().trim().min(1).max(160),type:z.enum(["inventory","service","non_inventory"]),incomeAccountId:z.string().optional().nullable(),expenseAccountId:z.string().optional().nullable(),inventoryAccountId:z.string().optional().nullable(),quantityOnHandMicros:z.number().int().default(0),averageCostMinor:z.number().int().nonnegative().default(0),reorderPointMicros:z.number().int().nonnegative().default(0),active:z.boolean().default(true)});
financeMobileOperationsRoutes.put("/products/:id",requireScope("products:write"),async c=>{const s=product.safeParse(await c.req.json().catch(()=>({})));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid product",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=s.data,ids=[v.incomeAccountId,v.expenseAccountId,v.inventoryAccountId].filter(Boolean);if(ids.length){const found=await c.env.FINANCE_DB.prepare(`SELECT COUNT(DISTINCT id) n FROM accounts WHERE organization_id=? AND id IN (${ids.map(()=>"?").join(",")})`).bind(p.organizationId,...ids).first<any>();if(Number(found?.n||0)!==new Set(ids).size)throw new AppError(422,"INVALID_ACCOUNT","All product accounts must belong to the organization")}const r=await c.env.FINANCE_DB.prepare(`UPDATE products SET sku=?,name=?,type=?,income_account_id=?,expense_account_id=?,inventory_account_id=?,quantity_on_hand_micros=?,average_cost_minor=?,reorder_point_micros=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(v.sku,v.name,v.type,v.incomeAccountId??null,v.expenseAccountId??null,v.inventoryAccountId??null,v.quantityOnHandMicros,v.averageCostMinor,v.reorderPointMicros,v.active?1:0,id,p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Product not found");await auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"product.updated",entityType:"product",entityId:id,after:v}).run();return c.json({data:{id,...v}})});
financeMobileOperationsRoutes.patch("/products/:id/active",requireScope("products:write"),async c=>{const s=z.object({active:z.boolean()}).safeParse(await c.req.json().catch(()=>({})));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid product status");const p=c.get("principal"),id=c.req.param("id"),r=await c.env.FINANCE_DB.prepare("UPDATE products SET active=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(s.data.active?1:0,id,p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Product not found");return c.json({data:{id,active:s.data.active}})});

const bank=z.object({ledgerAccountId:z.string(),name:z.string().trim().min(1).max(160),bankName:z.string().trim().max(160).optional().nullable(),accountNumberMasked:z.string().trim().max(40).optional().nullable(),currency:z.string().length(3).toUpperCase(),openingBalanceMinor:z.number().int().default(0),active:z.boolean().default(true)});
financeMobileOperationsRoutes.put("/banking/accounts/:id",requireScope("accounts:write"),async c=>{const s=bank.safeParse(await c.req.json().catch(()=>({})));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid bank account",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=s.data,ledger=await c.env.FINANCE_DB.prepare("SELECT id FROM accounts WHERE id=? AND organization_id=? AND type='asset' AND active=1").bind(v.ledgerAccountId,p.organizationId).first();if(!ledger)throw new AppError(422,"INVALID_LEDGER_ACCOUNT","Active asset ledger account required");const r=await c.env.FINANCE_DB.prepare(`UPDATE bank_accounts SET ledger_account_id=?,name=?,bank_name=?,account_number_masked=?,currency=?,opening_balance_minor=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(v.ledgerAccountId,v.name,v.bankName??null,v.accountNumberMasked??null,v.currency,v.openingBalanceMinor,v.active?1:0,id,p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Bank account not found");return c.json({data:{id,...v}})});
