import { useEffect,useMemo,useRef,useState,type DragEvent,type ReactNode } from "react";
import { Bot,Brain,Briefcase,Camera,ChevronRight,CirclePlus,Crown,Download,FileImage,FileSpreadsheet,FileText,GraduationCap,History,Image as ImageIcon,LoaderCircle,Paperclip,Presentation,ScanLine,Send,ShieldCheck,Sparkles,Users,Wallet,X } from "lucide-react";
import { ApiError,authStore,downloadFile,errorText,get,post,uploadFile } from "../../../web/api";

type Agent={key:string;name:string;title:string;description:string;modelTier:"luna"|"terra"|"sol";enabled:boolean;configuredTools:string[]};
type Conversation={id:string;agentKey:string;title:string;status:string;lastMessageAt?:string;createdAt?:string};
type ImageAttachment={kind:"image";id:string;name:string;mimeType:string;sizeBytes:number;status:string;ocrText?:string;visionSummary?:string;previewPath:string};
type DocumentAttachment={kind:"document";id:string;name:string;format:"docx"|"xlsx"|"pptx";mimeType:string;sourceSizeBytes:number;pdfSizeBytes:number;pdfPageCount:number;createdAt?:string;sourcePath:string;pdfPath:string};
type Attachment=ImageAttachment|DocumentAttachment;
type Message={id:string;role:"user"|"assistant"|"system";content:string;model?:string;createdAt?:string;attachments?:Attachment[]};
type WorkspacePayload={conversation:Conversation;messages:Message[];artifacts:DocumentAttachment[]};
type VisionResult={id:string;originalName:string;mimeType:string;sizeBytes:number;status:string;ocrText:string;visionSummary:string;model:string;provider:string;previewPath:string};
type PendingImage={key:string;file:File;preview:string;status:"queued"|"scanning"|"ready"|"failed";result?:VisionResult;error?:string};
type Approval={id:string};
type ProviderSettings={provider:string;configured:boolean};

const PROFILE:Record<string,{icon:ReactNode;label:string;accent:string}>={
 secretary:{icon:<Briefcase size={18}/>,label:"Office",accent:"mint"},dos:{icon:<GraduationCap size={18}/>,label:"Academics",accent:"blue"},bursar:{icon:<Wallet size={18}/>,label:"Finance",accent:"amber"},headteacher:{icon:<Crown size={18}/>,label:"Management",accent:"violet"},hr:{icon:<Users size={18}/>,label:"People",accent:"rose"},librarian:{icon:<FileText size={18}/>,label:"Library",accent:"teal"}
};
const FALLBACK={icon:<Bot size={18}/>,label:"AI",accent:"slate"};
const MAX_IMAGES=8;

function profile(key:string){return PROFILE[key]||FALLBACK;}
function when(value?:string){if(!value)return"recent";const d=new Date(value);if(Number.isNaN(d.getTime()))return value;const diff=Date.now()-d.getTime();if(diff<60000)return"now";if(diff<3600000)return`${Math.max(1,Math.floor(diff/60000))}m`;if(diff<86400000)return`${Math.floor(diff/3600000)}h`;return d.toLocaleDateString();}
function size(n:number){if(!Number.isFinite(n)||n<=0)return"—";return n>=1024*1024?`${(n/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;}
function docIcon(format:string){return format==="xlsx"?<FileSpreadsheet size={20}/>:format==="pptx"?<Presentation size={20}/>:<FileText size={20}/>;}

async function fetchProtectedBlob(path:string){const response=await fetch(`/api/v1${path}`,{headers:{Authorization:`Bearer ${authStore.getAccess()||""}`}});if(!response.ok){const payload=await response.clone().json().catch(()=>({})) as any;throw new ApiError(response.status,payload?.error?.code||"FILE_FAILED",payload?.error?.message||`File request failed (${response.status})`);}return response.blob();}
function ProtectedImage({attachment}:{attachment:ImageAttachment}){const[url,setUrl]=useState("");const[failed,setFailed]=useState(false);useEffect(()=>{let live=true,current="";void fetchProtectedBlob(attachment.previewPath).then(blob=>{if(!live)return;current=URL.createObjectURL(blob);setUrl(current);}).catch(()=>live&&setFailed(true));return()=>{live=false;if(current)URL.revokeObjectURL(current);};},[attachment.id,attachment.previewPath]);return failed?<div className="aew-image-fallback"><FileImage/><span>{attachment.name}</span></div>:url?<img src={url} alt={attachment.name}/>:<div className="aew-image-loading"><LoaderCircle className="spin"/></div>;}

export function AIWorkspacePage(){
 const[agents,setAgents]=useState<Agent[]>([]),[conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState("secretary"),[conversation,setConversation]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[artifacts,setArtifacts]=useState<DocumentAttachment[]>([]),[text,setText]=useState(""),[pending,setPending]=useState<PendingImage[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[dragging,setDragging]=useState(false),[approvals,setApprovals]=useState(0),[provider,setProvider]=useState<ProviderSettings|null>(null);
 const fileInput=useRef<HTMLInputElement>(null),cameraInput=useRef<HTMLInputElement>(null),chatEnd=useRef<HTMLDivElement>(null);
 const agent=useMemo(()=>agents.find(a=>a.key===selected)||agents[0],[agents,selected]),p=profile(agent?.key||selected);
 const agentThreads=useMemo(()=>conversations.filter(c=>c.agentKey===selected),[conversations,selected]);

 async function refreshShell(){try{const[a,c,pendingApprovals,approvedApprovals,s]=await Promise.all([get<Agent[]>("/agentic-employees/agents"),get<Conversation[]>("/agentic-employees/conversations"),get<Approval[]>("/agentic-employees/approvals?status=pending").catch(()=>[]),get<Approval[]>("/agentic-employees/approvals?status=approved").catch(()=>[]),get<ProviderSettings>("/agentic-employees/provider/settings").catch(()=>get<ProviderSettings>("/agentic-employees/settings"))]);setAgents(a);setConversations(c);setApprovals(pendingApprovals.length+approvedApprovals.length);setProvider(s);if(a.length&&!a.some(x=>x.key===selected))setSelected(a[0].key);return{agents:a,conversations:c};}catch(e){setError(errorText(e));return null;}}
 async function loadThread(thread:Conversation){setBusy(true);setError("");setSelected(thread.agentKey);try{const data=await get<WorkspacePayload>(`/agentic-employees/workspace/conversations/${thread.id}/messages`);setConversation(thread);setMessages(data.messages);setArtifacts(data.artifacts);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function newThread(nextAgent=agent){if(!nextAgent||busy)return null;setBusy(true);setError("");try{const thread=await post<Conversation>("/agentic-employees/conversations",{agentKey:nextAgent.key,title:`${nextAgent.name} workspace`});setConversation(thread);setMessages([]);setArtifacts([]);setSelected(nextAgent.key);setConversations(cur=>[thread,...cur]);return thread;}catch(e){setError(errorText(e));return null;}finally{setBusy(false);}}
 async function chooseAgent(next:Agent){setSelected(next.key);const recent=conversations.find(c=>c.agentKey===next.key);if(recent)await loadThread(recent);else{setConversation(null);setMessages([]);setArtifacts([]);}}
 useEffect(()=>{void(async()=>{const data=await refreshShell();if(!data)return;const requested=sessionStorage.getItem("ae:openConversation");if(requested){sessionStorage.removeItem("ae:openConversation");const found=data.conversations.find(c=>c.id===requested);if(found){await loadThread(found);return;}}const first=data.conversations[0];if(first)await loadThread(first);})();},[]);
 useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:"smooth",block:"end"});},[messages,busy]);
 useEffect(()=>()=>{for(const item of pending)URL.revokeObjectURL(item.preview);},[]);

 function addFiles(files:File[]){setError("");const images=files.filter(file=>["image/jpeg","image/png","image/webp"].includes(file.type));if(images.length!==files.length)setError("Only JPEG, PNG and WebP images can be scanned in chat.");setPending(current=>{const room=Math.max(0,MAX_IMAGES-current.length),next=images.slice(0,room).filter(file=>file.size<=10*1024*1024).map(file=>({key:`${Date.now()}-${Math.random()}`,file,preview:URL.createObjectURL(file),status:"queued" as const}));if(images.some(file=>file.size>10*1024*1024))setError("Each image must be 10 MB or smaller.");if(images.length>room)setError(`A chat message can contain up to ${MAX_IMAGES} images.`);return[...current,...next];});}
 function removePending(key:string){setPending(current=>{const target=current.find(x=>x.key===key);if(target)URL.revokeObjectURL(target.preview);return current.filter(x=>x.key!==key);});}
 function updatePending(key:string,patch:Partial<PendingImage>){setPending(current=>current.map(item=>item.key===key?{...item,...patch}:item));}
 function drop(e:DragEvent){e.preventDefault();setDragging(false);addFiles(Array.from(e.dataTransfer.files));}
 async function scanOne(item:PendingImage){if(item.result)return item.result;updatePending(item.key,{status:"scanning",error:""});try{const result=await uploadFile<VisionResult>("/agentic-employees/workspace/images",item.file,"agentic-chat-image");updatePending(item.key,{status:"ready",result});return result;}catch(e){const message=errorText(e);updatePending(item.key,{status:"failed",error:message});throw e;}}
 async function scanAll(){if(!pending.length||busy)return;setBusy(true);setError("");try{for(const item of pending)await scanOne(item);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function send(){if(busy||(!text.trim()&&!pending.length))return;setBusy(true);setError("");try{let thread=conversation;if(!thread){if(!agent)throw new Error("Choose an AI employee first.");thread=await post<Conversation>("/agentic-employees/conversations",{agentKey:agent.key,title:`${agent.name} workspace`});setConversation(thread);setConversations(cur=>[thread!,...cur]);}
   const scans:VisionResult[]=[];for(const item of pending)scans.push(await scanOne(item));const content=text.trim();await post(`/agentic-employees/workspace/conversations/${thread.id}/messages`,{content,imageIds:scans.map(x=>x.id)});setText("");setPending(current=>{for(const item of current)URL.revokeObjectURL(item.preview);return[];});const data=await get<WorkspacePayload>(`/agentic-employees/workspace/conversations/${thread.id}/messages`);setMessages(data.messages);setArtifacts(data.artifacts);await refreshShell();
  }catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function openPdf(doc:DocumentAttachment){try{const blob=await fetchProtectedBlob(doc.pdfPath),url=URL.createObjectURL(blob),win=window.open(url,"_blank","noopener,noreferrer");if(!win)await downloadFile(doc.pdfPath,`${doc.name}.pdf`);setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setError(errorText(e));}}
 function nav(path:string){location.hash=path;}

 return <div className="aew-page">
  <header className="aew-topbar"><div className="aew-brand"><span className={`aew-agent-avatar accent-${p.accent}`}>{p.icon}</span><div><small>LEDGERLY AI WORKSPACE</small><h1>{agent?.name||"AI employee"}</h1><p>{agent?.title||"Choose an employee"} · {agent?.modelTier?.toUpperCase()||""}</p></div></div><div className="aew-top-actions"><span className={`aew-provider-pill ${provider?.configured?"online":"offline"}`}><Sparkles size={14}/>{provider?.configured?`${provider.provider} connected`:"AI setup required"}</span><button className="secondary" onClick={()=>nav("agentic-employees-workforce")}><Users size={16}/> Workforce</button><button className={approvals?"attention-button":"secondary"} onClick={()=>nav("agentic-employees-actions")}><ShieldCheck size={16}/> Actions{approvals>0&&<em>{approvals}</em>}</button></div></header>
  {error&&<div className="aew-error">{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}
  <div className="aew-layout">
   <aside className="aew-left"><div className="aew-left-head"><b>AI team</b><button title="New conversation" onClick={()=>void newThread()} disabled={!agent||busy}><CirclePlus size={18}/></button></div><div className="aew-agent-list">{agents.map(item=>{const pp=profile(item.key);return <button key={item.key} className={item.key===selected?"active":""} disabled={!item.enabled} onClick={()=>void chooseAgent(item)}><span className={`aew-mini-avatar accent-${pp.accent}`}>{pp.icon}</span><span><b>{item.name}</b><small>{pp.label}</small></span><i className={item.enabled?"online":""}/></button>;})}</div><div className="aew-thread-head"><span>CONVERSATIONS</span><small>{agentThreads.length}</small></div><div className="aew-thread-list">{agentThreads.map(thread=><button key={thread.id} className={conversation?.id===thread.id?"active":""} onClick={()=>void loadThread(thread)}><History size={14}/><span><b>{thread.title}</b><small>{when(thread.lastMessageAt||thread.createdAt)}</small></span></button>)}{!agentThreads.length&&<p>No conversations yet.</p>}</div></aside>
   <main className="aew-main" onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={drop}>
    {dragging&&<div className="aew-drop-overlay"><ScanLine size={34}/><b>Drop images to scan</b><span>Up to {MAX_IMAGES} images in one message</span></div>}
    <div className="aew-contextbar"><span><ShieldCheck size={14}/> School-scoped access</span><span><Brain size={14}/> Memory on</span><span><ScanLine size={14}/> Multi-image OCR</span><span><FileText size={14}/> PDF & Office outputs</span></div>
    <section className="aew-chat">
     {!conversation&&!messages.length&&<div className="aew-empty"><div className={`aew-empty-icon accent-${p.accent}`}>{p.icon}</div><h2>Work with {agent?.name||"your AI employee"}</h2><p>Ask naturally, attach photos or scans, and receive structured answers and generated files in the same conversation.</p><div className="aew-suggestions"><button onClick={()=>setText("Give me a concise briefing of what needs my attention today.")}>Daily briefing<ChevronRight size={14}/></button><button onClick={()=>fileInput.current?.click()}>Scan school records<ChevronRight size={14}/></button><button onClick={()=>setText("Prepare a professional PDF and editable document for ")}>Create a document<ChevronRight size={14}/></button></div></div>}
     {messages.map(message=><article key={message.id} className={`aew-message ${message.role}`}><div className="aew-message-meta"><span className={message.role==="assistant"?`accent-${p.accent}`:""}>{message.role==="assistant"?p.icon:<Users size={15}/>}</span><b>{message.role==="assistant"?agent?.name:"You"}</b>{message.createdAt&&<small>{when(message.createdAt)}</small>}</div><div className="aew-bubble"><div className="aew-message-text">{message.content}</div>{message.attachments?.length?<AttachmentGrid attachments={message.attachments} onDownload={async doc=>{try{await downloadFile(doc.sourcePath,`${doc.name}.${doc.format}`);}catch(e){setError(errorText(e));}}} onPdf={openPdf}/>:null}{message.model&&<span className="aew-model">{message.model}</span>}</div></article>)}
     {busy&&<article className="aew-message assistant"><div className="aew-message-meta"><span className={`accent-${p.accent}`}>{p.icon}</span><b>{agent?.name}</b></div><div className="aew-bubble aew-thinking"><LoaderCircle className="spin"/><span>{pending.some(x=>x.status==="scanning")?"Scanning attached images…":"Working with Ledgerly…"}</span></div></article>}
     <div ref={chatEnd}/>
    </section>
    <div className="aew-compose-wrap">
     {pending.length>0&&<div className="aew-pending"><div className="aew-pending-head"><span><ScanLine size={15}/><b>{pending.length} image{pending.length===1?"":"s"} attached</b></span><button disabled={busy} onClick={()=>void scanAll()}>Scan now</button></div><div className="aew-pending-grid">{pending.map(item=><div key={item.key} className={`aew-pending-card ${item.status}`}><img src={item.preview} alt={item.file.name}/><button className="remove" disabled={busy} onClick={()=>removePending(item.key)}><X size={14}/></button><span>{item.status==="scanning"?<LoaderCircle className="spin" size={13}/>:item.status==="ready"?<ScanLine size={13}/>:item.status==="failed"?<X size={13}/>:<ImageIcon size={13}/>} {item.status==="queued"?"Ready to scan":item.status}</span><small>{item.file.name}</small></div>)}</div></div>}
     <div className="aew-quickbar"><button onClick={()=>fileInput.current?.click()} disabled={busy||pending.length>=MAX_IMAGES}><Paperclip size={15}/> Images</button><button onClick={()=>cameraInput.current?.click()} disabled={busy||pending.length>=MAX_IMAGES}><Camera size={15}/> Camera</button><button onClick={()=>setText(current=>current||"Create a professional PDF and editable document for ")}><FileText size={15}/> Create file</button><button onClick={()=>nav("agentic-employees-memory")}><Brain size={15}/> Memory</button><input ref={fileInput} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{addFiles(Array.from(e.target.files||[]));e.currentTarget.value="";}}/><input ref={cameraInput} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{addFiles(Array.from(e.target.files||[]));e.currentTarget.value="";}}/></div>
     <div className="aew-composer"><textarea rows={1} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder={`Message ${agent?.name||"your AI employee"}… attach images, ask for reports, PDFs or editable files`}/><button className="aew-send" disabled={busy||(!text.trim()&&!pending.length)} onClick={()=>void send()}><Send size={18}/><span>{pending.length?"Scan & send":"Send"}</span></button></div><small className="aew-compose-note">Images are scanned first. Any business change still requires the normal Ledgerly preview and human approval.</small>
    </div>
   </main>
   <aside className="aew-right"><div className="aew-right-card"><span className="aew-right-kicker">CURRENT EMPLOYEE</span><div className="aew-right-agent"><span className={`aew-agent-avatar accent-${p.accent}`}>{p.icon}</span><div><b>{agent?.name}</b><small>{agent?.title}</small></div></div><div className="aew-capabilities"><span>{agent?.configuredTools.length||0} permitted tools</span><span>{agent?.modelTier.toUpperCase()} model tier</span><span>Tenant-safe data access</span></div></div><div className="aew-right-card"><div className="aew-right-title"><b>Conversation files</b><button onClick={()=>nav("agentic-employees-documents")}>All</button></div>{artifacts.slice(-5).reverse().map(doc=><div key={doc.id} className="aew-mini-doc">{docIcon(doc.format)}<span><b>{doc.name}</b><small>{doc.format.toUpperCase()} + PDF</small></span><button title="Open PDF" onClick={()=>void openPdf(doc)}><ChevronRight size={15}/></button></div>)}{!artifacts.length&&<div className="aew-right-empty"><FileText size={22}/><span>Generated PDFs and editable documents from this chat will appear here.</span></div>}</div><div className="aew-right-card aew-scan-card"><ScanLine size={22}/><b>Smart image scanning</b><p>Attach receipts, handwritten notes, forms, tables, lesson plans or fee sheets. Multiple images are read together as one task.</p><button className="secondary" onClick={()=>nav("agentic-employees-vision")}>Open full scanner</button></div></aside>
  </div>
 </div>;
}

function AttachmentGrid({attachments,onDownload,onPdf}:{attachments:Attachment[];onDownload:(doc:DocumentAttachment)=>void|Promise<void>;onPdf:(doc:DocumentAttachment)=>void|Promise<void>}){const images=attachments.filter((x):x is ImageAttachment=>x.kind==="image"),docs=attachments.filter((x):x is DocumentAttachment=>x.kind==="document");return <div className="aew-attachments">{images.length>0&&<div className={`aew-message-images count-${Math.min(images.length,4)}`}>{images.map(image=><div key={image.id} className="aew-message-image"><ProtectedImage attachment={image}/><div><b>{image.name}</b><span>Scanned image · {size(image.sizeBytes)}</span></div>{(image.ocrText||image.visionSummary)&&<details><summary>Scan details</summary>{image.ocrText&&<><b>OCR</b><pre>{image.ocrText}</pre></>}{image.visionSummary&&<><b>Visual structure</b><pre>{image.visionSummary}</pre></>}</details>}</div>)}</div>}{docs.map(doc=><div key={doc.id} className="aew-doc-card"><span className="aew-doc-icon">{docIcon(doc.format)}</span><div><b>{doc.name}</b><small>{doc.format.toUpperCase()} · {size(doc.sourceSizeBytes)} · PDF {doc.pdfPageCount||1} page{doc.pdfPageCount===1?"":"s"}</small><span>AI-generated file · editable source + printable PDF</span></div><div className="aew-doc-actions"><button onClick={()=>void onPdf(doc)}><FileText size={14}/> PDF</button><button onClick={()=>void onDownload(doc)}><Download size={14}/> {doc.format.toUpperCase()}</button></div></div>)}</div>;}
