import { useEffect,useState } from "react";
import { Brain,CheckCircle2,Clock3,Plus,Search } from "lucide-react";
import { errorText,get,patch,post } from "../../../web/api";

type Agent={key:string;name:string;title:string};
type Memory={id:string;agentKey:string;memoryType:"working"|"institutional";visibility:"agent"|"organization";title:string;content:string;status:string;priority:string;dueAt?:string|null;tags?:string[];updatedAt?:string};
export function MemoryPage(){const[agents,setAgents]=useState<Agent[]>([]),[agentKey,setAgentKey]=useState("headteacher"),[items,setItems]=useState<Memory[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[type,setType]=useState<"working"|"institutional">("working"),[title,setTitle]=useState(""),[content,setContent]=useState(""),[dueAt,setDueAt]=useState(""),[visibility,setVisibility]=useState<"agent"|"organization">("agent");
 async function load(){setError("");try{const[a,m]=await Promise.all([get<Agent[]>("/agentic-employees/memory-agents"),get<Memory[]>(`/agentic-employees/memories?agentKey=${encodeURIComponent(agentKey)}&query=${encodeURIComponent(query)}`)]);setAgents(a);setItems(m);}catch(e){setError(errorText(e));}}
 useEffect(()=>{void load();},[agentKey]);
 async function add(){if(!title.trim()||!content.trim())return;setBusy(true);try{await post("/agentic-employees/memories",{agentKey,memoryType:type,title:title.trim(),content:content.trim(),visibility,priority:"normal",dueAt:dueAt||null,tags:[]});setTitle("");setContent("");setDueAt("");await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function status(item:Memory,next:string){setBusy(true);try{await patch(`/agentic-employees/memories/${item.id}`,{status:next});await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="ae-page"><div className="ae-hero"><div><span className="ae-kicker">LEDGERLY AI MEMORY</span><h1><Brain size={28}/> Employee Memory</h1><p>Conversation context stays in chat. Working memory tracks open commitments. Institutional memory keeps durable school preferences, procedures and decisions.</p></div></div>{error&&<div className="ae-error">{error}</div>}
 <div className="ae-panel"><div className="ae-form-row"><select value={agentKey} onChange={e=>setAgentKey(e.target.value)}>{agents.map(a=><option key={a.key} value={a.key}>{a.name} · {a.title}</option>)}</select><div style={{display:"flex",gap:8}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search memories…"/><button onClick={()=>void load()}><Search size={15}/>Search</button></div></div></div>
 <div className="ae-panel"><h2>Add memory</h2><div className="ae-form-row"><select value={type} onChange={e=>setType(e.target.value as any)}><option value="working">Working memory</option><option value="institutional">Institutional memory</option></select><select value={visibility} onChange={e=>setVisibility(e.target.value as any)}><option value="agent">This employee only</option><option value="organization">Shared across employees</option></select>{type==="working"&&<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/>}</div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Memory title"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder={type==="working"?"What must this employee remember to do?":"What durable preference, procedure or decision should be remembered?"}/><button disabled={busy} onClick={()=>void add()}><Plus size={15}/>Save memory</button></div>
 <div className="ae-panel"><h2>Saved memory</h2><div className="ae-list">{items.map(item=><div key={item.id}>{item.memoryType==="working"?<Clock3/>:<Brain/>}<div style={{flex:1}}><b>{item.title}</b><small>{item.memoryType} · {item.priority} · {item.visibility} · {item.status}{item.dueAt?` · due ${item.dueAt}`:""}</small><p>{item.content}</p>{item.tags?.length?<small>{item.tags.join(" · ")}</small>:null}<div className="ae-actions">{item.memoryType==="working"&&!['done','cancelled'].includes(item.status)&&<><button disabled={busy} onClick={()=>void status(item,"done")}><CheckCircle2 size={14}/>Done</button><button className="secondary" disabled={busy} onClick={()=>void status(item,"waiting")}>Waiting</button><button className="secondary" disabled={busy} onClick={()=>void status(item,"cancelled")}>Cancel</button></>}{item.memoryType==="institutional"&&item.status==="active"&&<button className="secondary" disabled={busy} onClick={()=>void status(item,"archived")}>Archive</button>}</div></div></div>)}{!items.length&&<p>No active memories for this employee.</p>}</div></div></div>;
}
