import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const medication=z.object({medicationName:z.string().min(1).max(200),dose:z.string().max(120).nullable().optional(),route:z.string().max(120).nullable().optional(),frequency:z.string().max(120).nullable().optional(),quantity:z.string().max(120).nullable().optional(),administeredAt:z.string().nullable().optional(),instructions:z.string().max(2000).nullable().optional()});
const immunization=z.object({vaccineName:z.string().min(1).max(200),doseNumber:z.string().max(80).nullable().optional(),administeredOn:date,nextDueOn:date.nullable().optional(),provider:z.string().max(200).nullable().optional(),batchNumber:z.string().max(120).nullable().optional(),notes:z.string().max(2000).nullable().optional()});
const referral=z.object({facilityName:z.string().min(2).max(240),reason:z.string().min(2).max(3000),referredAt:z.string().nullable().optional(),followUpOn:date.nullable().optional()});
const referralUpdate=z.object({status:z.enum(["referred","attended","completed","cancelled"]).optional(),outcome:z.string().max(4000).nullable().optional(),followUpOn:date.nullable().optional()}).refine(v=>Object.keys(v).length>0,{message:"At least one change is required"});
function camel(row:Record<string,unknown>){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(row))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return out;}
async function requireStudent(runtime:Runtime,org:string,id:string){const q=await runtime.db.query(`SELECT id FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[id,org]);if(!q.rowCount)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");}
async function requireVisit(runtime:Runtime,org:string,id:string){const q=await runtime.db.query(`SELECT id,student_id FROM school_clinic_visits WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(404,"VISIT_NOT_FOUND","Clinic visit not found");return q.rows[0] as {id:string;student_id:string};}

export function createClinicRecordRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/visits/:visitId/medications",async c=>{const p=c.get("principal"),visitId=c.req.param("visitId");await requireVisit(runtime,p.organizationId,visitId);const q=await runtime.db.query(`SELECT m.*,u.display_name AS administered_by_name FROM school_clinic_medications m LEFT JOIN users u ON u.id=m.administered_by WHERE m.organization_id=$1 AND m.visit_id=$2 ORDER BY COALESCE(m.administered_at,m.created_at),m.created_at`,[p.organizationId,visitId]);return c.json({data:q.rows.map(camel)});});
 r.post("/visits/:visitId/medications",requireScope("school:write"),async c=>{const parsed=medication.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid medication record",parsed.error.flatten());const p=c.get("principal"),visitId=c.req.param("visitId"),v=parsed.data;await requireVisit(runtime,p.organizationId,visitId);const id=createId("med");await runtime.db.query(`INSERT INTO school_clinic_medications(id,organization_id,visit_id,medication_name,dose,route,frequency,quantity,administered_at,instructions,administered_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::timestamptz,$10,$11)`,[id,p.organizationId,visitId,v.medicationName,v.dose??null,v.route??null,v.frequency??null,v.quantity??null,v.administeredAt??null,v.instructions??null,v.administeredAt?p.userId:null]);return c.json({data:{id,visitId,...v}},201);});
 r.get("/students/:studentId/immunizations",async c=>{const p=c.get("principal"),studentId=c.req.param("studentId");await requireStudent(runtime,p.organizationId,studentId);const q=await runtime.db.query(`SELECT i.*,u.display_name AS created_by_name FROM school_student_immunizations i LEFT JOIN users u ON u.id=i.created_by WHERE i.organization_id=$1 AND i.student_id=$2 ORDER BY i.administered_on DESC,i.created_at DESC`,[p.organizationId,studentId]);return c.json({data:q.rows.map(camel)});});
 r.post("/students/:studentId/immunizations",requireScope("school:write"),async c=>{const parsed=immunization.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid immunization record",parsed.error.flatten());const p=c.get("principal"),studentId=c.req.param("studentId"),v=parsed.data;await requireStudent(runtime,p.organizationId,studentId);const id=createId("imm");await runtime.db.query(`INSERT INTO school_student_immunizations(id,organization_id,student_id,vaccine_name,dose_number,administered_on,next_due_on,provider,batch_number,notes,created_by) VALUES($1,$2,$3,$4,$5,$6::date,$7::date,$8,$9,$10,$11)`,[id,p.organizationId,studentId,v.vaccineName,v.doseNumber??null,v.administeredOn,v.nextDueOn??null,v.provider??null,v.batchNumber??null,v.notes??null,p.userId]);return c.json({data:{id,studentId,...v}},201);});
 r.get("/visits/:visitId/referrals",async c=>{const p=c.get("principal"),visitId=c.req.param("visitId");await requireVisit(runtime,p.organizationId,visitId);const q=await runtime.db.query(`SELECT r.*,u.display_name AS created_by_name FROM school_clinic_referrals r LEFT JOIN users u ON u.id=r.created_by WHERE r.organization_id=$1 AND r.visit_id=$2 ORDER BY r.referred_at DESC`,[p.organizationId,visitId]);return c.json({data:q.rows.map(camel)});});
 r.post("/visits/:visitId/referrals",requireScope("school:write"),async c=>{const parsed=referral.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid referral",parsed.error.flatten());const p=c.get("principal"),visitId=c.req.param("visitId"),v=parsed.data;await requireVisit(runtime,p.organizationId,visitId);const id=createId("ref");await runtime.db.query(`INSERT INTO school_clinic_referrals(id,organization_id,visit_id,facility_name,reason,referred_at,follow_up_on,created_by) VALUES($1,$2,$3,$4,$5,COALESCE($6::timestamptz,CURRENT_TIMESTAMP),$7::date,$8)`,[id,p.organizationId,visitId,v.facilityName,v.reason,v.referredAt??null,v.followUpOn??null,p.userId]);return c.json({data:{id,visitId,status:"referred",...v}},201);});
 r.patch("/referrals/:id",requireScope("school:write"),async c=>{const parsed=referralUpdate.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid referral changes",parsed.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=parsed.data,q=await runtime.db.query(`UPDATE school_clinic_referrals SET status=COALESCE($1,status),outcome=CASE WHEN $2::boolean THEN $3 ELSE outcome END,follow_up_on=CASE WHEN $4::boolean THEN $5::date ELSE follow_up_on END,updated_at=CURRENT_TIMESTAMP WHERE id=$6 AND organization_id=$7 RETURNING *`,[v.status??null,Object.hasOwn(v,"outcome"),v.outcome??null,Object.hasOwn(v,"followUpOn"),v.followUpOn??null,id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"REFERRAL_NOT_FOUND","Referral not found");return c.json({data:camel(q.rows[0] as Record<string,unknown>)});});
 r.get("/students/:studentId/history",async c=>{const p=c.get("principal"),studentId=c.req.param("studentId");await requireStudent(runtime,p.organizationId,studentId);const [visits,immunizations]=await Promise.all([runtime.db.query(`SELECT v.*,COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id',m.id,'medicationName',m.medication_name,'dose',m.dose,'administeredAt',m.administered_at)) FILTER(WHERE m.id IS NOT NULL),'[]'::jsonb) medications,COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id',r.id,'facilityName',r.facility_name,'status',r.status,'referredAt',r.referred_at)) FILTER(WHERE r.id IS NOT NULL),'[]'::jsonb) referrals FROM school_clinic_visits v LEFT JOIN school_clinic_medications m ON m.organization_id=v.organization_id AND m.visit_id=v.id LEFT JOIN school_clinic_referrals r ON r.organization_id=v.organization_id AND r.visit_id=v.id WHERE v.organization_id=$1 AND v.student_id=$2 GROUP BY v.id ORDER BY v.visited_at DESC`,[p.organizationId,studentId]),runtime.db.query(`SELECT * FROM school_student_immunizations WHERE organization_id=$1 AND student_id=$2 ORDER BY administered_on DESC`,[p.organizationId,studentId])]);return c.json({data:{visits:visits.rows.map(camel),immunizations:immunizations.rows.map(camel)}});});
 return r;}
