import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";
function camel(r:Record<string,unknown>){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(r))o[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return o;}
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const award=z.object({studentId:z.string(),academicYearId:z.string().nullable().optional(),termId:z.string().nullable().optional(),feeCategoryId:z.string().nullable().optional(),awardType:z.enum(['discount','scholarship','bursary','waiver','sibling_discount','other']),calculationType:z.enum(['fixed','percentage']),amountMinor:z.number().int().nonnegative().nullable().optional(),rateMicros:z.number().int().min(0).max(100000000).nullable().optional(),reason:z.string().max(1000).nullable().optional(),startsOn:date.nullable().optional(),endsOn:date.nullable().optional()});
const plan=z.object({studentId:z.string(),documentId:z.string(),name:z.string().min(2).max(180),installments:z.array(z.object({dueDate:date,amountMinor:z.number().int().positive()})).min(1).max(24)});
async function owned(runtime:Runtime,org:string,table:string,id?:string|null){if(!id)return;const q=await runtime.db.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(422,'INVALID_REFERENCE',`Referenced ${table} record does not belong to this school`);}

export function createSchoolFeeParityRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('school:read'));
 r.get('/awards',async c=>{const p=c.get('principal'),studentId=c.req.query('studentId'),params:any[]=[p.organizationId],where=['a.organization_id=$1'];if(studentId){params.push(studentId);where.push(`a.student_id=$${params.length}`)}const q=await runtime.db.query(`SELECT a.*,s.admission_number,concat_ws(' ',s.first_name,s.last_name) student_name,fc.name fee_category_name FROM school_fee_awards a JOIN school_students s ON s.id=a.student_id LEFT JOIN school_fee_categories fc ON fc.id=a.fee_category_id WHERE ${where.join(' AND ')} ORDER BY a.active DESC,a.created_at DESC`,params);return c.json({data:q.rows.map(camel)});});
 r.post('/awards',requireScope('school:write'),async c=>{const parsed=award.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,'VALIDATION_ERROR','Invalid fee award',parsed.error.flatten());const p=c.get('principal'),v=parsed.data;if(v.calculationType==='fixed'&&v.amountMinor==null)throw new AppError(422,'AMOUNT_REQUIRED','Fixed awards require amountMinor');if(v.calculationType==='percentage'&&v.rateMicros==null)throw new AppError(422,'RATE_REQUIRED','Percentage awards require rateMicros');await owned(runtime,p.organizationId,'school_students',v.studentId);await owned(runtime,p.organizationId,'school_academic_years',v.academicYearId);await owned(runtime,p.organizationId,'school_terms',v.termId);await owned(runtime,p.organizationId,'school_fee_categories',v.feeCategoryId);if(v.termId&&v.academicYearId){const t=await runtime.db.query(`SELECT 1 FROM school_terms WHERE id=$1 AND organization_id=$2 AND academic_year_id=$3`,[v.termId,p.organizationId,v.academicYearId]);if(!t.rowCount)throw new AppError(422,'INVALID_TERM','Term does not belong to academic year');}const id=createId('faw');await runtime.db.query(`INSERT INTO school_fee_awards(id,organization_id,student_id,academic_year_id,term_id,fee_category_id,award_type,calculation_type,amount_minor,rate_micros,reason,starts_on,ends_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[id,p.organizationId,v.studentId,v.academicYearId??null,v.termId??null,v.feeCategoryId??null,v.awardType,v.calculationType,v.amountMinor??null,v.rateMicros??null,v.reason??null,v.startsOn??null,v.endsOn??null,p.userId]);return c.json({data:{id,...v,active:true}},201);});
 r.post('/awards/:id/deactivate',requireScope('school:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE school_fee_awards SET active=false,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND active=true RETURNING *`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'AWARD_NOT_FOUND','Active fee award not found');return c.json({data:camel(q.rows[0])});});

 r.get('/installment-plans',async c=>{const p=c.get('principal'),studentId=c.req.query('studentId'),params:any[]=[p.organizationId],where=['pl.organization_id=$1'];if(studentId){params.push(studentId);where.push(`pl.student_id=$${params.length}`)}const q=await runtime.db.query(`SELECT pl.*,s.admission_number,concat_ws(' ',s.first_name,s.last_name) student_name,d.number document_number,(SELECT COALESCE(SUM(i.paid_minor),0)::float8 FROM school_fee_installments i WHERE i.plan_id=pl.id) paid_minor FROM school_fee_installment_plans pl JOIN school_students s ON s.id=pl.student_id JOIN documents d ON d.id=pl.document_id WHERE ${where.join(' AND ')} ORDER BY pl.created_at DESC`,params);return c.json({data:q.rows.map(camel)});});
 r.post('/installment-plans',requireScope('school:write'),async c=>{const parsed=plan.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,'VALIDATION_ERROR','Invalid installment plan',parsed.error.flatten());const p=c.get('principal'),v=parsed.data,doc=(await runtime.db.query(`SELECT d.id,d.total_minor,d.paid_minor FROM documents d JOIN school_student_fee_charges ch ON ch.document_id=d.id AND ch.organization_id=d.organization_id WHERE d.id=$1 AND d.organization_id=$2 AND ch.student_id=$3 LIMIT 1`,[v.documentId,p.organizationId,v.studentId])).rows[0] as any;if(!doc)throw new AppError(404,'FEE_INVOICE_NOT_FOUND','Student fee invoice not found');const outstanding=Math.max(0,Number(doc.total_minor)-Number(doc.paid_minor)),scheduled=v.installments.reduce((n,x)=>n+x.amountMinor,0);if(scheduled!==outstanding)throw new AppError(422,'INSTALLMENT_TOTAL_MISMATCH','Installment amounts must equal the current invoice balance',{outstandingMinor:outstanding,scheduledMinor:scheduled});const client=await runtime.db.connect();try{await client.query('BEGIN');const id=createId('fpl');await client.query(`INSERT INTO school_fee_installment_plans(id,organization_id,student_id,document_id,name,total_minor,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,v.studentId,v.documentId,v.name,outstanding,p.userId]);for(let i=0;i<v.installments.length;i++){const x=v.installments[i]!;await client.query(`INSERT INTO school_fee_installments(id,organization_id,plan_id,sequence,due_date,amount_minor) VALUES($1,$2,$3,$4,$5,$6)`,[createId('fin'),p.organizationId,id,i+1,x.dueDate,x.amountMinor]);}await client.query('COMMIT');return c.json({data:{id,status:'active',studentId:v.studentId,documentId:v.documentId,totalMinor:outstanding,installments:v.installments}},201);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
 r.get('/installment-plans/:id',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT * FROM school_fee_installment_plans WHERE id=$1 AND organization_id=$2`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'PLAN_NOT_FOUND','Installment plan not found');const items=await runtime.db.query(`SELECT *,(amount_minor-paid_minor)::float8 balance_minor FROM school_fee_installments WHERE organization_id=$1 AND plan_id=$2 ORDER BY sequence`,[p.organizationId,c.req.param('id')]);return c.json({data:{...camel(q.rows[0]),installments:items.rows.map(camel)}});});
 r.post('/installment-plans/:id/cancel',requireScope('school:write'),async c=>{const p=c.get('principal'),id=c.req.param('id'),client=await runtime.db.connect();try{await client.query('BEGIN');const q=await client.query(`UPDATE school_fee_installment_plans SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status='active' RETURNING id`,[id,p.organizationId]);if(!q.rowCount)throw new AppError(409,'PLAN_NOT_ACTIVE','Only active installment plans can be cancelled');await client.query(`UPDATE school_fee_installments SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND plan_id=$2 AND status<>'paid'`,[p.organizationId,id]);await client.query('COMMIT');return c.json({data:{id,status:'cancelled'}});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
 return r;}
