import { Hono } from "hono";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { requireScope } from "../core-identity/security.js";

function camel(row:Record<string,unknown>){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(row))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return out;}
function csvCell(v:unknown){const s=v==null?"":String(v);return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
function csv(headers:string[],rows:unknown[][]){return [headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\n')+'\n';}
function csvResponse(c:any,name:string,body:string){c.header('content-type','text/csv; charset=utf-8');c.header('content-disposition',`attachment; filename="${name}"`);return c.body(body);}
function statementSummary(rows:any[]){return rows.reduce((a:any,x:any)=>{const debit=Number(x.debit_minor??x.debitMinor??0),credit=Number(x.credit_minor??x.creditMinor??0),kind=String(x.kind??'');a.billedMinor+=debit;a.balanceMinor+=debit-credit;if(kind==='payment')a.paidMinor+=credit;else if(kind==='writeoff')a.writtenOffMinor+=credit;else a.creditedMinor+=credit;return a;},{billedMinor:0,paidMinor:0,creditedMinor:0,writtenOffMinor:0,balanceMinor:0});}

export function createSchoolFeeExportRoutes(runtime:Runtime){
 const r=new Hono<AppEnv>();r.use('*',requireScope('school:read'));

 r.get('/students/:studentId/statement',async c=>{
  const p=c.get('principal'),studentId=c.req.param('studentId');
  const student=(await runtime.db.query<any>(`SELECT id,admission_number,student_number,first_name,middle_name,last_name,concat_ws(' ',first_name,middle_name,last_name) name FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[studentId,p.organizationId])).rows[0];
  if(!student)throw new AppError(404,'STUDENT_NOT_FOUND','Student not found');
  const ledger=await runtime.db.query<any>(`SELECT j.id,j.transaction_date date,COALESCE(j.reference,j.entry_number) reference,j.entry_number,j.description,j.source_type,j.status,SUM(l.debit_minor)::float8 debit_minor,SUM(l.credit_minor)::float8 credit_minor,CASE WHEN j.source_type='school_fee_writeoff' THEN 'writeoff' WHEN j.source_type IN ('receipt','schoolpay_payment') THEN 'payment' WHEN j.source_type IN ('schoolpay_credit','schoolpay_bursary') THEN 'credit' ELSE 'charge' END kind FROM journal_entries j JOIN journal_lines l ON l.journal_entry_id=j.id AND l.organization_id=j.organization_id JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE j.organization_id=$1 AND l.dimensions_json->>'schoolStudentId'=$2 AND (a.subtype='school_fee_receivable' OR (a.subtype='receivable' AND l.dimensions_json ? 'schoolStudentId')) AND j.status='posted' GROUP BY j.id ORDER BY j.transaction_date,j.created_at,j.entry_number`,[p.organizationId,studentId]);
  const summary=statementSummary(ledger.rows);
  return c.json({data:{student:camel(student),period:{academicYearId:null,academicYearName:null,termId:null,termName:null},openingBalanceMinor:0,charges:[],receipts:[],reductions:[],ledgerEntries:ledger.rows.map(camel),summary}});
 });

 r.get('/payers/:contactId/statement',async c=>{
  const p=c.get('principal'),contactId=c.req.param('contactId'),payer=(await runtime.db.query<any>(`SELECT id,name,email FROM contacts WHERE id=$1 AND organization_id=$2 AND type='customer' AND archived_at IS NULL`,[contactId,p.organizationId])).rows[0];
  if(!payer)throw new AppError(404,'PAYER_NOT_FOUND','Fee payer not found');
  const ledger=await runtime.db.query<any>(`SELECT j.id,j.transaction_date date,COALESCE(j.reference,j.entry_number) reference,j.entry_number,j.description,j.source_type,j.status,SUM(l.debit_minor)::float8 debit_minor,SUM(l.credit_minor)::float8 credit_minor,CASE WHEN j.source_type='school_fee_writeoff' THEN 'writeoff' WHEN j.source_type IN ('receipt','schoolpay_payment') OR j.source_type ILIKE '%payment%' THEN 'payment' WHEN j.source_type IN ('schoolpay_credit','schoolpay_bursary') THEN 'credit' ELSE 'charge' END kind FROM journal_entries j JOIN journal_lines l ON l.journal_entry_id=j.id AND l.organization_id=j.organization_id JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE j.organization_id=$1 AND l.contact_id=$2 AND (a.subtype='school_fee_receivable' OR (a.subtype='receivable' AND l.dimensions_json ? 'schoolStudentId')) AND j.status='posted' GROUP BY j.id ORDER BY j.transaction_date,j.created_at,j.entry_number`,[p.organizationId,contactId]);
  return c.json({data:{payer:camel(payer),period:{academicYearId:null,academicYearName:null,termId:null,termName:null},openingBalanceMinor:0,charges:[],receipts:[],reductions:[],ledgerEntries:ledger.rows.map(camel),summary:statementSummary(ledger.rows)}});
 });

 r.get('/guardians/:guardianId/statement',async c=>{
  const p=c.get('principal'),guardianId=c.req.param('guardianId'),guardian=(await runtime.db.query<any>(`SELECT g.*,ct.name contact_name FROM school_guardians g LEFT JOIN contacts ct ON ct.id=g.contact_id AND ct.organization_id=g.organization_id WHERE g.id=$1 AND g.organization_id=$2`,[guardianId,p.organizationId])).rows[0];
  if(!guardian)throw new AppError(404,'GUARDIAN_NOT_FOUND','Guardian not found');
  const students=await runtime.db.query<any>(`SELECT s.id student_id,s.admission_number,s.student_number,concat_ws(' ',s.first_name,s.middle_name,s.last_name) name,sg.relationship,sg.financial_responsibility FROM school_student_guardians sg JOIN school_students s ON s.id=sg.student_id AND s.organization_id=sg.organization_id WHERE sg.organization_id=$1 AND sg.guardian_id=$2 AND sg.deleted_at IS NULL AND s.deleted_at IS NULL ORDER BY s.last_name,s.first_name`,[p.organizationId,guardianId]);
  const rows=[];for(const student of students.rows){const q=await runtime.db.query<any>(`SELECT COALESCE(SUM(l.debit_minor),0)::float8 billed_minor,COALESCE(SUM(CASE WHEN j.source_type IN ('receipt','schoolpay_payment') OR j.source_type ILIKE '%payment%' THEN l.credit_minor ELSE 0 END),0)::float8 paid_minor,COALESCE(SUM(CASE WHEN j.source_type IN ('schoolpay_credit','schoolpay_bursary') THEN l.credit_minor ELSE 0 END),0)::float8 credited_minor,COALESCE(SUM(CASE WHEN j.source_type='school_fee_writeoff' THEN l.credit_minor ELSE 0 END),0)::float8 written_off_minor,COALESCE(SUM(l.debit_minor-l.credit_minor),0)::float8 balance_minor FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.organization_id=l.organization_id JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.dimensions_json->>'schoolStudentId'=$2 AND (a.subtype='school_fee_receivable' OR (a.subtype='receivable' AND l.dimensions_json ? 'schoolStudentId')) AND j.status='posted'`,[p.organizationId,student.student_id]);rows.push({...camel(student),balance:camel(q.rows[0]??{})});}
  const credit=guardian.contact_id?await runtime.db.query<any>(`SELECT COALESCE(SUM(l.credit_minor-l.debit_minor),0)::float8 amount FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.organization_id=l.organization_id JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.contact_id=$2 AND (a.subtype='school_fee_receivable' OR (a.subtype='receivable' AND l.dimensions_json ? 'schoolStudentId')) AND j.status='posted'`,[p.organizationId,guardian.contact_id]):null;
  return c.json({data:{guardian:camel(guardian),students:rows,unallocatedCreditMinor:Math.max(0,Number(credit?.rows[0]?.amount??0))}});
 });

 r.get('/students/:studentId/statement.csv',async c=>{
  const p=c.get('principal'),studentId=c.req.param('studentId'),student=(await runtime.db.query<any>(`SELECT admission_number,student_number,concat_ws(' ',first_name,middle_name,last_name) student_name FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[studentId,p.organizationId])).rows[0];
  if(!student)throw new AppError(404,'STUDENT_NOT_FOUND','Student not found');
  const q=await runtime.db.query<any>(`SELECT j.transaction_date event_date,j.source_type event_type,COALESCE(j.reference,j.entry_number) reference,j.description,SUM(l.debit_minor)::bigint debit_minor,SUM(l.credit_minor)::bigint credit_minor FROM journal_entries j JOIN journal_lines l ON l.journal_entry_id=j.id AND l.organization_id=j.organization_id JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE j.organization_id=$1 AND l.dimensions_json->>'schoolStudentId'=$2 AND (a.subtype='school_fee_receivable' OR (a.subtype='receivable' AND l.dimensions_json ? 'schoolStudentId')) AND j.status='posted' GROUP BY j.id ORDER BY j.transaction_date,j.created_at,j.entry_number`,[p.organizationId,studentId]);
  let balance=0;const rows=q.rows.map((x:any)=>{balance+=Number(x.debit_minor||0)-Number(x.credit_minor||0);return[x.event_date,x.event_type,x.reference,Number(x.debit_minor||0),Number(x.credit_minor||0),balance];});
  return csvResponse(c,`fee-statement-${student.admission_number??student.student_number??studentId}.csv`,csv(['Date','Type','Reference','Debit Minor','Credit Minor','Balance Minor'],rows));
 });

 r.get('/reports/balances.csv',async c=>{
  const p=c.get('principal'),q=await runtime.db.query<any>(`WITH ledger AS (SELECT l.dimensions_json->>'schoolStudentId' student_id,SUM(l.debit_minor)::bigint billed_minor,SUM(CASE WHEN j.source_type IN ('receipt','schoolpay_payment') THEN l.credit_minor ELSE 0 END)::bigint paid_minor,SUM(CASE WHEN j.source_type IN ('schoolpay_credit','schoolpay_bursary') THEN l.credit_minor ELSE 0 END)::bigint credited_minor,SUM(CASE WHEN j.source_type='school_fee_writeoff' THEN l.credit_minor ELSE 0 END)::bigint written_off_minor,SUM(l.debit_minor-l.credit_minor)::bigint balance_minor FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.organization_id=l.organization_id JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id WHERE l.organization_id=$1 AND (a.subtype='school_fee_receivable' OR (a.subtype='receivable' AND l.dimensions_json ? 'schoolStudentId')) AND j.status='posted' GROUP BY l.dimensions_json->>'schoolStudentId') SELECT s.admission_number,s.student_number,concat_ws(' ',s.first_name,s.middle_name,s.last_name) student_name,s.status,COALESCE(x.billed_minor,0)::bigint billed_minor,COALESCE(x.paid_minor,0)::bigint paid_minor,COALESCE(x.credited_minor,0)::bigint credited_minor,COALESCE(x.written_off_minor,0)::bigint written_off_minor,COALESCE(x.balance_minor,0)::bigint balance_minor FROM school_students s LEFT JOIN ledger x ON x.student_id=s.id WHERE s.organization_id=$1 AND s.deleted_at IS NULL ORDER BY s.last_name,s.first_name`,[p.organizationId]);
  return csvResponse(c,'school-fee-balances.csv',csv(['Admission Number','Student Number','Student Name','Status','Billed Minor','Paid Minor','Credits Minor','Written Off Minor','Balance Minor'],q.rows.map((x:any)=>[x.admission_number,x.student_number,x.student_name,x.status,x.billed_minor,x.paid_minor,x.credited_minor,x.written_off_minor,x.balance_minor])));
 });

 r.get('/receipts.csv',async c=>{
  const p=c.get('principal'),from=c.req.query('from')??null,to=c.req.query('to')??null,q=await runtime.db.query<any>(`SELECT r.receipt_number,r.payment_date,r.amount_minor,r.reference,s.admission_number,s.student_number,concat_ws(' ',s.first_name,s.middle_name,s.last_name) student_name,p.status payment_status,p.currency FROM school_fee_receipts r JOIN school_students s ON s.id=r.student_id JOIN payments p ON p.id=r.payment_id AND p.organization_id=r.organization_id WHERE r.organization_id=$1 AND ($2::date IS NULL OR r.payment_date>=$2::date) AND ($3::date IS NULL OR r.payment_date<=$3::date) ORDER BY r.payment_date DESC,r.created_at DESC`,[p.organizationId,from,to]);
  return csvResponse(c,'school-fee-receipts.csv',csv(['Receipt Number','Date','Admission Number','Student Number','Student Name','Amount Minor','Currency','Reference','Payment Status'],q.rows.map((x:any)=>[x.receipt_number,x.payment_date,x.admission_number,x.student_number,x.student_name,x.amount_minor,x.currency,x.reference,x.payment_status])));
 });

 r.get('/reports/collections.csv',async c=>{
  const p=c.get('principal'),from=c.req.query('from')??null,to=c.req.query('to')??null,q=await runtime.db.query<any>(`SELECT r.payment_date,COUNT(*)::int receipts,COALESCE(SUM(r.amount_minor),0)::bigint amount_minor FROM school_fee_receipts r JOIN payments p ON p.id=r.payment_id AND p.organization_id=r.organization_id WHERE r.organization_id=$1 AND p.status='posted' AND ($2::date IS NULL OR r.payment_date>=$2::date) AND ($3::date IS NULL OR r.payment_date<=$3::date) GROUP BY r.payment_date ORDER BY r.payment_date DESC`,[p.organizationId,from,to]);
  return csvResponse(c,'school-fee-collections.csv',csv(['Date','Receipts','Amount Minor'],q.rows.map((x:any)=>[x.payment_date,x.receipts,x.amount_minor])));
 });
 return r;
}
