import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";
import { createDocument, postDocument } from "../documents/service.js";
import { createPayment, postPayment } from "../payments/service.js";

const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const category=z.object({code:z.string().min(1).max(60),name:z.string().min(2).max(180),description:z.string().max(1000).nullable().optional(),incomeAccountId:z.string(),active:z.boolean().default(true)});
const structure=z.object({code:z.string().min(1).max(60),name:z.string().min(2).max(180),academicYearId:z.string(),termId:z.string().nullable().optional(),classLevelId:z.string().nullable().optional(),classId:z.string().nullable().optional(),streamId:z.string().nullable().optional(),residencyStatus:z.enum(["day","boarding","hybrid"]).nullable().optional(),studentCategory:z.string().max(100).nullable().optional(),currency:z.string().length(3).transform(v=>v.toUpperCase()).default("UGX"),priority:z.number().int().min(0).max(10000).default(100),status:z.enum(["draft","active","archived"]).default("draft"),notes:z.string().max(2000).nullable().optional()});
const line=z.object({feeCategoryId:z.string(),amountMinor:z.number().int().nonnegative(),dueDate:date.nullable().optional(),mandatory:z.boolean().default(true),description:z.string().max(1000).nullable().optional()});
const bill=z.object({studentId:z.string(),structureId:z.string(),issueDate:date,dueDate:date.nullable().optional(),controlAccountId:z.string().optional()});
const receipt=z.object({studentId:z.string(),bankAccountId:z.string(),controlAccountId:z.string(),paymentDate:date,amountMinor:z.number().int().positive(),reference:z.string().max(120).nullable().optional(),allocations:z.array(z.object({documentId:z.string(),amountMinor:z.number().int().positive()})).max(100).default([])});
function camel(row:Record<string,unknown>){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(row))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return out;}
async function owned(runtime:Runtime,org:string,table:string,id?:string|null){if(!id)return;const q=await runtime.db.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2`,[id,org]);if(!q.rowCount)throw new AppError(422,"INVALID_REFERENCE",`Referenced ${table} record does not belong to this school`);}
async function audit(runtime:Runtime,org:string,user:string,action:string,type:string,id:string,after?:unknown){await runtime.db.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,after_data) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[createId("aud"),org,user,action,type,id,after===undefined?null:JSON.stringify(after)]);}

export function createSchoolFeeRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/categories",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT fc.*,a.code AS income_account_code,a.name AS income_account_name FROM school_fee_categories fc JOIN accounts a ON a.id=fc.income_account_id WHERE fc.organization_id=$1 ORDER BY fc.active DESC,fc.name`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/categories",requireScope("school:write"),async c=>{const s=category.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid fee category",s.error.flatten());const p=c.get("principal"),v=s.data;const acc=(await runtime.db.query(`SELECT id FROM accounts WHERE id=$1 AND organization_id=$2 AND type='revenue' AND active=true AND allow_posting=true`,[v.incomeAccountId,p.organizationId])).rows[0];if(!acc)throw new AppError(422,"INVALID_ACCOUNT","Fee income account must be an active revenue posting account");const id=createId("fct");await runtime.db.query(`INSERT INTO school_fee_categories(id,organization_id,code,name,description,income_account_id,active) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,v.code.trim().toUpperCase(),v.name,v.description??null,v.incomeAccountId,v.active]);await audit(runtime,p.organizationId,p.userId,"school.fees.category.created","school_fee_category",id,v);return c.json({data:{id,...v}},201);});
 r.get("/structures",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT s.*,(SELECT COUNT(*)::int FROM school_fee_structure_lines l WHERE l.organization_id=s.organization_id AND l.structure_id=s.id) AS line_count,(SELECT COALESCE(SUM(amount_minor),0)::float8 FROM school_fee_structure_lines l WHERE l.organization_id=s.organization_id AND l.structure_id=s.id) AS nominal_total_minor FROM school_fee_structures s WHERE s.organization_id=$1 ORDER BY s.status='active' DESC,s.priority,s.name`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.get("/structures/:id",async c=>{const p=c.get("principal"),id=c.req.param("id"),row=(await runtime.db.query(`SELECT * FROM school_fee_structures WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!row)throw new AppError(404,"FEE_STRUCTURE_NOT_FOUND","Fee structure not found");const lines=await runtime.db.query(`SELECT l.*,fc.code AS fee_category_code,fc.name AS fee_category_name FROM school_fee_structure_lines l JOIN school_fee_categories fc ON fc.id=l.fee_category_id WHERE l.organization_id=$1 AND l.structure_id=$2 ORDER BY fc.name`,[p.organizationId,id]);return c.json({data:{...camel(row),lines:lines.rows.map(camel)}});});
 r.post("/structures",requireScope("school:write"),async c=>{const s=structure.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid fee structure",s.error.flatten());const p=c.get("principal"),v=s.data;await owned(runtime,p.organizationId,"school_academic_years",v.academicYearId);await owned(runtime,p.organizationId,"school_terms",v.termId);await owned(runtime,p.organizationId,"school_class_levels",v.classLevelId);await owned(runtime,p.organizationId,"school_classes",v.classId);await owned(runtime,p.organizationId,"school_streams",v.streamId);const id=createId("ffs");await runtime.db.query(`INSERT INTO school_fee_structures(id,organization_id,code,name,academic_year_id,term_id,class_level_id,class_id,stream_id,residency_status,student_category,currency,priority,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[id,p.organizationId,v.code,v.name,v.academicYearId,v.termId??null,v.classLevelId??null,v.classId??null,v.streamId??null,v.residencyStatus??null,v.studentCategory??null,v.currency,v.priority,v.status,v.notes??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.post("/structures/:id/lines",requireScope("school:write"),async c=>{const s=line.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid fee structure line",s.error.flatten());const p=c.get("principal"),structureId=c.req.param("id"),v=s.data;await owned(runtime,p.organizationId,"school_fee_structures",structureId);await owned(runtime,p.organizationId,"school_fee_categories",v.feeCategoryId);const id=createId("ffl");await runtime.db.query(`INSERT INTO school_fee_structure_lines(id,organization_id,structure_id,fee_category_id,amount_minor,due_date,mandatory,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,p.organizationId,structureId,v.feeCategoryId,v.amountMinor,v.dueDate??null,v.mandatory,v.description??null]);return c.json({data:{id,structureId,...v}},201);});
 r.post("/billing",requireScope("school:write"),async c=>{const s=bill.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid student billing request",s.error.flatten());const p=c.get("principal"),v=s.data;const student=(await runtime.db.query(`SELECT id,contact_id,current_class_id,current_stream_id,residency_status,student_category FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[v.studentId,p.organizationId])).rows[0];if(!student?.contact_id)throw new AppError(422,"STUDENT_CONTACT_REQUIRED","Student must have a finance contact before billing");const structureRow=(await runtime.db.query(`SELECT * FROM school_fee_structures WHERE id=$1 AND organization_id=$2 AND status='active'`,[v.structureId,p.organizationId])).rows[0];if(!structureRow)throw new AppError(404,"FEE_STRUCTURE_NOT_FOUND","Active fee structure not found");const lines=await runtime.db.query(`SELECT l.*,fc.name AS category_name,fc.income_account_id FROM school_fee_structure_lines l JOIN school_fee_categories fc ON fc.id=l.fee_category_id AND fc.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.structure_id=$2 AND fc.active=true ORDER BY fc.name`,[p.organizationId,v.structureId]);if(!lines.rowCount)throw new AppError(409,"EMPTY_FEE_STRUCTURE","Fee structure has no active fee lines");const number=`FEE-${v.issueDate.replaceAll("-","")}-${createId("n").slice(-6).toUpperCase()}`;const doc=await createDocument(runtime,p.organizationId,p.userId,{type:"invoice",number,contactId:String(student.contact_id),issueDate:v.issueDate,dueDate:v.dueDate??v.issueDate,currency:String(structureRow.currency),customFields:{schoolStudentId:v.studentId,schoolFeeStructureId:v.structureId},lines:lines.rows.map((x:any)=>({accountId:String(x.income_account_id),description:String(x.description??x.category_name),quantityMicros:1_000_000,unitPriceMinor:Number(x.amount_minor),taxMinor:0,classId:student.current_class_id??undefined,dimensions:{schoolStudentId:v.studentId,schoolFeeCategoryId:String(x.fee_category_id)}}))});await postDocument(runtime,p.organizationId,p.userId,doc.id,v.controlAccountId);for(const x of lines.rows)await runtime.db.query(`INSERT INTO school_student_fee_charges(id,organization_id,student_id,structure_id,structure_line_id,document_id,fee_category_id,amount_minor,due_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[createId("chg"),p.organizationId,v.studentId,v.structureId,x.id,doc.id,x.fee_category_id,x.amount_minor,x.due_date??v.dueDate??v.issueDate,p.userId]);await audit(runtime,p.organizationId,p.userId,"school.fees.student_billed","school_student",v.studentId,{documentId:doc.id,structureId:v.structureId,totalMinor:doc.totalMinor});return c.json({data:{studentId:v.studentId,documentId:doc.id,number,totalMinor:doc.totalMinor,status:"open"}},201);});
 r.get("/students/:studentId/balance",async c=>{const p=c.get("principal"),studentId=c.req.param("studentId"),docs=await runtime.db.query(`SELECT DISTINCT d.id,d.number,d.issue_date,d.due_date,d.currency,d.total_minor::float8 AS total_minor,d.paid_minor::float8 AS paid_minor,d.status FROM school_student_fee_charges ch JOIN documents d ON d.id=ch.document_id AND d.organization_id=ch.organization_id WHERE ch.organization_id=$1 AND ch.student_id=$2 ORDER BY d.issue_date,d.number`,[p.organizationId,studentId]);const invoices=docs.rows.map(camel),total=invoices.reduce((n:any,x:any)=>n+Number(x.totalMinor||0),0),paid=invoices.reduce((n:any,x:any)=>n+Number(x.paidMinor||0),0);return c.json({data:{studentId,totalBilledMinor:total,totalPaidMinor:paid,balanceMinor:total-paid,invoices}});});
 r.post("/receipts",requireScope("school:write"),async c=>{const s=receipt.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid school fee receipt",s.error.flatten());const p=c.get("principal"),v=s.data,student=(await runtime.db.query(`SELECT contact_id FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[v.studentId,p.organizationId])).rows[0];if(!student?.contact_id)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found or missing finance contact");const number=`RCPT-${v.paymentDate.replaceAll("-","")}-${createId("n").slice(-6).toUpperCase()}`,payment=await createPayment(runtime,p.organizationId,p.userId,{type:"receipt",number,contactId:String(student.contact_id),bankAccountId:v.bankAccountId,controlAccountId:v.controlAccountId,paymentDate:v.paymentDate,currency:"UGX",amountMinor:v.amountMinor,reference:v.reference??number},`school-fee:${p.organizationId}:${number}`);await postPayment(runtime,p.organizationId,p.userId,payment.id,v.allocations);const id=createId("sfr");await runtime.db.query(`INSERT INTO school_fee_receipts(id,organization_id,student_id,payment_id,receipt_number,amount_minor,payment_date,reference,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.studentId,payment.id,number,v.amountMinor,v.paymentDate,v.reference??null,p.userId]);return c.json({data:{id,receiptNumber:number,paymentId:payment.id,amountMinor:v.amountMinor}},201);});
 r.get("/receipts",async c=>{const p=c.get("principal"),studentId=c.req.query("studentId"),params:any[]=[p.organizationId],where=["r.organization_id=$1"];if(studentId){params.push(studentId);where.push(`r.student_id=$${params.length}`)}const q=await runtime.db.query(`SELECT r.*,s.admission_number,s.first_name,s.last_name,p.status AS payment_status FROM school_fee_receipts r JOIN school_students s ON s.id=r.student_id JOIN payments p ON p.id=r.payment_id WHERE ${where.join(" AND ")} ORDER BY r.payment_date DESC,r.created_at DESC LIMIT 500`,params);return c.json({data:q.rows.map(camel)});});
 r.get("/summary",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT COALESCE(SUM(d.total_minor),0)::float8 billed_minor,COALESCE(SUM(d.paid_minor),0)::float8 paid_minor,COALESCE(SUM(d.total_minor-d.paid_minor),0)::float8 outstanding_minor,COUNT(*) FILTER(WHERE d.status IN ('open','partially_paid'))::int open_invoices FROM documents d WHERE d.organization_id=$1 AND d.type='invoice' AND (d.custom_fields ? 'schoolStudentId')`,[p.organizationId]);return c.json({data:camel(q.rows[0]??{})});});
 return r;}
