import { Hono } from "hono";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const academicAdmin=["school.academics:read","school.academics:write","school.academics:approve","school.academics:supervise"];
const roles=[
 ["super_admin","Super Administrator","administration"],["school_admin","School Administrator","administration"],["head_teacher","Head Teacher / Principal","leadership"],["deputy_head","Deputy Head Teacher","leadership"],["director","Director","leadership"],["director_of_studies","Director of Studies (DOS)","academic"],["head_of_department","Head of Department (HOD)","academic"],["teacher","Teacher","academic"],["class_teacher","Class Teacher","academic"],["bursar","Bursar","finance"],["accountant","Accountant","finance"],["cashier","Cashier","finance"],["receptionist","Receptionist","administration"],["registrar","Registrar","administration"],["librarian","Librarian","operations"],["nurse","Nurse","welfare"],["warden","Warden","welfare"],["storekeeper","Storekeeper","operations"],["transport_staff","Transport Staff","operations"],["parent","Parent / Guardian","portal"],["student","Student","portal"]
] as const;
const perms:Record<string,string[]>={
 super_admin:["school.setup:read","school.setup:write","school.users:read","school.users:write","school.students:read","school.students:write","school.students:approve","school.students:export","school.finance:read","school.finance:write","school.fees:read","school.fees:write","school.fees:approve","school.fees:export","school.files:read","school.files:write","school.staff:read","school.staff:write","school.staff:approve","school.staff.payroll:read","school.staff.payroll:write","school.discipline:read","school.discipline:write","school.discipline:manage","school.attendance:read","school.attendance.student:write","school.attendance.staff:write","school.attendance:manage","school.attendance:export","school.exams:read","school.exams:write","school.exams:manage","school.exams:publish","school.communications:read","school.communications:send","school.communications:manage",...academicAdmin],
 school_admin:["school.setup:read","school.setup:write","school.users:read","school.users:write","school.students:read","school.students:write","school.students:approve","school.students:export","school.finance:read","school.fees:read","school.fees:write","school.fees:approve","school.fees:export","school.files:read","school.files:write","school.staff:read","school.staff:write","school.staff:approve","school.staff.payroll:read","school.staff.payroll:write","school.discipline:read","school.discipline:write","school.discipline:manage","school.attendance:read","school.attendance.student:write","school.attendance.staff:write","school.attendance:manage","school.attendance:export","school.exams:read","school.exams:write","school.exams:manage","school.exams:publish","school.communications:read","school.communications:send","school.communications:manage",...academicAdmin],
 head_teacher:["school.setup:read","school.users:read","school.students:read","school.students:write","school.students:approve","school.students:export","school.finance:read","school.fees:read","school.fees:approve","school.fees:export","school.files:read","school.files:write","school.staff:read","school.staff:write","school.staff:approve","school.staff.payroll:read","school.discipline:read","school.discipline:write","school.discipline:manage","school.attendance:read","school.attendance.student:write","school.attendance.staff:write","school.attendance:manage","school.attendance:export","school.exams:read","school.exams:write","school.exams:manage","school.exams:publish","school.communications:read","school.communications:send","school.communications:manage",...academicAdmin],
 director:["school.setup:read","school.users:read","school.students:read","school.students:export","school.files:read","school.files:write","school.finance:read","school.fees:read","school.fees:approve","school.fees:export","school.staff:read","school.staff.payroll:read","school.discipline:read","school.discipline:write","school.discipline:manage","school.attendance:read","school.attendance:manage","school.attendance:export","school.exams:read","school.exams:manage","school.exams:publish","school.communications:read","school.communications:send","school.communications:manage",...academicAdmin],
 deputy_head:["school.setup:read","school.users:read","school.students:read","school.students:write","school.students:approve","school.files:read","school.files:write","school.staff:read","school.staff:write","school.discipline:read","school.discipline:write","school.discipline:manage","school.attendance:read","school.attendance.student:write","school.attendance.staff:write","school.attendance:manage","school.attendance:export","school.exams:read","school.exams:write","school.exams:manage","school.exams:publish","school.communications:read","school.communications:send","school.communications:manage",...academicAdmin],
 director_of_studies:["school.setup:read","school.students:read","school.staff:read","school.files:read","school.files:write","school.attendance:read","school.exams:read","school.communications:read",...academicAdmin],
 head_of_department:["school.setup:read","school.students:read","school.staff:read","school.files:read","school.files:write","school.attendance:read","school.exams:read","school.exams:write","school.communications:read",...academicAdmin],
 teacher:["school.setup:read","school.students:read","school.files:read","school.staff:read","school.discipline:read","school.attendance:read","school.attendance.student:write","school.exams:read","school.exams:write","school.communications:read","school.academics:read","school.academics:write"],
 class_teacher:["school.setup:read","school.students:read","school.students:write","school.files:read","school.files:write","school.staff:read","school.discipline:read","school.discipline:write","school.attendance:read","school.attendance.student:write","school.exams:read","school.exams:write","school.communications:read","school.communications:send","school.academics:read","school.academics:write"],
 bursar:["school.setup:read","school.students:read","school.finance:read","school.finance:write","school.fees:read","school.fees:write","school.fees:approve","school.fees:export","school.files:read","school.staff:read","school.staff.payroll:read","school.staff.payroll:write","school.communications:read","school.communications:send"],
 accountant:["school.setup:read","school.students:read","school.finance:read","school.finance:write","school.fees:read","school.fees:write","school.fees:approve","school.fees:export","school.files:read","school.staff:read","school.staff.payroll:read","school.staff.payroll:write","school.communications:read","school.communications:send"],
 cashier:["school.students:read","school.finance:read","school.finance:write","school.fees:read","school.fees:write","school.staff:read","school.staff.payroll:read"],
 receptionist:["school.students:read","school.students:write","school.files:read","school.files:write","school.staff:read","school.attendance:read","school.attendance.staff:write","school.communications:read"],
 registrar:["school.students:read","school.students:write","school.students:approve","school.students:export","school.files:read","school.files:write","school.staff:read","school.discipline:read","school.attendance:read","school.attendance.student:write","school.attendance:export","school.exams:read","school.communications:read","school.communications:send"],
 librarian:["school.students:read"],nurse:["school.students:read"],warden:["school.students:read","school.files:read","school.files:write","school.discipline:read","school.discipline:write"],storekeeper:["school.students:read"],transport_staff:["school.students:read"],parent:["school.students:read"],student:["school.students:read"]
};
for(const [code,p] of Object.entries(perms)){if(p.includes("school.attendance:read"))p.push("attendance:read");if(p.some(x=>x==="school.attendance.student:write"||x==="school.attendance.staff:write"))p.push("attendance:write");if(p.includes("school.attendance:manage"))p.push("attendance:manage");if(["super_admin","school_admin","head_teacher"].includes(code))p.push("attendance:biometrics");if(["super_admin","school_admin"].includes(code))p.push("attendance:devices");}

export function createSchoolIamParityRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/permission-catalog",c=>c.json({data:{roles:roles.map(([code,name,category])=>({code,name,category,permissions:perms[code]??[]})),permissions:[...new Set(Object.values(perms).flat())].sort()}}));
 r.post("/bootstrap",requireScope("school:write"),async c=>{const p=c.get("principal"),client=await runtime.db.connect();let created=0,permissionsAdded=0;try{await client.query("BEGIN");for(const [code,name,category] of roles){let role=(await client.query<{id:string}>(`SELECT id FROM school_roles WHERE organization_id=$1 AND code=$2 FOR UPDATE`,[p.organizationId,code])).rows[0];if(!role){role={id:createId("srl")};await client.query(`INSERT INTO school_roles(id,organization_id,code,name,role_category,system_role,created_by) VALUES($1,$2,$3,$4,$5,true,$6)`,[role.id,p.organizationId,code,name,category,p.userId]);created++;}else await client.query(`UPDATE school_roles SET name=$1,role_category=$2,system_role=true,active=true,updated_at=CURRENT_TIMESTAMP WHERE id=$3`,[name,category,role.id]);for(const permission of perms[code]??[]){const q=await client.query(`INSERT INTO school_role_permissions(organization_id,role_id,permission,effect) VALUES($1,$2,$3,'allow') ON CONFLICT DO NOTHING RETURNING permission`,[p.organizationId,role.id,permission]);permissionsAdded+=q.rowCount??0;}}await client.query("COMMIT");return c.json({data:{roles:roles.length,created,permissionsAdded}});}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}});
 return r;}
