import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const profileSchema=z.object({schoolCode:z.string().min(1).max(60),registrationNumber:z.string().max(120).nullable().optional(),motto:z.string().max(300).nullable().optional(),schoolType:z.string().max(80).default("day"),ownershipType:z.string().max(80).nullable().optional(),educationLevel:z.string().max(120).nullable().optional(),curriculum:z.string().max(160).nullable().optional(),phoneNumbers:z.array(z.string().max(40)).max(20).default([]),emailAddresses:z.array(z.string().email()).max(20).default([]),website:z.string().max(500).nullable().optional(),physicalAddress:z.string().max(1000).nullable().optional(),postalAddress:z.string().max(500).nullable().optional(),country:z.string().max(100).default("Uganda"),districtRegion:z.string().max(160).nullable().optional(),locationText:z.string().max(500).nullable().optional(),headTeacherName:z.string().max(200).nullable().optional(),headTeacherPhone:z.string().max(40).nullable().optional(),headTeacherEmail:z.string().email().nullable().optional(),language:z.string().max(20).default("en"),timezone:z.string().max(80).default("Africa/Kampala"),dateFormat:z.string().max(40).default("DD/MM/YYYY"),timeFormat:z.enum(["12h","24h"]).default("24h"),defaultCurrency:z.string().length(3).transform(v=>v.toUpperCase()).default("UGX"),multiCampusEnabled:z.boolean().default(false),branding:z.record(z.string(),z.unknown()).default({}),systemPreferences:z.record(z.string(),z.unknown()).default({})});

const schemas={
  branches:z.object({code:z.string().min(1).max(40),name:z.string().min(1).max(180),registrationNumber:z.string().max(120).nullable().optional(),phone:z.string().max(40).nullable().optional(),email:z.string().email().nullable().optional(),physicalAddress:z.string().max(1000).nullable().optional(),postalAddress:z.string().max(500).nullable().optional(),districtRegion:z.string().max(160).nullable().optional(),locationText:z.string().max(500).nullable().optional(),principalName:z.string().max(200).nullable().optional(),isMain:z.boolean().default(false),active:z.boolean().default(true)}),
  academicYears:z.object({code:z.string().min(1).max(40),name:z.string().min(1).max(120),startsOn:date,endsOn:date,status:z.enum(["planned","active","closed","archived"]).default("planned"),isCurrent:z.boolean().default(false)}),
  terms:z.object({academicYearId:z.string(),code:z.string().min(1).max(40),name:z.string().min(1).max(120),sequenceNo:z.number().int().min(1).max(20),startsOn:date,endsOn:date,status:z.enum(["planned","active","closed","archived"]).default("planned"),isCurrent:z.boolean().default(false)}),
  departments:z.object({campusId:z.string().nullable().optional(),code:z.string().min(1).max(40),name:z.string().min(1).max(180),description:z.string().max(1000).nullable().optional(),headUserId:z.string().nullable().optional(),parentId:z.string().nullable().optional(),active:z.boolean().default(true)}),
  classLevels:z.object({code:z.string().min(1).max(40),name:z.string().min(1).max(120),sequenceNo:z.number().int().min(1).max(100),educationLevel:z.string().max(120).nullable().optional(),promotionLevelId:z.string().nullable().optional(),terminal:z.boolean().default(false),active:z.boolean().default(true)}),
  classes:z.object({academicYearId:z.string().nullable().optional(),campusId:z.string().nullable().optional(),classLevelId:z.string(),departmentId:z.string().nullable().optional(),code:z.string().min(1).max(40),name:z.string().min(1).max(180),capacity:z.number().int().positive().nullable().optional(),classTeacherUserId:z.string().nullable().optional(),active:z.boolean().default(true)}),
  streams:z.object({classId:z.string(),campusId:z.string().nullable().optional(),code:z.string().min(1).max(40),name:z.string().min(1).max(120),capacity:z.number().int().positive().nullable().optional(),classTeacherUserId:z.string().nullable().optional(),active:z.boolean().default(true)}),
  subjects:z.object({departmentId:z.string().nullable().optional(),code:z.string().min(1).max(40),name:z.string().min(1).max(180),shortName:z.string().max(60).nullable().optional(),subjectType:z.enum(["compulsory","optional","elective"]).default("compulsory"),curriculumCode:z.string().max(100).nullable().optional(),passMark:z.number().min(0).max(100).nullable().optional(),maxMark:z.number().positive().default(100),active:z.boolean().default(true),metadata:z.record(z.string(),z.unknown()).default({})}),
  classSubjects:z.object({classLevelId:z.string(),subjectId:z.string(),academicYearId:z.string().nullable().optional(),compulsory:z.boolean().default(true),periodsPerWeek:z.number().int().min(0).max(100).nullable().optional(),teacherUserId:z.string().nullable().optional(),active:z.boolean().default(true)})
} as const;

type Key=keyof typeof schemas;
type Spec={table:string;prefix:string;columns:Record<string,string>;json?:Set<string>;order:string};
const specs:Record<Key,Spec>={
 branches:{table:"school_branches",prefix:"brn",columns:{code:"code",name:"name",registrationNumber:"registration_number",phone:"phone",email:"email",physicalAddress:"physical_address",postalAddress:"postal_address",districtRegion:"district_region",locationText:"location_text",principalName:"principal_name",isMain:"is_main",active:"active"},order:"is_main DESC,name"},
 academicYears:{table:"school_academic_years",prefix:"acy",columns:{code:"code",name:"name",startsOn:"starts_on",endsOn:"ends_on",status:"status",isCurrent:"is_current"},order:"starts_on DESC"},
 terms:{table:"school_terms",prefix:"trm",columns:{academicYearId:"academic_year_id",code:"code",name:"name",sequenceNo:"sequence_no",startsOn:"starts_on",endsOn:"ends_on",status:"status",isCurrent:"is_current"},order:"starts_on DESC,sequence_no"},
 departments:{table:"school_departments",prefix:"dep",columns:{campusId:"campus_id",code:"code",name:"name",description:"description",headUserId:"head_user_id",parentId:"parent_id",active:"active"},order:"name"},
 classLevels:{table:"school_class_levels",prefix:"lvl",columns:{code:"code",name:"name",sequenceNo:"sequence_no",educationLevel:"education_level",promotionLevelId:"promotion_level_id",terminal:"terminal",active:"active"},order:"sequence_no"},
 classes:{table:"school_classes",prefix:"cls",columns:{academicYearId:"academic_year_id",campusId:"campus_id",classLevelId:"class_level_id",departmentId:"department_id",code:"code",name:"name",capacity:"capacity",classTeacherUserId:"class_teacher_user_id",active:"active"},order:"name"},
 streams:{table:"school_streams",prefix:"str",columns:{classId:"class_id",campusId:"campus_id",code:"code",name:"name",capacity:"capacity",classTeacherUserId:"class_teacher_user_id",active:"active"},order:"name"},
 subjects:{table:"school_subjects",prefix:"sub",columns:{departmentId:"department_id",code:"code",name:"name",shortName:"short_name",subjectType:"subject_type",curriculumCode:"curriculum_code",passMark:"pass_mark",maxMark:"max_mark",active:"active",metadata:"metadata"},json:new Set(["metadata"]),order:"name"},
 classSubjects:{table:"school_class_subjects",prefix:"csb",columns:{classLevelId:"class_level_id",subjectId:"subject_id",academicYearId:"academic_year_id",compulsory:"compulsory",periodsPerWeek:"periods_per_week",teacherUserId:"teacher_user_id",active:"active"},order:"created_at"}
};

function camel(row:Record<string,unknown>){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(row))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return out;}
function dbValue(spec:Spec,key:string,value:unknown){return spec.json?.has(key)?JSON.stringify(value):value;}
async function audit(runtime:Runtime,organizationId:string,actorId:string,action:string,entityType:string,entityId:string,after?:unknown){await runtime.db.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,after_data) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[createId("aud"),organizationId,actorId,action,entityType,entityId,after===undefined?null:JSON.stringify(after)]);}
async function owned(runtime:Runtime,organizationId:string,table:string,id:string|undefined|null){if(!id)return;const hit=await runtime.db.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2`,[id,organizationId]);if(!hit.rowCount)throw new AppError(422,"INVALID_REFERENCE",`Referenced ${table} record does not belong to this school`);}
async function validateRefs(runtime:Runtime,organizationId:string,key:Key,v:Record<string,unknown>){if(key==="terms")await owned(runtime,organizationId,"school_academic_years",v.academicYearId as string);if(key==="departments"){await owned(runtime,organizationId,"school_branches",v.campusId as string);await owned(runtime,organizationId,"school_departments",v.parentId as string);}if(key==="classLevels")await owned(runtime,organizationId,"school_class_levels",v.promotionLevelId as string);if(key==="classes"){await owned(runtime,organizationId,"school_academic_years",v.academicYearId as string);await owned(runtime,organizationId,"school_branches",v.campusId as string);await owned(runtime,organizationId,"school_class_levels",v.classLevelId as string);await owned(runtime,organizationId,"school_departments",v.departmentId as string);}if(key==="streams"){await owned(runtime,organizationId,"school_classes",v.classId as string);await owned(runtime,organizationId,"school_branches",v.campusId as string);}if(key==="subjects")await owned(runtime,organizationId,"school_departments",v.departmentId as string);if(key==="classSubjects"){await owned(runtime,organizationId,"school_class_levels",v.classLevelId as string);await owned(runtime,organizationId,"school_subjects",v.subjectId as string);await owned(runtime,organizationId,"school_academic_years",v.academicYearId as string);}}

export function createSchoolRoutes(runtime:Runtime){const root=new Hono<AppEnv>();
 root.get("/manifest",c=>c.json({data:{key:"school-management",name:"School Management",version:"2.0.0-node",backendModules:["setup"],plannedModules:["iam","student-management","promotion-engine","discipline-behaviour","staff-teacher-management","files","fees-billing","library","boarding","transport"],integratesWith:["academics","exams","communications"],accountingIntegration:true}}));
 const setup=new Hono<AppEnv>();setup.use("*",requireScope("school:read"));
 setup.get("/profile",async c=>{const p=c.get("principal"),row=(await runtime.db.query(`SELECT sp.*,o.name AS school_name,o.legal_name FROM school_profiles sp JOIN organizations o ON o.id=sp.organization_id WHERE sp.organization_id=$1`,[p.organizationId])).rows[0];return c.json({data:row?camel(row):null});});
 setup.put("/profile",requireScope("school:write"),async c=>{const s=profileSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Check the school profile fields and try again",s.error.flatten());const p=c.get("principal"),v=s.data;await runtime.db.query(`INSERT INTO school_profiles(organization_id,school_code,registration_number,motto,school_type,ownership_type,education_level,curriculum,phone_numbers,email_addresses,website,physical_address,postal_address,country,district_region,location_text,head_teacher_name,head_teacher_phone,head_teacher_email,language,timezone,date_format,time_format,default_currency,multi_campus_enabled,branding,system_preferences) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26::jsonb,$27::jsonb) ON CONFLICT(organization_id) DO UPDATE SET school_code=EXCLUDED.school_code,registration_number=EXCLUDED.registration_number,motto=EXCLUDED.motto,school_type=EXCLUDED.school_type,ownership_type=EXCLUDED.ownership_type,education_level=EXCLUDED.education_level,curriculum=EXCLUDED.curriculum,phone_numbers=EXCLUDED.phone_numbers,email_addresses=EXCLUDED.email_addresses,website=EXCLUDED.website,physical_address=EXCLUDED.physical_address,postal_address=EXCLUDED.postal_address,country=EXCLUDED.country,district_region=EXCLUDED.district_region,location_text=EXCLUDED.location_text,head_teacher_name=EXCLUDED.head_teacher_name,head_teacher_phone=EXCLUDED.head_teacher_phone,head_teacher_email=EXCLUDED.head_teacher_email,language=EXCLUDED.language,timezone=EXCLUDED.timezone,date_format=EXCLUDED.date_format,time_format=EXCLUDED.time_format,default_currency=EXCLUDED.default_currency,multi_campus_enabled=EXCLUDED.multi_campus_enabled,branding=EXCLUDED.branding,system_preferences=EXCLUDED.system_preferences,updated_at=CURRENT_TIMESTAMP`,[p.organizationId,v.schoolCode,v.registrationNumber??null,v.motto??null,v.schoolType,v.ownershipType??null,v.educationLevel??null,v.curriculum??null,JSON.stringify(v.phoneNumbers),JSON.stringify(v.emailAddresses),v.website??null,v.physicalAddress??null,v.postalAddress??null,v.country,v.districtRegion??null,v.locationText??null,v.headTeacherName??null,v.headTeacherPhone??null,v.headTeacherEmail??null,v.language,v.timezone,v.dateFormat,v.timeFormat,v.defaultCurrency,v.multiCampusEnabled,JSON.stringify(v.branding),JSON.stringify(v.systemPreferences)]);await audit(runtime,p.organizationId,p.userId,"school.profile.updated","school_profile",p.organizationId,v);return c.json({data:v});});

 for(const key of Object.keys(specs) as Key[]){const spec=specs[key],schema=schemas[key];
  setup.get(`/${key}`,async c=>{const p=c.get("principal"),limit=Math.min(Math.max(Number(c.req.query("limit")??100),1),500),offset=Math.max(Number(c.req.query("offset")??0),0),r=await runtime.db.query(`SELECT * FROM ${spec.table} WHERE organization_id=$1 ORDER BY ${spec.order} LIMIT $2 OFFSET $3`,[p.organizationId,limit,offset]);return c.json({data:r.rows.map(camel),pagination:{limit,offset,count:r.rows.length}});});
  setup.get(`/${key}/:id`,async c=>{const p=c.get("principal"),row=(await runtime.db.query(`SELECT * FROM ${spec.table} WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId])).rows[0];if(!row)throw new AppError(404,"NOT_FOUND",`${key} record not found`);return c.json({data:camel(row)});});
  setup.post(`/${key}`,requireScope("school:write"),async c=>{const parsed=schema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR",`Check the ${key} fields and try again`,parsed.error.flatten());const p=c.get("principal"),v=parsed.data as Record<string,unknown>;await validateRefs(runtime,p.organizationId,key,v);const id=createId(spec.prefix),client=await runtime.db.connect();try{await client.query("BEGIN");if((key==="academicYears"||key==="terms")&&v.isCurrent)await client.query(`UPDATE ${spec.table} SET is_current=false,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1`,[p.organizationId]);if(key==="branches"&&v.isMain)await client.query(`UPDATE school_branches SET is_main=false,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1`,[p.organizationId]);const entries=Object.entries(spec.columns).filter(([k])=>k in v),cols=entries.map(([,col])=>col),vals=entries.map(([k])=>dbValue(spec,k,v[k]));await client.query(`INSERT INTO ${spec.table}(id,organization_id,${cols.join(",")}) VALUES($1,$2,${entries.map((_,i)=>`$${i+3}`).join(",")})`,[id,p.organizationId,...vals]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}await audit(runtime,p.organizationId,p.userId,`school.${key}.created`,spec.table,id,v);return c.json({data:{id,...v}},201);});
  setup.put(`/${key}/:id`,requireScope("school:write"),async c=>{const parsed=schema.partial().safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR",`Check the ${key} changes and try again`,parsed.error.flatten());const p=c.get("principal"),v=parsed.data as Record<string,unknown>,id=c.req.param("id");if(!Object.keys(v).length)throw new AppError(422,"VALIDATION_ERROR","No changes supplied");const current=(await runtime.db.query(`SELECT * FROM ${spec.table} WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!current)throw new AppError(404,"NOT_FOUND",`${key} record not found`);await validateRefs(runtime,p.organizationId,key,{...camel(current),...v});const entries=Object.entries(spec.columns).filter(([k])=>k in v),set=entries.map(([,col],i)=>`${col}=$${i+1}`),vals=entries.map(([k])=>dbValue(spec,k,v[k]));const client=await runtime.db.connect();try{await client.query("BEGIN");if((key==="academicYears"||key==="terms")&&v.isCurrent)await client.query(`UPDATE ${spec.table} SET is_current=false,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND id<>$2`,[p.organizationId,id]);if(key==="branches"&&v.isMain)await client.query(`UPDATE school_branches SET is_main=false,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND id<>$2`,[p.organizationId,id]);await client.query(`UPDATE ${spec.table} SET ${set.join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=$${vals.length+1} AND organization_id=$${vals.length+2}`,[...vals,id,p.organizationId]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}await audit(runtime,p.organizationId,p.userId,`school.${key}.updated`,spec.table,id,v);return c.json({data:{id,...v}});});
  setup.delete(`/${key}/:id`,requireScope("school:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");let r;try{r=await runtime.db.query(`DELETE FROM ${spec.table} WHERE id=$1 AND organization_id=$2`,[id,p.organizationId]);}catch{throw new AppError(409,"RECORD_IN_USE","This configuration record is already in use and cannot be deleted");}if(!r.rowCount)throw new AppError(404,"NOT_FOUND",`${key} record not found`);await audit(runtime,p.organizationId,p.userId,`school.${key}.deleted`,spec.table,id);return c.body(null,204);});
 }
 setup.get("/settings/all",async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT setting_group AS "group",setting_key AS "key",value_json AS value,updated_at AS "updatedAt" FROM school_settings WHERE organization_id=$1 ORDER BY setting_group,setting_key`,[p.organizationId]);return c.json({data:r.rows});});
 setup.put("/settings/value",requireScope("school:write"),async c=>{const schema=z.object({group:z.string().min(1).max(80),key:z.string().min(1).max(120),value:z.unknown()}),parsed=schema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid school setting",parsed.error.flatten());const p=c.get("principal"),v=parsed.data;await runtime.db.query(`INSERT INTO school_settings(organization_id,setting_group,setting_key,value_json,updated_by) VALUES($1,$2,$3,$4::jsonb,$5) ON CONFLICT(organization_id,setting_group,setting_key) DO UPDATE SET value_json=EXCLUDED.value_json,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP`,[p.organizationId,v.group,v.key,JSON.stringify(v.value),p.userId]);return c.json({data:v});});
 root.route("/setup",setup);return root;}
