import { Hono } from "hono";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

async function member(runtime:Runtime,org:string,userId?:string|null){if(!userId)return;const q=await runtime.db.query(`SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$2`,[org,userId]);if(!q.rowCount)throw new AppError(422,"INVALID_USER","Selected teacher is not a member of this school");}

export function createSchoolSetupClassIntegrityRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.post("/classes",requireScope("school:write"),async c=>{const p=c.get("principal"),b=await c.req.json().catch(()=>({})) as any;if(!b.classLevelId||!b.code||!b.name)throw new AppError(422,"VALIDATION_ERROR","classLevelId, code and name are required");const level=await runtime.db.query(`SELECT 1 FROM school_class_levels WHERE id=$1 AND organization_id=$2 AND active=true`,[b.classLevelId,p.organizationId]);if(!level.rowCount)throw new AppError(422,"INVALID_CLASS_LEVEL","Class level is not active in this school");if(b.academicYearId){const q=await runtime.db.query(`SELECT 1 FROM school_academic_years WHERE id=$1 AND organization_id=$2`,[b.academicYearId,p.organizationId]);if(!q.rowCount)throw new AppError(422,"INVALID_ACADEMIC_YEAR","Academic year does not belong to this school");}if(b.campusId){const q=await runtime.db.query(`SELECT 1 FROM school_branches WHERE id=$1 AND organization_id=$2 AND active=true`,[b.campusId,p.organizationId]);if(!q.rowCount)throw new AppError(422,"INVALID_CAMPUS","Campus is not active in this school");}if(b.departmentId){const q=await runtime.db.query(`SELECT campus_id FROM school_departments WHERE id=$1 AND organization_id=$2 AND active=true`,[b.departmentId,p.organizationId]);if(!q.rowCount)throw new AppError(422,"INVALID_DEPARTMENT","Department is not active in this school");const campus=(q.rows[0] as any).campus_id;if(campus&&b.campusId&&String(campus)!==String(b.campusId))throw new AppError(422,"DEPARTMENT_CAMPUS_MISMATCH","Department does not belong to the selected campus");}await member(runtime,p.organizationId,b.classTeacherUserId);const id=createId("cls");await runtime.db.query(`INSERT INTO school_classes(id,organization_id,academic_year_id,campus_id,class_level_id,department_id,code,name,capacity,class_teacher_user_id,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,p.organizationId,b.academicYearId??null,b.campusId??null,b.classLevelId,b.departmentId??null,String(b.code),String(b.name),b.capacity??null,b.classTeacherUserId??null,b.active!==false]);return c.json({data:{id,...b}},201);});
 r.post("/streams",requireScope("school:write"),async c=>{const p=c.get("principal"),b=await c.req.json().catch(()=>({})) as any;if(!b.classId||!b.code||!b.name)throw new AppError(422,"VALIDATION_ERROR","classId, code and name are required");const cls=(await runtime.db.query(`SELECT campus_id,active FROM school_classes WHERE id=$1 AND organization_id=$2`,[b.classId,p.organizationId])).rows[0] as any;if(!cls||cls.active!==true)throw new AppError(422,"INVALID_CLASS","Class is not active in this school");if(b.campusId&&cls.campus_id&&String(b.campusId)!==String(cls.campus_id))throw new AppError(422,"CLASS_CAMPUS_MISMATCH","Stream campus must match its class campus");await member(runtime,p.organizationId,b.classTeacherUserId);const id=createId("str");await runtime.db.query(`INSERT INTO school_streams(id,organization_id,class_id,campus_id,code,name,capacity,class_teacher_user_id,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,b.classId,b.campusId??cls.campus_id??null,String(b.code),String(b.name),b.capacity??null,b.classTeacherUserId??null,b.active!==false]);return c.json({data:{id,...b}},201);});
 return r;}
