import { AppError } from "../../http/errors.js";
import type { Runtime } from "../../runtime.js";
import { domainCollections, queryDomainCollection } from "./domain-collections.js";

type CollectionMode="read-only"|"append-only";
type Definition={moduleKey:string;collectionKey:string;schemaVersion:number;mode:CollectionMode;sourceOfTruth:"server"|"merge";conflictPolicy:"server-wins"|"append-only";pullScope:string;pushScope?:string;dependsOn?:Array<{moduleKey:string;collectionKey:string}>};
export const financeCollections:Definition[]=[
 {moduleKey:"ledgerly-core",collectionKey:"accounts",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"accounts:read"},
 {moduleKey:"ledgerly-core",collectionKey:"dimensions",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"accounts:read"},
 {moduleKey:"ledgerly-core",collectionKey:"products",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"products:read"},
 {moduleKey:"ledgerly-core",collectionKey:"projects",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"documents:read"},
 {moduleKey:"ledgerly-core",collectionKey:"fiscal-periods",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"periods:read"},
 {moduleKey:"ledgerly-core",collectionKey:"bank-accounts",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"accounts:read"},
 {moduleKey:"ledgerly-core",collectionKey:"documents",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"documents:read"},
 {moduleKey:"ledgerly-core",collectionKey:"document-lines",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"documents:read",dependsOn:[{moduleKey:"ledgerly-core",collectionKey:"documents"}]},
 {moduleKey:"ledgerly-core",collectionKey:"journals",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"journals:read"},
 {moduleKey:"ledgerly-core",collectionKey:"journal-lines",schemaVersion:1,mode:"read-only",sourceOfTruth:"server",conflictPolicy:"server-wins",pullScope:"journals:read",dependsOn:[{moduleKey:"ledgerly-core",collectionKey:"journals"}]},
 {moduleKey:"ledgerly-core",collectionKey:"document-intents",schemaVersion:1,mode:"append-only",sourceOfTruth:"merge",conflictPolicy:"append-only",pullScope:"documents:read",pushScope:"documents:write",dependsOn:[{moduleKey:"ledgerly-core",collectionKey:"accounts"}]},
 {moduleKey:"ledgerly-core",collectionKey:"journal-intents",schemaVersion:1,mode:"append-only",sourceOfTruth:"merge",conflictPolicy:"append-only",pullScope:"journals:read",pushScope:"journals:write",dependsOn:[{moduleKey:"ledgerly-core",collectionKey:"accounts"},{moduleKey:"ledgerly-core",collectionKey:"fiscal-periods"}]},
 {moduleKey:"human-resources",collectionKey:"leave-request-intents",schemaVersion:1,mode:"append-only",sourceOfTruth:"merge",conflictPolicy:"append-only",pullScope:"hr:read",pushScope:"hr:write",dependsOn:[{moduleKey:"human-resources",collectionKey:"employees"},{moduleKey:"human-resources",collectionKey:"leave-types"}]},
 {moduleKey:"human-resources",collectionKey:"onboarding-completion-intents",schemaVersion:1,mode:"append-only",sourceOfTruth:"merge",conflictPolicy:"append-only",pullScope:"hr:read",pushScope:"hr:write",dependsOn:[{moduleKey:"human-resources",collectionKey:"onboarding-tasks"}]},
 {moduleKey:"payroll-payments",collectionKey:"payment-draft-intents",schemaVersion:1,mode:"append-only",sourceOfTruth:"merge",conflictPolicy:"append-only",pullScope:"payments:read",pushScope:"payments:write"},
 ...domainCollections,
];
export function collectionDefinition(moduleKey:string,collectionKey:string){return financeCollections.find(x=>x.moduleKey===moduleKey&&x.collectionKey===collectionKey);}
export function hasPrincipalScope(principal:{role:string;scopes:string[]},scope?:string){return !scope||principal.role==="owner"||principal.role==="admin"||principal.scopes.includes(scope);}

async function queryRows(runtime:Runtime,organizationId:string,userId:string,moduleKey:string,key:string,ids?:string[]){
 if(moduleKey==="human-resources"&&(key==="leave-request-intents"||key==="onboarding-completion-intents"))return[];
 if(moduleKey==="payroll-payments"&&key==="payment-draft-intents")return[];
 if(moduleKey!=="ledgerly-core"){const rows=await queryDomainCollection(runtime,organizationId,moduleKey,key,ids);if(rows!==null)return rows;throw new AppError(422,"COLLECTION_NOT_REGISTERED",`Unknown mobile-sync collection ${moduleKey}:${key}`);}
 const filter=ids?.length?` AND id=ANY($2::text[])`:"",params=ids?.length?[organizationId,ids]:[organizationId];switch(key){
 case"accounts":return(await runtime.db.query(`SELECT id,code,name,type,subtype,normal_balance AS "normalBalance",currency,allow_posting AS "allowPosting",active,parent_account_id AS "parentAccountId",account_group_id AS "accountGroupId",created_at AS "createdAt",updated_at AS "updatedAt" FROM accounts WHERE organization_id=$1${filter} ORDER BY code`,params)).rows;
 case"dimensions":return(await runtime.db.query(`SELECT id,type,code,name,active,created_at AS "createdAt",updated_at AS "updatedAt" FROM dimensions WHERE organization_id=$1${filter} ORDER BY type,code`,params)).rows;
 case"products":return(await runtime.db.query(`SELECT id,sku,name,type,income_account_id AS "incomeAccountId",expense_account_id AS "expenseAccountId",inventory_account_id AS "inventoryAccountId",quantity_on_hand_micros::float8 AS "quantityOnHandMicros",average_cost_minor::float8 AS "averageCostMinor",reorder_point_micros::float8 AS "reorderPointMicros",active,created_at AS "createdAt",updated_at AS "updatedAt" FROM products WHERE organization_id=$1${filter} ORDER BY name`,params)).rows;
 case"projects":return(await runtime.db.query(`SELECT id,customer_id AS "customerId",code,name,status,budget_amount_minor::float8 AS "budgetAmountMinor",created_at AS "createdAt",updated_at AS "updatedAt" FROM projects WHERE organization_id=$1${filter} ORDER BY code`,params)).rows;
 case"fiscal-periods":return(await runtime.db.query(`SELECT id,name,starts_on::text AS "startsOn",ends_on::text AS "endsOn",status,locked_at AS "lockedAt",locked_by AS "lockedBy",created_at AS "createdAt",updated_at AS "updatedAt" FROM fiscal_periods WHERE organization_id=$1${filter} ORDER BY starts_on DESC`,params)).rows;
 case"bank-accounts":return(await runtime.db.query(`SELECT id,ledger_account_id AS "ledgerAccountId",name,bank_name AS "bankName",account_number_masked AS "accountNumberMasked",currency,opening_balance_minor::float8 AS "openingBalanceMinor",active,created_at AS "createdAt",updated_at AS "updatedAt" FROM bank_accounts WHERE organization_id=$1${filter} ORDER BY name`,params)).rows;
 case"documents":return(await runtime.db.query(`SELECT id,type,number,contact_id AS "contactId",issue_date::text AS "issueDate",due_date::text AS "dueDate",status,currency,subtotal_minor::float8 AS "subtotalMinor",tax_minor::float8 AS "taxMinor",total_minor::float8 AS "totalMinor",paid_minor::float8 AS "paidMinor",journal_entry_id AS "journalEntryId",approval_status AS "approvalStatus",custom_fields AS "customFields",created_at AS "createdAt",updated_at AS "updatedAt" FROM documents WHERE organization_id=$1${filter} ORDER BY issue_date DESC,created_at DESC`,params)).rows;
 case"document-lines":return(await runtime.db.query(`SELECT id,document_id AS "documentId",product_id AS "productId",account_id AS "accountId",tax_account_id AS "taxAccountId",description,quantity_micros::float8 AS "quantityMicros",unit_price_minor::float8 AS "unitPriceMinor",subtotal_minor::float8 AS "subtotalMinor",tax_minor::float8 AS "taxMinor",total_minor::float8 AS "totalMinor",project_id AS "projectId",class_id AS "classId",department_id AS "departmentId",location_id AS "locationId",dimensions_json AS "dimensionsJson",created_at AS "createdAt",updated_at AS "updatedAt" FROM document_lines WHERE organization_id=$1${filter} ORDER BY created_at,id`,params)).rows;
 case"journals":return(await runtime.db.query(`SELECT id,entry_number AS "entryNumber",transaction_date::text AS "transactionDate",posting_date::text AS "postingDate",description,reference,source_type AS "sourceType",source_id AS "sourceId",status,currency,exchange_rate_micros::float8 AS "exchangeRateMicros",reversal_of_id AS "reversalOfId",posted_at AS "postedAt",posted_by AS "postedBy",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM journal_entries WHERE organization_id=$1${filter} ORDER BY posting_date DESC,created_at DESC`,params)).rows;
 case"journal-lines":return(await runtime.db.query(`SELECT id,journal_entry_id AS "journalEntryId",account_id AS "accountId",description,debit_minor::float8 AS "debitMinor",credit_minor::float8 AS "creditMinor",base_debit_minor::float8 AS "baseDebitMinor",base_credit_minor::float8 AS "baseCreditMinor",contact_id AS "contactId",project_id AS "projectId",class_id AS "classId",department_id AS "departmentId",location_id AS "locationId",tax_code AS "taxCode",dimensions_json AS "dimensionsJson",created_at AS "createdAt",updated_at AS "updatedAt" FROM journal_lines WHERE organization_id=$1${filter} ORDER BY created_at,id`,params)).rows;
 case"document-intents":{const params2:any[]=[organizationId,userId];let extra="";if(ids?.length){params2.push(ids);extra=" AND id=ANY($3::text[])";}return(await runtime.db.query(`SELECT id,intent_type AS "intentType",status,server_document_id AS "serverDocumentId",error_code AS "errorCode",error_message AS "errorMessage",attempts,client_created_at AS "clientCreatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM ledgerly_mobile_document_intents WHERE organization_id=$1 AND created_by=$2${extra} ORDER BY created_at DESC`,params2)).rows;}
 case"journal-intents":{const params2:any[]=[organizationId,userId];let extra="";if(ids?.length){params2.push(ids);extra=" AND id=ANY($3::text[])";}return(await runtime.db.query(`SELECT id,status,server_journal_id AS "serverJournalId",error_code AS "errorCode",error_message AS "errorMessage",attempts,client_created_at AS "clientCreatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM ledgerly_mobile_journal_intents WHERE organization_id=$1 AND created_by=$2${extra} ORDER BY created_at DESC`,params2)).rows;}
 default:throw new AppError(422,"COLLECTION_NOT_REGISTERED",`Unknown mobile-sync collection ledgerly-core:${key}`);
 }}

export async function snapshotCollection(runtime:Runtime,organizationId:string,userId:string,moduleKey:string,key:string,ids?:string[]){const def=collectionDefinition(moduleKey,key);if(!def)throw new AppError(422,"COLLECTION_NOT_REGISTERED",`Unknown mobile-sync collection ${moduleKey}:${key}`);const rows=await queryRows(runtime,organizationId,userId,moduleKey,key,ids);for(const row of rows as any[]){await runtime.db.query(`INSERT INTO mobile_sync_record_versions(organization_id,module_key,collection_key,record_id,version,deleted,server_updated_at) VALUES($1,$2,$3,$4,1,false,COALESCE($5::timestamptz,CURRENT_TIMESTAMP)) ON CONFLICT DO NOTHING`,[organizationId,moduleKey,key,row.id,row.updatedAt??row.createdAt??null]);}if(!rows.length)return[];const versions=(await runtime.db.query<{recordId:string;version:number;serverUpdatedAt:string}>(`SELECT record_id AS "recordId",version::float8 AS version,server_updated_at AS "serverUpdatedAt" FROM mobile_sync_record_versions WHERE organization_id=$1 AND module_key=$2 AND collection_key=$3 AND record_id=ANY($4::text[])`,[organizationId,moduleKey,key,(rows as any[]).map(r=>r.id)])).rows,map=new Map(versions.map(v=>[v.recordId,v]));return(rows as any[]).map(row=>({id:row.id,version:Number(map.get(row.id)?.version??1),updatedAt:row.updatedAt??row.createdAt??map.get(row.id)?.serverUpdatedAt??new Date(0).toISOString(),payload:row}));}
