import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { requireScope } from "../core-identity/security.js";
import { queueDocumentIntent, queueJournalIntent } from "./intents.js";

const product=z.object({sku:z.string().trim().min(1).max(60),name:z.string().trim().min(1).max(160),type:z.enum(["inventory","service","non_inventory"]),incomeAccountId:z.string().optional().nullable(),expenseAccountId:z.string().optional().nullable(),inventoryAccountId:z.string().optional().nullable(),quantityOnHandMicros:z.number().int().default(0),averageCostMinor:z.number().int().nonnegative().default(0),reorderPointMicros:z.number().int().nonnegative().default(0),active:z.boolean().default(true)});
const bank=z.object({ledgerAccountId:z.string(),name:z.string().trim().min(1).max(160),bankName:z.string().trim().max(160).optional().nullable(),accountNumberMasked:z.string().trim().max(40).optional().nullable(),currency:z.string().length(3).transform(v=>v.toUpperCase()),openingBalanceMinor:z.number().int().default(0),active:z.boolean().default(true)});
const intentEnvelope=z.object({id:z.string().min(8).max(160).optional(),deviceId:z.string().min(8).max(160).optional(),clientTimestamp:z.iso.datetime().optional(),payload:z.unknown()});

async function kick(runtime:Runtime){await runtime.queue.publish("finance-mobile.intents",{},{queue:"finance-mobile",maxAttempts:3}).catch(()=>undefined);}

export function createFinanceMobileRoutes(runtime:Runtime){const r=new Hono<AppEnv>();
 r.get("/budgets/:id",requireScope("reports:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),budget=(await runtime.db.query(`SELECT id,name,fiscal_year AS "fiscalYear",version,scenario,kind,parent_id AS "parentId",status,locked_at AS "lockedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM budgets WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!budget)throw new AppError(404,"NOT_FOUND","Budget not found");const lines=await runtime.db.query(`SELECT l.id,l.account_id AS "accountId",a.code AS "accountCode",a.name AS "accountName",l.period,l.amount_minor::float8 AS "amountMinor",l.class_id AS "classId",cl.name AS "className",l.department_id AS "departmentId",d.name AS "departmentName",l.location_id AS "locationId",loc.name AS "locationName",l.cost_center_id AS "costCenterId",cc.name AS "costCenterName",l.revenue_source_id AS "revenueSourceId",rs.name AS "revenueSourceName",l.project_id AS "projectId" FROM budget_lines l JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id LEFT JOIN dimensions cl ON cl.id=l.class_id AND cl.organization_id=l.organization_id LEFT JOIN dimensions d ON d.id=l.department_id AND d.organization_id=l.organization_id LEFT JOIN dimensions loc ON loc.id=l.location_id AND loc.organization_id=l.organization_id LEFT JOIN cost_centers cc ON cc.id=l.cost_center_id AND cc.organization_id=l.organization_id LEFT JOIN revenue_sources rs ON rs.id=l.revenue_source_id AND rs.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.budget_id=$2 ORDER BY l.period,a.code`,[p.organizationId,id]);return c.json({data:{...budget,lines:lines.rows}});});
 r.get("/banking/transactions/:id/match-candidates",requireScope("payments:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),tx=(await runtime.db.query<any>(`SELECT t.id,t.bank_account_id AS "bankAccountId",t.transaction_date::text AS "transactionDate",t.amount_minor::float8 AS "amountMinor",t.status,b.ledger_account_id AS "ledgerAccountId" FROM bank_transactions t JOIN bank_accounts b ON b.id=t.bank_account_id AND b.organization_id=t.organization_id WHERE t.id=$1 AND t.organization_id=$2`,[id,p.organizationId])).rows[0];if(!tx)throw new AppError(404,"NOT_FOUND","Bank transaction not found");const rows=await runtime.db.query(`SELECT l.id AS "journalLineId",j.id AS "journalId",j.entry_number AS "entryNumber",j.posting_date::text AS "postingDate",j.description,j.reference,j.status,l.debit_minor::float8 AS "debitMinor",l.credit_minor::float8 AS "creditMinor",(l.debit_minor-l.credit_minor)::float8 AS "netMinor" FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.organization_id=l.organization_id WHERE l.organization_id=$1 AND l.account_id=$2 AND j.status IN ('posted','reversed') AND (l.debit_minor-l.credit_minor)=$3 AND ABS(j.posting_date-$4::date)<=14 AND NOT EXISTS(SELECT 1 FROM bank_transactions x WHERE x.organization_id=l.organization_id AND x.matched_journal_line_id=l.id AND x.id<>$5) ORDER BY ABS(j.posting_date-$4::date),j.posting_date DESC,j.entry_number DESC LIMIT 100`,[p.organizationId,tx.ledgerAccountId,tx.amountMinor,tx.transactionDate,id]);return c.json({data:{transaction:tx,candidates:rows.rows}});});
 r.get("/inventory/movements",requireScope("products:read"),async c=>{const p=c.get("principal"),productId=c.req.query("productId")||null,locationId=c.req.query("locationId")||null,limit=Math.max(1,Math.min(500,Number(c.req.query("limit")||200)));const rows=await runtime.db.query(`SELECT m.id,m.product_id AS "productId",p.sku,p.name AS "productName",m.location_id AS "locationId",l.code AS "locationCode",l.name AS "locationName",m.type,m.movement_date::text AS "movementDate",m.quantity_delta_micros::float8 AS "quantityDeltaMicros",m.unit_cost_minor::float8 AS "unitCostMinor",m.value_delta_minor::float8 AS "valueDeltaMinor",m.source_type AS "sourceType",m.source_id AS "sourceId",m.journal_entry_id AS "journalEntryId",m.created_at AS "createdAt" FROM inventory_movements m JOIN products p ON p.id=m.product_id AND p.organization_id=m.organization_id JOIN inventory_locations l ON l.id=m.location_id AND l.organization_id=m.organization_id WHERE m.organization_id=$1 AND ($2::text IS NULL OR m.product_id=$2) AND ($3::text IS NULL OR m.location_id=$3) ORDER BY m.movement_date DESC,m.created_at DESC LIMIT $4`,[p.organizationId,productId,locationId,limit]);return c.json({data:rows.rows});});
 r.get("/projects/:id",requireScope("documents:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),project=(await runtime.db.query(`SELECT p.id,p.customer_id AS "customerId",c.name AS customer,p.code,p.name,p.status,p.budget_amount_minor::float8 AS "budgetAmountMinor",p.created_at AS "createdAt",p.updated_at AS "updatedAt" FROM projects p LEFT JOIN contacts c ON c.id=p.customer_id AND c.organization_id=p.organization_id WHERE p.id=$1 AND p.organization_id=$2`,[id,p.organizationId])).rows[0];if(!project)throw new AppError(404,"NOT_FOUND","Finance project not found");const time=await runtime.db.query(`SELECT t.id,t.user_id AS "userId",u.display_name AS "userName",t.entry_date::text AS "entryDate",t.minutes,t.description,t.billable,t.cost_rate_minor::float8 AS "costRateMinor",t.billing_rate_minor::float8 AS "billingRateMinor",t.status,t.created_at AS "createdAt",t.updated_at AS "updatedAt" FROM project_time_entries t LEFT JOIN users u ON u.id=t.user_id WHERE t.organization_id=$1 AND t.project_id=$2 ORDER BY t.entry_date DESC,t.created_at DESC`,[p.organizationId,id]);return c.json({data:{...project,timeEntries:time.rows}});});
 r.get("/tax/exemptions",requireScope("accounts:read"),async c=>{const p=c.get("principal"),rows=await runtime.db.query(`SELECT e.id,e.contact_id AS "contactId",c.name AS "contactName",e.tax_code_id AS "taxCodeId",t.code AS "taxCode",e.certificate_number AS "certificateNumber",e.reason,e.starts_on::text AS "startsOn",e.ends_on::text AS "endsOn",e.created_at AS "createdAt" FROM tax_exemptions e LEFT JOIN contacts c ON c.id=e.contact_id AND c.organization_id=e.organization_id LEFT JOIN tax_codes t ON t.id=e.tax_code_id AND t.organization_id=e.organization_id WHERE e.organization_id=$1 ORDER BY e.ends_on DESC NULLS FIRST,e.created_at DESC`,[p.organizationId]);return c.json({data:rows.rows});});

 r.put("/products/:id",requireScope("products:write"),async c=>{const s=product.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid product",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=s.data,current=(await runtime.db.query<any>(`SELECT quantity_on_hand_micros::float8 AS "quantityOnHandMicros",average_cost_minor::float8 AS "averageCostMinor" FROM products WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!current)throw new AppError(404,"NOT_FOUND","Product not found");if(v.quantityOnHandMicros!==current.quantityOnHandMicros||v.averageCostMinor!==current.averageCostMinor)throw new AppError(409,"INVENTORY_BALANCE_MANAGED","Stock quantity and average cost must be changed through inventory movements");const refs:[[string|null|undefined,string],...Array<[string|null|undefined,string]>]=[[v.incomeAccountId,"revenue"],[v.expenseAccountId,"expense"],[v.inventoryAccountId,"asset"]];for(const [accountId,type] of refs){if(!accountId)continue;const found=await runtime.db.query(`SELECT 1 FROM accounts WHERE id=$1 AND organization_id=$2 AND type=$3 AND active=true AND allow_posting=true`,[accountId,p.organizationId,type]);if(!found.rowCount)throw new AppError(422,"INVALID_ACCOUNT","All product accounts must belong to the organization and have the correct account type");}if(v.type==="inventory"&&!v.inventoryAccountId)throw new AppError(422,"INVENTORY_ACCOUNT_REQUIRED","Inventory products require an inventory account");await runtime.db.query(`UPDATE products SET sku=$1,name=$2,type=$3,income_account_id=$4,expense_account_id=$5,inventory_account_id=$6,reorder_point_micros=$7,active=$8,updated_at=CURRENT_TIMESTAMP WHERE id=$9 AND organization_id=$10`,[v.sku,v.name,v.type,v.incomeAccountId??null,v.expenseAccountId??null,v.inventoryAccountId??null,v.reorderPointMicros,v.active,id,p.organizationId]);return c.json({data:{id,...v}});});
 r.patch("/products/:id/active",requireScope("products:write"),async c=>{const s=z.object({active:z.boolean()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid product status");const p=c.get("principal"),result=await runtime.db.query(`UPDATE products SET active=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 RETURNING id`,[s.data.active,c.req.param("id"),p.organizationId]);if(!result.rowCount)throw new AppError(404,"NOT_FOUND","Product not found");return c.json({data:{id:c.req.param("id"),active:s.data.active}});});
 r.put("/banking/accounts/:id",requireScope("accounts:write"),async c=>{const s=bank.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid bank account",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),v=s.data,ledger=await runtime.db.query(`SELECT 1 FROM accounts WHERE id=$1 AND organization_id=$2 AND type='asset' AND active=true AND allow_posting=true`,[v.ledgerAccountId,p.organizationId]);if(!ledger.rowCount)throw new AppError(422,"INVALID_LEDGER_ACCOUNT","Active postable asset ledger account required");const duplicate=await runtime.db.query(`SELECT id FROM bank_accounts WHERE organization_id=$1 AND ledger_account_id=$2 AND id<>$3`,[p.organizationId,v.ledgerAccountId,id]);if(duplicate.rowCount)throw new AppError(409,"LEDGER_ACCOUNT_IN_USE","That ledger account is already linked to another bank account");const result=await runtime.db.query(`UPDATE bank_accounts SET ledger_account_id=$1,name=$2,bank_name=$3,account_number_masked=$4,currency=$5,opening_balance_minor=$6,active=$7,updated_at=CURRENT_TIMESTAMP WHERE id=$8 AND organization_id=$9 RETURNING id`,[v.ledgerAccountId,v.name,v.bankName??null,v.accountNumberMasked??null,v.currency,v.openingBalanceMinor,v.active,id,p.organizationId]);if(!result.rowCount)throw new AppError(404,"NOT_FOUND","Bank account not found");return c.json({data:{id,...v}});});

 r.post("/document-intents",requireScope("documents:write"),async c=>{const s=intentEnvelope.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid document intent envelope",s.error.flatten());const p=c.get("principal"),result=await queueDocumentIntent(runtime,p.organizationId,p.userId,s.data);await kick(runtime);return c.json({data:result},202);});
 r.get("/document-intents/:id",requireScope("documents:read"),async c=>{const p=c.get("principal"),row=(await runtime.db.query(`SELECT id,device_id AS "deviceId",intent_type AS "intentType",status,server_document_id AS "serverDocumentId",attempts,error_code AS "errorCode",error_message AS "errorMessage",client_created_at AS "clientCreatedAt",applied_at AS "appliedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM ledgerly_mobile_document_intents WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId])).rows[0];if(!row)throw new AppError(404,"NOT_FOUND","Document intent not found");return c.json({data:row});});
 r.post("/journal-intents",requireScope("journals:write"),async c=>{const s=intentEnvelope.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid journal intent envelope",s.error.flatten());const p=c.get("principal"),result=await queueJournalIntent(runtime,p.organizationId,p.userId,s.data);await kick(runtime);return c.json({data:result},202);});
 r.get("/journal-intents/:id",requireScope("journals:read"),async c=>{const p=c.get("principal"),row=(await runtime.db.query(`SELECT id,device_id AS "deviceId",status,server_journal_id AS "serverJournalId",attempts,error_code AS "errorCode",error_message AS "errorMessage",client_created_at AS "clientCreatedAt",applied_at AS "appliedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM ledgerly_mobile_journal_intents WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId])).rows[0];if(!row)throw new AppError(404,"NOT_FOUND","Journal intent not found");return c.json({data:row});});
 return r;}
