import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";
import { budgetVariance, checkBudget, createBudget, createForecast, forecastVariance, refreshBudgetActuals, replaceBudgetLines, reviseBudget, transitionBudget, type BudgetLineInput } from "./service.js";

const lineSchema=z.object({
  accountId:z.string().min(1),period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),amountMinor:z.number().int().nonnegative(),
  costCenterId:z.string().optional(),revenueSourceId:z.string().optional(),projectId:z.string().optional(),classId:z.string().optional(),
  departmentId:z.string().optional(),locationId:z.string().optional(),notes:z.string().max(500).optional(),
});
const budgetSchema=z.object({
  name:z.string().trim().min(1).max(160),fiscalYear:z.number().int().min(1900).max(9999),fiscalYearId:z.string().optional(),
  scenario:z.string().trim().min(1).max(60).default("base"),kind:z.enum(["annual","rolling_forecast","cash_flow","departmental"]).default("annual"),
  enforcement:z.enum(["none","warning","block"]).default("warning"),metadata:z.record(z.string(),z.unknown()).optional(),lines:z.array(lineSchema).min(1).max(5000),
});
const editSchema=z.object({name:z.string().trim().min(1).max(160).optional(),enforcement:z.enum(["none","warning","block"]).optional(),lines:z.array(lineSchema).min(1).max(5000)});
const revisionSchema=z.object({name:z.string().trim().min(1).max(160).optional(),scenario:z.string().trim().min(1).max(60).optional(),kind:z.enum(["annual","rolling_forecast","cash_flow","departmental"]).optional(),enforcement:z.enum(["none","warning","block"]).optional(),lines:z.array(lineSchema).min(1).max(5000)});
const forecastSchema=z.object({
  name:z.string().trim().min(1).max(160),scenario:z.string().trim().min(1).max(60).default("base"),
  method:z.enum(["manual","actuals_plus_plan","run_rate","percentage"]).default("manual"),asOfMonth:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).optional(),
  adjustmentPercent:z.number().min(-100).max(10000).optional(),assumptions:z.record(z.string(),z.unknown()).optional(),lines:z.array(lineSchema).min(1).max(5000).optional(),
});

async function assertCostCenterParent(runtime:Runtime,organizationId:string,parentId:string|undefined,selfId?:string){
  if(!parentId)return;if(parentId===selfId)throw new AppError(422,"INVALID_PARENT","A cost center cannot be its own parent");
  const seen=new Set<string>(selfId?[selfId]:[]);let cursor:string|null=parentId;
  while(cursor){if(seen.has(cursor))throw new AppError(422,"INVALID_PARENT","Circular cost-center hierarchy is not allowed");seen.add(cursor);
    const row=(await runtime.db.query<{parentId:string|null}>(`SELECT parent_id AS "parentId" FROM cost_centers WHERE id=$1 AND organization_id=$2`,[cursor,organizationId])).rows[0];
    if(!row)throw new AppError(422,"INVALID_PARENT","Parent cost center not found");cursor=row.parentId;}
}

async function assertRevenueAccount(runtime:Runtime,organizationId:string,accountId:string){
  const account=(await runtime.db.query<{type:string;active:boolean}>(`SELECT type,active FROM accounts WHERE id=$1 AND organization_id=$2`,[accountId,organizationId])).rows[0];
  if(!account||account.type!=="revenue"||!account.active)throw new AppError(422,"INVALID_REVENUE_ACCOUNT","Revenue source requires an active revenue account");
}

export function createBudgetRoutes(runtime:Runtime){
  const router=new Hono<AppEnv>();

  router.get("/cost-centers",requireScope("reports:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT id,code,name,parent_id AS "parentId",manager_user_id AS "managerUserId",description,active,created_at AS "createdAt" FROM cost_centers WHERE organization_id=$1 ORDER BY code`,[p.organizationId]);return c.json({data:r.rows});});
  router.post("/cost-centers",requireScope("reports:write"),async c=>{const s=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(160),parentId:z.string().optional(),managerUserId:z.string().optional(),description:z.string().max(500).optional(),active:z.boolean().default(true)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid cost center",s.error.flatten());const p=c.get("principal"),id=createId("cc");await assertCostCenterParent(runtime,p.organizationId,s.data.parentId);await runtime.db.query(`INSERT INTO cost_centers(id,organization_id,code,name,parent_id,manager_user_id,description,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,p.organizationId,s.data.code,s.data.name,s.data.parentId??null,s.data.managerUserId??null,s.data.description??null,s.data.active]);return c.json({data:{id,...s.data}},201);});
  router.patch("/cost-centers/:id",requireScope("reports:write"),async c=>{const s=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(160),parentId:z.string().nullable().optional(),managerUserId:z.string().nullable().optional(),description:z.string().max(500).nullable().optional(),active:z.boolean()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid cost center",s.error.flatten());const p=c.get("principal"),id=c.req.param("id");await assertCostCenterParent(runtime,p.organizationId,s.data.parentId??undefined,id);const r=await runtime.db.query(`UPDATE cost_centers SET code=$1,name=$2,parent_id=$3,manager_user_id=$4,description=$5,active=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$7 AND organization_id=$8`,[s.data.code,s.data.name,s.data.parentId??null,s.data.managerUserId??null,s.data.description??null,s.data.active,id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Cost center not found");return c.json({data:{id,...s.data}});});

  router.get("/revenue-sources",requireScope("reports:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT r.id,r.code,r.name,r.revenue_account_id AS "revenueAccountId",a.code AS "accountCode",a.name AS "accountName",r.description,r.active,r.created_at AS "createdAt" FROM revenue_sources r JOIN accounts a ON a.id=r.revenue_account_id AND a.organization_id=r.organization_id WHERE r.organization_id=$1 ORDER BY r.code`,[p.organizationId]);return c.json({data:r.rows});});
  router.post("/revenue-sources",requireScope("reports:write"),async c=>{const s=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(160),revenueAccountId:z.string().min(1),description:z.string().max(500).optional(),active:z.boolean().default(true)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid revenue source",s.error.flatten());const p=c.get("principal"),id=createId("rs");await assertRevenueAccount(runtime,p.organizationId,s.data.revenueAccountId);await runtime.db.query(`INSERT INTO revenue_sources(id,organization_id,code,name,revenue_account_id,description,active) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,s.data.code,s.data.name,s.data.revenueAccountId,s.data.description??null,s.data.active]);return c.json({data:{id,...s.data}},201);});
  router.patch("/revenue-sources/:id",requireScope("reports:write"),async c=>{const s=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(160),revenueAccountId:z.string().min(1),description:z.string().max(500).nullable().optional(),active:z.boolean()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid revenue source",s.error.flatten());const p=c.get("principal"),id=c.req.param("id");await assertRevenueAccount(runtime,p.organizationId,s.data.revenueAccountId);const r=await runtime.db.query(`UPDATE revenue_sources SET code=$1,name=$2,revenue_account_id=$3,description=$4,active=$5,updated_at=CURRENT_TIMESTAMP WHERE id=$6 AND organization_id=$7`,[s.data.code,s.data.name,s.data.revenueAccountId,s.data.description??null,s.data.active,id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Revenue source not found");return c.json({data:{id,...s.data}});});

  router.get("/forecasts/:id",requireScope("reports:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),header=(await runtime.db.query(`SELECT id,budget_id AS "budgetId",name,scenario,method,as_of_month AS "asOfMonth",adjustment_percent::float8 AS "adjustmentPercent",status,version,assumptions,created_by AS "createdBy",approved_by AS "approvedBy",approved_at AS "approvedAt",created_at AS "createdAt" FROM budget_forecasts WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!header)throw new AppError(404,"NOT_FOUND","Forecast not found");const lines=await runtime.db.query(`SELECT fl.id,fl.account_id AS "accountId",a.code AS "accountCode",a.name AS "accountName",fl.period,fl.amount_minor::float8 AS "amountMinor",fl.source,fl.cost_center_id AS "costCenterId",fl.revenue_source_id AS "revenueSourceId",fl.project_id AS "projectId",fl.class_id AS "classId",fl.department_id AS "departmentId",fl.location_id AS "locationId" FROM budget_forecast_lines fl JOIN accounts a ON a.id=fl.account_id AND a.organization_id=fl.organization_id WHERE fl.forecast_id=$1 AND fl.organization_id=$2 ORDER BY fl.period,a.code`,[id,p.organizationId]);return c.json({data:{...header,lines:lines.rows}});});
  router.get("/forecasts/:id/variance",requireScope("reports:read"),async c=>{const p=c.get("principal");return c.json({data:await forecastVariance(runtime,p.organizationId,c.req.param("id"))});});
  router.post("/forecasts/:id/approve",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),r=await runtime.db.query(`UPDATE budget_forecasts SET status='approved',approved_by=$1,approved_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status='draft'`,[p.userId,id,p.organizationId]);if(!r.rowCount)throw new AppError(409,"INVALID_STATE","Draft forecast not found");return c.json({data:{id,status:"approved"}});});
  router.post("/forecasts/:id/archive",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),r=await runtime.db.query(`UPDATE budget_forecasts SET status='archived',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status<>'archived'`,[id,p.organizationId]);if(!r.rowCount)throw new AppError(404,"NOT_FOUND","Forecast not found or already archived");return c.json({data:{id,status:"archived"}});});

  router.get("/",requireScope("reports:read"),async c=>{const p=c.get("principal"),params:unknown[]=[p.organizationId],where=["organization_id=$1"];const fiscalYear=c.req.query("fiscalYear"),status=c.req.query("status"),scenario=c.req.query("scenario"),kind=c.req.query("kind");if(fiscalYear){params.push(Number(fiscalYear));where.push(`fiscal_year=$${params.length}`);}if(status){params.push(status);where.push(`status=$${params.length}`);}if(scenario){params.push(scenario);where.push(`scenario=$${params.length}`);}if(kind){params.push(kind);where.push(`kind=$${params.length}`);}const r=await runtime.db.query(`SELECT id,name,fiscal_year AS "fiscalYear",fiscal_year_id AS "fiscalYearId",status,version,scenario,kind,enforcement,parent_id AS "parentId",locked_at AS "lockedAt",submitted_at AS "submittedAt",approved_at AS "approvedAt",created_at AS "createdAt" FROM budgets WHERE ${where.join(" AND ")} ORDER BY fiscal_year DESC,name,version DESC`,params);return c.json({data:r.rows});});
  router.post("/",requireScope("reports:write"),async c=>{const s=budgetSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid budget",s.error.flatten());const p=c.get("principal");return c.json({data:await createBudget(runtime,p.organizationId,p.userId,s.data)},201);});

  router.get("/:id",requireScope("reports:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),budget=(await runtime.db.query(`SELECT id,name,fiscal_year AS "fiscalYear",fiscal_year_id AS "fiscalYearId",status,version,scenario,kind,enforcement,parent_id AS "parentId",submitted_by AS "submittedBy",submitted_at AS "submittedAt",approved_by AS "approvedBy",approved_at AS "approvedAt",rejected_by AS "rejectedBy",rejected_at AS "rejectedAt",rejection_reason AS "rejectionReason",activated_at AS "activatedAt",locked_at AS "lockedAt",locked_by AS "lockedBy",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM budgets WHERE id=$1 AND organization_id=$2`,[id,p.organizationId])).rows[0];if(!budget)throw new AppError(404,"NOT_FOUND","Budget not found");await refreshBudgetActuals(runtime,p.organizationId,id);const lines=await runtime.db.query(`SELECT bl.id,bl.account_id AS "accountId",a.code AS "accountCode",a.name AS "accountName",a.type AS "accountType",bl.period,bl.amount_minor::float8 AS "amountMinor",COALESCE(ba.actual_minor,0)::float8 AS "actualMinor",bl.cost_center_id AS "costCenterId",cc.name AS "costCenter",bl.revenue_source_id AS "revenueSourceId",rs.name AS "revenueSource",bl.project_id AS "projectId",bl.class_id AS "classId",bl.department_id AS "departmentId",bl.location_id AS "locationId",bl.notes FROM budget_lines bl JOIN accounts a ON a.id=bl.account_id AND a.organization_id=bl.organization_id LEFT JOIN budget_actuals ba ON ba.budget_line_id=bl.id LEFT JOIN cost_centers cc ON cc.id=bl.cost_center_id LEFT JOIN revenue_sources rs ON rs.id=bl.revenue_source_id WHERE bl.budget_id=$1 AND bl.organization_id=$2 ORDER BY bl.period,a.code`,[id,p.organizationId]);return c.json({data:{...budget,lines:lines.rows}});});
  router.patch("/:id",requireScope("reports:write"),async c=>{const s=editSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid budget edit",s.error.flatten());const p=c.get("principal"),id=c.req.param("id");await replaceBudgetLines(runtime,p.organizationId,p.userId,id,s.data.lines,s.data.name,s.data.enforcement);return c.json({data:{id,updated:true}});});
  router.post("/:id/revisions",requireScope("reports:write"),async c=>{const s=revisionSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid budget revision",s.error.flatten());const p=c.get("principal");return c.json({data:await reviseBudget(runtime,p.organizationId,p.userId,c.req.param("id"),s.data)},201);});
  router.post("/:id/submit",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"submit");return c.json({data:{id,status:"submitted"}});});
  router.post("/:id/approve",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"approve");return c.json({data:{id,status:"approved"}});});
  router.post("/:id/reject",requireScope("reports:write"),async c=>{const s=z.object({reason:z.string().trim().min(3).max(500)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Rejection reason required",s.error.flatten());const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"reject",s.data.reason);return c.json({data:{id,status:"rejected"}});});
  router.post("/:id/activate",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"activate");return c.json({data:{id,status:"active"}});});
  router.post("/:id/lock",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"lock");return c.json({data:{id,locked:true}});});
  router.post("/:id/unlock",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"unlock");return c.json({data:{id,locked:false}});});
  router.post("/:id/archive",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id");await transitionBudget(runtime,p.organizationId,p.userId,id,"archive");return c.json({data:{id,status:"archived"}});});
  router.post("/:id/refresh-actuals",requireScope("reports:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),count=await refreshBudgetActuals(runtime,p.organizationId,id);return c.json({data:{id,refreshedLines:count}});});
  router.get("/:id/variance",requireScope("reports:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),rows=await budgetVariance(runtime,p.organizationId,id);const budgetMinor=rows.reduce((n,row)=>n+Number(row.budgetMinor),0),actualMinor=rows.reduce((n,row)=>n+Number(row.actualMinor),0);return c.json({data:{budgetId:id,rows,totals:{budgetMinor,actualMinor,varianceMinor:actualMinor-budgetMinor}}});});
  router.post("/:id/check-spend",requireScope("reports:read"),async c=>{const s=lineSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid budget check",s.error.flatten());const p=c.get("principal");return c.json({data:await checkBudget(runtime,p.organizationId,c.req.param("id"),s.data as BudgetLineInput)});});
  router.get("/:id/forecasts",requireScope("reports:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT id,name,scenario,method,as_of_month AS "asOfMonth",adjustment_percent::float8 AS "adjustmentPercent",status,version,created_by AS "createdBy",approved_at AS "approvedAt",created_at AS "createdAt" FROM budget_forecasts WHERE organization_id=$1 AND budget_id=$2 ORDER BY scenario,version DESC`,[p.organizationId,c.req.param("id")]);return c.json({data:r.rows});});
  router.post("/:id/forecasts",requireScope("reports:write"),async c=>{const s=forecastSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid forecast",s.error.flatten());if(s.data.method==="percentage"&&s.data.adjustmentPercent===undefined)throw new AppError(422,"ADJUSTMENT_REQUIRED","Percentage forecasts require adjustmentPercent");const p=c.get("principal");return c.json({data:await createForecast(runtime,p.organizationId,p.userId,c.req.param("id"),s.data)},201);});
  router.get("/:id/variance-notes",requireScope("reports:read"),async c=>{const p=c.get("principal"),r=await runtime.db.query(`SELECT id,budget_line_id AS "budgetLineId",period,note,created_by AS "createdBy",created_at AS "createdAt" FROM budget_variance_notes WHERE organization_id=$1 AND budget_id=$2 ORDER BY created_at DESC`,[p.organizationId,c.req.param("id")]);return c.json({data:r.rows});});
  router.post("/:id/variance-notes",requireScope("reports:write"),async c=>{const s=z.object({budgetLineId:z.string().optional(),period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).optional(),note:z.string().trim().min(1).max(2000)}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid variance note",s.error.flatten());const p=c.get("principal"),id=createId("bvn"),budgetId=c.req.param("id");const exists=await runtime.db.query("SELECT 1 FROM budgets WHERE id=$1 AND organization_id=$2",[budgetId,p.organizationId]);if(!exists.rowCount)throw new AppError(404,"NOT_FOUND","Budget not found");await runtime.db.query(`INSERT INTO budget_variance_notes(id,organization_id,budget_id,budget_line_id,period,note,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,budgetId,s.data.budgetLineId??null,s.data.period??null,s.data.note,p.userId]);return c.json({data:{id,budgetId,...s.data}},201);});

  return router;
}
