import {Hono} from "hono";
import {z} from "zod";
import type {AppVariables,Env} from "../../../src/types";
import {requireScope} from "../../../src/lib/auth";
import {AppError} from "../../../src/lib/errors";
import {createId} from "../../../src/lib/ids";
import {auditStatement} from "../../../src/services/audit";

export const contactsManagementRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
const address=z.object({type:z.enum(["billing","shipping","registered","other"]),line1:z.string().trim().min(1).max(300),line2:z.string().trim().max(300).optional().nullable(),city:z.string().trim().max(120).optional().nullable(),state:z.string().trim().max(120).optional().nullable(),postalCode:z.string().trim().max(40).optional().nullable(),country:z.string().trim().length(2).transform(v=>v.toUpperCase()),isDefault:z.boolean().default(false)});
const person=z.object({name:z.string().trim().min(1).max(160),email:z.email().optional().nullable(),phone:z.string().trim().max(40).optional().nullable(),role:z.string().trim().max(80).optional().nullable(),isPrimary:z.boolean().default(false)});

async function requireContact(db:D1Database,organizationId:string,id:string,includeArchived=false){const row=await db.prepare(`SELECT id,type,code,name,email,tax_number AS taxNumber,payment_terms_days AS paymentTermsDays,active,credit_limit_minor AS creditLimitMinor,pricing_tier AS pricingTier,custom_fields AS customFields,archived_at AS archivedAt,created_at AS createdAt,updated_at AS updatedAt FROM contacts WHERE id=? AND organization_id=? ${includeArchived?"":"AND archived_at IS NULL"}`).bind(id,organizationId).first<any>();if(!row)throw new AppError(404,"NOT_FOUND","Contact not found");try{row.customFields=JSON.parse(row.customFields||"{}")}catch{row.customFields={}}return row}

contactsManagementRoutes.get("/archived",requireScope("contacts:read"),async c=>{const p=c.get("principal"),r=await c.env.FINANCE_DB.prepare("SELECT id,type,code,name,email,archived_at AS archivedAt FROM contacts WHERE organization_id=? AND archived_at IS NOT NULL ORDER BY archived_at DESC,name").bind(p.organizationId).all();return c.json({data:r.results})});
contactsManagementRoutes.get("/:id/detail",requireScope("contacts:read"),async c=>{const p=c.get("principal"),id=c.req.param("id"),contact=await requireContact(c.env.FINANCE_DB,p.organizationId,id,true),[addresses,people]=await Promise.all([c.env.FINANCE_DB.prepare("SELECT id,type,line1,line2,city,state,postal_code AS postalCode,country,is_default AS isDefault,created_at AS createdAt,updated_at AS updatedAt FROM contact_addresses WHERE organization_id=? AND contact_id=? ORDER BY is_default DESC,type,line1").bind(p.organizationId,id).all(),c.env.FINANCE_DB.prepare("SELECT id,name,email,phone,role,is_primary AS isPrimary,created_at AS createdAt,updated_at AS updatedAt FROM contact_people WHERE organization_id=? AND contact_id=? ORDER BY is_primary DESC,name").bind(p.organizationId,id).all()]);return c.json({data:{contact,addresses:addresses.results,people:people.results}})});
contactsManagementRoutes.post("/:id/restore",requireScope("contacts:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),r=await c.env.FINANCE_DB.prepare("UPDATE contacts SET active=1,archived_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND archived_at IS NOT NULL").bind(id,p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Archived contact not found");await auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"contact.restored",entityType:"contact",entityId:id}).run();return c.json({data:{id,status:"active"}})});

contactsManagementRoutes.post("/:id/addresses/manage",requireScope("contacts:write"),async c=>{const parsed=address.safeParse(await c.req.json().catch(()=>({})));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid address",parsed.error.flatten());const p=c.get("principal"),contactId=c.req.param("id");await requireContact(c.env.FINANCE_DB,p.organizationId,contactId);const id=createId("adr"),v=parsed.data,statements=[] as D1PreparedStatement[];if(v.isDefault)statements.push(c.env.FINANCE_DB.prepare("UPDATE contact_addresses SET is_default=0,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND contact_id=? AND type=?").bind(p.organizationId,contactId,v.type));statements.push(c.env.FINANCE_DB.prepare("INSERT INTO contact_addresses(id,organization_id,contact_id,type,line1,line2,city,state,postal_code,country,is_default) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(id,p.organizationId,contactId,v.type,v.line1,v.line2??null,v.city??null,v.state??null,v.postalCode??null,v.country,v.isDefault?1:0),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"contact.address.created",entityType:"contact_address",entityId:id,after:{contactId,...v}}));await c.env.FINANCE_DB.batch(statements);return c.json({data:{id,...v}},201)});
contactsManagementRoutes.patch("/:id/addresses/:addressId",requireScope("contacts:write"),async c=>{const parsed=address.partial().safeParse(await c.req.json().catch(()=>({})));if(!parsed.success||!Object.keys(parsed.data).length)throw new AppError(422,"VALIDATION_ERROR","No valid address changes supplied",parsed.success?undefined:parsed.error.flatten());const p=c.get("principal"),contactId=c.req.param("id"),addressId=c.req.param("addressId"),current=await c.env.FINANCE_DB.prepare("SELECT type,line1,line2,city,state,postal_code AS postalCode,country,is_default AS isDefault FROM contact_addresses WHERE id=? AND contact_id=? AND organization_id=?").bind(addressId,contactId,p.organizationId).first<any>();if(!current)throw new AppError(404,"NOT_FOUND","Contact address not found");const next={...current,...parsed.data},statements=[] as D1PreparedStatement[];if(next.isDefault)statements.push(c.env.FINANCE_DB.prepare("UPDATE contact_addresses SET is_default=0,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND contact_id=? AND type=? AND id<>?").bind(p.organizationId,contactId,next.type,addressId));statements.push(c.env.FINANCE_DB.prepare("UPDATE contact_addresses SET type=?,line1=?,line2=?,city=?,state=?,postal_code=?,country=?,is_default=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND contact_id=? AND organization_id=?").bind(next.type,next.line1,next.line2??null,next.city??null,next.state??null,next.postalCode??null,String(next.country).toUpperCase(),next.isDefault?1:0,addressId,contactId,p.organizationId),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"contact.address.updated",entityType:"contact_address",entityId:addressId,after:{contactId,...parsed.data}}));await c.env.FINANCE_DB.batch(statements);return c.json({data:{id:addressId,...next,isDefault:Boolean(next.isDefault)}})});
contactsManagementRoutes.delete("/:id/addresses/:addressId",requireScope("contacts:write"),async c=>{const p=c.get("principal"),r=await c.env.FINANCE_DB.prepare("DELETE FROM contact_addresses WHERE id=? AND contact_id=? AND organization_id=?").bind(c.req.param("addressId"),c.req.param("id"),p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Contact address not found");return c.body(null,204)});

contactsManagementRoutes.post("/:id/people/manage",requireScope("contacts:write"),async c=>{const parsed=person.safeParse(await c.req.json().catch(()=>({})));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid contact person",parsed.error.flatten());const p=c.get("principal"),contactId=c.req.param("id");await requireContact(c.env.FINANCE_DB,p.organizationId,contactId);const id=createId("cpr"),v=parsed.data,statements=[] as D1PreparedStatement[];if(v.isPrimary)statements.push(c.env.FINANCE_DB.prepare("UPDATE contact_people SET is_primary=0,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND contact_id=?").bind(p.organizationId,contactId));statements.push(c.env.FINANCE_DB.prepare("INSERT INTO contact_people(id,organization_id,contact_id,name,email,phone,role,is_primary) VALUES(?,?,?,?,?,?,?,?)").bind(id,p.organizationId,contactId,v.name,v.email?.toLowerCase()??null,v.phone??null,v.role??null,v.isPrimary?1:0),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"contact.person.created",entityType:"contact_person",entityId:id,after:{contactId,...v}}));await c.env.FINANCE_DB.batch(statements);return c.json({data:{id,...v}},201)});
contactsManagementRoutes.patch("/:id/people/:personId",requireScope("contacts:write"),async c=>{const parsed=person.partial().safeParse(await c.req.json().catch(()=>({})));if(!parsed.success||!Object.keys(parsed.data).length)throw new AppError(422,"VALIDATION_ERROR","No valid person changes supplied",parsed.success?undefined:parsed.error.flatten());const p=c.get("principal"),contactId=c.req.param("id"),personId=c.req.param("personId"),current=await c.env.FINANCE_DB.prepare("SELECT name,email,phone,role,is_primary AS isPrimary FROM contact_people WHERE id=? AND contact_id=? AND organization_id=?").bind(personId,contactId,p.organizationId).first<any>();if(!current)throw new AppError(404,"NOT_FOUND","Contact person not found");const next={...current,...parsed.data},statements=[] as D1PreparedStatement[];if(next.isPrimary)statements.push(c.env.FINANCE_DB.prepare("UPDATE contact_people SET is_primary=0,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND contact_id=? AND id<>?").bind(p.organizationId,contactId,personId));statements.push(c.env.FINANCE_DB.prepare("UPDATE contact_people SET name=?,email=?,phone=?,role=?,is_primary=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND contact_id=? AND organization_id=?").bind(next.name,next.email?.toLowerCase()??null,next.phone??null,next.role??null,next.isPrimary?1:0,personId,contactId,p.organizationId),auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action:"contact.person.updated",entityType:"contact_person",entityId:personId,after:{contactId,...parsed.data}}));await c.env.FINANCE_DB.batch(statements);return c.json({data:{id:personId,...next,isPrimary:Boolean(next.isPrimary)}})});
contactsManagementRoutes.delete("/:id/people/:personId",requireScope("contacts:write"),async c=>{const p=c.get("principal"),r=await c.env.FINANCE_DB.prepare("DELETE FROM contact_people WHERE id=? AND contact_id=? AND organization_id=?").bind(c.req.param("personId"),c.req.param("id"),p.organizationId).run();if(!r.meta.changes)throw new AppError(404,"NOT_FOUND","Contact person not found");return c.body(null,204)});
