import {z} from "zod";
import {AppError} from "../../../src/lib/errors";
import type {MobileSyncMutation,MobileSyncMutationContext,PreparedMobileSyncMutation} from "../../mobile-sync/backend/contracts";
import {registerMobileSyncCollection} from "../../mobile-sync/backend/registry";
import {requireContactsRead,requireContactsWrite} from "./mobile-sync-permissions";
import {snapshotAddresses,snapshotContacts,snapshotPeople} from "./mobile-sync-snapshots";
type R=Record<string,any>;
const profile=z.object({name:z.string().trim().min(1).max(160).optional(),email:z.string().email().nullable().optional()}).strict();
const person=z.object({contactId:z.string().min(2),name:z.string().trim().min(1).max(160),email:z.string().email().nullable().optional(),phone:z.string().max(40).nullable().optional(),role:z.string().max(80).nullable().optional(),isPrimary:z.boolean().default(false)}).strict();
const address=z.object({contactId:z.string().min(2),type:z.enum(["billing","shipping","registered","other"]),line1:z.string().min(1).max(300),line2:z.string().max(300).nullable().optional(),city:z.string().max(120).nullable().optional(),state:z.string().max(120).nullable().optional(),postalCode:z.string().max(40).nullable().optional(),country:z.string().length(2),isDefault:z.boolean().default(false)}).strict();
const stable=(id:string)=>/^[A-Za-z0-9][A-Za-z0-9._:-]{7,149}$/.test(id);
const suppress=(c:MobileSyncMutationContext,key:string)=>c.db.prepare('INSERT OR REPLACE INTO contacts_mobile_sync_suppression(record_key) VALUES(?)').bind(key);
const unsuppress=(c:MobileSyncMutationContext,key:string)=>c.db.prepare('DELETE FROM contacts_mobile_sync_suppression WHERE record_key=?').bind(key);
async function prepareContact(c:MobileSyncMutationContext,m:MobileSyncMutation):Promise<PreparedMobileSyncMutation>{await requireContactsWrite(c);if(m.kind==='delete')throw new AppError(409,'SERVER_MANAGED_LIFECYCLE','Contacts must be archived or merged online');const p=profile.safeParse(m.payload);if(!p.success)throw new AppError(422,'VALIDATION_ERROR','Invalid offline contact profile',p.error.flatten());const entries=Object.entries(p.data);if(!entries.length)throw new AppError(422,'VALIDATION_ERROR','No contact profile changes supplied');const row=await c.db.prepare('SELECT * FROM contacts WHERE id=? AND organization_id=? AND archived_at IS NULL').bind(m.recordId,c.organizationId).first<R>();if(!row)throw new AppError(404,'CONTACT_NOT_FOUND','Contact not found');if(c.currentVersion===0)throw new AppError(409,'BOOTSTRAP_REQUIRED','Bootstrap Contacts before editing existing contacts offline');const map:Record<string,string>={name:'name',email:'email'},set:string[]=[],vals:any[]=[];for(const[k,v]of entries){set.push(`${map[k]}=?`);vals.push(k==='email'&&typeof v==='string'?v.toLowerCase():v??null)}const key=`${c.organizationId}:contacts:${m.recordId}`;const payload={id:row.id,type:row.type,code:row.code,name:p.data.name??row.name,email:'email'in p.data?(p.data.email?.toLowerCase()??null):row.email,active:Boolean(row.active)};return{statements:[suppress(c,key),c.db.prepare(`UPDATE contacts SET ${set.join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND archived_at IS NULL`).bind(...vals,m.recordId,c.organizationId),unsuppress(c,key)],serverPayload:payload,result:{contactId:m.recordId,updatedFields:entries.map(([k])=>k)}}}
async function ensureContact(c:MobileSyncMutationContext,id:string){const r=await c.db.prepare('SELECT 1 FROM contacts WHERE id=? AND organization_id=? AND archived_at IS NULL AND active=1').bind(id,c.organizationId).first();if(!r)throw new AppError(404,'CONTACT_NOT_FOUND','Active contact not found')}
async function preparePerson(c:MobileSyncMutationContext,m:MobileSyncMutation):Promise<PreparedMobileSyncMutation>{await requireContactsWrite(c);if(m.kind==='delete')throw new AppError(409,'APPEND_ONLY_COLLECTION','Contact people cannot be deleted offline');if(!stable(m.recordId))throw new AppError(422,'INVALID_PERSON_ID','Contact person IDs must be stable UUID-style identifiers');const p=person.safeParse(m.payload);if(!p.success)throw new AppError(422,'VALIDATION_ERROR','Invalid contact person',p.error.flatten());await ensureContact(c,p.data.contactId);if(await c.db.prepare('SELECT 1 FROM contact_people WHERE id=?').bind(m.recordId).first())throw new AppError(409,'PERSON_ID_EXISTS','This contact person ID already exists');const key=`${c.organizationId}:contact-people:${m.recordId}`,at=m.clientTimestamp;const d=p.data;const statements=[suppress(c,key)];if(d.isPrimary)statements.push(c.db.prepare('UPDATE contact_people SET is_primary=0,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND contact_id=? AND is_primary=1').bind(c.organizationId,d.contactId));statements.push(c.db.prepare('INSERT INTO contact_people(id,organization_id,contact_id,name,email,phone,role,is_primary,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(m.recordId,c.organizationId,d.contactId,d.name,d.email?.toLowerCase()??null,d.phone??null,d.role??null,d.isPrimary?1:0,at,at),unsuppress(c,key));return{statements,serverPayload:{id:m.recordId,contactId:d.contactId,name:d.name,email:d.email?.toLowerCase()??null,phone:d.phone??null,role:d.role??null,isPrimary:d.isPrimary,createdAt:at,updatedAt:at},result:{personId:m.recordId,contactId:d.contactId}}}
async function prepareAddress(c:MobileSyncMutationContext,m:MobileSyncMutation):Promise<PreparedMobileSyncMutation>{await requireContactsWrite(c);if(m.kind==='delete')throw new AppError(409,'APPEND_ONLY_COLLECTION','Contact addresses cannot be deleted offline');if(!stable(m.recordId))throw new AppError(422,'INVALID_ADDRESS_ID','Contact address IDs must be stable UUID-style identifiers');const p=address.safeParse(m.payload);if(!p.success)throw new AppError(422,'VALIDATION_ERROR','Invalid contact address',p.error.flatten());await ensureContact(c,p.data.contactId);if(await c.db.prepare('SELECT 1 FROM contact_addresses WHERE id=?').bind(m.recordId).first())throw new AppError(409,'ADDRESS_ID_EXISTS','This contact address ID already exists');const key=`${c.organizationId}:contact-addresses:${m.recordId}`,at=m.clientTimestamp,d=p.data;const statements=[suppress(c,key)];if(d.isDefault)statements.push(c.db.prepare('UPDATE contact_addresses SET is_default=0,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND contact_id=? AND type=? AND is_default=1').bind(c.organizationId,d.contactId,d.type));statements.push(c.db.prepare('INSERT INTO contact_addresses(id,organization_id,contact_id,type,line1,line2,city,state,postal_code,country,is_default,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(m.recordId,c.organizationId,d.contactId,d.type,d.line1,d.line2??null,d.city??null,d.state??null,d.postalCode??null,d.country.toUpperCase(),d.isDefault?1:0,at,at),unsuppress(c,key));return{statements,serverPayload:{id:m.recordId,contactId:d.contactId,type:d.type,line1:d.line1,line2:d.line2??null,city:d.city??null,state:d.state??null,postalCode:d.postalCode??null,country:d.country.toUpperCase(),isDefault:d.isDefault,createdAt:at,updatedAt:at},result:{addressId:m.recordId,contactId:d.contactId}}}
const read={pullScope:'contacts:read',authorizePull:requireContactsRead} as const;
registerMobileSyncCollection({moduleKey:'contacts',collectionKey:'contacts',schemaVersion:2,mode:'read-write',sourceOfTruth:'server',conflictPolicy:'reject-stale',...read,pushScope:'contacts:write',authorizePush:requireContactsWrite,prepareMutation:prepareContact,snapshot:snapshotContacts});
registerMobileSyncCollection({moduleKey:'contacts',collectionKey:'contact-people',schemaVersion:1,mode:'append-only',sourceOfTruth:'merge',conflictPolicy:'append-only',...read,pushScope:'contacts:write',authorizePush:requireContactsWrite,prepareMutation:preparePerson,snapshot:snapshotPeople});
registerMobileSyncCollection({moduleKey:'contacts',collectionKey:'contact-addresses',schemaVersion:1,mode:'append-only',sourceOfTruth:'merge',conflictPolicy:'append-only',...read,pushScope:'contacts:write',authorizePush:requireContactsWrite,prepareMutation:prepareAddress,snapshot:snapshotAddresses});
