import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),bookType=z.enum(["small","a4"]);
const movement=z.object({bookType,quantityDelta:z.number().int().refine(v=>v!==0),movementDate:date,source:z.string().max(80).default("manual"),reference:z.string().max(120).nullable().optional(),notes:z.string().max(1000).nullable().optional()});
const issue=z.object({studentId:z.string(),academicYearId:z.string().nullable().optional(),termId:z.string().nullable().optional(),classId:z.string().nullable().optional(),streamId:z.string().nullable().optional(),bookType,quantity:z.number().int().positive(),distributedOn:date,source:z.string().max(80).default("manual"),notes:z.string().max(1000).nullable().optional()});
const bulk=z.object({studentIds:z.array(z.string()).min(1).max(500),academicYearId:z.string().nullable().optional(),termId:z.string().nullable().optional(),classId:z.string().nullable().optional(),streamId:z.string().nullable().optional(),bookType,quantity:z.number().int().positive(),distributedOn:date,notes:z.string().max(1000).nullable().optional()});
function camel(row:Record<string,unknown>){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(row))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return out;}
async function available(runtime:Runtime,org:string,type:string){const q=await runtime.db.query(`SELECT COALESCE((SELECT SUM(quantity_delta) FROM book_stock_movements WHERE organization_id=$1 AND book_type=$2 AND reversed_at IS NULL),0)-COALESCE((SELECT SUM(quantity) FROM book_distributions WHERE organization_id=$1 AND book_type=$2 AND reversed_at IS NULL),0) AS available`,[org,type]);return Number(q.rows[0]?.available??0);}
async function audit(runtime:Runtime,org:string,user:string,action:string,type:string,id:string,after?:unknown){await runtime.db.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,after_data) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[createId("aud"),org,user,action,type,id,after===undefined?null:JSON.stringify(after)]);}

export function createBookRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use("*",requireScope("school:read"));
 r.get("/manifest",c=>c.json({data:{key:"books",name:"Books",version:"2.0.0-node",standalone:true,requiresModules:["school-management"],bookTypes:["small","a4"]}}));
 r.get("/overview",async c=>{const p=c.get("principal"),stock=await runtime.db.query(`SELECT t.book_type,COALESCE(t.stock_in,0)::int stock_in,COALESCE(i.issued,0)::int issued,(COALESCE(t.stock_in,0)-COALESCE(i.issued,0))::int available FROM (SELECT x.book_type,SUM(x.quantity_delta) FILTER(WHERE x.reversed_at IS NULL) stock_in FROM book_stock_movements x WHERE x.organization_id=$1 GROUP BY x.book_type) t LEFT JOIN (SELECT book_type,SUM(quantity) FILTER(WHERE reversed_at IS NULL) issued FROM book_distributions WHERE organization_id=$1 GROUP BY book_type)i USING(book_type)`,[p.organizationId]);const active=await runtime.db.query(`SELECT COUNT(*)::int distributions,COUNT(DISTINCT student_id)::int learners,COALESCE(SUM(quantity),0)::int books_issued FROM book_distributions WHERE organization_id=$1 AND reversed_at IS NULL`,[p.organizationId]);return c.json({data:{stock:stock.rows.map(camel),...camel(active.rows[0]??{})}});});
 r.get("/reference",async c=>{const p=c.get("principal"),[years,classes,streams]=await Promise.all([runtime.db.query(`SELECT id,name,code FROM school_academic_years WHERE organization_id=$1 ORDER BY starts_on DESC`,[p.organizationId]),runtime.db.query(`SELECT id,name,code FROM school_classes WHERE organization_id=$1 AND active=true ORDER BY name`,[p.organizationId]),runtime.db.query(`SELECT id,class_id,name,code FROM school_streams WHERE organization_id=$1 AND active=true ORDER BY name`,[p.organizationId])]);return c.json({data:{academicYears:years.rows.map(camel),classes:classes.rows.map(camel),streams:streams.rows.map(camel),bookTypes:["small","a4"]}});});
 r.get("/students",async c=>{const p=c.get("principal"),classId=c.req.query("classId"),streamId=c.req.query("streamId"),q=c.req.query("q")?.trim().toLowerCase(),params:any[]=[p.organizationId],where=["organization_id=$1","deleted_at IS NULL","status='active'"];if(classId){params.push(classId);where.push(`current_class_id=$${params.length}`)}if(streamId){params.push(streamId);where.push(`current_stream_id=$${params.length}`)}if(q){params.push(`%${q}%`);where.push(`(lower(first_name||' '||last_name) LIKE $${params.length} OR lower(admission_number) LIKE $${params.length})`)}const rows=await runtime.db.query(`SELECT id,admission_number,student_number,first_name,middle_name,last_name,current_class_id,current_stream_id FROM school_students WHERE ${where.join(" AND ")} ORDER BY last_name,first_name LIMIT 500`,params);return c.json({data:rows.rows.map(camel)});});
 r.get("/stock",async c=>{const p=c.get("principal"),q=await runtime.db.query(`WITH types(book_type) AS (VALUES('small'::text),('a4'::text)) SELECT t.book_type,COALESCE(m.stock_in,0)::int stock_in,COALESCE(d.issued,0)::int issued,(COALESCE(m.stock_in,0)-COALESCE(d.issued,0))::int available FROM types t LEFT JOIN (SELECT book_type,SUM(quantity_delta) stock_in FROM book_stock_movements WHERE organization_id=$1 AND reversed_at IS NULL GROUP BY book_type)m USING(book_type) LEFT JOIN (SELECT book_type,SUM(quantity) issued FROM book_distributions WHERE organization_id=$1 AND reversed_at IS NULL GROUP BY book_type)d USING(book_type) ORDER BY t.book_type`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.get("/stock-movements",async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT * FROM book_stock_movements WHERE organization_id=$1 ORDER BY movement_date DESC,created_at DESC LIMIT 500`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/stock-movements",requireScope("school:write"),async c=>{const s=movement.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid stock movement",s.error.flatten());const p=c.get("principal"),v=s.data;if(v.quantityDelta<0&&await available(runtime,p.organizationId,v.bookType)<Math.abs(v.quantityDelta))throw new AppError(409,"INSUFFICIENT_BOOK_STOCK","Stock movement would make available book stock negative");const id=createId("bsm");await runtime.db.query(`INSERT INTO book_stock_movements(id,organization_id,book_type,quantity_delta,movement_date,source,reference,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,v.bookType,v.quantityDelta,v.movementDate,v.source,v.reference??null,v.notes??null,p.userId]);await audit(runtime,p.organizationId,p.userId,"books.stock_movement.created","book_stock_movement",id,v);return c.json({data:{id,...v}},201);});
 r.post("/stock-movements/:id/reverse",requireScope("school:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),body=await c.req.json().catch(()=>({})),q=await runtime.db.query(`UPDATE book_stock_movements SET reversed_at=CURRENT_TIMESTAMP,reversed_by=$1,reversal_reason=$2 WHERE id=$3 AND organization_id=$4 AND reversed_at IS NULL RETURNING *`,[p.userId,String(body.reason??"Reversed"),id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Stock movement not found or already reversed");return c.json({data:camel(q.rows[0])});});
 r.get("/distributions",async c=>{const p=c.get("principal"),studentId=c.req.query("studentId"),classId=c.req.query("classId"),params:any[]=[p.organizationId],where=["d.organization_id=$1"];if(studentId){params.push(studentId);where.push(`d.student_id=$${params.length}`)}if(classId){params.push(classId);where.push(`d.class_id=$${params.length}`)}const q=await runtime.db.query(`SELECT d.*,s.admission_number,s.first_name,s.last_name,c.name AS class_name,st.name AS stream_name FROM book_distributions d JOIN school_students s ON s.id=d.student_id LEFT JOIN school_classes c ON c.id=d.class_id LEFT JOIN school_streams st ON st.id=d.stream_id WHERE ${where.join(" AND ")} ORDER BY d.distributed_on DESC,d.created_at DESC LIMIT 500`,params);return c.json({data:q.rows.map(camel)});});
 r.post("/distributions",requireScope("school:write"),async c=>{const s=issue.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid book distribution",s.error.flatten());const p=c.get("principal"),v=s.data,student=(await runtime.db.query(`SELECT id,current_academic_year_id,current_class_id,current_stream_id FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[v.studentId,p.organizationId])).rows[0];if(!student)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");if(await available(runtime,p.organizationId,v.bookType)<v.quantity)throw new AppError(409,"INSUFFICIENT_BOOK_STOCK","Not enough books are available");const id=createId("bdst");await runtime.db.query(`INSERT INTO book_distributions(id,organization_id,student_id,academic_year_id,term_id,class_id,stream_id,book_type,quantity,distributed_on,source,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[id,p.organizationId,v.studentId,v.academicYearId??student.current_academic_year_id,v.termId??null,v.classId??student.current_class_id,v.streamId??student.current_stream_id,v.bookType,v.quantity,v.distributedOn,v.source,v.notes??null,p.userId]);return c.json({data:{id,...v}},201);});
 r.post("/distributions/bulk",requireScope("school:write"),async c=>{const s=bulk.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid bulk distribution",s.error.flatten());const p=c.get("principal"),v=s.data,total=v.studentIds.length*v.quantity;if(await available(runtime,p.organizationId,v.bookType)<total)throw new AppError(409,"INSUFFICIENT_BOOK_STOCK","Not enough books are available for this batch");const batchId=createId("bbt"),batchNumber=`BOOK-${v.distributedOn.replaceAll("-","")}-${batchId.slice(-6).toUpperCase()}`,client=await runtime.db.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO book_distribution_batches(id,organization_id,batch_number,academic_year_id,term_id,class_id,stream_id,book_type,distributed_on,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[batchId,p.organizationId,batchNumber,v.academicYearId??null,v.termId??null,v.classId??null,v.streamId??null,v.bookType,v.distributedOn,v.notes??null,p.userId]);for(const studentId of v.studentIds){const st=(await client.query(`SELECT current_academic_year_id,current_class_id,current_stream_id FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[studentId,p.organizationId])).rows[0];if(!st)throw new AppError(404,"STUDENT_NOT_FOUND",`Student ${studentId} not found`);await client.query(`INSERT INTO book_distributions(id,organization_id,batch_id,student_id,academic_year_id,term_id,class_id,stream_id,book_type,quantity,distributed_on,source,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'bulk',$12,$13)`,[createId("bdst"),p.organizationId,batchId,studentId,v.academicYearId??st.current_academic_year_id,v.termId??null,v.classId??st.current_class_id,v.streamId??st.current_stream_id,v.bookType,v.quantity,v.distributedOn,v.notes??null,p.userId]);}await client.query("COMMIT");return c.json({data:{batchId,batchNumber,students:v.studentIds.length,totalBooks:total}},201);}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}});
 r.post("/distributions/:id/reverse",requireScope("school:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),body=await c.req.json().catch(()=>({})),q=await runtime.db.query(`UPDATE book_distributions SET reversed_at=CURRENT_TIMESTAMP,reversed_by=$1,reversal_reason=$2 WHERE id=$3 AND organization_id=$4 AND reversed_at IS NULL RETURNING *`,[p.userId,String(body.reason??"Reversed"),id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Distribution not found or already reversed");return c.json({data:camel(q.rows[0])});});
 r.post("/distribution-batches/:id/reverse",requireScope("school:write"),async c=>{const p=c.get("principal"),id=c.req.param("id"),body=await c.req.json().catch(()=>({})),reason=String(body.reason??"Bulk issue reversed"),client=await runtime.db.connect();try{await client.query("BEGIN");const b=await client.query(`UPDATE book_distribution_batches SET reversed_at=CURRENT_TIMESTAMP,reversed_by=$1,reversal_reason=$2 WHERE id=$3 AND organization_id=$4 AND reversed_at IS NULL RETURNING id`,[p.userId,reason,id,p.organizationId]);if(!b.rowCount)throw new AppError(404,"NOT_FOUND","Batch not found or already reversed");await client.query(`UPDATE book_distributions SET reversed_at=CURRENT_TIMESTAMP,reversed_by=$1,reversal_reason=$2 WHERE batch_id=$3 AND organization_id=$4 AND reversed_at IS NULL`,[p.userId,reason,id,p.organizationId]);await client.query("COMMIT");return c.json({data:{id,status:"reversed"}});}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}});
 r.get("/reports/learner",async c=>{const p=c.get("principal"),studentId=c.req.query("studentId");if(!studentId)throw new AppError(422,"VALIDATION_ERROR","studentId is required");const [student,tx]=await Promise.all([runtime.db.query(`SELECT id,admission_number,student_number,first_name,last_name FROM school_students WHERE id=$1 AND organization_id=$2`,[studentId,p.organizationId]),runtime.db.query(`SELECT * FROM book_distributions WHERE organization_id=$1 AND student_id=$2 ORDER BY distributed_on DESC`,[p.organizationId,studentId])]);return c.json({data:{student:camel(student.rows[0]??{}),transactions:tx.rows.map(camel)}});});
 r.get("/reports/class",async c=>{const p=c.get("principal"),classId=c.req.query("classId");if(!classId)throw new AppError(422,"VALIDATION_ERROR","classId is required");const q=await runtime.db.query(`SELECT s.id,s.admission_number,s.student_number,s.first_name||' '||s.last_name AS student_name,COALESCE(SUM(d.quantity) FILTER(WHERE d.book_type='small' AND d.reversed_at IS NULL),0)::int small,COALESCE(SUM(d.quantity) FILTER(WHERE d.book_type='a4' AND d.reversed_at IS NULL),0)::int a4,COALESCE(SUM(d.quantity) FILTER(WHERE d.reversed_at IS NULL),0)::int total FROM school_students s LEFT JOIN book_distributions d ON d.student_id=s.id AND d.organization_id=s.organization_id WHERE s.organization_id=$1 AND s.current_class_id=$2 AND s.deleted_at IS NULL GROUP BY s.id ORDER BY s.last_name,s.first_name`,[p.organizationId,classId]);return c.json({data:{rows:q.rows.map(camel)}});});
 r.get("/reports/unissued",async c=>{const p=c.get("principal"),classId=c.req.query("classId");if(!classId)throw new AppError(422,"VALIDATION_ERROR","classId is required");const q=await runtime.db.query(`SELECT s.id,s.admission_number,s.student_number,s.first_name||' '||s.last_name AS student_name FROM school_students s WHERE s.organization_id=$1 AND s.current_class_id=$2 AND s.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM book_distributions d WHERE d.organization_id=s.organization_id AND d.student_id=s.id AND d.reversed_at IS NULL) ORDER BY s.last_name,s.first_name`,[p.organizationId,classId]);return c.json({data:{rows:q.rows.map(camel)}});});
 r.get("/reports/period",async c=>{const p=c.get("principal"),from=c.req.query("from"),to=c.req.query("to"),params:any[]=[p.organizationId],where=["organization_id=$1","reversed_at IS NULL"];if(from){params.push(from);where.push(`distributed_on>=$${params.length}`)}if(to){params.push(to);where.push(`distributed_on<=$${params.length}`)}const q=await runtime.db.query(`SELECT distributed_on AS date,SUM(quantity)::int quantity,COUNT(*)::int transactions,COUNT(DISTINCT student_id)::int learners FROM book_distributions WHERE ${where.join(" AND ")} GROUP BY distributed_on ORDER BY distributed_on`,params);return c.json({data:{byDay:q.rows.map(camel)}});});
 r.get("/reports/stock",async c=>{const p=c.get("principal"),q=await runtime.db.query(`WITH types(book_type) AS (VALUES('small'::text),('a4'::text)) SELECT t.book_type,COALESCE(m.stock_in,0)::int stock_in,COALESCE(d.issued,0)::int issued,(COALESCE(m.stock_in,0)-COALESCE(d.issued,0))::int available FROM types t LEFT JOIN (SELECT book_type,SUM(quantity_delta) stock_in FROM book_stock_movements WHERE organization_id=$1 AND reversed_at IS NULL GROUP BY book_type)m USING(book_type) LEFT JOIN (SELECT book_type,SUM(quantity) issued FROM book_distributions WHERE organization_id=$1 AND reversed_at IS NULL GROUP BY book_type)d USING(book_type) ORDER BY t.book_type`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 return r;}
