export type ReadinessMetrics={cameras:number;recordingCameras:number;assignedRecordingCameras:number;criticalHealth:number;degradedHealth:number;staleRecording:number;servers:number;onlineServers:number;validationFailed24h:number;validationWarning24h:number;criticalAlerts:number;lowStorageVolumes:number;redundancyProtected:number;backupsEnabled:number;backupsHealthy:number};
export type ReadinessGate={key:string;label:string;status:"passed"|"warning"|"failed";detail:string;required:boolean};
export function evaluateReadiness(x:ReadinessMetrics){const gates:ReadinessGate[]=[];const push=(key:string,label:string,status:ReadinessGate["status"],detail:string,required=true)=>gates.push({key,label,status,detail,required});
 push("cameras","Camera enrollment",x.cameras>0?"passed":"failed",x.cameras>0?`${x.cameras} active camera(s) enrolled`:"No active cameras are enrolled");
 push("nvr","NVR availability",x.onlineServers>0?"passed":"failed",`${x.onlineServers}/${x.servers} NVR(s) currently online`);
 push("assignment","Recording assignment",x.recordingCameras===x.assignedRecordingCameras?"passed":"failed",`${x.assignedRecordingCameras}/${x.recordingCameras} recording-enabled camera(s) assigned to an NVR`);
 push("health","Camera health",x.criticalHealth===0?(x.degradedHealth===0?"passed":"warning"):"failed",x.criticalHealth?`${x.criticalHealth} camera(s) critical`:x.degradedHealth?`${x.degradedHealth} camera(s) degraded`:"No active camera health degradation");
 push("freshness","Recording freshness",x.staleRecording===0?"passed":"failed",x.staleRecording?`${x.staleRecording} recording-enabled camera(s) have stale footage`:"Recording freshness is within policy");
 push("validation","NVR validation",x.validationFailed24h===0?(x.validationWarning24h===0?"passed":"warning"):"failed",x.validationFailed24h?`${x.validationFailed24h} failed validation check(s) in 24h`:x.validationWarning24h?`${x.validationWarning24h} validation warning(s) in 24h`:"No NVR validation failures in 24h");
 push("storage","Storage headroom",x.lowStorageVolumes===0?"passed":"failed",x.lowStorageVolumes?`${x.lowStorageVolumes} storage volume(s) below safe free-space threshold`:"All reported recording volumes have safe headroom");
 push("alerts","Critical alerts",x.criticalAlerts===0?"passed":"failed",x.criticalAlerts?`${x.criticalAlerts} unresolved critical Security alert(s)`:"No unresolved critical Security alerts");
 push("redundancy","NVR redundancy",x.cameras>0&&x.redundancyProtected>=x.cameras?"passed":"warning",`${x.redundancyProtected}/${x.cameras} camera(s) have secondary NVR coverage`,false);
 push("backup","Archive backup",x.backupsEnabled>0&&x.backupsHealthy===x.backupsEnabled?"passed":"warning",x.backupsEnabled?`${x.backupsHealthy}/${x.backupsEnabled} enabled backup target(s) healthy`:"No local/NAS archive backup is enabled",false);
 let score=100;for(const g of gates){if(g.status==="failed")score-=g.required?15:8;else if(g.status==="warning")score-=g.required?6:3}score=Math.max(0,Math.min(100,score));const hardFailure=gates.some(g=>g.required&&g.status==="failed");const status=hardFailure?"not_ready":score>=90?"ready":score>=70?"caution":"not_ready";return{score,status,gates,metrics:{...x}}}
