// @ts-nocheck
import {cameraAudit} from "./audit";
import {enqueueAlertNotifications} from "./governance-service";
import {decideFailover} from "./redundancy-policy";
function uid(prefix:string){return `${prefix}_${crypto.randomUUID().replace(/-/g,"")}`}
function clean(v:any,max=500){return String(v??"").trim().slice(0,max)}

export async function listRedundancy(db:D1Database,organizationId:string){const r=await db.prepare(`SELECT r.*,c.name camera_name,c.location,p.name primary_server_name,p.status primary_status,p.last_seen_at primary_last_seen_at,s.name secondary_server_name,s.status secondary_status,s.last_seen_at secondary_last_seen_at FROM security_camera_redundancy r JOIN security_cameras c ON c.id=r.camera_id JOIN security_camera_servers p ON p.id=r.primary_server_id JOIN security_camera_servers s ON s.id=r.secondary_server_id WHERE r.organization_id=? ORDER BY c.name`).bind(organizationId).all();return r.results||[]}
export async function listFailoverEvents(db:D1Database,organizationId:string,limit=200){const r=await db.prepare(`SELECT e.*,c.name camera_name,fs.name from_server_name,ts.name to_server_name FROM security_camera_failover_events e JOIN security_cameras c ON c.id=e.camera_id LEFT JOIN security_camera_servers fs ON fs.id=e.from_server_id LEFT JOIN security_camera_servers ts ON ts.id=e.to_server_id WHERE e.organization_id=? ORDER BY e.created_at DESC LIMIT ?`).bind(organizationId,Math.max(1,Math.min(1000,limit))).all();return r.results||[]}

export async function saveRedundancy(db:D1Database,organizationId:string,userId:string,cameraId:string,input:any){const camera:any=await db.prepare(`SELECT id,name,server_id FROM security_cameras WHERE id=? AND organization_id=? AND revoked_at IS NULL`).bind(cameraId,organizationId).first();if(!camera)throw new Error("Camera was not found");const primary=clean(input?.primaryServerId,180)||camera.server_id,secondary=clean(input?.secondaryServerId,180);if(!primary||!secondary)throw new Error("Primary and secondary NVRs are required");if(primary===secondary)throw new Error("Primary and secondary NVRs must be different");const servers=await db.prepare(`SELECT id FROM security_camera_servers WHERE organization_id=? AND id IN (?,?)`).bind(organizationId,primary,secondary).all();if((servers.results||[]).length!==2)throw new Error("One of the selected NVRs was not found");const failover=Math.max(30,Math.min(900,Number(input?.failoverAfterSeconds)||90)),failback=Math.max(60,Math.min(3600,Number(input?.failbackAfterSeconds)||300)),failbackEnabled=input?.failbackEnabled===false?0:1,enabled=input?.enabled===false?0:1;await db.batch([db.prepare(`INSERT INTO security_camera_redundancy(camera_id,organization_id,primary_server_id,secondary_server_id,mode,failover_after_seconds,failback_enabled,failback_after_seconds,state,state_changed_at,primary_healthy_since,enabled,updated_by,updated_at) VALUES(?,?,?,?,'automatic',?,?,?,'primary',CURRENT_TIMESTAMP,NULL,?,?,CURRENT_TIMESTAMP) ON CONFLICT(camera_id) DO UPDATE SET primary_server_id=excluded.primary_server_id,secondary_server_id=excluded.secondary_server_id,failover_after_seconds=excluded.failover_after_seconds,failback_enabled=excluded.failback_enabled,failback_after_seconds=excluded.failback_after_seconds,state='primary',state_changed_at=CURRENT_TIMESTAMP,primary_healthy_since=NULL,last_reason='Redundancy configuration updated',enabled=excluded.enabled,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(cameraId,organizationId,primary,secondary,failover,failbackEnabled,failback,enabled,userId),db.prepare(`UPDATE security_cameras SET server_id=? WHERE id=? AND organization_id=?`).bind(primary,cameraId,organizationId)]);await cameraAudit(db,{organizationId,actorId:userId,action:"camera.redundancy.saved",resourceType:"camera",resourceId:cameraId,cameraId,details:{primaryServerId:primary,secondaryServerId:secondary,failoverAfterSeconds:failover,failbackEnabled:Boolean(failbackEnabled),failbackAfterSeconds:failback,enabled:Boolean(enabled)}});return{cameraId,primaryServerId:primary,secondaryServerId:secondary,failoverAfterSeconds:failover,failbackEnabled:Boolean(failbackEnabled),failbackAfterSeconds:failback,enabled:Boolean(enabled)}}

async function switchServer(db:D1Database,row:any,target:string,state:string,reason:string,automatic=true){if(row.server_id===target&&row.state===state)return false;await db.batch([db.prepare(`UPDATE security_cameras SET server_id=? WHERE id=? AND organization_id=?`).bind(target,row.camera_id,row.organization_id),db.prepare(`UPDATE security_camera_redundancy SET state=?,state_changed_at=CURRENT_TIMESTAMP,primary_healthy_since=NULL,last_evaluated_at=CURRENT_TIMESTAMP,last_reason=?,updated_at=CURRENT_TIMESTAMP WHERE camera_id=?`).bind(state,reason,row.camera_id),db.prepare(`INSERT INTO security_camera_failover_events(id,organization_id,camera_id,from_server_id,to_server_id,reason,automatic,state) VALUES(?,?,?,?,?,?,?,?)`).bind(uid("camfail"),row.organization_id,row.camera_id,row.server_id||null,target,reason,automatic?1:0,state)]);await cameraAudit(db,{organizationId:row.organization_id,actorId:automatic?"camera-failover":"security-operator",action:state==="secondary"?"camera.failover.activated":"camera.failover.restored",resourceType:"camera",resourceId:row.camera_id,cameraId:row.camera_id,serverId:target,details:{fromServerId:row.server_id,toServerId:target,reason,automatic}});return true}

async function degradedAlert(db:D1Database,row:any,reason:string){const id=`redundancy:${row.camera_id}:exhausted`,now=new Date().toISOString();await db.prepare(`INSERT INTO security_camera_alerts(id,organization_id,camera_id,server_id,alert_type,severity,status,message,details_json,first_seen_at,last_seen_at) VALUES(?,?,?,NULL,'camera_redundancy_exhausted','critical','open',?,?,?,?) ON CONFLICT(id) DO UPDATE SET severity='critical',status='open',message=excluded.message,details_json=excluded.details_json,last_seen_at=excluded.last_seen_at,resolved_at=NULL`).bind(id,row.organization_id,row.camera_id,`No healthy NVR is available for ${row.camera_name||row.camera_id}`,JSON.stringify({primaryServerId:row.primary_server_id,secondaryServerId:row.secondary_server_id,reason}),now,now).run();const alert=await db.prepare(`SELECT * FROM security_camera_alerts WHERE id=?`).bind(id).first<any>();if(alert)await enqueueAlertNotifications(db,row.organization_id,alert)}
async function resolveDegradedAlert(db:D1Database,cameraId:string){await db.prepare(`UPDATE security_camera_alerts SET status='resolved',resolved_at=CURRENT_TIMESTAMP,last_seen_at=CURRENT_TIMESTAMP WHERE id=? AND status!='resolved'`).bind(`redundancy:${cameraId}:exhausted`).run()}

export async function evaluateFailover(db:D1Database){const rows=await db.prepare(`SELECT r.*,c.server_id,c.name camera_name,p.status primary_status,p.last_seen_at primary_last_seen,s.status secondary_status,s.last_seen_at secondary_last_seen FROM security_camera_redundancy r JOIN security_cameras c ON c.id=r.camera_id JOIN security_camera_servers p ON p.id=r.primary_server_id JOIN security_camera_servers s ON s.id=r.secondary_server_id WHERE r.enabled=1 AND c.revoked_at IS NULL`).all<any>();let failedOver=0,failedBack=0,degraded=0,unchanged=0,recoveryStarted=0;const now=Date.now();for(const row of rows.results){const d=decideFailover({state:row.state==="secondary"?"secondary":"primary",primaryStatus:row.primary_status,primaryLastSeenAt:row.primary_last_seen,secondaryStatus:row.secondary_status,secondaryLastSeenAt:row.secondary_last_seen,failoverAfterSeconds:Number(row.failover_after_seconds)||90,failbackEnabled:Boolean(row.failback_enabled),failbackAfterSeconds:Number(row.failback_after_seconds)||300,primaryHealthySince:row.primary_healthy_since,nowMs:now});if(d.action==="failover"){await resolveDegradedAlert(db,row.camera_id);if(await switchServer(db,row,row.secondary_server_id,"secondary",d.reason,true))failedOver++;continue}if(d.action==="failback"){await resolveDegradedAlert(db,row.camera_id);if(await switchServer(db,row,row.primary_server_id,"primary",d.reason,true))failedBack++;continue}if(d.action==="begin_primary_recovery"){await resolveDegradedAlert(db,row.camera_id);await db.prepare(`UPDATE security_camera_redundancy SET primary_healthy_since=CURRENT_TIMESTAMP,last_evaluated_at=CURRENT_TIMESTAMP,last_reason=? WHERE camera_id=?`).bind(d.reason,row.camera_id).run();recoveryStarted++;continue}if(d.action==="clear_primary_recovery"){await db.prepare(`UPDATE security_camera_redundancy SET primary_healthy_since=NULL,last_evaluated_at=CURRENT_TIMESTAMP,last_reason=? WHERE camera_id=?`).bind(d.reason,row.camera_id).run();unchanged++;continue}if(d.action==="degraded"){await degradedAlert(db,row,d.reason);await db.prepare(`UPDATE security_camera_redundancy SET last_evaluated_at=CURRENT_TIMESTAMP,last_reason=? WHERE camera_id=?`).bind(d.reason,row.camera_id).run();degraded++;continue}await resolveDegradedAlert(db,row.camera_id);await db.prepare(`UPDATE security_camera_redundancy SET last_evaluated_at=CURRENT_TIMESTAMP,last_reason=? WHERE camera_id=?`).bind(d.reason,row.camera_id).run();unchanged++}return{evaluated:rows.results.length,failedOver,failedBack,recoveryStarted,degraded,unchanged}}

export async function manualFailover(db:D1Database,organizationId:string,userId:string,cameraId:string,target:"primary"|"secondary",reason?:string){const row:any=await db.prepare(`SELECT r.*,c.server_id,c.name camera_name FROM security_camera_redundancy r JOIN security_cameras c ON c.id=r.camera_id WHERE r.camera_id=? AND r.organization_id=?`).bind(cameraId,organizationId).first();if(!row)throw new Error("Camera redundancy is not configured");const serverId=target==="secondary"?row.secondary_server_id:row.primary_server_id;await switchServer(db,row,serverId,target,clean(reason,500)||`Manual ${target} selection`,false);await cameraAudit(db,{organizationId,actorId:userId,action:"camera.failover.manual",resourceType:"camera",resourceId:cameraId,cameraId,serverId,details:{target,reason:clean(reason,500)||null}});return{cameraId,state:target,serverId}}

export async function recordValidation(db:D1Database,organizationId:string,input:any){const id=uid("camval"),status=["passed","warning","failed"].includes(input?.status)?input.status:"warning";await db.prepare(`INSERT INTO security_camera_validation_runs(id,organization_id,server_id,camera_id,check_type,status,message,details_json) VALUES(?,?,?,?,?,?,?,?)`).bind(id,organizationId,clean(input?.serverId,180)||null,clean(input?.cameraId,180)||null,clean(input?.checkType,100)||"unknown",status,clean(input?.message,500)||null,JSON.stringify(input?.details||{})).run();return{id,status}}
export async function validationSummary(db:D1Database,organizationId:string){const [r,e]=await db.batch([db.prepare(`SELECT v.*,s.name server_name,c.name camera_name FROM security_camera_validation_runs v LEFT JOIN security_camera_servers s ON s.id=v.server_id LEFT JOIN security_cameras c ON c.id=v.camera_id WHERE v.organization_id=? ORDER BY v.created_at DESC LIMIT 250`).bind(organizationId),db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) failed,SUM(CASE WHEN status='warning' THEN 1 ELSE 0 END) warning,SUM(CASE WHEN status='passed' THEN 1 ELSE 0 END) passed FROM security_camera_validation_runs WHERE organization_id=? AND created_at>=datetime('now','-24 hours')`).bind(organizationId)]);return{runs:r.results||[],summary:e.results?.[0]||{}}}
