import {useState} from "react";
import {SafeAreaView,StatusBar,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {OverviewTab} from "./OverviewTab";
import {ExamsTab} from "./ExamsTab";
import {MarksTab} from "./MarksTab";
import {ReportsTab} from "./ReportsTab";
import {SetupTab} from "./SetupTab";
type Tab="overview"|"exams"|"marks"|"reports"|"setup";
export function ExamsWorkspaceScreen({session,onSession,onBack}:{session:MobileSession;onSession:SessionUpdater;onBack:()=>void}){const[tab,setTab]=useState<Tab>("overview");const render=()=>tab==="overview"?<OverviewTab session={session} onSession={onSession}/>:tab==="exams"?<ExamsTab session={session} onSession={onSession}/>:tab==="marks"?<MarksTab session={session} onSession={onSession}/>:tab==="reports"?<ReportsTab session={session} onSession={onSession}/>:<SetupTab session={session} onSession={onSession}/>;const tabs:[Tab,string,string][]=[["overview","Overview","⌂"],["exams","Exams","E"],["marks","Marks","✓"],["reports","Reports","R"],["setup","Setup","⚙"]];return <SafeAreaView style={s.root}><StatusBar barStyle="light-content" backgroundColor="#102b42"/><View style={s.head}><TouchableOpacity style={s.back} onPress={onBack}><Text style={s.backText}>←</Text></TouchableOpacity><View><Text style={s.eyebrow}>LEDGERLY MOBILE · MODULE 04</Text><Text style={s.title}>Examinations</Text></View><View style={s.badge}><Text style={s.badgeText}>PLE</Text></View></View><View style={s.body}>{render()}</View><View style={s.nav}>{tabs.map(([id,label,icon])=><TouchableOpacity key={id} onPress={()=>setTab(id)} style={s.navItem}><View style={[s.navIcon,tab===id&&s.navIconOn]}><Text style={[s.navGlyph,tab===id&&s.navGlyphOn]}>{icon}</Text></View><Text style={[s.navText,tab===id&&s.navTextOn]}>{label}</Text></TouchableOpacity>)}</View></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f4f7f5"},head:{height:74,backgroundColor:"#102b42",flexDirection:"row",alignItems:"center",paddingHorizontal:14},back:{width:38,height:38,borderRadius:13,backgroundColor:"#1d435f",alignItems:"center",justifyContent:"center",marginRight:12},backText:{fontSize:21,color:"white"},eyebrow:{fontSize:7,fontWeight:"900",letterSpacing:1.1,color:"#78bbdf"},title:{fontSize:20,fontWeight:"900",color:"white",marginTop:2},badge:{marginLeft:"auto",borderRadius:14,backgroundColor:"#dceefa",paddingHorizontal:10,paddingVertical:7},badgeText:{fontSize:9,fontWeight:"900",color:"#1c6e99"},body:{flex:1},nav:{height:72,backgroundColor:"white",borderTopWidth:1,borderTopColor:"#dde6e2",flexDirection:"row",paddingHorizontal:5,paddingTop:7},navItem:{flex:1,alignItems:"center"},navIcon:{width:31,height:28,borderRadius:10,alignItems:"center",justifyContent:"center"},navIconOn:{backgroundColor:"#e4f1f7"},navGlyph:{fontSize:12,fontWeight:"900",color:"#8a9992"},navGlyphOn:{color:"#2178a5"},navText:{fontSize:7.5,fontWeight:"900",color:"#8b9993",marginTop:3},navTextOn:{color:"#2178a5"}});
