import type {RefObject} from "react";
import type {Camera} from "react-native-vision-camera";
import {CameraSpool,OfflineStore} from "../../native";
import type {CameraConfig,CameraRegistration,CameraRuntimeState} from "./types";
const QUEUE_KEY="camera.segment.queue.v1",MAX_SPOOL_FILES=180;
type Pending={path:string;startedAt:string;endedAt:string;attempts:number};
async function readQueue():Promise<Pending[]>{const raw=await OfflineStore.getSecure(QUEUE_KEY);if(!raw)return[];try{return JSON.parse(raw) as Pending[]}catch{return[]}}
async function writeQueue(rows:Pending[]){await OfflineStore.putSecure(QUEUE_KEY,JSON.stringify(rows.slice(-MAX_SPOOL_FILES)))}
function uri(path:string){return path.startsWith("file://")?path:`file://${path}`}
export class CameraSegmentRuntime{
 private running=false;private stopping=false;private timer:any=null;private queue:Pending[]=[];private state:CameraRuntimeState={recording:false,uploading:false,pendingSegments:0};
 constructor(private camera:RefObject<Camera|null>,private reg:CameraRegistration,private config:CameraConfig,private onState:(state:CameraRuntimeState)=>void){}
 private emit(patch:Partial<CameraRuntimeState>={}){this.state={...this.state,...patch,pendingSegments:this.queue.length};this.onState(this.state)}
 private async refreshStats(patch:Partial<CameraRuntimeState>={}){const stats=await CameraSpool.stats().catch(()=>null);this.emit(stats?{...patch,spoolBytes:stats.bytes,spoolFreeBytes:stats.freeBytes,bufferPressure:stats.pressure}:patch)}
 private async restoreQueue(){const saved=await readQueue(),spooled=await CameraSpool.list().catch(()=>[]),known=new Set(saved.map(x=>x.path));for(const item of spooled){if(!known.has(item.path)){const at=new Date(item.modifiedAt||Date.now()).toISOString();saved.push({path:item.path,startedAt:at,endedAt:at,attempts:0})}}const available:Pending[]=[];for(const row of saved){if(await CameraSpool.exists(row.path).catch(()=>false))available.push(row)}this.queue=available.slice(-MAX_SPOOL_FILES);await writeQueue(this.queue);await this.refreshStats()}
 async start(){if(this.running||!this.config.recording.enabled||!this.config.transport.ingestUrl)return;this.running=true;this.stopping=false;await this.restoreQueue();void this.flush();void this.recordNext()}
 async drain(){await this.restoreQueue();await this.flush()}
 async stop(){this.stopping=true;this.running=false;if(this.timer)clearTimeout(this.timer);this.timer=null;try{await this.camera.current?.stopRecording()}catch{}await this.refreshStats({recording:false})}
 update(config:CameraConfig){this.config=config;if(config.transport.ingestUrl)void this.flush()}
 private async recordNext(){if(!this.running||this.stopping)return;if(!this.camera.current){this.timer=setTimeout(()=>void this.recordNext(),500);return}if(!this.config.transport.ingestUrl||!this.config.recording.enabled)return;const startedAt=new Date().toISOString();try{this.emit({recording:true,lastError:undefined});this.camera.current.startRecording({onRecordingFinished:video=>{void this.finished(video.path,startedAt)},onRecordingError:error=>{this.emit({recording:false,lastError:error.message});if(this.running)this.timer=setTimeout(()=>void this.recordNext(),2000)}});const seconds=Math.max(10,Math.min(60,Number(this.config.capture.segmentSeconds)||20));this.timer=setTimeout(()=>{void this.camera.current?.stopRecording().catch(()=>{})},seconds*1000)}catch(e){this.emit({recording:false,lastError:e instanceof Error?e.message:String(e)});this.timer=setTimeout(()=>void this.recordNext(),2500)}}
 private async finished(sourcePath:string,startedAt:string){this.emit({recording:false});try{const stashed=await CameraSpool.stash(sourcePath,MAX_SPOOL_FILES),evicted=new Set(stashed.evicted||[]);if(evicted.size)this.queue=this.queue.filter(x=>!evicted.has(x.path));this.queue.push({path:stashed.path,startedAt,endedAt:new Date().toISOString(),attempts:0});await writeQueue(this.queue);await this.refreshStats({bufferPressure:Boolean(stashed.pressure)});void this.flush()}catch(e){await this.refreshStats({lastError:e instanceof Error?e.message:String(e)})}finally{if(this.running&&!this.stopping)this.timer=setTimeout(()=>void this.recordNext(),250)}}
 private async upload(row:Pending){const target=this.config.transport.ingestUrl;if(!target)throw new Error("Local NVR ingest address is unavailable");const form=new FormData();form.append("file",{uri:uri(row.path),type:"video/mp4",name:"segment.mp4"} as any);const response=await fetch(target,{method:"POST",headers:{Accept:"application/json",Authorization:`Device ${this.reg.deviceId}.${this.reg.credential}`,"X-Ledgerly-Segment-Start":row.startedAt,"X-Ledgerly-Segment-End":row.endedAt},body:form});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`NVR returned ${response.status}`)}
 async flush(){if(this.state.uploading||!this.queue.length||!this.config.transport.ingestUrl){if(!this.state.uploading)void this.refreshStats();return}this.emit({uploading:true});try{while(this.queue.length&&this.config.transport.ingestUrl){const row=this.queue[0];const exists=await CameraSpool.exists(row.path).catch(()=>false);if(!exists){this.queue.shift();await writeQueue(this.queue);continue}try{await this.upload(row);await CameraSpool.remove(row.path).catch(()=>false);this.queue.shift();await writeQueue(this.queue);await this.refreshStats({lastUploadedAt:new Date().toISOString(),lastError:undefined})}catch(e){row.attempts++;await writeQueue(this.queue);await this.refreshStats({lastError:e instanceof Error?e.message:String(e)});break}}}finally{this.emit({uploading:false})}}
}
