import { createHash } from "node:crypto";
import { Hono } from "hono";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function text(value: unknown) { return value == null ? "" : String(value); }
function amount(currency: string, minor: unknown) { return `${currency} ${(Number(minor ?? 0)/100).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`; }

export function createDocumentOutputRoutes(runtime: Runtime) {
  const router=new Hono<AppEnv>();
  router.get("/:id/pdf",requireScope("documents:read"),async(c)=>{
    const p=c.get("principal"),id=c.req.param("id");
    const d=(await runtime.db.query<any>(`SELECT d.type,d.number,d.issue_date::text AS "issueDate",d.due_date::text AS "dueDate",d.currency,d.subtotal_minor::float8 AS "subtotalMinor",d.tax_minor::float8 AS "taxMinor",d.total_minor::float8 AS "totalMinor",d.status,c.name AS "contactName",o.name AS "organizationName",o.legal_name AS "legalName",o.address,o.tax_registration_number AS "taxNumber",o.branding FROM documents d JOIN contacts c ON c.id=d.contact_id AND c.organization_id=d.organization_id JOIN organizations o ON o.id=d.organization_id WHERE d.id=$1 AND d.organization_id=$2`,[id,p.organizationId])).rows[0];
    if(!d)throw new AppError(404,"NOT_FOUND","Document not found");
    const lines=(await runtime.db.query<any>(`SELECT description,quantity_micros::float8 AS "quantityMicros",unit_price_minor::float8 AS "unitPriceMinor",tax_minor::float8 AS "taxMinor",total_minor::float8 AS "totalMinor" FROM document_lines WHERE document_id=$1 AND organization_id=$2 ORDER BY created_at,id`,[id,p.organizationId])).rows;
    const branding=d.branding??{},address=d.address??{},pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),page=pdf.addPage([595,842]),accent=rgb(.04,.32,.25),margin=44,width=595;
    let y=790; let logo:any;
    try{const match=text(branding.logoDataUrl).match(/^data:image\/(png|jpeg);base64,(.+)$/);if(match)logo=match[1]==="png"?await pdf.embedPng(match[2]!):await pdf.embedJpg(match[2]!);}catch{}
    if(logo)page.drawImage(logo,{x:margin,y:y-45,width:90,height:45});const ox=logo?150:margin;
    page.drawText(text(d.legalName||d.organizationName),{x:ox,y,font:bold,size:16,color:accent});
    [address.formatted,d.taxNumber&&`Tax ID: ${d.taxNumber}`,branding.email,branding.phone,branding.website].filter(Boolean).slice(0,3).forEach((v,i)=>page.drawText(text(v).slice(0,70),{x:ox,y:y-15-i*10,font,size:7,color:rgb(.4,.45,.5)}));
    y-=70;page.drawLine({start:{x:margin,y},end:{x:width-margin,y},thickness:2,color:accent});y-=32;
    page.drawText(text(d.type).replaceAll("_"," ").toUpperCase(),{x:margin,y,font:bold,size:22,color:accent});page.drawText(text(d.number),{x:width-margin-bold.widthOfTextAtSize(text(d.number),13),y:y+4,font:bold,size:13});
    y-=38;page.drawText("BILL TO",{x:margin,y,font:bold,size:7,color:rgb(.45,.5,.55)});page.drawText(text(d.contactName),{x:margin,y:y-17,font:bold,size:12});page.drawText(`Issue: ${d.issueDate}   Due: ${d.dueDate||"-"}`,{x:340,y,font,size:8});page.drawText(`Status: ${text(d.status).toUpperCase()}`,{x:340,y:y-16,font:bold,size:8,color:accent});
    y-=64;const widths=[235,45,85,70,72],heads=["Description","Qty","Unit price","Tax","Total"];page.drawRectangle({x:margin,y:y-18,width:width-margin*2,height:24,color:accent});let x=margin;heads.forEach((h,i)=>{page.drawText(h,{x:x+5,y:y-9,font:bold,size:7,color:rgb(1,1,1)});x+=widths[i]!});y-=25;
    for(const [i,l] of lines.entries()){if(y<95){y=790;pdf.addPage([595,842]);}if(i%2)page.drawRectangle({x:margin,y:y-17,width:width-margin*2,height:21,color:rgb(.96,.97,.98)});const vals=[text(l.description).slice(0,42),String(Number(l.quantityMicros)/1e6),amount(d.currency,l.unitPriceMinor),amount(d.currency,l.taxMinor),amount(d.currency,l.totalMinor)];let xx=margin;vals.forEach((v,j)=>{page.drawText(v.slice(0,18+(j===0?24:0)),{x:xx+5,y:y-8,font:j===4?bold:font,size:7});xx+=widths[j]!});y-=21;}
    y-=20;for(const[label,val]of[["Subtotal",d.subtotalMinor],["Tax",d.taxMinor]] as const){page.drawText(label,{x:370,y,font,size:9});const v=amount(d.currency,val);page.drawText(v,{x:width-margin-font.widthOfTextAtSize(v,9),y,font,size:9});y-=18;}
    page.drawRectangle({x:360,y:y-10,width:width-margin-360,height:30,color:accent});page.drawText("TOTAL",{x:370,y,font:bold,size:10,color:rgb(1,1,1)});const total=amount(d.currency,d.totalMinor);page.drawText(total,{x:width-margin-bold.widthOfTextAtSize(total,10),y,font:bold,size:10,color:rgb(1,1,1)});if(branding.footer)page.drawText(text(branding.footer).slice(0,110),{x:margin,y:35,font,size:7,color:rgb(.4,.45,.5)});
    const bytes=await pdf.save();c.header("Content-Type","application/pdf");c.header("Content-Disposition",`inline; filename="${text(d.number).replaceAll('"','')}.pdf"`);return c.body(bytes);
  });
  return router;
}

const attachmentRequest=z.object({entityType:z.string().min(1).max(80),entityId:z.string().min(1),filename:z.string().min(1).max(255),contentType:z.string().min(1).max(150),sizeBytes:z.number().int().positive().max(25_000_000)});
const deliveryInput=z.object({entityType:z.enum(["document","order"]),entityId:z.string(),channel:z.enum(["email","download"]),recipient:z.string().min(1)});
const claimInput=z.object({employeeId:z.string(),number:z.string().min(1),claimDate:z.iso.date(),currency:z.string().length(3).transform(v=>v.toUpperCase()),lines:z.array(z.object({type:z.enum(["expense","mileage","per_diem","card"]),expenseDate:z.iso.date(),description:z.string().min(1),accountId:z.string(),amountMinor:z.number().int().nonnegative(),taxMinor:z.number().int().nonnegative().default(0),mileageMicros:z.number().int().optional(),perDiemDays:z.number().int().optional(),projectId:z.string().optional(),receiptAttachmentId:z.string().optional()})).min(1)});

export function createDocumentOperationsRoutes(runtime: Runtime) {
  const router=new Hono<AppEnv>();
  router.post("/attachments/presign",requireScope("documents:write"),async(c)=>{const parsed=attachmentRequest.safeParse(await c.req.json());if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid attachment",parsed.error.flatten());const p=c.get("principal"),id=createId("att"),key=`attachments/${p.organizationId}/${id}/${parsed.data.filename}`;await runtime.db.query(`INSERT INTO document_attachments(id,organization_id,entity_type,entity_id,filename,content_type,object_key,size_bytes,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,parsed.data.entityType,parsed.data.entityId,parsed.data.filename,parsed.data.contentType,key,parsed.data.sizeBytes,p.userId]);return c.json({data:{id,objectKey:key,uploadMethod:"PUT",uploadUrl:`/api/v1/operations/attachments/${id}/content`}},201);});
  router.put("/attachments/:id/content",requireScope("documents:write"),async(c)=>{const p=c.get("principal"),record=(await runtime.db.query<{objectKey:string;sizeBytes:number;contentType:string}>(`SELECT object_key AS "objectKey",size_bytes::float8 AS "sizeBytes",content_type AS "contentType" FROM document_attachments WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId])).rows[0];if(!record)throw new AppError(404,"NOT_FOUND","Attachment not found");const bytes=new Uint8Array(await c.req.arrayBuffer());if(bytes.byteLength>record.sizeBytes)throw new AppError(413,"ATTACHMENT_TOO_LARGE","Uploaded attachment exceeds the declared size");await runtime.storage.put(record.objectKey,bytes,record.contentType);const sha=createHash("sha256").update(bytes).digest("hex");await runtime.db.query(`UPDATE document_attachments SET size_bytes=$1,sha256=$2,uploaded_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND organization_id=$4`,[bytes.byteLength,sha,c.req.param("id"),p.organizationId]);return c.json({data:{id:c.req.param("id"),uploaded:true,sizeBytes:bytes.byteLength,sha256:sha}});});
  router.get("/attachments/:id/content",requireScope("documents:read"),async(c)=>{const p=c.get("principal"),record=(await runtime.db.query<{objectKey:string;contentType:string;filename:string}>(`SELECT object_key AS "objectKey",content_type AS "contentType",filename FROM document_attachments WHERE id=$1 AND organization_id=$2 AND uploaded_at IS NOT NULL`,[c.req.param("id"),p.organizationId])).rows[0];if(!record)throw new AppError(404,"NOT_FOUND","Attachment not found");const bytes=await runtime.storage.get(record.objectKey);if(!bytes)throw new AppError(404,"FILE_NOT_FOUND","Attachment file not found");c.header("Content-Type",record.contentType);c.header("Content-Disposition",`attachment; filename="${record.filename.replaceAll('"','')}"`);return c.body(bytes);});
  router.post("/deliveries",requireScope("documents:write"),async(c)=>{const parsed=deliveryInput.safeParse(await c.req.json());if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid delivery",parsed.error.flatten());const p=c.get("principal"),id=createId("dlv");await runtime.db.query(`INSERT INTO document_deliveries(id,organization_id,entity_type,entity_id,channel,recipient,status,sent_at,created_by) VALUES($1,$2,$3,$4,$5,$6,'sent',CURRENT_TIMESTAMP,$7)`,[id,p.organizationId,parsed.data.entityType,parsed.data.entityId,parsed.data.channel,parsed.data.recipient,p.userId]);return c.json({data:{id,status:"sent"}},201);});
  router.post("/deliveries/:id/open",requireScope("documents:read"),async(c)=>{const p=c.get("principal");await runtime.db.query(`UPDATE document_deliveries SET status='opened',opened_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2`,[c.req.param("id"),p.organizationId]);return c.json({data:{id:c.req.param("id"),status:"opened"}});});
  router.post("/expenses",requireScope("documents:write"),async(c)=>{const parsed=claimInput.safeParse(await c.req.json());if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid expense claim",parsed.error.flatten());const p=c.get("principal"),total=parsed.data.lines.reduce((n,l)=>n+l.amountMinor+l.taxMinor,0);if(!Number.isSafeInteger(total))throw new AppError(422,"INVALID_AMOUNT","Expense total is too large");const ids=[...new Set(parsed.data.lines.map(l=>l.accountId))],accounts=await runtime.db.query(`SELECT id FROM accounts WHERE organization_id=$1 AND id=ANY($2::text[]) AND active=true AND allow_posting=true`,[p.organizationId,ids]);if(accounts.rows.length!==ids.length)throw new AppError(422,"INVALID_ACCOUNT","Expense lines contain an invalid account");const id=createId("exp"),client=await runtime.db.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO expense_claims(id,organization_id,employee_id,number,claim_date,currency,total_minor,created_by) VALUES($1,$2,$3,$4,$5::date,$6,$7,$8)`,[id,p.organizationId,parsed.data.employeeId,parsed.data.number,parsed.data.claimDate,parsed.data.currency,total,p.userId]);for(const l of parsed.data.lines)await client.query(`INSERT INTO expense_claim_lines(id,organization_id,claim_id,type,expense_date,description,account_id,amount_minor,tax_minor,mileage_micros,per_diem_days,project_id,receipt_attachment_id) VALUES($1,$2,$3,$4,$5::date,$6,$7,$8,$9,$10,$11,$12,$13)`,[createId("exl"),p.organizationId,id,l.type,l.expenseDate,l.description,l.accountId,l.amountMinor,l.taxMinor,l.mileageMicros??null,l.perDiemDays??null,l.projectId??null,l.receiptAttachmentId??null]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}return c.json({data:{id,status:"draft",totalMinor:total}},201);});
  router.post("/expenses/:id/:action",requireScope("documents:write"),async(c)=>{const action=c.req.param("action"),map:Record<string,[string,string]>={submit:["draft","submitted"],approve:["submitted","approved"],reject:["submitted","rejected"],reimburse:["approved","reimbursed"]},rule=map[action];if(!rule)throw new AppError(404,"NOT_FOUND","Unknown expense action");const p=c.get("principal"),result=await runtime.db.query(`UPDATE expense_claims SET status=$1,submitted_at=CASE WHEN $1='submitted' THEN CURRENT_TIMESTAMP ELSE submitted_at END,approved_by=CASE WHEN $1='approved' THEN $2 ELSE approved_by END,approved_at=CASE WHEN $1='approved' THEN CURRENT_TIMESTAMP ELSE approved_at END,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND organization_id=$4 AND status=$5 RETURNING id`,[rule[1],p.userId,c.req.param("id"),p.organizationId,rule[0]]);if(!result.rowCount)throw new AppError(409,"INVALID_STATE","Expense action is not allowed");return c.json({data:{id:c.req.param("id"),status:rule[1]}});});
  return router;
}
