// @ts-nocheck
import { createId } from "../../../src/lib/ids";
import { AppError } from "../../../src/lib/errors";

export const PLE_BANDS = [
  { grade:"D1", label:"Distinction", min_mark:90, max_mark:100, points:1, color_hex:"#059669", sort_order:1 },
  { grade:"D2", label:"Distinction", min_mark:80, max_mark:89,  points:2, color_hex:"#10B981", sort_order:2 },
  { grade:"C3", label:"Credit",      min_mark:70, max_mark:79,  points:3, color_hex:"#1D4ED8", sort_order:3 },
  { grade:"C4", label:"Credit",      min_mark:60, max_mark:69,  points:4, color_hex:"#3B82F6", sort_order:4 },
  { grade:"C5", label:"Credit",      min_mark:55, max_mark:59,  points:5, color_hex:"#60A5FA", sort_order:5 },
  { grade:"C6", label:"Credit",      min_mark:50, max_mark:54,  points:6, color_hex:"#93C5FD", sort_order:6 },
  { grade:"P7", label:"Pass",        min_mark:45, max_mark:49,  points:7, color_hex:"#D97706", sort_order:7 },
  { grade:"P8", label:"Pass",        min_mark:40, max_mark:44,  points:8, color_hex:"#F59E0B", sort_order:8 },
  { grade:"F9", label:"Fail",        min_mark:0,  max_mark:39,  points:9, color_hex:"#DC2626", sort_order:9 },
];

const DEFAULT_CT = [
  { min_agg:4,  max_agg:12, comment_text:"Excellent performance! This student has demonstrated outstanding academic ability — Division 1. Keep up the great work." },
  { min_agg:13, max_agg:24, comment_text:"Very good performance — Division 2. This student is performing above average. Consistent effort will lead to even better results." },
  { min_agg:24, max_agg:29, comment_text:"Good performance — Division 3. The student is progressing well. With more effort, higher results are attainable." },
  { min_agg:30, max_agg:34, comment_text:"Fair performance — Division 4. The student needs to work harder, especially in weak subjects. Regular revision is highly encouraged." },
  { min_agg:35, max_agg:99, comment_text:"Below average performance. The student did not meet the minimum standard. Immediate intervention and parental support are needed." },
];
const DEFAULT_HT = [
  { min_agg:4,  max_agg:12, comment_text:"Exceptional results — Division 1. We are very proud of this student's achievement. Continue to soar high." },
  { min_agg:13, max_agg:24, comment_text:"Commendable performance — Division 2. This student shows real promise. We encourage continued dedication to studies." },
  { min_agg:24, max_agg:29, comment_text:"Satisfactory performance — Division 3. The school believes this student can achieve much more with sustained commitment." },
  { min_agg:30, max_agg:34, comment_text:"Average performance — Division 4. We urge the student to take studies more seriously and participate actively in class." },
  { min_agg:35, max_agg:99, comment_text:"Ungraded (U). The school calls upon parents and the student to seek immediate academic support and remediation." },
];
const AGGREGATE_SUBJECT_COUNT = 4;
const PLE_MIN_SUBJECTS = 4;
const now = () => new Date().toISOString();

function asBool(v:any){return Number(v||0)!==0}
function pickComment(aggregate:number|null, rules:any[]){if(aggregate==null)return null;return rules.find(r=>aggregate>=Number(r.min_agg)&&aggregate<=Number(r.max_agg))?.comment_text??null}
function computeGrade(marks:number|null,maxMark:number,bands:any[]){
  if(marks==null)return{grade:null,grade_points:null,label:null,percentage:null};
  const pct=maxMark>0?Math.round((marks/maxMark)*1000)/10:0;
  const band=bands.find(b=>pct>=Number(b.min_mark)&&pct<=Number(b.max_mark))||bands[bands.length-1]||PLE_BANDS[PLE_BANDS.length-1];
  return{grade:band.grade,grade_points:band.points,label:band.label,percentage:pct};
}
function selectCountedSubjectIds(sat:any[],count=AGGREGATE_SUBJECT_COUNT){
  if(sat.length<=count)return new Set(sat.map(s=>s.subject_id));
  return new Set([...sat].sort((a,b)=>(Number(a.grade_points??999)-Number(b.grade_points??999))).slice(0,count).map(s=>s.subject_id));
}
function computeDivision(aggregate:number|null, sat:number, totalConfigured:number, missingCount=0){
  if(missingCount>0)return"X";
  const required=totalConfigured>0?totalConfigured:PLE_MIN_SUBJECTS;
  if(sat<required||aggregate==null)return"U";
  if(aggregate<=12)return"1";if(aggregate<=24)return"2";if(aggregate<=29)return"3";if(aggregate<=34)return"4";return"U";
}
async function requireExam(db:D1Database,org:string,id:string){const row=await db.prepare("SELECT * FROM exm_exams WHERE id=? AND organization_id=?").bind(id,org).first();if(!row)throw new AppError(404,"EXAM_NOT_FOUND","Exam not found");return row}
async function requireSchoolRef(db:D1Database,org:string,table:string,id:string|undefined|null,label:string){if(!id)return null;const allowed=new Set(["school_terms","school_academic_years","school_classes","school_streams","school_subjects"]);if(!allowed.has(table))throw new Error("Unsafe exam reference");const row=await db.prepare(`SELECT * FROM ${table} WHERE id=? AND organization_id=?`).bind(id,org).first();if(!row)throw new AppError(422,"INVALID_REFERENCE",`${label} does not belong to this school`);return row}
async function bandsForExam(db:D1Database,org:string,examId:string){const exam=await requireExam(db,org,examId);if(!exam.grading_scale_id)return PLE_BANDS;const r=await db.prepare("SELECT * FROM exm_grade_bands WHERE grading_scale_id=? AND organization_id=? ORDER BY sort_order").bind(exam.grading_scale_id,org).all();return r.results.length?r.results:PLE_BANDS}

export async function overview(db:D1Database,org:string){
 const [exams,marking,published,marks,cards]=await Promise.all([
  db.prepare("SELECT COUNT(*) n FROM exm_exams WHERE organization_id=?").bind(org).first<any>(),
  db.prepare("SELECT COUNT(*) n FROM exm_exams WHERE organization_id=? AND status='marking'").bind(org).first<any>(),
  db.prepare("SELECT COUNT(*) n FROM exm_exams WHERE organization_id=? AND status='published'").bind(org).first<any>(),
  db.prepare("SELECT COUNT(*) n FROM exm_marks WHERE organization_id=?").bind(org).first<any>(),
  db.prepare("SELECT COUNT(*) n FROM exm_report_cards WHERE organization_id=?").bind(org).first<any>()]);
 return{exams:Number(exams?.n||0),marking:Number(marking?.n||0),published:Number(published?.n||0),marks:Number(marks?.n||0),report_cards:Number(cards?.n||0)};
}

export async function listSchoolSubjects(db:D1Database,org:string,classId?:string|null){
 let classLevelId:string|null=null,yearId:string|null=null;
 if(classId){const cls=await requireSchoolRef(db,org,"school_classes",classId,"Class") as any;classLevelId=cls.class_level_id;yearId=cls.academic_year_id}
 if(classLevelId){const rows=await db.prepare(`SELECT s.*,cs.compulsory,cs.periods_per_week,cs.teacher_user_id
   FROM school_subjects s LEFT JOIN school_class_subjects cs ON cs.subject_id=s.id AND cs.organization_id=s.organization_id AND cs.class_level_id=? AND (cs.academic_year_id=? OR cs.academic_year_id IS NULL) AND cs.active=1
   WHERE s.organization_id=? AND s.active=1 AND (cs.id IS NOT NULL OR NOT EXISTS(SELECT 1 FROM school_class_subjects x WHERE x.organization_id=s.organization_id AND x.class_level_id=? AND x.active=1))
   ORDER BY s.name`).bind(classLevelId,yearId,org,classLevelId).all();return rows.results}
 return (await db.prepare("SELECT * FROM school_subjects WHERE organization_id=? AND active=1 ORDER BY name").bind(org).all()).results;
}

export async function seedPleScale(db:D1Database,org:string,userId:string){
 let scale=await db.prepare("SELECT * FROM exm_grading_scales WHERE organization_id=? AND is_default=1 AND active=1").bind(org).first<any>();
 if(!scale){const id=createId("egs");await db.prepare("INSERT INTO exm_grading_scales(id,organization_id,code,name,is_default,created_by) VALUES (?,?,?,'Uganda PLE Scale',1,?)").bind(id,org,"PLE",userId).run();scale=await db.prepare("SELECT * FROM exm_grading_scales WHERE id=?").bind(id).first()}
 const existing=await db.prepare("SELECT COUNT(*) n FROM exm_grade_bands WHERE grading_scale_id=?").bind(scale.id).first<any>();
 if(!Number(existing?.n||0)){await db.batch(PLE_BANDS.map(b=>db.prepare(`INSERT INTO exm_grade_bands(id,organization_id,grading_scale_id,grade,label,min_mark,max_mark,points,color_hex,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(createId("egb"),org,scale.id,b.grade,b.label,b.min_mark,b.max_mark,b.points,b.color_hex,b.sort_order)))}
 return getScale(db,org,scale.id);
}
export async function listScales(db:D1Database,org:string){const scales=(await db.prepare("SELECT * FROM exm_grading_scales WHERE organization_id=? AND active=1 ORDER BY is_default DESC,name").bind(org).all()).results as any[];for(const s of scales)s.bands=(await db.prepare("SELECT * FROM exm_grade_bands WHERE grading_scale_id=? ORDER BY sort_order").bind(s.id).all()).results;return scales}
export async function getScale(db:D1Database,org:string,id:string){const s=await db.prepare("SELECT * FROM exm_grading_scales WHERE id=? AND organization_id=?").bind(id,org).first<any>();if(!s)throw new AppError(404,"GRADING_SCALE_NOT_FOUND","Grading scale not found");s.bands=(await db.prepare("SELECT * FROM exm_grade_bands WHERE grading_scale_id=? ORDER BY sort_order").bind(id).all()).results;return s}
export async function updateBand(db:D1Database,org:string,id:string,data:any){const before=await db.prepare("SELECT * FROM exm_grade_bands WHERE id=? AND organization_id=?").bind(id,org).first();if(!before)throw new AppError(404,"GRADE_BAND_NOT_FOUND","Grade band not found");await db.prepare(`UPDATE exm_grade_bands SET grade=?,label=?,min_mark=?,max_mark=?,points=?,color_hex=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(data.grade,data.label,data.min_mark,data.max_mark,data.points??null,data.color_hex||"#64748B",data.sort_order??0,id,org).run();return db.prepare("SELECT * FROM exm_grade_bands WHERE id=?").bind(id).first()}

export async function seedDefaultComments(db:D1Database,org:string,userId:string){const c=await db.prepare("SELECT COUNT(*) n FROM exm_comment_rules WHERE organization_id=?").bind(org).first<any>();if(Number(c?.n||0)>0)return{skipped:true};const rows=[...DEFAULT_CT.map(x=>({...x,comment_type:"class_teacher"})),...DEFAULT_HT.map(x=>({...x,comment_type:"head_teacher"}))];await db.batch(rows.map(x=>db.prepare("INSERT INTO exm_comment_rules(id,organization_id,comment_type,min_agg,max_agg,comment_text,created_by) VALUES (?,?,?,?,?,?,?)").bind(createId("ecr"),org,x.comment_type,x.min_agg,x.max_agg,x.comment_text,userId)));return{seeded:true}}
export async function listComments(db:D1Database,org:string,type?:string|null){let q="SELECT * FROM exm_comment_rules WHERE organization_id=? AND active=1",b:any[]=[org];if(type){q+=" AND comment_type=?";b.push(type)}q+=" ORDER BY comment_type,min_agg";return(await db.prepare(q).bind(...b).all()).results}
export async function upsertComment(db:D1Database,org:string,userId:string,data:any){if(data.id){await db.prepare("UPDATE exm_comment_rules SET min_agg=?,max_agg=?,comment_text=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(data.min_agg,data.max_agg,data.comment_text,data.id,org).run();return db.prepare("SELECT * FROM exm_comment_rules WHERE id=?").bind(data.id).first()}const id=createId("ecr");await db.prepare("INSERT INTO exm_comment_rules(id,organization_id,comment_type,min_agg,max_agg,comment_text,created_by) VALUES (?,?,?,?,?,?,?)").bind(id,org,data.comment_type,data.min_agg,data.max_agg,data.comment_text,userId).run();return db.prepare("SELECT * FROM exm_comment_rules WHERE id=?").bind(id).first()}
export async function deleteComment(db:D1Database,org:string,id:string){await db.prepare("UPDATE exm_comment_rules SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(id,org).run();return{deleted:true}}

export async function listExams(db:D1Database,org:string,filters:any={}){let q=`SELECT e.*,t.name term_name,ay.name academic_year_name,gs.name grading_scale_name,(SELECT COUNT(*) FROM exm_exam_classes ec WHERE ec.exam_id=e.id) class_count FROM exm_exams e LEFT JOIN school_terms t ON t.id=e.term_id LEFT JOIN school_academic_years ay ON ay.id=e.academic_year_id LEFT JOIN exm_grading_scales gs ON gs.id=e.grading_scale_id WHERE e.organization_id=?`,b:any[]=[org];for(const [k,col] of [["status","status"],["term_id","term_id"],["academic_year_id","academic_year_id"]])if(filters[k]){q+=` AND e.${col}=?`;b.push(filters[k])}q+=" ORDER BY e.created_at DESC";return(await db.prepare(q).bind(...b).all()).results}
export async function getExam(db:D1Database,org:string,id:string){const e=await db.prepare(`SELECT e.*,t.name term_name,ay.name academic_year_name,gs.name grading_scale_name FROM exm_exams e LEFT JOIN school_terms t ON t.id=e.term_id LEFT JOIN school_academic_years ay ON ay.id=e.academic_year_id LEFT JOIN exm_grading_scales gs ON gs.id=e.grading_scale_id WHERE e.id=? AND e.organization_id=?`).bind(id,org).first<any>();if(!e)throw new AppError(404,"EXAM_NOT_FOUND","Exam not found");e.classes=await listExamClasses(db,org,id);return e}
export async function createExam(db:D1Database,org:string,userId:string,data:any){if(data.term_id)await requireSchoolRef(db,org,"school_terms",data.term_id,"Term");if(data.academic_year_id)await requireSchoolRef(db,org,"school_academic_years",data.academic_year_id,"Academic year");let scale=data.grading_scale_id;if(!scale){const s=await seedPleScale(db,org,userId);scale=s.id}await seedDefaultComments(db,org,userId);const id=createId("exm");await db.prepare(`INSERT INTO exm_exams(id,organization_id,term_id,academic_year_id,name,exam_type,start_date,end_date,grading_scale_id,status,remarks,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,'draft',?,?,?)`).bind(id,org,data.term_id||null,data.academic_year_id||null,String(data.name).trim(),data.exam_type||"end_of_term",data.start_date||null,data.end_date||null,scale,data.remarks||null,userId,userId).run();return getExam(db,org,id)}
export async function updateExam(db:D1Database,org:string,userId:string,id:string,data:any){await requireExam(db,org,id);if(data.term_id)await requireSchoolRef(db,org,"school_terms",data.term_id,"Term");if(data.academic_year_id)await requireSchoolRef(db,org,"school_academic_years",data.academic_year_id,"Academic year");await db.prepare(`UPDATE exm_exams SET name=COALESCE(?,name),exam_type=COALESCE(?,exam_type),start_date=?,end_date=?,term_id=?,academic_year_id=?,grading_scale_id=COALESCE(?,grading_scale_id),remarks=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?`).bind(data.name??null,data.exam_type??null,data.start_date??null,data.end_date??null,data.term_id??null,data.academic_year_id??null,data.grading_scale_id??null,data.remarks??null,userId,id,org).run();return getExam(db,org,id)}
export async function updateExamStatus(db:D1Database,org:string,userId:string,id:string,status:string){if(!["draft","active","marking","published","archived"].includes(status))throw new AppError(422,"INVALID_STATUS","Invalid exam status");await requireExam(db,org,id);await db.prepare("UPDATE exm_exams SET status=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=?").bind(status,userId,id,org).run();return getExam(db,org,id)}

export async function listExamClasses(db:D1Database,org:string,examId:string){return(await db.prepare(`SELECT ec.*,c.name class_name,c.code class_code,st.name stream_name,cl.name class_level_name,(SELECT COUNT(*) FROM school_students ss WHERE ss.organization_id=ec.organization_id AND ss.current_class_id=ec.class_id AND ss.deleted_at IS NULL AND ss.status='active') student_count FROM exm_exam_classes ec JOIN school_classes c ON c.id=ec.class_id LEFT JOIN school_streams st ON st.id=ec.stream_id LEFT JOIN school_class_levels cl ON cl.id=c.class_level_id WHERE ec.exam_id=? AND ec.organization_id=? ORDER BY cl.sequence_no,c.name,st.name`).bind(examId,org).all()).results}
export async function enrollClass(db:D1Database,org:string,userId:string,examId:string,classId:string,streamId?:string|null){await requireExam(db,org,examId);await requireSchoolRef(db,org,"school_classes",classId,"Class");if(streamId){const st:any=await requireSchoolRef(db,org,"school_streams",streamId,"Stream");if(st.class_id!==classId)throw new AppError(422,"INVALID_STREAM","Stream does not belong to the selected class")};const existing=await db.prepare("SELECT * FROM exm_exam_classes WHERE exam_id=? AND class_id=? AND IFNULL(stream_id,'')=IFNULL(?,'')").bind(examId,classId,streamId||null).first();if(existing)return existing;const id=createId("exc");await db.prepare("INSERT INTO exm_exam_classes(id,organization_id,exam_id,class_id,stream_id,created_by) VALUES (?,?,?,?,?,?)").bind(id,org,examId,classId,streamId||null,userId).run();return db.prepare("SELECT * FROM exm_exam_classes WHERE id=?").bind(id).first()}
export async function removeClass(db:D1Database,org:string,examId:string,classId:string){const used=await db.prepare("SELECT COUNT(*) n FROM exm_marks WHERE exam_id=? AND class_id=? AND organization_id=?").bind(examId,classId,org).first<any>();if(Number(used?.n||0)>0)throw new AppError(409,"EXAM_CLASS_HAS_MARKS","This class already has entered marks. Remove or correct the marks before removing the class from the exam.");await db.prepare("DELETE FROM exm_exam_subjects WHERE exam_id=? AND class_id=? AND organization_id=?").bind(examId,classId,org).run();await db.prepare("DELETE FROM exm_exam_classes WHERE exam_id=? AND class_id=? AND organization_id=?").bind(examId,classId,org).run();return{removed:true}}

export async function listExamSubjects(db:D1Database,org:string,examId:string,classId?:string|null){let q=`SELECT es.*,s.name subject_name,s.code subject_code,s.short_name,s.subject_type FROM exm_exam_subjects es JOIN school_subjects s ON s.id=es.subject_id WHERE es.exam_id=? AND es.organization_id=?`,b:any[]=[examId,org];if(classId){q+=" AND es.class_id=?";b.push(classId)}q+=" ORDER BY es.sort_order,s.name";return(await db.prepare(q).bind(...b).all()).results}
export async function addSubject(db:D1Database,org:string,userId:string,examId:string,classId:string,subjectId:string,overrides:any={}){await requireExam(db,org,examId);await requireSchoolRef(db,org,"school_classes",classId,"Class");const subj:any=await requireSchoolRef(db,org,"school_subjects",subjectId,"Subject");const existing=await db.prepare("SELECT id FROM exm_exam_subjects WHERE exam_id=? AND class_id=? AND subject_id=?").bind(examId,classId,subjectId).first<any>();if(existing){await db.prepare("UPDATE exm_exam_subjects SET max_mark=?,passing_mark=?,is_gradable=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(overrides.max_mark??subj.max_mark??100,overrides.passing_mark??subj.pass_mark??50,overrides.is_gradable??1,overrides.sort_order??0,existing.id).run();return db.prepare("SELECT * FROM exm_exam_subjects WHERE id=?").bind(existing.id).first()}const id=createId("exs");await db.prepare("INSERT INTO exm_exam_subjects(id,organization_id,exam_id,class_id,subject_id,max_mark,passing_mark,is_gradable,sort_order,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,org,examId,classId,subjectId,overrides.max_mark??subj.max_mark??100,overrides.passing_mark??subj.pass_mark??50,overrides.is_gradable??1,overrides.sort_order??0,userId).run();return db.prepare("SELECT * FROM exm_exam_subjects WHERE id=?").bind(id).first()}
export async function bulkAddSubjects(db:D1Database,org:string,userId:string,examId:string,classId:string,subjectIds:string[]){const out=[];for(let i=0;i<subjectIds.length;i++){try{out.push(await addSubject(db,org,userId,examId,classId,subjectIds[i],{sort_order:i}))}catch(e){out.push({subject_id:subjectIds[i],error:e instanceof Error?e.message:String(e)})}}return out}
export async function removeSubject(db:D1Database,org:string,examId:string,classId:string,subjectId:string){const used=await db.prepare("SELECT COUNT(*) n FROM exm_marks WHERE exam_id=? AND class_id=? AND subject_id=? AND organization_id=?").bind(examId,classId,subjectId,org).first<any>();if(Number(used?.n||0)>0)throw new AppError(409,"EXAM_SUBJECT_HAS_MARKS","This subject already has entered marks for the class. Clear or correct those marks before removing the subject from the exam.");await db.prepare("DELETE FROM exm_exam_subjects WHERE exam_id=? AND class_id=? AND subject_id=? AND organization_id=?").bind(examId,classId,subjectId,org).run();return{removed:true}}

async function roster(db:D1Database,org:string,examId:string,classId:string){const exam:any=await requireExam(db,org,examId);if(exam.academic_year_id){const rows=await db.prepare(`SELECT DISTINCT s.id,s.first_name,s.middle_name,s.last_name,s.student_number,s.admission_number,e.class_id AS current_class_id,e.stream_id AS current_stream_id,st.name stream_name FROM school_enrollments e JOIN school_students s ON s.id=e.student_id AND s.organization_id=e.organization_id LEFT JOIN school_streams st ON st.id=e.stream_id WHERE e.organization_id=? AND e.academic_year_id=? AND e.class_id=? AND e.status IN ('active','completed','repeated') AND s.deleted_at IS NULL AND s.status IN ('active','suspended','graduated') ORDER BY s.last_name,s.first_name`).bind(org,exam.academic_year_id,classId).all();if(rows.results.length)return rows.results}return(await db.prepare(`SELECT s.id,s.first_name,s.middle_name,s.last_name,s.student_number,s.admission_number,s.current_class_id,s.current_stream_id,st.name stream_name FROM school_students s LEFT JOIN school_streams st ON st.id=s.current_stream_id WHERE s.organization_id=? AND s.current_class_id=? AND s.deleted_at IS NULL AND s.status IN ('active','suspended') ORDER BY s.last_name,s.first_name`).bind(org,classId).all()).results}
export async function getMarksheet(db:D1Database,org:string,examId:string,classId:string){const subjects=await listExamSubjects(db,org,examId,classId),students=await roster(db,org,examId,classId),marks=(await db.prepare("SELECT * FROM exm_marks WHERE exam_id=? AND class_id=? AND organization_id=?").bind(examId,classId,org).all()).results as any[],idx:any={};for(const m of marks)idx[`${m.student_id}_${m.subject_id}`]=m;return{subjects,students:students.map((s:any)=>({...s,marks:subjects.reduce((a:any,x:any)=>(a[x.subject_id]=idx[`${s.id}_${x.subject_id}`]||null,a),{})}))}}

export async function enterMark(db:D1Database,org:string,examId:string,studentId:string,subjectId:string,data:any,userId:string){
 const student:any=await db.prepare("SELECT * FROM school_students WHERE id=? AND organization_id=? AND deleted_at IS NULL").bind(studentId,org).first();if(!student)throw new AppError(404,"STUDENT_NOT_FOUND","Student not found");
 const classId=data.class_id||student.current_class_id;if(!classId)throw new AppError(422,"CLASS_REQUIRED","Cannot determine class for student");
 const es:any=await db.prepare("SELECT * FROM exm_exam_subjects WHERE exam_id=? AND class_id=? AND subject_id=? AND organization_id=?").bind(examId,classId,subjectId,org).first();if(!es)throw new AppError(422,"SUBJECT_NOT_CONFIGURED",`Subject is not configured for this student's class in this exam`);
 const bands=await bandsForExam(db,org,examId),isAbsent=!!data.is_absent,isExempt=!!data.is_exempt,raw=isAbsent||isExempt?null:(data.marks_obtained===""||data.marks_obtained==null?null:Number(data.marks_obtained));if(raw!=null&&(raw<0||raw>Number(es.max_mark)))throw new AppError(422,"INVALID_MARK",`Mark must be between 0 and ${es.max_mark}`);
 const comp=es.is_gradable?computeGrade(raw,Number(es.max_mark),bands):{grade:"NG",grade_points:null,label:"Non-Gradable",percentage:raw!=null?Math.round(raw/Number(es.max_mark)*1000)/10:null};
 const existing:any=await db.prepare("SELECT * FROM exm_marks WHERE exam_id=? AND student_id=? AND subject_id=?").bind(examId,studentId,subjectId).first();
 if(existing){await db.batch([db.prepare("INSERT INTO exm_mark_audit(id,organization_id,mark_id,exam_id,student_id,subject_id,action,old_mark,new_mark,changed_by,reason,changes_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(createId("ema"),org,existing.id,examId,studentId,subjectId,"updated",existing.marks_obtained,raw,userId,data.reason||null,JSON.stringify({before:{is_absent:existing.is_absent,is_exempt:existing.is_exempt,remarks:existing.remarks},after:{is_absent:isAbsent,is_exempt:isExempt,remarks:data.remarks||null}})),db.prepare(`UPDATE exm_marks SET marks_obtained=?,is_absent=?,is_exempt=?,percentage=?,grade=?,grade_points=?,remarks=?,entered_by=?,entered_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(raw,isAbsent?1:0,isExempt?1:0,comp.percentage,comp.grade,comp.grade_points,data.remarks||null,userId,now(),existing.id)]);return db.prepare("SELECT * FROM exm_marks WHERE id=?").bind(existing.id).first()}
 const id=createId("emk");await db.batch([db.prepare(`INSERT INTO exm_marks(id,organization_id,exam_id,exam_subject_id,student_id,class_id,subject_id,marks_obtained,is_absent,is_exempt,percentage,grade,grade_points,remarks,entered_by,entered_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,org,examId,es.id,studentId,classId,subjectId,raw,isAbsent?1:0,isExempt?1:0,comp.percentage,comp.grade,comp.grade_points,data.remarks||null,userId,now()),db.prepare("INSERT INTO exm_mark_audit(id,organization_id,mark_id,exam_id,student_id,subject_id,action,new_mark,changed_by,reason) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(createId("ema"),org,id,examId,studentId,subjectId,"entered",raw,userId,data.reason||null)]);return db.prepare("SELECT * FROM exm_marks WHERE id=?").bind(id).first();
}
export async function bulkEnterMarks(db:D1Database,org:string,examId:string,subjectId:string,records:any[],userId:string){const out=[];for(const r of records){try{out.push({student_id:r.student_id,ok:true,data:await enterMark(db,org,examId,r.student_id,subjectId,r,userId)})}catch(e){out.push({student_id:r.student_id,ok:false,error:e instanceof Error?e.message:String(e)})}}return out}

function buildStudentCard({student,subjectsConfigured,marksByStudent,ctRules,htRules,existingComment}:any){
 const gradable=subjectsConfigured.filter((s:any)=>asBool(s.is_gradable)),rows:any[]=[];let missingCount=0;
 for(const cfg of gradable){const m=marksByStudent[cfg.subject_id];if(!m){missingCount++;rows.push({subject_id:cfg.subject_id,exam_subject_id:cfg.id,marks_obtained:null,is_absent:0,is_exempt:0,percentage:null,grade:"X",grade_points:null,_missing:true})}else rows.push(m)}
 for(const cfg of subjectsConfigured.filter((s:any)=>!asBool(s.is_gradable))){const m=marksByStudent[cfg.subject_id];if(m)rows.push(m)}
 const allSat=rows.filter(m=>!m._missing&&!asBool(m.is_absent)&&!asBool(m.is_exempt)&&m.grade_points!=null),scored=rows.filter(m=>!m._missing&&!asBool(m.is_absent)&&!asBool(m.is_exempt)&&m.marks_obtained!=null),counted=selectCountedSubjectIds(allSat),forAgg=allSat.filter(m=>counted.has(m.subject_id));
 const totalMarks=scored.reduce((s,m)=>s+Number(m.marks_obtained||0),0),maxPossible=scored.reduce((s,m)=>s+Number(gradable.find((x:any)=>x.subject_id===m.subject_id)?.max_mark||0),0),aggregate=forAgg.length?forAgg.reduce((s,m)=>s+Number(m.grade_points||0),0):null;
 const sat=Math.min(allSat.length,AGGREGATE_SUBJECT_COUNT),required=Math.min(gradable.length,AGGREGATE_SUBJECT_COUNT),effectiveMissing=allSat.length>=AGGREGATE_SUBJECT_COUNT?0:missingCount,division=computeDivision(aggregate,sat,required,effectiveMissing),summary:any={};
 for(const m of rows){const g=!m._missing&&!asBool(m.is_absent)&&!asBool(m.is_exempt)&&m.grade_points!=null;if(g&&!counted.has(m.subject_id))continue;if(m.grade)summary[m.grade]=(summary[m.grade]||0)+1}
 return{student_id:student.id,class_id:student.current_class_id,stream_id:student.current_stream_id||null,total_marks:totalMarks,max_possible_marks:maxPossible,subjects_sat:rows.length-missingCount,subjects_missing:missingCount,aggregate,division,grade_summary:JSON.stringify(summary),class_teacher_comment:existingComment?.class_teacher_comment||pickComment(aggregate,ctRules),head_teacher_comment:existingComment?.head_teacher_comment||pickComment(aggregate,htRules)};
}
async function attendancePercent(db:D1Database,org:string,studentId:string,exam:any){const where=["r.organization_id=?","r.person_id=?","r.person_type='student'","r.official=1","s.session_type='daily'","s.status IN ('finalized','locked')"],b:any[]=[org,studentId];if(exam.term_id){where.push("s.term_id=?");b.push(exam.term_id)}else if(exam.academic_year_id){where.push("s.academic_year_id=?");b.push(exam.academic_year_id)}const x=await db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN r.status IN ('present','late','excused','sick','permission') THEN 1 ELSE 0 END) attended FROM att_records r JOIN att_sessions s ON s.id=r.session_id WHERE ${where.join(" AND ")}`).bind(...b).first<any>();return Number(x?.total||0)?Math.round(Number(x.attended||0)/Number(x.total)*1000)/10:null}

export async function computeClassReportCards(db:D1Database,org:string,examId:string,classId:string,userId:string){
 const exam:any=await requireExam(db,org,examId),[students,subjects,allMarks,ctRules,htRules,existing]=await Promise.all([roster(db,org,examId,classId),listExamSubjects(db,org,examId,classId),db.prepare("SELECT * FROM exm_marks WHERE exam_id=? AND class_id=? AND organization_id=?").bind(examId,classId,org).all().then(r=>r.results),db.prepare("SELECT * FROM exm_comment_rules WHERE organization_id=? AND comment_type='class_teacher' AND active=1 ORDER BY min_agg").bind(org).all().then(r=>r.results),db.prepare("SELECT * FROM exm_comment_rules WHERE organization_id=? AND comment_type='head_teacher' AND active=1 ORDER BY min_agg").bind(org).all().then(r=>r.results),db.prepare("SELECT * FROM exm_report_cards WHERE exam_id=? AND class_id=? AND organization_id=?").bind(examId,classId,org).all().then(r=>r.results)]);
 if(!students.length)return{computed:0,total_in_class:0,report_cards:[]};const markIdx:any={},cardIdx:any={};for(const m of allMarks as any[]){(markIdx[m.student_id]??={})[m.subject_id]=m}for(const c of existing as any[])cardIdx[c.student_id]=c;const cards=students.map((s:any)=>buildStudentCard({student:s,subjectsConfigured:subjects,marksByStudent:markIdx[s.id]||{},ctRules,htRules,existingComment:cardIdx[s.id]}));
 const rankable=[...cards].filter(c=>c.aggregate!=null&&c.division!=="X").sort((a,b)=>a.aggregate!==b.aggregate?a.aggregate-b.aggregate:(b.total_marks||0)-(a.total_marks||0)),positions:any={};for(const c of cards)positions[c.student_id]=null;let prev:any,prevPos=1;for(let i=0;i<rankable.length;i++){const c=rankable[i];if(c.aggregate!==prev)prevPos=i+1;positions[c.student_id]=prevPos;prev=c.aggregate}const total=cards.length;
 const statements=[];for(const card of cards){const old=cardIdx[card.student_id],att=await attendancePercent(db,org,card.student_id,exam);if(old)statements.push(db.prepare(`UPDATE exm_report_cards SET total_marks=?,max_possible_marks=?,subjects_sat=?,subjects_missing=?,aggregate=?,division=?,grade_summary=?,class_teacher_comment=?,head_teacher_comment=?,position_in_class=?,total_students_in_class=?,attendance_percent=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(card.total_marks,card.max_possible_marks,card.subjects_sat,card.subjects_missing,card.aggregate,card.division,card.grade_summary,card.class_teacher_comment,card.head_teacher_comment,positions[card.student_id],total,att,old.id));else statements.push(db.prepare(`INSERT INTO exm_report_cards(id,organization_id,exam_id,student_id,class_id,stream_id,total_marks,max_possible_marks,subjects_sat,subjects_missing,aggregate,division,grade_summary,class_teacher_comment,head_teacher_comment,position_in_class,total_students_in_class,attendance_percent) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(createId("erc"),org,examId,card.student_id,card.class_id,card.stream_id,card.total_marks,card.max_possible_marks,card.subjects_sat,card.subjects_missing,card.aggregate,card.division,card.grade_summary,card.class_teacher_comment,card.head_teacher_comment,positions[card.student_id],total,att))}for(let i=0;i<statements.length;i+=50)await db.batch(statements.slice(i,i+50));return{computed:students.length,total_in_class:total,report_cards:await getClassReportSummary(db,org,examId,classId)}}

export async function getClassReportSummary(db:D1Database,org:string,examId:string,classId:string){const rows=await db.prepare(`SELECT rc.*,s.first_name,s.middle_name,s.last_name,s.student_number,s.admission_number,st.name stream_name FROM exm_report_cards rc JOIN school_students s ON s.id=rc.student_id LEFT JOIN school_streams st ON st.id=rc.stream_id WHERE rc.exam_id=? AND rc.class_id=? AND rc.organization_id=? ORDER BY (rc.position_in_class IS NULL),rc.position_in_class,s.last_name,s.first_name`).bind(examId,classId,org).all<any>();return rows.results.map((r:any)=>({...r,grade_summary:typeof r.grade_summary==="string"?JSON.parse(r.grade_summary||"{}"):r.grade_summary}))}
export async function getStudentReportCard(db:D1Database,org:string,examId:string,studentId:string){let card:any=await db.prepare(`SELECT rc.*,s.first_name,s.middle_name,s.last_name,s.student_number,s.admission_number,s.date_of_birth,c.name class_name,st.name stream_name,e.name exam_name,e.exam_type,e.start_date,e.end_date,t.name term_name,ay.name academic_year_name,(SELECT nt.starts_on FROM school_terms nt WHERE nt.organization_id=rc.organization_id AND nt.starts_on>COALESCE(t.ends_on,e.end_date,e.start_date,'0000-01-01') ORDER BY nt.starts_on LIMIT 1) next_term_begins FROM exm_report_cards rc JOIN school_students s ON s.id=rc.student_id JOIN exm_exams e ON e.id=rc.exam_id LEFT JOIN school_classes c ON c.id=rc.class_id LEFT JOIN school_streams st ON st.id=rc.stream_id LEFT JOIN school_terms t ON t.id=e.term_id LEFT JOIN school_academic_years ay ON ay.id=e.academic_year_id WHERE rc.exam_id=? AND rc.student_id=? AND rc.organization_id=?`).bind(examId,studentId,org).first();if(!card){const s:any=await db.prepare(`SELECT s.*,c.name class_name,st.name stream_name FROM school_students s LEFT JOIN school_classes c ON c.id=s.current_class_id LEFT JOIN school_streams st ON st.id=s.current_stream_id WHERE s.id=? AND s.organization_id=?`).bind(studentId,org).first(),e:any=await getExam(db,org,examId);return{_not_computed:true,student_id:studentId,exam_id:examId,first_name:s?.first_name,last_name:s?.last_name,student_number:s?.student_number,admission_number:s?.admission_number,class_name:s?.class_name,stream_name:s?.stream_name,exam_name:e.name,term_name:e.term_name,academic_year_name:e.academic_year_name,aggregate:null,position_in_class:null,total_students_in_class:null,class_teacher_comment:null,head_teacher_comment:null,is_published:0,marks:[]}}
 const entered=(await db.prepare(`SELECT m.*,s.name subject_name,s.code subject_code,es.sort_order,es.max_mark exam_max_mark,es.is_gradable FROM exm_marks m JOIN school_subjects s ON s.id=m.subject_id JOIN exm_exam_subjects es ON es.id=m.exam_subject_id WHERE m.exam_id=? AND m.student_id=? AND m.organization_id=? ORDER BY es.sort_order,s.name`).bind(examId,studentId,org).all()).results as any[],configured=(await db.prepare(`SELECT es.*,s.name subject_name,s.code subject_code FROM exm_exam_subjects es JOIN school_subjects s ON s.id=es.subject_id WHERE es.exam_id=? AND es.class_id=? AND es.is_gradable=1 ORDER BY es.sort_order,s.name`).bind(examId,card.class_id).all()).results as any[],enteredIds=new Set(entered.map(m=>m.subject_id)),missing=configured.filter(x=>!enteredIds.has(x.subject_id)).map(x=>({subject_id:x.subject_id,subject_name:x.subject_name,subject_code:x.subject_code,sort_order:x.sort_order,exam_max_mark:x.max_mark,is_gradable:1,marks_obtained:null,is_absent:0,is_exempt:0,percentage:null,grade:"X",grade_points:null,remarks:"Missing — no mark recorded for this subject"})),sat=entered.filter(m=>asBool(m.is_gradable)&&!asBool(m.is_absent)&&!asBool(m.is_exempt)&&m.grade_points!=null),counted=selectCountedSubjectIds(sat);
 card.marks=[...entered,...missing].map(m=>{const graded=asBool(m.is_gradable)&&!asBool(m.is_absent)&&!asBool(m.is_exempt)&&m.grade_points!=null,c=graded?counted.has(m.subject_id):null,display=c===false?"N/A":m.grade;return{...m,grade:display,display_grade:display,counted_in_aggregate:c,...(c===false&&!m.remarks?{remarks:" - "}:{})}}).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0));try{card.grade_summary=JSON.parse(card.grade_summary||"{}")}catch{card.grade_summary={}}return card;
}
export async function updateComments(db:D1Database,org:string,examId:string,studentId:string,userId:string,data:any){const card:any=await db.prepare("SELECT * FROM exm_report_cards WHERE exam_id=? AND student_id=? AND organization_id=?").bind(examId,studentId,org).first();if(!card)throw new AppError(404,"REPORT_CARD_NOT_FOUND","Report card not found. Compute the class first.");await db.batch([db.prepare(`UPDATE exm_report_cards SET class_teacher_comment=?,head_teacher_comment=?,class_teacher_id=?,head_teacher_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(data.class_teacher_comment??null,data.head_teacher_comment??null,data.class_teacher_id??null,data.head_teacher_id??null,card.id),db.prepare("INSERT INTO exm_mark_audit(id,organization_id,mark_id,exam_id,student_id,action,changed_by,reason,changes_json) VALUES (?,?,?,?,?,?,?,?,?)").bind(createId("ema"),org,card.id,examId,studentId,card.is_published?"comment_edited_post_publish":"comment_edited",userId,data.reason||null,JSON.stringify({class_teacher_comment:data.class_teacher_comment,head_teacher_comment:data.head_teacher_comment}))]);return getStudentReportCard(db,org,examId,studentId)}
export async function publishClass(db:D1Database,org:string,examId:string,classId:string,userId:string){const r=await db.prepare("UPDATE exm_report_cards SET is_published=1,published_at=?,published_by=?,updated_at=CURRENT_TIMESTAMP WHERE exam_id=? AND organization_id=? AND class_id=?").bind(now(),userId,examId,org,classId).run();return{published:true,class_id:classId,count:r.meta.changes}}

export async function reportSummary(db:D1Database,org:string,examId:string,classId?:string|null){let where="rc.organization_id=? AND rc.exam_id=?",b:any[]=[org,examId];if(classId){where+=" AND rc.class_id=?";b.push(classId)}const [s,divs,grades,classes]=await Promise.all([db.prepare(`SELECT COUNT(*) students,AVG(rc.total_marks*100.0/NULLIF(rc.max_possible_marks,0)) average_percent,MIN(rc.aggregate) best_aggregate,AVG(rc.aggregate) average_aggregate,SUM(CASE WHEN rc.division='X' THEN 1 ELSE 0 END) incomplete FROM exm_report_cards rc WHERE ${where}`).bind(...b).first(),db.prepare(`SELECT division,COUNT(*) count FROM exm_report_cards rc WHERE ${where} GROUP BY division ORDER BY division`).bind(...b).all(),db.prepare(`SELECT rc.grade_summary FROM exm_report_cards rc WHERE ${where}`).bind(...b).all(),db.prepare(`SELECT rc.class_id,c.name class_name,COUNT(*) students,MIN(rc.aggregate) best_aggregate,AVG(rc.aggregate) average_aggregate FROM exm_report_cards rc JOIN school_classes c ON c.id=rc.class_id WHERE ${where} GROUP BY rc.class_id,c.name ORDER BY c.name`).bind(...b).all()]);const gradeTotals:any={};for(const row of grades.results as any[]){try{const g=JSON.parse(row.grade_summary||"{}");for(const[k,v]of Object.entries(g))gradeTotals[k]=(gradeTotals[k]||0)+Number(v||0)}catch{}}return{summary:s||{},divisions:divs.results,grades:gradeTotals,classes:classes.results}}
export async function markAudit(db:D1Database,org:string,examId:string,limit=200){return(await db.prepare(`SELECT a.*,s.first_name,s.last_name,s.student_number,sub.name subject_name,u.display_name changed_by_name FROM exm_mark_audit a LEFT JOIN school_students s ON s.id=a.student_id LEFT JOIN school_subjects sub ON sub.id=a.subject_id LEFT JOIN users u ON u.id=a.changed_by WHERE a.organization_id=? AND a.exam_id=? ORDER BY a.created_at DESC LIMIT ?`).bind(org,examId,limit).all()).results}
