import {useEffect,useState} from "react";
import {RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import type {MobileSession} from "../auth";
import type {SessionUpdater} from "../apiClient";
import {Card,ErrorNotice,Metric,Pill,SectionTitle} from "../school/ui";
import {contactsApi} from "./api";
import type {ContactCapability,CoreContact,DirectoryPerson} from "./types";
import {err,tone} from "./context";
export function OverviewTab({session,onSession}:{session:MobileSession;onSession:SessionUpdater}){const c={session,onSession};const[cap,setCap]=useState<ContactCapability|null>(null),[contacts,setContacts]=useState<CoreContact[]>([]),[people,setPeople]=useState<DirectoryPerson[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const[a,b,d]=await Promise.all([contactsApi.capabilities(c),contactsApi.contacts(c),contactsApi.people(c,{limit:250})]);setCap(a);setContacts(b);setPeople(d as DirectoryPerson[])}catch(e){setError(err(e))}finally{setLoading(false)}}useEffect(()=>{void load()},[session.accessToken]);const active=contacts.filter(x=>x.active).length,channels=new Set(people.flatMap(x=>x.channels||[]));return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.scroll}><View style={s.hero}><Text style={s.eyebrow}>SHARED IDENTITY DIRECTORY</Text><Text style={s.title}>Contacts</Text><Text style={s.copy}>One operational directory across Ledgerly finance, School Management, Communications and Tasks & Work, while keeping each source module authoritative.</Text></View>{error?<ErrorNotice message={error} onRetry={load}/>:null}<View style={s.metrics}><Metric label="Core contacts" value={contacts.length} sub={`${active} active`}/><Metric label="People" value={people.length} sub="across enabled modules" tone="good"/><Metric label="Sources" value={cap?.sources?.length||0} sub="enabled providers"/><Metric label="Channels" value={channels.size} sub={[...channels].join(" · ")||"none"}/></View><SectionTitle title="Enabled contact sources" subtitle="The directory automatically follows the organization’s enabled modules"/><Card>{cap?.sources?.map(x=><View key={x.moduleKey} style={s.row}><View style={{flex:1}}><Text style={s.name}>{x.name}</Text><Text style={s.meta}>{x.groups.join(" · ")}</Text></View><Pill text={x.channels?.length?x.channels.join("+"):"directory"} tone={x.channels?.length?"good":"neutral"}/></View>)}{!cap?.sources?.length?<Text style={s.empty}>No source modules are currently available.</Text>:null}</Card><SectionTitle title="Recent directory sample"/><Card>{people.slice(0,6).map(p=><View key={p.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.meta}>{[p.group,p.sourceModule,p.phone,p.email].filter(Boolean).join(" · ")}</Text></View><Pill text={p.active?"active":"inactive"} tone={tone(p.active?"active":"inactive")}/></View>)}</Card></ScrollView>}
const s=StyleSheet.create({scroll:{padding:16,paddingBottom:40,gap:12},hero:{backgroundColor:"#173c46",borderRadius:24,padding:20},eyebrow:{fontSize:8,fontWeight:"900",letterSpacing:1.1,color:"#75d4de"},title:{fontSize:28,fontWeight:"900",color:"white",marginTop:7},copy:{fontSize:11,lineHeight:17,color:"#c2dadd",marginTop:6},metrics:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",gap:10},row:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#edf1ef"},name:{fontSize:11,fontWeight:"900",color:"#263d33"},meta:{fontSize:9,color:"#809087",marginTop:3},empty:{fontSize:10,color:"#819087"}});
