import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function camel(row:Record<string,unknown>){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(row))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;return out;}
async function portalGuardian(rt:Runtime,org:string,userId:string){const q=await rt.db.query(`SELECT a.guardian_id FROM school_guardian_portal_accounts a JOIN school_guardians g ON g.id=a.guardian_id AND g.organization_id=a.organization_id WHERE a.organization_id=$1 AND a.user_id=$2 AND a.active=true AND g.deleted_at IS NULL`,[org,userId]);if(!q.rowCount)throw new AppError(403,"PARENT_PORTAL_NOT_LINKED","This user is not linked to an active guardian portal account");return String(q.rows[0].guardian_id);}
async function childLink(rt:Runtime,org:string,guardianId:string,studentId:string){const q=await rt.db.query(`SELECT 1 FROM school_student_guardians sg JOIN school_students s ON s.id=sg.student_id AND s.organization_id=sg.organization_id WHERE sg.organization_id=$1 AND sg.guardian_id=$2 AND sg.student_id=$3 AND sg.deleted_at IS NULL AND s.deleted_at IS NULL`,[org,guardianId,studentId]);return Boolean(q.rowCount);}
const createSchema=z.object({studentId:z.string().min(1),title:z.string().min(2).max(200),description:z.string().max(5000).nullable().optional(),dueOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional()});
const responseSchema=z.object({decision:z.enum(["accepted","declined"]),notes:z.string().max(2000).nullable().optional()});

export function createParentPortalConsentRoutes(runtime:Runtime){const r=new Hono<AppEnv>();
 r.get("/consents",async c=>{const p=c.get("principal"),gid=await portalGuardian(runtime,p.organizationId,p.userId);const q=await runtime.db.query(`SELECT cr.*,s.admission_number,s.first_name,s.last_name,rs.id response_id,rs.decision,rs.notes response_notes,rs.responded_at FROM school_parent_consent_requests cr JOIN school_student_guardians sg ON sg.organization_id=cr.organization_id AND sg.student_id=cr.student_id AND sg.guardian_id=$2 AND sg.deleted_at IS NULL JOIN school_students s ON s.id=cr.student_id AND s.organization_id=cr.organization_id AND s.deleted_at IS NULL LEFT JOIN school_parent_consent_responses rs ON rs.organization_id=cr.organization_id AND rs.request_id=cr.id AND rs.guardian_id=$2 WHERE cr.organization_id=$1 AND cr.status<>'cancelled' ORDER BY CASE WHEN cr.status='active' THEN 0 ELSE 1 END,cr.due_on NULLS LAST,cr.created_at DESC`,[p.organizationId,gid]);return c.json({data:q.rows.map(camel)});});
 r.post("/consents/:id/respond",async c=>{const parsed=responseSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid consent response",parsed.error.flatten());const p=c.get("principal"),gid=await portalGuardian(runtime,p.organizationId,p.userId),id=c.req.param("id"),client=await runtime.db.connect();try{await client.query("BEGIN");const req=(await client.query<any>(`SELECT * FROM school_parent_consent_requests WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[id,p.organizationId])).rows[0];if(!req)throw new AppError(404,"CONSENT_NOT_FOUND","Consent request not found");if(req.status!=="active")throw new AppError(409,"CONSENT_CLOSED","This consent request is no longer accepting responses");if(req.due_on&&new Date(String(req.due_on))<new Date(new Date().toISOString().slice(0,10)))throw new AppError(409,"CONSENT_EXPIRED","The consent response deadline has passed");if(!(await childLink(runtime,p.organizationId,gid,String(req.student_id))))throw new AppError(403,"CHILD_NOT_LINKED","This consent request is not for a student linked to your account");const rid=createId("pcr");const q=await client.query(`INSERT INTO school_parent_consent_responses(id,organization_id,request_id,student_id,guardian_id,decision,notes,responded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id,request_id,guardian_id) DO UPDATE SET decision=EXCLUDED.decision,notes=EXCLUDED.notes,responded_by=EXCLUDED.responded_by,responded_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP RETURNING *`,[rid,p.organizationId,id,req.student_id,gid,parsed.data.decision,parsed.data.notes??null,p.userId]);await client.query("COMMIT");return c.json({data:camel(q.rows[0] as any)});}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}});
 r.get("/admin/consents",requireScope("school:read"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT cr.*,s.admission_number,s.first_name,s.last_name,COUNT(rs.id)::int response_count,COUNT(rs.id) FILTER(WHERE rs.decision='accepted')::int accepted_count,COUNT(rs.id) FILTER(WHERE rs.decision='declined')::int declined_count FROM school_parent_consent_requests cr JOIN school_students s ON s.id=cr.student_id AND s.organization_id=cr.organization_id LEFT JOIN school_parent_consent_responses rs ON rs.organization_id=cr.organization_id AND rs.request_id=cr.id WHERE cr.organization_id=$1 GROUP BY cr.id,s.admission_number,s.first_name,s.last_name ORDER BY cr.created_at DESC`,[p.organizationId]);return c.json({data:q.rows.map(camel)});});
 r.post("/admin/consents",requireScope("school:write"),async c=>{const parsed=createSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)throw new AppError(422,"VALIDATION_ERROR","Invalid consent request",parsed.error.flatten());const p=c.get("principal"),v=parsed.data,student=await runtime.db.query(`SELECT 1 FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[v.studentId,p.organizationId]);if(!student.rowCount)throw new AppError(422,"INVALID_STUDENT","Student does not belong to this school");const id=createId("pcn");await runtime.db.query(`INSERT INTO school_parent_consent_requests(id,organization_id,student_id,title,description,due_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,v.studentId,v.title,v.description??null,v.dueOn??null,p.userId]);return c.json({data:{id,status:"active",...v}},201);});
 r.post("/admin/consents/:id/close",requireScope("school:write"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`UPDATE school_parent_consent_requests SET status='closed',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status='active' RETURNING *`,[c.req.param("id"),p.organizationId]);if(!q.rowCount)throw new AppError(404,"CONSENT_NOT_FOUND","Active consent request not found");return c.json({data:camel(q.rows[0] as any)});});
 return r;}
