import type {Env,CommunicationJob} from "../../../src/types";
import {createId} from "../../../src/lib/ids";
import {GENERAL_WHATSAPP_LANGUAGE,GENERAL_WHATSAPP_TEMPLATE} from "./service";

function cleanPhone(raw:unknown){let p=String(raw||"").trim().replace(/[\s()\-]/g,"");if(!p)return null;if(p.startsWith("00"))p=`+${p.slice(2)}`;if(/^256\d+$/.test(p))p=`+${p}`;if(/^0\d{9}$/.test(p))p=`+256${p.slice(1)}`;return p.length>=7?p:null}
function parse(v:any,f:any={}){try{return JSON.parse(v)}catch{return f}}
async function existingJob(db:D1Database,row:any){if(!row.communication_delivery_id)return null;const r=await db.prepare(`SELECT d.id delivery_id,d.status delivery_status,d.recipient_snapshot_id,d.channel,d.recipient_phone,d.rendered_subject,d.rendered_message,d.template_variables_json,c.id campaign_id,c.sender_name FROM communication_deliveries d JOIN communication_campaigns c ON c.id=d.campaign_id WHERE d.id=? AND d.organization_id=?`).bind(row.communication_delivery_id,row.organization_id).first<any>();if(!r)return null;const vars=parse(r.template_variables_json,[]);return{row:r,job:{kind:"communication",deliveryId:r.delivery_id,organizationId:row.organization_id,campaignId:r.campaign_id,recipientSnapshotId:r.recipient_snapshot_id,channel:r.channel,recipient:r.recipient_phone,senderName:r.sender_name,subject:r.rendered_subject,message:r.rendered_message,templateName:r.channel==='whatsapp'?GENERAL_WHATSAPP_TEMPLATE:undefined,templateLanguage:r.channel==='whatsapp'?GENERAL_WHATSAPP_LANGUAGE:undefined,variables:r.channel==='whatsapp'?(Array.isArray(vars)?vars:[]):undefined} as CommunicationJob}}

export async function dispatchSecurityCameraNotifications(env:Env,limit=50){
 const db=env.FINANCE_DB,rows=await db.prepare(`SELECT q.*,p.name policy_name FROM security_camera_notification_queue q JOIN security_camera_notification_policies p ON p.id=q.policy_id WHERE q.status IN ('queued','retry') AND q.not_before<=CURRENT_TIMESTAMP AND q.channel IN ('sms','whatsapp') ORDER BY CASE JSON_EXTRACT(q.payload_json,'$.severity') WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,q.created_at LIMIT ?`).bind(Math.max(1,Math.min(200,limit))).all<any>();let submitted=0,failed=0;
 for(const row of rows.results){const claim=await db.prepare(`UPDATE security_camera_notification_queue SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('queued','retry')`).bind(row.id).run();if(!(claim.meta?.changes))continue;try{
   const prior=await existingJob(db,row);if(prior){if(["sent","delivered"].includes(prior.row.delivery_status)){await db.prepare(`UPDATE security_camera_notification_queue SET status='sent',provider_status=?,provider_error=NULL,delivered_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(prior.row.delivery_status,row.id).run();continue}await db.prepare(`UPDATE communication_deliveries SET status='queued',last_error=NULL,failed_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(prior.row.delivery_id).run();await db.prepare(`UPDATE communication_campaigns SET status='sending',completed_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(prior.row.campaign_id).run();await env.COMMUNICATION_QUEUE.send(prior.job,{contentType:"json"});await db.prepare(`UPDATE security_camera_notification_queue SET status='submitted',provider_status='queued',provider_error=NULL,last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.id).run();submitted++;continue}
   const phone=cleanPhone(row.recipient);if(!phone)throw new Error("SMS/WhatsApp escalation recipient must be a valid phone number");if(row.channel==='sms'&&(!env.EGOSMS_USERNAME||!env.EGOSMS_PASSWORD||!env.EGOSMS_SENDER_ID))throw new Error("EgoSMS provider is not configured");if(row.channel==='whatsapp'&&(!env.WHATSAPP_SUPPORT_APP_KEY||!env.WHATSAPP_SUPPORT_HUB_URL))throw new Error("WhatsApp Hub provider is not configured");const payload=parse(row.payload_json,{}),org=await db.prepare(`SELECT name FROM organizations WHERE id=?`).bind(row.organization_id).first<any>(),campaignId=createId("cmp"),recipientId=createId("cmr"),deliveryId=createId("cmd"),subject=`Security alert · ${String(payload.severity||'warning').toUpperCase()}`,message=String(payload.message||`Security camera alert ${row.alert_id}`),sender=org?.name||"Ledgerly Security",provider=row.channel==='sms'?"egosms":"ulib_whatsapp_hub",variables=row.channel==='whatsapp'?["Security team",sender,subject,message]:[];
   await db.batch([db.prepare(`INSERT INTO communication_campaigns(id,organization_id,message_type_id,type_key,module_key,name,sender_name,subject_template,message_template,channels_json,audience_kind,audience_json,status,started_at,recipient_count,skipped_count,delivery_count,created_by,updated_by) VALUES(?,?,NULL,?,?,?,?,?,?,?,?,?,'sending',CURRENT_TIMESTAMP,1,0,1,NULL,NULL)`).bind(campaignId,row.organization_id,"security_camera_alert","security-camera",`Security alert · ${row.policy_name}`,sender,subject,message,JSON.stringify([row.channel]),"security_direct",JSON.stringify({cameraNotificationId:row.id,alertId:row.alert_id})),db.prepare(`INSERT INTO communication_recipients(id,organization_id,campaign_id,recipient_type,recipient_id,related_entity_type,related_entity_id,recipient_name,phone,data_json,status) VALUES(?,?,?,?,?,?,?,?,?,?, 'queued')`).bind(recipientId,row.organization_id,campaignId,"security_contact",null,"security_camera_alert",row.alert_id,"Security contact",phone,JSON.stringify(payload)),db.prepare(`INSERT INTO communication_deliveries(id,organization_id,campaign_id,recipient_snapshot_id,channel,recipient_phone,provider,template_name,template_language,template_variables_json,rendered_subject,rendered_message,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'queued')`).bind(deliveryId,row.organization_id,campaignId,recipientId,row.channel,phone,provider,row.channel==='whatsapp'?GENERAL_WHATSAPP_TEMPLATE:null,row.channel==='whatsapp'?GENERAL_WHATSAPP_LANGUAGE:null,JSON.stringify(variables),subject,message),db.prepare(`UPDATE security_camera_notification_queue SET communication_campaign_id=?,communication_delivery_id=?,provider_status='queued',provider_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(campaignId,deliveryId,row.id)]);const job:CommunicationJob={kind:"communication",deliveryId,organizationId:row.organization_id,campaignId,recipientSnapshotId:recipientId,channel:row.channel,recipient:phone,senderName:sender,subject,message,templateName:row.channel==='whatsapp'?GENERAL_WHATSAPP_TEMPLATE:undefined,templateLanguage:row.channel==='whatsapp'?GENERAL_WHATSAPP_LANGUAGE:undefined,variables:row.channel==='whatsapp'?variables:undefined};await env.COMMUNICATION_QUEUE.send(job,{contentType:"json"});await db.prepare(`UPDATE security_camera_notification_queue SET status='submitted',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.id).run();submitted++;
  }catch(error){const msg=error instanceof Error?error.message:String(error),attempts=Number(row.attempts||0)+1,next=attempts>=5?"failed":"retry",delay=Math.min(3600,30*2**Math.min(6,attempts));await db.prepare(`UPDATE security_camera_notification_queue SET status=?,provider_status='failed',provider_error=?,last_error=?,not_before=datetime('now',?),updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(next,msg.slice(0,1000),msg.slice(0,1000),`+${delay} seconds`,row.id).run();failed++}}
 await reconcileSecurityCameraNotifications(db);return{submitted,failed,scanned:rows.results.length};
}
export async function reconcileSecurityCameraNotifications(db:D1Database){const rows=await db.prepare(`SELECT q.id,q.communication_delivery_id,d.status,d.last_error,d.sent_at FROM security_camera_notification_queue q JOIN communication_deliveries d ON d.id=q.communication_delivery_id WHERE q.communication_delivery_id IS NOT NULL AND q.status IN ('submitted','processing','retry') LIMIT 500`).all<any>();let changed=0;for(const row of rows.results){const delivery=String(row.status||"");let status="submitted";if(["sent","delivered"].includes(delivery))status="sent";else if(delivery==="failed")status="failed";else if(delivery==="sending")status="processing";const r=await db.prepare(`UPDATE security_camera_notification_queue SET status=?,provider_status=?,provider_error=?,delivered_at=CASE WHEN ?='sent' THEN COALESCE(?,CURRENT_TIMESTAMP) ELSE delivered_at END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND (status!=? OR COALESCE(provider_status,'')!=?)`).bind(status,delivery,row.last_error||null,status,row.sent_at||null,row.id,status,delivery).run();changed+=Number(r.meta?.changes||0)}return{changed}}
