import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../../../src/types";
import { AppError } from "../../../src/lib/errors";
import { createId } from "../../../src/lib/ids";
import { auditStatement } from "../../../src/services/audit";
import { GENERAL_WHATSAPP_LANGUAGE, GENERAL_WHATSAPP_TEMPLATE, dispatchCampaign, ensureBuiltinMessageTypes, previewAudience, retryFailedDeliveries, type AudienceSpec, type Channel } from "./service";

export const communicationRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();

function access(level:"read"|"send"|"manage"){
  return async (c:any,next:any)=>{const p=c.get("principal");if(p.role==="owner"||p.role==="admin"){await next();return}const core=level==="read"?["communications:read","communications:write"]:["communications:write"];if(core.some((x:string)=>p.scopes.includes(x))){await next();return}const perm=`school.communications:${level}`;const row=await c.env.FINANCE_DB.prepare(`SELECT 1 FROM school_user_roles ur JOIN school_role_permissions rp ON rp.organization_id=ur.organization_id AND rp.role_id=ur.role_id WHERE ur.organization_id=? AND ur.user_id=? AND rp.permission=? AND rp.effect='allow' AND (ur.starts_at IS NULL OR ur.starts_at<=CURRENT_TIMESTAMP) AND (ur.ends_at IS NULL OR ur.ends_at>=CURRENT_TIMESTAMP) UNION ALL SELECT 1 FROM school_temporary_permissions tp WHERE tp.organization_id=? AND tp.user_id=? AND tp.permission=? AND tp.revoked_at IS NULL AND tp.starts_at<=CURRENT_TIMESTAMP AND tp.ends_at>=CURRENT_TIMESTAMP LIMIT 1`).bind(p.organizationId,p.userId,perm,p.organizationId,p.userId,perm).first();if(!row)throw new AppError(403,"FORBIDDEN",`Missing communication permission: ${perm}`);await next()}
}
communicationRoutes.use("*",access("read"));

const audienceSchema=z.object({kind:z.string().min(2).max(80),academicYearId:z.string().optional().nullable(),termId:z.string().optional().nullable(),classId:z.string().optional().nullable(),streamId:z.string().optional().nullable(),campusId:z.string().optional().nullable(),departmentId:z.string().optional().nullable(),examId:z.string().optional().nullable(),taskId:z.string().optional().nullable(),incidentId:z.string().optional().nullable(),attendanceDate:z.string().optional().nullable(),attendanceStatus:z.string().optional().nullable(),studentIds:z.array(z.string()).max(1000).optional(),staffIds:z.array(z.string()).max(1000).optional(),userIds:z.array(z.string()).max(1000).optional(),contactIds:z.array(z.string()).max(1000).optional(),recipientMode:z.enum(["primary_guardian","all_guardians","student_direct","guardians_and_student"]).optional(),minimumBalanceMinor:z.number().int().nonnegative().optional(),teacherOnly:z.boolean().optional()});
const channelsSchema=z.array(z.enum(["sms","whatsapp"])).min(1).max(2).transform(v=>[...new Set(v)] as Channel[]);

async function audit(c:any,action:string,entityId:string,after?:unknown){const p=c.get("principal");await auditStatement(c.env.FINANCE_DB,{organizationId:p.organizationId,actorId:p.userId,action,entityType:"communication_campaign",entityId,requestId:c.get("requestId"),after}).run()}

communicationRoutes.get("/manifest",async c=>c.json({data:{name:"Messages & Notifications",version:"1.0.0",channels:["sms","whatsapp"],whatsapp:{templateName:GENERAL_WHATSAPP_TEMPLATE,language:GENERAL_WHATSAPP_LANGUAGE,status:"approved",category:"UTILITY",variables:["Recipient name","Application or organization name","Update subject","Update message"]}}}));

communicationRoutes.get("/providers",async c=>c.json({data:{sms:{provider:"EgoSMS",configured:Boolean(c.env.EGOSMS_USERNAME&&c.env.EGOSMS_PASSWORD&&c.env.EGOSMS_SENDER_ID)},whatsapp:{provider:"ULIB WhatsApp Hub",configured:Boolean(c.env.WHATSAPP_SUPPORT_HUB_URL&&c.env.WHATSAPP_SUPPORT_APP_KEY),templateName:GENERAL_WHATSAPP_TEMPLATE,language:GENERAL_WHATSAPP_LANGUAGE,status:"approved"}}}));

communicationRoutes.get("/message-types",async c=>{const p=c.get("principal");await ensureBuiltinMessageTypes(c.env.FINANCE_DB,p.organizationId,p.userId);const rows=await c.env.FINANCE_DB.prepare(`SELECT id,type_key AS typeKey,name,module_key AS moduleKey,category,audience_kind AS audienceKind,subject_template AS subjectTemplate,message_template AS messageTemplate,audience_defaults_json AS audienceDefaultsJson,system_type AS systemType,active FROM communication_message_types WHERE organization_id=? AND active=1 ORDER BY CASE category WHEN 'urgent' THEN 0 WHEN 'finance' THEN 1 WHEN 'academic' THEN 2 ELSE 3 END,module_key,name`).bind(p.organizationId).all<any>();return c.json({data:rows.results.map(r=>({...r,audienceDefaults:JSON.parse(r.audienceDefaultsJson||"{}") }))})});

communicationRoutes.post("/message-types",access("manage"),async c=>{const p=c.get("principal"),s=z.object({typeKey:z.string().regex(/^[a-z0-9._-]+$/).max(80),name:z.string().min(2).max(120),moduleKey:z.string().max(80).default("custom"),category:z.string().max(80).default("general"),audienceKind:z.enum(["students","staff","organization_users","contacts","fee_balances","published_results","attendance","discipline","work_users"]),subjectTemplate:z.string().min(1).max(200),messageTemplate:z.string().min(1).max(2000),audienceDefaults:z.record(z.string(),z.unknown()).default({})}).safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid message type",s.error.flatten());const id=createId("cmt"),v=s.data;await c.env.FINANCE_DB.prepare(`INSERT INTO communication_message_types (id,organization_id,type_key,name,module_key,category,audience_kind,subject_template,message_template,audience_defaults_json,system_type,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,0,?)`).bind(id,p.organizationId,v.typeKey,v.name,v.moduleKey,v.category,v.audienceKind,v.subjectTemplate,v.messageTemplate,JSON.stringify(v.audienceDefaults),p.userId).run();return c.json({data:{id,...v}},201)});

communicationRoutes.get("/context",async c=>{const p=c.get("principal");const [org,years,terms,classes,streams,departments,exams,staff,tasks,contacts]=await Promise.all([
  c.env.FINANCE_DB.prepare("SELECT id,name,base_currency AS currency,timezone FROM organizations WHERE id=?").bind(p.organizationId).first(),
  c.env.FINANCE_DB.prepare("SELECT id,name,code,is_current AS isCurrent,status FROM school_academic_years WHERE organization_id=? ORDER BY starts_on DESC").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,name,code,academic_year_id AS academicYearId,is_current AS isCurrent,status FROM school_terms WHERE organization_id=? ORDER BY starts_on DESC").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,name,code,academic_year_id AS academicYearId,campus_id AS campusId FROM school_classes WHERE organization_id=? AND active=1 ORDER BY name").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,name,code,class_id AS classId,campus_id AS campusId FROM school_streams WHERE organization_id=? AND active=1 ORDER BY name").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,name,code FROM school_departments WHERE organization_id=? AND active=1 ORDER BY name").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,name,status,academic_year_id AS academicYearId,term_id AS termId FROM exm_exams WHERE organization_id=? ORDER BY created_at DESC LIMIT 100").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,staff_number AS staffNumber,first_name||' '||last_name AS name,is_teacher AS isTeacher,department_id AS departmentId FROM school_staff_profiles WHERE organization_id=? AND deleted_at IS NULL AND employment_status='active' ORDER BY last_name,first_name LIMIT 500").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT id,task_number AS taskNumber,title,status FROM work_tasks WHERE organization_id=? AND archived_at IS NULL ORDER BY updated_at DESC LIMIT 100").bind(p.organizationId).all(),
  c.env.FINANCE_DB.prepare("SELECT c.id,c.name,c.type,cp.phone FROM contacts c LEFT JOIN contact_people cp ON cp.organization_id=c.organization_id AND cp.contact_id=c.id AND cp.is_primary=1 WHERE c.organization_id=? AND c.active=1 AND c.archived_at IS NULL ORDER BY c.name LIMIT 500").bind(p.organizationId).all()
]);return c.json({data:{organization:org,years:years.results,terms:terms.results,classes:classes.results,streams:streams.results,departments:departments.results,exams:exams.results,staff:staff.results,tasks:tasks.results,contacts:contacts.results}})});

communicationRoutes.post("/audience/preview",async c=>{const p=c.get("principal"),s=z.object({audience:audienceSchema,channels:channelsSchema}).safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid audience preview",s.error.flatten());return c.json({data:await previewAudience(c.env.FINANCE_DB,p.organizationId,s.data.audience as AudienceSpec,s.data.channels)})});

communicationRoutes.get("/summary",async c=>{const p=c.get("principal"),x=await c.env.FINANCE_DB.prepare(`SELECT COUNT(*) AS campaigns,SUM(CASE WHEN status='scheduled' THEN 1 ELSE 0 END) AS scheduled,SUM(sent_count) AS sent,SUM(failed_count) AS failed FROM communication_campaigns WHERE organization_id=?`).bind(p.organizationId).first<any>(),today=await c.env.FINANCE_DB.prepare(`SELECT COUNT(*) AS deliveries,SUM(CASE WHEN status IN ('sent','delivered') THEN 1 ELSE 0 END) AS sent,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) AS failed FROM communication_deliveries WHERE organization_id=? AND created_at>=date('now')`).bind(p.organizationId).first<any>();return c.json({data:{campaigns:Number(x?.campaigns||0),scheduled:Number(x?.scheduled||0),sent:Number(x?.sent||0),failed:Number(x?.failed||0),todayDeliveries:Number(today?.deliveries||0),todaySent:Number(today?.sent||0),todayFailed:Number(today?.failed||0)}})});

communicationRoutes.get("/campaigns",async c=>{const p=c.get("principal"),status=c.req.query("status"),limit=Math.max(1,Math.min(200,Number(c.req.query("limit")||50))),offset=Math.max(0,Number(c.req.query("offset")||0)),rows=await c.env.FINANCE_DB.prepare(`SELECT c.id,c.type_key AS typeKey,c.module_key AS moduleKey,c.name,c.sender_name AS senderName,c.subject_template AS subjectTemplate,c.channels_json AS channelsJson,c.audience_kind AS audienceKind,c.status,c.scheduled_at AS scheduledAt,c.started_at AS startedAt,c.completed_at AS completedAt,c.recipient_count AS recipientCount,c.skipped_count AS skippedCount,c.delivery_count AS deliveryCount,c.sent_count AS sentCount,c.failed_count AS failedCount,c.created_at AS createdAt,u.display_name AS createdByName FROM communication_campaigns c LEFT JOIN users u ON u.id=c.created_by WHERE c.organization_id=? AND (? IS NULL OR c.status=?) ORDER BY c.created_at DESC LIMIT ? OFFSET ?`).bind(p.organizationId,status||null,status||null,limit,offset).all<any>();const count=await c.env.FINANCE_DB.prepare("SELECT COUNT(*) AS total FROM communication_campaigns WHERE organization_id=? AND (? IS NULL OR status=?)").bind(p.organizationId,status||null,status||null).first<any>();return c.json({data:{items:rows.results.map(r=>({...r,channels:JSON.parse(r.channelsJson||"[]")})),pagination:{limit,offset,total:Number(count?.total||0)}}})});

communicationRoutes.get("/campaigns/:id",async c=>{const p=c.get("principal"),id=c.req.param("id"),campaign=await c.env.FINANCE_DB.prepare(`SELECT * FROM communication_campaigns WHERE id=? AND organization_id=?`).bind(id,p.organizationId).first<any>();if(!campaign)throw new AppError(404,"CAMPAIGN_NOT_FOUND","Communication campaign not found");const recipients=await c.env.FINANCE_DB.prepare(`SELECT id,recipient_type AS recipientType,recipient_id AS recipientId,related_entity_type AS relatedEntityType,related_entity_id AS relatedEntityId,recipient_name AS recipientName,phone,status,skip_reason AS skipReason,data_json AS dataJson FROM communication_recipients WHERE campaign_id=? AND organization_id=? ORDER BY recipient_name LIMIT 500`).bind(id,p.organizationId).all<any>(),deliveries=await c.env.FINANCE_DB.prepare(`SELECT d.id,d.channel,d.recipient_phone AS recipientPhone,d.provider,d.template_name AS templateName,d.template_language AS templateLanguage,d.rendered_subject AS renderedSubject,d.rendered_message AS renderedMessage,d.status,d.attempts,d.provider_message_id AS providerMessageId,d.last_error AS lastError,d.sent_at AS sentAt,d.failed_at AS failedAt,r.recipient_name AS recipientName FROM communication_deliveries d JOIN communication_recipients r ON r.id=d.recipient_snapshot_id WHERE d.campaign_id=? AND d.organization_id=? ORDER BY d.created_at DESC LIMIT 1000`).bind(id,p.organizationId).all<any>();return c.json({data:{...campaign,channels:JSON.parse(campaign.channels_json||"[]"),audience:JSON.parse(campaign.audience_json||"{}"),recipients:recipients.results.map(r=>({...r,data:JSON.parse(r.dataJson||"{}")})),deliveries:deliveries.results}})});

communicationRoutes.post("/campaigns",access("send"),async c=>{const p=c.get("principal");await ensureBuiltinMessageTypes(c.env.FINANCE_DB,p.organizationId,p.userId);const s=z.object({typeKey:z.string().min(1).max(80),name:z.string().min(1).max(160).optional(),senderName:z.string().min(1).max(160).optional(),subject:z.string().min(1).max(200).optional(),message:z.string().min(1).max(2000).optional(),channels:channelsSchema,audience:audienceSchema,scheduledAt:z.string().optional().nullable(),sendNow:z.boolean().default(false)}).safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid communication campaign",s.error.flatten());const v=s.data,type=await c.env.FINANCE_DB.prepare("SELECT * FROM communication_message_types WHERE organization_id=? AND type_key=? AND active=1").bind(p.organizationId,v.typeKey).first<any>();if(!type)throw new AppError(404,"MESSAGE_TYPE_NOT_FOUND","Message type not found");const org=await c.env.FINANCE_DB.prepare("SELECT name FROM organizations WHERE id=?").bind(p.organizationId).first<{name:string}>();const id=createId("cmp"),audience={...JSON.parse(type.audience_defaults_json||"{}"),...v.audience,kind:v.audience.kind||type.audience_kind},now=Date.now(),schedule=v.scheduledAt?new Date(v.scheduledAt).getTime():null,status=!v.sendNow&&schedule&&schedule>now?"scheduled":"draft";await c.env.FINANCE_DB.prepare(`INSERT INTO communication_campaigns (id,organization_id,message_type_id,type_key,module_key,name,sender_name,subject_template,message_template,channels_json,audience_kind,audience_json,status,scheduled_at,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,p.organizationId,type.id,type.type_key,type.module_key,v.name||type.name,v.senderName||org?.name||"Ledgerly",v.subject||type.subject_template,v.message||type.message_template,JSON.stringify(v.channels),audience.kind,JSON.stringify(audience),status,v.scheduledAt||null,p.userId,p.userId).run();await audit(c,"communications.campaign.created",id,{typeKey:v.typeKey,channels:v.channels,audience,status});if(v.sendNow){const result=await dispatchCampaign(c.env,id);return c.json({data:{id,...result}},201)}return c.json({data:{id,status,scheduledAt:v.scheduledAt||null}},201)});

communicationRoutes.post("/campaigns/:id/send",access("send"),async c=>{const p=c.get("principal"),id=c.req.param("id"),row=await c.env.FINANCE_DB.prepare("SELECT id FROM communication_campaigns WHERE id=? AND organization_id=?").bind(id,p.organizationId).first();if(!row)throw new AppError(404,"CAMPAIGN_NOT_FOUND","Communication campaign not found");const data=await dispatchCampaign(c.env,id);await audit(c,"communications.campaign.dispatched",id,data);return c.json({data})});
communicationRoutes.post("/campaigns/:id/retry-failed",access("send"),async c=>{const p=c.get("principal"),id=c.req.param("id"),count=await retryFailedDeliveries(c.env,p.organizationId,id);await audit(c,"communications.campaign.retry_failed",id,{count});return c.json({data:{queued:count}})});
communicationRoutes.post("/campaigns/:id/cancel",access("send"),async c=>{const p=c.get("principal"),id=c.req.param("id"),r=await c.env.FINANCE_DB.prepare("UPDATE communication_campaigns SET status='cancelled',updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND status IN ('draft','scheduled')").bind(p.userId,id,p.organizationId).run();if(!r.meta.changes)throw new AppError(409,"CANNOT_CANCEL","Only draft or scheduled campaigns can be cancelled");await audit(c,"communications.campaign.cancelled",id);return c.json({data:{id,status:"cancelled"}})});

communicationRoutes.get("/deliveries",async c=>{const p=c.get("principal"),channel=c.req.query("channel"),status=c.req.query("status"),limit=Math.max(1,Math.min(500,Number(c.req.query("limit")||100))),rows=await c.env.FINANCE_DB.prepare(`SELECT d.id,d.campaign_id AS campaignId,c.name AS campaignName,r.recipient_name AS recipientName,d.recipient_phone AS recipientPhone,d.channel,d.provider,d.status,d.attempts,d.provider_message_id AS providerMessageId,d.last_error AS lastError,d.sent_at AS sentAt,d.created_at AS createdAt FROM communication_deliveries d JOIN communication_campaigns c ON c.id=d.campaign_id JOIN communication_recipients r ON r.id=d.recipient_snapshot_id WHERE d.organization_id=? AND (? IS NULL OR d.channel=?) AND (? IS NULL OR d.status=?) ORDER BY d.created_at DESC LIMIT ?`).bind(p.organizationId,channel||null,channel||null,status||null,status||null,limit).all();return c.json({data:rows.results})});

communicationRoutes.put("/preferences/:recipientType/:recipientId",access("manage"),async c=>{const p=c.get("principal"),recipientType=c.req.param("recipientType"),recipientId=c.req.param("recipientId"),s=z.object({smsEnabled:z.boolean().default(true),whatsappEnabled:z.boolean().default(true),doNotContact:z.boolean().default(false),quietHours:z.record(z.string(),z.unknown()).default({})}).safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid recipient preference",s.error.flatten());await c.env.FINANCE_DB.prepare(`INSERT INTO communication_preferences (organization_id,recipient_type,recipient_id,sms_enabled,whatsapp_enabled,do_not_contact,quiet_hours_json,updated_by) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(organization_id,recipient_type,recipient_id) DO UPDATE SET sms_enabled=excluded.sms_enabled,whatsapp_enabled=excluded.whatsapp_enabled,do_not_contact=excluded.do_not_contact,quiet_hours_json=excluded.quiet_hours_json,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(p.organizationId,recipientType,recipientId,s.data.smsEnabled?1:0,s.data.whatsappEnabled?1:0,s.data.doNotContact?1:0,JSON.stringify(s.data.quietHours),p.userId).run();return c.json({data:{recipientType,recipientId,...s.data}})});
