import {useState} from "react";
import {Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View,type TextInputProps} from "react-native";

export type Option={label:string;value:string;detail?:string};
export function Card({children,style}:{children:any;style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function SectionTitle({title,subtitle,action}:{title:string;subtitle?:string;action?:any}){return <View style={s.sectionHead}><View style={{flex:1}}><Text style={s.sectionTitle}>{title}</Text>{subtitle?<Text style={s.sectionSub}>{subtitle}</Text>:null}</View>{action}</View>}
export function Pill({text,tone="neutral"}:{text:string;tone?:"good"|"warn"|"bad"|"neutral"}){return <View style={[s.pill,tone==="good"&&s.pillGood,tone==="warn"&&s.pillWarn,tone==="bad"&&s.pillBad]}><Text style={[s.pillText,tone==="good"&&s.pillGoodText,tone==="warn"&&s.pillWarnText,tone==="bad"&&s.pillBadText]}>{text}</Text></View>}
export function PrimaryButton({title,onPress,disabled=false,compact=false,danger=false}:{title:string;onPress:()=>void;disabled?:boolean;compact?:boolean;danger?:boolean}){return <TouchableOpacity activeOpacity={.85} disabled={disabled} onPress={onPress} style={[s.button,compact&&s.buttonCompact,danger&&s.buttonDanger,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></TouchableOpacity>}
export function SecondaryButton({title,onPress,compact=false}:{title:string;onPress:()=>void;compact?:boolean}){return <TouchableOpacity activeOpacity={.85} onPress={onPress} style={[s.secondary,compact&&s.buttonCompact]}><Text style={s.secondaryText}>{title}</Text></TouchableOpacity>}
export function Field({label,...props}:TextInputProps&{label:string}){return <View style={s.fieldWrap}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#98a7a0" {...props} style={[s.input,props.multiline&&s.multiline,props.style]}/></View>}
export function SelectField({label,value,options,onChange,placeholder="Select",disabled=false}:{label:string;value?:string;options:Option[];onChange:(v:string)=>void;placeholder?:string;disabled?:boolean}){
  const[open,setOpen]=useState(false);
  const current=options.find(x=>x.value===value);
  return <View style={s.fieldWrap}><Text style={s.label}>{label}</Text><TouchableOpacity disabled={disabled} activeOpacity={.85} onPress={()=>setOpen(true)} style={[s.select,disabled&&s.disabled]}><Text numberOfLines={1} style={[s.selectText,!current&&s.placeholder]}>{current?.label||placeholder}</Text><Text style={s.chev}>⌄</Text></TouchableOpacity>
    <Modal visible={open} animationType="slide" transparent onRequestClose={()=>setOpen(false)}><Pressable style={s.modalShade} onPress={()=>setOpen(false)}><Pressable style={s.sheet} onPress={()=>{}}><View style={s.sheetBar}/><Text style={s.sheetTitle}>{label}</Text><ScrollView contentContainerStyle={{paddingBottom:30}}>{options.map(o=><TouchableOpacity key={o.value} style={[s.option,o.value===value&&s.optionActive]} onPress={()=>{onChange(o.value);setOpen(false)}}><View style={{flex:1}}><Text style={[s.optionText,o.value===value&&s.optionTextActive]}>{o.label}</Text>{o.detail?<Text style={s.optionDetail}>{o.detail}</Text>:null}</View>{o.value===value?<Text style={s.tick}>✓</Text>:null}</TouchableOpacity>)}</ScrollView></Pressable></Pressable></Modal>
  </View>
}
export function Empty({title,copy}:{title:string;copy:string}){return <View style={s.empty}><Text style={s.emptyIcon}>○</Text><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyCopy}>{copy}</Text></View>}
export function ErrorNotice({message,onRetry}:{message:string;onRetry?:()=>void}){return <View style={s.error}><Text style={s.errorTitle}>Couldn’t load this section</Text><Text style={s.errorText}>{message}</Text>{onRetry?<TouchableOpacity onPress={onRetry}><Text style={s.retry}>Retry</Text></TouchableOpacity>:null}</View>}
const s=StyleSheet.create({
 card:{backgroundColor:"#fff",borderRadius:20,borderWidth:1,borderColor:"#dfe7e2",padding:16},
 sectionHead:{flexDirection:"row",alignItems:"center",marginBottom:12},sectionTitle:{fontSize:18,fontWeight:"900",color:"#173127",letterSpacing:-.3},sectionSub:{fontSize:11,lineHeight:16,color:"#7a8c83",marginTop:3},
 pill:{alignSelf:"flex-start",paddingHorizontal:9,paddingVertical:5,borderRadius:20,backgroundColor:"#eef2f0"},pillText:{fontSize:9,fontWeight:"900",color:"#5f7068",textTransform:"uppercase"},pillGood:{backgroundColor:"#e7f7ef"},pillGoodText:{color:"#158859"},pillWarn:{backgroundColor:"#fff5df"},pillWarnText:{color:"#a96808"},pillBad:{backgroundColor:"#ffeded"},pillBadText:{color:"#b63535"},
 button:{minHeight:48,borderRadius:14,backgroundColor:"#148e5b",alignItems:"center",justifyContent:"center",paddingHorizontal:16},buttonCompact:{minHeight:38,paddingHorizontal:12,borderRadius:12},buttonDanger:{backgroundColor:"#b63b3b"},buttonText:{color:"white",fontSize:12,fontWeight:"900"},secondary:{minHeight:48,borderRadius:14,borderWidth:1,borderColor:"#cad8d1",backgroundColor:"#f8faf9",alignItems:"center",justifyContent:"center",paddingHorizontal:16},secondaryText:{fontSize:12,fontWeight:"900",color:"#28483a"},disabled:{opacity:.45},
 fieldWrap:{marginBottom:12},label:{fontSize:9,fontWeight:"900",textTransform:"uppercase",letterSpacing:.8,color:"#708078",marginBottom:6},input:{minHeight:48,borderRadius:14,borderWidth:1,borderColor:"#d9e3de",backgroundColor:"#fbfcfb",paddingHorizontal:13,color:"#193127",fontSize:12,fontWeight:"700"},multiline:{minHeight:88,textAlignVertical:"top",paddingTop:12},select:{minHeight:48,borderRadius:14,borderWidth:1,borderColor:"#d9e3de",backgroundColor:"#fbfcfb",paddingHorizontal:13,flexDirection:"row",alignItems:"center"},selectText:{flex:1,color:"#193127",fontSize:12,fontWeight:"800"},placeholder:{color:"#98a7a0"},chev:{color:"#688078",fontSize:18},
 modalShade:{flex:1,backgroundColor:"rgba(4,20,14,.45)",justifyContent:"flex-end"},sheet:{maxHeight:"72%",backgroundColor:"white",borderTopLeftRadius:26,borderTopRightRadius:26,padding:18},sheetBar:{width:42,height:4,borderRadius:2,backgroundColor:"#d8dfdb",alignSelf:"center",marginBottom:13},sheetTitle:{fontSize:18,fontWeight:"900",color:"#173127",marginBottom:10},option:{minHeight:56,borderBottomWidth:1,borderBottomColor:"#edf1ef",flexDirection:"row",alignItems:"center",paddingVertical:10},optionActive:{backgroundColor:"#f2fbf7",marginHorizontal:-8,paddingHorizontal:8,borderRadius:12},optionText:{fontSize:13,fontWeight:"800",color:"#334c41"},optionTextActive:{color:"#148e5b"},optionDetail:{fontSize:10,color:"#829189",marginTop:2},tick:{fontSize:16,fontWeight:"900",color:"#148e5b"},
 empty:{alignItems:"center",paddingVertical:30,paddingHorizontal:18},emptyIcon:{fontSize:28,color:"#a4b3ac",fontWeight:"300"},emptyTitle:{fontSize:14,fontWeight:"900",color:"#31483e",marginTop:7},emptyCopy:{fontSize:11,lineHeight:17,color:"#89968f",textAlign:"center",marginTop:4},
 error:{padding:14,borderRadius:16,backgroundColor:"#fff3f1",borderWidth:1,borderColor:"#f2d2cd"},errorTitle:{fontSize:12,fontWeight:"900",color:"#8d312a"},errorText:{fontSize:10,lineHeight:15,color:"#9c5a54",marginTop:3},retry:{fontSize:11,fontWeight:"900",color:"#148e5b",marginTop:8}
});
