import { sha256 } from "../../../src/lib/crypto";

const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
export function randomBase32(bytes=20){const a=new Uint8Array(bytes);crypto.getRandomValues(a);let bits=0,value=0,out="";for(const b of a){value=(value<<8)|b;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5}}if(bits)out+=alphabet[(value<<(5-bits))&31];return out}
function decodeBase32(input:string){let bits=0,value=0,out:number[]=[];for(const ch of input.replace(/=+$/,"")){const idx=alphabet.indexOf(ch.toUpperCase());if(idx<0)continue;value=(value<<5)|idx;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}}return new Uint8Array(out)}
async function encryptionKey(secret:string){const raw=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`school-mfa:${secret}`));return crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["encrypt","decrypt"])}
export async function encryptMfaSecret(appSecret:string,secret:string){const iv=new Uint8Array(12);crypto.getRandomValues(iv);const enc=await crypto.subtle.encrypt({name:"AES-GCM",iv},await encryptionKey(appSecret),new TextEncoder().encode(secret));return `${btoa(String.fromCharCode(...iv))}.${btoa(String.fromCharCode(...new Uint8Array(enc)))}`}
export async function decryptMfaSecret(appSecret:string,value:string){const [a,b]=value.split(".");const iv=Uint8Array.from(atob(a),c=>c.charCodeAt(0)),cipher=Uint8Array.from(atob(b),c=>c.charCodeAt(0));const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv},await encryptionKey(appSecret),cipher);return new TextDecoder().decode(plain)}
export async function verifyTotp(secret:string,code:string,now=Date.now()){const key=await crypto.subtle.importKey("raw",decodeBase32(secret),{name:"HMAC",hash:"SHA-1"},false,["sign"]);for(let d=-1;d<=1;d++){const counter=Math.floor(now/30000)+d,b=new ArrayBuffer(8),v=new DataView(b);v.setUint32(4,counter,false);const mac=new Uint8Array(await crypto.subtle.sign("HMAC",key,b)),off=mac[mac.length-1]&15,n=((mac[off]&127)<<24)|((mac[off+1]&255)<<16)|((mac[off+2]&255)<<8)|(mac[off+3]&255);if(String(n%1_000_000).padStart(6,"0")===code.replace(/\s/g,""))return true}return false}
export async function hashRecoveryCode(code:string){return sha256(`school-recovery:${code.trim().toUpperCase()}`)}
