import { Hono } from "hono";
import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { AppEnv } from "../../http/types.js";
import type { Runtime } from "../../runtime.js";
import { createId, requireScope } from "../core-identity/security.js";

function csvEscape(value:unknown){return `"${String(value??"").replaceAll('"','""')}"`;}
async function audit(runtime:Runtime,org:string,user:string,action:string,id:string){await runtime.db.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4,'compliance_approval',$5)`,[createId("aud"),org,user,action,id]);}
export function createComplianceRoutes(runtime:Runtime){const r=new Hono<AppEnv>();
 r.get("/audit-logs",requireScope("admin:read"),async c=>{const p=c.get("principal"),limit=Math.min(Math.max(Number(c.req.query("limit")??100),1),1000),before=c.req.query("before")??"9999-12-31T23:59:59Z",q=await runtime.db.query(`SELECT id,actor_id AS "actorId",action,entity_type AS "entityType",entity_id AS "entityId",request_id AS "requestId",before_data AS before,after_data AS after,created_at AS "createdAt" FROM audit_logs WHERE organization_id=$1 AND created_at<$2::timestamptz ORDER BY created_at DESC LIMIT $3`,[p.organizationId,before,limit]);return c.json({data:q.rows,nextCursor:(q.rows.at(-1) as any)?.createdAt??null});});
 r.get("/audit-logs/export",requireScope("admin:read"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT created_at,actor_id,action,entity_type,entity_id,request_id,before_data,after_data FROM audit_logs WHERE organization_id=$1 ORDER BY created_at`,[p.organizationId]);const headers=["created_at","actor_id","action","entity_type","entity_id","request_id","before_data","after_data"];const text=[headers.join(","),...q.rows.map(row=>headers.map(h=>csvEscape((row as any)[h])).join(","))].join("\n");c.header("Content-Type","text/csv");c.header("Content-Disposition",'attachment; filename="audit-log.csv"');return c.body(text);});
 r.get("/approvals",requireScope("admin:read"),async c=>{const p=c.get("principal"),status=c.req.query("status"),params:unknown[]=[p.organizationId],where=["organization_id=$1"];if(status){params.push(status);where.push(`status=$${params.length}`);}const q=await runtime.db.query(`SELECT id,entity_type AS "entityType",entity_id AS "entityId",action,status,requested_by AS "requestedBy",reviewed_by AS "reviewedBy",reason,review_comment AS "reviewComment",created_at AS "createdAt",reviewed_at AS "reviewedAt" FROM compliance_approvals WHERE ${where.join(" AND ")} ORDER BY created_at DESC`,params);return c.json({data:q.rows});});
 r.post("/approvals",requireScope("admin:write"),async c=>{const s=z.object({entityType:z.string().max(80),entityId:z.string(),action:z.string().max(80),reason:z.string().max(1000).optional()}).safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid approval request",s.error.flatten());const p=c.get("principal"),rule=(await runtime.db.query<{requesterRoles:string[]}>(`SELECT requester_roles AS "requesterRoles" FROM segregation_rules WHERE organization_id=$1 AND entity_type=$2 AND action=$3 AND active=true ORDER BY created_at DESC LIMIT 1`,[p.organizationId,s.data.entityType,s.data.action])).rows[0];if(rule&&rule.requesterRoles.length&&!rule.requesterRoles.includes(p.role))throw new AppError(403,"REQUESTER_ROLE_NOT_ALLOWED","Your role cannot request this controlled action");const id=createId("apr");await runtime.db.query(`INSERT INTO compliance_approvals(id,organization_id,entity_type,entity_id,action,requested_by,reason) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,s.data.entityType,s.data.entityId,s.data.action,p.userId,s.data.reason??null]);return c.json({data:{id,status:"pending",...s.data}},201);});
 r.post("/approvals/:id/:decision",requireScope("admin:write"),async c=>{const decision=c.req.param("decision");if(!["approve","reject"].includes(decision))throw new AppError(404,"NOT_FOUND","Unknown decision");const s=z.object({comment:z.string().max(1000).optional()}).safeParse(await c.req.json().catch(()=>({})));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid approval decision");const p=c.get("principal"),id=c.req.param("id"),req=(await runtime.db.query<{requestedBy:string;entityType:string;action:string}>(`SELECT requested_by AS "requestedBy",entity_type AS "entityType",action FROM compliance_approvals WHERE id=$1 AND organization_id=$2 AND status='pending'`,[id,p.organizationId])).rows[0];if(!req)throw new AppError(409,"INVALID_STATE","Pending approval not found");if(req.requestedBy===p.userId)throw new AppError(409,"MAKER_CHECKER_VIOLATION","The maker cannot approve their own request");const rule=(await runtime.db.query<{approverRoles:string[]}>(`SELECT approver_roles AS "approverRoles" FROM segregation_rules WHERE organization_id=$1 AND entity_type=$2 AND action=$3 AND active=true ORDER BY created_at DESC LIMIT 1`,[p.organizationId,req.entityType,req.action])).rows[0];if(rule&&rule.approverRoles.length&&!rule.approverRoles.includes(p.role)&&!['owner','admin'].includes(p.role))throw new AppError(403,"APPROVER_ROLE_NOT_ALLOWED","Your role cannot approve this controlled action");const status=decision==="approve"?"approved":"rejected";await runtime.db.query(`UPDATE compliance_approvals SET status=$1,reviewed_by=$2,reviewed_at=CURRENT_TIMESTAMP,review_comment=$3 WHERE id=$4 AND organization_id=$5 AND status='pending'`,[status,p.userId,s.data.comment??null,id,p.organizationId]);await audit(runtime,p.organizationId,p.userId,`approval.${decision}d`,id);return c.json({data:{id,status}});});
 const rule=z.object({name:z.string().min(1).max(120),entityType:z.string().max(80),action:z.string().max(80),requesterRoles:z.array(z.string()),approverRoles:z.array(z.string()),active:z.boolean().default(true)});
 r.get("/segregation-rules",requireScope("admin:read"),async c=>{const p=c.get("principal"),q=await runtime.db.query(`SELECT id,name,entity_type AS "entityType",action,requester_roles AS "requesterRoles",approver_roles AS "approverRoles",active FROM segregation_rules WHERE organization_id=$1 ORDER BY name`,[p.organizationId]);return c.json({data:q.rows});});
 r.post("/segregation-rules",requireScope("admin:write"),async c=>{const s=rule.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid segregation rule",s.error.flatten());const p=c.get("principal"),id=createId("sod");await runtime.db.query(`INSERT INTO segregation_rules(id,organization_id,name,entity_type,action,requester_roles,approver_roles,active) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8)`,[id,p.organizationId,s.data.name,s.data.entityType,s.data.action,JSON.stringify(s.data.requesterRoles),JSON.stringify(s.data.approverRoles),s.data.active]);return c.json({data:{id,...s.data}},201);});
 r.put("/segregation-rules/:id",requireScope("admin:write"),async c=>{const s=rule.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid segregation rule",s.error.flatten());const p=c.get("principal"),id=c.req.param("id"),q=await runtime.db.query(`UPDATE segregation_rules SET name=$1,entity_type=$2,action=$3,requester_roles=$4::jsonb,approver_roles=$5::jsonb,active=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$7 AND organization_id=$8`,[s.data.name,s.data.entityType,s.data.action,JSON.stringify(s.data.requesterRoles),JSON.stringify(s.data.approverRoles),s.data.active,id,p.organizationId]);if(!q.rowCount)throw new AppError(404,"NOT_FOUND","Segregation rule not found");return c.json({data:{id,...s.data}});});
 const attachment=z.object({entityType:z.string().max(80),entityId:z.string(),fileName:z.string().min(1).max(255),contentType:z.string().max(120),objectKey:z.string().min(1).max(1000),sha256:z.string().regex(/^[a-f0-9]{64}$/i),retentionUntil:z.iso.date().optional()});
 r.get("/attachments",requireScope("admin:read"),async c=>{const p=c.get("principal"),entityType=c.req.query("entityType"),entityId=c.req.query("entityId"),params:unknown[]=[p.organizationId],where=["organization_id=$1"];if(entityType){params.push(entityType);where.push(`entity_type=$${params.length}`);}if(entityId){params.push(entityId);where.push(`entity_id=$${params.length}`);}const q=await runtime.db.query(`SELECT id,entity_type AS "entityType",entity_id AS "entityId",file_name AS "fileName",content_type AS "contentType",object_key AS "objectKey",sha256,retention_until::text AS "retentionUntil",uploaded_by AS "uploadedBy",created_at AS "createdAt" FROM attachments WHERE ${where.join(" AND ")} ORDER BY created_at DESC`,params);return c.json({data:q.rows});});
 r.post("/attachments",requireScope("admin:write"),async c=>{const s=attachment.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid evidence attachment",s.error.flatten());const p=c.get("principal"),id=createId("att");await runtime.db.query(`INSERT INTO attachments(id,organization_id,entity_type,entity_id,file_name,content_type,object_key,sha256,retention_until,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::date,$10)`,[id,p.organizationId,s.data.entityType,s.data.entityId,s.data.fileName,s.data.contentType,s.data.objectKey,s.data.sha256,s.data.retentionUntil??null,p.userId]);return c.json({data:{id,...s.data}},201);});
 return r;}
