import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Archive, ContactRound, Eye, MessageSquareText, Plus, Search } from "lucide-react";
import { can, errorText, get, post } from "../../../web/api";
import { useAuth } from "../../../web/auth";
import { Badge, Button, Card, EmptyState, Field, Modal, Notice, Spinner } from "../../../web/components/ui";

type Person = { id: string; entityId: string; contactId?: string | null; sourceModule: string; group: string; name: string; email?: string | null; phone?: string | null; code?: string | null; active: boolean; channels?: string[] };
type Source = { moduleKey: string; name: string; groups: string[]; channels: string[] };
type Capabilities = { enabledModules: Array<{ key: string; name: string; category: string }>; sources: Source[] };
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, char => char.toUpperCase());

export function ContactsPage() {
  const { principal } = useAuth(), write = can(principal, "contacts:write");
  const [capabilities, setCapabilities] = useState<Capabilities | null>(null), [people, setPeople] = useState<Person[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [search, setSearch] = useState(""), [source, setSource] = useState(""), [group, setGroup] = useState(""), [channel, setChannel] = useState(""), [open, setOpen] = useState(false), [selected, setSelected] = useState<Person | null>(null);
  const load = async () => { setLoading(true); setError(""); try { const [caps, rows] = await Promise.all([get<Capabilities>("/contacts/capabilities"), get<Person[]>("/contacts/people?limit=1000")]); setCapabilities(caps); setPeople(rows); } catch (reason) { setError(errorText(reason)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [principal?.organizationId]);
  const groups = useMemo(() => { const sources = capabilities?.sources || []; return [...new Set((source ? sources.filter(item => item.moduleKey === source) : sources).flatMap(item => item.groups))]; }, [capabilities, source]);
  const channels = useMemo(() => [...new Set(capabilities?.sources.flatMap(item => item.channels) || [])], [capabilities]);
  const filtered = people.filter(person => (!source || person.sourceModule === source) && (!group || person.group === group) && (!channel || person.channels?.includes(channel)) && (!search || `${person.name} ${person.email || ""} ${person.phone || ""} ${person.code || ""}`.toLowerCase().includes(search.toLowerCase())));
  const communicationEnabled = capabilities?.enabledModules.some(module => module.key === "communications");
  return <div className="page contacts-page">
    <div className="page-header"><div><span className="eyebrow">Standalone directory</span><h1>Contacts</h1><p>People and organizations from the modules enabled for this workspace.</p></div>{write && <Button onClick={() => setOpen(true)}><Plus size={17}/> New contact</Button>}</div>
    {message && <Notice tone="success">{message}</Notice>}{error && <Notice tone="danger">{error}</Notice>}
    {capabilities && <div className="contact-source-strip"><small>Enabled sources</small>{capabilities.sources.map(item => <span key={item.moduleKey}>{item.name}</span>)}</div>}
    <Card><div className="contact-filters"><label><Search size={17}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search people, organizations, email or phone…"/></label><select value={source} onChange={event => { setSource(event.target.value); setGroup(""); }}><option value="">All enabled modules</option>{capabilities?.sources.map(item => <option key={item.moduleKey} value={item.moduleKey}>{item.name}</option>)}</select><select value={group} onChange={event => setGroup(event.target.value)}><option value="">All people</option>{groups.map(item => <option key={item} value={item}>{label(item)}</option>)}</select>{channels.length > 0 && <select value={channel} onChange={event => setChannel(event.target.value)}><option value="">All communication states</option>{channels.map(item => <option key={item} value={item}>{label(item)} enabled</option>)}</select>}</div>
      {loading ? <Spinner label="Loading enabled contact sources"/> : filtered.length ? <div className="table-wrap"><table><thead><tr><th>Person / organization</th><th>Relationship</th><th>Source module</th><th>Contact details</th>{communicationEnabled && <th>Messaging</th>}<th/></tr></thead><tbody>{filtered.map(person => <tr key={person.id}><td><b>{person.name}</b><small>{person.code || person.entityId}</small></td><td>{label(person.group)}</td><td><Badge>{capabilities?.enabledModules.find(module => module.key === person.sourceModule)?.name || label(person.sourceModule)}</Badge></td><td>{person.email || "—"}<small>{person.phone || "No phone"}</small></td>{communicationEnabled && <td><div className="contact-channels">{person.channels?.map(item => <span key={item}><MessageSquareText size={12}/>{item.toUpperCase()}</span>)}{!person.channels?.length && <small>Not message-ready</small>}</div></td>}<td><button className="contact-view" onClick={() => setSelected(person)}><Eye size={15}/> View</button></td></tr>)}</tbody></table></div> : <EmptyState title="No people found" description="Adjust the filters or add the first shared contact."/>}
    </Card>
    {open && <CreateContact groups={capabilities?.sources.find(item => item.moduleKey === "ledgerly-core")?.groups || ["other"]} close={() => setOpen(false)} done={() => { setOpen(false); setMessage("Contact saved."); void load(); }}/>} 
    {selected && <PersonDetail person={selected} write={write} close={() => setSelected(null)} archived={() => { setSelected(null); setMessage("Contact archived."); void load(); }}/>} 
  </div>;
}

function CreateContact({ groups, close, done }: { groups: string[]; close: () => void; done: () => void }) {
  const contactGroups = groups.filter(group => ["customer", "supplier", "employee", "other"].includes(group)), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setBusy(true); setError(""); try { await post("/contacts", { type: values.type, name: values.name, code: values.code || undefined, email: values.email || undefined, paymentTermsDays: Number(values.paymentTermsDays || 0), creditLimitMinor: Math.round(Number(values.creditLimit || 0) * 100), customFields: {}, active: true }); done(); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); } }
  return <Modal title="Create contact" onClose={close} locked={busy}><form onSubmit={save}><div className="modal-body form-grid"><Field label="Relationship"><select name="type">{contactGroups.map(group => <option value={group} key={group}>{label(group)}</option>)}</select></Field><Field label="Name"><input name="name" required maxLength={160}/></Field><Field label="Code"><input name="code" maxLength={30}/></Field><Field label="Email"><input name="email" type="email"/></Field><Field label="Payment terms (days)"><input name="paymentTermsDays" type="number" min="0" max="365" defaultValue="0"/></Field><Field label="Credit limit"><input name="creditLimit" type="number" min="0" step=".01" defaultValue="0"/></Field>{error && <Notice tone="danger">{error}</Notice>}</div><div className="modal-actions"><Button type="button" variant="ghost" onClick={close}>Cancel</Button><Button disabled={busy}>{busy ? "Saving…" : "Save contact"}</Button></div></form></Modal>;
}

function PersonDetail({ person, write, close, archived }: { person: Person; write: boolean; close: () => void; archived: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function archive() { if (!person.contactId) return; setBusy(true); try { await post(`/contacts/${person.contactId}/archive`, {}); archived(); } catch (reason) { setError(errorText(reason)); setBusy(false); } }
  return <Modal title={person.name} onClose={close} locked={busy}><div className="modal-body"><div className="contact-detail-icon"><ContactRound/><div><b>{label(person.group)}</b><small>{label(person.sourceModule)}</small></div></div><div className="summary-grid"><span><small>Email</small><b>{person.email || "—"}</b></span><span><small>Phone</small><b>{person.phone || "—"}</b></span><span><small>Code</small><b>{person.code || "—"}</b></span><span><small>Status</small><b>{person.active ? "Active" : "Inactive"}</b></span></div>{person.channels?.length ? <p>Available messaging channels: {person.channels.map(channel => channel.toUpperCase()).join(", ")}.</p> : null}{error && <Notice tone="danger">{error}</Notice>}</div>{write && person.contactId && <div className="modal-actions"><Button variant="secondary" disabled={busy} onClick={() => void archive()}><Archive size={15}/> Archive contact</Button></div>}</Modal>;
}
