import { Hono } from 'hono';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { AppError } from '../../http/errors.js';
import { createId, requireScope } from '../core-identity/security.js';
import { requireNvrCameraAccess } from './access.js';

export function createNvrAccessRoutes(runtime:Runtime){
 const r=new Hono<AppEnv>();r.use('*',requireScope('school:read'));
 r.get('/cameras',async c=>{const p=c.get('principal'),priv=p.role==='owner'||p.role==='admin';const q=await runtime.db.query(`SELECT c.id,c.name,c.location,c.source_type AS "sourceType",c.status,c.enabled,c.capabilities,c.settings,c.last_seen_at AS "lastSeenAt",c.last_error AS "lastError",c.created_at AS "createdAt" FROM nvr_cameras c WHERE c.organization_id=$1 AND ($3::boolean OR NOT EXISTS(SELECT 1 FROM nvr_camera_group_members gm WHERE gm.organization_id=c.organization_id AND gm.camera_id=c.id) OR EXISTS(SELECT 1 FROM nvr_camera_group_members gm JOIN nvr_camera_group_shares gs ON gs.organization_id=gm.organization_id AND gs.group_id=gm.group_id WHERE gm.organization_id=c.organization_id AND gm.camera_id=c.id AND gs.user_id=$2)) ORDER BY c.name`,[p.organizationId,p.userId,priv]);return c.json({data:q.rows});});
 r.get('/recordings',async c=>{const p=c.get('principal'),cameraId=c.req.query('cameraId')??'',priv=p.role==='owner'||p.role==='admin';if(cameraId)await requireNvrCameraAccess(runtime,p,cameraId);const q=await runtime.db.query(`SELECT r.id,r.camera_id AS "cameraId",c.name AS "cameraName",r.mime_type AS "mimeType",r.size_bytes AS "sizeBytes",r.started_at AS "startedAt",r.ended_at AS "endedAt",r.duration_seconds AS "durationSeconds",r.status,r.retention_until AS "retentionUntil" FROM nvr_recordings r JOIN nvr_cameras c ON c.id=r.camera_id AND c.organization_id=r.organization_id WHERE r.organization_id=$1 AND ($2='' OR r.camera_id=$2) AND r.status<>'deleted' AND ($4::boolean OR NOT EXISTS(SELECT 1 FROM nvr_camera_group_members gm WHERE gm.organization_id=c.organization_id AND gm.camera_id=c.id) OR EXISTS(SELECT 1 FROM nvr_camera_group_members gm JOIN nvr_camera_group_shares gs ON gs.organization_id=gm.organization_id AND gs.group_id=gm.group_id WHERE gm.organization_id=c.organization_id AND gm.camera_id=c.id AND gs.user_id=$3)) ORDER BY r.started_at DESC LIMIT 500`,[p.organizationId,cameraId,p.userId,priv]);return c.json({data:q.rows});});
 r.get('/events',async c=>{const p=c.get('principal'),priv=p.role==='owner'||p.role==='admin';const q=await runtime.db.query(`SELECT e.id,e.camera_id AS "cameraId",c.name AS "cameraName",e.event_type AS "eventType",e.severity,e.title,e.details,e.occurred_at AS "occurredAt",e.acknowledged_by AS "acknowledgedBy",e.acknowledged_at AS "acknowledgedAt" FROM nvr_events e LEFT JOIN nvr_cameras c ON c.id=e.camera_id AND c.organization_id=e.organization_id WHERE e.organization_id=$1 AND (e.camera_id IS NULL OR $3::boolean OR NOT EXISTS(SELECT 1 FROM nvr_camera_group_members gm WHERE gm.organization_id=e.organization_id AND gm.camera_id=e.camera_id) OR EXISTS(SELECT 1 FROM nvr_camera_group_members gm JOIN nvr_camera_group_shares gs ON gs.organization_id=gm.organization_id AND gs.group_id=gm.group_id WHERE gm.organization_id=e.organization_id AND gm.camera_id=e.camera_id AND gs.user_id=$2)) ORDER BY e.occurred_at DESC LIMIT 500`,[p.organizationId,p.userId,priv]);return c.json({data:q.rows});});
 r.post('/cameras/:id/live-sessions',async c=>{const p=c.get('principal'),cameraId=c.req.param('id');await requireNvrCameraAccess(runtime,p,cameraId);const cam=await runtime.db.query(`SELECT status FROM nvr_cameras WHERE id=$1 AND organization_id=$2 AND enabled=true`,[cameraId,p.organizationId]);if(!cam.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');if(!['online','recording'].includes(String((cam.rows[0] as any).status)))throw new AppError(409,'CAMERA_OFFLINE','Camera is offline');const id=createId('nvrLive'),expires=new Date(Date.now()+5*60*1000).toISOString();await runtime.db.query(`INSERT INTO nvr_stream_sessions(id,organization_id,camera_id,requested_by,transport,expires_at) VALUES($1,$2,$3,$4,'webrtc',$5)`,[id,p.organizationId,cameraId,p.userId,expires]);return c.json({data:{id,cameraId,transport:'webrtc',status:'requested',expiresAt:expires}},201);});
 return r;
}
