import { Hono } from 'hono';
import { z } from 'zod';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { AppError } from '../../http/errors.js';
import { createId, requireScope } from '../core-identity/security.js';

const groupSchema=z.object({name:z.string().min(1).max(120),description:z.string().max(500).nullable().optional(),zone:z.string().max(120).nullable().optional()});
const memberSchema=z.object({cameraId:z.string().min(1)});
const shareSchema=z.object({userId:z.string().min(1),role:z.enum(['viewer','manager'])});

export function createNvrGroupRoutes(runtime:Runtime){
  const r=new Hono<AppEnv>();
  r.use('*',requireScope('school:read'));
  r.get('/camera-groups',async c=>{const p=c.get('principal');const q=await runtime.db.query(`SELECT g.*,COUNT(DISTINCT m.camera_id)::int AS "cameraCount",COUNT(DISTINCT s.user_id)::int AS "sharedUsers" FROM nvr_camera_groups g LEFT JOIN nvr_camera_group_members m ON m.organization_id=g.organization_id AND m.group_id=g.id LEFT JOIN nvr_camera_group_shares s ON s.organization_id=g.organization_id AND s.group_id=g.id WHERE g.organization_id=$1 GROUP BY g.id ORDER BY g.name`,[p.organizationId]);return c.json({data:q.rows});});
  r.post('/camera-groups',requireScope('school:write'),async c=>{const p=c.get('principal'),s=groupSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera group',s.error.flatten());const id=createId('nvrGroup');await runtime.db.query(`INSERT INTO nvr_camera_groups(id,organization_id,name,description,zone,created_by) VALUES($1,$2,$3,$4,$5,$6)`,[id,p.organizationId,s.data.name,s.data.description??null,s.data.zone??null,p.userId]);return c.json({data:{id,...s.data}},201);});
  r.patch('/camera-groups/:id',requireScope('school:write'),async c=>{const p=c.get('principal'),s=groupSchema.partial().safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera group',s.error.flatten());const q=await runtime.db.query(`UPDATE nvr_camera_groups SET name=COALESCE($1,name),description=COALESCE($2,description),zone=COALESCE($3,zone),updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND organization_id=$5 RETURNING *`,[s.data.name??null,s.data.description??null,s.data.zone??null,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'GROUP_NOT_FOUND','Camera group not found');return c.json({data:q.rows[0]});});
  r.post('/camera-groups/:id/cameras',requireScope('school:write'),async c=>{const p=c.get('principal'),s=memberSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera membership',s.error.flatten());const own=await runtime.db.query(`SELECT 1 FROM nvr_cameras WHERE id=$1 AND organization_id=$2`,[s.data.cameraId,p.organizationId]);if(!own.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');await runtime.db.query(`INSERT INTO nvr_camera_group_members(organization_id,group_id,camera_id) SELECT $1,$2,$3 WHERE EXISTS(SELECT 1 FROM nvr_camera_groups WHERE id=$2 AND organization_id=$1) ON CONFLICT DO NOTHING`,[p.organizationId,c.req.param('id'),s.data.cameraId]);return c.json({data:{ok:true}});});
  r.delete('/camera-groups/:id/cameras/:cameraId',requireScope('school:write'),async c=>{const p=c.get('principal');await runtime.db.query(`DELETE FROM nvr_camera_group_members WHERE organization_id=$1 AND group_id=$2 AND camera_id=$3`,[p.organizationId,c.req.param('id'),c.req.param('cameraId')]);return c.json({data:{ok:true}});});
  r.get('/camera-groups/:id/shares',requireScope('school:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT s.user_id AS "userId",u.email,u.display_name AS "displayName",s.role,s.created_at AS "createdAt" FROM nvr_camera_group_shares s JOIN users u ON u.id=s.user_id WHERE s.organization_id=$1 AND s.group_id=$2 ORDER BY u.display_name`,[p.organizationId,c.req.param('id')]);return c.json({data:q.rows});});
  r.put('/camera-groups/:id/shares',requireScope('school:write'),async c=>{const p=c.get('principal'),s=shareSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera group share',s.error.flatten());const member=await runtime.db.query(`SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$2`,[p.organizationId,s.data.userId]);if(!member.rowCount)throw new AppError(404,'USER_NOT_FOUND','Organization user not found');await runtime.db.query(`INSERT INTO nvr_camera_group_shares(organization_id,group_id,user_id,role,created_by) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM nvr_camera_groups WHERE id=$2 AND organization_id=$1) ON CONFLICT(organization_id,group_id,user_id) DO UPDATE SET role=EXCLUDED.role,created_by=EXCLUDED.created_by,created_at=CURRENT_TIMESTAMP`,[p.organizationId,c.req.param('id'),s.data.userId,s.data.role,p.userId]);return c.json({data:s.data});});
  r.delete('/camera-groups/:id/shares/:userId',requireScope('school:write'),async c=>{const p=c.get('principal');await runtime.db.query(`DELETE FROM nvr_camera_group_shares WHERE organization_id=$1 AND group_id=$2 AND user_id=$3`,[p.organizationId,c.req.param('id'),c.req.param('userId')]);return c.json({data:{ok:true}});});
  r.get('/cameras/accessible',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT DISTINCT c.* FROM nvr_cameras c LEFT JOIN nvr_camera_group_members gm ON gm.organization_id=c.organization_id AND gm.camera_id=c.id LEFT JOIN nvr_camera_group_shares gs ON gs.organization_id=c.organization_id AND gs.group_id=gm.group_id WHERE c.organization_id=$1 AND (gs.user_id=$2 OR NOT EXISTS(SELECT 1 FROM nvr_camera_group_members x WHERE x.organization_id=c.organization_id AND x.camera_id=c.id)) ORDER BY c.name`,[p.organizationId,p.userId]);return c.json({data:q.rows});});
  return r;
}
