import { Hono } from 'hono';
import { z } from 'zod';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { createId, requireScope } from '../core-identity/security.js';

const cameraSchema=z.object({name:z.string().min(1).max(160),location:z.string().max(200).nullable().optional(),sourceType:z.enum(['phone','rtsp','onvif','usb','other']).default('phone'),sourceUri:z.string().max(2000).nullable().optional(),capabilities:z.record(z.string(),z.unknown()).default({}),settings:z.record(z.string(),z.unknown()).default({})});
const heartbeatSchema=z.object({status:z.enum(['online','recording','error']).default('online'),capabilities:z.record(z.string(),z.unknown()).optional(),error:z.string().max(1000).nullable().optional()});
const eventSchema=z.object({eventType:z.string().min(1).max(80),severity:z.enum(['info','warning','critical']).default('info'),title:z.string().min(1).max(200),details:z.record(z.string(),z.unknown()).default({})});

export function createNvrRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('school:read'));
 r.get('/manifest',c=>c.json({data:{key:'nvr',name:'Security Camera / NVR',version:'1.0.0',capabilities:['camera-registry','phone-camera','rtsp-catalog','recording-catalog','events','live-session-registry']}}));
 r.get('/overview',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT COUNT(*)::int cameras,COUNT(*) FILTER(WHERE enabled AND status IN ('online','recording'))::int online,COUNT(*) FILTER(WHERE status='recording')::int recording FROM nvr_cameras WHERE organization_id=$1`,[p.organizationId]),e=await runtime.db.query(`SELECT COUNT(*)::int unacknowledged FROM nvr_events WHERE organization_id=$1 AND acknowledged_at IS NULL AND severity IN ('warning','critical')`,[p.organizationId]),rec=await runtime.db.query(`SELECT COUNT(*)::int recordings,COALESCE(SUM(size_bytes),0)::bigint bytes FROM nvr_recordings WHERE organization_id=$1 AND status='ready'`,[p.organizationId]);return c.json({data:{...(q.rows[0] as any),unacknowledged:Number((e.rows[0] as any)?.unacknowledged||0),recordings:Number((rec.rows[0] as any)?.recordings||0),bytes:Number((rec.rows[0] as any)?.bytes||0)}});});
 r.get('/cameras',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT id,name,location,source_type AS "sourceType",status,enabled,capabilities,settings,last_seen_at AS "lastSeenAt",last_error AS "lastError",created_at AS "createdAt" FROM nvr_cameras WHERE organization_id=$1 ORDER BY name`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/cameras',requireScope('school:write'),async c=>{const p=c.get('principal'),s=cameraSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera configuration',s.error.flatten());const id=createId('nvrCam'),v=s.data;await runtime.db.query(`INSERT INTO nvr_cameras(id,organization_id,name,location,source_type,source_uri,capabilities,settings,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9)`,[id,p.organizationId,v.name,v.location??null,v.sourceType,v.sourceUri??null,JSON.stringify(v.capabilities),JSON.stringify(v.settings),p.userId]);return c.json({data:{id,status:'offline'}},201);});
 r.patch('/cameras/:id',requireScope('school:write'),async c=>{const p=c.get('principal'),s=cameraSchema.partial().safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera update',s.error.flatten());const v=s.data,q=await runtime.db.query(`UPDATE nvr_cameras SET name=COALESCE($1,name),location=COALESCE($2,location),source_type=COALESCE($3,source_type),source_uri=COALESCE($4,source_uri),capabilities=COALESCE($5::jsonb,capabilities),settings=COALESCE($6::jsonb,settings),updated_at=CURRENT_TIMESTAMP WHERE id=$7 AND organization_id=$8 RETURNING id`,[v.name??null,v.location??null,v.sourceType??null,v.sourceUri??null,v.capabilities?JSON.stringify(v.capabilities):null,v.settings?JSON.stringify(v.settings):null,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');return c.json({data:{id:c.req.param('id'),updated:true}});});
 r.post('/cameras/:id/heartbeat',requireScope('school:write'),async c=>{const p=c.get('principal'),s=heartbeatSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera heartbeat',s.error.flatten());const q=await runtime.db.query(`UPDATE nvr_cameras SET status=$1,capabilities=COALESCE($2::jsonb,capabilities),last_error=$3,last_seen_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND organization_id=$5 AND enabled=true RETURNING id`,[s.data.status,s.data.capabilities?JSON.stringify(s.data.capabilities):null,s.data.error??null,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found or disabled');return c.json({data:{id:c.req.param('id'),status:s.data.status}});});
 r.post('/cameras/:id/disable',requireScope('school:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE nvr_cameras SET enabled=false,status='disabled',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 RETURNING id`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');return c.json({data:{id:c.req.param('id'),enabled:false}});});
 r.get('/recordings',async c=>{const p=c.get('principal'),cameraId=c.req.query('cameraId')??'',q=await runtime.db.query(`SELECT r.id,r.camera_id AS "cameraId",c.name AS "cameraName",r.mime_type AS "mimeType",r.size_bytes AS "sizeBytes",r.started_at AS "startedAt",r.ended_at AS "endedAt",r.duration_seconds AS "durationSeconds",r.status,r.retention_until AS "retentionUntil" FROM nvr_recordings r JOIN nvr_cameras c ON c.id=r.camera_id AND c.organization_id=r.organization_id WHERE r.organization_id=$1 AND ($2='' OR r.camera_id=$2) AND r.status<>'deleted' ORDER BY r.started_at DESC LIMIT 500`,[p.organizationId,cameraId]);return c.json({data:q.rows});});
 r.get('/events',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT e.id,e.camera_id AS "cameraId",c.name AS "cameraName",e.event_type AS "eventType",e.severity,e.title,e.details,e.occurred_at AS "occurredAt",e.acknowledged_by AS "acknowledgedBy",e.acknowledged_at AS "acknowledgedAt" FROM nvr_events e LEFT JOIN nvr_cameras c ON c.id=e.camera_id AND c.organization_id=e.organization_id WHERE e.organization_id=$1 ORDER BY e.occurred_at DESC LIMIT 500`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/cameras/:id/events',requireScope('school:write'),async c=>{const p=c.get('principal'),s=eventSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid camera event',s.error.flatten());const exists=await runtime.db.query(`SELECT 1 FROM nvr_cameras WHERE id=$1 AND organization_id=$2`,[c.req.param('id'),p.organizationId]);if(!exists.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');const id=createId('nvrEvt');await runtime.db.query(`INSERT INTO nvr_events(id,organization_id,camera_id,event_type,severity,title,details) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[id,p.organizationId,c.req.param('id'),s.data.eventType,s.data.severity,s.data.title,JSON.stringify(s.data.details)]);return c.json({data:{id}},201);});
 r.post('/events/:id/ack',requireScope('school:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE nvr_events SET acknowledged_by=$1,acknowledged_at=COALESCE(acknowledged_at,CURRENT_TIMESTAMP) WHERE id=$2 AND organization_id=$3 RETURNING id`,[p.userId,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'EVENT_NOT_FOUND','Camera event not found');return c.json({data:{id:c.req.param('id'),acknowledged:true}});});
 r.post('/cameras/:id/live-sessions',async c=>{const p=c.get('principal'),cam=await runtime.db.query(`SELECT status FROM nvr_cameras WHERE id=$1 AND organization_id=$2 AND enabled=true`,[c.req.param('id'),p.organizationId]);if(!cam.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');if(!['online','recording'].includes(String((cam.rows[0] as any).status)))throw new AppError(409,'CAMERA_OFFLINE','Camera is offline');const id=createId('nvrLive'),expires=new Date(Date.now()+5*60*1000).toISOString();await runtime.db.query(`INSERT INTO nvr_stream_sessions(id,organization_id,camera_id,requested_by,transport,expires_at) VALUES($1,$2,$3,$4,'webrtc',$5)`,[id,p.organizationId,c.req.param('id'),p.userId,expires]);return c.json({data:{id,cameraId:c.req.param('id'),transport:'webrtc',status:'requested',expiresAt:expires}},201);});
 return r;}
