import { Hono } from 'hono';
import { z } from 'zod';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { createId, requireScope } from '../core-identity/security.js';

const ruleSchema=z.object({name:z.string().min(1).max(160),active:z.boolean().default(true),cameraId:z.string().nullable().optional(),eventType:z.string().max(80).nullable().optional(),minSeverity:z.enum(['info','warning','critical']).default('warning'),recipientUserIds:z.array(z.string()).max(100).default([]),cooldownSeconds:z.number().int().min(0).max(86400).default(300)});

async function validateRecipients(runtime:Runtime,org:string,ids:string[]){if(!ids.length)return;const q=await runtime.db.query(`SELECT user_id FROM memberships WHERE organization_id=$1 AND user_id=ANY($2::text[])`,[org,ids]);if((q.rowCount??0)!==new Set(ids).size)throw new AppError(422,'INVALID_RECIPIENT','One or more notification recipients are not organization members');}

export function createNvrRuleRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('school:read'));
 r.get('/event-rules',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT id,name,active,camera_id AS "cameraId",event_type AS "eventType",min_severity AS "minSeverity",recipient_user_ids AS "recipientUserIds",cooldown_seconds AS "cooldownSeconds",created_at AS "createdAt",updated_at AS "updatedAt" FROM nvr_event_rules WHERE organization_id=$1 ORDER BY active DESC,name`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/event-rules',requireScope('school:write'),async c=>{const p=c.get('principal'),s=ruleSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid NVR event rule',s.error.flatten());const v=s.data;if(v.cameraId){const cam=await runtime.db.query(`SELECT 1 FROM nvr_cameras WHERE id=$1 AND organization_id=$2`,[v.cameraId,p.organizationId]);if(!cam.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');}await validateRecipients(runtime,p.organizationId,v.recipientUserIds);const id=createId('nvrRule');await runtime.db.query(`INSERT INTO nvr_event_rules(id,organization_id,name,active,camera_id,event_type,min_severity,recipient_user_ids,cooldown_seconds,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10)`,[id,p.organizationId,v.name,v.active,v.cameraId??null,v.eventType??null,v.minSeverity,JSON.stringify(v.recipientUserIds),v.cooldownSeconds,p.userId]);return c.json({data:{id}},201);});
 r.patch('/event-rules/:id',requireScope('school:write'),async c=>{const p=c.get('principal'),s=ruleSchema.partial().safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid NVR event rule update',s.error.flatten());const v=s.data;if(v.cameraId){const cam=await runtime.db.query(`SELECT 1 FROM nvr_cameras WHERE id=$1 AND organization_id=$2`,[v.cameraId,p.organizationId]);if(!cam.rowCount)throw new AppError(404,'CAMERA_NOT_FOUND','Camera not found');}if(v.recipientUserIds)await validateRecipients(runtime,p.organizationId,v.recipientUserIds);const q=await runtime.db.query(`UPDATE nvr_event_rules SET name=COALESCE($1,name),active=COALESCE($2,active),camera_id=CASE WHEN $3::boolean THEN $4 ELSE camera_id END,event_type=CASE WHEN $5::boolean THEN $6 ELSE event_type END,min_severity=COALESCE($7,min_severity),recipient_user_ids=COALESCE($8::jsonb,recipient_user_ids),cooldown_seconds=COALESCE($9,cooldown_seconds),updated_at=CURRENT_TIMESTAMP WHERE id=$10 AND organization_id=$11 RETURNING id`,[v.name??null,v.active??null,Object.prototype.hasOwnProperty.call(v,'cameraId'),v.cameraId??null,Object.prototype.hasOwnProperty.call(v,'eventType'),v.eventType??null,v.minSeverity??null,v.recipientUserIds?JSON.stringify(v.recipientUserIds):null,v.cooldownSeconds??null,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'RULE_NOT_FOUND','Event rule not found');return c.json({data:{id:c.req.param('id'),updated:true}});});
 r.delete('/event-rules/:id',requireScope('school:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`DELETE FROM nvr_event_rules WHERE id=$1 AND organization_id=$2 RETURNING id`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'RULE_NOT_FOUND','Event rule not found');return c.json({data:{id:c.req.param('id'),deleted:true}});});
 r.get('/notifications',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT n.id,n.event_id AS "eventId",n.rule_id AS "ruleId",n.title,n.body,n.severity,n.read_at AS "readAt",n.created_at AS "createdAt",e.camera_id AS "cameraId",e.event_type AS "eventType" FROM nvr_alert_notifications n JOIN nvr_events e ON e.id=n.event_id AND e.organization_id=n.organization_id WHERE n.organization_id=$1 AND n.user_id=$2 ORDER BY n.created_at DESC LIMIT 300`,[p.organizationId,p.userId]);return c.json({data:q.rows});});
 r.post('/notifications/:id/read',async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE nvr_alert_notifications SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE id=$1 AND organization_id=$2 AND user_id=$3 RETURNING id,read_at AS "readAt"`,[c.req.param('id'),p.organizationId,p.userId]);if(!q.rowCount)throw new AppError(404,'NOTIFICATION_NOT_FOUND','Notification not found');return c.json({data:q.rows[0]});});
 r.post('/notifications/read-all',async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE nvr_alert_notifications SET read_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND user_id=$2 AND read_at IS NULL`,[p.organizationId,p.userId]);return c.json({data:{updated:q.rowCount??0}});});
 return r;}
