import { createId } from '../core-identity/security.js';
import type { ClaimedJob } from '../../queue/postgres-queue.js';
import type { Runtime } from '../../runtime.js';
import { readNvrStorageUsage } from './storage-pressure.js';

export async function sweepNvrStoragePressure(_job:ClaimedJob,runtime:Runtime){
 const orgs=await runtime.db.query(`SELECT id FROM organizations WHERE status='active' ORDER BY id LIMIT 1000`);
 for(const row of orgs.rows as any[]){const org=row.id,pq=await runtime.db.query(`SELECT * FROM nvr_storage_policies WHERE organization_id=$1`,[org]),p:any=pq.rows[0]??{max_bytes:107374182400,high_watermark_percent:85,critical_watermark_percent:95,min_local_free_bytes:5368709120,cleanup_target_percent:75,automatic_cleanup:true};let u=await readNvrStorageUsage(runtime,org),pct=(u.usedBytes/Number(p.max_bytes))*100,level=(pct>=Number(p.critical_watermark_percent)||(u.localFreeBytes!==null&&u.localFreeBytes<Number(p.min_local_free_bytes)))?'critical':pct>=Number(p.high_watermark_percent)?'high':'normal',deleted=0,reclaimed=0;
  if(level!=='normal'&&p.automatic_cleanup){const target=Number(p.max_bytes)*Number(p.cleanup_target_percent)/100,candidates=await runtime.db.query(`SELECT r.id,r.upload_state,r.object_key,r.size_bytes FROM nvr_recordings r WHERE r.organization_id=$1 AND r.status='ready' AND r.purged_at IS NULL AND NOT EXISTS(SELECT 1 FROM nvr_recording_holds h WHERE h.organization_id=r.organization_id AND h.recording_id=r.id AND h.released_at IS NULL) ORDER BY r.started_at ASC LIMIT 1000`,[org]);for(const rec of candidates.rows as any[]){if(u.usedBytes-reclaimed<=target&&!(u.localFreeBytes!==null&&u.localFreeBytes<Number(p.min_local_free_bytes)))break;if(rec.upload_state==='chunked'){const ch=await runtime.db.query(`SELECT object_key FROM nvr_recording_chunks WHERE organization_id=$1 AND recording_id=$2 ORDER BY chunk_index`,[org,rec.id]);for(const x of ch.rows as any[])await runtime.storage.delete(x.object_key).catch(()=>{});}else if(rec.object_key)await runtime.storage.delete(rec.object_key).catch(()=>{});await runtime.db.query(`UPDATE nvr_recordings SET status='deleted',purged_at=CURRENT_TIMESTAMP,purge_reason='storage-pressure' WHERE id=$1 AND organization_id=$2 AND purged_at IS NULL`,[rec.id,org]);deleted++;reclaimed+=Number(rec.size_bytes||0);}}
  if(level!=='normal'||deleted)await runtime.db.query(`INSERT INTO nvr_storage_pressure_events(id,organization_id,pressure_level,used_bytes,quota_bytes,local_free_bytes,deleted_recordings,reclaimed_bytes,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)`,[createId('nvrPressure'),org,level,u.usedBytes,p.max_bytes,u.localFreeBytes,deleted,reclaimed,JSON.stringify({driver:runtime.storage.driver})]);
 }
}
