import { statfs } from 'node:fs/promises';
import { Hono } from 'hono';
import { z } from 'zod';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { AppError } from '../../http/errors.js';
import { requireScope } from '../core-identity/security.js';

const policy=z.object({maxBytes:z.number().int().positive(),highWatermarkPercent:z.number().int().min(50).max(99),criticalWatermarkPercent:z.number().int().min(60).max(100),minLocalFreeBytes:z.number().int().min(0),cleanupTargetPercent:z.number().int().min(10).max(95),automaticCleanup:z.boolean()});
async function usage(runtime:Runtime,org:string){const q=await runtime.db.query(`SELECT COALESCE(SUM(size_bytes),0)::bigint AS used FROM nvr_recordings WHERE organization_id=$1 AND status='ready' AND purged_at IS NULL`,[org]);let free:null|number=null;if(runtime.storage.driver==='local'){try{const s=await statfs(runtime.config.STORAGE_LOCAL_ROOT);free=Number(s.bavail)*Number(s.bsize)}catch{}}return {usedBytes:Number((q.rows[0] as any).used||0),localFreeBytes:free};}
export function createNvrStorageRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('school:read'));
r.get('/storage',async c=>{const org=c.get('principal').organizationId,p=await runtime.db.query(`SELECT max_bytes AS "maxBytes",high_watermark_percent AS "highWatermarkPercent",critical_watermark_percent AS "criticalWatermarkPercent",min_local_free_bytes AS "minLocalFreeBytes",cleanup_target_percent AS "cleanupTargetPercent",automatic_cleanup AS "automaticCleanup",updated_at AS "updatedAt" FROM nvr_storage_policies WHERE organization_id=$1`,[org]),u=await usage(runtime,org);const x:any=p.rows[0]??{maxBytes:107374182400,highWatermarkPercent:85,criticalWatermarkPercent:95,minLocalFreeBytes:5368709120,cleanupTargetPercent:75,automaticCleanup:true};const pct=Math.round((u.usedBytes/Number(x.maxBytes))*10000)/100,level=(pct>=x.criticalWatermarkPercent||(u.localFreeBytes!==null&&u.localFreeBytes<Number(x.minLocalFreeBytes)))?'critical':pct>=x.highWatermarkPercent?'high':'normal';return c.json({data:{...x,...u,usedPercent:pct,pressureLevel:level,driver:runtime.storage.driver}})});
r.put('/storage/policy',requireScope('school:write'),async c=>{const p=c.get('principal'),s=policy.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid storage policy',s.error.flatten());const v=s.data;await runtime.db.query(`INSERT INTO nvr_storage_policies(organization_id,max_bytes,high_watermark_percent,critical_watermark_percent,min_local_free_bytes,cleanup_target_percent,automatic_cleanup,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id) DO UPDATE SET max_bytes=EXCLUDED.max_bytes,high_watermark_percent=EXCLUDED.high_watermark_percent,critical_watermark_percent=EXCLUDED.critical_watermark_percent,min_local_free_bytes=EXCLUDED.min_local_free_bytes,cleanup_target_percent=EXCLUDED.cleanup_target_percent,automatic_cleanup=EXCLUDED.automatic_cleanup,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP`,[p.organizationId,v.maxBytes,v.highWatermarkPercent,v.criticalWatermarkPercent,v.minLocalFreeBytes,v.cleanupTargetPercent,v.automaticCleanup,p.userId]);return c.json({data:v})});
r.get('/storage/events',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT * FROM nvr_storage_pressure_events WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 100`,[p.organizationId]);return c.json({data:q.rows})});return r;}
export { usage as readNvrStorageUsage };
