import { z } from "zod";
import { AppError } from "../../http/errors.js";
import type { ClaimedJob } from "../../queue/postgres-queue.js";
import type { Runtime } from "../../runtime.js";

const leaveIntent=z.object({employeeId:z.string().min(3),leaveTypeId:z.string().min(3),startsOn:z.iso.date(),endsOn:z.iso.date(),days:z.number().positive().max(366),reason:z.string().max(1000).nullable().optional()}).refine(v=>v.startsOn<=v.endsOn,{message:"Leave end date must not be before its start date"});
const onboardingIntent=z.object({taskId:z.string().min(3),completedAt:z.iso.datetime().optional()});

type QueueContext={id:string;organizationId:string;userId:string;deviceId:string;clientTimestamp:string;role:string;payload:unknown};
async function version(runtime:Runtime,organizationId:string,collectionKey:string,id:string,at:string){await runtime.db.query(`INSERT INTO mobile_sync_record_versions(organization_id,module_key,collection_key,record_id,version,deleted,server_updated_at) VALUES($1,'human-resources',$2,$3,1,false,$4::timestamptz) ON CONFLICT(organization_id,module_key,collection_key,record_id) DO NOTHING`,[organizationId,collectionKey,id,at]);}

export async function queueHrLeaveIntent(runtime:Runtime,input:QueueContext){const parsed=leaveIntent.safeParse(input.payload);if(!parsed.success)throw new AppError(422,"INVALID_HR_LEAVE_INTENT","Invalid offline leave request",parsed.error.flatten());const v=parsed.data,employee=(await runtime.db.query(`SELECT id FROM hr_employees WHERE id=$1 AND organization_id=$2 AND employment_status IN ('active','on_leave')`,[v.employeeId,input.organizationId])).rows[0];if(!employee)throw new AppError(422,"INVALID_EMPLOYEE","Active HR employee required");const type=(await runtime.db.query(`SELECT id FROM hr_leave_types WHERE id=$1 AND organization_id=$2 AND active=true`,[v.leaveTypeId,input.organizationId])).rows[0];if(!type)throw new AppError(422,"INVALID_LEAVE_TYPE","Active leave type required");const q=await runtime.db.query(`INSERT INTO hr_mobile_leave_intents(id,organization_id,device_id,employee_id,leave_type_id,starts_on,ends_on,days,reason,requested_by,client_created_at) VALUES($1,$2,$3,$4,$5,$6::date,$7::date,$8,$9,$10,$11::timestamptz) ON CONFLICT(id) DO NOTHING RETURNING id`,[input.id,input.organizationId,input.deviceId,v.employeeId,v.leaveTypeId,v.startsOn,v.endsOn,v.days,v.reason??null,input.userId,input.clientTimestamp]);if(!q.rowCount){const existing=(await runtime.db.query<any>(`SELECT id,status,server_leave_request_id AS "serverLeaveRequestId" FROM hr_mobile_leave_intents WHERE id=$1 AND organization_id=$2`,[input.id,input.organizationId])).rows[0];if(!existing)throw new AppError(409,"INTENT_ID_CONFLICT","Intent ID already belongs to another organization");return{...existing,replayed:true};}await version(runtime,input.organizationId,"leave-request-intents",input.id,input.clientTimestamp);return{id:input.id,status:"pending_sync",...v};}

export async function queueHrOnboardingCompletionIntent(runtime:Runtime,input:QueueContext){const parsed=onboardingIntent.safeParse(input.payload);if(!parsed.success)throw new AppError(422,"INVALID_HR_ONBOARDING_INTENT","Invalid onboarding completion",parsed.error.flatten());const v=parsed.data,task=(await runtime.db.query<any>(`SELECT id,status,assigned_user_id AS "assignedUserId" FROM hr_onboarding_tasks WHERE id=$1 AND organization_id=$2`,[v.taskId,input.organizationId])).rows[0];if(!task)throw new AppError(404,"ONBOARDING_TASK_NOT_FOUND","Onboarding task not found");if(task.status==="completed")throw new AppError(409,"ALREADY_COMPLETED","Onboarding task is already completed");if(task.assignedUserId&&task.assignedUserId!==input.userId&&!['owner','admin'].includes(input.role))throw new AppError(403,"FORBIDDEN","This onboarding task is assigned to another user");const completedAt=v.completedAt??input.clientTimestamp,q=await runtime.db.query(`INSERT INTO hr_mobile_onboarding_intents(id,organization_id,device_id,task_id,completed_by,client_completed_at) VALUES($1,$2,$3,$4,$5,$6::timestamptz) ON CONFLICT(id) DO NOTHING RETURNING id`,[input.id,input.organizationId,input.deviceId,v.taskId,input.userId,completedAt]);if(!q.rowCount){const existing=(await runtime.db.query<any>(`SELECT id,status,applied_at AS "appliedAt" FROM hr_mobile_onboarding_intents WHERE id=$1 AND organization_id=$2`,[input.id,input.organizationId])).rows[0];if(!existing)throw new AppError(409,"INTENT_ID_CONFLICT","Intent ID already belongs to another organization");return{...existing,replayed:true};}await version(runtime,input.organizationId,"onboarding-completion-intents",input.id,input.clientTimestamp);return{id:input.id,taskId:v.taskId,status:"pending_sync",completedAt};}

function retryMinutes(attempt:number){return Math.min(1440,Math.max(1,2**Math.min(Math.max(attempt-1,0),10)));}
async function fail(runtime:Runtime,table:string,id:string,org:string,attempt:number,error:unknown){const terminal=error instanceof AppError&&error.status<500,final=terminal||attempt>=10,msg=(error instanceof Error?error.message:String(error)).slice(0,1000),code=error instanceof AppError?error.code:"PROCESSING_ERROR";if(final)await runtime.db.query(`UPDATE ${table} SET status='rejected',error_code=$1,error_message=$2,next_attempt_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND organization_id=$4`,[code,msg,id,org]);else await runtime.db.query(`UPDATE ${table} SET status='retry',error_code=$1,error_message=$2,next_attempt_at=CURRENT_TIMESTAMP+($3*INTERVAL '1 minute'),updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND organization_id=$5`,[code,msg,retryMinutes(attempt),id,org]);}

async function processLeave(runtime:Runtime,row:any){const claim=await runtime.db.query(`UPDATE hr_mobile_leave_intents SET status='processing',attempts=attempts+1,last_attempt_at=CURRENT_TIMESTAMP,next_attempt_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status IN ('pending','retry') RETURNING attempts`,[row.id,row.organizationId]);if(!claim.rowCount)return;const attempt=Number(claim.rows[0].attempts);try{let serverId=row.serverLeaveRequestId as string|undefined;if(!serverId)serverId=(await runtime.db.query<{id:string}>(`SELECT id FROM hr_leave_requests WHERE id=$1 AND organization_id=$2`,[row.id,row.organizationId])).rows[0]?.id;if(!serverId){const inserted=await runtime.db.query<{id:string}>(`INSERT INTO hr_leave_requests(id,organization_id,employee_id,leave_type_id,starts_on,ends_on,days,reason,status,requested_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'pending',$9,$10,$10) RETURNING id`,[row.id,row.organizationId,row.employeeId,row.leaveTypeId,row.startsOn,row.endsOn,row.days,row.reason??null,row.requestedBy,row.clientCreatedAt]);serverId=inserted.rows[0]?.id;}await runtime.db.query(`UPDATE hr_mobile_leave_intents SET status='applied',server_leave_request_id=$1,applied_at=COALESCE(applied_at,CURRENT_TIMESTAMP),error_code=NULL,error_message=NULL,next_attempt_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[serverId,row.id,row.organizationId]);}catch(e){await fail(runtime,"hr_mobile_leave_intents",row.id,row.organizationId,attempt,e);}}
async function processOnboarding(runtime:Runtime,row:any){const claim=await runtime.db.query(`UPDATE hr_mobile_onboarding_intents SET status='processing',attempts=attempts+1,last_attempt_at=CURRENT_TIMESTAMP,next_attempt_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status IN ('pending','retry') RETURNING attempts`,[row.id,row.organizationId]);if(!claim.rowCount)return;const attempt=Number(claim.rows[0].attempts);try{const task=(await runtime.db.query<any>(`SELECT id,status FROM hr_onboarding_tasks WHERE id=$1 AND organization_id=$2`,[row.taskId,row.organizationId])).rows[0];if(!task)throw new AppError(404,"ONBOARDING_TASK_NOT_FOUND","Onboarding task not found");if(task.status!=="completed")await runtime.db.query(`UPDATE hr_onboarding_tasks SET status='completed',completed_at=COALESCE(completed_at,$1::timestamptz),updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[row.clientCompletedAt,row.taskId,row.organizationId]);await runtime.db.query(`UPDATE hr_mobile_onboarding_intents SET status='applied',applied_at=COALESCE(applied_at,CURRENT_TIMESTAMP),error_code=NULL,error_message=NULL,next_attempt_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2`,[row.id,row.organizationId]);}catch(e){await fail(runtime,"hr_mobile_onboarding_intents",row.id,row.organizationId,attempt,e);}}

export async function processPendingHrMobileIntents(runtime:Runtime,options:{limit?:number;organizationId?:string}={}){const limit=Math.min(Math.max(options.limit??25,1),100),org=options.organizationId??null;for(const table of ["hr_mobile_leave_intents","hr_mobile_onboarding_intents"])await runtime.db.query(`UPDATE ${table} SET status='retry',next_attempt_at=CURRENT_TIMESTAMP,error_code=COALESCE(error_code,'PROCESS_INTERRUPTED'),error_message=COALESCE(error_message,'Recovered interrupted conversion'),updated_at=CURRENT_TIMESTAMP WHERE status='processing' AND updated_at<CURRENT_TIMESTAMP-INTERVAL '10 minutes' AND ($1::text IS NULL OR organization_id=$1)`,[org]);const leaves=(await runtime.db.query<any>(`SELECT id,organization_id AS "organizationId",employee_id AS "employeeId",leave_type_id AS "leaveTypeId",starts_on AS "startsOn",ends_on AS "endsOn",days::float8,reason,requested_by AS "requestedBy",client_created_at AS "clientCreatedAt",server_leave_request_id AS "serverLeaveRequestId" FROM hr_mobile_leave_intents WHERE status IN ('pending','retry') AND (next_attempt_at IS NULL OR next_attempt_at<=CURRENT_TIMESTAMP) AND ($1::text IS NULL OR organization_id=$1) ORDER BY created_at LIMIT $2`,[org,limit])).rows;for(const row of leaves)await processLeave(runtime,row);const remaining=Math.max(0,limit-leaves.length),tasks=remaining?(await runtime.db.query<any>(`SELECT id,organization_id AS "organizationId",task_id AS "taskId",client_completed_at AS "clientCompletedAt" FROM hr_mobile_onboarding_intents WHERE status IN ('pending','retry') AND (next_attempt_at IS NULL OR next_attempt_at<=CURRENT_TIMESTAMP) AND ($1::text IS NULL OR organization_id=$1) ORDER BY created_at LIMIT $2`,[org,remaining])).rows:[];for(const row of tasks)await processOnboarding(runtime,row);return{leaveRequests:leaves.length,onboardingCompletions:tasks.length};}
export async function handleHrMobileIntents(_job:ClaimedJob,runtime:Runtime){await processPendingHrMobileIntents(runtime,{limit:50});}
