export type ResponsePurpose="analysis"|"account-for"|"report"|"comparison"|"summary"|"recommendation"|"action-preview"|"warning"|"general";
export type ResponseRegister="executive"|"school-professional"|"finance"|"teacher"|"plain"|"technical";
export type EvidenceStrength="direct"|"strong"|"moderate"|"limited"|"conflicting";
export type ResponseMove="orient"|"fact"|"comparison"|"trend"|"interpretation"|"counterevidence"|"limitation"|"recommendation"|"conclusion"|"next-step";

export const RESPONSE_LIBRARY={
 openings:[
  "The clearest pattern in the records is","The records point first to","What stands out most is","The strongest signal is","The available evidence shows","Looking across the relevant records","The first thing the data makes clear is","The main pattern is not a single event but","The evidence is strongest around","A useful starting point is","Across the records reviewed","The most material finding is","The data does not point equally in every direction; it points most strongly to","Several signals matter here, but the clearest is","The picture becomes clearer when the records are considered together","The strongest evidence comes from","The result is better understood by separating the main signals","The records reveal a pattern that is more specific than the headline result","The evidence suggests a concentrated issue rather than a general one","The data is most informative when compared with the relevant baseline","The immediate takeaway is","The underlying pattern is","The records show a meaningful shift in","The evidence supports a focused explanation around"
 ],
 factLeads:[
  "The records show that","The recorded figures indicate that","On the available records","The underlying entries show","The verified data places","The source records record","The observed value is","The period data shows","The learner-level records show","The staff-level records show","The account activity shows","The class-level evidence shows","The comparison period records show","The transaction history shows","The attendance history shows","The assessment history shows","The operational records show","The system evidence confirms","The strongest direct fact is","A direct reading of the records shows","The verified result is","The relevant records place","The recorded pattern is","The measured outcome is"
 ],
 comparisonLeads:[
  "Compared with","Against the previous period","Against the relevant peer group","Relative to the baseline","When placed beside the earlier result","The difference becomes clearer when compared with","The contrast is visible against","On a like-for-like comparison","When the two periods are aligned","Relative to the class position","Relative to the cohort","Against the expected pattern in the available data","The gap is most visible when set against","The comparison is not marginal:","The more informative comparison is","A stronger contrast appears between","The same measure in the comparison group shows","The change is clearer in percentage terms","The relative movement is","The baseline helps put the result in context:","The current value differs from the earlier value by","The peer comparison shows","Across comparable records","The difference is concentrated in"
 ],
 trendLeads:[
  "Over time,","Across the period,","The direction of travel is","The sequence of records shows","The pattern is persistent rather than isolated:","The recent movement is","The change appears gradual rather than sudden:","The shift is concentrated in the latest period:","The historical pattern suggests","The series shows a reversal from","The trend strengthens after","The decline is not uniform across all measures:","The improvement is concentrated in","The movement becomes visible from","The period-to-period pattern is","The trajectory is best described as","The latest result continues","The latest result breaks with","The longer view shows","The short-term pattern differs from the longer trend:","The rate of change is","The sequence is more informative than the latest value alone:","Across comparable periods","The trend remains visible after separating"
 ],
 interpretationLeads:[
  "Taken together, this is consistent with","In context, these signals are consistent with","This pattern is better interpreted as","The evidence supports the interpretation that","The records make it reasonable to conclude that","A cautious interpretation is that","The combination of signals points toward","The most defensible interpretation is","This is more consistent with","The evidence weighs more heavily toward","The result appears to be driven more by","The pattern is unlikely to be explained by the headline figure alone;","The records support a narrower explanation:","A useful interpretation is","The strongest account of the result is","This does not require assuming motives; the observable pattern is","The evidence separates two issues:","The data supports distinguishing","The available evidence makes one explanation more plausible than others:","The combined picture suggests","The relationship is meaningful because","The pattern matters operationally because","The result is best understood in relation to","The evidence points to a practical issue around"
 ],
 causalGuards:[
  "This is an association in the available records, not proof of causation.","The records show that these events moved together; they do not establish that one alone caused the other.","The evidence supports a contribution, not a single-cause explanation.","This should not be read as proof that the observed factor caused the outcome.","The data supports a relationship, while the causal mechanism remains unverified.","The evidence is compatible with this explanation, but other unrecorded factors may also matter.","The records are strong enough to identify a contributor, not to claim exclusive causation.","The timing strengthens the explanation but does not, by itself, prove cause.","The observed relationship is relevant, but causality requires evidence beyond correlation.","The available records narrow the explanation without eliminating every alternative.","The system can describe what changed and what moved with it; it cannot infer private motives from those records.","The evidence supports a working explanation, not a definitive causal verdict.","This finding should be treated as evidence-backed context rather than a diagnosis of motive or intent.","The pattern is consistent with a contribution from this factor, although the records do not isolate it experimentally.","The result may have multiple contributors; the data only supports those visible in the records.","The comparison strengthens the observed relationship, while still leaving room for other causes.","The records support a measured explanation rather than an absolute one.","The causal claim should remain limited to what the recorded sequence can support.","This evidence helps explain the outcome, but it does not prove that removing this factor would have changed the outcome.","The records identify a plausible contributor; they do not establish inevitability."
 ],
 uncertainty:[
  "The evidence is incomplete on","The records do not currently show","There is not enough verified data to determine","The available data leaves uncertainty around","One important gap is","The system cannot verify","The comparison is limited by","The conclusion should be qualified because","The record set is thin on","The current evidence does not distinguish between","A remaining uncertainty is","The data is sufficient to describe the pattern but not to establish","The evidence would be stronger with","The missing piece is","The analysis is constrained by","No reliable conclusion can be drawn about","The records are silent on","The result should be interpreted cautiously because","There is a data-quality limitation around","The strongest unanswered question is","The available evidence stops short of","The analysis cannot safely infer","A more confident conclusion would require","The uncertainty is material because"
 ],
 counterEvidence:[
  "There is also counter-evidence:","Not every signal points in the same direction.","One part of the record weakens a simple explanation:","A competing observation is","The evidence is mixed in one important respect:","The pattern has an exception:","The broader record prevents an overly simple conclusion:","A factor arguing against the obvious explanation is","The data contains a meaningful contradiction:","One comparison does not support the same story:","The explanation should account for the fact that","A balancing observation is","The records also show","The strongest alternative reading is","One piece of evidence points away from","The case is not one-sided:","An important exception is","The pattern weakens when","The relationship does not hold consistently for","The evidence is strongest only in"
 ],
 recommendations:[
  "A practical next step would be to","The evidence supports following up by","The most targeted response would be to","The records suggest prioritising","A proportionate next action is to","Before making a larger intervention,","The strongest operational follow-up is to","A useful management response would be to","The next decision should focus on","A sensible follow-up is to","The evidence supports a focused review of","The school could test this explanation by","The fastest way to reduce uncertainty is to","The recommended follow-up is not a broad intervention but to","The next action should be tied to the observed gap:","A targeted response would be to","The data points to a practical follow-up around","The least disruptive useful action is to","A reasonable next step is to","The records justify reviewing","If action is required, priority should go to","The evidence supports monitoring","A useful control would be to","The system should next verify"
 ],
 conclusionLeads:[
  "Overall,","In summary,","The evidence therefore points to","The most defensible conclusion is","The records support a clear but qualified conclusion:","The combined evidence suggests","On balance,","The conclusion is narrower than a generic explanation:","The strongest conclusion the records support is","The practical conclusion is","The evidence converges on","Taken as a whole,","The result is best summarised as","The central finding is","The evidence supports saying","The analysis therefore identifies","The records leave a clear management issue:","The outcome is most closely associated with","The data supports a focused conclusion around","The final picture is","The most important conclusion is","The records are sufficient to conclude","The analysis closes with one clear point:","The evidence does not support a generic explanation; it supports"
 ],
 transitions:{
  add:["In addition","Also","A second signal is","Alongside this","The records further show","Another relevant point is","There is a second layer to the result","The same pattern appears in","Beyond the first finding","A related signal is","The analysis also found","Another part of the evidence matters"],
  contrast:["However","By contrast","That said","At the same time","The picture changes when","This is partly offset by","A different pattern appears in","The comparison is weaker in","Even so","On the other hand","The evidence is less consistent for","This should be balanced against"],
  consequence:["As a result","This matters because","Operationally, this means","The practical effect is","That difference translates into","The implication is","For the school, this means","This creates a follow-on issue:","The immediate consequence is","In practice","The effect is visible in","That pattern increases the importance of"],
  sequence:["First","Next","After that","In the following period","Earlier in the sequence","Later in the period","At the start of the period","By the end of the period","Before the change","After the change","During the same period","In the subsequent records"]
 },
 sectionTitles:{
  overview:["What the records show","The central pattern","What stands out","Evidence overview","The picture in the data","Key signal","Main finding","What changed","The core issue","The strongest evidence","The pattern at a glance","What matters most"],
  comparison:["Compared with the baseline","How it compares","The meaningful difference","Comparison with peers","Current versus previous","Where the gap appears","The relative position","What changed between periods","Benchmark comparison","The size of the difference","The comparison that matters","Against the reference point"],
  explanation:["What may be contributing","Evidence behind the outcome","What helps explain the result","Likely contributors in the records","How the factors connect","What the evidence can explain","Observed contributors","A measured explanation","Why the result looks this way","Factors supported by the records","What appears to be driving the outcome","How the evidence fits together"],
  counter:["What does not fit a simple explanation","Counter-evidence","Where the pattern is weaker","Evidence pointing the other way","Important exceptions","Why the conclusion needs qualification","Competing signals","What prevents an easy conclusion","Evidence that tempers the finding","The other side of the record","Where the relationship breaks","Balancing evidence"],
  limits:["Limits of the evidence","What the records cannot establish","Evidence gaps","What remains uncertain","Missing information","Where confidence is lower","What cannot be inferred safely","Unresolved questions","Data limitations","What still needs verification","Where the analysis stops","Important unknowns"],
  action:["Practical follow-up","What to do next","Targeted next steps","Management response","Recommended follow-up","Where to focus next","Action supported by the evidence","A proportionate response","What should be checked next","Next operational step","Recommended review","Follow-up priorities"],
  conclusion:["Bottom line","Conclusion from the evidence","What the analysis supports","The clearest conclusion","Overall finding","Evidence-based conclusion","What can be said with confidence","Final assessment","The practical conclusion","Where the evidence lands","The main takeaway","The conclusion the records support"]
 },
 registers:{
  executive:{sentenceTarget:[12,24],paragraphTarget:[2,4],notes:["Lead with material findings.","Prefer quantified comparisons.","Keep caveats concise but explicit.","Avoid academic jargon."]},
  "school-professional":{sentenceTarget:[11,26],paragraphTarget:[2,5],notes:["Use education language naturally.","Refer to learners, classes, teachers and periods precisely.","Do not sound disciplinary unless the evidence requires it.","Keep explanations suitable for school leadership."]},
  finance:{sentenceTarget:[10,24],paragraphTarget:[2,5],notes:["Distinguish balances, flows, accruals and cash.","Use amounts and periods precisely.","Separate accounting movement from operational explanation.","Do not infer fraud or intent without direct evidence."]},
  teacher:{sentenceTarget:[10,24],paragraphTarget:[2,4],notes:["Keep language practical and instructional.","Connect findings to teaching and learner evidence carefully.","Avoid blaming language.","Prefer actionable classroom implications."]},
  plain:{sentenceTarget:[8,20],paragraphTarget:[2,4],notes:["Use familiar words.","Explain technical terms once.","Prefer direct sentences.","Avoid corporate language."]},
  technical:{sentenceTarget:[12,30],paragraphTarget:[2,6],notes:["State methodology and denominators.","Preserve field names when needed.","Separate observation from inference.","Include limitations and data quality notes."]}
 },
 paragraphPatterns:[
  ["orient","fact","comparison","interpretation"],["fact","comparison","trend","interpretation"],["orient","fact","interpretation","limitation"],
  ["fact","trend","counterevidence","interpretation"],["comparison","fact","interpretation","conclusion"],["orient","comparison","fact","counterevidence","conclusion"],
  ["fact","fact","comparison","interpretation","recommendation"],["trend","comparison","interpretation","limitation"],["orient","fact","trend","interpretation","next-step"],
  ["fact","comparison","counterevidence","limitation","conclusion"],["orient","fact","comparison","recommendation"],["fact","interpretation","counterevidence","conclusion"],
  ["comparison","trend","fact","interpretation"],["orient","fact","limitation","recommendation"],["fact","comparison","interpretation","recommendation","conclusion"],
  ["orient","trend","fact","counterevidence","interpretation"],["fact","fact","interpretation","limitation","next-step"],["comparison","fact","counterevidence","interpretation","conclusion"]
 ] as ResponseMove[][],
 bannedBoilerplate:[
  "It is important to note that","It should be noted that","Based on the data provided","Based on the information provided","In today's fast-paced world",
  "In conclusion, it can be said that","This comprehensive analysis","delve into","multifaceted","holistic approach","leverage insights","actionable insights",
  "It is worth mentioning that","As an AI","I hope this helps","overall performance was good","needs improvement" 
 ],
 verbs:{
  increase:["rose","increased","climbed","grew","moved upward","strengthened","accelerated","expanded","advanced","picked up"],
  decrease:["fell","declined","dropped","moved downward","weakened","contracted","reduced","slipped","deteriorated","eased"],
  stable:["remained broadly stable","changed little","held near its earlier level","was largely unchanged","stayed within a narrow range","showed limited movement"],
  explain:["accounts for","helps explain","is consistent with","contributes to","is associated with","coincides with","appears alongside","provides context for","supports an explanation around","helps make sense of"],
  show:["shows","indicates","records","demonstrates","reveals","places","confirms","captures","documents","reflects"]
 }
} as const;

export function responseLibraryStats(){
 const l=RESPONSE_LIBRARY;
 const phraseCount=l.openings.length+l.factLeads.length+l.comparisonLeads.length+l.trendLeads.length+l.interpretationLeads.length+l.causalGuards.length+l.uncertainty.length+l.counterEvidence.length+l.recommendations.length+l.conclusionLeads.length+
 Object.values(l.transitions).reduce((n,a)=>n+a.length,0)+Object.values(l.sectionTitles).reduce((n,a)=>n+a.length,0)+Object.values(l.verbs).reduce((n,a)=>n+a.length,0);
 const sectionVariants=Object.values(l.sectionTitles).reduce((n,a)=>n*a.length,1);
 const discourseVariants=l.paragraphPatterns.length*l.openings.length*l.factLeads.length*l.interpretationLeads.length*l.conclusionLeads.length;
 return{phraseCount,paragraphPatterns:l.paragraphPatterns.length,sectionTitleCombinations:sectionVariants,coreDiscourseCombinations:discourseVariants,registers:Object.keys(l.registers).length};
}
