import type { AuthPrincipal, Env } from "./shared.js";
import type { AgentDefinition } from "./policy.js";
import { openAiTools } from "./memory-tools-v17.js";

export type LightTaskKind="query"|"report"|"create"|"update"|"delete"|"action"|"communication"|"document"|"analysis";
export type LightToolDescriptor={name:string;description:string;kind:LightTaskKind;module:string;group:string;source:"route"|"native";readOnly:boolean;method?:"GET"|"POST"|"PUT"|"PATCH"|"DELETE";pathTemplate?:string;nativeName?:string;parameters?:Record<string,unknown>;aliases:string[]};
export type LightToolRegistry={tools:LightToolDescriptor[];kinds:LightTaskKind[];modules:string[];groupsByModule:Record<string,string[]>;stats:{total:number;routeTools:number;nativeTools:number;writes:number;reads:number}};

const DISCOVERY=new Set(["system_catalog","system_schema","system_read","prepare_system_action"]);
const NODE_STUBBED_NATIVE=new Set(["timetable_intelligence","draft_timetable","timetable_week_context","timetable_lesson_context","timetable_contingency_options"]);
const ACTION_WORDS=new Set(["approve","reject","publish","apply","execute","reverse","void","close","reopen","archive","restore","promote","transfer","assign","unassign","send","submit","activate","deactivate","finalize","post","allocate","reconcile","reschedule","substitute"]);
const QUERY_WORDS=new Set(["search","lookup","preview","calculate","validate","check","summary","matrix","context","options","status"]);
const REPORT_WORDS=new Set(["report","reports","statement","statements","analytics","dashboard","summary"]);

function routeParts(path:string){return path.split("?")[0]!.split("/").filter(Boolean).slice(2).map(x=>x.replace(/^:/,"by-").toLowerCase());}
function words(path:string){return routeParts(path).filter(x=>!x.startsWith("by-")).map(x=>x.replace(/[-_]+/g," "));}
function tinyHash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36).slice(0,7);}
function kindFor(method:string,path:string):LightTaskKind{const ws=words(path),last=ws.at(-1)||"";if(method==="GET")return ws.some(w=>REPORT_WORDS.has(w))?"report":"query";if(method==="DELETE")return"delete";if(method==="PUT"||method==="PATCH")return"update";if(method==="POST"&&QUERY_WORDS.has(last))return"query";if(ACTION_WORDS.has(last)||ws.some(w=>ACTION_WORDS.has(w)))return"action";if(ws.some(w=>w.includes("communication")||w==="campaigns"))return"communication";if(ws.some(w=>w.includes("document")||w.includes("print")))return"document";return"create";}
function businessModule(path:string){const p=routeParts(path).filter(x=>!x.startsWith("by-"));const first=p[0]||"general",second=p[1]||"general";if(first==="school"){if(second==="student-management")return"students";if(second==="staff-management")return"staff";if(second==="fees"||second==="billing")return"fees";if(second==="setup")return"school setup";if(second==="iam")return"school iam";if(second==="discipline")return"discipline";if(second==="files")return"school files";return second.replace(/-/g," ");}return first.replace(/-/g," ");}
function groupFor(path:string){const p=routeParts(path).filter(x=>!x.startsWith("by-"));if(!p.length)return"general";if(p[0]==="school")return(p[2]||p[1]||"general").replace(/-/g," ");return(p[1]||p[0]||"general").replace(/-/g," ");}
function verb(kind:LightTaskKind){return kind==="query"?"get":kind==="report"?"report":kind==="communication"?"communicate":kind==="document"?"document":kind;}

const PROMOTED:Record<string,string>={
 "GET /api/v1/school/setup/classes":"list_classes","POST /api/v1/school/setup/classes":"create_class","GET /api/v1/school/setup/classes/:id":"get_class","PUT /api/v1/school/setup/classes/:id":"update_class","DELETE /api/v1/school/setup/classes/:id":"delete_class",
 "GET /api/v1/school/setup/classLevels":"list_class_levels","POST /api/v1/school/setup/classLevels":"create_class_level","GET /api/v1/school/setup/streams":"list_streams","POST /api/v1/school/setup/streams":"create_stream","GET /api/v1/school/setup/subjects":"list_subjects","POST /api/v1/school/setup/subjects":"create_subject","GET /api/v1/school/setup/academicYears":"list_academic_years","POST /api/v1/school/setup/academicYears":"create_academic_year","GET /api/v1/school/setup/terms":"list_terms","POST /api/v1/school/setup/terms":"create_term","GET /api/v1/school/setup/departments":"list_departments","POST /api/v1/school/setup/departments":"create_department",
 "GET /api/v1/school/student-management/students":"list_students","POST /api/v1/school/student-management/students":"create_student","GET /api/v1/school/student-management/students/:id":"get_student","PUT /api/v1/school/student-management/students/:id":"update_student","DELETE /api/v1/school/student-management/students/:id":"delete_student",
 "GET /api/v1/school/staff-management/staff":"list_staff","POST /api/v1/school/staff-management/staff":"create_staff_member","GET /api/v1/school/staff-management/staff/:id":"get_staff_member","PUT /api/v1/school/staff-management/staff/:id":"update_staff_member","DELETE /api/v1/school/staff-management/staff/:id":"delete_staff_member"
};
function routeName(method:string,path:string,kind:LightTaskKind){const promoted=PROMOTED[`${method} ${path}`];if(promoted)return promoted;const body=routeParts(path).join("_").replace(/[^a-z0-9_]+/g,"_").slice(0,70);return`route_${verb(kind)}_${body}_${tinyHash(`${method}:${path}`)}`;}
function aliases(method:string,path:string,kind:LightTaskKind,name:string){const ws=words(path),noun=ws.slice(-2).join(" "),full=ws.join(" "),set=new Set<string>([name.replace(/_/g," "),noun,full,`${verb(kind)} ${noun}`,`${verb(kind)} ${full}`]);if(kind==="create")for(const v of["create","add","new","register","make","set up","setup","start"])set.add(`${v} ${noun}`);if(kind==="query")for(const v of["get","check","find","show","search","list","view","open","lookup","browse","inspect","see","query"])set.add(`${v} ${noun}`);if(kind==="report")for(const v of["report","show report","generate report","build report","analyze","analyse","summary","dashboard","export"])set.add(`${v} ${noun}`);if(kind==="update")for(const v of["update","edit","change","modify","revise","set","adjust","rename"])set.add(`${v} ${noun}`);if(kind==="delete")for(const v of["delete","remove","drop","erase"])set.add(`${v} ${noun}`);if(kind==="action")for(const v of["run","perform","execute","apply","process"])set.add(`${v} ${noun}`);if(kind==="document")for(const v of["create","generate","build","prepare","print","export"])set.add(`${v} ${noun}`);return[...set].filter(Boolean).slice(0,24);}
function description(method:string,path:string,kind:LightTaskKind,name:string){return`${name.replace(/_/g," ")}. ${kind} operation in Ledgerly (${method} ${path}).`;}

function nativeKind(name:string,desc:string):LightTaskKind{const t=`${name} ${desc}`.toLowerCase();if(name.includes("document")||name.includes("print"))return"document";if(name.includes("communication"))return"communication";if(name.startsWith("prepare_")||name.startsWith("remember_")||name.startsWith("update_"))return name.startsWith("update_")?"update":"action";if(t.includes("report"))return"report";if(t.includes("analy")||t.includes("intelligence")||name==="delegate_to_employee")return"analysis";return"query";}
function nativeModule(name:string){if(/fee|arrears|collection/.test(name))return"fees";if(/academic|lesson|scheme|timetable/.test(name))return"academics";if(/staff|hr_/.test(name))return"staff";if(name.includes("book"))return"books";if(name.includes("communication"))return"communications";if(/student|guardian|family/.test(name))return"students";if(/document|print/.test(name))return"documents";if(name.includes("memory"))return"memory";if(name.includes("work_task"))return"tasks";return"general";}
function nativeGroup(name:string,module:string){if(name.includes("fee"))return"fees";if(name.includes("timetable"))return"timetable";if(name.includes("lesson"))return"lesson plans";if(name.includes("scheme"))return"schemes";if(/guardian|family/.test(name))return"families";if(name.includes("student"))return"students";if(/staff|hr_/.test(name))return"staff";return module;}

export async function buildLightToolRegistry(env:Env,principal:AuthPrincipal,agent:AgentDefinition):Promise<LightToolRegistry>{
 const nativeSpecs=(openAiTools(agent,null) as Array<{name:string;description?:string;parameters?:Record<string,unknown>}>).filter(x=>!DISCOVERY.has(x.name)&&!NODE_STUBBED_NATIVE.has(x.name));
 const native:LightToolDescriptor[]=nativeSpecs.map(spec=>{const d=spec.description||spec.name.replace(/_/g," "),kind=nativeKind(spec.name,d),module=nativeModule(spec.name);return{name:spec.name,description:d,kind,module,group:nativeGroup(spec.name,module),source:"native",readOnly:!spec.name.startsWith("prepare_")&&!spec.name.startsWith("remember_")&&!spec.name.startsWith("update_"),nativeName:spec.name,parameters:spec.parameters||{type:"object",properties:{}},aliases:(()=>{const readable=spec.name.replace(/_/g," "),noun=readable.replace(/^(search|prepare|update|remember|get|list|generate|create|analyze|analyse) /,""),set=new Set<string>([readable,d.toLowerCase().slice(0,180)]);if(/^(search|get|list)_/.test(spec.name))for(const v of["find","search","show","get","list","open","query"])set.add(`${v} ${noun}`);if(spec.name.startsWith("prepare_"))for(const v of["prepare","create","make","build","draft","generate"])set.add(`${v} ${noun}`);if(spec.name.startsWith("update_"))for(const v of["update","edit","change","modify"])set.add(`${v} ${noun}`);if(/report|analysis|summary/.test(readable))for(const v of["report","analyze","analyse","summarize","show"])set.add(`${v} ${noun}`);return[...set].slice(0,24);})()};});
 const gateway=env.AGENT_SYSTEM_GATEWAY;const routes=gateway?await gateway.catalog(agent.key,principal):[];
 const routed:LightToolDescriptor[]=routes.slice(0,5000).map((r:any)=>{const method=String(r.method||"GET").toUpperCase() as LightToolDescriptor["method"],path=String(r.path||""),kind=kindFor(method!,path),name=routeName(method!,path,kind);return{name,description:description(method!,path,kind,name),kind,module:businessModule(path),group:groupFor(path),source:"route",readOnly:method==="GET"||(method==="POST"&&kind==="query"),method,pathTemplate:path,aliases:aliases(method!,path,kind,name)};});
 const map=new Map<string,LightToolDescriptor>();for(const t of[...native,...routed])map.set(`${t.source}:${t.name}`,t);const tools=[...map.values()],kinds=[...new Set(tools.map(t=>t.kind))].sort() as LightTaskKind[],modules=[...new Set(tools.map(t=>t.module))].sort(),groupsByModule:Record<string,string[]>={};for(const m of modules)groupsByModule[m]=[...new Set(tools.filter(t=>t.module===m).map(t=>t.group))].sort();return{tools,kinds,modules,groupsByModule,stats:{total:tools.length,routeTools:routed.length,nativeTools:native.length,writes:tools.filter(t=>!t.readOnly).length,reads:tools.filter(t=>t.readOnly).length}};
}
export function toolsForKind(registry:LightToolRegistry,kinds:LightTaskKind[]){const s=new Set(kinds);return registry.tools.filter(t=>s.has(t.kind));}
export function toolsForModules(tools:LightToolDescriptor[],modules:string[]){const s=new Set(modules);return tools.filter(t=>s.has(t.module));}
export function toolsForGroups(tools:LightToolDescriptor[],groups:string[]){const s=new Set(groups);return tools.filter(t=>s.has(t.group));}
