import { createId } from "./shared.js";
import type { Env } from "./shared.js";
import { executeTool as baseExecute,openAiTools as baseTools } from "./tools-v15.js";
import type { ToolContext } from "./tools-v14.js";
import { lookupSystemSchema } from "./system-schemas.js";

const NAMES=["system_catalog","system_schema","system_read","prepare_system_action"] as const;
type SystemTool=typeof NAMES[number];
const SPECS:Record<SystemTool,any>={
 system_catalog:{type:"function",name:"system_catalog",strict:false,description:"List Ledgerly API operations available to this employee role on the self-hosted runtime. Use this before unfamiliar system work.",parameters:{type:"object",properties:{query:{type:"string"}},additionalProperties:false}},
 system_schema:{type:"function",name:"system_schema",strict:false,description:"Get the exact request body fields (names, types, required, enum values) for a specific Ledgerly API write path. ALWAYS call this before prepare_system_action for a POST, PUT or PATCH so the field names, enum values and required fields are correct.",parameters:{type:"object",properties:{path:{type:"string",description:"The exact /api/v1/... path you intend to write to"}},required:["path"],additionalProperties:false}},
 system_read:{type:"function",name:"system_read",strict:false,description:"Perform a read-only GET against an allowed Ledgerly API route using the current user's exact tenant, role and scopes.",parameters:{type:"object",properties:{path:{type:"string",description:"Absolute Ledgerly API path beginning /api/v1/"}},required:["path"],additionalProperties:false}},
 prepare_system_action:{type:"function",name:"prepare_system_action",strict:false,description:"Prepare a role-scoped Ledgerly API mutation (POST, PUT, PATCH or DELETE) in the AI Action Center. It does not execute until human approval and explicit execution; Ledgerly permission checks run again at execution. Call system_schema for this path first if you have not already.",parameters:{type:"object",properties:{method:{type:"string",enum:["POST","PUT","PATCH","DELETE"]},path:{type:"string"},bodyJson:{type:"string",description:"JSON request body. Use {} for DELETE or requests without fields."},title:{type:"string"},summary:{type:"string"}},required:["method","path","bodyJson","title","summary"],additionalProperties:false}}
};
function sameSet(a:readonly string[],b:readonly string[]){return a.length===b.length&&a.every(x=>b.includes(x));}
function allowed(agent:any,name:SystemTool,requested?:string[]|null){if(!agent.tools.includes(name))return false;if(!requested)return true;if(requested.includes(name))return true;const legacy=agent.tools.filter((x:string)=>!NAMES.includes(x as SystemTool));return sameSet(requested,legacy);}
function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
function pathMatchesRoute(routePath:string,actualPath:string){const a=routePath.split("/"),b=actualPath.split("/");if(a.length!==b.length)return false;return a.every((seg,i)=>seg.startsWith(":")||seg===b[i]);}
function scopeFor(path:string){const p=path.toLowerCase();if(p.includes("/accounts"))return"accounts:write";if(p.includes("/journals"))return"journals:write";if(p.includes("/reports"))return"reports:write";if(p.includes("/contacts"))return"contacts:write";if(p.includes("/documents")||p.includes("/files"))return"documents:write";if(p.includes("/payments")||p.includes("/banking"))return"payments:write";if(p.includes("/payroll"))return"payroll:write";if(p.includes("/communications"))return"communications:write";if(p.includes("/products")||p.includes("/inventory"))return"products:write";return"school:write";}
export function openAiTools(agent:any,requested?:string[]|null){return[...baseTools(agent,requested),...NAMES.filter(name=>allowed(agent,name,requested)).map(name=>SPECS[name])];}
export async function executeTool(ctx:ToolContext & {env?:Env},name:string,raw:unknown){if(!NAMES.includes(name as SystemTool))return baseExecute(ctx,name,raw);if(!allowed(ctx.agent,name as SystemTool,ctx.requestedTools))throw new Error(`${name} is not enabled for this employee`);const env=ctx.env as Env|undefined;if(!env?.AGENT_SYSTEM_GATEWAY)throw new Error("The self-hosted delegated system gateway is not available");const args=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>;
 if(name==="system_catalog"){const routes=await env.AGENT_SYSTEM_GATEWAY.catalog(ctx.agent.key,ctx.principal),q=String(args.query||"").trim().toLowerCase();const tokens=q.split(/[\s/_-]+/).filter(Boolean);const matched=tokens.length?routes.filter(r=>{const haystack=`${r.method} ${r.path}`.toLowerCase();return tokens.every(t=>haystack.includes(t));}):routes;return{role:ctx.agent.key,routeCount:matched.length,routes:matched.slice(0,250),advice:!tokens.length&&routes.length>250?"This is only the first 250 of many available routes. Pass a query (e.g. path keywords like 'staff' or 'class') to search the full catalog for this role.":undefined};}
 if(name==="system_schema"){const path=String(args.path||"").trim(),schema=lookupSystemSchema(path);if(!schema)return{path,cataloged:false,advice:"No curated schema for this path. Call system_read on the list endpoint for this resource (or a similar one) first and match the field names/types you see in an existing record before preparing this action."};return{path,cataloged:true,method:schema.method,fields:schema.fields};}
 if(name==="system_read"){const path=String(args.path||"").trim();const result=await env.AGENT_SYSTEM_GATEWAY.request({agentKey:ctx.agent.key,principal:ctx.principal,method:"GET",path});if(!result.ok)throw new Error(`Ledgerly API ${result.status}: ${JSON.stringify(result.data).slice(0,1200)}`);return result.data;}
 const method=String(args.method||"").toUpperCase() as "POST"|"PUT"|"PATCH"|"DELETE",path=String(args.path||"").trim(),title=String(args.title||"Ledgerly action").trim().slice(0,200),summary=String(args.summary||"").trim().slice(0,600);if(!["POST","PUT","PATCH","DELETE"].includes(method)||!path.startsWith("/api/v1/"))throw new Error("A valid Ledgerly API method and /api/v1/ path are required");
 const knownRoutes=await env.AGENT_SYSTEM_GATEWAY.catalog(ctx.agent.key,ctx.principal);
 if(!knownRoutes.some(r=>r.method===method&&pathMatchesRoute(r.path,path)))throw new Error(`No ${method} route exists at ${path}. This path was not found in system_catalog — do not guess Ledgerly API paths from convention. Call system_catalog with a keyword (e.g. the resource name) to find the exact real path, then try again.`);
 let body:unknown={};try{body=JSON.parse(String(args.bodyJson||"{}"));}catch{throw new Error("bodyJson must be valid JSON");}const payload={agentKey:ctx.agent.key,method,path,body},key=`conversation:${ctx.conversationId}:system:${method}:${path}:${hash(JSON.stringify(body))}`,id=createId("aea");await ctx.db.prepare(`INSERT INTO ae_actions(id,organization_id,agent_key,action_type,title,summary,required_scope,payload_json,idempotency_key,status) VALUES(?,?,?,?,?,?,?,?,?,'suggested') ON CONFLICT(organization_id,idempotency_key) DO NOTHING`).bind(id,ctx.principal.organizationId,ctx.agent.key,"system.api.request",title,summary||`${method} ${path}`,scopeFor(path),JSON.stringify(payload),key).run();const action=await ctx.db.prepare("SELECT id,status,title,action_type AS actionType,required_scope AS requiredScope FROM ae_actions WHERE organization_id=? AND idempotency_key=?").bind(ctx.principal.organizationId,key).first();return{prepared:true,executed:false,requiresHumanApproval:true,action};}
