import { Archive, BarChart3, CalendarClock, Droplets, Gauge, LifeBuoy, ListChecks, LockKeyhole, Printer, Receipt, Route, ScanLine, ShieldCheck, ShoppingCart } from "lucide-react";
import type { FrontendModuleDefinition } from "../../frontend-types";
import { PrinterlyWorkspace } from "./PrinterlyWorkspace";
import { PrinterlyOperationsWorkspace } from "./PrinterlyOperationsWorkspace";
import { PrinterlyReportsWorkspace } from "./PrinterlyReportsWorkspace";
import { PrinterlyQuotaWorkspace } from "./PrinterlyQuotaWorkspace";
import { PrinterlyRulesWorkspace } from "./PrinterlyRulesWorkspace";
import { PrinterlyBatchesWorkspace } from "./PrinterlyBatchesWorkspace";
import { PrinterlyAuditWorkspace } from "./PrinterlyAuditWorkspace";
import { PrinterlyRoutingWorkspace } from "./PrinterlyRoutingWorkspace";
import { PrinterlyReleaseWorkspace } from "./PrinterlyReleaseWorkspace";
import { PrinterlyRetentionWorkspace } from "./PrinterlyRetentionWorkspace";
import { PrinterlySuppliesWorkspace } from "./PrinterlySuppliesWorkspace";
import { PrinterlyProcurementWorkspace } from "./PrinterlyProcurementWorkspace";
import { PrinterlyServiceDeskWorkspace } from "./PrinterlyServiceDeskWorkspace";
import { PrinterlyReceiptsWorkspace } from "./PrinterlyReceiptsWorkspace";
import { PrintWithPrinterlyAction } from "./PrintWithPrinterlyAction";
import { ScannerlyInboxAction } from "./ScannerlyInboxAction";
import "./printerly.css";
const moduleDefinition:FrontendModuleDefinition={key:"printerly",name:"Printerly",version:"1.15.0",order:42,routes:{printerly:{view:PrinterlyWorkspace},"printerly-receipts":{view:PrinterlyReceiptsWorkspace},"printerly-operations":{view:PrinterlyOperationsWorkspace},"printerly-reports":{view:PrinterlyReportsWorkspace},"printerly-quotas":{view:PrinterlyQuotaWorkspace,admin:true},"printerly-rules":{view:PrinterlyRulesWorkspace},"printerly-batches":{view:PrinterlyBatchesWorkspace},"printerly-audit":{view:PrinterlyAuditWorkspace},"printerly-routing":{view:PrinterlyRoutingWorkspace,admin:true},"printerly-release":{view:PrinterlyReleaseWorkspace},"printerly-retention":{view:PrinterlyRetentionWorkspace,admin:true},"printerly-supplies":{view:PrinterlySuppliesWorkspace},"printerly-procurement":{view:PrinterlyProcurementWorkspace},"printerly-service-desk":{view:PrinterlyServiceDeskWorkspace}},navigation:[{label:"Printerly",icon:Printer,order:42,items:[{label:"Print Center",path:"printerly", icon: Printer},{label:"Automatic Receipts",path:"printerly-receipts", icon: Receipt},{label:"Operations & Scannerly",path:"printerly-operations", icon: ScanLine},{label:"Secure Release",path:"printerly-release", icon: LockKeyhole},{label:"Usage Reports",path:"printerly-reports", icon: BarChart3},{label:"Quotas & Governance",path:"printerly-quotas",admin:true, icon: Gauge},{label:"Rules & Approvals",path:"printerly-rules", icon: ListChecks},{label:"Schedules & Batches",path:"printerly-batches", icon: CalendarClock},{label:"Audit & Compliance",path:"printerly-audit", icon: ShieldCheck},{label:"Printer Pools & Routing",path:"printerly-routing",admin:true, icon: Route},{label:"Retention & Privacy",path:"printerly-retention",admin:true, icon: Archive},{label:"Supplies & Maintenance",path:"printerly-supplies", icon: Droplets},{label:"Procurement & Replenishment",path:"printerly-procurement", icon: ShoppingCart},{label:"Service Desk & SLA",path:"printerly-service-desk", icon: LifeBuoy}]}],globalActions:[{key:"printerly-global-print",label:"Print with Printerly",order:42,component:PrintWithPrinterlyAction},{key:"printerly-global-scannerly",label:"Scannerly",order:43,component:ScannerlyInboxAction}]};export default moduleDefinition;
