import { useEffect,useMemo,useState } from "react";
import type { FormEvent } from "react";
import { CalendarClock,Files,Play,RefreshCw,RotateCcw,Trash2,Upload } from "lucide-react";
import { errorText,get,post,uploadFile } from "../../../web/api";
import type { CostingOptions,PrinterlyPrinter } from "./client";

type BatchItem={id:string;title:string;documentName:string;status:string;jobId?:string|null;jobNumber?:string|null;jobStatus?:string|null;errorMessage?:string|null;attempts:number};
type Batch={id:string;batchNumber:string;name:string;description?:string;status:string;scheduledAt?:string|null;itemCount?:number;pendingCount?:number;dispatchingCount?:number;submittedCount?:number;failedCount?:number;completedJobs?:number;activeJobs?:number;createdBy?:string;items?:BatchItem[]};
type UploadDoc={id:string;originalName:string;mimeType:string;sizeBytes:number;checksum:string};

const statusLabel=(s:string)=>({scheduled:"Scheduled",ready:"Ready",dispatching:"Dispatching",active:"In progress",completed:"Completed",partial:"Completed with issues",failed:"Failed",cancelled:"Cancelled"}[s]||s);
const localInput=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)};

export function PrinterlyBatchesWorkspace(){
  const[batches,setBatches]=useState<Batch[]>([]),[selected,setSelected]=useState<Batch|null>(null),[costing,setCosting]=useState<CostingOptions|null>(null),[printers,setPrinters]=useState<PrinterlyPrinter[]>([]),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[files,setFiles]=useState<File[]>([]);
  const[name,setName]=useState(""),[description,setDescription]=useState(""),[scheduledAt,setScheduledAt]=useState(""),[printerId,setPrinterId]=useState(""),[copies,setCopies]=useState(1),[priority,setPriority]=useState("normal"),[pageSize,setPageSize]=useState("A4"),[colorMode,setColorMode]=useState("monochrome"),[duplex,setDuplex]=useState(false),[secureRelease,setSecureRelease]=useState(false),[projectId,setProjectId]=useState(""),[department,setDepartment]=useState("");
  const active=useMemo(()=>batches.filter(b=>["scheduled","ready","dispatching","active"].includes(b.status)).length,[batches]);
  const load=async()=>{setBusy(true);setErr("");try{const[b,p,c]=await Promise.all([get<Batch[]>("/printerly/batches"),get<PrinterlyPrinter[]>("/printerly/printers"),get<CostingOptions>("/printerly/costing/options")]);setBatches(b);setPrinters(p);setCosting(c);if(selected){const fresh=await get<Batch>(`/printerly/batches/${selected.id}`);setSelected(fresh)}}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
  const open=async(id:string)=>{setBusy(true);setErr("");try{setSelected(await get<Batch>(`/printerly/batches/${id}`))}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const reset=()=>{setFiles([]);setName("");setDescription("");setScheduledAt("");setPrinterId("");setCopies(1);setPriority("normal");setPageSize("A4");setColorMode("monochrome");setDuplex(false);setSecureRelease(false);setProjectId("");setDepartment("")};
  const create=async(e:FormEvent)=>{e.preventDefault();if(!files.length)return;setBusy(true);setErr("");const uploaded:UploadDoc[]=[];try{for(const file of files)uploaded.push(await uploadFile<UploadDoc>("/printerly/documents",file,"printerly-batch"));const[departmentType,departmentId]=department?department.split(":"):[];const batch=await post<Batch>("/printerly/batches",{name:name||`Print batch · ${new Date().toLocaleDateString()}`,description,scheduledAt:scheduledAt?new Date(scheduledAt).toISOString():null,defaults:{printerId:printerId||null,copies,priority,pageSize,colorMode,duplex,secureRelease,projectId:projectId||null,departmentType:departmentType||null,departmentId:departmentId||null},items:uploaded.map((d,i)=>({documentId:d.id,title:files[i]?.name||d.originalName,settings:{estimatedPages:1}}))});reset();await load();await open(batch.id)}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const act=async(kind:"dispatch"|"cancel",batch:Batch)=>{setBusy(true);setErr("");try{await post(`/printerly/batches/${batch.id}/${kind}`,{});await load();await open(batch.id)}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const retry=async(batchId:string,itemId:string)=>{setBusy(true);setErr("");try{await post(`/printerly/batches/${batchId}/items/${itemId}/retry`,{});await load();await open(batchId)}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  return <div className="printerly">
    <header className="prn-hero"><div><div className="prn-kicker">SCHEDULE · BATCH · GOVERN</div><h1>Schedules & batches</h1><p>Send many documents together now or schedule them for later. Every item still passes current Printerly policy, approval and quota controls at dispatch time.</p></div><div className="prn-actions"><button className="prn-ghost" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>Refresh</button></div></header>
    {err&&<div className="prn-error">{err}</div>}
    <div className="prn-metrics"><div><span>Active batches</span><b>{active}</b></div><div><span>Total batches</span><b>{batches.length}</b></div><div><span>Selected documents</span><b>{files.length}</b></div></div>
    <div className="prn-grid">
      <section className="prn-card"><div className="prn-cardhead"><div><span>NEW BATCH</span><h2>Schedule multiple documents</h2></div><Files size={20}/></div>
        <form onSubmit={create}><label>Batch name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Friday report pack"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional purpose or instructions"/></label><label>Documents<input type="file" multiple accept="application/pdf,image/png,image/jpeg,text/plain" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,100))} required/></label>{files.length>0&&<div className="prn-capture"><Upload size={17}/><div><b>{files.length} document{files.length===1?"":"s"}</b><small>{files.slice(0,4).map(f=>f.name).join(" · ")}{files.length>4?` · +${files.length-4} more`:""}</small></div></div>}
          <div className="prn-formgrid"><label>Run at<input type="datetime-local" min={localInput(new Date())} value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/><small>Leave blank to dispatch immediately.</small></label><label>Printer<select value={printerId} onChange={e=>setPrinterId(e.target.value)}><option value="">Auto route</option>{printers.map(p=><option key={p.id} value={p.id}>{p.name}{p.location?` · ${p.location}`:""}</option>)}</select></label><label>Copies<input type="number" min="1" max="1000" value={copies} onChange={e=>setCopies(Math.max(1,Number(e.target.value)||1))}/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="bulk">Bulk</option></select></label><label>Paper<select value={pageSize} onChange={e=>setPageSize(e.target.value)}><option>A4</option><option>A5</option><option>Letter</option><option>Legal</option></select></label><label>Colour<select value={colorMode} onChange={e=>setColorMode(e.target.value)}><option value="monochrome">Black & white</option><option value="color">Colour</option></select></label><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{costing?.projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">No department</option><optgroup label="Finance">{costing?.financeDepartments.map(d=><option key={d.id} value={`finance:${d.id}`}>{d.code} · {d.name}</option>)}</optgroup><optgroup label="School">{costing?.schoolDepartments.map(d=><option key={d.id} value={`school:${d.id}`}>{d.code} · {d.name}</option>)}</optgroup></select></label></div>
          <div className="prn-inlinechecks"><label className="prn-check"><input type="checkbox" checked={duplex} onChange={e=>setDuplex(e.target.checked)}/> Duplex</label><label className="prn-check"><input type="checkbox" checked={secureRelease} onChange={e=>setSecureRelease(e.target.checked)}/> Secure release</label></div>
          <button className="prn-primary" disabled={busy||!files.length} type="submit"><CalendarClock size={15}/>{busy?"Preparing…":scheduledAt?"Schedule batch":"Create & dispatch"}</button>
        </form>
      </section>
      <section className="prn-card"><div className="prn-cardhead"><div><span>BATCH HISTORY</span><h2>Recent schedules</h2></div></div>{batches.map(b=><button key={b.id} className="prn-row prn-row-button" onClick={()=>void open(b.id)}><span><b>{b.batchNumber} · {b.name}</b><small>{statusLabel(b.status)} · {b.itemCount||0} items{b.scheduledAt?` · ${new Date(b.scheduledAt).toLocaleString()}`:""}</small></span><span><b>{b.completedJobs||0}/{b.itemCount||0}</b><small>completed</small></span></button>)}{!batches.length&&<div className="prn-empty">No Printerly batches yet.</div>}</section>
    </div>
    {selected&&<section className="prn-card"><div className="prn-cardhead"><div><span>{selected.batchNumber}</span><h2>{selected.name}</h2><p>{statusLabel(selected.status)}{selected.scheduledAt?` · scheduled ${new Date(selected.scheduledAt).toLocaleString()}`:""}</p></div><div className="prn-actions">{["ready","scheduled"].includes(selected.status)&&<button className="prn-primary" onClick={()=>void act("dispatch",selected)} disabled={busy}><Play size={15}/>Dispatch now</button>}{["ready","scheduled"].includes(selected.status)&&<button className="prn-danger" onClick={()=>void act("cancel",selected)} disabled={busy}><Trash2 size={15}/>Cancel batch</button>}</div></div>
      {selected.items?.map(i=><div className="prn-row" key={i.id}><span><b>{i.title}</b><small>{i.documentName} · {i.jobNumber?`${i.jobNumber} · `:""}{i.jobStatus||i.status}{i.errorMessage?` · ${i.errorMessage}`:""}</small></span>{i.status==="failed"&&!i.jobId&&<button className="prn-ghost" onClick={()=>void retry(selected.id,i.id)} disabled={busy}><RotateCcw size={14}/>Retry</button>}</div>)}
    </section>}
    {busy&&<div className="prn-sync">Updating Printerly schedules…</div>}
  </div>;
}
