import { useEffect,useMemo,useState } from "react";
import { CheckCircle2,Clock3,RefreshCw,ShieldCheck,SlidersHorizontal,Trash2,XCircle } from "lucide-react";
import { authStore,del,errorText,get,post,put } from "../../../web/api";

type Opt={id:string;name:string;code?:string;email?:string;role?:string;location?:string;status?:string};
type Options={roles:string[];users:Opt[];projects:Opt[];financeDepartments:Opt[];schoolDepartments:Opt[];printers:Opt[]};
type Rule={id:string;name:string;description?:string;active:boolean;priority:number;match:any;action:any;updatedAt:string};
type Approval={id:string;jobId:string;jobNumber:string;title:string;status:string;requestedBy:string;requestedAt:string;requesterName?:string;requesterEmail?:string;approverRoles:string[];approverUserIds:string[];allowSelfApproval:boolean;priority:string;copies:number;pageSize:string;colorMode:string;duplex:boolean;secureRelease:boolean;estimatedImpressions?:number;estimatedCostMinor?:number;decisionNote?:string;decidedAt?:string};
const money=(v:any)=>Number(v||0).toLocaleString();
const emptyForm={name:"",description:"",priority:100,role:"",userId:"",projectId:"",department:"",sourceModule:"",colorMode:"",minImpressions:"",minCostMinor:"",block:false,blockMessage:"",requireApproval:false,approverRoles:["owner","admin"],approverUserId:"",allowSelfApproval:false,forceDuplex:false,forceMonochrome:false,forceSecureRelease:false,printerId:"",forcePriority:""};

export function PrinterlyRulesWorkspace(){
  const principal=authStore.principal(),canAdmin=!!principal&&(principal.role==="owner"||principal.role==="admin"||principal.scopes.includes("admin:write"));
  const[tab,setTab]=useState<"approvals"|"rules">("approvals"),[options,setOptions]=useState<Options|null>(null),[rules,setRules]=useState<Rule[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<any>(emptyForm),[notes,setNotes]=useState<Record<string,string>>({});
  const pending=useMemo(()=>approvals.filter(a=>a.status==="pending"),[approvals]);
  const load=async()=>{setBusy(true);setErr("");try{const[o,r,a]=await Promise.all([get<Options>("/printerly/rules/options"),get<Rule[]>("/printerly/rules"),get<Approval[]>("/printerly/approvals")]);setOptions(o);setRules(r);setApprovals(a)}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const edit=(r:Rule)=>{const m=r.match||{},a=r.action||{};setEditing(r.id);setForm({name:r.name,description:r.description||"",priority:r.priority,role:m.roles?.[0]||"",userId:m.userIds?.[0]||"",projectId:m.projectIds?.[0]||"",department:m.departments?.[0]||"",sourceModule:m.sourceModules?.[0]||"",colorMode:m.colorModes?.[0]||"",minImpressions:m.minImpressions??"",minCostMinor:m.minCostMinor??"",block:Boolean(a.block),blockMessage:a.blockMessage||"",requireApproval:Boolean(a.requireApproval),approverRoles:a.approverRoles?.length?a.approverRoles:["owner","admin"],approverUserId:a.approverUserIds?.[0]||"",allowSelfApproval:Boolean(a.allowSelfApproval),forceDuplex:Boolean(a.forceDuplex),forceMonochrome:Boolean(a.forceMonochrome),forceSecureRelease:Boolean(a.forceSecureRelease),printerId:a.printerId||"",forcePriority:a.priority||""});setTab("rules")};
  const reset=()=>{setEditing(null);setForm(emptyForm)};
  const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setErr("");try{const payload={name:form.name,description:form.description,priority:Number(form.priority)||100,match:{roles:form.role?[form.role]:[],userIds:form.userId?[form.userId]:[],projectIds:form.projectId?[form.projectId]:[],departments:form.department?[form.department]:[],sourceModules:form.sourceModule?[form.sourceModule]:[],colorModes:form.colorMode?[form.colorMode]:[],minImpressions:form.minImpressions===""?null:Number(form.minImpressions),minCostMinor:form.minCostMinor===""?null:Number(form.minCostMinor)},action:{block:form.block,blockMessage:form.blockMessage,requireApproval:form.requireApproval,approverRoles:form.approverRoles,approverUserIds:form.approverUserId?[form.approverUserId]:[],allowSelfApproval:form.allowSelfApproval,forceDuplex:form.forceDuplex,forceMonochrome:form.forceMonochrome,forceSecureRelease:form.forceSecureRelease,printerId:form.printerId||null,priority:form.forcePriority||null}};if(editing)await put(`/printerly/rules/${editing}`,payload);else await post("/printerly/rules",payload);reset();await load()}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const deactivate=async(id:string)=>{setBusy(true);setErr("");try{await del(`/printerly/rules/${id}`);await load()}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const cancelRequest=async(a:Approval)=>{setBusy(true);setErr("");try{await post(`/printerly/jobs/${a.jobId}/cancel`,{});await load()}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const decide=async(a:Approval,decision:"approve"|"reject")=>{setBusy(true);setErr("");try{await post(`/printerly/approvals/${a.id}/${decision}`,{note:notes[a.id]||""});await load()}catch(e){setErr(errorText(e))}finally{setBusy(false)}};
  const roleToggle=(role:string)=>setForm((f:any)=>({...f,approverRoles:f.approverRoles.includes(role)?f.approverRoles.filter((x:string)=>x!==role):[...f.approverRoles,role]}));
  return <div className="printerly">
    <header className="prn-hero"><div><div className="prn-kicker">POLICY · APPROVAL · CONTROL</div><h1>Rules & approvals</h1><p>Automatically enforce print policy before a job can reach a Printerly Node.</p></div><div className="prn-actions"><button className="prn-ghost" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>Refresh</button></div></header>
    {err&&<div className="prn-error">{err}</div>}
    <div className="prn-tabs"><button className={tab==="approvals"?"active":""} onClick={()=>setTab("approvals")}><Clock3 size={15}/>Approvals {pending.length?`(${pending.length})`:""}</button>{canAdmin&&<button className={tab==="rules"?"active":""} onClick={()=>setTab("rules")}><SlidersHorizontal size={15}/>Print rules</button>}</div>
    {tab==="approvals"&&<section className="prn-card"><div className="prn-cardhead"><div><span>APPROVAL QUEUE</span><h2>Print requests awaiting a decision</h2></div></div>
      {approvals.map(a=><div className="prn-row" key={a.id}><span><b>{a.jobNumber} · {a.title}</b><small>{a.requesterName||a.requesterEmail||"Requester"} · {a.copies} copies · {a.colorMode} · {money(a.estimatedImpressions)} impressions{a.secureRelease?" · secure release":""}</small><small>Status: {a.status}{a.decisionNote?` · ${a.decisionNote}`:""}</small></span>{a.status==="pending"?<div className="prn-actions"><input style={{minWidth:190}} placeholder="Decision note" value={notes[a.id]||""} onChange={e=>setNotes(n=>({...n,[a.id]:e.target.value}))}/><button className="prn-primary" onClick={()=>void decide(a,"approve")} disabled={busy}><CheckCircle2 size={15}/>Approve</button><button className="prn-danger" onClick={()=>void decide(a,"reject")} disabled={busy}><XCircle size={15}/>Reject</button>{a.requestedBy===principal?.userId&&<button className="prn-ghost" onClick={()=>void cancelRequest(a)} disabled={busy}>Cancel request</button>}</div>:<span><b>{a.status}</b><small>{a.decidedAt||""}</small></span>}</div>)}
      {!approvals.length&&<div className="prn-empty">No Printerly approvals are visible to you.</div>}
    </section>}
    {tab==="rules"&&canAdmin&&<div className="prn-grid">
      <section className="prn-card"><div className="prn-cardhead"><div><span>{editing?"EDIT POLICY":"NEW POLICY"}</span><h2>{editing?"Update print rule":"Create print rule"}</h2></div>{editing&&<button className="prn-ghost" onClick={reset}>Cancel edit</button>}</div>
        <form onSubmit={save}><label>Rule name<input value={form.name} onChange={e=>setForm((f:any)=>({...f,name:e.target.value}))} required/></label><label>Description<textarea value={form.description} onChange={e=>setForm((f:any)=>({...f,description:e.target.value}))}/></label>
          <div className="prn-formgrid"><label>Priority<input type="number" min="1" max="1000" value={form.priority} onChange={e=>setForm((f:any)=>({...f,priority:e.target.value}))}/></label><label>Requester role<select value={form.role} onChange={e=>setForm((f:any)=>({...f,role:e.target.value}))}><option value="">Any role</option>{options?.roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Requester<select value={form.userId} onChange={e=>setForm((f:any)=>({...f,userId:e.target.value}))}><option value="">Any user</option>{options?.users.map(u=><option key={u.id} value={u.id}>{u.name||u.email}</option>)}</select></label><label>Project<select value={form.projectId} onChange={e=>setForm((f:any)=>({...f,projectId:e.target.value}))}><option value="">Any project</option>{options?.projects.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Department<select value={form.department} onChange={e=>setForm((f:any)=>({...f,department:e.target.value}))}><option value="">Any department</option><optgroup label="Finance">{options?.financeDepartments.map(x=><option key={x.id} value={`finance:${x.id}`}>{x.code} · {x.name}</option>)}</optgroup><optgroup label="School">{options?.schoolDepartments.map(x=><option key={x.id} value={`school:${x.id}`}>{x.code} · {x.name}</option>)}</optgroup></select></label><label>Source module<input placeholder="e.g. school-management" value={form.sourceModule} onChange={e=>setForm((f:any)=>({...f,sourceModule:e.target.value}))}/></label><label>Colour condition<select value={form.colorMode} onChange={e=>setForm((f:any)=>({...f,colorMode:e.target.value}))}><option value="">Any</option><option value="color">Colour</option><option value="monochrome">B&W</option></select></label><label>Minimum impressions<input type="number" min="0" value={form.minImpressions} onChange={e=>setForm((f:any)=>({...f,minImpressions:e.target.value}))}/></label><label>Minimum estimated cost<input type="number" min="0" value={form.minCostMinor} onChange={e=>setForm((f:any)=>({...f,minCostMinor:e.target.value}))}/></label></div>
          <div className="prn-inlinechecks"><label className="prn-check"><input type="checkbox" checked={form.block} onChange={e=>setForm((f:any)=>({...f,block:e.target.checked}))}/> Block job</label><label className="prn-check"><input type="checkbox" checked={form.requireApproval} onChange={e=>setForm((f:any)=>({...f,requireApproval:e.target.checked}))}/> Require approval</label><label className="prn-check"><input type="checkbox" checked={form.forceDuplex} onChange={e=>setForm((f:any)=>({...f,forceDuplex:e.target.checked}))}/> Force duplex</label><label className="prn-check"><input type="checkbox" checked={form.forceMonochrome} onChange={e=>setForm((f:any)=>({...f,forceMonochrome:e.target.checked}))}/> Force B&W</label><label className="prn-check"><input type="checkbox" checked={form.forceSecureRelease} onChange={e=>setForm((f:any)=>({...f,forceSecureRelease:e.target.checked}))}/> Force secure release</label></div>
          {form.block&&<label>Block message<input value={form.blockMessage} onChange={e=>setForm((f:any)=>({...f,blockMessage:e.target.value}))} placeholder="Explain why this job is blocked"/></label>}
          {form.requireApproval&&<><label>Approver roles<div className="prn-inlinechecks">{["owner","admin","manager","accountant"].map(r=><label className="prn-check" key={r}><input type="checkbox" checked={form.approverRoles.includes(r)} onChange={()=>roleToggle(r)}/>{r}</label>)}</div></label><div className="prn-formgrid"><label>Specific approver<select value={form.approverUserId} onChange={e=>setForm((f:any)=>({...f,approverUserId:e.target.value}))}><option value="">No specific user</option>{options?.users.map(u=><option key={u.id} value={u.id}>{u.name||u.email}</option>)}</select></label><label className="prn-check"><input type="checkbox" checked={form.allowSelfApproval} onChange={e=>setForm((f:any)=>({...f,allowSelfApproval:e.target.checked}))}/> Allow requester self-approval</label></div></>}
          <div className="prn-formgrid"><label>Route to printer<select value={form.printerId} onChange={e=>setForm((f:any)=>({...f,printerId:e.target.value}))}><option value="">Do not force a printer</option>{options?.printers.map(p=><option key={p.id} value={p.id}>{p.name}{p.location?` · ${p.location}`:""}</option>)}</select></label><label>Force priority<select value={form.forcePriority} onChange={e=>setForm((f:any)=>({...f,forcePriority:e.target.value}))}><option value="">Keep requested priority</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="bulk">Bulk</option></select></label></div>
          <button className="prn-primary" disabled={busy} type="submit"><ShieldCheck size={15}/>{editing?"Save changes":"Create policy"}</button>
        </form>
      </section>
      <section className="prn-card"><div className="prn-cardhead"><div><span>ACTIVE POLICY</span><h2>Configured rules</h2></div></div>{rules.map(r=><div className="prn-row" key={r.id}><span><b>{r.priority} · {r.name}</b><small>{r.active?"Active":"Inactive"} · {(r.action?.block?"Block · ":"")+(r.action?.requireApproval?"Approval · ":"")+(r.action?.forceDuplex?"Duplex · ":"")+(r.action?.forceMonochrome?"B&W · ":"")+(r.action?.forceSecureRelease?"Secure release":"")}</small><small>{r.description||"No description"}</small></span><div className="prn-actions">{r.active&&<button className="prn-ghost" onClick={()=>edit(r)}>Edit</button>}{r.active&&<button className="prn-danger" onClick={()=>void deactivate(r.id)} disabled={busy}><Trash2 size={14}/>Disable</button>}</div></div>)}{!rules.length&&<div className="prn-empty">No automatic print policies configured yet.</div>}</section>
    </div>}
    {busy&&<div className="prn-sync">Updating Printerly governance…</div>}
  </div>
}
