import {useEffect,useState} from "react";
import {Copy,KeyRound,LockKeyhole,RefreshCw,ShieldCheck,TimerReset,XCircle} from "lucide-react";
import {errorText,get,post} from "../../../web/api";

type Job={id:string;jobNumber:string;title:string;status:string;printerName?:string;printerLocation?:string;requesterName?:string;createdAt:string;credentialId?:string;credentialExpiresAt?:string;credentialAttempts?:number;credentialMaxAttempts?:number;credentialLockedAt?:string;credentialActive:boolean};
type Credential={id:string;jobId:string;jobNumber:string;title:string;pin:string;token:string;qrValue:string;expiresAt:string};
export function PrinterlyReleaseWorkspace(){
 const[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[credential,setCredential]=useState<Credential|null>(null),[ttl,setTtl]=useState(15);
 const load=async()=>{setBusy(true);setError("");try{setJobs(await get<Job[]>("/printerly/release/jobs"))}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 const issue=async(job:Job)=>{setBusy(true);setError("");try{const c=await post<Credential>(`/printerly/release/jobs/${job.id}/credential`,{ttlMinutes:ttl});setCredential(c);await load()}catch(e){setError(errorText(e));setBusy(false)}};
 const revoke=async(job:Job)=>{if(!confirm(`Revoke the active release credential for ${job.jobNumber}?`))return;setBusy(true);setError("");try{await post(`/printerly/release/jobs/${job.id}/revoke`,{});await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value)}catch{prompt("Copy this value",value)}};
 return <div className="printerly"><header className="prn-hero"><div><div className="prn-kicker"><LockKeyhole size={14}/> CONFIDENTIAL OUTPUT CONTROL</div><h1>Secure Release</h1><p>Generate short-lived release credentials for confidential jobs, then release them only at the physical Printerly Node beside the selected printer.</p></div><div className="prn-actions"><label style={{display:"flex",gap:8,alignItems:"center"}}><span style={{fontSize:12}}>Credential life</span><select value={ttl} onChange={e=>setTtl(Number(e.target.value))}><option value={5}>5 min</option><option value={15}>15 min</option><option value={30}>30 min</option><option value={60}>1 hour</option></select></label><button className="prn-ghost" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></div></header>
 {error&&<div className="prn-error">{error}</div>}
 <section className="prn-security"><ShieldCheck/><div><b>Secrets are never stored in plaintext.</b><p>The six-digit PIN and high-entropy QR token are shown only when generated. Ledgerly stores their SHA-256 digests, limits failed attempts and expires them automatically.</p></div><KeyRound/></section>
 <section className="prn-card"><div className="prn-cardhead"><div><span>HELD OUTPUT</span><h2>Jobs waiting for secure release</h2></div></div><div className="prn-table"><div className="prn-tr prn-th"><span>Job</span><span>Printer</span><span>Status</span><span>Credential</span><span>Actions</span></div>{jobs.length?jobs.map(j=><div className="prn-tr" key={j.id}><span><b>{j.title}</b><small>{j.jobNumber}{j.requesterName?` · ${j.requesterName}`:""}</small></span><span>{j.printerName||"Auto route"}<small>{j.printerLocation||""}</small></span><span><em className={`prn-pill ${j.status}`}>{j.status}</em></span><span>{j.status==="approval_pending"?<><b>After approval</b><small>No credential until the job is held.</small></>:j.credentialActive?<><b>Active</b><small>Expires {new Date(j.credentialExpiresAt!).toLocaleTimeString()} · {j.credentialAttempts||0}/{j.credentialMaxAttempts||5} attempts</small></>:j.credentialLockedAt?<><b>Locked</b><small>Generate a new credential.</small></>:<><b>None</b><small>Generate when you are ready to collect.</small></>}</span><span style={{display:"flex",gap:6,flexWrap:"wrap"}}>{j.status==="held"&&<button className="prn-primary" disabled={busy} onClick={()=>void issue(j)}><KeyRound size={14}/>{j.credentialActive?"Regenerate":"Generate"}</button>}{j.credentialId&&<button className="prn-secondary" disabled={busy} onClick={()=>void revoke(j)}><XCircle size={14}/>Revoke</button>}</span></div>):<div className="prn-empty">No secure jobs are waiting for release.</div>}</div></section>
 <section className="prn-card"><div className="prn-cardhead"><div><span>AT THE PRINTER</span><h2>Release station</h2></div></div><div className="prn-capture"><TimerReset size={18}/><div><b>Open the local Printerly release portal beside the printer.</b><small>Default: http://127.0.0.1:8791 on the Printerly Node. A separate kiosk/tablet can use the Node LAN address when releaseStationHost is configured for LAN access.</small></div></div></section>
 {credential&&<div className="prn-modalback"><div className="prn-modal"><div className="prn-modalhead"><div><small>SHOW ONCE</small><h3>Release credential · {credential.jobNumber}</h3></div><button onClick={()=>setCredential(null)}>×</button></div><div className="prn-pair"><small>SIX-DIGIT RELEASE PIN</small><strong>{credential.pin.slice(0,3)} {credential.pin.slice(3)}</strong><p>Expires {new Date(credential.expiresAt).toLocaleTimeString()}. Generating another credential invalidates this one.</p><button className="prn-secondary" onClick={()=>void copy(credential.pin)}><Copy size={14}/>Copy PIN</button></div><label>QR credential payload<textarea readOnly value={credential.qrValue} rows={3}/><small>Use this value with a QR-capable release scanner. It is a high-entropy single-use credential, not the Node machine token.</small></label><div className="prn-modal-actions"><button className="prn-secondary" onClick={()=>void copy(credential.qrValue)}><Copy size={14}/>Copy QR payload</button><button className="prn-primary" onClick={()=>setCredential(null)}>I saved it</button></div></div></div>}
 {busy&&<div className="prn-sync">Updating secure release…</div>}</div>
}
