import { Hono } from 'hono';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { requireScope } from '../core-identity/security.js';

function validDate(v:string|undefined,fallback:string){return v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:fallback;}
function csv(v:unknown){return `"${String(v??'').replaceAll('"','""')}"`;}
function label(v:string){return v.split('-').map(x=>x?x[0]!.toUpperCase()+x.slice(1):x).join(' ');}

async function audit(runtime:Runtime,org:string,query:Record<string,string|undefined>){
 const today=new Date().toISOString().slice(0,10),from=validDate(query.from,new Date(Date.now()-30*86400000).toISOString().slice(0,10)),to=validDate(query.to,today);if(from>to)throw new AppError(422,'INVALID_AUDIT_RANGE','Choose a valid audit date range');
 const start=`${from}T00:00:00.000Z`,end=`${to}T23:59:59.999Z`,limit=Math.min(500,Math.max(1,Number(query.limit)||100)),offset=Math.max(0,Number(query.offset)||0);
 const q=await runtime.db.query(`WITH records AS (
  SELECT e.created_at ts,'print' category,e.event_type,e.actor_id,u.display_name actor_name,j.job_number reference,'print_job' entity_type,j.id entity_id,j.title,e.details details FROM prn_job_events e JOIN prn_jobs j ON j.id=e.job_id AND j.organization_id=e.organization_id LEFT JOIN users u ON u.id=e.actor_id WHERE e.organization_id=$1 AND e.created_at BETWEEN $2 AND $3
  UNION ALL SELECT e.created_at,'scan',e.event_type,e.actor_id,u.display_name,s.scan_number,'scan_job',s.id,s.title,e.details FROM prn_scan_events e JOIN prn_scan_jobs s ON s.id=e.scan_job_id AND s.organization_id=e.organization_id LEFT JOIN users u ON u.id=e.actor_id WHERE e.organization_id=$1 AND e.created_at BETWEEN $2 AND $3
  UNION ALL SELECT a.decided_at,'approval','approval_'||a.status,a.decided_by,u.display_name,j.job_number,'print_job',j.id,j.title,jsonb_build_object('note',a.decision_note) FROM prn_approvals a JOIN prn_jobs j ON j.id=a.job_id AND j.organization_id=a.organization_id LEFT JOIN users u ON u.id=a.decided_by WHERE a.organization_id=$1 AND a.decided_at BETWEEN $2 AND $3
  UNION ALL SELECT e.created_at,'retention',e.event_type,e.actor_id,u.display_name,e.entity_id,e.entity_type,e.entity_id,e.event_type,e.details FROM prn_retention_events e LEFT JOIN users u ON u.id=e.actor_id WHERE e.organization_id=$1 AND e.created_at BETWEEN $2 AND $3
 ) SELECT *,COUNT(*) OVER() total FROM records WHERE ($4='' OR category=$4) AND ($5='' OR actor_id=$5) AND ($6='' OR lower(COALESCE(event_type,'')||' '||COALESCE(actor_name,'')||' '||COALESCE(reference,'')||' '||COALESCE(title,'')) LIKE '%'||lower($6)||'%') ORDER BY ts DESC LIMIT $7 OFFSET $8`,[org,start,end,query.category??'',query.userId??'',query.q??'',limit,offset]);
 return {from,to,records:q.rows,total:Number((q.rows[0] as any)?.total||0),offset,limit,hasMore:offset+q.rows.length<Number((q.rows[0] as any)?.total||0)};
}

export function createPrinterlyAuditMobileRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('documents:read'));
 r.get('/audit/users',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT DISTINCT u.id,u.display_name name,u.email FROM users u JOIN memberships m ON m.user_id=u.id AND m.organization_id=$1 WHERE u.id IN(SELECT actor_id FROM prn_job_events WHERE organization_id=$1 UNION SELECT actor_id FROM prn_scan_events WHERE organization_id=$1 UNION SELECT decided_by FROM prn_approvals WHERE organization_id=$1 AND decided_by IS NOT NULL) ORDER BY name,email`,[p.organizationId]);return c.json({data:q.rows});});
 r.get('/audit',async c=>{const p=c.get('principal');return c.json({data:await audit(runtime,p.organizationId,{from:c.req.query('from'),to:c.req.query('to'),category:c.req.query('category'),userId:c.req.query('userId'),q:c.req.query('q'),offset:c.req.query('offset'),limit:c.req.query('limit')})});});
 r.get('/audit.csv',async c=>{const p=c.get('principal'),x=await audit(runtime,p.organizationId,{from:c.req.query('from'),to:c.req.query('to'),category:c.req.query('category'),userId:c.req.query('userId'),q:c.req.query('q'),limit:'500'});const head=['timestamp','category','event_type','actor','actor_id','reference','entity_type','entity_id','title','details'];const lines=[head.join(',')];for(const y of x.records as any[])lines.push([y.ts,y.category,y.event_type,y.actor_name,y.actor_id,y.reference,y.entity_type,y.entity_id,y.title,JSON.stringify(y.details??{})].map(csv).join(','));c.header('Content-Type','text/csv; charset=utf-8');c.header('Content-Disposition',`attachment; filename="printerly-audit-${x.from}-to-${x.to}.csv"`);return c.body('\uFEFF'+lines.join('\n')+'\n');});
 r.get('/rules/mobile-options',async c=>{const p=c.get('principal');const [users,projects,printers,pools,mods]=await Promise.all([runtime.db.query(`SELECT u.id,u.display_name name,u.email FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 ORDER BY u.display_name,u.email LIMIT 500`,[p.organizationId]),runtime.db.query(`SELECT id,name FROM projects WHERE organization_id=$1 ORDER BY name LIMIT 500`,[p.organizationId]).catch(()=>({rows:[]} as any)),runtime.db.query(`SELECT id,name,status FROM prn_printers WHERE organization_id=$1 ORDER BY name`,[p.organizationId]),runtime.db.query(`SELECT id,name FROM prn_printer_pools WHERE organization_id=$1 AND active=true ORDER BY name`,[p.organizationId]).catch(()=>({rows:[]} as any)),runtime.db.query(`SELECT module_key id FROM organization_modules WHERE organization_id=$1 AND enabled=true AND module_key<>'mobile-sync' ORDER BY module_key`,[p.organizationId]).catch(()=>({rows:[]} as any))]);return c.json({data:{users:users.rows,projects:projects.rows,printers:printers.rows,pools:pools.rows,modules:mods.rows.map((x:any)=>({id:x.id,name:label(String(x.id))})),roles:['owner','admin','manager','accountant','viewer'],priorities:['urgent','high','normal','bulk'],colorModes:['monochrome','color'],actions:['block','require_approval','force_duplex','force_monochrome','force_secure_release','route_printer','force_priority']}});});
 return r;}
