import { Hono } from 'hono';
import { z } from 'zod';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { createId, requireScope } from '../core-identity/security.js';
import { ensureCostProfile } from './costing-core.js';
import { checkPrinterlyQuotas } from './quotas.js';

const ruleSchema=z.object({name:z.string().min(1).max(160),description:z.string().max(800).nullable().optional(),priority:z.number().int().min(1).max(1000).default(100),active:z.boolean().default(true),match:z.record(z.string(),z.any()).default({}),action:z.record(z.string(),z.any()).default({})});
function applies(rule:any,p:any,body:any,metrics:any){const m=rule.match_json||{};if(Array.isArray(m.roles)&&m.roles.length&&!m.roles.includes(p.role))return false;if(Array.isArray(m.userIds)&&m.userIds.length&&!m.userIds.includes(p.userId))return false;if(Array.isArray(m.projectIds)&&m.projectIds.length&&!m.projectIds.includes(body.projectId))return false;if(m.minImpressions!=null&&metrics.impressions<Number(m.minImpressions))return false;if(m.maxImpressions!=null&&metrics.impressions>Number(m.maxImpressions))return false;if(m.minCostMinor!=null&&metrics.costMinor<Number(m.minCostMinor))return false;return true;}
export async function previewPrinterlyPolicy(runtime:Runtime,p:any,body:any){const copies=Math.max(1,Number(body.copies||1)),pages=Math.max(1,Number(body.estimatedPages||1)),impressions=copies*pages,sheets=body.duplex?Math.ceil(impressions/2):impressions,profile=await ensureCostProfile(runtime,p.organizationId),costMinor=sheets*Number(profile.paperCostMinor||0)+impressions*(Number(body.colorMode==='color'?profile.colorTonerCostMinor:profile.bwTonerCostMinor||0)+Number(profile.maintenanceCostMinor||0)+Number(profile.electricityCostMinor||0)),rules=await runtime.db.query(`SELECT * FROM prn_print_rules WHERE organization_id=$1 AND active=true ORDER BY priority,created_at`,[p.organizationId]);let effective={...body},blocked=false,blockMessage='',requireApproval=false;const ruleIds:string[]=[];let approverRoles=['owner','admin'],approverUserIds:string[]=[];for(const r of rules.rows as any[]){if(!applies(r,p,body,{impressions,sheets,costMinor}))continue;const a=r.action_json||{};ruleIds.push(r.id);if(a.block&&!blocked){blocked=true;blockMessage=String(a.blockMessage||'This print request is blocked by organization policy');}if(a.requireApproval){requireApproval=true;if(Array.isArray(a.approverRoles)&&a.approverRoles.length)approverRoles=a.approverRoles;if(Array.isArray(a.approverUserIds))approverUserIds=a.approverUserIds;}if(a.forceDuplex)effective.duplex=true;if(a.forceMonochrome)effective.colorMode='monochrome';if(a.forceSecureRelease)effective.secureRelease=true;if(a.printerId)effective.printerId=a.printerId;if(a.priority)effective.priority=a.priority;}const quota=await checkPrinterlyQuotas(runtime,p,{projectId:body.projectId??null,impressions,sheets,costMinor});return {blocked,blockMessage,requireApproval,ruleIds,approverRoles,approverUserIds,effective,estimate:{impressions,sheets,costMinor},quota};}

export function createPrinterlyPolicyRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('documents:read'));
 r.get('/rules',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT * FROM prn_print_rules WHERE organization_id=$1 ORDER BY active DESC,priority,created_at`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/rules',requireScope('admin:write'),async c=>{const s=ruleSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid Printerly policy',s.error.flatten());const p=c.get('principal'),id=createId('prnrule'),v=s.data;await runtime.db.query(`INSERT INTO prn_print_rules(id,organization_id,name,description,active,priority,match_json,action_json,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$9)`,[id,p.organizationId,v.name,v.description??null,v.active,v.priority,JSON.stringify(v.match),JSON.stringify(v.action),p.userId]);return c.json({data:{id,...v}},201);});
 r.delete('/rules/:id',requireScope('admin:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE prn_print_rules SET active=false,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND active=true RETURNING id`,[p.userId,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'NOT_FOUND','Policy not found');return c.json({data:{id:c.req.param('id'),active:false}});});
 r.post('/rules/preview',async c=>{const p=c.get('principal'),body=await c.req.json().catch(()=>({}));return c.json({data:await previewPrinterlyPolicy(runtime,p,body)});});
 r.post('/jobs/:id/request-approval',requireScope('documents:write'),async c=>{const p=c.get('principal'),body=await c.req.json().catch(()=>({})),preview=await previewPrinterlyPolicy(runtime,p,body);if(preview.blocked)throw new AppError(409,'PRINT_POLICY_BLOCKED',preview.blockMessage,{preview});if(!preview.quota.allowed)throw new AppError(409,'PRINTERLY_QUOTA_EXCEEDED','This print job exceeds a hard Printerly quota',{preview});if(!preview.requireApproval)throw new AppError(409,'APPROVAL_NOT_REQUIRED','No active Printerly policy requires approval for this request');const client=await runtime.db.connect();try{await client.query('BEGIN');const job=await client.query(`UPDATE prn_jobs SET status='approval_pending',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status IN ('queued','held') RETURNING id`,[c.req.param('id'),p.organizationId]);if(!job.rowCount)throw new AppError(409,'INVALID_STATE','Only queued or held jobs can request approval');const id=createId('prnappr');await client.query(`INSERT INTO prn_approvals(id,organization_id,job_id,rule_ids,requested_by,approver_roles,approver_user_ids) VALUES($1,$2,$3,$4::jsonb,$5,$6::jsonb,$7::jsonb) ON CONFLICT (organization_id,job_id) DO NOTHING`,[id,p.organizationId,c.req.param('id'),JSON.stringify(preview.ruleIds),p.userId,JSON.stringify(preview.approverRoles),JSON.stringify(preview.approverUserIds)]);await client.query('COMMIT');return c.json({data:{id,jobId:c.req.param('id'),status:'pending'}});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}});
 r.get('/approvals',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT a.*,j.job_number AS "jobNumber",j.title FROM prn_approvals a JOIN prn_jobs j ON j.id=a.job_id WHERE a.organization_id=$1 ORDER BY a.requested_at DESC LIMIT 300`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/approvals/:id/:decision',async c=>{const p=c.get('principal'),decision=c.req.param('decision');if(!['approve','reject'].includes(decision))throw new AppError(404,'NOT_FOUND','Unknown approval decision');const client=await runtime.db.connect();try{await client.query('BEGIN');const q=await client.query(`SELECT * FROM prn_approvals WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'NOT_FOUND','Approval not found');const a=q.rows[0] as any;if(a.status!=='pending')throw new AppError(409,'INVALID_STATE','Approval is already decided');const roles=Array.isArray(a.approver_roles)?a.approver_roles:[],users=Array.isArray(a.approver_user_ids)?a.approver_user_ids:[];if(p.role!=='owner'&&p.role!=='admin'&&!roles.includes(p.role)&&!users.includes(p.userId))throw new AppError(403,'FORBIDDEN','You are not an approver for this job');const status=decision==='approve'?'approved':'rejected';await client.query(`UPDATE prn_approvals SET status=$1,decided_by=$2,decided_at=CURRENT_TIMESTAMP WHERE id=$3`,[status,p.userId,a.id]);await client.query(`UPDATE prn_jobs SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status='approval_pending'`,[decision==='approve'?'queued':'cancelled',a.job_id,p.organizationId]);await client.query('COMMIT');return c.json({data:{id:a.id,status,jobId:a.job_id}});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}});
 return r;}
