import { Hono } from 'hono';
import { z } from 'zod';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { createId, requireScope } from '../core-identity/security.js';

const schema=z.object({name:z.string().min(1).max(160),scopeType:z.enum(['organization','user','project']).default('organization'),scopeId:z.string().nullable().optional(),mode:z.enum(['soft','hard']).default('soft'),maxImpressions:z.number().int().min(0).default(0),maxSheets:z.number().int().min(0).default(0),maxCostMinor:z.number().int().min(0).default(0),warningPercent:z.number().int().min(1).max(100).default(80)});
async function usage(runtime:Runtime,org:string,q:any){const month=new Date().toISOString().slice(0,7),params:any[]=[org,`${month}-01`,`${month}-01`],extra=q.scope_type==='user'?` AND j.created_by=$4`:q.scope_type==='project'?` AND j.charge_project_id=$4`:'';if(extra)params.push(q.scope_id);const x=await runtime.db.query(`SELECT COALESCE(SUM(COALESCE(actual_impressions,estimated_impressions,0)),0)::bigint impressions,COALESCE(SUM(COALESCE(actual_sheets,estimated_sheets,total_sheets,0)),0)::bigint sheets,COALESCE(SUM(COALESCE(actual_cost_minor,estimated_cost_minor,0)),0)::bigint cost FROM prn_jobs j WHERE j.organization_id=$1 AND j.status NOT IN ('cancelled','failed') AND j.created_at::date >= $2::date AND j.created_at::date < ($3::date + INTERVAL '1 month')${extra}`,params);const r=x.rows[0] as any;return {periodKey:month,impressions:Number(r.impressions),sheets:Number(r.sheets),costMinor:Number(r.cost)};}
export async function checkPrinterlyQuotas(runtime:Runtime,p:any,request:{projectId?:string|null;impressions:number;sheets:number;costMinor:number}){const q=await runtime.db.query(`SELECT * FROM prn_quotas WHERE organization_id=$1 AND active=true AND (scope_type='organization' OR (scope_type='user' AND scope_id=$2) OR (scope_type='project' AND scope_id=$3))`,[p.organizationId,p.userId,request.projectId??null]),items:any[]=[];let allowed=true;for(const row of q.rows as any[]){const u=await usage(runtime,p.organizationId,row),projected={impressions:u.impressions+request.impressions,sheets:u.sheets+request.sheets,costMinor:u.costMinor+request.costMinor},exceeded=(Number(row.max_impressions)>0&&projected.impressions>Number(row.max_impressions))||(Number(row.max_sheets)>0&&projected.sheets>Number(row.max_sheets))||(Number(row.max_cost_minor)>0&&projected.costMinor>Number(row.max_cost_minor));if(row.mode==='hard'&&exceeded)allowed=false;items.push({...row,usage:u,projected,exceeded});}return {allowed,quotas:items};}
export function createPrinterlyQuotaRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('documents:read'));
 r.get('/quotas',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT * FROM prn_quotas WHERE organization_id=$1 AND active=true ORDER BY name`,[p.organizationId]),out=[];for(const x of q.rows as any[])out.push({...x,usage:await usage(runtime,p.organizationId,x)});return c.json({data:out});});
 r.post('/quotas',requireScope('admin:write'),async c=>{const s=schema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid Printerly quota',s.error.flatten());const p=c.get('principal'),v=s.data;if(!v.maxImpressions&&!v.maxSheets&&!v.maxCostMinor)throw new AppError(422,'QUOTA_LIMIT_REQUIRED','Set at least one quota limit');if(v.scopeType!=='organization'&&!v.scopeId)throw new AppError(422,'QUOTA_SCOPE_REQUIRED','Choose a quota target');const id=createId('prnquota');await runtime.db.query(`INSERT INTO prn_quotas(id,organization_id,name,scope_type,scope_id,mode,max_impressions,max_sheets,max_cost_minor,warning_percent,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,p.organizationId,v.name,v.scopeType,v.scopeType==='organization'?null:v.scopeId,v.mode,v.maxImpressions,v.maxSheets,v.maxCostMinor,v.warningPercent,p.userId]);return c.json({data:{id,...v}},201);});
 r.delete('/quotas/:id',requireScope('admin:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE prn_quotas SET active=false,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND active=true RETURNING id`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'NOT_FOUND','Quota not found');return c.json({data:{id:c.req.param('id'),active:false}});});
 return r;}
