import { Hono } from 'hono';
import { z } from 'zod';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { createId, requireScope } from '../core-identity/security.js';

const poolSchema=z.object({name:z.string().min(1).max(160),description:z.string().max(800).nullable().optional(),routingMode:z.enum(['priority','least_loaded']).default('priority'),printerIds:z.array(z.string()).min(1),active:z.boolean().default(true)});
const batchSchema=z.object({name:z.string().min(1).max(160),scheduledAt:z.string().datetime().nullable().optional(),jobIds:z.array(z.string()).min(1).max(500)});

async function resolvePool(runtime:Runtime,org:string,poolId:string){const pool=await runtime.db.query(`SELECT * FROM prn_printer_pools WHERE id=$1 AND organization_id=$2 AND active=true`,[poolId,org]);if(!pool.rowCount)throw new AppError(404,'POOL_NOT_FOUND','Printer pool not found');const mode=(pool.rows[0] as any).routing_mode;const order=mode==='least_loaded'?`active_jobs ASC,m.priority,p.name`:`m.priority,p.name`;const q=await runtime.db.query(`SELECT p.id,p.name,p.system_name AS "systemName",p.location,p.status,m.priority,COUNT(j.id) FILTER(WHERE j.status IN ('queued','claimed','downloading','spooling','printing'))::int AS active_jobs FROM prn_printer_pool_members m JOIN prn_printers p ON p.id=m.printer_id AND p.organization_id=m.organization_id LEFT JOIN prn_jobs j ON j.printer_id=p.id AND j.organization_id=p.organization_id WHERE m.organization_id=$1 AND m.pool_id=$2 AND m.enabled=true AND p.status='ready' GROUP BY p.id,m.priority ORDER BY ${order} LIMIT 1`,[org,poolId]);return {pool:pool.rows[0],printer:q.rows[0]??null};}

export function createPrinterlyRoutingBatchRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('documents:read'));
 r.get('/pools',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT x.id,x.name,x.description,x.routing_mode AS "routingMode",x.active,x.created_at AS "createdAt",COUNT(m.printer_id)::int AS "printerCount" FROM prn_printer_pools x LEFT JOIN prn_printer_pool_members m ON m.organization_id=x.organization_id AND m.pool_id=x.id AND m.enabled=true WHERE x.organization_id=$1 GROUP BY x.id ORDER BY x.active DESC,x.name`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/pools',requireScope('admin:write'),async c=>{const s=poolSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid printer pool',s.error.flatten());const p=c.get('principal'),printers=await runtime.db.query(`SELECT id FROM prn_printers WHERE organization_id=$1 AND id=ANY($2::text[])`,[p.organizationId,s.data.printerIds]);if(printers.rows.length!==new Set(s.data.printerIds).size)throw new AppError(422,'INVALID_PRINTER','Every pool printer must belong to this organization');const id=createId('prnpool'),client=await runtime.db.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO prn_printer_pools(id,organization_id,name,description,routing_mode,active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,p.organizationId,s.data.name,s.data.description??null,s.data.routingMode,s.data.active,p.userId]);for(const [i,printerId] of s.data.printerIds.entries())await client.query(`INSERT INTO prn_printer_pool_members(organization_id,pool_id,printer_id,priority) VALUES($1,$2,$3,$4)`,[p.organizationId,id,printerId,(i+1)*10]);await client.query('COMMIT');return c.json({data:{id,...s.data}},201);}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}});
 r.delete('/pools/:id',requireScope('admin:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE prn_printer_pools SET active=false,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND active=true RETURNING id`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(404,'POOL_NOT_FOUND','Active printer pool not found');return c.json({data:{id:c.req.param('id'),active:false}});});
 r.post('/pools/:id/preview',async c=>{const p=c.get('principal'),result=await resolvePool(runtime,p.organizationId,c.req.param('id'));return c.json({data:{poolId:c.req.param('id'),printer:result.printer}});});
 r.post('/jobs/:id/route',requireScope('documents:write'),async c=>{const p=c.get('principal'),body=await c.req.json().catch(()=>({})) as any,poolId=String(body.poolId||'');if(!poolId)throw new AppError(422,'POOL_REQUIRED','Choose a printer pool');const resolved=await resolvePool(runtime,p.organizationId,poolId);if(!resolved.printer)throw new AppError(409,'NO_READY_PRINTER','The selected pool has no ready printers');const q=await runtime.db.query(`UPDATE prn_jobs SET printer_id=$1,route_pool_id=$2,route_reason=$3,routed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND organization_id=$5 AND status IN ('queued','held') RETURNING id,status`,[(resolved.printer as any).id,poolId,`Pool ${String((resolved.pool as any).name)}`,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(409,'INVALID_STATE','Only queued or held jobs can be routed');return c.json({data:{id:c.req.param('id'),poolId,printer:resolved.printer,status:(q.rows[0] as any).status}});});

 r.get('/batches',async c=>{const p=c.get('principal'),q=await runtime.db.query(`SELECT b.id,b.name,b.status,b.scheduled_at AS "scheduledAt",b.queued_at AS "queuedAt",b.completed_at AS "completedAt",b.created_at AS "createdAt",COUNT(i.id)::int AS "itemCount",COUNT(j.id) FILTER(WHERE j.status='completed')::int AS "completedJobs",COUNT(j.id) FILTER(WHERE j.status='failed')::int AS "failedJobs" FROM prn_batches b LEFT JOIN prn_batch_items i ON i.organization_id=b.organization_id AND i.batch_id=b.id LEFT JOIN prn_jobs j ON j.organization_id=i.organization_id AND j.id=i.job_id WHERE b.organization_id=$1 GROUP BY b.id ORDER BY b.created_at DESC LIMIT 200`,[p.organizationId]);return c.json({data:q.rows});});
 r.post('/batches',requireScope('documents:write'),async c=>{const s=batchSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid print batch',s.error.flatten());const p=c.get('principal'),jobs=await runtime.db.query(`SELECT id,status FROM prn_jobs WHERE organization_id=$1 AND id=ANY($2::text[])`,[p.organizationId,s.data.jobIds]);if(jobs.rows.length!==new Set(s.data.jobIds).size)throw new AppError(422,'INVALID_JOB','Every batch job must belong to this organization');if(jobs.rows.some((j:any)=>!['queued','held'].includes(j.status)))throw new AppError(409,'INVALID_JOB_STATE','Only queued or held jobs can be added to a batch');const id=createId('prnbatch'),client=await runtime.db.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO prn_batches(id,organization_id,name,status,scheduled_at,created_by) VALUES($1,$2,$3,'draft',$4,$5)`,[id,p.organizationId,s.data.name,s.data.scheduledAt??null,p.userId]);for(const [i,jobId] of s.data.jobIds.entries()){await client.query(`INSERT INTO prn_batch_items(id,organization_id,batch_id,job_id,sequence) VALUES($1,$2,$3,$4,$5)`,[createId('prnbi'),p.organizationId,id,jobId,i+1]);await client.query(`UPDATE prn_jobs SET batch_id=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3`,[id,jobId,p.organizationId]);}await client.query('COMMIT');return c.json({data:{id,name:s.data.name,status:'draft',scheduledAt:s.data.scheduledAt??null,itemCount:s.data.jobIds.length}},201);}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}});
 r.post('/batches/:id/queue',requireScope('documents:write'),async c=>{const p=c.get('principal'),client=await runtime.db.connect();try{await client.query('BEGIN');const batch=await client.query(`SELECT * FROM prn_batches WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[c.req.param('id'),p.organizationId]);if(!batch.rowCount)throw new AppError(404,'BATCH_NOT_FOUND','Print batch not found');if((batch.rows[0] as any).status!=='draft')throw new AppError(409,'INVALID_STATE','Only draft batches can be queued');const held=await client.query(`SELECT COUNT(*)::int count FROM prn_batch_items i JOIN prn_jobs j ON j.id=i.job_id AND j.organization_id=i.organization_id WHERE i.organization_id=$1 AND i.batch_id=$2 AND j.status='held'`,[p.organizationId,c.req.param('id')]);if(Number((held.rows[0] as any)?.count||0)>0)throw new AppError(409,'BATCH_HAS_HELD_JOBS','Release secure jobs before queueing the batch');await client.query(`UPDATE prn_batches SET status='queued',queued_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2`,[c.req.param('id'),p.organizationId]);await client.query('COMMIT');return c.json({data:{id:c.req.param('id'),status:'queued'}});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}});
 r.post('/batches/:id/cancel',requireScope('documents:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE prn_batches SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status IN ('draft','queued') RETURNING id`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(409,'INVALID_STATE','Only draft or queued batches can be cancelled');return c.json({data:{id:c.req.param('id'),status:'cancelled'}});});
 return r;}
