import { Hono } from 'hono';
import { z } from 'zod';
import { AppError } from '../../http/errors.js';
import type { AppEnv } from '../../http/types.js';
import type { Runtime } from '../../runtime.js';
import { createId, requireScope } from '../core-identity/security.js';

const settingsSchema=z.object({responseSlaMinutes:z.number().int().min(1).max(10080).default(60),resolutionSlaMinutes:z.number().int().min(1).max(43200).default(480),autoCreateFromCriticalAlerts:z.boolean().default(true)});
const ticketSchema=z.object({title:z.string().min(1).max(200),description:z.string().max(2000).nullable().optional(),priority:z.enum(['low','medium','high','critical']).default('medium'),printerId:z.string().nullable().optional(),nodeId:z.string().nullable().optional()});
const windowSchema=z.object({printerId:z.string().nullable().optional(),nodeId:z.string().nullable().optional(),title:z.string().min(1).max(200),startsAt:z.string().datetime(),endsAt:z.string().datetime(),notes:z.string().max(1000).nullable().optional()});

function tnum(id:string){return `TKT-${new Date().getUTCFullYear()}-${id.slice(-8).toUpperCase()}`}
async function settings(runtime:Runtime,org:string){const q=await runtime.db.query(`SELECT response_sla_minutes AS "responseSlaMinutes",resolution_sla_minutes AS "resolutionSlaMinutes",auto_create_from_critical_alerts AS "autoCreateFromCriticalAlerts" FROM prn_service_desk_settings WHERE organization_id=$1`,[org]);return q.rows[0]??{responseSlaMinutes:60,resolutionSlaMinutes:480,autoCreateFromCriticalAlerts:true};}
async function member(runtime:Runtime,org:string,userId:string){const q=await runtime.db.query(`SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$2`,[org,userId]);if(!q.rowCount)throw new AppError(422,'INVALID_ASSIGNEE','Assignee is not a member of this organization');}

export function createPrinterlyServiceDeskRoutes(runtime:Runtime){const r=new Hono<AppEnv>();r.use('*',requireScope('documents:read'));
 r.get('/service-desk',async c=>{const p=c.get('principal');const [cfg,tickets,windows]=await Promise.all([settings(runtime,p.organizationId),runtime.db.query(`SELECT t.*,p.name AS printer_name,n.name AS node_name,u.display_name AS assignee_name FROM prn_service_tickets t LEFT JOIN prn_printers p ON p.id=t.printer_id AND p.organization_id=t.organization_id LEFT JOIN prn_nodes n ON n.id=t.node_id AND n.organization_id=t.organization_id LEFT JOIN users u ON u.id=t.assignee_id WHERE t.organization_id=$1 ORDER BY CASE t.priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,t.created_at DESC LIMIT 300`,[p.organizationId]),runtime.db.query(`SELECT w.*,p.name AS printer_name,n.name AS node_name FROM prn_maintenance_windows w LEFT JOIN prn_printers p ON p.id=w.printer_id AND p.organization_id=w.organization_id LEFT JOIN prn_nodes n ON n.id=w.node_id AND n.organization_id=w.organization_id WHERE w.organization_id=$1 ORDER BY w.starts_at DESC LIMIT 200`,[p.organizationId])]);return c.json({data:{settings:cfg,tickets:tickets.rows,maintenanceWindows:windows.rows}});});
 r.put('/service-desk/settings',requireScope('admin:write'),async c=>{const p=c.get('principal'),s=settingsSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid service desk settings',s.error.flatten());await runtime.db.query(`INSERT INTO prn_service_desk_settings(organization_id,response_sla_minutes,resolution_sla_minutes,auto_create_from_critical_alerts,updated_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT (organization_id) DO UPDATE SET response_sla_minutes=EXCLUDED.response_sla_minutes,resolution_sla_minutes=EXCLUDED.resolution_sla_minutes,auto_create_from_critical_alerts=EXCLUDED.auto_create_from_critical_alerts,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP`,[p.organizationId,s.data.responseSlaMinutes,s.data.resolutionSlaMinutes,s.data.autoCreateFromCriticalAlerts,p.userId]);return c.json({data:s.data});});
 r.post('/service-desk/tickets',requireScope('documents:write'),async c=>{const p=c.get('principal'),s=ticketSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid ticket',s.error.flatten());if(!s.data.printerId&&!s.data.nodeId)throw new AppError(422,'ASSET_REQUIRED','Choose a printer or Printerly node');const cfg=await settings(runtime,p.organizationId),id=createId('prntkt');await runtime.db.query(`INSERT INTO prn_service_tickets(id,organization_id,ticket_number,title,description,priority,printer_id,node_id,created_by,response_due_at,resolution_due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,CURRENT_TIMESTAMP+($10||' minutes')::interval,CURRENT_TIMESTAMP+($11||' minutes')::interval)`,[id,p.organizationId,tnum(id),s.data.title,s.data.description??null,s.data.priority,s.data.printerId??null,s.data.nodeId??null,p.userId,cfg.responseSlaMinutes,cfg.resolutionSlaMinutes]);return c.json({data:{id,ticketNumber:tnum(id),status:'open'}},201);});
 r.post('/service-desk/tickets/:id/assign',requireScope('documents:write'),async c=>{const p=c.get('principal'),b=await c.req.json().catch(()=>({})),assigneeId=String((b as any).assigneeId||'');await member(runtime,p.organizationId,assigneeId);const q=await runtime.db.query(`UPDATE prn_service_tickets SET assignee_id=$1,status=CASE WHEN status='open' THEN 'assigned' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status NOT IN ('resolved','closed','cancelled') RETURNING id`,[assigneeId,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(409,'INVALID_TICKET_STATE','Ticket cannot be assigned');await runtime.db.query(`INSERT INTO prn_service_ticket_events(id,organization_id,ticket_id,event_type,actor_id,notes) VALUES($1,$2,$3,'assigned',$4,$5)`,[createId('prntktev'),p.organizationId,c.req.param('id'),p.userId,assigneeId]);return c.json({data:{id:c.req.param('id'),assigneeId}});});
 r.post('/service-desk/tickets/:id/acknowledge',requireScope('documents:write'),async c=>{const p=c.get('principal'),q=await runtime.db.query(`UPDATE prn_service_tickets SET status='acknowledged',acknowledged_at=COALESCE(acknowledged_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND organization_id=$2 AND status IN ('open','assigned') RETURNING id`,[c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(409,'INVALID_TICKET_STATE','Ticket cannot be acknowledged');return c.json({data:{id:c.req.param('id'),status:'acknowledged'}});});
 r.post('/service-desk/tickets/:id/status',requireScope('documents:write'),async c=>{const p=c.get('principal'),b=await c.req.json().catch(()=>({})),status=String((b as any).status||'');if(!['in_progress','closed','cancelled'].includes(status))throw new AppError(422,'INVALID_STATUS','Invalid service ticket status');const q=await runtime.db.query(`UPDATE prn_service_tickets SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status NOT IN ('resolved','closed','cancelled') RETURNING id`,[status,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(409,'INVALID_TICKET_STATE','Ticket cannot change status');return c.json({data:{id:c.req.param('id'),status}});});
 r.post('/service-desk/tickets/:id/comments',requireScope('documents:write'),async c=>{const p=c.get('principal'),b=await c.req.json().catch(()=>({})),notes=String((b as any).notes||'').trim().slice(0,2000);if(!notes)throw new AppError(422,'COMMENT_REQUIRED','Comment is required');await runtime.db.query(`INSERT INTO prn_service_ticket_events(id,organization_id,ticket_id,event_type,actor_id,notes) SELECT $1,$2,id,'comment',$3,$4 FROM prn_service_tickets WHERE id=$5 AND organization_id=$2`,[createId('prntktev'),p.organizationId,p.userId,notes,c.req.param('id')]);return c.json({data:{created:true}},201);});
 r.post('/service-desk/tickets/:id/resolve',requireScope('documents:write'),async c=>{const p=c.get('principal'),b=await c.req.json().catch(()=>({})),notes=String((b as any).notes||'').trim().slice(0,2000);const q=await runtime.db.query(`UPDATE prn_service_tickets SET status='resolved',resolved_at=CURRENT_TIMESTAMP,resolution_notes=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND organization_id=$3 AND status NOT IN ('resolved','closed','cancelled') RETURNING id`,[notes||null,c.req.param('id'),p.organizationId]);if(!q.rowCount)throw new AppError(409,'INVALID_TICKET_STATE','Ticket cannot be resolved');return c.json({data:{id:c.req.param('id'),status:'resolved'}});});
 r.post('/service-desk/maintenance-windows',requireScope('admin:write'),async c=>{const p=c.get('principal'),s=windowSchema.safeParse(await c.req.json().catch(()=>null));if(!s.success)throw new AppError(422,'VALIDATION_ERROR','Invalid maintenance window',s.error.flatten());if(!s.data.printerId&&!s.data.nodeId)throw new AppError(422,'ASSET_REQUIRED','Choose a printer or node');if(new Date(s.data.endsAt)<=new Date(s.data.startsAt))throw new AppError(422,'INVALID_WINDOW','Maintenance window end must be after start');const id=createId('prnwin');await runtime.db.query(`INSERT INTO prn_maintenance_windows(id,organization_id,printer_id,node_id,title,starts_at,ends_at,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.organizationId,s.data.printerId??null,s.data.nodeId??null,s.data.title,s.data.startsAt,s.data.endsAt,s.data.notes??null,p.userId]);return c.json({data:{id,...s.data}},201);});
 return r;}

export async function sweepPrinterlyServiceDesk(runtime:Runtime){const orgs=await runtime.db.query(`SELECT id FROM organizations WHERE status='active'`);for(const org of orgs.rows as any[]){const cfg=await settings(runtime,org.id);if(cfg.autoCreateFromCriticalAlerts){const alerts=await runtime.db.query(`SELECT a.id,a.title,a.body,a.entity_type,a.entity_id FROM prn_alerts a WHERE a.organization_id=$1 AND a.severity='critical' AND a.resolved_at IS NULL AND NOT EXISTS(SELECT 1 FROM prn_service_tickets t WHERE t.organization_id=a.organization_id AND t.source_alert_id=a.id AND t.status NOT IN ('resolved','closed','cancelled')) LIMIT 100`,[org.id]);for(const a of alerts.rows as any[]){const id=createId('prntkt');await runtime.db.query(`INSERT INTO prn_service_tickets(id,organization_id,ticket_number,title,description,priority,printer_id,node_id,source_alert_id,response_due_at,resolution_due_at) VALUES($1,$2,$3,$4,$5,'critical',$6,$7,$8,CURRENT_TIMESTAMP+($9||' minutes')::interval,CURRENT_TIMESTAMP+($10||' minutes')::interval) ON CONFLICT DO NOTHING`,[id,org.id,tnum(id),a.title,a.body,a.entity_type==='printer'?a.entity_id:null,a.entity_type==='node'?a.entity_id:null,a.id,cfg.responseSlaMinutes,cfg.resolutionSlaMinutes]);}}
 await runtime.db.query(`INSERT INTO prn_service_ticket_events(id,organization_id,ticket_id,event_type,notes) SELECT 'prntktev_'||md5(random()::text||clock_timestamp()::text),organization_id,id,'sla_response_breached','Response SLA breached' FROM prn_service_tickets t WHERE t.organization_id=$1 AND t.acknowledged_at IS NULL AND t.response_due_at<CURRENT_TIMESTAMP AND t.status NOT IN ('resolved','closed','cancelled') AND NOT EXISTS(SELECT 1 FROM prn_service_ticket_events e WHERE e.ticket_id=t.id AND e.event_type='sla_response_breached')`,[org.id]);
 await runtime.db.query(`INSERT INTO prn_service_ticket_events(id,organization_id,ticket_id,event_type,notes) SELECT 'prntktev_'||md5(random()::text||clock_timestamp()::text),organization_id,id,'sla_resolution_breached','Resolution SLA breached' FROM prn_service_tickets t WHERE t.organization_id=$1 AND t.resolved_at IS NULL AND t.resolution_due_at<CURRENT_TIMESTAMP AND t.status NOT IN ('resolved','closed','cancelled') AND NOT EXISTS(SELECT 1 FROM prn_service_ticket_events e WHERE e.ticket_id=t.id AND e.event_type='sla_resolution_breached')`,[org.id]);}}
